### ISSUE TITLE
Ideas for a new icon for Planner 2

### ISSUE THREAD

**Issue by alainm23** [alainm23/planify#10]
### The current icon is fine, it just does not look good when the badge is activated.

![icon](https://user-images.githubusercontent.com/33765137/49949305-4e44a700-fec3-11e8-8736-ccfbf9a0eb3d.png)

**Comment by Alecaddd** [comment]
Ah, good call, I'll see what I can do

**Comment by NathanBnm** [comment]
Maybe you can just reverse it ?

**Comment by alainm23** [comment]
As I am rebuilding Planner 2 with a super new UI we could release a new icon too.

![image](https://user-images.githubusercontent.com/33765137/68495885-17842780-021f-11ea-8238-9fa34359fcff.png)
I am attaching an image to see how Planner 2 is looking

**Comment by Alecaddd** [comment]
Let's start some brainstorming on this new icon.
I created a buck on dribbble for inspiration: https://dribbble.com/alecaddd/buckets/1711647-Planner

I personally think this concept might be the right one: https://dribbble.com/shots/3704554-Studyguide-Student-planner
Obviously, updated to reflect the elementary OS style guide and to not create a copycat of this design.

**Comment by alainm23** [comment]
I like the concept of the backpack with a calendar and an agenda, personally I think this is also the right way.

**Comment by Alecaddd** [comment]
All right, I'll see if I can create something this weekend

**Comment by 4jNsY6fCVqZv** [comment]
@Alecaddd Thanks for working on it! I am curious!

**Comment by ghost** [comment]
I'll see what I can do

**Comment by Alecaddd** [comment]
What do you think about this?
![planner2](https://user-images.githubusercontent.com/2527103/71773227-9e4b3d00-2f0e-11ea-90ad-9e96bbc25203.png)

Here's the SVG
[planner2.svg.zip](https://github.com/alainm23/planner/files/4022762/planner2.svg.zip)

**Comment by alainm23** [comment]
Great, this looks pretty cool. thanks for your time.

![image](https://user-images.githubusercontent.com/33765137/71773995-f5640880-2f34-11ea-8330-084985d4e9cd.png)

I only have some suggestions:
-  We could make the icons inside the backpack look bigger. The icon in Plank looks good but the icons inside it can't be noticed.

**Comment by Alecaddd** [comment]
That's only the 48px version, I made that because it's the default size for plank icons.
You'd need to create variations and adapt those for the different sizes as you shouldn't use one size for all.
Unfortunately I don't have time to create the variations, sorry.

**Comment by ghost** [comment]
nicely done, Could I suggest matching the corner radius to that of the terminal, current radius looks more of a moka icon theme? i will play with the file a bit and see what I can do.

**Comment by 4jNsY6fCVqZv** [comment]
@bertob Do you want to support the redesign of the icon?

**Comment by 4jNsY6fCVqZv** [comment]
@bertob Could you imagine supporting the redesign of this icon with your experience?

**Comment by 4jNsY6fCVqZv** [comment]
For me, the icon would be more appealing if the tools were more showcased and the bag less.

**Comment by ghost** [comment]
This is what I had in mind, adds bit of uniqueness to the shape

[planner2a.svg.tar.gz](https://github.com/alainm23/planner/files/4023352/planner2a.svg.tar.gz)

![image](https://user-images.githubusercontent.com/59498682/71779996-71a62c80-2fc5-11ea-84b7-44951077eff6.png)


![image](https://user-images.githubusercontent.com/59498682/71780637-c8176900-2fcd-11ea-8e32-bbf82bf5771a.png)

**Comment by 4jNsY6fCVqZv** [comment]
@inputbim Thank you for your work! How does it look in combination with a badge?
As far as I understood, this was the starting point to rework the design of the current icon.

Does your current design support HDPI resolutions?

Of course it would be exciting to see how the design fits into elementary OS HIG.
https://elementary.io/docs/human-interface-guidelines#iconography

**Comment by ghost** [comment]
@4jNsY6fCVqZv no problem I've done almost nothing though it was @Alecaddd that did the design. I had more of a backpack idea or a simple square calender with a pencil. 

![image](https://user-images.githubusercontent.com/59498682/71780714-ab2f6580-2fce-11ea-9ba9-0d1cffa59add.png)

![image](https://user-images.githubusercontent.com/59498682/71780753-2264f980-2fcf-11ea-92d3-0004bb13f2d9.png)

**Comment by 4jNsY6fCVqZv** [comment]
@inputbim Would you like to share a realization of your thoughts for the new Planner icon with us as well?

In the current version, the badge in the Applications menu does not look very sharp, is that possible? Or is it because of the screenshot?

With the current design in Plank, I notice that the pen is completely hidden as soon as the badge is there.

**Comment by alainm23** [comment]
@inputbim Great job, it definitely looks better.

Personal opinion: 
 - I feel that the color blue is very soft, maybe if we play with #0d52bf instead of #3689e6, I would like to see the result.

![image](https://user-images.githubusercontent.com/33765137/71780840-63401c80-2f95-11ea-8e12-6a2ef51aa7ff.png)
- The design in general is a backpack, but I don't feel it was, maybe if we could add the cover part.

![image](https://user-images.githubusercontent.com/33765137/71780865-c9c53a80-2f95-11ea-8ef2-5576d6a6f944.png)

- Or maybe we could change the focus and make a toolbox, in the same way as Things 3

**Comment by ghost** [comment]
i will do some mock ups, i also like the idea of similar to the "things". 

as for colour i think its important to try use the elementary os colours.

@4jNsY6fCVqZv yes the blur part is due to me doing a quick edit, not pixel perfect, don't have the time for that right now.

![image](https://user-images.githubusercontent.com/59498682/71781276-74108280-2fd5-11ea-9694-ddc63f75f355.png)

take a look at apple. simple and makes sense
![image](https://user-images.githubusercontent.com/59498682/71781319-f731d880-2fd5-11ea-801b-0a45ed4f4f90.png)
 
![image](https://user-images.githubusercontent.com/59498682/71781329-221c2c80-2fd6-11ea-947b-116dd08c5831.png)

**Comment by alainm23** [comment]
I would like to hear the opinion of @Fatih20 The Byte icon designer.

**Comment by ghost** [comment]
thoughts?

![image](https://user-images.githubusercontent.com/59498682/71781813-a7eea680-2fdb-11ea-8ef6-aac0946f8bd1.png)
![image](https://user-images.githubusercontent.com/59498682/71781827-c81e6580-2fdb-11ea-9e99-04ce14b16fc9.png)

**Comment by Fatih20** [comment]
@alainm23 My concern about the backpack one is that the detail wouldn't be recognizable on low monitor PPI. I have tried making icons in the past with small details like that and it's unable to convey the meaning because the reason I stated. Also, it would be a pain to pixel fit it for smaller icon sizes. 

> Your icon should not be overly complicated. Keep in mind that since there are smaller sizes, the elements that make up your icon should be distinguishable when at those sizes.

-Quoted from the official guidelines.

As for the original problem, why not just flip the icon horizontally so that the badge doesn't cover the eyes?

**Comment by alainm23** [comment]
@Fatih20  I understand, the icon does not flip horizontally because the idea of ​​the original design is a "P" by Planner.

**Comment by Fatih20** [comment]
@inputbim  Idea is nice if you get rid of the calendar and the marker. Only need the actual planner book.

**Comment by alainm23** [comment]
What do you think of this icon, is an alternative to things 3.

![image](https://user-images.githubusercontent.com/33765137/71782163-195f3280-2fa5-11ea-922c-6afd497619f4.png)
https://www.deviantart.com/jasonzigrino/art/Things-For-OS-X-Yosemite-497758700

**Comment by Fatih20** [comment]
Seems good. But doesn't really shows the app capabilities in my opinion.

**Comment by ghost** [comment]
@Fatih20 I think it looks to similar to other apps, also that badge hides the "tabs" in the notebook when used on the dock
 
![image](https://user-images.githubusercontent.com/59498682/71782190-1b92b280-2fe0-11ea-8621-943942405bf1.png)

I'm going to do some brainstorming and propose some images, need to look at the app as a holistic entity

**Comment by Fatih20** [comment]
I think it's fine that it hides it.

**Comment by ghost** [comment]
happy @alainm23 ?

![image](https://user-images.githubusercontent.com/59498682/71782957-c018f280-2fe8-11ea-9bb5-f9bcdbaf7b22.png)

**Comment by 4jNsY6fCVqZv** [comment]
I think it would be wonderful if we kept simplicity in mind. Especially when we look at HIG. It would be a pity if the fine details just don't come out and cause uncertainty rather than recognition about the function of the app. Maybe it could also be an umbrella metaphor?

By the way, it would also be great if we could use/combine colors from the elementary color palette.

A simple checklist on a notepad reminds me too much of Agenda or GNOME To Do. And for me this does not correspond to the complexity of projects/project management.  Agenda is more like a shopping list where I cross out what I could get. The variant with the note box seems too close to the elementary Mail/Geary icon.

**Comment by 4jNsY6fCVqZv** [comment]
@inputbim Your last icon looks quite good, I really like it. And it really has a strong resemblance to other apps, as your screenshot shows. I do not know to what extent an indication is to choose another way of implementation? Maybe we can think a little bit more around the corner, but not too far?

**Comment by ghost** [comment]
@4jNsY6fCVqZv "Maybe we can think a little bit more around the corner, but not too far?" don't think I follow, yes like i mentioned earlier it looks to much like other icons, i will propose new icons

**Comment by 4jNsY6fCVqZv** [comment]
@inputbim That was just an impulse. Just like Nimbus. https://appcenter.elementary.io/com.github.danrabbit.nimbus/ A cloud that symbolizes weather and then directly results in a great icon, which can have a high recognition value without many details.

Right now I am also just grateful that so many creative ideas are in the room and people who support the design process. I am looking forward to the wonderful new icon!

**Comment by alainm23** [comment]
Thank you all for your comments and time.  I have been thinking and I think we could use the agenda icon as a base but with some modifications: 
- We could use a color palette based on blue, black and white, the same ones that are in the Planner 2 UI.
- We could add a check on the cover of the agenda implying that this is a task app.
- I think we should keep the color labels, this gives a more natural touch.

**Comment by ghost** [comment]
I think you just described the Agenda app?

![image](https://user-images.githubusercontent.com/59498682/71783954-ab435b80-2ff6-11ea-9dbf-e857de63fd3a.png)

**Comment by ghost** [comment]
Did a quick study of Elementary icon design guidlines and here is my proposal.

Thoughts?

![image](https://user-images.githubusercontent.com/59498682/71784903-9f10cb80-3001-11ea-8daf-288df1691ee9.png)

![image](https://user-images.githubusercontent.com/59498682/71784911-b485f580-3001-11ea-9ba7-aafc2db9af59.png)


![image](https://user-images.githubusercontent.com/59498682/71784908-ad5ee780-3001-11ea-9d4a-fe0b762e622a.png)

**Comment by 4jNsY6fCVqZv** [comment]
@inputbim I kind of miss the planning part.
So in the spirit of Getting Things GNOME! icon https://wiki.gnome.org/Apps/GTG or https://icons8.com/icon/117510/color-hand-drawn
Otherwise it looks like a copy of the Agenda app icon to me.
Planner should also express "Planner" for me, not just "To-do list".

@alainm23 What do you mean by "I think we should keep the color labels, this gives a more natural touch"?

The bigger question for me is also, is the idea of Planner to develop further towards a more complex project management app in the future? Or should it remain with the simplicity of a task list? Both visions can simply be there and are wonderful! But it would help me to decide what the icon should transport.
The question also goes to Alain, of course. What are your dreams and utopias for the future development of your app?

**Comment by alainm23** [comment]
@4jNsY6fCVqZv  I was referring to this little detail:
![image](https://user-images.githubusercontent.com/33765137/71823497-5d197100-3065-11ea-9513-365b02669bf3.png)

Regarding the future of Planner, I see it as a personal application of tasks. However, thanks to Todoist (and in a future update) we can use Planner to work with a team, assign tasks and communication (Premium Todoist User).

But in the more distant future, maybe Planner 3, I think about developing a product with its own synchronization cloud and maybe an app on Android and iOS (I am currently working as a developer of mobile apps).

**Comment by ghost** [comment]
@alainm23  not sure where this leaves us in terms of the icon. can I ask for a clear icon reference and ill propose more elemental :) icon

![image](https://user-images.githubusercontent.com/59498682/71825551-c5d40e00-30a4-11ea-964c-cb44aaf821a0.png)

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 I also like the small detail of the notebook icon variant very much. How can this interact with the base of the Agenda icon?

**Comment by ghost** [comment]
@alainm23 @4jNsY6fCVqZv 
 I am getting quite confused as to what this icon needs ;(
@4jNsY6fCVqZv 
is this what you had in mind?
![image](https://user-images.githubusercontent.com/59498682/71830422-5f082200-30af-11ea-8972-01eb85db3838.png)

just stating the end project of this can still be tweaks in terms of gradients, colours, shading, emboss etc. 

we just need to settle on the actual icon.

sketched images would be better than trying to describe a graphical intention. :)

**Comment by 4jNsY6fCVqZv** [comment]
@inputbim Thanks for your designs! I'm just as confused.

Alain wrote that he'd like to include that detail. And he wrote that the basis could be the Agenda icon. I was also wondering in what direction it should go. That's why I asked how the two can come together.

Because of the description about the future of Planner, I personally feel that an icon that shows more complexity than a simple task list makes still sense.
But I am a user and not a designer.

**Comment by alainm23** [comment]
Sorry for not being clear. The idea that I gave you above is the image number 2.
These are some designs that I have been saving for some time (Planner is about 2 years old)
- I lean towards numbers 2, 5 and 12.

![image](https://user-images.githubusercontent.com/33765137/71832424-e5554180-3078-11ea-9360-b7e6f13e6bd5.png)

**Comment by ghost** [comment]
I like number 2 and 5, lean more to 2 due to 5 being bit to detailed I think for icon, and small scale might loose clarity. 

@alainm23 Can I take number to and elementify it for you? just send the svg if you have.

**Comment by 4jNsY6fCVqZv** [comment]
Goes well with the discussion, I think:
https://blogs.gnome.org/tbernard/2019/12/30/designing-an-icon-for-your-app/

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/72274422-278efd80-35fa-11ea-8fe9-7157aeb31bc8.png)
Apparently [Any.do](https://play.google.com/store/apps/details?id=com.anydo) already thought about it.

![image](https://user-images.githubusercontent.com/33765137/72274334-f31b4180-35f9-11ea-8be2-3c9d2fd19737.png)
Based on the UI, could it be a viable icon?

**Comment by ghost** [comment]
think they look very different, im not sure what the big icon is that you posed? can you send the svg of number 2, so I can implement Elementary style?

**Comment by alainm23** [comment]
Sure.
[diary.svg.zip](https://github.com/alainm23/planner/files/4055597/diary.svg.zip)

**Comment by ghost** [comment]
@alainm23 , thanks I;m very busy lately, will try to sneak it in

**Comment by alainm23** [comment]
@inputbim Don't worry, rather thanks to you 🙌️.

**Comment by alainm23** [comment]
Well folks, I think we just need the icon to launch Planner 2. These are some ideas I've been thinking about.

![image](https://user-images.githubusercontent.com/33765137/72364568-bc5e2d80-36c4-11ea-8a0b-b50a5f0cf5de.png)
![image](https://user-images.githubusercontent.com/33765137/72364598-c7b15900-36c4-11ea-83d9-c1bf8c2d2748.png)

![image](https://user-images.githubusercontent.com/33765137/72364771-07784080-36c5-11ea-95ce-3abe76de92da.png)
![image](https://user-images.githubusercontent.com/33765137/72364781-0f37e500-36c5-11ea-81f6-99c0f3eceef4.png)

**Comment by ghost** [comment]
@alainm23 hold on there, :) I'm working on the icon today

**Comment by ghost** [comment]
@alainm23  

I lost focus... but this works nicely with notification.

![image](https://user-images.githubusercontent.com/59498682/72380653-85b50100-371e-11ea-9253-ba33443714a0.png)

![image](https://user-images.githubusercontent.com/59498682/72380689-9d8c8500-371e-11ea-90c2-35107bec264f.png)

![image](https://user-images.githubusercontent.com/59498682/72380784-ce6cba00-371e-11ea-88a3-aedc8eef4d0b.png)

**Comment by alainm23** [comment]
I like the idea. what do you think of my design?

![image](https://user-images.githubusercontent.com/33765137/72383924-7b790f80-36ea-11ea-925e-7aa31921ce28.png)
![image](https://user-images.githubusercontent.com/33765137/72383970-8cc21c00-36ea-11ea-8b1b-3cf41fb785a0.png)

**Comment by ghost** [comment]
@alainm23 nice, i like it, but might come down to previously discussed, does it resemble what the app does, think its more what people prefer now, I will post on twitter and tag planner and elementary, if you can go rewteet, 

Think it will be best way to close this issue

![image](https://user-images.githubusercontent.com/59498682/72413184-dc025e00-3777-11ea-8593-b314fd50e2ad.png)

**Comment by 4jNsY6fCVqZv** [comment]
@inputbim Hi, I like your latest version, because for me it also expresses the previously discussed planning qualities of this app! 

A few notes:
1. in the comparison with the elementary default apps in Plank your icon doesn't look so sharp in the outlines. Like for example in Settings or Mail. Why is that? And can you fix it?
2. what caused you to insert "2020"? -> Does it simply stand for the release year and calendar in one?
3. do you think the icon is visible from a distance/or how far should it be? Or could it be further simplified without losing quality?

**Comment by alainm23** [comment]
I really like your design, and I think it complies with all the indications mentioned above.  However, I feel that this design is more oriented to a calendar application. It is true that Planner supports calendar events but with very basic functionality.

I like number 1 but I don't know, I feel that something is missing. 

I designed the number 2 taking into account a blueprint (with the intention of planning or designing something) and the image of the rocket with the meaning of a project.

The numbers 4, 5 and 6 are super simple and I believe that they show the basic functionality of Planner.

I tilted at number 6, I believe that design is more detailed and without much complexity. As an example there are many task managers and I think everyone has the same idea. Things 3, Microsoft ToDo, Google Task, etc.

**Comment by ghost** [comment]
Perfect, online it also seemed to be 5 or 6 leaning more to 6. I'm just glad that this issue can be closed :)

**Comment by alainm23** [comment]
Thank you all for your ideas and time. With this problem solved, only a few details are missing before you can launch Planner 2.

**Comment by Bronislas** [comment]
Hi, I was playing around with Inkscape, trying to learn how to use it. I began to modify some of my icons, and I added an edge highlight as recommended here : https://elementary.io/docs/human-interface-guidelines#composition

I thought you may like it.

![Planner16 svg](https://user-images.githubusercontent.com/34268533/78609182-77303e80-7862-11ea-9aa5-e811f2b22e15.png)
![Planner24 svg](https://user-images.githubusercontent.com/34268533/78609183-77c8d500-7862-11ea-9d0b-acdd7168c249.png)
![Planner32 svg](https://user-images.githubusercontent.com/34268533/78609186-78616b80-7862-11ea-8b0b-49e0b0b30c3d.png)
![Planner48 svg](https://user-images.githubusercontent.com/34268533/78609188-78fa0200-7862-11ea-8f94-e1e6315a67ee.png)
![Planner64 svg](https://user-images.githubusercontent.com/34268533/78609193-79929880-7862-11ea-838e-ebd6732dcc3d.png)
![Planner128 svg](https://user-images.githubusercontent.com/34268533/78609196-7a2b2f00-7862-11ea-9533-da7522e8d214.png)

**Comment by alainm23** [comment]
@Bronislas Thank you very much, you could create a PR in this repository to improve the icons.
