### ISSUE TITLE
Add description as comment to Todoist

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#100]
**Describe the solution you'd like**
To keep everything synced, the description of the task should be synced to todoist as a comment

**Describe alternatives you've considered**
There is no alternative at the moment. Descriptions are not synced.

**Additional context**

**Comment by alainm23** [comment]
I was also thinking about this, but I still don't have a clear idea of ​​how to do it.

**Comment by Hedronmx** [comment]
How to do it with the api? or how to do it UI wise?

**Comment by alainm23** [comment]
How to do it in the design.

**Comment by Hedronmx** [comment]
There is no need to design anything, since it should sync to todoist anyways.
You can pull the first comment as the description of every task. And every task should sync the description to the first comment

**Comment by alainm23** [comment]
Of course, that's easy but what happens if the user adds more comments?

**Comment by Hedronmx** [comment]
You can have a icon next to the sub task icon, that shows all the comments in a seperate window. Like in the tags.

Ill do a mock up later today to see if that helps.

**Comment by alainm23** [comment]
I was also thinking about that solution. Also keep in mind that comments are only available to pro account users in Todoist.

**Comment by Hedronmx** [comment]
Oh snap you are right... hmmm is there any other way you can sync just the description of the tasks?

**Comment by alainm23** [comment]
At the moment, I dont have idea.

**Comment by Hedronmx** [comment]
Looking at the pricing, file upload is also just for pro users... :(

Let me think of something... maybe i can come up with something useful

**Comment by alainm23** [comment]
I think this will be impossible to solve at the moment.

**Comment by alainm23** [comment]
I will close this problem because of Todoist API limitations, but I will keep the feature in mind.
