### ISSUE TITLE
[Question] Is version 4.0 released on Flathub a beta release?

### ISSUE THREAD

**Issue by hyuri** [alainm23/planify#1000]
Hi,

I noticed version 4.0 was just released on Flathub.org.

Is it a stable release, or is it a beta release? It doesn't say "beta" on its Flathub page but your comment here seems to imply it is a beta release: https://github.com/alainm23/planify/issues/953#issuecomment-1572459609

**Comment by alainm23** [comment]
Planify is quite stable so far but it is still in Beta version. If you find any bug, don't forget to report it, thanks.

**Comment by hyuri** [comment]
Shouldn't the betas be posted to the flathub-beta repo?

Last time I used Planner (v2), I think a beta (v3) was pushed to the stable channel, corrupted the app's database and me and many others lost all of our tasks.

**Comment by hyuri** [comment]
I think you should at least label it "alpha" or "beta" on Flathub until it's stable. The app is broken and unusable now. I was reporting bugs but it got a bit tiring after so many. Just use the app for a few minutes and you'll see it's impossible.

I got duplicated tasks after checking and unchecking a bunch of them, I got tasks disappearing, I got left or right click sometimes not working on tasks, some buttons not working, plus the ones I already reported, and many more bugs.

If people start using the app without knowing it's unfinished, it's going to hurt its reputation — like the change from v2 to v3 that deleted people's projects and tasks.

It's a really nice app once the bugs get fixed, so I really want it to succeed.
