### ISSUE TITLE
[Bug] Does not respect chosen window buttons placement

### ISSUE THREAD

**Issue by hyuri** [alainm23/planify#1001]
**Describe the bug**
The app does not properly respect the window buttons (close, minimize, maximize) placement setting. When window buttons placement is set to "left", the window buttons are placed on the left side of the right panel, and not on the left side of the whole window.

**To Reproduce**
1. Open Gnome Tweaks
2. Go to 'Window Titlebars'
3. Click on 'Left' on the Placement switch
4. Open Planify
5. Notice how the window title buttons are placed in the wrong spot

**Expected behavior**
When set to "Left", the window buttons should be place to the extreme left of the header bar.

**Screenshots**
![image](https://github.com/alainm23/planify/assets/18584014/1472b24b-b44a-48c1-9bdc-19dc39833a42)

**Desktop (please complete the following information):**
 - OS or DE: Pop!_OS 22.04  /  Gnome 42.5
 - App Version 4.0

**Additional context**
Installed from Flathub

**Comment by alainm23** [comment]
For linhandy there was Hdy.HeaderGroup, but that is not migrated in libadwaita, I will look for a way to solve it, thanks.

**Comment by alainm23** [comment]
This has been fixed, available in the new Planify update.
