### ISSUE TITLE
Tags and/or releases

### ISSUE THREAD

**Issue by Jarodiv** [alainm23/planify#1002]
**Is your feature request related to a problem? Please describe.**
I am privately maintaining a Gentoo e-build for this program (since I am using it myself). For more than a year now, there has been no new release or even just new version tag, making it difficult to impossible to get active when a new version is released (judging by the version tags, the project still is v3.0.7 and judging by the releases it even is just v3.0.0-beta2)

**Describe the solution you'd like**
Please start again to at least tag the commits that are used to create new versions, even if it's just alpha or beta releases. Or any other way that makes it possible to identify which commit is marking a new version.

**Comment by alainm23** [comment]
I'll keep that in mind, thanks for the recommendation. By the way, Planify has been ported to Gtk4 and libadwaita and there is a version on Flathub.

**Comment by jansol** [comment]
Seconding this, there is a [planify package for NixOS](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/office/planify/default.nix) and it could get kept up to date by a semi-automatically (bot makes PRs to bump the version and source hash, someone has to manually approve the PR) if there were github releases or git tags.

**Comment by Jarodiv** [comment]
Just realized that version 4.1.1 has been long ago (apparent commit: adf3629bcacfc9978f6dde5b87eff0278533ab3e). Without version tags it's really difficult to track and to update packages.
