### ISSUE TITLE
Duplicated find dialog

### ISSUE THREAD

**Issue by hyuri** [alainm23/planify#1005]
**Describe the bug**
The find dialog is duplicated. Both when clicking the button and when pressing Ctrl + F.

**To Reproduce**
1. Open the app
2. Click on the magnifier icon, or press Ctrl + F
3. See error

**Expected behavior**
No duplicated dialog.

**Screenshots**
![image](https://github.com/alainm23/planify/assets/18584014/5e5cc0e3-4f85-4b12-bc12-8831c32b8522)

**Desktop (please complete the following information):**
 - OS or DE: Pop!_OS 22.04 Gnome 42.5
 - App Version: 4.0 (on Flathub)

**Additional context**
Fresh new install, no tasks or projects added

**Comment by alainm23** [comment]
I have not been able to reproduce this bug, could you try it again in Planify 4.1?
