### ISSUE TITLE
Improve drag & drop of tasks

### ISSUE THREAD

**Issue by hyuri** [alainm23/planify#1008]
**Is your feature request related to a problem? Please describe.**
Right now, it's very frustrating to drag & drop tasks. We have to drag & drop them on top of another task for it to work, and it often doesn't work or it drops the task below when you wanted to drop it on top or vice-versa.

**Describe the solution you'd like**
Be able to drag & drop:
1. In-between tasks;
2. To the bottom, empty space, to send the task to the end of the list;
3. To the top, to send the task to the top of the list.

In all of the above, it should work both for the whole project, sections, and sub-tasks.

Even better if we get visual feedback, such as a horizontal line indicating where the task will be placed.

**Comment by massenz** [comment]
As described this "sort of" works now, but it's frustratingly inconsistent.
The main issue is when selecting a task to drag and reorder, also opens the panel: this makes placing it accurately in the list extremely frustrating.

Also, it's visually unappealing (and probably unnecessary).

Ideally, when a click-and-hold mouse action is detected, it should *not* open the task's description, and just visually indicated it is ready to be dragged-and-dropped in the list.

I also have the distinct impression there is a bug and when dropping it as the "second topmost" task, it actually gets placed at the top instead, but given the current clumsiness of the visual, it's really hard to actually say for sure.

The UI is gorgeous, minimalist and functional - so fixing the re-ordering of tasks (a pretty fundamental feature of any ToDo app) would be truly awesome.

Many thanks! :heart:

**Comment by alainm23** [comment]
This feature will be available in Planify 4.4.
