### ISSUE TITLE
Add sub-tasks by drag & dropping

### ISSUE THREAD

**Issue by hyuri** [alainm23/planify#1009]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to add existing tasks as sub-tasks of another task, but I can't simply drag & drop it, I have to delete the task and create it again as a sub-task.

**Describe the solution you'd like**
Drag & dropping a Task A onto another Task B to add Task A as a sub-task of Task B.

We should also have visual feedback for that, like a change in cursor, so that we get an indication of what's going to happen.

**Comment by alainm23** [comment]
The new gtk4 drag and drop api limits this kind of features a bit. I will investigate how to make it work, thanks for commenting.

**Comment by alainm23** [comment]
This feature will be available in Planify 4.4.
