### ISSUE TITLE
Task's schedule date not updating until the task is re-opened

### ISSUE THREAD

**Issue by hyuri** [alainm23/planify#1010]
**Describe the bug**
Changing a task's schedule date does not update it in the UI until you close the task and open it again.

**To Reproduce**

A:
1. Add a task;
2. Change schedule date to "Today";
3. Change schedule date to "Tomorrow";
4. See error.

B:
1. Right Click on an existing, closed task;
2. Choose one of the preset dates at the top (Today / Tomorrow), that is different than the current one if set;
3. See how the date does not change in the task until you open the task;

**Expected behavior**
The new date show be displayed as soon as we change the date.

**Screenshots**
![image](https://github.com/alainm23/planify/assets/18584014/5ce2b3d0-c681-4e2e-98ce-5c8db24ccb07)

**Desktop (please complete the following information):**
 - OS or DE: Pop!_OS 22.04 / Gnome 42.5
 - App Version: 4.0 (Flathub)

**Comment by alainm23** [comment]
Have you been able to reproduce this bug in Planify 4.1?
