### ISSUE TITLE
Cant enable Google account - Planify 4.0.1

### ISSUE THREAD

**Issue by oparada1988** [alainm23/planify#1012]
Simple, cant seem to enable Google Taks under account

**To Reproduce**
1. Go to Preference
2. Click on accounts
3. Google Task cannot be enabled

**Expected behavior**
enable google tasks

**Screenshots**
![Screenshot from 2023-06-06 18-04-12](https://github.com/alainm23/planify/assets/4031078/a711af6d-cb01-418f-8b71-9584931d59ad)

**Desktop (please complete the following information):**
 - OS or DE: Ubuntu 22.04.2 LTS - Gnome 42.5
 - Version 4.0.1

Installed the flatpak verions

**Comment by alainm23** [comment]
Synchronization with Google Tasks is still in development.

**Comment by alainm23** [comment]
I am going to close this topic because the synchronization with Google Tasks is not yet available, but it is under development, thanks.

**Comment by alainm23** [comment]
I am going to close this topic because the synchronization with Google Tasks is not yet available, but it is under development, thanks.
