### ISSUE TITLE
Truncated strings on the left pane

### ISSUE THREAD

**Issue by rene-coty** [alainm23/planify#1015]
The translated strings of the 'Inbox', 'Today', 'Sheduled' and 'Labels' cards on the left pane are systematically truncated even when the app window is maximized (see screenshot below - in French):
![Capture d’écran du 2023-06-12 22-13-01](https://github.com/alainm23/planify/assets/95506494/8cbe8290-ca56-4280-adb8-9992bcb48c1c)

**Proposals:**
- The size of these cards should be adaptative (i.e. increased length of the cards) ← might be a good idea as there is enough space on the right to increase the size of the pane
- The text should adjust with a line break (i.e. increased heigth)

**Desktop:**
 - OS: Fedora 38, GNOME 44
 - Version 4.0

**Comment by alainm23** [comment]
It is true that it looks a bit ugly, but Gtk does not offer a Widget that allows you to resize the sidebar and hide it at the same time. Perhaps a quick fix would be to give the option to resize the sidebar as an appearance preference option.

**Comment by alainm23** [comment]
This functionality has been added in the preferences.

![image](https://github.com/alainm23/planify/assets/33765137/983d1f22-7311-45f6-9f15-411708e6553a)
