### ISSUE TITLE
Flatpak says it installed version 4.1, but Planify About window says 4.01

### ISSUE THREAD

**Issue by shvchk** [alainm23/planify#1021]
**Describe the bug**
See title

**To Reproduce**
1. `flatpak install flathub io.github.alainm23.planify`
2. Verify you have v 4.1: `flatpak list --app | grep planify`
3. Run Planify
4. Go to Menu → About Planify
5. See version 4.0.1

**Expected behavior**
Version should be the same: 4.1

**Desktop (please complete the following information):**
 - OS or DE: Ubuntu
 - Version 23.04

**Comment by alainm23** [comment]
Fixed on v4.1.1.
