### ISSUE TITLE
Migration from `planner` to `planify`

### ISSUE THREAD

**Issue by aarondill** [alainm23/planify#1022]
**Is your feature request related to a problem? Please describe.**
On migration from `planner` to `planify`, I was forced to install `sqlitebrowser` to manually copy values from the old database.db to the new one. Copying the file is not viable, as the structure changed between updates, so old tasks must either be hand migrated (which introduces many problems) or completely given up on.

**Describe the solution you'd like**
An option in the settings to import old tasks. Due to implementation details and the flatpak sandbox, this would likely have to invoke `org.freedesktop.portal.FileChooser` and import the values from the chosen `database.db` file.

**Describe alternatives you've considered**
_manually_ copy values from the old file to the new, handling issues as they come. - This puts extra strain on users and should be avoided.

**Comment by alainm23** [comment]
It's something I'm working on, import automatically and if the database file doesn't exist, give the user the option to select it.

Obviously only local tasks would be imported, Todoist or CalDAV have their separate backup systems.

**Comment by alainm23** [comment]
Hi, I am going to disregard this functionality, Planify was released more than 6 months ago and I think I can spend more time on other functionality that Planify requires.
