### ISSUE TITLE
Multiple entries in Gnome Shell Background Apps

### ISSUE THREAD

**Issue by marcinjahn** [alainm23/planify#1023]
**Describe the bug**
The app appears 6 times in Background Apps in Quick Settings of Gnome Shell.

**To Reproduce**
I just enabled background working support in Planify, and closed the app. Right after that, there were no Background Apps in Gnome Shell Quick Settings. However,  some time later, it appeared, with 6 instances of Planify.

**Expected behavior**
I should see just one instance of Planify in Background Apps.
I'd expect to see Planify in Background Apps right after I close the app window.

**Screenshots**
![image](https://github.com/alainm23/planify/assets/10273406/06877759-43af-4d87-8940-5e96a31324a3)

**Desktop (please complete the following information):**
 - OS or DE: Fedora 38, Gnome 44
 - Version: 4.0.1

**Comment by alainm23** [comment]
Could you verify how many instances of Planify were created? check in the following path:

`~/.config/autostart`

![image](https://github.com/alainm23/planify/assets/33765137/446f380b-52db-44c1-b011-45e831c374b0)

You could also check if Planify is running multiple times.
![image](https://github.com/alainm23/planify/assets/33765137/a1eb185f-0741-43c2-a7c0-57734e39be99)

**Comment by alainm23** [comment]
I will close this issue for the time it has been inactive, thank you.
