### ISSUE TITLE
Can't change the view to Board View.

### ISSUE THREAD

**Issue by mkblast** [alainm23/planify#1024]
**Describe the bug**
After creating a new project I tried to change the view to border after adding some sections, but the button is not highlighted to i can't change it.

**To Reproduce**
1. Create an new Project.
2. Add some sections and tasks.
3. Try to change the layout to board view.
4. See that the button is not highlighted and can't be clicked 

**Desktop (please complete the following information):**
 - OS or DE: Fedora 38, Gnome 44
 - Version: 4.0.1

**Additional context**
I don't know if it's a bug or I just don't know how to change the view, regardless please take a look at it.

**Comment by alainm23** [comment]
Sorry, the Board view is not available yet, but it is being developed for Planify 4.2. I will close the issue because the button to switch between views was hidden in v4.1.1.

**Comment by TheWeirdDev** [comment]
Is this included in the 4.2 release? I can't seem to find it.
