### ISSUE TITLE
"Delete Project" button does nothing

### ISSUE THREAD

**Issue by jntdofe** [alainm23/planify#1025]
**Describe the bug**
Clicking on the "Delete Project" button on the top right menu does nothing

**To Reproduce**
1. Open a project
2. Click on the top right three dots menu
3. Click on the "Delete Project" button
4. Nothing happens

**Expected behavior**
The project would be deleted

**Desktop (please complete the following information):**
 - Fedora Silverblue 38, Gnome 44.2, Wayland.
 - Version 4.1 ([4.0.1](https://github.com/alainm23/planify/issues/1021))

**Additional context**
Right clicking on the project and then on "Delete Project" still works

**Comment by alainm23** [comment]
Planify has been updated, have you been able to reproduce the error again

**Comment by alainm23** [comment]
I will close this issue because it has been inactive for some time, if the bug still persists, please report it again.
