### ISSUE TITLE
Conflicts on Weblate

### ISSUE THREAD

**Issue by ryonakano** [alainm23/planify#1031]
**Describe the bug**
There are conflicts on Weblate and translators cannot work on translations of Planify

**To Reproduce**
1. Visit [the Alert page on Weblate](https://hosted.weblate.org/projects/planner/translations/#alerts)
2. See the error about conflicts

**Expected behavior**
Conflicts are resolved and translators can work on translation of Planify on Weblate.
(If it is hard to fix conflicts, maybe you can delete the old planner project on Weblate and re-create it as planify project)

**Screenshots**
The screenshot of the Alert page on Weblate:
![hosted weblate org_projects_planner_translations_](https://github.com/alainm23/planify/assets/26003928/f617bda2-35df-4098-bfc5-4b0db5c062e6)

**Desktop (please complete the following information):**
 - OS or DE: Not relevant
 - Version: Not relevant

**Additional context**
N/A

**Comment by alainm23** [comment]
Hello and thanks for commenting, Planify stopped using weblate for its translations, currently they are done manually with a PR. In any case, I will delete the project to avoid future confusion.

**Comment by ryonakano** [comment]
Yes, it would be helpful to delete the old project to avoid confusion if you won't use Weblate anymore :pray:
