### ISSUE TITLE
Loss of tasks when the application is waiting

### ISSUE THREAD

**Issue by HDInfautre** [alainm23/planify#1032]
Hello
I share this but I don't know the context, it's happened to me 2 times, maybe when trying to move a task/save a task.

What's for sure is that afterwards I entered the same task.
When I do a search, I can see the 2 tasks, but only one job remains visible in list mode.

What's more, I don't see any tasks appear when I click on "show completed tasks" in the configuration!

I don't have the impression that there's a trash can.
is there a tool to clean the database?

Planify 4.1.1

**Comment by HDInfautre** [comment]
Hello
I think I've reproduced the problem.
In a project with a lot of sections and tasks, when I try to move a task into a section with a lot of items or into another selection.
I can't quite pinpoint where I'm leaving the list.
At this point, the application stops responding and I'm forced to close it.
When I reopen it, I can't see the task (and any sub-tasks).
I find it with the search module, but it's invisible!

**Comment by deiiviidas** [comment]
Hello, same happens to me. As i touht at first - what the hell, where are all tasks list, becouse i see online 7 tasks instead of 8. in search i saw there exists one.

I only found a solution: to disable application, and re-enable the app - to start up - then it shows tasks normally located. - and the hidden ones are shown again.

this is due to limited refreshed/updates in tasks, in offline mode when moving tasks from one section, task subtasks to other ones.

**Comment by HDInfautre** [comment]
Hi
I had, by chance, arrived at the same resolution, but I had to kill the task.
But I don't understand what offline means, without internet?
After that, I think it's something that can be improved. No ?

**Comment by alainm23** [comment]
@HDInfautre  If you have Todoist enabled and don't have internet, Planify will save your tasks locally and sync it later.

**Comment by deiiviidas** [comment]
@alainm23 would be great if there was a button, near Project name, reload button, which you press -and then all tasks should unload/reload in project, to show normally.

also good solution is that, you after drag/n/drop tasks between, tasks,which have subtasks, and more sub sub tasks, that tasks should reload/load again, to show latest shanges, becouse from parent when you move out - then theyre gone, best solution would be reload only target tasks, to show - all of them + dragged in from parent, if not possible - then do hot reload - like the reload button - which reloads all tasks at once in specified project.

**Comment by deiiviidas** [comment]
i have some dumb habit, to randomly press on tasks, and those tasks ussualy fade out :D like - you thinking wtf where my task gone - otherwise, the application is very good and do really good job, im already using it and it works great.

**Comment by deiiviidas** [comment]
> Hi I had, by chance, arrived at the same resolution, but I had to kill the task. But I don't understand what offline means, without internet? After that, I think it's something that can be improved. No ?

Offline means without any other integrations, that means locally - which is why i decided to use this app.
As @alainm23 mentioned, **Planify will save your tasks locally**

**Comment by HDInfautre** [comment]
Hello
Well, that's several tasks I've lost at once :-( , or even the tasks next to them!
It's really the annoying BUG par excellence, because it makes me feel insecure.
Especially as it's random! and sometimes I recover the information by killing the planify application (ubunut 23.04).

I think I can give a description :
1. I make a movement of the mouse towards the top left (less problem if my movement remains horizontal)
2. the box becomes greyed out and then I have the choice of waiting or closing the application
3. waiting is useless, closing the application means I lose the task and others (perhaps open?)

**Comment by deiiviidas** [comment]
> Hello Well, that's several tasks I've lost at once :-( , or even the tasks next to them! It's really the annoying BUG par excellence, because it makes me feel insecure. Especially as it's random! and sometimes I recover the information by killing the planify application (ubunut 23.04).
> 
> I think I can give a description :
> 
>     1. I make a movement of the mouse towards the top left (less problem if my movement remains horizontal)
> 
>     2. the box becomes greyed out and then I have the choice of waiting or closing the application
> 
>     3. waiting is useless, closing the application means I lose the task and others (perhaps open?)

Hi bro, please update from version 3 to version 4 and there is no bugs.

**Comment by deiiviidas** [comment]
There is two versions: planify and planner. who is v4 one is v3.
@HDInfautre

**Comment by HDInfautre** [comment]
Hello
Thanks for the information :-)
But I thought I'd said it, I'm already on 4.1.1  and I've got this very annoying bug which has also been labelled as such I think?

**Comment by deiiviidas** [comment]
i see, youre getting crashes - sorry for you.

**Comment by HDInfautre** [comment]
Hello
I'm very embarrassed., but I lost a whole task tree and these sub-tasks, wanting to copy / paste after blocking the application.
Could this be repaired?
Or is it lost?

I imagine you are on vacation.
Can you prioritize this task problem when you can?
In the meantime, I have to operate differently on most of my projects

Thanks in advance
_Sorry for my bad English, which often uses the translator._

**Comment by alainm23** [comment]
Hi, sorry for the late reply, I have resumed Planify development, I am concerned about your problem. do you use Todoist or just local tasks?

**Comment by HDInfautre** [comment]
Hi
Thanks for picking up. For now I'm back on todoist.
I'm waiting to see the evolution of planify for local tasks with appimage ? if 1 day?

**Comment by alainm23** [comment]
I will close this issue because it has been inactive for some time, if the bug still persists, please report it again.

**Comment by alainm23** [comment]
Hi @HDInfautre , Planify does not yet support AppImage (and it is not planned in the short term), regarding local tasks Planify handles it correctly.
