### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by HDInfautre** [alainm23/planify#1034]
Hello

1/ Project: when I bookmark a project, can I automatically remove it from the list of projects below?
2/ Task: I can't see where bookmarked tasks appear?

**Comment by alainm23** [comment]
1. When you select a project as a favorite, you have the option to deselect it

[Grabación de pantalla desde 2023-07-08 03-41-04.webm](https://github.com/alainm23/planify/assets/33765137/3cf49f77-cf1c-4ec0-94e2-50b0531e0d26)

2. To see your pinned tasks, find the Pinboard view in Quick Find.

![image](https://github.com/alainm23/planify/assets/33765137/8f5e67ce-4856-4771-8599-5717d5ee1b55)

If it is not very clear, I will add it as indications in the tutorial project.

**Comment by HDInfautre** [comment]
Hi
I misspoke
**Project:** this means not having a project in both the favorite and the complete list.
By placing it in favorite, you can remove it from the complete list.
This is interesting for me, who currently has about twenty projects, but needs to move some from my old everdo task application. Of course, this request would be obsolete if there were sub-projects :-)

**favorite tasks:**
This seems really complicated to me, I was expecting to have a list of favorite tasks (or shortcut like ) above the list of favorite projects. 
![planify_favori](https://github.com/alainm23/planify/assets/6817936/d7033e3a-ca34-46a5-979c-f02990e50bec)

Is this clearer?
Is it necessary to create another request so that it's no longer closed?
