### ISSUE TITLE
Spinner is displayed incorrectly

### ISSUE THREAD

**Issue by latenightdef** [alainm23/planify#1035]
**Describe the bug**
The spinner displayed when doing operations is rotating counter-clockwise instead of clockwise

**To Reproduce**
1. Go to any Todoist project
2. Add a new task
3. Press the save button
4. See the spinner on counter-clockwise

**Expected behavior**
The spinner should display in clockwise and not counter-clockwise

**Screenshots**
[Screencast from 2023-07-04 15-13-37.webm](https://github.com/alainm23/planify/assets/64822291/3ebbab47-c159-46fa-aad7-f0092749998c)

**Desktop (please complete the following information):**
 - OS or DE: GNOME
 - Version 44.2

**Additional context**
This also happens when loading the Todoist login page

**Comment by alainm23** [comment]
Thanks for submitting the issue, this has been resolved, available in the new update, best regards.
