### ISSUE TITLE
Problem displaying tasks [today] and [planned].

### ISSUE THREAD

**Issue by HDInfautre** [alainm23/planify#1037]
Hello
**Describe the bug**
In [today] , I'm missing tasks that got stuck in [planned].
The counter shows 3 when the display shows 2 tasks
I'm missing 3 tasks markedq (tomorrow) in [scheduled] which should have been switched this morning to [today].

in [planned], there are spots indicating July 5 and tomorrow

**Expected behavior [Today] displays all spots that have been defined for today's date.
[forecast] displays all spots defined for today's date
The next day (July 5), I should only see dates with (July 5) in them.

**Screenshots
see screenshot

Desktop (please fill in the following information)** : 
Ubuntu 23.04
Planifiy 4.1.1
![Capture d’écran du 2023-07-04 10-28-15](https://github.com/alainm23/planify/assets/6817936/5c3a480e-c330-4e54-b222-94ef9059971f)
![Capture d’écran du 2023-07-04 10-27-31](https://github.com/alainm23/planify/assets/6817936/ce888314-b900-497e-9a16-ae3f291cf3db)

**Comment by HDInfautre** [comment]
Hi
It works again when you close the application (see the kill)
See https://github.com/alainm23/planify/issues/1032

Then I noticed that at startup, despite the "launch at startup" setting, I can't access the tasks on my ubuntu 23.04.

**Comment by alainm23** [comment]
The algorithm for calculating the change of day has been improved and is now available in the new update.
