### ISSUE TITLE
Can't enter credentials / manjaro Kernel 5.15 / installed via flatpack

### ISSUE THREAD

**Issue by MAWSpitau** [alainm23/planify#1038]
**Describe the bug**
I would like to log in to tosoist, but I just get an blank screen.

**To Reproduce**
1. Go to Burger-Menu → Prefenrences
2. Klick on accounts.
3. activate todoist
6. Get a blank page

**Expected behavior**
Able to login - somehow.

**Screenshots**
![grafik](https://github.com/alainm23/planify/assets/539371/f80101fd-9d48-44f1-a814-20a28e344377)

**Desktop (please complete the following information):**
 - OS or DE: Gnome

**Comment by alainm23** [comment]
You could start Planify from the terminal and be able to see the error log when trying to log in to Todoist. attentive to your response, thank you very much.

`flatpak run --devel io.github.alainm23.planify`

**Comment by MAWSpitau** [comment]
Thanks for helping. 

```
$ flatpak run --devel io.github.alainm23.planify
Fehler: runtime/org.gnome.Sdk/x86_64/44 ist nicht installiert
```
Not that much log :(

I tried:

```
$ io.github.alainm23.planify
Name: Inbox
Backend: local
Name: Meet Planify
Backend: local

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 14:47:59.804: gtk_widget_add_css_class: assertion 'css_class[0] != '\0'' failed

** (io.github.alainm23.planify:2): CRITICAL **: 14:47:59.805: widgets_labels_header_init: assertion 'self != NULL' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 14:47:59.830: gtk_stack_remove: assertion 'GTK_IS_WIDGET (child)' failed

(io.github.alainm23.planify:2): GLib-GObject-CRITICAL **: 14:47:59.833: g_signal_handler_disconnect: assertion 'handler_id > 0' failed

(io.github.alainm23.planify:2): GLib-GObject-CRITICAL **: 14:47:59.833: g_signal_handler_disconnect: assertion 'handler_id > 0' failed

** (io.github.alainm23.planify:2): WARNING **: 14:48:29.746: TodoistOAuth.vala:153: Loading uri 'https://todoist.com/oauth/authorize?client_id=b0dd7d3714314b1dbbdab9ee03b6b432&scope=data:read_write,data:delete,project:delete&state=QRomymzx6sHBTtZTrqu7hOcBNVOA69iN6etj' failed, error : Timeout was reached

(io.github.alainm23.planify:2): Gtk-WARNING **: 14:48:29.747: Child name 'error_view' not found in GtkStack
```
I saw, the time out and took the URL in my normal browser. That gives me: 
![image](https://github.com/alainm23/planify/assets/539371/49cefe3f-df5f-4cc0-acfa-646a3d0cbc9f)

Klicking there on "zustimmen" (accept) - closes the todoist page and loads my last opend page, but nothing happens in planify

**Comment by MAWSpitau** [comment]
No more ideas, what I could try?

**Comment by MAWSpitau** [comment]
Still can't use planify :(

**Comment by alainm23** [comment]
Hello and sorry for the late reply, maybe this solution could help you, please let me know.
https://github.com/alainm23/planify/issues/1069

**Comment by alainm23** [comment]
I will close this issue, if the problem still persists you can reopen it.
