### ISSUE TITLE
no way of logging into google to sync tasks

### ISSUE THREAD

**Issue by mohsen-w-elsisi** [alainm23/planify#1039]
hello, 

checking twitter posts and github issues, i know that Gtasks support landed in late 2020, but i see no way of logging in to my account nor entering a caldav url. and the account is not auto-detected via gnome's online accounts

system info:
- app installed through flathub (not the beta)
- gnome desktop enviornment 44
- fedora distribution

**Comment by alainm23** [comment]
Native support for Google Tasks is under development, currently not available.

**Comment by mohsen-w-elsisi** [comment]
K, thx for developing this awesome app 😃
