### ISSUE TITLE
Add sync for Todoist labels

### ISSUE THREAD

**Issue by Appeltabak** [alainm23/planify#104]
**Is your feature request related to a problem? Please describe.**
I saw that Planner that planner supports adding labels to items, but it doesn't sync them when using Todoist. I'm aware that this is a premium feature of Todoist.

**Describe the solution you'd like**
Full synchronisation of labels when someone has Todoist Premium.

**Describe alternatives you've considered**
Standard labels, but they don't sync...

**Comment by t3mujin** [comment]
@alainm23 is the limitation only related with not having a Todoist subscription? I have one so I could do some testing. Or development, but have zero experience with Vala and gtk3.

**Comment by alainm23** [comment]
@t3mujin Don't worry, Todoist gave me a Premium membership until 2030 😅️ This feature takes a while to arrive but it is in my plans, thanks for your interest.

**Comment by t3mujin** [comment]
Alright! Feel free to reach out if needed 🙂

**Comment by mend0za** [comment]
+1 for such improvement. I hope Todoist provide API support for labels?

**Comment by alainm23** [comment]
Happy to announce that this feature will be available in an upcoming Planner update but only for premium Todoist users.

**Comment by alainm23** [comment]
You will probably need to resynchronize your Todoist account to load all the label into your tasks.

https://user-images.githubusercontent.com/33765137/107238343-bcc71600-69f5-11eb-8083-a311425f1a36.mp4

**Comment by ghost** [comment]
Hi, this does not work for me. I do not even see the sync labels option in Planner.
![Sync labels?](https://i.imgur.com/BwVh32V.png)
Planner version 2.6.9.

Todoist Premium Subscription

Any ideas?

**Comment by bigforcegun** [comment]
Same issue like https://github.com/alainm23/planner/issues/104#issuecomment-809203585

I have paid account on todoist, and there are no labels from my account, only initial labels

I tried:
- re-sync with buttons
- remove and add todoist account
- `rm -rf ~/.var/app/com.github.alainm23.planner/data/com.github.alainm23.planner` and setup sync again

Any ideas?
