### ISSUE TITLE
Add task icon for each section in projects

### ISSUE THREAD

**Issue by iamkartiksingh-K** [alainm23/planify#1041]
There should be a add task button for each section.  

If we have multiple sections in a project then the new task is created using the '+' button at the top and then we have to drag the task to the suitable section.

Every section must have a add task button along the heading of the section.

**Comment by alainm23** [comment]
This button is available


[Grabación de pantalla desde 2023-07-08 03-25-50.webm](https://github.com/alainm23/planify/assets/33765137/7ddaee13-476b-48ef-b4b9-2953704dea4e)

**Comment by iamkartiksingh-K** [comment]
Yes it's available, sorry I didn't wrote it clearly but that's just too many clicks to add a task. Suppose I want to add 5 tasks in a section then I will have to click 10 times to add all the task. Instead add task button should be added on the left of three dots menu button.

**Comment by alainm23** [comment]
Sorry, I did not understand the request, I will keep it in mind as an improvement for the next release.

**Comment by iamkartiksingh-K** [comment]
By the way, I love this app.

**Comment by alainm23** [comment]
Added the + button in the header of the sections, making its use faster. Thank you, wait for the next release.
