### ISSUE TITLE
Issue with title buttons on the left + request

### ISSUE THREAD

**Issue by stpnwf** [alainm23/planify#1042]
**Describe the bug**
Planify won't respect global title buttons.

**To Reproduce**
1. Set title buttons to the Left side
2. Enable minimize and maximize button.

**Expected behavior**
I would expect application to respect title button behavior and be displayed on the Left side, along with Maximize and Minimize buttons, as visible in the other applications in the screenshot below.

**Screenshots**
![Untitled](https://github.com/alainm23/planify/assets/81482539/7aa2de17-2e5c-4010-a14a-ee5ffcbde330)

**Desktop (please complete the following information):**
 - OS or DE: Fedora 38 (Gnome 44.2)
 - Planify Version: 4.1.1 (installed via Flathub)

**Additional request**
Also, I am using Gradience to change Gnome colors; regarding the sidebar, could there be an option in settings (other than Dark and Dark Blue) that uses a color variable that is used in Gradience such as `card_bg_color`,  `view_bg_color`,  `popover_bg_color`, etc? That way, Planify would work with Gradience perfectly.

It may be planned, but I would also suggest that the Gnome icons be used instead of the apple ones.

**Comment by alainm23** [comment]
This problem will be solved by migrating to libadwaita 1.4, wait for the next release.
