### ISSUE TITLE
Background color not changing in dark mode

### ISSUE THREAD

**Issue by Fr4nk1inCs** [alainm23/planify#1047]
**Describe the bug**
I found some widgets does not change background color when I enabled dark mode, such as:
- Main window
- Many dialogs
  - Preferences
  - Shortcuts
  - About
  - New Project
  - Edit Project
  - Project Description
  - When?
- Header of Quick Find dialog

Planify is built from source code (commit [`488afdad5803fb5edf36079785dd91d0dce7cdb8`](https://github.com/alainm23/planify/commit/488afdad5803fb5edf36079785dd91d0dce7cdb8)).

**To Reproduce**
1. Go to 'Preferences/Appearance'
2. Click on 'Dark mode'

**Expected behavior**
The background color should be changed with the dark mode enabled.

**Screenshots**
Here are some examples of inproper background color.

- <details>
    <summary>Main window</summary>

    ![main-window](https://github.com/alainm23/planify/assets/74861140/5f4d60c6-f26e-4edf-b474-52161cdde9fa)
  </details>
- <details>
    <summary>Preferences</summary>

    ![preferences](https://github.com/alainm23/planify/assets/74861140/d3f372c9-492e-4505-be83-5c6db39541e5)
  </details>
- <details>
    <summary>About</summary>

    ![about](https://github.com/alainm23/planify/assets/74861140/c18be616-4b7c-4f26-9d16-f3ab5155a1a3)
  </details>
- <details>
    <summary>New Project</summary>

    ![new-project](https://github.com/alainm23/planify/assets/74861140/c884932c-96a6-4d60-8c87-6aed5ce2f084)
  </details>
- <details>
    <summary>Edit Project</summary>

    ![image](https://github.com/alainm23/planify/assets/74861140/f086bf2b-86c1-46ed-9dc2-b64da621c54a)
  </details>
- <details>
    <summary>Quick Find</summary>

    ![image](https://github.com/alainm23/planify/assets/74861140/c9df682c-1b4b-4a4c-86b2-54cd4a322664)
  </details>

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - DE: Hyprland
 - Planify: Version 4.1.1, built from source code, commit `488afdad5803fb5edf36079785dd91d0dce7cdb8`

**Additional context**
After reading some source code, I found that there's a color `window_bg_color` defined in `data/resources/stylesheet/variables.css`. However, the color is not used in any other css file or vala code (except `update_theme()` in both `src/Util.vala` and `quick-add/Util.vala`).

**Comment by DejanGegic** [comment]
Same problem here. KDE Arch, KDE system theme does not affect the issue. I'm willing to provide all the logs and cooperate.

**Comment by hcur** [comment]
Having the same issue on NixOS with both GNOME and Hyprland.

**Comment by OlivierPineau-qc** [comment]
Writing to follow this thread, I have the same problem in dark theme on Arch linux, KDE plasma with Breeze theme.

**Comment by Jarodiv** [comment]
Same issue here with KDE Plasma and Breeze theme. Build from source (release 4.1) on Gentoo.

Edit: Persists with 4.1.1

**Comment by alainm23** [comment]
@Fr4nk1inCs  Thank you for using Planify. We recommend installing the application from the official source (Flathub)
.

**Comment by ghost** [comment]
Hello!

I'd like to request this issue to be re-opened. I had the problem described by installing Planify from nixpkgs in NixOS, and after reading 

> @Fr4nk1inCs Thank you for using Planify. We recommend installing the application from the official source (Flathub) .

installed as a flatpak as well, but the issue remains even when running the flatpak version.
