### ISSUE TITLE
Add support for Encryption/Password Protection

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#105]
**Is your feature request related to a problem? Please describe.**
Sometimes a very protected environment is needed for smaller or larger projects. A database that lies unprotected on a hard disk is not so nice. Many people don't have full hard disk encryption either.

**Describe the solution you'd like**
The ability to protect my Planner database or individual projects using GPG, e.g. by supporting Open Smart Cards like Nitrokey, could allow security conscious people to protect Planner 2 with a two-factor authentication. This is especially exciting for professional work contexts. And also for all the private things I want to protect. Of course, this option should always be optional.

**Comment by alainm23** [comment]
Maybe a solution could be to use a master key before entering Planner?

**Comment by 4jNsY6fCVqZv** [comment]
Thank you for your feedback and for the openness towards my idea!

> Maybe a solution could be to use a master key before entering Planner?

That would be an idea! Are you familiar with the password manager KeePassXC?
It also has a Welcome Screen, which would be good in the sense of elementary HIG.
Reference https://elementary.io/docs/human-interface-guidelines section "Welcome Screen".

You can see the KeePassXC example in the first screenshot https://keepassxc.org/screenshots/ here.

If I choose to open an existing database, I will be asked via FileChooser to select it. Then I currently have the option to select different methods to unlock the database:
- Password
- Key File
- Challenge Response

Perhaps this could be a good start to think about what and how database encryption & decryption support can be realized for Planner. Probably it just needs a first design, doesn't it?!

There does not have to be all authentication types in the first version. This can develop slowly. I would already be very happy with the possibility of strong encryption using password/passphrase and 2FA support for Open Smart Cards!

**Comment by ghost** [comment]
This feature in my opinion should be optional.

**Comment by 4jNsY6fCVqZv** [comment]
My idea is that people have the choice of encrypting their Planner database (or even individual projects or single tasks) when creating it or not. It might be fine to explain to people what situations exist where sensitivity in handling project data makes sense. For example, especially in work contexts or when teams share a common database.

Can you think of other use cases where this feature makes sense (for you personally)?

**Comment by unsungNovelty** [comment]
[Joplin](joplinapp.org/) which is a note taking application does encryption which could also be a good way to encrypt offline data maybe?

There is some reading you can do about it in :point_right: https://joplinapp.org/spec/#encryption-service.

Hope this helps.

**Comment by 4jNsY6fCVqZv** [comment]
What would be suitable labels for this issue?
What are the next steps towards implementation?

**Comment by antimech** [comment]
> Thank you for your feedback and for the openness towards my idea!
> 
> > Maybe a solution could be to use a master key before entering Planner?
> 
> That would be an idea! Are you familiar with the password manager KeePassXC?
> It also has a Welcome Screen, which would be good in the sense of elementary HIG.
> Reference https://elementary.io/docs/human-interface-guidelines section "Welcome Screen".
> 
> You can see the KeePassXC example in the first screenshot https://keepassxc.org/screenshots/ here.
> 
> If I choose to open an existing database, I will be asked via FileChooser to select it. Then I currently have the option to select different methods to unlock the database:
> 
>     * Password
> 
>     * Key File
> 
>     * Challenge Response
> 
> 
> Perhaps this could be a good start to think about what and how database encryption & decryption support can be realized for Planner. Probably it just needs a first design, doesn't it?!
> 
> There does not have to be all authentication types in the first version. This can develop slowly. I would already be very happy with the possibility of strong encryption using password/passphrase and 2FA support for Open Smart Cards!

Having options similar to KeePassXC would be cool.

**Comment by martinord** [comment]
Regarding the implementation of this feature, I would firstly protect the **local database** with a master password as @alainm23 suggests.

> Maybe a solution could be to use a master key before entering Planner?

After this, it may be interesting developing a public key encryption schema, but not urgent. However I think the first step would be to encrypt at least with a master key the local database, which I find really interesting and really necessary.

**Comment by 4jNsY6fCVqZv** [comment]
> After this, it may be interesting developing a public key encryption schema, but not urgent. However I think the first step would be to encrypt at least with a master key the local database, which I find really interesting and really necessary.

@martinord Could you imagine working on a design for it?

**Comment by ProfessorCode212** [comment]
I would also love to see this feature implemented. It would be even better if there was an option to sync the database to a custom location so people can have an encrypted copy of it in their cloud storage service of choice.

**Comment by BeatLink** [comment]
I know for a fact that @alainm23 is working on CalDAV synchronization at the moment, so this may not be implemented quite as yet, But perhaps a solution could be implemented into the release after the next?

**Comment by alainm23** [comment]
It's an interesting feature, I haven't had a lot of practice with some encryption algorithm but I like the idea.

**Comment by alainm23** [comment]
There are no plans to develop this feature at the moment.
