### ISSUE TITLE
Support a mode to conform to libadwaita style appearance

### ISSUE THREAD

**Issue by crab2313** [alainm23/planify#1050]
**Is your feature request related to a problem? Please describe.**
Planify doesn't look the same to other applications based on libadwaita. For example, evince, gnome-control-center, etc..

**Describe the solution you'd like**
Remove the custom CSS styling related to widget color.

**Describe alternatives you've considered**
 Support a mode to conform to libadwaita style appearance.

**Additional context**
https://gitlab.gnome.org/GNOME/libadwaita/-/issues/53

**Comment by Julian4711** [comment]
Good idea. It would be nice if there was a version that didn't give away the elementary origin.

**Comment by bragefuglseth** [comment]
Tbh this should just be the default - the two «modes» would be way to similar to be worth maintaining.

**Comment by alainm23** [comment]
Hi guys and thanks for the suggestion, I have tried to customize the Planify style to the minimum and use the libadwaita widgets for almost everything, likewise, we are applying to Gnome Circle and I have been sent several design fixes, I am sure this will improve with time. I will close this issue as it does not lead to a real problem.
