### ISSUE TITLE
Inbox issues when transferring db from one machine to another

### ISSUE THREAD

**Issue by Sharkitty** [alainm23/planify#1051]
**Describe the bug**
After transferring the `database.db` file from one machine to another (through my own means, I don't use `todoist`), the inbox, today and schedule sections started to misbehave on the receiving machine:
- UI doesn't always show up on the main panel.
- It is impossible to add tasks from sections mentioned above, only directly inside projects.
- No functionality seems to be lost in projects.
- Tasks that are outside of a project in the sending machine (but are in the inbox) won't show up in the inbox on the receiving machine (They still show up in labels if they have been labeled).
- Quick add doesn't work shows up but won't add the created task.
- When sending the database back to the initial sending machine, no functionality is lost.

**To Reproduce**
- Create some tasks in the inbox on an installation of planify.
- Install planify on another machine and transfer the database to the second machine (Should be reproducible in VMs).

**Expected behavior**
Successful transfer between both machines without causing issues on the receiving end.

**Desktop (please complete the following information):**
- Sending machine: Fedora-KDE 38 (KDE Plasma 5.27.6)
- Receiving machine: OpenSUSE Tumbleweed (XFCE 4.18)

**Additional context**
Both machines use planify as a flatpak, and have the same version.

**Comment by alainm23** [comment]
Sorry for the inconvenience, a backup and migration system is being developed for this type of scenario. I will close the issue because it is a case that has already been reported.
