### ISSUE TITLE
No task display today and Planify no longer responds

### ISSUE THREAD

**Issue by HDInfautre** [alainm23/planify#1057]
Hello
Every morning, I close/reopen the Planify app to use the day's events.
![Capture d’écran du 2023-09-01 07-38-51](https://github.com/alainm23/planify/assets/6817936/45cbba25-fe72-4baa-8076-e6829c2122a9)

This morning, it's no longer possible. 
If I close it, it doesn't improve
If I wait, it increases resources until the computer is blogged (Ubuntu 23.04)
![Capture d’écran du 2023-09-01 07-38-06](https://github.com/alainm23/planify/assets/6817936/f0e83255-feeb-486a-9aaa-0ffe7d10939d)
Project pages are accessible

a) I think it has to do with the fact that the tasks with these children are suddenly closed and I can't find them when I reopen the application:
https://github.com/alainm23/planify/issues/1032

When I close before it locks up the computer
![Capture d’écran du 2023-09-01 07-42-53](https://github.com/alainm23/planify/assets/6817936/666242ca-44a4-44c5-b6da-303e76bd2094)

b) I can't figure out how to permanently delete tasks with "done" ticked.

Probably database corruption, 
How can I fix it?
Planify 4.1.1

**Comment by HDInfautre** [comment]
Hi
Still the same problem of not being able to open the tasks for "today".
I think the database is corrupted.
What to do
Thanks

**Comment by HDInfautre** [comment]
HI
I'm always embarrassed because I have to use another tasks management tool as a complement, but I prefer planify :-)
is there a way around it, hoping for a real solution soon?
1/ I export the data
2/ delete the application
3/ I import the data
Who can help me?
Regards

**Comment by alainm23** [comment]
Planify has been updated, have you been able to reproduce the error again? If so, try to kill the process and if it doesn't work, you could delete and restore the Planify database.

`flatpak run io.github.alainm23.planify -r`

Sorry for the inconvenience, a backup system is being developed for this random case of errors.
