### ISSUE TITLE
Tutorial project mentions integrations that aren't ready yet

### ISSUE THREAD

**Issue by lofidevops** [alainm23/planify#1059]
**Describe the bug**
The tutorial project mentions the system calendar, Google Tasks and CalDAV, but these integrations are not ready. The instructions given don't lead anywhere.

**To Reproduce**
1. Follow the "Meet Planify" project step-by-step
2. Follow the instructions under "Tune Your Setup": "Show your calendar events" and "Enable synchronization with third-party service"

**Expected behavior**
Instructions should be actionable. If they aren't actionable they should not be presented.

**Screenshots**

```
Show your calendar events

You can display your system's calendar events in Planify. Go to 'Preferences' 🡒 Calendar Events to turn ir on.
```

```
Enable synchronization with third-party service.

Planify not only creates tasks locally, it can also synchronize your Todoist, Google Tasks and CalDAV accounts. Go to 'Preferences' 🡒 'Accounts'.
```

**Desktop (please complete the following information):**
 - OS or DE: Ubuntu 22.04 LTS, GNOME 42.9
 - Version: 4.1.1 (installed from Flathub)

**Comment by IllyaYalovyy** [comment]
I see the same behavior. Am I missing anything. I need google tasks integration. Thank you!

**Comment by lofidevops** [comment]
It's a bit confusing, but there currently isn't any integration with Google Tasks aka Gtasks.

There's an existing feature request at https://github.com/alainm23/planify/issues/949

**Comment by IllyaYalovyy** [comment]
Thank you for the update.

**Comment by alainm23** [comment]
This functionality is under development, the text will be corrected, thank you.
