### ISSUE TITLE
Support of project planning in Kanban style

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#106]
Question for discussion: Do you think it makes sense to think project management with Planner 2 differently and to therefore extend it?
So in the sense of https://github.com/nextcloud/deck?

**Comment by alainm23** [comment]
Planner could be a project planning with the help of Todoist. However, this was created as a personal task management tool, similar to projects like Things.

**Comment by 4jNsY6fCVqZv** [comment]
Things?

Do you think Kanban view is not so good for personal project planning? Or is it rather a question of which organizational method I prefer as a user?

As far as I know Todoist does not have a Kanban view and unfortunately is not FLOSS compatible.

I would rather see a potential Kanban view as an alternative way of displaying projects in Planner. For example, I have a project and can already choose in the welcome screen whether I want to create it as a normal list or as a Kanban board. It might also be possible to switch between the different views. And possibly even translate a Todoist project list into a Kanban view for the users, if they can work better that way.

p.s. Would it be possible to add a team component to the app at some point?
That would be a new issue, of course, wouldn't it? ;-) 
Then there would also be the question of how I can share tasks with others. For example, using a contractor file, which my colleague can then import, or in the form of a shared database to which several users can have access. Locally in the network or remote.

**Comment by alainm23** [comment]
I think I know what you mean, I saw this same behavior in other project managers. Of course this feature can be added but for the first release not yet.

**Comment by 4jNsY6fCVqZv** [comment]
Which project managers are you thinking of?

> Of course this feature can be added but for the first release not yet.

Very nice!

Related to the part on team collaboration using Planner: Should I open a separate issue for it? Or was your last statement about team collaboration?

**Comment by amar-laksh** [comment]
+1 for kanban please!

**Comment by notanimposter** [comment]
This has suddenly become extra relevant now that Todoist has a Kanban-style view of its own.

**Comment by reesericci** [comment]
Also, I would like to see integration with Nextcloud Deck if this gets implemented. 

For me, Kanban is crucial, and I am currently using Asana and would like to switch to a more local solution even if it syncs with Todoist. I can't use this app without Kanban support.

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/101976051-8a748480-3c0f-11eb-9a20-c892b68d9488.png)
