### ISSUE TITLE
Integration with Todoist

### ISSUE THREAD

**Issue by Mnemonic775** [alainm23/planify#1063]
I feel like this should be easy, but I've browsed basically every button, icon, and menu in Planner and I cannot for the life of me figure out how to start the integration process with todoist on my phone. Am I missing something or is the button / feature not present?

**Comment by rebokdev** [comment]
It is in preferences > accounts

![image](https://github.com/alainm23/planify/assets/68105407/f6bb8b99-217b-4acd-a92a-8910376e1637)
