### ISSUE TITLE
ctrl+backspace should delete the entire previous word (English)

### ISSUE THREAD

**Issue by jansol** [alainm23/planify#1065]
**Describe the bug**
In task title / description fields (likely other text fields as well), pressing ctrl+backspace only deletes the previous character.

**Expected behavior**
The entire word before the cursor gets deleted, like in other applications. (not sure what the usual behavior is for other languages/writing systems)

Interestingly enough, just moving the cursor with the arrow keys while holding down ctrl *does* jump between words rather than individual letters. Selecting text with ctrl+shift+arrows also works as expected.

**Desktop (please complete the following information):**
 - OS or DE: NixOS unstable / KDE Plasma 5.27.8
 - Version: 4.1.1

**Comment by alainm23** [comment]
It is an interesting feature, I just discovered it, the behavior is the default one offered by Gtlk and it works in Planify. Maybe you should check the configuration of your computer. I will close this issue because it has been open for so long.
