### ISSUE TITLE
Crash if trying to open "Today" or "Scheduled"

### ISSUE THREAD

**Issue by Tondar** [alainm23/planify#1066]
**Describe the bug**
Planner crashes if I try to click on either "Today" or "Scheduled" in the top left corner. "Inbox" and "Pinboard" in contrast work just fine.

**To Reproduce**
1. Open the application
2. Click on the either the red "Scheduled" or the yellow "Today" in the top left corner
3. Planner crashes

**Expected behavior**
The corresponding task list is shown

**Desktop (please complete the following information):**
Ubuntu 23.10

**Additional context**
It does produce the following message:
Bail out! ERROR:../src/Services/CalDAV/Util.vala:134:cal_dav_util_ical_to_date_time_local: assertion failed: (!date.is_null_time ())

The whole Output from running the application:

$ flatpak run com.github.alainm23.planner

Gtk-Message: 12:43:32.560: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:43:32.561: Failed to load module "canberra-gtk-module"

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:32.572: gee_abstract_map_get_entries: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:32.572: gee_iterable_iterator: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:32.572: gee_iterator_next: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.020: gee_map_set: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.022: gee_map_set: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.024: gee_map_set: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.026: gee_map_set: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.028: gee_map_set: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.030: gee_map_set: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.032: gee_map_set: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.036: gee_map_set: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.038: gee_map_set: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.040: gee_map_set: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.042: gee_map_set: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.043: gee_map_set: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.045: gee_map_set: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.047: gee_map_set: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.047: services_database_get_items_by_scheduled: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.047: gee_abstract_collection_get_size: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:33.050: objects_color_get_hexadecimal: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.630: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.630: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.630: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.630: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.630: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.630: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.631: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.631: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.631: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.631: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.632: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.632: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.632: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.632: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.633: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.633: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.633: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.633: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.633: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.633: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.634: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.634: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.634: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.634: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.634: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.634: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.635: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.635: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.635: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.635: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.636: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.636: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.636: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.636: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.636: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.636: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.636: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.636: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.636: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.636: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.637: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.637: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.637: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.637: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.638: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.638: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.638: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.638: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.639: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.639: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.639: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.639: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.639: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.639: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.640: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.640: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.640: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.640: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.640: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.640: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.641: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.641: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.641: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.641: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.642: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.642: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.642: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.642: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.642: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.642: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.642: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.642: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.642: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.642: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.643: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.643: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.643: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.643: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.644: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.644: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.644: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.644: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.644: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.644: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.644: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.645: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.645: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.645: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.645: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.645: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.646: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.646: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.646: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.646: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.647: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.647: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.647: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.647: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.647: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.648: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.648: services_database_get_items_by_date: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.648: gee_abstract_collection_get_size: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.739: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.739: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.739: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.739: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.739: invalid (NULL) pointer instance

(com.github.alainm23.planner:2): GLib-GObject-CRITICAL **: 12:43:47.739: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.739: gee_abstract_map_get_values: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.739: gee_iterable_iterator: assertion 'self != NULL' failed

** (com.github.alainm23.planner:2): CRITICAL **: 12:43:47.739: gee_iterator_next: assertion 'self != NULL' failed

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.741: invalid cast from 'ObjectsScheduled' to 'ObjectsProject'

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 12:43:47.741: invalid cast from 'ObjectsScheduled' to 'ObjectsProject'
**
ERROR:../src/Services/CalDAV/Util.vala:134:cal_dav_util_ical_to_date_time_local: assertion failed: (!date.is_null_time ())
Bail out! ERROR:../src/Services/CalDAV/Util.vala:134:cal_dav_util_ical_to_date_time_local: assertion failed: (!date.is_null_time ())

**Comment by Tondar** [comment]
Just seen that this has already been reported

**Comment by ktmohammedsulaim** [comment]
+1

**Comment by ktmohammedsulaim** [comment]
Kindly check this console output:
```
** (io.github.alainm23.planify:2): CRITICAL **: 16:40:29.725: Settings.vala:95: Could not connect: No such file or directory

** (io.github.alainm23.planify:2): CRITICAL **: 16:40:29.725: Settings.vala:136: Could not connect: No such file or directory

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:40:29.991: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:40:30.238: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:40:30.239: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:40:30.240: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify:2): Json-CRITICAL **: 16:40:31.225: json_object_get_string_member: assertion 'node != NULL' failed

(io.github.alainm23.planify:2): GLib-CRITICAL **: 16:40:31.225: g_variant_new_string: assertion 'string != NULL' failed

(io.github.alainm23.planify:2): GLib-CRITICAL **: 16:40:31.225: g_variant_ref_sink: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): GLib-GIO-CRITICAL **: 16:40:31.225: g_settings_schema_key_type_check: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): GLib-CRITICAL **: 16:40:31.225: g_variant_get_type_string: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): GLib-GIO-CRITICAL **: 16:40:31.225: g_settings_set_value: key 'todoist-sync-token' in 'io.github.alainm23.planify' expects type 's', but a GVariant of type '(null)' was given

(io.github.alainm23.planify:2): GLib-CRITICAL **: 16:40:31.225: g_variant_unref: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:41:54.140: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:41:54.165: objects_color_get_hexadecimal: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:41:54.165: util_set_widget_color: assertion 'color != NULL' failed
```
