### ISSUE TITLE
Dark Mode doesn't work as intended

### ISSUE THREAD

**Issue by demonkillerr** [alainm23/planify#1067]
**Describe the bug**
Dark theme doesn't work as intended, or shown in the screenshot. Most of the wordings are just not readable, and the main window is still in light mode.

**To Reproduce**
1. Install planify from AUR

**Expected behavior**
Dark theme should work as shown in project screenshot

**Screenshots**
![Screenshot from 2023-11-23 02-18-04](https://github.com/alainm23/planify/assets/55846983/ee3e5e63-7946-4265-8263-627398555887)

**Desktop (please complete the following information):**
 - Arch Linux, Gnome Desktop with Orchis Dark Theme
 - Gnome Shell - 45.1

**Additional context**
NA

**Comment by Daz-3ux** [comment]
Same Issue, Install from AUR

Desktop:
Arch Linux, 
DE: KDE Plasma 5.27.9,
Theme: [Plasma], Breeze [GTK2/3]

**Comment by alainm23** [comment]
@demonkillerr Thank you for using Planify. We recommend installing the application from the official source (Flathub) and not from third parties that are not under maintenance.
