### ISSUE TITLE
Can't input todoist credentials 

### ISSUE THREAD

**Issue by ThePiklOfTime** [alainm23/planify#1069]
**Describe the bug**
When trying to add account credentials to Todoist, nothing except input credentials appears on screen. Tested both white and dark mode. There seems so be some sort of invisible input fields on the page, but it's hard to guess exactly what should go where. 

**To Reproduce**
1. install on flathub
2. Try to connect 

**Expected behavior**
I would expect to be able input credentials. 

**Screenshots**
![planifyBug?](https://github.com/alainm23/planify/assets/60430708/fe3ef2bf-bf0d-458e-95c1-5c4bd2be605b)

**Desktop (please complete the following information):**
-Fedora kde  39 with nvidia drivers and a wayland session. 
- version 4.1.1 from flathub

Edit
This is the terminal output when trying to authorize Todoist
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 475x529: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 475x529: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 475x529: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1

**Comment by velvetzhero** [comment]
Yes, happens to me to...Just installed your app yesterday.
The screen has a clickable item but cannot be seen ( if you hoover with your mouse on the screen ..) ...
A real bummer !

**Comment by alainm23** [comment]
@velvetzhero Thanks for the comment, what exactly do you mean? I can't understand your problem.

**Comment by ThePiklOfTime** [comment]
Update:
For anyone who finds themselves  stuck in a similar situation with the proprietary Nvidia drivers, run the app with:
WEBKIT_DISABLE_COMPOSITING_MODE=1 flatpak run io.github.alainm23.planify

This happens because flatpak doesn't ship nvidia proprietary drivers, and gtk webkit tries to render using the gpu. This way you can sign in.

**Comment by ThePiklOfTime** [comment]
As for fixing this for other users, there is the option of launching the systems default browser to sing in (requires work), or forcing that option for Nvidia drivers/everyone. Or just displaying that workaround somewhere, for example on the flathub store page where users might find it a bit easier.

**Comment by alainm23** [comment]
@ThePiklOfTime  Thank you very much for your solution, I currently do not have a computer that uses NVIDIA, but I am adding a line of code that I think could solve it. I hope to release it in the next release.

![image](https://github.com/alainm23/planify/assets/33765137/e7481da1-0a97-469a-a53a-17937b84b1c5)

**Comment by velvetzhero** [comment]
Thank you @ThePiklOfTime ! 
I am on an NVidia too/Ubuntu 22.04..

Before:
![image](https://github.com/alainm23/planify/assets/3206393/16443f83-3435-40fc-97c8-78a0c5bd7147)

After:
![image](https://github.com/alainm23/planify/assets/3206393/b3bf0719-29b2-4750-b4be-3c45de6d9bca)

**Comment by ThePiklOfTime** [comment]
You're all welcome. 
I don't know that much about flatpaks and gtkwebview, so I don't know if this could also be fixed by adding Nvidia drivers as a dependency to the flatpak. However from what I've heard, it seems like gtkwebview doesn't enjoy Nvidia drivers very much, so it's possible even that wouldn't fix this. I tried building the project from source but I couldn't get all dependencies resolved. So this issue might or might not be present for native installs.

**Comment by alainm23** [comment]
@ThePiklOfTime Planify 4.2 has been released, could you help me to validate if the bug is still available? I look forward to your answer, thank you very much.

**Comment by ThePiklOfTime** [comment]
I wanted to test this, so I logged of of todoist, and haven't been able to get log back in since for some reason. It's just stuck on this?
![image](https://github.com/alainm23/planify/assets/60430708/ba0c6504-954a-4f20-83a5-01fe3d5ded74)

**Comment by ThePiklOfTime** [comment]
It does seem like something is wrong on my side, since this seems happen even with 4.1.1. I just get this in the console
flatpak-spawn: Invalid byte sequence in conversion input
Try "flatpak-spawn --help" for more information.

**Comment by alainm23** [comment]
Hi, I'm not sure what might be going on, have you tried to remove and reinstall Planify from Flathub?

**Comment by ThePiklOfTime** [comment]
Yeah I tried for example reverting to 4.1.1 which did work previesly, totally removing the app from kde discovery and reinstalling, but none of this worked. I then enabled debug messages, and there is this:
DEBUG: 17:20:37.610: Todoist.vala:1067: {"error":"Invalid format for Authentication header","error_code":412,"error_extra":{"access_type":"none","event_id":"xxx","retry_after":2},"error_tag":"AUTH_INVALID_AUTHENTICATION_HEADER","http_code":403}
Other than that there are no clear errors. Is it possible that it somehow thinks it still has the authentication header even after reinstall?

**Comment by alainm23** [comment]
I am not sure what it can be, please try to run this command, it will reset Planify. 
Sorry for the inconvenience, I hope this can help.

`flatpak run io.github.alainm23.planify -r`

**Comment by ThePiklOfTime** [comment]
Sadly that did not work.

**Comment by alainm23** [comment]
It seems to be a problem with Todoist (I did the test with three different accounts), could you please remove the Planify integration from Todoist and try again, I look forward to your reply. thank you.

https://app.todoist.com/app/settings/integrations/installed

![image](https://github.com/alainm23/planify/assets/33765137/98bf976a-1ee6-44b9-a2c9-2bb5ed9ab518)

**Comment by ThePiklOfTime** [comment]
Yeah it has firmly decided to not let me progress past that loading stage. I mean I might switch my distro to nobara 39 whenever that comes out, which might fix this too. It's not the end of the world if I can't figure this out. If you want, I can send you the txt file that G_MESSAGES_DEBUG=all flatpak run io.github.alainm23.planify >> "planify.txt" spits out. All 1100 lines :)

**Comment by velvetzhero** [comment]
I apologize in advance if this is not related, but I saw your last comment, and I did not know there is such an integration with `planify` ..I've looked it up on my account, but I got `planner` instead..No `planify`. 

![image](https://github.com/alainm23/planify/assets/3206393/6e020439-fbd5-49b2-89c7-8763b778fd44)

Again, please discard completely if this is irrelevant for the discussion ..Just trying to help.

**Comment by alainm23** [comment]
@velvetzhero Thanks, I have to update it.

**Comment by alainm23** [comment]
I will close this issue, if the problem still persists you can reopen it.

**Comment by ThePiklOfTime** [comment]
I can now confirm that this is working fine even with nvidia gpus. I don't know what fixed it, but it's working just fine now. I don't know why I had the infinite loading screen before. Thank you!
