### ISSUE TITLE
Couldn't input Todoist credentials (Different from 1069)

### ISSUE THREAD

**Issue by justresisting** [alainm23/planify#1070]
**Describe the bug**
This bug is different from [1069](https://github.com/alainm23/planify/issues/1069). Luckily it is caused by design, not code. 

There is [a problem in Debian](https://unix.stackexchange.com/questions/628155/newly-launched-program-windows-not-on-top) where some of the windows can open behind the active window. I had Gnome Tweaks set to "Attach Model Dialogue" and the window that opened to enter the Todoist credentials fell behind the window where I could choose to integrate Todoist and Planify. 

I didn't see the credentials window and with attached modal dialogue I couldn't move that to see the window below. 

I suggest setting the credential window larger so that if this happens to others they would be able to see it behind the modal dialogue and click the title bar and grab it without having to turn off attached modal dialogues in Gnome Tweaks like I had to.  

This isn't a high priority bug. Just wanted to be helpful in case anyone else ran into this issue.

Great project, thanks for your hard work!  

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Accounts'
3. Click on 'Synchronize with your Todoist Account'
4. Credentials popped up behind the 'Accounts' modal dialogue. 

**Expected behavior**
Credentials should have popped up in front. 

**Screenshots**
I added my credentials before I thought to take screenshots, sorry!

**Desktop (please complete the following information):**
 - Debian 12
 - Gnome 43.9
 - X11

**Additional context**
This is caused by a bug in Debian and may not affect that many people. This is a great project though and I would hate to have anyone's first impressions be affected by a bug that isn't even caused by Planify.

**Comment by justresisting** [comment]
Forgot to add..

Downloaded from Flatpak.

**Comment by alainm23** [comment]
Thanks for reporting the bug, it seems to be a Debian bug, but to fix it, it would be to open the OAuth window as a subscreen inside the preferences instead of opening another modal. this way you would still navigate inside the preferences.
