### ISSUE TITLE
Schedule Time's Hour not changing on increment or decrement hour as well as entered hour number

### ISSUE THREAD

**Issue by golamrabbiazad** [alainm23/planify#1073]
**To Reproduce**
1. Go to Inbox
2. Click on a specific task
3. Click on Schedule
4. Choose a date
5. Click the :heavy_plus_sign: button
6. set an hour or increment or decrement hour
7. It does not change the hour and stays at 12. Because of this issue AM / PM is not set correctly.

**Screenshots**

![Screenshot from 2023-12-12 03-11-18](https://github.com/alainm23/planify/assets/35021384/dd57a36c-9069-439f-8f20-2d1cac9d0262)

**Desktop:**
 - OS or DE: Ubuntu 23.10 x86_64
 - Version: 4.2.1

**Comment by alainm23** [comment]
Thank you for reporting it, I am checking it.
