### ISSUE TITLE
When clicking save while creating the task, the task card closes and then opens up on its own.

### ISSUE THREAD

**Issue by iamkartiksingh-K** [alainm23/planify#1076]
**To Reproduce**
1. Go to 'Inbox'
2. Click on '+ button'
3. Now save the task using the "save" button.
4. The task card will close and will open up again.

[Screencast from 2023-12-15 20-48-39.webm](https://github.com/alainm23/planify/assets/62024947/fe21dd4f-44f3-4433-810e-55fbb6c2f2e3)

**Desktop (please complete the following information):**
 - gnome45

**Comment by alainm23** [comment]
Thank you very much for reporting it
