### ISSUE TITLE
Font Size is too small

### ISSUE THREAD

**Issue by mostafaahnaw** [alainm23/planify#1078]
**Is your feature request related to a problem? Please describe.**
I can't change the font size of the app

**Describe the solution you'd like**
A way to change the font size and UI size so it fit well on big screens

Here's a screen shot for previewing the problem

![Screenshot from 2023-12-16 20-20-30](https://github.com/alainm23/planify/assets/63565792/231cee6f-ed9a-4f89-9e47-aaadf1c58fda)

**Comment by alainm23** [comment]
Hi, I see you are using Planner, sorry but Planner is no longer supported. Instead you can use [Planify](https://flathub.org/apps/io.github.alainm23.planify) which was completely rewritten in Gtk4 and libadawaita (And the text problem was also fixed) Thanks.
