### ISSUE TITLE
If I open a task card in one view then it's opening in every other view

### ISSUE THREAD

**Issue by iamkartiksingh-K** [alainm23/planify#1081]
**Describe the bug**
When I open a task card in one view let's say Inbox then this card will also open if it is present in Today view.

**To Reproduce**
1. Go to 'Inbox'
2. click on a task card that is present in multiple views, for example, if a task is scheduled for tomorrow then click on that task in  
Inbox which will open it.
4. Open scheduled view
5. You will see the task is also open in that view. Also if you close that task it will not be reflected in the Inbox.

**Expected behavior**
If I am opening a task in one view it should not open in other views.

[Screencast from 2023-12-18 23-26-50.webm](https://github.com/alainm23/planify/assets/62024947/8ef7ab76-709e-426a-82e2-e3d22cf44acc)

**Desktop (please complete the following information):**
 - Gnome 45
 - fedora 39

**Additional context**

**Comment by alainm23** [comment]
I will take it into account, thank you for reporting it.

**Comment by alainm23** [comment]
This feature will be available in Planify 4.4.
