### ISSUE TITLE
Moving subtasks breaks the parent task

### ISSUE THREAD

**Issue by Raiden0456** [alainm23/planify#1087]
**Describe the bug**
When trying to move subtasks inside of the parent task, notify crashes and erases the task, but it is still present in project task counter, syncing with todoist doesn't bring back the task. Backup restore "helps" to restore the structure. 

**To Reproduce**
1. Go to any project
2. Click and hold subtask
3. Drag it anywhere inside of the parent task

**Expected behavior**
Reordering subtasks

**Screencast**
[Screencast from 2023-12-21 14-43-28.webm](https://github.com/alainm23/planify/assets/41489691/2451b2fd-fa61-46f4-b5bb-25824260a180)

**Desktop:**
 - Fedora Linux 39 (Workstation Edition)
 - GNOME: 45.2
 - Linux kernel: Linux 6.6.6-200.fc39.x86_64

**Comment by alainm23** [comment]
I am sorry, I am aware of the mistake and I ask you not to do it again. I am working on a fix for Planify 4.4 that will improve the way of sorting and adding parent tasks. Thank you.
