### ISSUE TITLE
Planify crashes when deleting projects (io.github.alainm23.planify killed by SIGABRT)

### ISSUE THREAD

**Issue by Fenimoure** [alainm23/planify#1089]
# Steps to recreate
In order to recreate the bug, you will need to have a projects with tasks in it. 
1. Open Planify
2. In the left side panel, right click on a project you want to delete
3. In the opened context menu click option "Delete project"
4. The program crashes due to a SIGABRT signal

# Useful information
Application version: 4.2.1 (flatpak)
OS: Fedora Linux 39 (Workstation Edition) x86_64
Kernel: 6.6.7-200.fc39.x86_64
DE: GNOME 45.2
WM: X11

**Comment by Fenimoure** [comment]
#1025 seems to be related

**Comment by Fenimoure** [comment]
The problem also persists in 4.3.2

**Comment by alainm23** [comment]
Sorry, I have not been able to reproduce the error, is there anything else you have done, anything special?

**Comment by Fenimoure** [comment]
Try using Cyrillic for the project and task names. The problem seems to appear then.

Here's a string for you to copy: назва проєкту

Hope that helps.

**Comment by alainm23** [comment]
That's quite useful, the error is because of some strange characters that GLib doesn't identify and breaks the app.

**Comment by timdenholm** [comment]
Encountered the same issue on a fresh install of 4.5 (Flatpak). I simply deleted the introductory project from the sidebar context menu and the application crashed due to a SIGABRT signal.

Application version: 4.5 (Flatpak)
OS: Fedora Linux 39 (Workstation Edition) x86_64
Kernel: 6.7.3-200.fc39.x86_64
DE: GNOME 45.3
WM: Wayland

**Comment by alainm23** [comment]
I am reviewing it, I was also able to reproduce it.
