### ISSUE TITLE
Should Planner 2 use or offer the standard color palette of elementary OS?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#109]
Reference https://elementary.io/de/brand
The variety of this colour palette is unfortunately very limited.
What is the planning status/actual status of Planner 2 in this context?

**Comment by Hedronmx** [comment]
I also love color, would love to see more of it

**Comment by alainm23** [comment]
I think the same but I did this for [Todoist support](https://developer.todoist.com/sync/v8/#colors) Maybe what we can do is change the colors and adapt them to the official elementary palette.

**Comment by alainm23** [comment]
This looks like this with the official elementary palette

![image](https://user-images.githubusercontent.com/33765137/70724364-77f80000-1cc8-11ea-9a43-a050995ae270.png)

**Comment by 4jNsY6fCVqZv** [comment]
- How did you come to this collection?
Todoist has according to your link 20 colors, the color spectrum of the elementary palette completely 60 or 10 colors. In your screenshot I see only 20 colors for both.
- Are the colors currently hard-coded? Would it be possible to display them in a correct color gradient if you want to pursue the idea that all colors are presented in a common selection?
- How do you think it would look if different palettes were integrated into the widget and the users could choose which palette they want to use? So instead of combining them in a common selection. If other services are integrated later, it would be possible for each service to have its own default color palette.

**Comment by alainm23** [comment]
- I tried to find similar colors in the elementary palette.

- Correct, the colors are drawn with CSS inside a Gtk.Grid, I only use a background but if possible use a grandiant. You can send a PR with these improvements to see how it looks.

- I like idea, but do you think this is necessary? Planner currently only uses the color for the progress widget and tags.

**Comment by 4jNsY6fCVqZv** [comment]
> You can send a PR with these improvements to see how it looks.

I'd love to, but my programming skills aren't ready yet.

> I like idea, but do you think this is necessary?

What exactly do you like about my idea?

I'm sure it's not absolutely necessary. There are always other ways to solve something.
When I think of my idea of developing Planner step by step towards an optional integration of different services, it might at least fit well. https://github.com/alainm23/planner/issues/97

Then users who have activated the respective integrations via switch in the settings could select the standard labels & standard colors of the respective service in the corresponding menus/lists/icons. Or discover new ones. This means that you would never see all of them, but only the ones you need or want.

>  Planner currently only uses the color for the progress widget and tags.

Do you see any limitation in that? For me, these are also the areas where I, as a user, would like to see colors in order to be able to distinguish between items and tasks and projects. How do you see this?

**Comment by ghost** [comment]
I think offer the whole spectrum of elementary colour. so have the main colours, then selecting one shows the accents

![image](https://user-images.githubusercontent.com/59498682/71807962-3c591780-3075-11ea-9253-b05a95ddea28.png)

**Comment by alainm23** [comment]
I'm going to close this issue since it seems to be a topic of unfinished conversation.

**Comment by 4jNsY6fCVqZv** [comment]
Wouldn't it be useful to discuss the topic further, especially since it is not yet finished?
If the issue is closed, the possible discussion about its contents will disappear, won't it?
