### ISSUE TITLE
reactivating a completed task creates duplicates in the active session

### ISSUE THREAD

**Issue by KeyLawd** [alainm23/planify#1091]
**Describe the bug**
I reactivated a completed task and it did reactivate, albeit while creating two versions of the task : one still with the completed task and one in the ongoing task, also while doing a few duplicates of others ongoing tasks. It seems to only be a display problem, as restarting the app made the duplicates disappear

**To Reproduce**
1. Create a task
2. Complete it
3. Reactivate it
4. There is now two versions, one in completed and one in ongoing. 

The task should move from completed to ongoing instead of duplicating

**Screenshots**

**Desktop (please complete the following information):**
 - Fedora 39
 - Gnome 45.2

**Comment by alainm23** [comment]
Sorry, I have not been able to reproduce the error, is there anything else you have done, anything special?
