### ISSUE TITLE
Move collapse/expand sidebar button

### ISSUE THREAD

**Issue by amwnag** [alainm23/planify#1095]
**Is your feature request related to a problem? Please describe.**
The position of the toggle sidebar button changes based on whether the sidebar is currently open or not. It would be much more handy if the position stayed the same for both views. If I wanted to open the sidebar again after closing it, I would need to move my mouse over to the new position rather than simply clicking again

**Describe the solution you'd like**
![planner](https://github.com/alainm23/planify/assets/86573349/4d0be297-cc9e-4024-81ae-b64f2034e355)

Cheers. Thank you for the work so far, as this is the most well made to-do list for GNU/Linux

**Comment by alainm23** [comment]
Hi and thanks for using Planify. regarding your request, it's an interesting question. i always had the doubt whether to put the expand button inside the sidebar or the project view. We could follow the same way as other apps like Todoist or ClickUp and keep the button in the sidebar.

**Comment by amwnag** [comment]
As another thought, I also like the way default GNOME file browser Nautilus deals with the sidebar. 

When in full size view, the sidebar is always visible. It is automatically hidden when the window is resized horizontally and made narrower. The toggle sidebar button on this view slides it into view temporarily.

What are your thoughts?

**Comment by alainm23** [comment]
I like it much better, I have to check how to make it work, thanks.
