### ISSUE TITLE
Is CalDAV support implemented ?

### ISSUE THREAD

**Issue by damionx7** [alainm23/planify#1096]
Thanks for this great application. I have long searched for an application for linux that syncs with caldav todo and has a UI like planify. I read github issues and can see that caldav tasks support was mentioned in many issues including #555 but when I installed version 4.3.2 from flathub, i only see Todoist implementation.

Can you please confirm if CalDAV support is added or is hidden somewhere ? Thank you for your effors.

**Comment by alainm23** [comment]
Hi, I already talked about CalDAV support [here](https://github.com/alainm23/planify/issues/1049#issuecomment-1849960447), for now I will close this problem as it is a duplicate, thanks

**Comment by alainm23** [comment]
dupl
