### ISSUE TITLE
Escape key to close project description pop-up

### ISSUE THREAD

**Issue by amwnag** [alainm23/planify#1097]
**Is your feature request related to a problem? Please describe.**
By muscle memory, I sometimes click on 'add a description' to add a task rather than the blue plus button. I usually then hit the escape key to close the pop-up, but the only way to close it is using the x in the corner.

**Describe the solution you'd like**
Similar to the pop-up for adding a task, it would be nice to be able to close the project description pop-up with a keypress (esc) as well.

**Comment by alainm23** [comment]
I think it will no longer be necessary, for the new version of Planify I have changed the description to an editable field.
