### ISSUE TITLE
Wrong month variable used

### ISSUE THREAD

**Issue by Mejans** [alainm23/planify#1099]
Hello,
on the view "Scheduled" there is a list of months after the abbreviated day of the week (might be a good idea to write the full name?).
This month list is not correct for languages that use two forms, one for the name of the month and when it's a date.
Occitan and Catalan for example put a « de » in front of the month name, and « d' » if the month start with a vowel in the case of a date, and nothing when it's only the name of the month.
See « Correct Date Formats in Inflected Languages » in this blog article: http://lingonborough.com/glibc-2-28-new-and-updated-locales/

Planify should use %OB and not %B in this case.

**Comment by alainm23** [comment]
I will take it into account as an improvement, thank you very much.
