### ISSUE TITLE
Cannot Install dependencies libecal1.2-dev

### ISSUE THREAD

**Issue by goldcoders** [alainm23/planify#110]
Hi I just need this last dependency so i can compile the code but im having trouble

```
╰>>> sudo apt install libecal1.2-dev 
Reading package lists... Done 
Building dependency tree 
Reading state information... Done 
Package libecal1.2-dev is not available, but is referred to by another package. 
This may mean that the package is missing, has been obsoleted, or 
is only available from another source 
However the following packages replace it: 
  libecal2.0-dev:i386 libecal2.0-dev 
E: Package 'libecal1.2-dev' has no installation candidate 
```

im running  Ubuntu 19.04 ,what do i need to do to use the older version 
thanks

**Comment by 4jNsY6fCVqZv** [comment]
Should already be there. If you use the default package sources. libecal2.0-dev is only available starting with Ubuntu 19.10.
https://packages.ubuntu.com/search?suite=disco&searchon=names&keywords=libecal

@alainm23  In this context perhaps also relevant for Planner? https://github.com/elementary/calendar/issues/404

**Comment by alainm23** [comment]
@goldcoders  Sorry libecal 1.2-dev is not available in ubuntu 19.04 and I developed Planner in elementary OS Hera (ubuntu 18.04) . I could not tell you how to run it. 

@4jNsY6fCVqZv I'll keep that in mind, thank you very much.

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 Why should libecal 1.2-dev not be available in Ubuntu 19.04?
https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=libecal
Up to and including 19.04 the package should be available.
@goldcoders Are you sure you are not already using Ubuntu 19.10? Because there libecal1.2-dev is actually no longer available.

**Comment by alainm23** [comment]
I could not tell you why, now I do not have ubuntu 19.04 to try it.

**Comment by 4jNsY6fCVqZv** [comment]
Neither do I. My hint was simply the one that you can port to libecal-2.0 in the future if this makes sense ;-)

**Comment by alainm23** [comment]
Hello friends, I will close this problem because Planner will be distributed in elementary OS AppCenter and for users of other distributions through Flathub so this error should not appear.

**Comment by alainm23** [comment]
@goldcoders Hey friend if you are using ubuntu and want to try Planner, you can build it using flatpak
https://github.com/alainm23/planner/tree/master/build-aux/flatpak

```
flatpak-builder --install repo com.github.alainm23.planner.json --force-clean --user
flatpak run com.github.alainm23.planner
```

**Comment by 01AutoMonkey** [comment]
@alainm23 
```
flatpak-builder --install repo com.github.alainm23.planner.json --force-clean --user
```
On Ubuntu 19.10, the command above gives me:
```
error: org.gnome.Sdk/x86_64/3.34 not installed
Failed to init: Unable to find sdk org.gnome.Sdk version 3.34
```

**Comment by alainm23** [comment]
Yes. you need to install the dependencies to be able to build
`flatpak install flathub org.gnome.Sdk/x86_64/3.34`

Or you can build using Gnome Builder, this downloads everything automatically.

**Comment by 01AutoMonkey** [comment]
![img0](https://user-images.githubusercontent.com/6819983/71628945-a34c7b80-2bf2-11ea-945e-905ddfab2bd2.jpg)

Up and running!

```
sudo apt install flatpak-builder
flatpak install flathub org.gnome.Sdk/x86_64/3.34
flatpak install flathub org.gnome.Platform/x86_64/3.34
flatpak install flathub io.elementary.BaseApp/x86_64/juno-19.08

flatpak-builder --install repo com.github.alainm23.planner.json --force-clean --user
```
