### ISSUE TITLE
Better appdata screenshots

### ISSUE THREAD

**Issue by bertob** [alainm23/planify#1100]
The current screenshots are not following the new [guidelines](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/) in a few minor ways:
- The window size is a bit larger than the recommended maximum (1000x700 pixels)
- The window controls are not the platform default (close-only)

This is becoming more important due to a new [curation initiative](https://docs.flathub.org/blog/quality-moderation) :)

**Comment by alainm23** [comment]
I will keep it in mind for this next release, thank you,

**Comment by bertob** [comment]
Thanks! The new screenshots fix the issues above, but unfortunately the first one (which is the one used on banners) is almost empty, which doesn't look great on featured banners:

![image](https://github.com/alainm23/planify/assets/1908896/96bbc882-212f-4165-9f0b-ff681efd6f9f)

Something like screenshot 4 would be better, since it looks more interesting visually and shows off more of the app's features.

**Comment by alainm23** [comment]
@bertob  Haha, I already do

**Comment by alainm23** [comment]
I will use this
![screenshot-01](https://github.com/alainm23/planify/assets/33765137/4b2d490c-bba5-4f7f-ba33-0ee089415daa)
