### ISSUE TITLE
Add option to set a recurrent due date or reminder for each task (e.g. "due every Thursday").

### ISSUE THREAD

**Issue by SJSJr626** [alainm23/planify#1105]
I have tasks that are due weekly. I would be great if Planner would be able to remind of them each week and allow me to check them off.

**Comment by alainm23** [comment]
Currently you can create a reminder for a specific date and time, but this is not recurring. I also saw that other apps have the option to remind you of the completion of the task 30 min or 1 hour before, is this what you are requesting?

**Comment by SJSJr626** [comment]
That would be a great feature too, but not exactly what I am suggesting. Say I have a task such as "complete all meeting minutes" due end of the day every Thursday. It would be useful so that I could set up as a recurrent task that shows up on "today" every Thursday.

**Comment by starget24** [comment]
I think the functionally you're describing is already integrated in Planify.
See:


![image](https://github.com/alainm23/planify/assets/92924912/6c2b8d02-b11e-4bc1-b967-5be1dbfd7ab2)


That being said, as far as i know the only way to get to this feature is on planify itself have a task already being created and the view must be on list mode, you can't access it on board mode nor quick add, nor when making a new task.

But it has the feature nonetheless.

**Comment by SJSJr626** [comment]
Interesting, I do not have those dots.

[image: image.png]

**Comment by alainm23** [comment]
Hi, @SJSJr626 maybe you are using Planner, Planner was deprecated and you will have to migrate to Planify.
https://flathub.org/apps/io.github.alainm23.planify
