### ISSUE TITLE
Can't close settings menu  with mouse in specific instances

### ISSUE THREAD

**Issue by forteller** [alainm23/planify#1106]
**Describe the bug**

See title. After following the steps I can only close the menu by pressing Esc, not clicking anywhere.

**To Reproduce**
1. Click on the settings menu in the upper right corner
2. Click on "Order by"
3. Click again at the same spot to close the "Order by" dropdown.
4. Now click anywhere outside of the menu and notice that nothing happens.

**Expected behavior**
The settings menu should close, just like it normally does when clicking outside of it if you haven't clicked on "Order by"

**Desktop (please complete the following information):**
 - OS or DE: Nobara 39, Gnome
 - Version 4.4

**Additional context**
Flatpak

**Comment by alainm23** [comment]
I have also replicated it on certain occasions, I am reviewing it.

**Comment by alainm23** [comment]
Apparently there is a bug in Gtk that breaks the behavior of a Popover when another Popover is opened on top of it. to fix it I will change the behavior avoiding this.
