### ISSUE TITLE
Fix Travis Build again

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#111]
https://travis-ci.com/alainm23/planner/builds/141052542

# Incorrect values in Debian control file
AppCenter checked your Debian control files and found some errors
- Source should be "com.github.alainm23.planner"
- Package should be "com.github.alainm23.planner"

**Suggestion:** Change the Debian control file in lines 1 & 15 to com.github.alainm23.planner
https://github.com/alainm23/planner/blob/master/debian/control

**Comment by alainm23** [comment]
Thank you very much, I could solve it.
