### ISSUE TITLE
QUESTION/SUGGESTION: Syncronice encrypted database.

### ISSUE THREAD

**Issue by Erz3** [alainm23/planify#1112]
**Is your feature request related to a problem? Please describe.**
Hi, I am implementing a script to save Planify's database in Google Drive, synchronized and encrypted. For this job, I am working with Rclone, however I need to know if Planify's database could change in the future with a major update. should I worry about this?

**Describe the solution you'd like**
I will implement my script with a condition to check Planify's version before starting synchronization process.

**Describe alternatives you've considered**
It would be nice implement this process in Planify. For example, Deja Dup uses [Duplicity](https://duplicity.gitlab.io/) for this job.

**Comment by alainm23** [comment]
Hi, I am not sure if it is best to save the database to sync, the database is constantly updated to add new features and improvements, you could create a backup instead. I will close this issue as it is a query.
