### ISSUE TITLE
Add an option to hide the (no section) list from the board view

### ISSUE THREAD

**Issue by Mohs9n** [alainm23/planify#1113]
I like the new board view a lot, but i usually have everything in a section so the no section list would just always be there taking up space for no reason.

Maybe you could add an option to hide that section when it's empty.

**Comment by wada3n** [comment]
I came to make a request like this, actually hiding it in case it's empty would be very practical.
Thank you so much, @alainm23, for the amazing work you do

**Comment by alainm23** [comment]
Yes, it is something that also makes me uncomfortable, the simplest thing would be to give an option of visibility to the Section, to hide it and show it. Doing it automatically, as Todoist does, is possible but it requires a lot more work.

**Comment by wada3n** [comment]
Yes, I think that this simpler method is an effective solution.

**Comment by alainm23** [comment]
Sorry for the delay, the option to hide or make a section visible (Included (No Section)) has been added, I don't have a release yet but I hope it can be next week.

![image](https://github.com/alainm23/planify/assets/33765137/5d115c95-6ad8-4e2f-ab99-978c3210eb11)

**Comment by wada3n** [comment]
Bravo @alainm23 , great job!
