### ISSUE TITLE
I have planner 3 from flathub, how do I upgrade?

### ISSUE THREAD

**Issue by BarbzYHOOL** [alainm23/planify#1115]
I have planner 3 from flathub, how do I upgrade to planify?
thanks

**Comment by BarbzYHOOL** [comment]
@alainm23 halp

**Comment by alainm23** [comment]
Sorry, Planner is no longer supported. We don't have a migration plan yet, you can live with both apps at the same time and migrate their tasks manually.

**Comment by BarbzYHOOL** [comment]
omg i have like 150

**Comment by mamekoro** [comment]
I recently noticed that Planner has been replaced by Planify when I ran `flatpak update`.
Do I have to manually migrate many TODO titles, descriptions, schedules, projects, labels, etc.?
That's really painful. Please consider adding a migration feature. 🙏🏻

**Comment by alainm23** [comment]
Hi guys, I don't want to leave you abandoned, I will try to move forward with this migration functionality for the next version of Planify, the migration would be automatic (Only for local tasks) and the user would have to select the Planner database.

**Comment by BarbzYHOOL** [comment]
ok ok

**Comment by MarcSchuh** [comment]
@alainm23 thanks for your efforts. I installed planner some time ago and ran in the same problem as the others, that it got replaced by Planify. One can install planner manually but as it is no longer supported a migration feature from Planner to Planify would be awesome! Thanks in advance! :)

**Comment by alainm23** [comment]
Hi guys, I understand that Planner was replaced by Planify, but can you still run Planner on your computer?

**Comment by alainm23** [comment]
Guys, could you please validate if the database.db file in the following path on your computer exists?
`/home/<user>/.var/app/com.github.alainm23.planner/data/com.github.alainm23.planner/database.db`

**Comment by MarcSchuh** [comment]
Yes, Planner is still running and the database is present.
