### ISSUE TITLE
can't create a recurring task

### ISSUE THREAD

**Issue by Naadiyaar** [alainm23/planify#1119]
**Describe the bug**
In schedule section there is no way to create a recurring task

**Expected behavior**
get an option to make a repeating task like showed in change log
https://useplanner.com/release/2020/04/17/hi-everyone-Planner-2-3-is-here/

![Screenshot from 2024-01-27 14-46-41](https://github.com/alainm23/planify/assets/106643149/718ee269-ad09-4cef-8860-c95cb4037b44)
![Screenshot from 2024-01-27 14-50-54](https://github.com/alainm23/planify/assets/106643149/b5391872-d765-4d27-83b3-a2805708add8)

**Desktop (please complete the following information):**
 - OS or DE: Fedora 38 GNOME 44.8
 - 3.0.10 flatpak

**Comment by alainm23** [comment]
Hello and thank you for using Planify. The recurring task option is found in the option menu of each task.

![image](https://github.com/alainm23/planify/assets/33765137/a8c39233-f6d4-41bb-8eec-792b935ec782)

Although several users have already asked me the same question, maybe we need to improve the UX a bit for this functionality.

**Comment by alainm23** [comment]
And sorry, but Planner is no longer supported, try migrating to Planify, which receives constant updates.
https://flathub.org/apps/io.github.alainm23.planify

**Comment by Naadiyaar** [comment]
Okay, thanks for clarification and all good work
