### ISSUE TITLE
Trash folder

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#112]
- a place where tasks can be first deleted to 
- then brought back if required

- then the "Are you sure you want to delete, pop-up can be remove and only used when emptying trash folder.

Could call it "back-pocket"

**Comment by alainm23** [comment]
I would like to open a debate here. Is this feature really necessary?

**Comment by ghost** [comment]
possible not necessary (more a preference) suppose user could create their own "trash"

**Comment by 4jNsY6fCVqZv** [comment]
Not sure if a separate "Trash" folder makes sense either.

Maybe I need a way to reopen already closed tasks/projects when I realize that the task/project is not completely finished after all?

What I think should be there in any case: An undo functionality for tasks/projects that have just been deleted or maybe accidentally deleted.

More about this in the elmentary HIG https://elementary.io/docs/human-interface-guidelines#always-provide-an-undo

With Agenda https://github.com/dahenson/agenda, this is implemented in two steps:
1. completed tasks are crossed out
2. a small trash symbol appears next to a task.

I'm also wondering how a Planner solution could look like in combination with external & integrated services like GitHub or Todoist?

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 Should this issue be reopened for discussion?

**Comment by ghost** [comment]
if you feel like it should re-opened, i don't feel like its MVP at this time. future feature maybe?, maybe a task history that shows completed/deleted items based on dates, that could be turned into quite a nice graph.
