### ISSUE TITLE
Cannot sync with Todoist

### ISSUE THREAD

**Issue by hubertmalkowski** [alainm23/planify#1120]
**Describe the bug**
When I open Todoist integration window, it is in loading state forever. 
**To Reproduce**
1. Go to `Preferences`
2. Click on `Integrations`
3. Scroll down to 'Switch on Todoist integration`
4. See a loading screen that never ends

**Expected behavior**
Well, I want to integrate with todoist.

**Screenshots**
![image](https://github.com/alainm23/planify/assets/61802095/8dfdd36d-c4b4-4a1b-b310-e0a029806da7)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 39
 - DE: GNOME 45.3 
 - PLANIFY: version 4.4 installed from flathub

**Comment by alainm23** [comment]
Thanks for using Planify, could you run the app in debug mode and send me the error message it sends?
`flatpak run --devel io.github.alainm23.planify`

**Comment by hubertmalkowski** [comment]
Probably this one
```
(io.github.alainm23.planify:2): GLib-GIO-CRITICAL **: 14:05:56.874: g_settings_set_value: key 'todoist-sync-token' in 'io.github.alainm23.planify' expects type 's', but a GVariant of type '(null)' was given
```

Whole command output:
```
(io.github.alainm23.planify:2): Gtk-WARNING **: 14:05:30.616: Locale not supported by C library.
	Using the fallback 'C' locale.

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 14:05:30.984: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 14:05:31.502: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed
flatpak-spawn: Invalid byte sequence in conversion input
Try "flatpak-spawn --help" for more information.


(io.github.alainm23.planify:2): Json-CRITICAL **: 14:05:56.874: json_object_get_string_member: assertion 'node != NULL' failed

(io.github.alainm23.planify:2): GLib-CRITICAL **: 14:05:56.874: g_variant_new_string: assertion 'string != NULL' failed

(io.github.alainm23.planify:2): GLib-CRITICAL **: 14:05:56.874: g_variant_ref_sink: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): GLib-GIO-CRITICAL **: 14:05:56.874: g_settings_schema_key_type_check: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): GLib-CRITICAL **: 14:05:56.874: g_variant_get_type_string: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): GLib-GIO-CRITICAL **: 14:05:56.874: g_settings_set_value: key 'todoist-sync-token' in 'io.github.alainm23.planify' expects type 's', but a GVariant of type '(null)' was given

(io.github.alainm23.planify:2): GLib-CRITICAL **: 14:05:56.874: g_variant_unref: assertion 'value != NULL' failed
```

**Comment by alainm23** [comment]
For some reason, Todoist is automatically logging you in and getting an invalid token, could you go into Todoist and Integrations and check if you have Planify installed? if so, delete it and try again.

![image](https://github.com/alainm23/planify/assets/33765137/1c91bc86-1fa2-4a9a-b35b-17ecf365c889)

**Comment by hubertmalkowski** [comment]
I have no integrations in todoist and I've never even logged in to planify through todoist. I've also deleted all `online accounts` from my system (just to be sure) and it still doesn't work.

**Comment by gab1one** [comment]
I had the same issue, the log messages when starting planify from the CLI, and the todoist login would just show a blank screen.
- `(io.github.alainm23.planify:2): Gtk-WARNING **: 09:54:36.620: Locale not supported by C library.
	Using the fallback 'C' locale.`
- `flatpak-spawn: Invalid byte sequence in conversion input` 
After setting the locale with Flatseal, as suggested here: https://github.com/johnfactotum/foliate/issues/1169#-and-im-using-flatpak the login worked.

**Comment by hubertmalkowski** [comment]
Yeah, it fixed the issue. Thanks @gab1one!

**Comment by alainm23** [comment]
@gab1one  It's a great solution, I'm adding it as an environment setting when starting Planify.
