### ISSUE TITLE
Can not remove focus from Note text field

### ISSUE THREAD

**Issue by forteller** [alainm23/planify#1122]
**Describe the bug**
If I click in the Note field in any project it is almost impossible to get the focus away from that field again, rendering the keyboard shortcuts unusable. Even pressing Tab just inserts a tab char instead of moving the focus. The only option is to click on any of the buttons in the headerbar.

In addition: If I create a new project while in a project where the focus is in the Note field, the new project starts with the Note field already focused.

**To Reproduce**
1. Go to any project
2. Click on the Note field
3. Try to click anywhere except for the buttons in the headerbar
4. See how focus is still in the Note field
5. Create a new project
6. See how focus is in the Note field of the new project

**Expected behavior**
Clicking anywhere outside of the Notes field, or pressing Tab should remove focus from the field.

Pressing Enter should possibly also do the same, while Shift+Enter should be used for adding line breaks in the note. Not totally sure about that, though, but seeing as it is a field, not a text box, I expect it to only be one line of text by default.

**Screenshots**

**Desktop (please complete the following information):**
 - OS or DE: Nobara 39, Gnome
 - Version 4.4

**Comment by alainm23** [comment]
I'm sorry, it happened to me too and it feels really bad, I'll fix it.
