### ISSUE TITLE
Subtasks should not have project and section fields

### ISSUE THREAD

**Issue by wada3n** [alainm23/planify#1123]
Dear @alainm23,

I am writing to report a bug I encountered while using the app.

**Steps to reproduce the bug:**

1. Create a new task.
2. Click on the "Add subtask" button.
3. Notice that the same window appears as when creating a new task.
4. The bottom of the window shows the project and section fields.

**Expected behavior:**

When creating a subtask, the project and section fields should be hidden or disabled. Subtasks should always be added to the same project and section as the parent task.

**Actual behavior:**

The project and section fields are visible and enabled when creating a subtask. This can lead to confusion and errors, as users may accidentally add subtasks to the wrong project or section.

Screenshot Video:

[Kooha-2024-02-01-14-26-48.webm](https://github.com/alainm23/planify/assets/13304792/e17611e7-c621-4821-a0ad-54b459e2db9a)

**OS information:**

- OS: Fedora 39
- Planify version: 4.4

I would appreciate it if you could investigate this bug and fix it in a future update.

Thank you for your time and consideration.

**Comment by alainm23** [comment]
Thanks for using Planify, I agree with you, Planify should not show the Projects and Sections selector when creating a subtask. it will be fixed in the next version. Thanks for your help.
