### ISSUE TITLE
Add new section from new to-do box

### ISSUE THREAD

**Issue by forteller** [alainm23/planify#1125]
**Is your feature request related to a problem? Please describe.**
Hi again. Love the app! Thank you for making the first ever offline kanban app for Linux that I've seen that is kept updated. Also looks great! :)

So, when I add a new todo item I often have an idea for a section it should go into, but I never think ahead to add that section first. In my mind the logical thing is that I can add that new section from the new to-do box where I select the section.

**Describe the solution you'd like**
The section drop-down in the new to-do box should have a new section option that lets you type in the name for a new section and add the new to-do to that section.

![image](https://github.com/alainm23/planify/assets/343561/0b1acd29-3851-4902-98b6-6ce07eaae68d)

It would be nice if you could type the name directly in the dropdown, so there doesn't have to be a second box on top of the first.

Thanks! :)

**Comment by alainm23** [comment]
Hello, an entry has been added to search, if you can't find it you can create a new section by pressing the Enter key.
![image](https://github.com/user-attachments/assets/5813d8dc-4f11-4955-ad2e-ebce7e73b87e)

**Comment by forteller** [comment]
Love it! Thanks!
