### ISSUE TITLE
Planify should always show completed sub-tasks

### ISSUE THREAD

**Issue by oktayacikalin** [alainm23/planify#1126]
**Is your feature request related to a problem? Please describe.**
I often have tasks having a couple of sub-tasks, which are relevant as a reference while the main gig is running.

Also, I have about 100 completed tasks per list, which I don't want to see until I do my monthly review and finally remove them. In other lists, I keep them for a year or so just for reference. Always showing those is slowing down the app significantly.

Nextcloud Tasks does it differently. By default it hides completed tasks, but shows completed sub-tasks. This keeps the web app snappy, while not hiding important steps of a task (sequence).

**Describe the solution you'd like**
Ignoring the "Hide completed tasks" setting, always showing all sub-tasks of a **open** task.

**Describe alternatives you've considered**
Keep the "Hide completed tasks" setting off, but this clutters the relevant view and slows down Planify.

**Additional context**
None

**Comment by alainm23** [comment]
To fix this, we could add a setting to "Always show completed subtasks" and make this alternate behaviour for the user.

**Comment by oktayacikalin** [comment]
> To fix this, we could add a setting to "Always show completed subtasks" and make this alternate behaviour for the user.

In order not to break it for existing users? Sounds fine to me :+1: 

Are you collecting some metrics about usage of features? I'm not a fan of bloated tools and I would not want Planify to be one. This is also why I let my wishlist sleep for over a week, before letting it out.
