### ISSUE TITLE
Cannot get to the parent of a scheduled sub-task

### ISSUE THREAD

**Issue by oktayacikalin** [alainm23/planify#1127]
**Describe the bug**
I have a task with some sub-tasks. Each of those sub-tasks are being scheduled. The **Today** and **Scheduled** view only show the relevant sub-tasks, with no reference to the parent nor siblings. The context is completely lost at this point.

**To Reproduce**
1. Create task with sub-tasks.
2. Schedule some sub-tasks.
3. Click on scheduled sub-task in **Today** or **Scheduled** view.
4. I cannot see what the sub-task is related to, nor can I get back to the parent.

**Expected behavior**
When showing sub-tasks in the **Today** or **Scheduled** view, it should show the root task and all children down to the relevant sub-task (critical path). Hiding all irrelevant branches and siblings. This way I could easily get back to the topic.

**Screenshots**
![Bildschirmfoto vom 2024-02-01 23-32-22](https://github.com/alainm23/planify/assets/687189/db0a6554-2ea5-46c8-9ff9-408fead53c06)
![Bildschirmfoto vom 2024-02-01 23-33-04-obfuscated](https://github.com/alainm23/planify/assets/687189/5c6f263d-d865-4d38-bd07-e16873cb5d53)
![Bildschirmfoto vom 2024-02-01 23-33-28](https://github.com/alainm23/planify/assets/687189/981dbe02-ebd6-46ec-8eea-bcacf5ce41e3)

**Desktop**
 - Fedora 39 with GNOME 45.3
 - Planify devel from #1118 

**Additional context**
None

**Comment by alainm23** [comment]
This feature is available in Planify 4.7.6
