### ISSUE TITLE
Segmentation Fault when Adding Tasks

### ISSUE THREAD

**Issue by clark-ja** [alainm23/planify#1129]
**Describe the bug**

Planify crashes when clicking the "Plus" Icon to create a new Task after setting up synchronization to Nextcloud via CalDAV. After synchronziation is enabled this happens even when trying to add a task to a local project.

**Expected behavior**
I would expect no crash to happen.

**Desktop (please complete the following information):**
 - OS or DE:  Arch Linux (Kernel 6.7.2) with KDE Plasma 5.27.10 (X11)
 - Version: `main` branch at commit 2c17785d1a2b8c3988b0d4ad6e587f5e78c75e2d

**Additional context**

<details>
<summary> `strace -f -t -e trace=file planify` </summary>
<pre>
[...]
[pid 67209] 18:50:59 mkdir("/run/user/1000/dconf", 0700) = -1 EEXIST (File exists)
[pid 67209] 18:50:59 newfstatat(AT_FDCWD, "/run/user/1000/dconf", {st_mode=S_IFDIR|0700, st_size=40, ...}, 0) = 0
[pid 67209] 18:50:59 openat(AT_FDCWD, "/run/user/1000/dconf/user", O_RDWR|O_CREAT, 0600) = 20
[pid 67209] 18:50:59 openat(AT_FDCWD, "/home/REDACTED/.config/dconf/user", O_RDONLY|O_CLOEXEC) = 20
[pid 67209] 18:50:59 newfstatat(20, "", {st_mode=S_IFREG|0644, st_size=23996, ...}, AT_EMPTY_PATH) = 0
[pid 67209] 18:50:59 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x20} ---
[pid 67271] 18:51:01 +++ killed by SIGSEGV (core dumped) +++
[pid 67252] 18:51:01 +++ killed by SIGSEGV (core dumped) +++
[pid 67245] 18:51:01 +++ killed by SIGSEGV (core dumped) +++
[pid 67244] 18:51:01 +++ killed by SIGSEGV (core dumped) +++
[pid 67243] 18:51:01 +++ killed by SIGSEGV (core dumped) +++
[pid 67242] 18:51:01 +++ killed by SIGSEGV (core dumped) +++
[pid 67241] 18:51:01 +++ killed by SIGSEGV (core dumped) +++
[pid 67231] 18:51:01 +++ killed by SIGSEGV (core dumped) +++
[pid 67228] 18:51:01 +++ killed by SIGSEGV (core dumped) +++
[pid 67227] 18:51:01 +++ killed by SIGSEGV (core dumped) +++
</pre>
</details>

<details>
<summary>Stacktrace at moment of crash (in function `layouts_quick_add_construct`)</summary>
<pre>
#0  0x000073bdfdfd4a90 in layouts_quick_add_construct () at /usr/lib/libplanify.so.0
#1  0x000056bbf07127ff in ??? ()
#2  0x000073bdfdd5780c in ??? () at /usr/lib/libgobject-2.0.so.0
#3  0x000073bdfdd59af1 in g_object_new_valist () at /usr/lib/libgobject-2.0.so.0
#4  0x000073bdfdd5a29e in g_object_new () at /usr/lib/libgobject-2.0.so.0
#5  0x000056bbf071e187 in dialogs_quick_add_construct ()
#6  0x000056bbf070143c in views_today_prepare_new_item ()
#7  0x000073bdfdd476c0 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#8  0x000073bdfdd75a36 in ??? () at /usr/lib/libgobject-2.0.so.0
#9  0x000073bdfdd66a42 in ??? () at /usr/lib/libgobject-2.0.so.0
#10 0x000073bdfdd66c77 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#11 0x000073bdfdd66d34 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#12 0x000073bdfdd66b73 in ??? () at /usr/lib/libgobject-2.0.so.0
#13 0x000073bdfdd66c77 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#14 0x000073bdfdd66d34 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#15 0x000073bdfd4a9575 in ??? () at /usr/lib/libgtk-4.so.1
#16 0x000073bdfdd66b73 in ??? () at /usr/lib/libgobject-2.0.so.0
#17 0x000073bdfdd66c77 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#18 0x000073bdfdd66d34 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#19 0x000073bdfd54d847 in ??? () at /usr/lib/libgtk-4.so.1
#20 0x000073bdfdd4b4f7 in g_cclosure_marshal_VOID__BOXEDv () at /usr/lib/libgobject-2.0.so.0
#21 0x000073bdfdd66b73 in ??? () at /usr/lib/libgobject-2.0.so.0
#22 0x000073bdfdd66c77 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#23 0x000073bdfdd66d34 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#24 0x000073bdfd547938 in ??? () at /usr/lib/libgtk-4.so.1
#25 0x000073bdfd5486ab in ??? () at /usr/lib/libgtk-4.so.1
#26 0x000073bdfd54e0e0 in ??? () at /usr/lib/libgtk-4.so.1
#27 0x000073bdfd66633a in ??? () at /usr/lib/libgtk-4.so.1
#28 0x000073bdfd666555 in ??? () at /usr/lib/libgtk-4.so.1
#29 0x000073bdfd8b6b76 in ??? () at /usr/lib/libgtk-4.so.1
#30 0x000073bdfd58bae5 in ??? () at /usr/lib/libgtk-4.so.1
#31 0x000073bdfd675a9c in ??? () at /usr/lib/libgtk-4.so.1
#32 0x000073bdfd4adffd in ??? () at /usr/lib/libgtk-4.so.1
#33 0x000073bdfd850773 in ??? () at /usr/lib/libgtk-4.so.1
#34 0x000073bdfdd476c0 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#35 0x000073bdfdd75a36 in ??? () at /usr/lib/libgobject-2.0.so.0
#36 0x000073bdfdd66335 in ??? () at /usr/lib/libgobject-2.0.so.0
#37 0x000073bdfdd66c77 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#38 0x000073bdfdd66d34 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#39 0x000073bdfd8ad5f0 in ??? () at /usr/lib/libgtk-4.so.1
#40 0x000073bdfd81fd7e in ??? () at /usr/lib/libgtk-4.so.1
#41 0x000073bdfdebbf69 in ??? () at /usr/lib/libglib-2.0.so.0
#42 0x000073bdfdf1a3a7 in ??? () at /usr/lib/libglib-2.0.so.0
#43 0x000073bdfdeba162 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#44 0x000073bdfd306b66 in g_application_run () at /usr/lib/libgio-2.0.so.0
#45 0x000056bbf06a60da in main ()
#46 0x000073bdf8a1fcd0 in ??? () at /usr/lib/libc.so.6
#47 0x000073bdf8a1fd8a in __libc_start_main () at /usr/lib/libc.so.6
#48 0x000056bbf06a6125 in _start ()
</pre>
</details>

The Crash also still happens if I disable synchronization in the UI settings. It does not happen right after installation and without any CalDAV sync or any other tasks.

Let me know if there is any other info I can provide you with to better understand this issue. Unfortunately I currently do not have the time to dive into the source code of planify and extensively debug the issue, but I thought it would be useful for you...

**Comment by alainm23** [comment]
Could you disable the Run in background option in the Preferences and try again?

**Comment by alainm23** [comment]
Can I upgrade to 4.5.4 and try again?

**Comment by alainm23** [comment]
I'm sending an update to fix the bug.
You could change the New Task Position preference to 'Bottom' to fix the problem for now.
![image](https://github.com/alainm23/planify/assets/33765137/f93c208b-2f34-45dc-89a2-7cdbd30bbd0d)
