### ISSUE TITLE
Task Completed still shows

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#113]
**To Reproduce**
Steps to reproduce the behaviour:
1. Create a task
2. complete the task
3. then untick the completed task and/or delete it
4. Task Completed heading still shows

**Expected behaviour**
Task Completed to be hidden if there is no completed tasks

**Screenshots**
![planner_bug_task_completed](https://user-images.githubusercontent.com/59498682/71762590-bf456b00-2ed9-11ea-9bf8-816666568bd5.png)

 - OS: Elementary
 - Version OS 5.1 Hera

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 What I also notice when I look at the screenshot: The sidebar also shows "2" tasks for the Inbox, while the Inbox view doesn't show any more tasks. Is this an issue that you have fixed as well?

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 So, how's things looking after your fix? Can you please post a screenshot?

**Comment by 4jNsY6fCVqZv** [comment]
I think an empty list would be weird, too. Maybe there can be a generic hint that there are no tasks available at the moment, maybe with the suggestion that I can create some?
Or the app automatically shows the welcome screen again as soon as there are no more tasks and projects?
see https://elementary.io/docs/human-interface-guidelines#welcome-screen
I'm sure there are other solutions. I am curious about your ideas!
What does the current status look like after the fix?

**Comment by alainm23** [comment]
If I think the same as you, what we could do here is to use a placeholder telling the user that their completed tasks will appear here.

**Comment by alainm23** [comment]
I am going to investigate the Inbox problem, thanks for your observation.

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 In addition to the idea of a placeholder:
That would also make sense for the "Today" and "Upcoming" view, right?
At the moment the view looks a bit empty.
For example Today view https://github.com/alainm23/planner/issues/120#issue-545570796
Do you wish me to create a separate issue for this? Otherwise the comments and issues will probably get confusing very quickly, right?

**Comment by alainm23** [comment]
@4jNsY6fCVqZv Of course, these are small details that I have not yet developed by focusing more on the main functionality.
