### ISSUE TITLE
Snap package working

### ISSUE THREAD

**Issue by soumyaDghosh** [alainm23/planify#1130]
Hii dev, thanks for this awesome app. I have created a snap package for this app. The snap can be easily run with the command `planify` for normal GUI and `planify.quick-add` for quick addition of tasks. It's at per to the flatpak and have no extra need to continue updating until some big change comes up. I can help in that case also. Some screenshots

![image](https://github.com/alainm23/planify/assets/72045785/2621f816-4410-41df-ae88-51b975c4e9d5)

![image](https://github.com/alainm23/planify/assets/72045785/fddaa3b4-1690-450f-ae96-eddee90bba20)

![image](https://github.com/alainm23/planify/assets/72045785/7c6a8aff-dec3-44fc-8617-f08cd2693e17)

**Comment by alainm23** [comment]
Hi and thanks for using Planify, I really don't have any experience using Snap and I don't use Ubuntu either. I'm not sure what step to take. maybe I could start by adding the build file in the following build-aux path.

**Comment by soumyaDghosh** [comment]
> I really don't have any experience using Snap and I don't use Ubuntu either.

It's actually simple. Let me guide you.

1. Create an account in the snap store from this [link](https://snapcraft.io/snaps).
2. Register the snap name `planify`.
3. Connect this github repo under the name. 
4. I'll create a PR adding the snap files in this repo. The manifest file has to be either on the top of the repo or under `snap` folder for the store to recognize the manifest.
5. Additionally, I can add workflows for the snap to check if it's building for every single commit, and also, build & upload the latest commit in the `edge` channel of the snap store which is meant to be for the nightly or unstable packages. Also if you want to completely control your upload of snap to the store from this repo only, that can also be done. But things need to be done first upto step 2. 

Again thanks for showing interest on the snap package. I am very happy to assist you whenever you need :-)
