### ISSUE TITLE
Visual bug when dragging todos

### ISSUE THREAD

**Issue by luiover** [alainm23/planify#1131]
Ok, so I noticed when I try moving one of my to-do box it will show me a blue box (for better ux) but that should be only to let me know where I'm placing the box and shouldn't be kept, because when I release the box that blue box remains there.

**To Reproduce**
1. Go on a task "On This Computer"
2. Drag a box and while holding move it between two elements
3. You should notice a blue box indicating where the element is going to be placed.
4. Once released the box doesn't fade away but remains there.

**Expected behavior**
Disappears after the release of the dragging

**Screenshots**
![blue box glitch img](https://github.com/alainm23/planify/assets/157648225/75d838e7-ca80-4735-a0ee-bec3e373eefb)
[video](https://github.com/alainm23/planify/assets/157648225/ef092ad3-6ed5-440c-a2dd-2434df04a209)

**Desktop (please complete the following information):**
 - Ubuntu (Zorin OS 17) 
 - GNOME 3 and XFCE 4

I don't know if it's me or the program issue but this is pretty much annoying and it doesn't go away with a simple click. Anyways nice work on the UI and that's the best todo app I could find on the internet.

**Comment by BeatLink** [comment]
I am seeing this bug as well 
![image](https://github.com/alainm23/planify/assets/47278150/898e9bf4-8a2a-412e-8054-84e7cb13aa2c)
