### ISSUE TITLE
Blue Dot ?

### ISSUE THREAD

**Issue by in4matix** [alainm23/planify#1139]
First of all many thanks for this well designed application. I will definitely send a denotation soon. 

Minor Bug? : What is this blue dot and how do I get rid of it?

![Screenshot from 2024-02-21 10-29-11](https://github.com/alainm23/planify/assets/62904593/1130355a-f992-4c00-bedb-0ddfb0fedd19)

**Comment by alainm23** [comment]
Hello and thank you for using Planify. The blue dot is a visual indicator that shows if you made any type of change in the filters, you probably have the option to see completed tasks or change the type of order.

**Comment by in4matix** [comment]
Ah! I had the sort order set to Due date.. It was driving me nuts as I just could not figure it out. Thanks!

**Comment by alainm23** [comment]
Now it is a bit confusing because we only have one filter, but later on it will be useful, I plan to add filters by priority, tags, dates, etc.
