### ISSUE TITLE
highlighting text while typing elsewhere

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#114]
To Reproduce
Steps to reproduce the behaviour
- highlight some text
- select elsewhere and type
- highlight stays

**Screenshots**
![planner_bug_highlightig](https://user-images.githubusercontent.com/59498682/71764673-8619f480-2ef3-11ea-9af4-9a67fb006b72.png)

OS: Elementary
Version OS 5.1 Hera

**Comment by alainm23** [comment]
I really don't know how to solve this. But the question is: is it a problem?

**Comment by ghost** [comment]
I see it also happens in elementary mail, so not app related

**Comment by 4jNsY6fCVqZv** [comment]
@inputbim Did you test with the stable version of Mail or the rewrite?

Why do you consider this behavior an issue? Which behavior would you expect / wish?
Would it be important to you to change this behavior? Then you can create a general issue: https://github.com/elementary/stylesheet

p.s. Just tested it myself. Code works the way you want it to?
