### ISSUE TITLE
Feature request: Logbook

### ISSUE THREAD

**Issue by wada3n** [alainm23/planify#1140]
**Description:**

I would like to request a new feature for Planify, The feature is called "Logbook" and it is inspired by the Things 3 app for Mac.

The Logbook is a permanent, searchable record of completed tasks. It provides a way to track what you have done and when you did it. It is essentially an automatic work journal.

**Implementation:**

The Logbook could be implemented as a new section in the sidebar of Planify. the list of completed tasks, could organized by today, yesterday, last week, months, and year.

Tasks could be added to the Logbook by project setting or automatically. There could be an option in each project to automatically add completed tasks to the Logbook. To add a task automatically, you could create a rule in preferences that says "When a task is marked as complete, add it to the Logbook."

The Logbook could be filtered by project, label, or other criteria. This would allow you to quickly find the tasks you are looking for.

![things logbook](https://github.com/alainm23/planify/assets/13304792/9f3e9f47-3ec1-47d2-a37d-3f645b799129)

**Comment by alainm23** [comment]
This function is now available, go to Quick Find and enter Completed.

![image](https://github.com/alainm23/planify/assets/33765137/66f6fe18-1d48-41e2-8c3e-2fbb3766c019)

**Comment by wada3n** [comment]
OH, it really works and it's so elegant!
Thank you for your quick response.

**Comment by wada3n** [comment]
@alainm23,
Is there any way i can add it to the sidebar? We already have enough room for that!

**Comment by wada3n** [comment]
By the way, there is a minor glitch. When using Quick Find, non-existent tasks appear. These are specific to the application's Tutorial and have been deleted previously.

![Screenshot from 2024-02-21 20-22-13](https://github.com/alainm23/planify/assets/13304792/bd906f92-6711-4245-9b6f-ff42d72028e2)

**Comment by alainm23** [comment]
Oh, I'll check the bug.

**Comment by wada3n** [comment]
once again, thank you for this outstanding application!
It has been immensely helpful to me.
