### ISSUE TITLE
Removal, Renaming or Reordering (No Section)

### ISSUE THREAD

**Issue by jonatkc** [alainm23/planify#1141]
**Is your feature request related to a problem? Please describe.**
I've been organizing my tasks in sections and when you have Planify viewed in Board mode it leaves a gap for the (No Section). It been bothering me having a massive gap. 

**Describe the solution you'd like**
Is there a way to rename, remove or re-order the (No Section) section?

![Screenshot from 2024-02-21 16-33-39](https://github.com/alainm23/planify/assets/105486415/7643b474-6965-47c1-9696-d1bd51ceb9a0)

**Comment by alainm23** [comment]
This feature is available in Planify 4.5.
