### ISSUE TITLE
CalDAV Tasks do not sort by due times

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#1142]
**Describe the bug**
On the Today and Scheduled views, tasks with due dates and times do not sort in chronological order by the due time

**To Reproduce**
1. Create a task for today at time 9:00 AM
2. Create a task for today at 10:00 PM 
3. Go to Today view and Upcoming view
4. Note that tasks are not sorted chronologically

**Expected behavior**
Tasks should be sorted chronologically based on time.

**Screenshots**
![image](https://github.com/alainm23/planify/assets/47278150/f789a5e5-c722-410e-a74a-f4a823b4d1ab)

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint 21.3 Cinnamon
 - Version https://github.com/alainm23/planify/issues/1118#issuecomment-1949963222

**Additional context**

**Comment by BeatLink** [comment]
Are there any updates on this bug?

**Comment by alainm23** [comment]
In the next update, thank you for reminding me (There are many things I work on and forget).

![image](https://github.com/alainm23/planify/assets/33765137/8277d78e-7d41-4af7-b473-692d0d2d199a)
