### ISSUE TITLE
CalDAV Don't load completed tasks until requested

### ISSUE THREAD

**Issue by oktayacikalin** [alainm23/planify#1144]
**Is your feature request related to a problem? Please describe.**
I've about 500 completed tasks as a reference. This is not a problem for the web app of NC, which won't load them initially. But Planify tries to load them all and slows down to a long halt for me.
After starting Planify, I have to wait for up to a minute until I can work with it. Every sync if painfully slow. davx5 on Android does not have this problem at all.

**Describe the solution you'd like**
Please don't load completed tasks initially. Only when I select to view them and then only for the current list/project.

**Describe alternatives you've considered**
Deleting all completed tasks, but I need them occasionally as a reference.

**Additional context**
Planify 4.5 from flathub.

I don't know what exactly is taking so long, but every time it syncs, I have to wait for a long time and the GUI stalls, which is really annoying.
Perhaps there's also room for improvement when instantiating the GUI elements?

**Comment by oktayacikalin** [comment]
[Bildschirmaufzeichnung vom 2024-02-23, 18-04-47.webm](https://github.com/alainm23/planify/assets/687189/1365b25e-6969-4072-8837-f4f101590900)

**Comment by alainm23** [comment]
Wow, it's a big problem, when I start Planify, I synchronize each of the task lists (Completed and not completed). I imagine that is the reason for the poor performance, I will analyze how to solve it.

**Comment by oktayacikalin** [comment]
Hmm.. Is the sync routine running in a separate thread or is it running in the main thread?

**Comment by alainm23** [comment]
I do the loading asynchronously (which does not block the user interface). I will try using separate threads.

**Comment by alainm23** [comment]
I am solving this problem by using a [sync_token](https://sabre.io/dav/building-a-caldav-client/), I should only update the tasks that changed.

**Comment by oktayacikalin** [comment]
There's still a little lag after showing the main window, but waiting a few seconds and it becomes responsible. Much, much better than before! :smiley: :+1: 

[Bildschirmaufzeichnung vom 2024-03-06, 01-43-22.webm](https://github.com/alainm23/planify/assets/687189/c805773d-ca0a-486d-a228-003920b239d2)

**Comment by oktayacikalin** [comment]
I think, the problem is solved like this. I still have to see how it plays along with aCalendar+ and davx on Android, but I have a good feeling now.

Pehaps you should somehow display a warning, that the initial sync with many tasks can take some time.

**Comment by alainm23** [comment]
@oktayacikalin I'll keep it in mind
