### ISSUE TITLE
Crashes when adding subtasks

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#1148]
**Describe the bug**
When adding a subtask it crashes with no relevant logs

**To Reproduce**
1. Select any task
2. Click on + icon to add subtask
3. App crashes

**Expected behavior**
It should create a dialog box to add subtask

**Desktop (please complete the following information):**
Operating System: Fedora Linux 39
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.7.5-200.fc39.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600H with Radeon Graphics
Memory: 5.6 GiB of RAM
Graphics Processor: AMD Radeon Graphics

**Comment by andreasweber01** [comment]
I have the same problem with Linux Mint. When i press the add task button, or press Str + A, the app freezes for less than a second and then crashes without any notification

**Comment by alainm23** [comment]
Can you run Planify from the terminal and see the error logs?
`flatpak run io.github.alainm23.planify`

**Comment by andreasweber01** [comment]
This is everything I get after running it from terminal
`flatpak run io.github.alainm23.planify

** (io.github.alainm23.planify:2): CRITICAL **: 10:59:44.863: services_cal_dav_set_credential: assertion 'message != NULL' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 10:59:45.172: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 10:59:45.434: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify:2): Json-CRITICAL **: 10:59:45.597: json_object_get_string_member: assertion 'node != NULL' failed

(io.github.alainm23.planify:2): GLib-CRITICAL **: 10:59:45.597: g_variant_new_string: assertion 'string != NULL' failed

(io.github.alainm23.planify:2): GLib-CRITICAL **: 10:59:45.597: g_variant_ref_sink: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): GLib-GIO-CRITICAL **: 10:59:45.597: g_settings_schema_key_type_check: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): GLib-CRITICAL **: 10:59:45.597: g_variant_get_type_string: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): GLib-GIO-CRITICAL **: 10:59:45.597: g_settings_set_value: key 'todoist-sync-token' in 'io.github.alainm23.planify' expects type 's', but a GVariant of type '(null)' was given

(io.github.alainm23.planify:2): GLib-CRITICAL **: 10:59:45.597: g_variant_unref: assertion 'value != NULL' failed
`

After that planify opens normally. When I then press the add task button, it crashes again without any new messages.

**Comment by ghost** [comment]
Logs after running app from terminal:
`(io.github.alainm23.planify:2): CRITICAL **: 15:34:34.064: services_cal_dav_set_credential: assertion 'message != NULL' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 15:34:34.765: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify:2): Json-CRITICAL **: 15:34:35.245: json_object_get_string_member: assertion 'node != NULL' failed

(io.github.alainm23.planify:2): GLib-CRITICAL **: 15:34:35.245: g_variant_new_string: assertion 'string != NULL' failed

(io.github.alainm23.planify:2): GLib-CRITICAL **: 15:34:35.245: g_variant_ref_sink: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): GLib-GIO-CRITICAL **: 15:34:35.245: g_settings_schema_key_type_check: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): GLib-CRITICAL **: 15:34:35.245: g_variant_get_type_string: assertion 'value != NULL' failed

(io.github.alainm23.planify:2): GLib-GIO-CRITICAL **: 15:34:35.245: g_settings_set_value: key 'todoist-sync-token' in 'io.github.alainm23.planify' expects type 's', but a GVariant of type '(null)' was given

(io.github.alainm23.planify:2): GLib-CRITICAL **: 15:34:35.245: g_variant_unref: assertion 'value != NULL' failed
`

And there are no logs after it crashes

Here's what 'Problem Reporting' Applications says is the reason:
`io.github.alainm23.planify killed by SIGSEGV`

**Comment by fhamborg** [comment]
I am facing the same issue, but also when trying to add actually just any todo (not only subtasks). I'm using gnome and get this:

```
(planify:23939): Gtk-CRITICAL **: 14:47:32.395: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

(planify:23939): Gtk-CRITICAL **: 14:47:32.642: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(planify:23939): Gtk-CRITICAL **: 14:47:32.645: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(planify:23939): Gtk-CRITICAL **: 14:47:32.645: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(planify:23939): Gtk-CRITICAL **: 14:47:32.645: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed
Segmentation fault (core dumped)

```

**Comment by ghost** [comment]
Tried it again and yes as @fhamborg mentioned, it now crashes when adding normal todos as well with the same logs

**Comment by emj04** [comment]
Crashes when adding any todo.
Planify 4.5.2 Fedora 39 GNOME 45.4 Wayland

Full log:
```
** (process:9105): WARNING **: 07:25:49.646: Error writing credentials to socket: Error sending message: Broken pipe

** (io.github.alainm23.planify:2): CRITICAL **: 07:25:50.113: services_database_get_labels_by_item_labels: assertion 'labels != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 07:25:50.113: services_database_get_labels_by_item_labels: assertion 'labels != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 07:25:50.113: services_database_get_labels_by_item_labels: assertion 'labels != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 07:25:50.113: services_database_get_labels_by_item_labels: assertion 'labels != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 07:25:50.113: services_database_get_labels_by_item_labels: assertion 'labels != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 07:25:50.113: services_database_get_labels_by_item_labels: assertion 'labels != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 07:25:50.113: services_database_get_labels_by_item_labels: assertion 'labels != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 07:25:50.113: services_database_get_labels_by_item_labels: assertion 'labels != NULL' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 07:25:50.118: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 07:25:50.366: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 07:25:50.366: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed
```

**Comment by fhamborg** [comment]
After updating to 4.5.2, for me also still the same issue (same crash logs as above)

**Comment by fhamborg** [comment]
Same after updating to 4.5.4
@alainm23 is there any information I could provide aside from the info already posted above that would help you understand what the issue is here?

**Comment by alainm23** [comment]
I'm sending an update to fix the bug.
You could change the New Task Position preference to 'Bottom' to fix the problem for now.
![image](https://github.com/alainm23/planify/assets/33765137/f93c208b-2f34-45dc-89a2-7cdbd30bbd0d)

**Comment by fhamborg** [comment]
thank you also for the workaround :)
