### ISSUE TITLE
Unable to add a Description

### ISSUE THREAD

**Issue by ImanMontajabi** [alainm23/planify#1160]
**Unable to add a description**
After adding a new task, it's initially impossible to add a description. However, you can add a description after clicking the "Add To-Do" button.

**To Reproduce**
1. Go to App
2. Click on Add Task
4. Try to write a description
5. nothing!

**Desktop (please complete the following information):**
 - OS or DE: Cinnamon
 - Version 6.0.4

**Comment by BarryBanana** [comment]
Same issue with a brand new install of Fedora 39 / Gnome 45.

I notice you can edit the description once task has been created. 

This is the kind of bug that you run across within minutes of installing and opening the app for the first time.
