### ISSUE TITLE
Can't update description when adding a new task

### ISSUE THREAD

**Issue by brokoli18** [alainm23/planify#1163]
First off let me thank you for creating this application as its currently the best todo app on linux that works with Nextcloud/Cal-Dav.

**Describe the bug**
When adding a new task I can update the To-do name, but I cannot add a description. The description field is there but I cant type anything into it. After the task is saved I can then update the todo name.

**To Reproduce**
1. Click the + icon
2. Try to type something in the `Add description` field. Fail

**Expected behavior**
I would like to be able to update the title and description of the to do before I save it

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS or DE: Gnome
 - Version: 43.9

**Additional context**
N/A

**Comment by w-wagner** [comment]
Same here: Just installed via flatpak on latest debian
When I close the task open it again, I can add something.
Pasting some content works initially, deleting it is also not possible. 
Thanks for this tool, it looks promising!

**Comment by alainm23** [comment]
Update to v4.5.1

**Comment by w-wagner** [comment]
Works! Thank you! Really fast!
