### ISSUE TITLE
Install Planify via Snapstore is aborted?!

### ISSUE THREAD

**Issue by carboncrystal** [alainm23/planify#1165]
### From your GitHub main page:

![Screenshot from 2024-03-01 04-06-14](https://github.com/alainm23/planify/assets/106466414/dc384090-7ba9-464e-be3c-7922dc4f78c6)

### No Planify app found via Snapstore:

https://snapcraft.io/planify > 404: Aw, snap! We couldn't find that page

### Search Planify via Google (planify snap store):
https://snapcraft.io/install/planify/ubuntu > 404: Aw, snap! We couldn't find that page

![image](https://github.com/alainm23/planify/assets/106466414/4dc22d58-35fb-4b20-876e-776eb95af949)

**Comment by alainm23** [comment]
I'm not sure what happened but it's available now,
