### ISSUE TITLE
Dragging tasks not possible

### ISSUE THREAD

**Issue by w-wagner** [alainm23/planify#1166]
**Describe the bug**
Following the introduction tasks, I cannot move/drag/reorder tasks . Tasks are opened, dragging is not initiated. 

**To Reproduce**
1. Sample project
2. Click and old a task
3. Try to drag it => does not work

**Expected behavior**
I am able to drag the task in front or behind other tasks

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - debian 12.5, cinnamon
 - planify Version 4.5, installed from flatpak

**Comment by alainm23** [comment]
Do you use Nvidia? Wayland or X11?

**Comment by w-wagner** [comment]
nvidia, with proprietary drivers and X11.
I am the one with the project drag and drop problem #1172
So dragging works. 
I have installed the flatpak version. Maybe you are using different dependencies?
I just checked that everything is recent. (flatpak update)
The problem still persists.

**Comment by Riksu9000** [comment]
Clicking and holding a task for too long before moving the mouse expands the task view, after which the task cannot be dragged. Maybe the view should expand only after releasing the click. Actions generally happen after releasing the click in other apps.

**Comment by alainm23** [comment]
Hi @w-wagner , this is still a problem for you? with the new versions of Planify the event to view a task is triggered by releasing the click and not by pressing click.

**Comment by w-wagner** [comment]
I can drag tasks now, can produce subtasks, and if I drag project subprojects.
I get empty lines in the list as described here: https://github.com/alainm23/planify/issues/1172

But I cannot move a task, nor a project to the end, to be the last element of the list. I always end up creating subitems or subprojects.

**Comment by alainm23** [comment]
Moving an element at the end is a feature that is under development, but is beyond the scope of this issue, thank you.
