### ISSUE TITLE
Phantom task cannot be deleted

### ISSUE THREAD

**Issue by SCoumes** [alainm23/planify#1167]
**Describe the bug**
A tasks keeps appearing in the "today" view and cannot be deleted or edited in any way. It remains even after all the projects have been removed and the application uninstalled and then reinstalled.
Note that this task does not appear in other tools that use the system's calendar.

**To Reproduce**
I am unsure which exact steps led to this situation and I do not know how to reproduce the problem.
Here are some steps I went through that I hope will be informative in solving the issue.
1. Create tasks and events in another task management app (framagenda), including the task that will become problematic, called "Test2".
2. Install planify and enable CalDAV sync with framagenda.
3. Delete all local projects in planify.
4. Remove Test2 from framagenda.
5. Notice its presence in Planify.
6. Attempt to delete the task in planify, nothing happens.
7. Disable CalDAV sync in Planify. The only task that still shows up is Test2, visible only in the "today" view, despite there being no project.
8. Uninstall and reinstall Planify, Test2 is still there.

**Expected behavior**
The tasks should disappear when deleted.

**Screenshots**
Don't have one.

**Desktop (please complete the following information):**
 - OS or DE: gnome on PopOS 22.04
 - Version: 4.5

**Additional context**
I have since solved the issue for myself by removing the folder ```~/.var/app/io.github.alainm23.planify``` after uninstalling Planify and then reinstalling Planify.
This renders me unable to make tests around this issue, as everything is now working perfectly for me.
I have kept the bit of the file ```~/.var/app/io.github.alainm23.planify/data/io.github.alainm23.planify/database.db``` that relates to this task. Finding it with ```grep -lr Test2``` is what led me to remove the folder in ```.var/app``` and solved my issue. See attached.
[databaseExtract.txt](https://github.com/alainm23/planify/files/14465866/databaseExtract.txt)

**Comment by alainm23** [comment]
You could upgrade to 4.5.4, the option to run in background has been removed to solve this problem.

**Comment by SCoumes** [comment]
I did the new update and intend to report here if I get any similar issues.

**Comment by alainm23** [comment]
I will close the Issue for now, if the error persists feel free to report it, Thank you.
