### ISSUE TITLE
What should happen if I want to delete a project that still contains tasks/subtasks?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#117]
One question for me would be whether it is important if the tasks/ subtasks in question are solved or unsolved. If they are unsolved, there might be the possibility to create a new project out of them or move them to other existing projects or decide that everything can be deleted - of course always with an undo option, as mentioned in https://github.com/alainm23/planner/issues/112#issuecomment-570778066.

The second point for me would be whether Planner should give a warning dialog if I want to delete a project that still contains active tasks/subtasks. Like this: "The project still contains 'n' (active) tasks/subtasks. Do you still want to delete it?"

How do you feel about that?

**Comment by alainm23** [comment]
I think it is not necessary to complicate with this. The user must be shown an alert indicating that if he accepts, all his tasks will be eliminated.

**Comment by 4jNsY6fCVqZv** [comment]
btw. What about the mentioned undo function? Possible? Makes sense? Separate issue?

**Comment by alainm23** [comment]
Thinking about UX, it is more common to delete tasks than projects or sections for this reason I think that only by deleting the tasks should it be possible to undo it.
