### ISSUE TITLE
Task disappears from Today/Planned after dragging it into project

### ISSUE THREAD

**Issue by w-wagner** [alainm23/planify#1171]
**Describe the bug**
I have created a task "Disappear from Today" in the project ToDos.

![grafik](https://github.com/alainm23/planify/assets/16692358/60a0ddd0-0ef8-4926-87ac-d4be12347d0e)

After some testing I found, that moving a task from "Today" view to a project (for instance ToDos) makes it invisible in "Today", although it is still a task for today. (Simple drag and drop)
![grafik](https://github.com/alainm23/planify/assets/16692358/e1a546c7-9a0b-4091-b1ea-39501ab9d6e6)

![grafik](https://github.com/alainm23/planify/assets/16692358/70e2c390-fd07-4e7a-b8e5-f28e5d2013eb)

The same thing "works" if I drag a task from calendar to a project. It disappears, although scheduling has not changed.
![grafik](https://github.com/alainm23/planify/assets/16692358/140ffcc6-86d3-46f0-bbb7-c305c2074e29)

![grafik](https://github.com/alainm23/planify/assets/16692358/6adb7eaa-5668-428a-9b24-fecda96b144b)

The tasks appear in Today and Planned again if you remove the schedule and create it again.

Maybe I got it wrong, but I thought, that the filter categories above cover all projects?

A question: In which project are task generated, when I create them in Inbox? 
Somehow I would expect that the current project is being highlighted.

**Comment by alainm23** [comment]
This is not expected behaviour, I will disable DnD for all views except the project view.
