### ISSUE TITLE
Shifting List items (reordering produces empty line)

### ISSUE THREAD

**Issue by w-wagner** [alainm23/planify#1172]
**Describe the bug**
I noticed, that moving projects and tags to reorder them produces empty lines, after you released the dragged item

![grafik](https://github.com/alainm23/planify/assets/16692358/deaf5e25-0b85-4aab-a236-eb7fb09bbcbe)

![grafik](https://github.com/alainm23/planify/assets/16692358/bd9619a1-b80d-475f-8390-2ce5a2f87e00)

Debian, Cinnamon, Planify 4.5.1

**Comment by alainm23** [comment]
I have not been able to reproduce this bug, do you use Nvidia? Wayland or x11?

**Comment by w-wagner** [comment]
Nvidia, and I am running the non-free drivers. I use X11.
I have tried the same in Gnome and XFCE. All of them show the behavior.

https://github.com/alainm23/planify/assets/16692358/ce429608-65b5-4dfa-8135-b4b6fdb5f709

If I can help with any further analysis?

**Comment by afuetterer** [comment]
I can confirm this. Happens to me as well, planify 4.5.2 an Linux Manjaro KDE, using nvidia.

**Comment by jajones87** [comment]
I happens **every** time I move something. Have to be careful about dropping items or they vanish into the void.
Running Kubuntu 23.10 with amdgpu; the planify packed in the published snap doesn't output a version with `-v`

**Comment by Dez1gner** [comment]
Yes, I have this happening too. Kubuntu 24.04.

**Comment by w-wagner** [comment]
I am testing using 4.9.0 Flatpak
Unfortunately, this behavior still exists.

The project view and the todo view (right) behave the same: 
When I move an item to be a subitem of another one, the empty line appears at the original position of the list item and stays. Like in the very first screenshot. Same, when I change the order. 
After restart of planify everything is fine again.

By the way: I am not able to place an item at the end of the list, without making it a subitem.

**Comment by alainm23** [comment]
I understand, this fix will arrive in version 4.10.
