### ISSUE TITLE
All tasks gone after update

### ISSUE THREAD

**Issue by Lich-Corals** [alainm23/planify#1173]
**Describe the bug**
I updated the app prom, planner to planify, and now all my projects and tasks are gone.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a task in Planner
2. Update Planner to Planify using flatpak
3. Open Planify and see that the app is reset

**Expected behaviour**
All tasks I've set up earlier in the same place as before the update.

**Desktop (please complete the following information):**
 - Fedora 39 ThirtyNine, Plasma 5.27.10 Wayland
 - Version 4.5

**Additional context**
My main question is, if there is any way to recover all the old tasks, without having a backup.

**Comment by alainm23** [comment]
Planify has an option to migrate. Go to Preferences, Backups and Migrate from Planner.

**Comment by Lich-Corals** [comment]
Thank you, that worked.
