### ISSUE TITLE
CalDAV Cannot move sub-task to another project

### ISSUE THREAD

**Issue by oktayacikalin** [alainm23/planify#1176]
**Describe the bug**
When I try to move a sub-task to another project, it just bounces back where it was.

**To Reproduce**
1. Create a task
2. Create a sub-task within the task above
3. Try to move the sub-task to another project
4. Sub-task bounces back

**Expected behavior**
When I move a sub-task out of a task, it will be converted into a normal task.
When I move a sub-task into another project, it should be converted into a normal task and moved into the project.

**Screenshots**
[Planify Cannot move sub-task into another project 2024-03-04, 10-18-37.webm](https://github.com/alainm23/planify/assets/687189/75077266-ce3b-4fed-8ff4-7ad373df61ef)

**Desktop (please complete the following information):**
 - Fedora 39, GNOME Shell 45.4
 - Planify 4.5.1 from flathub

**Additional context**
None

**Comment by oktayacikalin** [comment]
I'm not sure if this is really a bug or just a missing feature. Either way, I would be happy to have this functionality. :smile:

**Comment by alainm23** [comment]
The task should move.
