### ISSUE TITLE
Adding subtasks should auto-expand the subtask list

### ISSUE THREAD

**Issue by oktayacikalin** [alainm23/planify#1178]
**Is your feature request related to a problem?**
When I create a task and add some subtasks, they won't be visible.

**Describe the solution you'd like**
When I add a subtask and the list is not expanded (visible), it should automatically expand, so that I can see what I've added so far.

**Describe alternatives you've considered**
Perhaps it would be even better if Planify auto-expands subtask lists when I click and therefore unfold a task. This is also what NextCloud Tasks does.

**Additional context**
[Planify subtasks initially not visible 2024-03-05, 13-32-45.webm](https://github.com/alainm23/planify/assets/687189/f07b3a05-77cb-4c40-a30f-55ca63656072)

**Comment by alainm23** [comment]
It makes a lot of sense, I'll check it out, but first I'll send version 4.5.2 which fixes some problems with Nextcloud synchronisation.
