### ISSUE TITLE
Flatpak DBus for Nextcloud

### ISSUE THREAD

**Issue by saxc** [alainm23/planify#1179]
**Describe the bug**
With the default Flaptack settings, no connection to a NextCloud server was possible. No error was displayed in the UI. The error is only visible in the terminal, that the DBus authorizations are missing. After manually setting, a connection was possible.

**To Reproduce**

**Expected behavior**

**Screenshots**

![2024-03-06T16-07-41](https://github.com/alainm23/planify/assets/7613585/a6561bb7-3b74-461d-aba2-9351347aec08)

**Desktop (please complete the following information):**
- EndeavourOS (KDE Plasma) 
 - Version 4.5.2
 - Flatpack Version 1.15.6

**Additional context**

**Comment by alainm23** [comment]
I have not been able to replicate the error, what settings did you apply to make the connection work?

**Comment by saxc** [comment]
I hat set the "D-Bus session bus" and "D-Bus sysem bus" with  Flatseal. After this i add the NextCloud Account, all tasks was sync to Planify.

In Flatseal on the Session Bus grope i see.
- org.gnome.evolution.dataserver.Sources5
- org.gnome.evolution.dataserver.Calendar8

I can now add tasks to Planify that syncs to NextCloud, but it doesn't sync info back from NextCloud to Planify  (new Tasks, completion).

**Comment by privx-de** [comment]
Had the same problem on Fedora 39 Silverblue with the package from Flathub. DBUS session allowed, everything works as expected.

**Comment by alainm23** [comment]
We can't add the "D-Bus session bus" and "D-Bus system bus" configurations, they are very general and probably the Flathub team observes it, I can only try to replicate the error, any special configuration in your computer, processor, video card, etc?

**Comment by alainm23** [comment]
Hi, I will close this Issue for the time it has been inactive, if you reproduce the problem again, do not hesitate to create a new one.
