### ISSUE TITLE
Add subsequent task via ctrl+enter

### ISSUE THREAD

**Issue by oktayacikalin** [alainm23/planify#1180]
**Is your feature request related to a problem? Please describe.**
When creating new tasks with subtasks, which I do regularly, I have to cancel the second dialog in order to proceed with the subtasks and the "create more" option.

**Describe the solution you'd like**
1. Hit the big blue +-button to create a new task in a project
2. Enter title
3. Hit enter, which saves and closes the dialog ("create more" disabled)
4. Automatically unfold the new task and focus the +-button for adding subtasks
5. Hit enter key which pops up the add-subtask-dialog
6. Enter title for subtask
7. Hit ctrl+enter, which saves and asks for another subtask
8. Repeat step 6 and 7 several times
9. Hit enter without ctrl saves and closes the dialog without asking for more

"Create more" should be pulled out of the submenu and be visible all the time instead. Often times I don't know if it's activated or not. Perhaps it should also change to enabled as long as I hold the ctrl key. This would be a visual aid for what could happen next.

**Describe alternatives you've considered**
What also could work is that if the task in focus (unfolded) reacts to "a" for adding subtasks and "p" for opening the planning dialog.
But this would require, that only one task could be unfolded and therefore be in focus. As of now, I like having 2 tasks unfolded so that I can copy+paste data etc.. Perhaps we really need some real highlight as a focus indicator where task specific hotkeys could work? Keyboard navigation is still something I kind of dream for :-).

**Additional context**
[Bildschirmaufzeichnung vom 2024-03-07, 12-57-47.webm](https://github.com/alainm23/planify/assets/687189/c9c436da-26b4-4985-8761-57db2832b297)

**Comment by alainm23** [comment]
Keyboard shortcut added.
I will review the button design in more detail.

**Comment by alainm23** [comment]
A button will be used instead of a Popover Menu.

![image](https://github.com/alainm23/planify/assets/33765137/2b5ea50a-6671-4f66-b87b-eb04704208ec)
