### ISSUE TITLE
Select option id diasbled after open it

### ISSUE THREAD

**Issue by jasjastone** [alainm23/planify#1182]
**Describe the bug**
When you choose something when creating a to-do like choosing the schedule after you click it then you click away if you click it again it doesn't open

**To Reproduce**
1. Click on any option that has a drop-down menu(select option)
2. Click on it then click away

**Video preview**
[Screencast 2024-03-07 21:51:13.webm](https://github.com/alainm23/planify/assets/73587145/2d0990a8-6cb7-4ad3-9147-489cbfc417bb)

**Desktop (please complete the following information):**
 - OS Zorin 16.3 Pro gnome (not on way land)
 - Kernel Ubuntu 20.04
 - Version 4.5.2

**Comment by alainm23** [comment]
I have not been able to replicate the bug, do you have any special configuration on your computer, video card, processor?

**Comment by jasjastone** [comment]
Sorry to disappoint you but I decide to just use todoist direct since i was integrating it with planify, then i just want more things to be organize this was not due to the bug but rather the tasks i created previously before i installed todoist i could get them to sync, also the subt-tasks which i created from todoist they were not showing on planify they only show i think one level of subtask. as of now i don't have planify on my machine you could just close the issue.
