### ISSUE TITLE
Labels are Duplicated from Nextcloud

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#1184]
**Describe the bug**
When adding tasks from Nextcloud, labels are duplicated

**To Reproduce**
1. Create multiple tasks on Nextcloud
2. Add various labels to tasks
3. Connect planify to nextcloud
4. See that multiple duplicate labels are created on sync

**Expected behavior**
Labels should only appear once without duplication

**Screenshots**
![image](https://github.com/alainm23/planify/assets/47278150/c86d3632-fc2e-4799-b5e6-bda924f3b6e1)

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint Cinnamon 21.3 
 - Version: 4.5.2 (Flatpak)

**Additional context**

**Comment by BeatLink** [comment]
An update. The duplicate labels disappear when planify is restarted

**Comment by alainm23** [comment]
Upgrade to version 4.5.4 to fix the problem.
