### ISSUE TITLE
New tasks from other clients do not show up after first sync (CalDav)

### ISSUE THREAD

**Issue by brokoli18** [alainm23/planify#1185]
**Describe the bug**
I am running planify using the caldav/nextcloud integration. When I first set it up it successfully syncs all the todos from my nextcloud server. I can also add todos from here no problem. The problem is that if I add a todo via another client (like the nextcloud web interface or on my phone) it will not show up in planify. The only way to fix this that I found is to remove the `database.db` file in my home dir so another sync is retriggered. I am using planify version 4.5.2

**To Reproduce**
1. Add nextcloud integration in planify using caldav and perform first sync
2. Open another client and add a todo that way
3. Refresh tasks in planify or restart the application. The tasks added via another client are not visible

**Expected behavior**
Planify should be able to sync/display todos that are added via other clients

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS or DE: Pop OS 
 - Version 22.04

**Comment by jcberga** [comment]
Exact same Bug with zorin Zorin OS 17.1

**Comment by oktayacikalin** [comment]
It looks like I'm experiencing the same. But it also feels like it won't sync anymore at all (after the initial one). Can you provide us another dev build so that I can see what it does?

**Comment by alainm23** [comment]
Upgrade to version 4.5.4 to fix the problem.
