### ISSUE TITLE
WebDAV errors on Nextcloud logs caused by synching

### ISSUE THREAD

**Issue by starget24** [alainm23/planify#1186]
**Describe the bug**
Content itself is updated without problems and inspecting Planify in the terminal doesn't really show error apart from some gtk stuff, but reviewing the logs on the nextcloud server reveal some errors

**To Reproduce**
1. Go to 'Planify'
2. Click on 'sync icon (the one next to the add project icon)'
3. Content is updated normally, but reviewing logs in nextcloud server shows errors

**Expected behavior**
Nextcloud shouldn't throw error logs.

**Screenshots**

![image](https://github.com/alainm23/planify/assets/92924912/143fc04e-7d3c-4eb4-8bac-d78c63354d68)

**Desktop (please complete the following information):**
 - OS or DE: Fedora 39 
 - Version: Nextcloud 28.0.3 - Planify 4.5.2

**Additional context**
To be honest, i don't know if this is an actual issue on Planify, it might be my Nextcloud setup but, im opening this regardless cause i tried several caldav sync apps and they dont have this error, so it might help me debug what its actually happening. If this is an issue with my setup or nextcloud itself feel free to close this.

[Raw_Log_Entry.txt](https://github.com/alainm23/planify/files/14591864/Raw_Log_Entry.txt)

**Comment by alainm23** [comment]
What version of Nextcloud do you use? Are your tasks synchronising correctly? Planify uses a Sync Token to synchronise tasks, apparently your server does not support it.

**Comment by alainm23** [comment]
I know what happened, I see you have Nextcloud Deck enabled, the Sync Token does not work with your Deck type task lists, with the new update this should no longer happen.
