### ISSUE TITLE
Done tasks on other clients does not marked as done in Planify

### ISSUE THREAD

**Issue by Shahin-rmz** [alainm23/planify#1189]
**Describe the bug**
My instance is synced via Nextcloud. Recently, I have seen  a phenomen, if I check a task as done in mobile, it does not marked as done in planify.

**To Reproduce**
1. Click done a task on other instances (Tasks app Anfdroid)
2. sync the Tasks app Android
3. Open planify and sync 
4. The task is still there unchecked.

**Expected behavior**
The task on Planify should be marked as done. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS x86_64

 - Version [4.5.2]

**Comment by alainm23** [comment]
Upgrade to version 4.5.4 to fix the problem.

**Comment by Shahin-rmz** [comment]
Hello,
The App is updated, It works sometimes but does not work sometimes. I tried to observe the pattern and tell you how the bug is working but couldn't find a patterns.
It seems if I mark a task in `Tasks` app on Android yesterday and sync the planify app a day after, it does not get marked.

**Comment by alainm23** [comment]
The same thing happened to me with Tasks.org, it is necessary to force the update. Edit a task and reload the main view (Sliding down).
