### ISSUE TITLE
libecal not found

### ISSUE THREAD

**Issue by codeitlikemiley** [alainm23/planify#119]
I tried installing planner using YAY package manager of archlinux.
Im using kernel 
But it failed missing a dev dependencies 
libecal not found.
Hope someone can share a solution on this...

**Comment by alainm23** [comment]
I'm sorry but Planner is not officially available on Archlinux. However, you can try Planner using Flarpak: https://planner-todo.web.app/planner-beta-blog

**Comment by printfdebugging** [comment]
i built it locally, it complained about missing `libecal-2.0` dependency, installing `evolution-data-server` fixed that error
