### ISSUE TITLE
Context menu doesn't appear in task marked as complete

### ISSUE THREAD

**Issue by subhoghoshX** [alainm23/planify#1194]
**Describe the bug**
Same as title.

**To Reproduce**
1. Create a new task
2. Right click on it (the context menu appears)
3. Mark it as completed
4. Right click on it again (the context menu doesn't appear)

**Expected behavior**
I wanted the context menu to appear so that I can delete it.

**Desktop (please complete the following information):**
 - OS or DE: GNOME 45
 - Planify Version: 4.5.4

**Comment by alainm23** [comment]
It is correct, being a completed task disables the option to edit, use the context menu or move the task, it is necessary to decomplete to return to edit and have the context menu enabled.

Although it makes a lot of sense to enable the delete option, I will consider it as an improvement.
