### ISSUE TITLE
Segfault when clicking "Add Task" if New Task Position setting is Top

### ISSUE THREAD

**Issue by folknor** [alainm23/planify#1196]
**Describe the bug**
Segfault when I click the blue plus button, whether I'm at the startup "Add Some Tasks" screen or in the "Meet Planify" list(?) under On This Computer.

**To Reproduce**
1. git clone repo
2. Follow build and install instructions in readme
3. Start app
4. Click +

**Desktop (please complete the following information):**
 - OS or DE: ubuntu noble, gnome-shell 45.3, kernel 6.7.8-060708-generic, X11, intel display driver
 - Version: latest git as of 15 minutes ago, 728ec11

Console output
```
$ io.github.alainm23.planify

(io.github.alainm23.planify:1961817): Gtk-CRITICAL **: 13:35:49.251: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

(io.github.alainm23.planify:1961817): GLib-GObject-CRITICAL **: 13:35:49.260: invalid cast from 'LayoutsSectionRow' to 'LayoutsSectionBoard'

(io.github.alainm23.planify:1961817): Gtk-CRITICAL **: 13:35:49.500: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify:1961817): Gtk-CRITICAL **: 13:35:51.440: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

(io.github.alainm23.planify:1961817): GLib-GObject-CRITICAL **: 13:35:51.510: invalid cast from 'LayoutsSectionRow' to 'LayoutsSectionBoard'

(io.github.alainm23.planify:1961817): GLib-GObject-CRITICAL **: 13:35:51.531: invalid cast from 'LayoutsSectionRow' to 'LayoutsSectionBoard'

(io.github.alainm23.planify:1961817): GLib-GObject-CRITICAL **: 13:35:51.561: invalid cast from 'LayoutsSectionRow' to 'LayoutsSectionBoard'
[1]    1961817 segmentation fault  io.github.alainm23.planify
```

I tried it three times now and same result every time.

Thank you!

**Comment by folknor** [comment]
Aha yes indeed, thank you! :-) I'll change the issue title if I can.

**Comment by alainm23** [comment]
I'm sending an update to fix the bug.
You could change the New Task Position preference to 'Bottom' to fix the problem for now.
![image](https://github.com/alainm23/planify/assets/33765137/f93c208b-2f34-45dc-89a2-7cdbd30bbd0d)
