### ISSUE TITLE
Crash with my CalDAV server/provider

### ISSUE THREAD

**Issue by rene-coty** [alainm23/planify#1197]
**Describe the bug**

I use [murena.io](https://murena.io/) as my cloud provider, it is based on Nextcloud and uses CalDav to sync my calendar and tasks on my various devices/apps.
When I provide my credentials in Planify, the app will freeze and crash. If I open it again it will try to sync with my account and crash again, and again, making the app unusable unless I disconnect my laptop from Internet to stop the sync and deactivate CalDav integration in Planify.

**To Reproduce**

1. Go to 'Integrations'
2. Toggle 'CalDav' on
3. Type 'https://murena.io/' in the server entry field and provide your credentials
4. Click 'Connect' and wait → crash after a few seconds

**Expected behavior**

Planify should sync with my account without problem, it works on many other apps I have tested on Linux so far (Errands…). The problem doesn't come from my credentials, because Planify will display a proper error message if the URL or the password/username aren't correct.

**Screenshots**

[Capture vidéo du 2024-03-21 09-15-35.webm](https://github.com/alainm23/planify/assets/95506494/91f99980-5435-4437-b910-c93ab3ebc833)

**Desktop (please complete the following information):**
 - OS or DE: GNOME
 - Version 45.5

**Comment by alainm23** [comment]
What version of Nextcloud Hub are you using? For now we only test on NH 7 onwards.

**Comment by rene-coty** [comment]
Apparently I'm running Nextcloud 26.0.8.12, but I don't know to which version of NH it refers

**Comment by sebastiaanfranken** [comment]
I am running into the exact same issue. I am using Nextcloud 27.1.7 and 28.0.3 and it does add my CalDav info, and I can add projects, but the very first time the app crashes for me as well, and projects are *not* shared.

Desktop:
- OS or DE: Fedora 39, 40 and Rawhide with GNOME
- Version: 45 and 46

**Comment by alainm23** [comment]
@rene-coty I have just created an account and have no problem, approximately how many task lists and to-do do you have, including completed ones?

**Comment by rene-coty** [comment]
I have 4 lists, with 26 tasks + 34 completed that I've deleted (yet it still crashes)
What's the server URL you used to log in ?

**Comment by alainm23** [comment]
Server URL
https://murena.io/

User:
alainmh23

![image](https://github.com/alainm23/planify/assets/33765137/d0204b0c-886b-470f-903c-0401ba6c72e3)

**Comment by alainm23** [comment]
@rene-coty  It seems the problem is your Username, you could try the username instead of your email.

![image](https://github.com/alainm23/planify/assets/33765137/55893a90-80b4-4638-ae94-8b5470326fa4)

**Comment by rene-coty** [comment]
Yes I tried with other usernames but it ended up with an error message saying username/password was incorrect

**Comment by rene-coty** [comment]
This is what I get in my terminal, when I launch Planify 4.5.4 and enter my credentials:

```
[ireneethirion@laptop ~]$ flatpak run io.github.alainm23.planify

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 21:22:31.859: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 21:22:32.108: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed
**
ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
Bail out! ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)

[ireneethirion@laptop ~]$ 
```

The first 2 warnings appear at the very opening so it's probably nothing important.
The error message is what I get when the app has crashed after I've entered my credentials.

**Comment by sebastiaanfranken** [comment]
I'm getting the exact same error as @rene-coty when running Planify via the terminal.

**Comment by asubedi** [comment]
I'm also getting the exact same error as @rene-coty and @sebastiaanfranken when running Planify via the terminal.

**Comment by byquanton** [comment]
It appears that if the Nextcloud Account has a list that was created by [Errands](https://apps.gnome.org/List/), the tag `x1:calendar-color` isn't defined. Which itself causes `get_element (0)` to return null.

[core/Objects/Project.vala](https://github.com/alainm23/planify/blob/2fd3ecb894f0f7fa08df078617e1a201d14faff9/core/Objects/Project.vala#L327C6-L327C99)
```vala
    public void update_from_xml (GXml.DomElement element, bool update_sync_token = true) {
        GXml.DomElement propstat = element.get_elements_by_tag_name ("d:propstat").get_element (0);
        GXml.DomElement prop = propstat.get_elements_by_tag_name ("d:prop").get_element (0);
        name = get_content (prop.get_elements_by_tag_name ("d:displayname").get_element (0));
        // -v- This causes the program to crash -v-
        color = get_content (prop.get_elements_by_tag_name ("x1:calendar-color").get_element (0)); 

        GXml.DomHTMLCollection sync_token_collection = prop.get_elements_by_tag_name ("d:sync-token");
        if (update_sync_token && sync_token_collection.length > 0) {
            sync_id = get_content (sync_token_collection.get_element (0));
        }
    }
```

**Comment by rene-coty** [comment]
Seems correct :) I deleted all the lists I created through Errands on my account and now I can connect without any problem
