### ISSUE TITLE
Missing Icons in Quick Add Menu

### ISSUE THREAD

**Issue by Legotier** [alainm23/planify#1198]
**Describe the bug**
When opening the quick add menu via a global keyboard shortcut, the icons aren't displayed properly (see screenshot below). They do work when opening the same window via the app itself though.

**Screenshots**
![image](https://github.com/alainm23/planify/assets/66439435/23e530e2-996a-4f17-8542-89cafa18d076)

**Desktop (please complete the following information):**
Fedora 39, GNOME 45.5

**Comment by alainm23** [comment]
Did you install Planify from Flathub?

**Comment by Legotier** [comment]
> Did you install Planify from Flathub?

Yes
