### ISSUE TITLE
cohesive elementary experience

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#120]
Should a title-bar not be used for the app, so that a more cohesive feel for elementary (main target) would be achieved?

Having all user actions located in the title.

![image](https://user-images.githubusercontent.com/59498682/71800762-a10a7700-3061-11ea-9019-d891b8d08ebe.png)

**Comment by 4jNsY6fCVqZv** [comment]
Do you have an example from another native elementary app or from the HIG to which you are referring?

**Comment by ghost** [comment]
Optimizer, Mail, Document Viewer, LookBook, files

![image](https://user-images.githubusercontent.com/59498682/71810000-fc486380-3079-11ea-9b6b-03c877eceb75.png)

**Comment by alainm23** [comment]
@4jNsY6fCVqZv  Of course, these are small details that I have not yet developed by focusing more on the main functionality.

**Comment by alainm23** [comment]
@inputbim Believe me I tried, but I did not like the final result.
However, the latest apps that elementary is developing tend to use this same design line.
- https://github.com/elementary/tasks
- https://github.com/elementary/granite/pull/315
- https://github.com/elementary/friends/pull/7
