### ISSUE TITLE
Feature Request: Add "Anytime" Section to Sidebar for Tasks with No Due Date

### ISSUE THREAD

**Issue by wada3n** [alainm23/planify#1200]
Hi,
**Description**:

I would like to request a new feature in the Planify app to display all tasks that do not have a due date set. This feature could be called "Anytime" or any similar name such as "Unassigned" or "Not Scheduled."

**Purpose:**

- To make it easier to access tasks that do not have a due date set.
- To save time and effort spent searching for these tasks in different projects and sections.

**Functionality:**

- Add a new section to the sidebar called "Anytime."
- Display all tasks that do not have a due date set in this section.
- Sort tasks by project.
- Allow users to select tasks and take action on them.

**Use Cases:**

- This feature could be used to view all tasks that you would like to complete at some point, but have not set a specific date for.
- It could be used to view all tasks that require more research or information before a due date can be set.
- It could be used to view all tasks that have been postponed for various reasons.
- This addition can allow the user every day to take a look at all the tasks and choose what he wants to add to the Today's work.

> Personally, I work around this by using labels. I add a "Someday" label to tasks that I haven't assigned a time to yet. This allows me to see them all at once by selecting this label. However, this method has some drawbacks and requires an extra step. Additionally, I can't select multiple tasks from label view.

Thank you for your time and consideration.

**Comment by alainm23** [comment]
I am working on adding new filter views such as Tomorrow, No Labels, All tasks. I will consider an Anytime filter as well.
