### ISSUE TITLE
Expand details of tasks via button instead of clicking on it

### ISSUE THREAD

**Issue by oktayacikalin** [alainm23/planify#1201]
**Is your feature request related to a problem? Please describe.**
Most of the time, I try to move tasks around, which most of the time results in expanding the task, instead of starting the drag-n-drop action.

**Describe the solution you'd like**
When I click and hold a task, it should never expand, just start the dnd action.
When I click a small "i"-button, it should expand to details.

**Describe alternatives you've considered**
Perhaps it's possible to fine-tune the timings for deciding on which action the user meant.

**Additional context**
None

**Comment by alainm23** [comment]
I understand, currently the waiting time to drag a task is 250ms, if in that time the task is not dragged it expands. As a solution I could add a configuration to open the detail of a task using double click or increase the time to 300 or 350ms.

**Comment by oktayacikalin** [comment]
Double click does not seem intuitive to me. It's not a file in a file explorer, after all. And I don't want another config setting - less is more here.

I think, the expand action should only trigger if I press and release on the same task (typical click action).
Is there a movement threshold as when a dnd is considered, or is it just timeout based?

As for the timeout... what about 750ms? Is it too sluggish?

**Comment by alainm23** [comment]
750 is too slow

[Screencast from 2024-03-27 20-02-19.webm](https://github.com/alainm23/planify/assets/33765137/5300899c-8536-4278-b291-5093002fed52)

**Comment by oktayacikalin** [comment]
Hmm.. I see...

How does the logic work?

What about unfolding a task on a single click? (press-release-cycle)

I just went thru the tutorial again, and it says to press and hold a task to move it. But when I press and hold a task, it will expand after the timeout. Can you change the logic to only unfold when pressing and releasing without a significant movement?

**Comment by andreyrd** [comment]
Expanding on the "release" of the mouse would be much more intuitive (and like most other software out there) than expanding after press + delay.

**Comment by qwertele** [comment]
Thank you so much for this fix!
It was driving me crazy while using the touchpad, where im not as fast as with a mouse, but i just assumed it was a problem on my end...
