### ISSUE TITLE
Application name is shown as 'Alain' instead of 'Planify' in Flatpak

### ISSUE THREAD

**Issue by Gert-dev** [alainm23/planify#1204]
**Describe the bug**
In `flatpak list` or [Warehouse](https://flathub.org/apps/io.github.flattool.Warehouse), the application name is shown as 'Alain', which doesn't seem intentional and should probably be 'Planify'. :wink:

**To Reproduce**
1. Execute `flatpak list`
2. See the name of the application being 'Alain'.

**Expected behavior**
The name of the application is 'Planify'.

**Screenshots**
![image](https://github.com/alainm23/planify/assets/24809863/a9f56405-d52c-49a1-8cb2-465f2a312921)

**Desktop (please complete the following information):**
 - OS or DE: GNOME
 - Version: 4.5.8

**Comment by alainm23** [comment]
This has been fixed. Thank you for reporting it.
