### ISSUE TITLE
Planify lists nextcloud calendar events as tasks

### ISSUE THREAD

**Issue by moshiur-raj** [alainm23/planify#1209]
Newly created calendar events in nextcloud are shown as tasks in planify. If I mark the task as completed the calendar event is deleted. But these events are not listed as tasks in nextcloud web or in Endeavor.

**Comment by oktayacikalin** [comment]
Same here - happens with combined calendars. I haven't noticed it yet, because I've calendars for either events or tasks, not both at the same time.

**Comment by moshiur-raj** [comment]
@alainm23  After the latest commit planify crashes after adding a calendar event.

```
(io.github.alainm23.planify:2): Gtk-CRITICAL **: 05:09:14.661: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 05:09:14.661: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed
**
ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
Bail out! ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
```

**Comment by alainm23** [comment]
@moshiur-raj What version of Nextcloud are you using?

**Comment by moshiur-raj** [comment]
@alainm23 Nextcloud 28.0.3.2

**Comment by alainm23** [comment]
Could you install this devel version and check if the error persists?
https://github.com/alainm23/planify/actions/runs/8480460211
![image](https://github.com/alainm23/planify/assets/33765137/ff3bb656-845f-4f1d-8d92-f078980d0ff9)

**Comment by jomaway** [comment]
@alainm23  seems to work. I had a similar or the same problem #1227 

> Could you install this devel version and check if the error persists?

With this version it starts at least. Don't know about the other error with adding calendar events.
