### ISSUE TITLE
completed tasks to stay in there section

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#121]
Think the completed tasks should stay under the respected category not new "TASK COMPLETED"

![image](https://user-images.githubusercontent.com/59498682/71807740-a9b87880-3074-11ea-9e20-e70346f20b6a.png)

**Comment by 4jNsY6fCVqZv** [comment]
Does it need an extra section "Task completed" in your perception? When I look at the Agenda app for elementary OS: Doesn't a crossed out task already mean that the task is completed?

Then the tasks could just stay where they are after they have been checked off. Or they could automatically move to the end of the list within the respective category?

On the other hand, a visual separation can be a support to enable clarity. But maybe it is also possible to leave the completed tasks in place, but cross them out and in addition grey them out?

But yes, I know the variant with an extra section from other apps as well.

I'm not sure what is necessary, useful and desirable in terms of user experience.

@alainm23 How do you feel about this?

**Comment by alainm23** [comment]
I did Planner with this behavior for these reasons:
- To make the view of your project look clean.
- To make the task load faster. Think about this, what else is there? tasks created or tasks completed? The answer is completed tasks: if I charge all completed and unfinished tasks, Planner would take a long time to start.
### Let's analyze how other projects do it:
- Todoist, Google Task: You complete the tasks and it disappears but it gives you a toast to undo it.
- Things 3: When completing a task, Things 3 makes a banner appear at the top of your project so you can disappear all those completed tasks.

I really like the way Things 3 does but this feature is subject to a UX study. If you have a better idea let me know 😉️.

**Comment by ghost** [comment]
I use iOS reminder, there tasks that are completed simple hide, if you select show completed taks, the appear and they are ticked.

![image](https://user-images.githubusercontent.com/59498682/71825251-23b42600-30a4-11ea-9e10-f9b7516120b6.png)

think in terms of digital UX, apple has kind of got the gold standard.

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/79033418-caacd000-7b73-11ea-87b0-54b90efccb5b.png)

**Comment by 4jNsY6fCVqZv** [comment]
Will there still be a switch in the menu to show or hide the completed tasks?

**Comment by alainm23** [comment]
Yes.

**Comment by 4jNsY6fCVqZv** [comment]
Is this setting adjustable per project? Can't find the issue, we had thought about it, I think.

**Comment by 4jNsY6fCVqZv** [comment]
Is this a setting that I can make per project and that will remain after restarting Planner?
I can't find the issue right now, I think we had thought about it.
