### ISSUE TITLE
Unable to retrieve previously scheduled tasks after last update

### ISSUE THREAD

**Issue by Fragolone** [alainm23/planify#1211]
I cannot see any of the previously scheduled tasks after the recent update to version 4.5.8

1. update the Planify version to the 4.5.8
2. open the software
3. see the home page or browse the other sections
4. no event is shown

I expected the update not to be disruptive and keep all the previously scheduled tasks.

 - Ubuntu Mate 23.10  - kernel 6.5.0-26-generic #26-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar  5 21:19:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by alainm23** [comment]
I'm not sure what could have happened, this new update just brings new icons. Have you verified by killing the Planify process and running it again? Do I generate a backup copy? if so could you see if the JSON file has your tasks?

**Comment by alainm23** [comment]
Hi, I will close this Issue for the time it has been inactive, if you reproduce the problem again, do not hesitate to create a new one.
