### ISSUE TITLE
Task action button tooltips aren't translated (but are translatable?)

### ISSUE THREAD

**Issue by Gert-dev** [alainm23/planify#1216]
**Describe the bug**
The task action tooltips don't appear to be translated. I [can find some of them in the translation files](https://github.com/alainm23/planify/blob/master/po/nl.po#L594), though.

The priority dropdown items also aren't translated.

**To Reproduce**
1. Open the application in another locale (e.g. Dutch).
2. Hover over the task action buttons when expanding an existing task.
3. Observe them not being translated.
4. Click 'Set The Priority'
5. Observe the dropdown items also not being translated.

**Expected behavior**
The tooltips and dropdown items are translated.

**Screenshots**
![image](https://github.com/alainm23/planify/assets/24809863/a859c7b4-f224-4a3f-a96c-a94da3761513)

![image](https://github.com/alainm23/planify/assets/24809863/3a09dc68-4598-4f80-97d1-0cafb784b20a)

**Desktop (please complete the following information):**
 - OS or DE: GNOME
 - Version: 4.5.10

**Additional context**
The 'pin' button tooltip _is_ translated, strangely enough, it's just the four other actions that aren't:

* Add Subtasks
* Add Labels
* Set The Priority
* Add Reminders

... and also the priority dropdown tooltips also isn't translated, as mentioned.

**Comment by alainm23** [comment]
The translation files were updated, you could generate a PR to update the translation.
