### ISSUE TITLE
High RAM usage when viewing completed tasks

### ISSUE THREAD

**Issue by wada3n** [alainm23/planify#1217]
Dear @alainm23 ,

First of all, I would like to thank you for the amazing work you are doing on the Planify app. 
I really appreciate the way you are constantly adding new features and improvements to the app. The latest update is particularly impressive.
_________________________________________

I am reporting a high RAM usage issue, Whenever I click on the "Completed" to view completed tasks, the app loads all of the tasks into memory. When I exit the tab and return to it again, it loads a new instance of the data into memory again. I tested this by entering the tab repeatedly 3 times, and the RAM usage reached 1.3 GB for only 100 tasks.

**Comment by alainm23** [comment]
There is no precise way to free memory, but I will upload an update to improve it.
