### ISSUE TITLE
Inbox, Today & Upcoming View, should show a placeholder when there are no tasks

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#122]
Read more at https://github.com/alainm23/planner/issues/113#issuecomment-570796668

**Comment by alainm23** [comment]
Of course my friend.

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/72186518-74d55a00-33c3-11ea-875e-7e679fd4cd39.png)

What do you think?

**Comment by 4jNsY6fCVqZv** [comment]
Visually it looks very good to me!
Not sure about the placeholder text itself yet.
To better understand this, I have a question: What exactly is the function of the Inbox?
For example, when I think of a solely local use of Planner.

Do you already have screenshots for the other views?

**Comment by 4jNsY6fCVqZv** [comment]
Can you please show how you solved it?

**Comment by alainm23** [comment]
The same design that I sent above.

**Comment by 4jNsY6fCVqZv** [comment]
For Inbox or also for the other views?

**Comment by alainm23** [comment]
For all views except Upcoming.

**Comment by 4jNsY6fCVqZv** [comment]
Haha **all** means "Inbox" and "Today"?
Why not for "Upcoming"?
For example, what happens to the view if the calendar integration is disabled and/or no tasks have been assigned a due date?
