### ISSUE TITLE
CalDAV Task is marked as repeating but should not

### ISSUE THREAD

**Issue by oktayacikalin** [alainm23/planify#1221]
**Describe the bug**
I've a bunch of tasks which are shown as repeating tasks, but they should not. I cannot really say how it came to this but those have never been configured as repeating tasks. Perhaps they inherited this value from the task before? Like in forgot to unset the repeating value during import/sync.

**To Reproduce**
1. Open tasks list
2. Open first repeating task
3. Open second non repeating task
4. Second task has same repeating value

**Expected behavior**
Of course the one-time task should be shown as such.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS or DE: [e.g. pantheon, unity, gnome]
 - Version [e.g. 0.1.2]

**Additional context**
It looks like it happened during a sync some time ago. I will try to reproduce it somehow.
Those one-time tasks look normal:

```
BEGIN:VTODO
DTSTAMP:20240308T121103Z
UID:f63ede61-7261-4820-a8b4-90a9b3667a0d
SEQUENCE:5
CREATED:20230913T170723Z
LAST-MODIFIED:20240308T121006Z
SUMMARY:Dings für unsere Kinder abschließen
PRIORITY:5
STATUS:NEEDS-ACTION 
DUE;TZID=Europe/Berlin:20231005T123001
END:VTODO

BEGIN:VTODO
DTSTAMP:20240322T112205Z
UID:f9d92eb0-d4fd-4be5-9ada-e5e99f485296
CREATED:20240322T112133Z
LAST-MODIFIED:20240322T112133Z
SUMMARY:xyz will Frau Name eine email schreiben 
PRIORITY:1
STATUS:NEEDS-ACTION
DUE;TZID=Europe/Berlin:20240411T100000
END:VTODO
```

**Comment by McBaumwolle** [comment]
I can confirm this, and it seems to only affect incoming tasks from Nextcloud (as far as my testing goes). 

![image](https://github.com/alainm23/planify/assets/67203883/fe48d2e0-186e-4742-af01-32a07b58a658)
