### ISSUE TITLE
Planify Crashes when syncing to nextcloud

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#1228]
**Describe the bug**
Whenever I attempt to sync Planify with my nextcloud instance, Planify will crash after a few seconds

**To Reproduce**
1. Start planify from terminal
2. Create a nextcloud account and sign in
3. Click on the sync button
4. Wait for planify to close
5. See error

**Expected behavior**
Planify should not crash when syncing to nextcloud

**Screenshots**

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint 21.3
 - Version 4.5.11 (Flatpak)

**Additional context**
>ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
Bail out! ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)

**Comment by alainm23** [comment]
Update to 4.5.12

**Comment by oktayacikalin** [comment]
Same here. 4.5.12 works again :+1:
