### ISSUE TITLE
Can I make a backup copy or similar to export all of my Projects to another laptop? If so, how? Thankyou

### ISSUE THREAD

**Issue by watjilpa** [alainm23/planify#1235]
Please, see title. This is my first time in the forum so mi apologies if I have missed something (labels, mostly).

**Comment by alainm23** [comment]
You can create a backup from the preferences and import them.

![image](https://github.com/alainm23/planify/assets/33765137/117d4782-f8cc-47d4-b3ce-ca895c17ee3b)

**Comment by watjilpa** [comment]
Thank you Alain. However this would solve my problem if the preferences
menu was available, which is not. I have posted a new query in github where
the issue is detailed. It seems that flatpak installation (see commands
used in the query) provides a non fully functional version of Planner where
some important features are missing, such as the one that allows backup.
Again, please see my new query. Thank you in advance for your prompt
response.

**Comment by alainm23** [comment]
I understand you are still using Planner? Planner is no longer supported, you can use Planify instead. Planify offers you the option to migrate from Planner, please note, thank you.

**Comment by watjilpa** [comment]
Thank you Alain. Thing is I upgraded to 22.04 and finally got to install
planify... Works like a charm! Preferences are visible at last! One final
question. I am trying to migrate all of my projects from planner; I see the
option "migrate from planner". Apparently there is no backup copy (of
course I could not backup anything in the old Planner as the option was
missing). I would appreciate your advice as to how to recover my projects
in the old Planner, maybe by navigating to some directory I would find a
key file that would do the trick through the option "import". Any
suggestions? Thank you for your patience. Kind regards

**Comment by alainm23** [comment]
This would be the solution:

1. install Planify and migrate from Planner (I understood you already performed this step).
2. Go to the Backup section and create a new one.
3. Download the backup by clicking the download button.
4. On your new computer, install Planify and import the downloaded backup.

**Comment by watjilpa** [comment]
Alain: Muchas gracias por toda la atención que me has dedicado. Decirte
que, una vez instalado, Planify es una magnífica aplicación, con
presentación y funcionalidades estupendas. Creo que tiene mucho mérito como
proyecto personal y, desde luego, en lo que respecta a la atención y
mantenimiento. Si funcionas con donaciones, me gustaría compensar el
esfuerzo y la dedicación con una aportación (modesta). Así, te agradecería
que me indicaras si esto está previsto en la web de la aplicación con algún
enlace a ella o similar. Saludos desde Madrid.

**Comment by alainm23** [comment]
Thank you for using Planify, we have a support section in the preferences.

![image](https://github.com/alainm23/planify/assets/33765137/395167b7-d8e6-44ee-aaa2-2029b36fe4ae)
