### ISSUE TITLE
Planner does not display features as it should: cannot make a backup copy amongst others

### ISSUE THREAD

**Issue by watjilpa** [alainm23/planify#1237]
Ubuntu 20.04 Installed Planner via Flatpak with the following commands:
sudo apt update && sudo apt upgrade
sudo apt install flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub com.github.alainm23.planner

Planner opens but does not show, it seems, full features. For instance, I tried to get a backup copy and got almost immediate response from Alan (thank you) with a simple solution: open preferences and make backup. And then the issue was marked as closed.

Problem is that the preferences (or settings) menu does not show such option. An I am sure that there are many more missing options. So, question is: can I install Planner from an alternative source with full functionalities?

Please see the screen capture with the limited settings I get, so that you may have an idea of the problem I am facing. Thank you.

![Planner settings](https://github.com/alainm23/planify/assets/166117120/85b8a33d-1643-4978-92c5-10b3772ab4d4)

**Comment by alainm23** [comment]
Hi, Planner is no longer supported, use [Planify](https://flathub.org/es/apps/io.github.alainm23.planify) instead. To migrate your data you can use the migration option that Planify offers.
