### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Alexandos** [alainm23/planify#1238]
**Title:** Application Crashes on Startup

https://github.com/alainm23/planify/assets/166318450/873640a1-6949-4c10-8ab9-ddebca000dfe

**Description:**
Everything was working fine until a sudden issue occurred that causes the application to crash. The crash happend at ~450 milliseconds into the startup  process(lol). A part of the interface manages to load, and a notification reminder appears.

- **Environment:** [Hyprland]
- **Operating System:** [Artix linux]
- **Application Version:** [Last from git]

~/> planify

** (planify:5207): CRITICAL **: 22:12:08.054: util_get_todoist_datetime: assertion 'date != NULL' failed

(planify:5207): GLib-CRITICAL **: 22:12:08.054: g_date_time_difference: assertion 'end != NULL' failed

** (planify:5207): CRITICAL **: 22:12:08.054: string_to_string: assertion 'self != NULL' failed

** (planify:5207): CRITICAL **: 22:12:08.055: services_database_set_parameter_str: assertion 'val != NULL' failed

** (planify:5207): CRITICAL **: 22:12:08.055: string_to_string: assertion 'self != NULL' failed
**
ERROR:arraylist.c:745:gee_array_list_real_get: assertion failed: (index < _size)
Bail out! ERROR:arraylist.c:745:gee_array_list_real_get: assertion failed: (index < _size)
fish: Job 1, 'planify' terminated by signal SIGABRT (Abort)

**Comment by alainm23** [comment]
Are you using a version installed by git? 
You should use the version available on Flathub.

**Comment by Alexandos** [comment]
Because there is no Flathub on Artix and i do not wish to install Flatpak, all programs work perfectly and integrate well with the system through Git. Planify also worked. I have been using it for a long time. But recently, this bug occurred. I tried updating system and reinstalling the program, but it didn't help. Maybe it's worth manually reinstalling some modules or deleting some folders to reset.
Thank you in advance for your understanding and help!

**Comment by Alexandos** [comment]
It's okay to lose all local tasks (if needed), as all tasks are stored in the todoist.

**Comment by alainm23** [comment]
Sorry, I've been uploading changes to the master branch that break the app, I just uploaded a change, could you check it again.

If the error persists, restart Planify.

io.github.alainm23.planify -r

**Comment by Alexandos** [comment]
Thx!
