### ISSUE TITLE
planner beta not launching on archlinux after installing from flatpak

### ISSUE THREAD

**Issue by goldcoders** [alainm23/planify#124]
**Describe the bug**
i follow installation here for not elementary OS disto
https://planner-todo.web.app/planner-beta-blog

Im using archlinux , with i3 gaps , im not using any desktop only window manager

**To Reproduce**
1. flatpak -v run com.github.alainm23.planner

```
  flatpak -v run com.github.alainm23.planner
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/uriah/.local/share/flatpak
F: Opening user flatpak installation at path /home/uriah/.local/share/flatpak
F: Opening user flatpak installation at path /home/uriah/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 1242644538
F: Cleaning up unused container id 314585946
F: Allocated instance id 307290841
F: Add defaults in dir /com/github/alainm23/planner/
F: Add locks in dir /com/github/alainm23/planner/
F: Allowing homedir access
F: Allowing wayland access
F: Allowing x11 access
F: Running 'bwrap --args 27 xdg-dbus-proxy --args=33'
F: Running 'bwrap --args 30 com.github.alainm23.planner'

```
**Expected behavior**
App should be running / launch

**Comment by goldcoders** [comment]
it did launch after 30secs or a  minute or so... but that is way too slow 
ive tried this before on VM using elementary OS it  started around few secs around 5 or 10... with limited ram...
Any reason why this is launching the app very slow?

**Comment by alainm23** [comment]
In my case it starts around 2 to 3 sec. Not sure why this happens. Planner 2 was built thinking of always starting fast.

**Comment by goldcoders** [comment]
I uploaded a video on how i try to launch this with verbose , so we can see the logs
also you will see it will start very slow, It should be starting very fast im using a latest laptop

https://youtu.be/jEkb27cZv6U

**Comment by alainm23** [comment]
It's true, what patience you have. Have you tried any other application using Flatpak?

**Comment by goldcoders** [comment]
when will this be uploaded in flathub? I think it would be better if i wait the stable version...
This App looks promising, looking forward for stable version in version 2, 
or much better if this is available in Arch AUR , than flatpak  ,
I did tried to installed this on arch but it failed due to some dev dependencies...
arch uses always the latest package so the old packages if i installe them it would be compatible
thanks for the great app anyway keep up the good wowrk

**Comment by alainm23** [comment]
I have registered some errors to solve before a release. I think it shouldn't take more than 2 weeks.

**Comment by goldcoders** [comment]
i think i found a solution on this,  ill try it first to recompile it on my arch set and see if it works then ill post the solution

**Comment by goldcoders** [comment]
OK ive fixed the issue , that makes loading the app very slow , now its like 1 to 2 secs ...

Hope you add this in the repo documentations

if the user is using archlinux without any Desktop Environment

he should add this to his .xinitrc

```
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

#before calling 
exec i3
# or whatever Window manager he is using
```

**Comment by alainm23** [comment]
Thank you very much for finding a solution. I'll add this to the documentation.
