### ISSUE TITLE
Can't always drag tasks out of a section

### ISSUE THREAD

**Issue by Riksu9000** [alainm23/planify#1245]
**Describe the bug**
If there are no tasks outside of a section, it's not possible to drag tasks out of a section.

To Reproduce
1. Create a project
2. Create a section with a task
3. Try to move the task out of the section
4. Create a new task outside the section
5. Move the original task out of the section

Expected behavior
I expect I should be able to move the task out of the section even if there are no other tasks

Screenshots
https://github.com/alainm23/planify/assets/37774658/24615f80-8e50-4c68-863e-f09adba05b45

Desktop (please complete the following information):
 - Fedora, planify master

**Comment by alainm23** [comment]
It has been fixed.
[Screencast from 2024-04-14 06-43-13.webm](https://github.com/alainm23/planify/assets/33765137/a4e8d836-23eb-46cb-b707-210163d4df49)

**Comment by Riksu9000** [comment]
Thanks!
