### ISSUE TITLE
Failed Login with Caldav (nextcloud)

### ISSUE THREAD

**Issue by chmol** [alainm23/planify#1247]
**Describe the bug**
Using the latest flatpak I cannot add an external caldav calendar hosted on a nextcloud server. 

the error I get is  

```
?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Calendar object not found</s:message>
</d:error>
```

**To Reproduce**
1. Go to preference>integration>caldav
2. setup :
    - server url https://[my.domain.name]/remote.php/dav/calendars/[UserName]/[CalendarName]/
       * I also tried, with https://[my.domain.name] or 
       * https://[my.domain.name]/remote.php/dav/calendars/ or
       *  https://[my.domain.name]/remote.php/dav/calendars/[UserName]
    - username/password 
   
3.  Get the follwing error 
   -  https://[my.domain.name]/remote.php/dav/calendars/[UserName]/[CalendarName]/
   
```
?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Calendar object not found</s:message>
</d:error>
```
   
  - https://[my.domain.name]/ : 
     ` org.freedesktop.DBus.Error.ServiceUnknown`

  -  https://[my.domain.name]/remote.php/dav/calendars/ &  https://[my.domain.name]/remote.php/dav/calendars/[UserName]
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Principal with name remote.php not found</s:message>
</d:error>

```

**Expected behavior**
Login works. 

**Desktop (please complete the following information):**
 - OS : debian unstable
 - DE:  openbox
 - install method: flatpak

**Comment by garrettwp** [comment]
I get the same error message:  org.freedesktop.DBus.Error.ServiceUnknown when trying to add my nextcloud server on one of my computers. On another computer running the same distro and software version has no issue adding the nexcloud server. In my case I am using https://cloud.domainhere.com as the server url.

Desktop (please complete the following information):

    OS : Fedora 40
    DE: KDE
    install method: flatpak

**Comment by TraceyC77** [comment]
I also got the error `org.freedesktop.DBus.Error.ServiceUnknown ` when I tried to add my Nextcloud server. I have Thunderbird set up with it, so I know I can connect and authenticate to it.

**Comment by alainm23** [comment]
Thanks for using Planify, maybe you could use this solution.
https://github.com/alainm23/planify/issues/1179#issuecomment-1998053391

**Comment by chmol** [comment]
Thanks you for your answer. 

From my understanding that solution is incomplete and requires external tools. 

> I can now add tasks to Planify that syncs to NextCloud, but it doesn't sync info back from NextCloud to Planify (new Tasks, completion).


Your UI is great I would love to be able to use it with my tasks :)

**Comment by alainm23** [comment]
The error with the synchronization has already been fixed, could you please verify it?

**Comment by garrettwp** [comment]
So the odd thing is that planify works on my laptop and not on my desktop. They both run the same distro and version with almost exact setup. I did try the workaround to enable DBus via flatseal prior to thiinking of opening an issue and that did now work. I then saw this issue opened up and wanted to chime in stating I am also seeing the same issue. After seeing your response of the dbus workaround, I went back into planify, removed the nextcloud account, closed the app, opened up flatseal and enabled DBus System and Session. I then opened up planify and readded the account and it now works. However, this is a workaround and not a true fix. The odd thing as mentioned in the beginning is that I did not have to do this on my laptop.

**Comment by alainm23** [comment]
It's exactly the same, I can't replicate it on my computer.

**Comment by TraceyC77** [comment]
I just re-tested this and I no longer see the bug with 4.7.6

- I removed the existing entry for my Nextcloud calendar. (Aside, the UX for this is not really intuitive. Togging the Nextcloud calendar "off" prompts to delete the calendar entry)
- I re-added the Nextcloud calendar using the main URL of the Nextcloud instance (as indicated by the help text)
- After logging in, I see the two calendars and the tasks from them.

Thanks for your work on this :)
