### ISSUE TITLE
Show repeating indicator before date of task in list

### ISSUE THREAD

**Issue by oktayacikalin** [alainm23/planify#1248]
**Is your feature request related to a problem? Please describe.**
I've repeating on non-repeating tasks. When looking at the list of tasks, I cannot see which is what.

**Describe the solution you'd like**
When I unfold a task, an indicator is shown before the date, if it has been configured as repeating. The task list should also show this indicator. When hovering over it, a tooltip should tell me how often.

**Describe alternatives you've considered**
It would of course be better if the task got another pill showing something like "every month", "daily" etc.

**Additional context**
None

**Comment by alainm23** [comment]
It has been fixed.
![image](https://github.com/alainm23/planify/assets/33765137/3e2cf5c4-ae54-4678-99ce-5b8f09597d7a)
