### ISSUE TITLE
& Problems

### ISSUE THREAD

**Issue by mzzntn** [alainm23/planify#125]
It seems that the program has several problem digesting the character &

* If & is insert between 2 words when a new project is created this happens
![1](https://user-images.githubusercontent.com/37122612/71932785-e1244380-31a0-11ea-9e9c-b640d7fc63e7.png)
* If i try to change the name removing the character nothing happens 
* If i add the character after a new project is created it doesn't update the name on the left.
![Screenshot from 2020-01-07 22 59 23](https://user-images.githubusercontent.com/37122612/71933074-922ade00-31a1-11ea-82ba-d4d1451aac0e.png)

**Comment by alainm23** [comment]
Thank you very much for your comment. Sorry to tell you that you are running an outdated version of Planner. We are currently in the [beta](https://planner-todo.web.app/planner-beta-blog) test of Planner 2, a version with new design and UX.
