### ISSUE TITLE
Planify crashes when I activate "Run at startup"

### ISSUE THREAD

**Issue by Explosiveduckfeather** [alainm23/planify#1257]
**Describe the bug**
Turning on "Run at startup"  (i have it in spanish, so i don't  know what this says actually in english)causes Planify to crash, freeze or slow down too much, to the point where i can't work. And if I close it, the configuration is not saved.

**To Reproduce**
1. Go to 'Menu'
2. Click on 'Preferences'
3. Go to 'General'
4. Click on 'Run at startup'
5. See the bug

**Expected behavior**
Not crash, freeze or slow down when i activate "Run at startup".

**Screenshots**

**Desktop (please complete the following information):**
 - OS or DE: Fedora XFCE
 - Version: 39

**Additional context**

**Comment by janvlug** [comment]
Probably related, therefore I did not create a new issue:

For me Planify crashes when disabling "Run at startup".

Maybe related: Note that I always have the "Offline Mode Is On" marker visible (even when I am (partially?) connected to Nextcloud). That is issue #1215.

**Comment by rsholmes** [comment]
Same or similar problem:

**To Reproduce**
Steps to reproduce the behavior:

1. Open Planify
2. Go to Main Menu, click on Preferences
3. Click on General
4. Click "Run on Startup" to enable it
5. Click on close window icon or anything else. Nothing happens.
6. Force close Planify
7. Restart Planify
8. Re-open preferences, "Run on Startup" is not enabled.

**Desktop**

OS or DE: Linux Mint Cinnamon
Version 21.2

Planify version 4.9.0

**Terminal output**

Errors below appear when Planify is started. No new messages appear when attempting to set preferences.

```
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=io.github.alainm23.planify io.github.alainm23.planify

** (io.github.alainm23.planify:2): CRITICAL **: 22:29:04.097: objects_item_get_completed: assertion 'self != NULL' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 22:29:04.133: gtk_text_buffer_set_text: assertion 'text != NULL' failed

(io.github.alainm23.planify:2): Gtk-WARNING **: 22:29:04.270: No IM module matching GTK_IM_MODULE=uim found

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 22:29:04.549: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 22:29:04.794: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed
```

**Comment by janvlug** [comment]
Thanks, I confirm the fix :tada:
