### ISSUE TITLE
Completing a task from the search popup doesn't work 

### ISSUE THREAD

**Issue by Riksu9000** [alainm23/planify#1259]
**Describe the bug**
The tasks in the search popup have a checkbox that can be checked, however doing so doesn't complete the task.

**To Reproduce**
1. Create a task
2. Search for the task
3. Click the checkbox
4. Close the popup

**Expected behavior**
The checkbox should either not be checkable and clicking should always open the containing project, **or** checking off the task should actually complete it, which is what I'd prefer.

**Screenshots**
https://github.com/alainm23/planify/assets/37774658/6e9dda62-c349-4889-8db9-046ca915dd51

**Desktop (please complete the following information):**
 - Fedora, planify 89ef685c

**Comment by alainm23** [comment]
Sorry for the confusion, the check is more of a visual element than an action element, it should not complete, just send you to the selected task. I will make an adjustment to avoid this kind of actions.

**Comment by Riksu9000** [comment]
That's fair. Thanks.
