### ISSUE TITLE
Building from source fails on GNOME 3.34.3

### ISSUE THREAD

**Issue by yochananmarqos** [alainm23/planify#126]
**Describe the bug**
Build fails with:

```
Compilation failed: 45 error(s), 3 warning(s)
[6/66] Generating com.github.alainm23.planner.appdata.xml_data_merge with a custom command.
ninja: build stopped: subcommand failed.
```

**To Reproduce**
Attempt to build on an Arch-based distro

**Expected behavior**
Self-explanatory

**Desktop**
 - Manjaro
- GNOME 3.34.3

**Additional context**
I ran into the same issue as in #119 as `evolution-data-server` 3.34.3-1 provides `libecal-2.0`. I bumped the version in `meson.build` to no avail. 

I know you're building this on and for Elementary OS, but it would be nice if it at least worked on The DE it's based on as well.

[Build log](https://del.dog/yupicyrett)

**Comment by alainm23** [comment]
Could you rebuild please. I just updated the support for `libecal-2.0`

**Comment by yochananmarqos** [comment]
The build still fails. 

[Build log](https://del.dog/firasapafe)

**Comment by alainm23** [comment]
One more time pls. We go from 45 errors to 8.

**Comment by yochananmarqos** [comment]
Success! 

The dark theme needs a little work. I'm using Adwaita-maia-dark:

![Screenshot from 2020-01-09 09-04-47](https://user-images.githubusercontent.com/5437803/72083486-250d6a80-32bf-11ea-8fc6-eec8e3c7de82.png)

**Comment by alainm23** [comment]
Are you building Planner using flatpak?

**Comment by yochananmarqos** [comment]
No, I'm building from source. See my PKGBUILD in the first post.

**Comment by alainm23** [comment]
Understood, I am programming Planner from elementary OS, for other distributions I recommend using flatpak.

```
sudo apt install flatpak-builder
flatpak install flathub org.gnome.Sdk/x86_64/3.34
flatpak install flathub org.gnome.Platform/x86_64/3.34
flatpak install flathub io.elementary.BaseApp/x86_64/juno-19.08

git clone https://github.com/alainm23/planner.git
cd planner/build-aux/flatpak

flatpak-builder --install repo com.github.alainm23.planner.json --force-clean --user
```

Try this and Planner works better.

**Comment by yochananmarqos** [comment]
Arch packages are built from source. I don't use flatpaks or snaps.

**Comment by alainm23** [comment]
So we have a problem here. The planner will not look good here because this depends on the theme and official icons of elementary OS.

![image](https://user-images.githubusercontent.com/33765137/72084967-7410cb00-32d2-11ea-9940-38b7df7fd82b.png)
Planner 2 in dark theme.

**Comment by yochananmarqos** [comment]
Alright, I'll see if I can add those as dependencies. Right now I'm off to work.

**Comment by alainm23** [comment]
If you could do that job, I would be very grateful.

**Comment by yochananmarqos** [comment]
I added the GTK theme & icons to dependencies and added it to the AUR: [`elementary-planner-git`](https://aur.archlinux.org/packages/elementary-planner-git/). 

![Screenshot from 2020-01-10 08-33-46](https://user-images.githubusercontent.com/5437803/72164992-f5746600-3383-11ea-8985-cd17720499bf.png)

**Comment by alainm23** [comment]
You are a genius, thank you very much.

**Comment by alainm23** [comment]
@yochananmarqos Just a little more detail. Could you try the calendar feature? it works?

![image](https://user-images.githubusercontent.com/33765137/72167359-ffed2a80-3398-11ea-9c5a-a56a4b1e90bc.png)

![image](https://user-images.githubusercontent.com/33765137/72167438-1e532600-3399-11ea-8e3a-b179187ac278.png)

If you have a calendar application configured. Planner can bring all events and display it on the respective date.

**Comment by yochananmarqos** [comment]
Yes, the calendar works, I'm signed in to Google in Online Accounts.

**Comment by alainm23** [comment]
Great!!!

**Comment by yochananmarqos** [comment]
Do you recommend any particular fonts? It looks like Elementary has a few default fonts like Open Sans, Raleway, Dejavu, Droid, GNU Free Fonts and Liberation.

**Comment by yochananmarqos** [comment]
I just built using the latest commit 172e3e2dcd6aa6e0f60b2a173ff90ad59596cecd and get this now:
```
(planner:8054): Gtk-CRITICAL **: 14:00:28.589: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed
**
ERROR:com.github.alainm23.planner@exe/src/Services/Database.c:4066:services_database_get_all_projects_no_area: assertion failed: (res == Sqlite.OK)
Bail out! ERROR:com.github.alainm23.planner@exe/src/Services/Database.c:4066:services_database_get_all_projects_no_area: assertion failed: (res == Sqlite.OK)
Aborted (core dumped)
```

**Comment by alainm23** [comment]
I imagine, I just made some modifications to the Planner 2 database file before the first release. Try deleting the database file.

`/home/<user>/.local/share/com.github.alainm23.planner`

**Comment by yochananmarqos** [comment]
I removed that folder, still no go:

```
            ALTER TABLE Projects ADD COLUMN is_kanban INTEGER DEFAULT 0;
        
**
ERROR:com.github.alainm23.planner@exe/src/Services/Database.c:2053:services_database_add_int_column: assertion failed: (res == Sqlite.OK)
Bail out! ERROR:com.github.alainm23.planner@exe/src/Services/Database.c:2053:services_database_add_int_column: assertion failed: (res == Sqlite.OK)
Aborted (core dumped)
```

**Comment by alainm23** [comment]
Try one more time pls.

**Comment by yochananmarqos** [comment]
Yep, it works now. Thanks!
