### ISSUE TITLE
Keep right Side-Panel open 

### ISSUE THREAD

**Issue by Jopp-gh** [alainm23/planify#1262]
**Is your feature request related to a problem? Please describe.**
Planify's right side panel has been a great addition, however I'd like to keep that panel open all times.
Also, its quick animation is irritating, bc you see that animation too often as you browse/click through your tasks

**Describe the solution you'd like**
I don't see a reason to close an info panel. I'd suggest to add a keyboard shortcut instead, so users can decide themselves to keep that panel permanently open or not. 

**Describe alternatives you've considered**
---

**Additional context**
Thanks for making Planify!

**Comment by alainm23** [comment]
Added an option in the Preferences to always have the detail panel visible.

![image](https://github.com/user-attachments/assets/391da9c3-e781-4441-bf50-7749d2589035)
