### ISSUE TITLE
Planify breaks down when I try to move a task from one day to another.

### ISSUE THREAD

**Issue by OsipyanG** [alainm23/planify#1268]
**Describe the bug**
Planify breaks down when I try to move a task from one day to another. These actions take place in "Completed". For example, a situation where I completed a task on the day it was scheduled, but marked it the next day. I am trying to move the task to the day it was scheduled for in Completed and the application crashes

**Desktop (please complete the following information):**
 -  OS: Fedora Linux 40 (Workstation Edition) x86_64 
 - Version: 4.6

**Comment by alainm23** [comment]
Hi, thanks for using Planify, I'm not sure how to replicate the error you mention, maybe you could upload a video.

**Comment by Riksu9000** [comment]
I was able to replicate this issue. After opening the completed tasks view twice, the tasks can now be dragged, which crashes the app.

https://github.com/alainm23/planify/assets/37774658/de33f0a2-2700-4873-af8a-28915e507779
