### ISSUE TITLE
Multiple CalDav sources

### ISSUE THREAD

**Issue by azmeuk** [alainm23/planify#1276]
Hi, this is a pretty straightforward feature request:

**Is your feature request related to a problem? Please describe.**
I have at least two CalDAV sources : a personal and a professional one. Planify only allows me to synchronize with one of the two sources.

**Describe the solution you'd like**
Allow multiple CalDAV sources synchronization.

What do you think?

**Comment by alainm23** [comment]
This is something I am working on, it will require a change in the core application, but it is possible.

**Comment by alainm23** [comment]
#1212
