### ISSUE TITLE
ninja install error when installing v4.7, Error  - undefined reference to `gtk_calendar_set_year' 

### ISSUE THREAD

**Issue by lx-abhi** [alainm23/planify#1277]
**Describe the bug**
Issue: 
When trying to install the latest version Planify v4.7 
there was an error when executed the command - "ninja install"

Attached the error log for details.
[Planify Error.txt](https://github.com/alainm23/planify/files/15211883/Planify.Error.txt)

**To Reproduce**

Completed the meson build to configure the build environment without issues.
meson build --prefix=/usr
cd build
ninja

For installation,  used ninja install thats when error occurs

`
/usr/bin/ld: src/io.github.alainm23.planify.p/meson-generated_Dialogs_RepeatConfig.c.o: in function `dialogs_repeat_config_set_duedate':
/home/lx/Downloads/planify-4.7/build/../src/Dialogs/RepeatConfig.vala:74:(.text+0x1aae): undefined reference to `gtk_calendar_set_year'
/usr/bin/ld: /home/lx/Downloads/planify-4.7/build/../src/Dialogs/RepeatConfig.vala:75:(.text+0x1aea): undefined reference to `gtk_calendar_set_month'
/usr/bin/ld: /home/lx/Downloads/planify-4.7/build/../src/Dialogs/RepeatConfig.vala:76:(.text+0x1b26): undefined reference to `gtk_calendar_set_day'
collect2: error: ld returned 1 exit status`

**Expected behavior**
Expected the app to be installed when executing the command ninja install

**Screenshots**
![Planify error](https://github.com/alainm23/planify/assets/129678374/523a1a9d-abc2-4f8a-97ab-201d0b875468)

**Desktop (please complete the following information):**
 - OS:  Manjaro
 - DE:  Gnome 45.4
 - Kernel: Linux 6.8.8-2-MANJARO
 
I could have tried the Flatpak, but prefers to compile, build and install.

**Comment by alainm23** [comment]
Hi, sorry, I have not been able to reproduce the error, when you run `meson build --prefix=/usr` what versions do you get on screen, I get these.

![image](https://github.com/alainm23/planify/assets/33765137/9ab478ae-9b44-40eb-99a0-3fc37ab3fc2e)

**Comment by lx-abhi** [comment]
Hi Alain,
Very Nice App, Awesome work!

Attached the meson config
[Meson Config.txt](https://github.com/alainm23/planify/files/15214938/Meson.Config.txt)

**Additional Info:**
Planify v4.4 works fine in my system but  I tried upgrading it to v4.6 ( I think ) last time error-ed out.
Now I tried upgrading to v4.7, I have the same error now as well.

Thanks

**Comment by alainm23** [comment]
Hi, I will close this Issue for the time it has been inactive, if you reproduce the problem again, do not hesitate to create a new one.
