### ISSUE TITLE
Backups crashing the app

### ISSUE THREAD

**Issue by Riksu9000** [alainm23/planify#1278]
**Describe the bug**
Creating and restoring backups will crash the app.

**To Reproduce**
Easiest way to reproduce the crash
1. Delete app data
2. Create a backup

**Desktop (please complete the following information):**
 - Fedora, planify 0e1f7ab7

**Additional context**

I tried to import my tasks into a development build of planify, but the app froze and subsequently crashed every time. After restarting the app, there's a project called Inbox, and the inbox view doesn't load. I believe this issue is caused by this commit, though I didn't check every commit https://github.com/alainm23/planify/commit/8d1aaa7d233ebaf1ea3474eb7f4e7830a9491754. Reverting to the parent commit fixes the issue.

```
(io.github.alainm23.planify.Devel:2): GLib-GIO-ERROR **: 11:26:52.615: Settings schema 'io.github.alainm23.planify' does not contain a key named 'default-inbox'

```

**Comment by alainm23** [comment]
Hello, changes were made in the core of the application, it is necessary to run a `sudo ninja install`.
