### ISSUE TITLE
Add keyboard shortcut for creating a new task

### ISSUE THREAD

**Issue by phase1geo** [alainm23/planify#128]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to see a keyboard shortcut for creating a new task (Control-N or something else). It would also be nice to see what this keyboard shortcut is within the tooltip associated with the Plus button.

**Comment by alainm23** [comment]
Of course, this feature comes in a future update, but not yet for the first version.

**Comment by alainm23** [comment]
Available in version 2.1.
