### ISSUE TITLE
Planify crashes after trying to create a task for any label.

### ISSUE THREAD

**Issue by MysterJacob** [alainm23/planify#1282]
Planify crashes after trying to create a task for any label.

1. Go to 'Labels'
2. Enter on any label
3. Press 'a' 

Error message: 
```
(io.github.alainm23.planify:57522): GLib-GObject-CRITICAL **: invalid cast from 'ViewsLabel' to 'ViewsFilter'
Segmentation fault
```

OS: TuxedoOS (Ubuntu Jammy)
Version: 3 (22.04.4)

Planify installed from snap store.

**Comment by alainm23** [comment]
I couldn't see the bug, have you tried to close Planify, kill the process and start again?

**Comment by MysterJacob** [comment]
I've tried, but it doesn't seem to resolve the issue. 


Worth noting is that I am on KDE6. I didn't test Planify on KDE5.

**Comment by alainm23** [comment]
Hello, Planify 4.1 was released, could you check if the error persists?

**Comment by MysterJacob** [comment]
Hello, it seems to have resolved the issue.
