### ISSUE TITLE
Nextcloud projects (or "lists") created in Planify only sync one way

### ISSUE THREAD

**Issue by bipox** [alainm23/planify#1284]
**Describe the bug**
Projects (and their tasks) created from Planify will sync to Nextcloud but not from Nextcloud to Planify

This issue has been mentioned by another user [here](https://github.com/alainm23/planify/issues/1215#issuecomment-2029395328) (but in my case tasks created in planify **do** appear in nextcloud)

**To Reproduce**
1. In Planify, create a new project (I name it Test-project)
2. In Planify still, create a task in Test-project -> task is correctly synced with server
3. Now in Nextcloud's webapp create a task in Test-project -> task does not show up in Planify

 - Same issue happens with modified tasks.  
 - "Tasks" app on Android, the Nextcloud webapp, "Errands" on Linux, all sync correctly Test-project between each other.   
 - Projects created outside of Planify sync correctly with Planify. 
 
 Edit: tasks marked as done works, but tasks deleted in the web app don't get deleted in Planify
 If I mark as done a task that has been deleted on the server the "progress circle" spins infinitely 

**Desktop (please complete the following information):**
 - OS or DE: Fedora 40 with Gnome 46
 - Planify 4.7 (flatpak)
 
Nextcloud 28.0.5 running the tasks app version 0.16.0

**Comment by alainm23** [comment]
This happens because Planify does not save the synchronisation token when creating a project, it is being checked.

**Comment by bipox** [comment]
Great, thanks!

And is this related?
>tasks marked as done works, but tasks deleted in the web app don't get deleted in Planify

This happens in projects not created in Planify.

Should I open a bug report, or is there one already?

**Comment by alainm23** [comment]
I also fixed it, please wait for an update.
