### ISSUE TITLE
A project moved to Inbox and renamed

### ISSUE THREAD

**Issue by wada3n** [alainm23/planify#1289]
Dear @alainm23 ,

I hope this report finds you well.

I'm writing to report a bug I've encountered with the latest update 4.7.2. 
After the introduction of the new Inbox feature, the app moved an old project named "**My Life**" (the first one in my project list) into the **Inbox** and renamed the Inbox title-bar "My Life."

I believe it would be better to leave projects as they were and not change them, and to add the new Inbox as a separate project as originally described. This would allow users to keep their existing project structure intact while still taking advantage of the new Inbox feature.

**Comment by alainm23** [comment]
Hi and thanks for using Planify, sorry for the late reply and the inconvenience this change caused, I hope you were able to fix it, having a separate Inbox project adds a better understanding of the GTD methodology, having one place to add ideas and then schedule or organise them later. I'll close this problem for now, but if you have any other question, feel free to write me. Regards.
