### ISSUE TITLE
Hitting return after creating a new section should create a new task within it

### ISSUE THREAD

**Issue by phase1geo** [alainm23/planify#129]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It feels like unexpected behavior to have Planner change the UI to adding a another new section after creating one and hitting the return key.  If I create a new section, it is typically because I plan to add tasks to it.  Perhaps we could change the behavior by combining the Return key with a modifier key that would allow a new section or new task to be added if others feel strongly about the current behavior.

**Comment by alainm23** [comment]
Thank you very much for the comment, I'm not sure if this is very good to implement by default and even more that the way to create a Section in Planner changed.
