### ISSUE TITLE
Overdue task missing

### ISSUE THREAD

**Issue by fenixservicios** [alainm23/planify#1295]
**Describe the bug**
I have a task pending from yesterday but it don't show in today tasks pending list.

**To Reproduce**
1. Click on Today list and yesterday pending task is missing. I can see the today list only.
2. Click on project and I can see the task market as "yesterday".
3. I edited the "yesterday" task adding some text... and Oh! now is in the Today list.
4. (Update) I shut down my pc, when turn on again... the same behavior occurs.. (see again steps 1 through 3) 
**Expected behavior**
The today list must show task for today and overdue tasks.

**Desktop (please complete the following information):**9
 - Linux Fedora
 - Version 39 workstation

**Comment by Araly** [comment]
it feels like I get some recent overdue tasks (like I get a task for a few days ago) but I don't see any of the older overdue tasks (like a month ago)

**Comment by stefan623** [comment]
I have the same issue

* Ubuntu 24.04 LTS
* Planify 4.7.6 (flathub)

**Comment by Riksu9000** [comment]
The overdue tasks disappear from the today view after this commit 57c3a4877ea65b724f045bb315d247115dd2808a. This is a high impact issue, so I hope it gets fixed soon. In the meantime I have to keep using version 4.7.

**Comment by alainm23** [comment]
Sorry, I will send an update as soon as possible.

**Comment by Riksu9000** [comment]
I tried master now and the overdue tasks have reappeared. Thank you very much.
