### ISSUE TITLE
GNOME 46 - libecal-2.0.so.2: cannot open shared object file  (Planify v4.4)

### ISSUE THREAD

**Issue by lx-abhi** [alainm23/planify#1297]
**Describe the bug**
The **Planify v4.4**  stopped working after upgrading Manjaro v23 to  Manjaro v24.0 Wynsdey  ( Gnome 46 ).

**Error Message:**
io.github.alainm23.planify: error while loading shared libraries: libecal-2.0.so.2: cannot open shared object file: No such file or directory

I believe the error occurs in GNOME 46, which has bumped the file numbers
libecal-2.0.so.2 → libecal-2.0.so.3

please ref the below link for file name bumped.
https://archlinux.org/todo/gnome-46-in-staging/

**To Reproduce**

1. Install the Planify v4.4 in GNOME 45
2. Upgraded the GNOME to  v46 
3. Execute the App in the terminal io.github.alainm23.planify 
4. Terminal errors out with message 
io.github.alainm23.planify: error while loading shared libraries: libecal-2.0.so.2: cannot open shared object file: No such file or directory

OR

1. Install the Planify v4.4 in GNOME 46  ( don't know if it works or not )
2. Execute the App in the terminal io.github.alainm23.planify 
3. Terminal errors out with message 
io.github.alainm23.planify: error while loading shared libraries: libecal-2.0.so.2: cannot open shared object file: No such file or directory

**Expected behavior**
Expected the App to run without issues.

**Screenshots**
![image](https://github.com/alainm23/planify/assets/129678374/206712da-028e-4cf9-9c4e-2fa28f396380)

**Desktop **
 - OS: Manjaro v24 
 - DE: Gnome v46

**Comment by alainm23** [comment]
Hello, did the same bug still occur?

**Comment by lx-abhi** [comment]
Hi @alainm23 ,

With the new Version 4.9.0 (Installed from  AUR Repo), the issue got fixed. 
Thank you so much !
