### ISSUE TITLE
[How to] Transfer data from a crashed (compiled and installed) app to flatpak planify 

### ISSUE THREAD

**Issue by lx-abhi** [alainm23/planify#1303]
I want to transfer the data from a not working (compiled and installed) app to the flatpak app. 

**Describe the bug**
I have lot of to do items in planify v4.4  (compiled and installed ) App, which got crashed when upgrade to gnome v46.
Cannot compile and install Planify v4.7 in my system due to other issues.

Wanted to migrate the items from the compile and installed (not working) planify app to (working) flatpak app.

**Steps I have tried:**
Get the database.db from the file path
$ ~/.local/share/io.github.alainm23.planify/  

I have copied database.db file from planify v4.4 but this format is **not accepted** by working flatpak v7.4 as it is **not the backup file** format.

**To Reproduce**
1. install a compiled and installed planify app (mostly v4.4)
2. Also, install the flatpak app
3. try to copy the data from compiled and installed app to flatpak planify.

**Expected behavior**
Copy the data (personel to do items) from planify (compiled and installed) to flatpak.

**Desktop (please complete the following information):**
 - OS Manjaro v24
 - DE Gnome v26
 - Version Planify v4.4 and Planify v4.7

**Note:**
This really helps in recovery of all my data and get going with flatpak app.
Thank you and any feedback is greatly appreciated.

**Comment by alainm23** [comment]
Hello and thank you for using Planify, it is not necessary to copy the database, simply create a backup from Preferences > Backups, download the backup and import it from your Flatpak installation.

**Comment by lx-abhi** [comment]
Hi Alainm,
I cannot create a backup from Preference > Backups as the App is **not currently** working in the GNOME v46 (App has stopped working after gnome upgrade, I should have taken a backup). Any way to access the data from the terminal ?
so that, I can some how import it to Flatpak.

Trying to retrieve the data from a crashed App.

Thank you!

**Comment by omenos** [comment]
The SQLite database should be stored somewhere in your home directory (I want to assume `~/.config`). You can do a database dump and restore via:

```bash
# Backup
$ sqlite3 /path/to/database.db ".dump" | tee -a planify.sql

# Restore
$ DATABASE="~/.var/app/io.github.alainm23.planify/data/io.github.alainm23.planify/database.db"
$ sqlite3 ${DATABASE} ".read planify.sql"
```

**Comment by lx-abhi** [comment]
Hi @omenos,

In my system, the database.db that has all the data is in the location 
$ ~/.local/share/io.github.alainm23.planify/

I was able to restore all my Data.
 
Thank you!
