### ISSUE TITLE
Caldav and Synology calendar

### ISSUE THREAD

**Issue by jhautefeuille** [alainm23/planify#1306]
Not fonctional with Synology Calendar

URL example 

https://domain.x.y/caldav/

**Comment by joe67** [comment]
i have the same problem with synology caldav. When i try to connect to the synology NAS i get an error message "Unacceptable TLS certificate". In Evolution or other apps i get a dialog where i can trust the certificate, despite that it is not really secure. For example it is  a self signed certificate. It possible to implement the same mechanism in planify?

**Comment by RomainMorlevat** [comment]
Same issue with Nextcloud with a self-signed certificate (LAN access), I get a "Unacceptable TLS certificate". If I set with an external access (Let's Encrypt certificate), I can set the sync, but when back on my LAN, it load forever.

**Comment by alainm23** [comment]
Version 4.10.8 should fix the bug, expect the update to arrive in a couple of hours.
