### ISSUE TITLE
Todoist integration: completed tasks results as still to be completed

### ISSUE THREAD

**Issue by angystardust** [alainm23/planify#1307]
**Describe the bug**
There are some synchronization issues with the tasks imported by the Todoist plugin. 
Watch the screenshot below.

**To Reproduce**
1. Open a Todoist account
2. Generate some projects and create tasks in different sections
3. Close some tasks
4. Open Planify and configure the Todoist plugin to import the tasks from your Todoist account
5. Check for mismatches in opened and closed tasks between the 2 applications

**Expected behavior**
Tasks marked as closed on Todoist server should result as "status = completed" instead of "todo"

**Screenshots**
Here on this screenshot you can see on the left the Planify sidebar and on the right the Todoist one. As you can see, both "Ciclofficina Nascosta" and "LoveMeTandem" projects have a different number of total open tasks

![Screenshot from 2024-05-21 19-27-14](https://github.com/alainm23/planify/assets/1568397/236034d0-143d-4fb7-994c-7e378541136b)

**Desktop (please complete the following information):**
 - OS or DE: Fedora Linux 40 (Workstation Edition) + Gnome 46 
 - Planify v. 4.7.6 (flatpak)

**Additional context**

#721

**Comment by alainm23** [comment]
Hi, have you tried re-syncing with Todoist.

**Comment by alainm23** [comment]
I will close this issue for the time of inactivity, if it happens again, feel free to create a new issue.
