### ISSUE TITLE
On french layout with multiples task creation i cannot enter "m" because it move and hide the side panel

### ISSUE THREAD

**Issue by yodatak** [alainm23/planify#1310]
**Describe the bug**
On french layout with multiples task creation i cannot enter "m" because it move and hide the side panel

The bug in video
[Capture vidéo du 2024-05-23 14-20-28.webm](https://github.com/alainm23/planify/assets/704477/8115d0ef-b57d-453a-b7f9-8d87c50799c7)

**To Reproduce**
1. Create a task
2. Create another
3. try to type something with m in azerty french layout
4. you cant

**Expected behavior**
Type m in my task name

**Desktop (please complete the following information):**
 - OS or DE: [e.g. pantheon, unity, gnome] Fedora gnome
 - Version [e.g. 0.1.2]  4.7.3 on flathub

- **Model :**                         Lenovo ThinkPad X13 Gen 3
- **memory :**                                    16,0 Gio
- **Proc :**                                 12th Gen Intel® Core™ i5-1240P × 16
- **GPU :**                            Intel® Graphics (ADL GT2)

 Fedora Linux 40.20240519.0 (Silverblue)
64 bits
- **Version GNOME :**                           46
- **windows system :**                       Wayland
- **kernel :**                           Linux 6.8.9-300.fc40.x86_64

**Comment by alp10711** [comment]
This problem also appears on the German layout

**Comment by alainm23** [comment]
Hello and thank you for using Planify, I made an adjustment in version 4.8 in Quick Add, does it still reproduce the same bug?

**Comment by alp10711** [comment]
@alainm23 hi, I have tried to reproduce the bug in the German layout and it looks like the bug no longer occurs :)
