### ISSUE TITLE
App Crashes when going to link Todoist

### ISSUE THREAD

**Issue by sfs-quentin** [alainm23/planify#1313]
**Describe the bug**
When I go to link my Todoist account to Planify, the app simply crashes the second I press the toggle.

**To Reproduce**
1. Go to preferences
2. Go to Integrations
3. Click on `Todoist`

**Expected behavior**
A login page or extension page to open on Firefox.

**Screenshots**
[Screencast from 2024-05-24 21-20-34.webm](https://github.com/alainm23/planify/assets/154846367/fb12c190-b4db-4c13-b52a-88518dbc43dd)

**Desktop (please complete the following information):**
 - OS or DE: Ubuntu 24.04 LTS
 - Version 4.7

**Additional context**
App is running as a Snap.

**Comment by alainm23** [comment]
I'm not sure why this is happening, you could run Planify from the terminal to see the error log.

`flatpak run --devel io.github.alainm23.planify`

**Comment by alainm23** [comment]
Hi @notro636 , has the Issue been reproduced again? Planify 4.10 and several bugs with synchronisation were fixed.

**Comment by sfs-quentin** [comment]
> Hi @notro636 , has the Issue been reproduced again? Planify 4.10 and several bugs with synchronisation were fixed.

I haven't had anymore issues since Planify 4.10 came out! when I did have issues though, I just went to the Todoist website to deal with it, I typically had to restart my computer to get it to work again.
