### ISSUE TITLE
Sort completed tasks by completion date

### ISSUE THREAD

**Issue by itm4n** [alainm23/planify#1316]
**Is your feature request related to a problem? Please describe.**
I use Planify during team meetings to go through all the tasks that were completed since last meeting, but since there is no possibility to sort them by completion date, it can get a bit difficult to see which ones were completed last.

**Describe the solution you'd like**
It would be nice if completed tasks were sorted by date by default, from newest (top), to oldest (bottom).

**Describe alternatives you've considered**
If not by default, this feature could be implemented as an additional sorting option to the existing "Sort By":
- One section for "Sort active tasks by...": existing options here
- Another section for "Sort completed tasks by...": "Custom sort order", "Alphabetically", "Date completed"

**Additional context**

![image](https://github.com/alainm23/planify/assets/30777390/78fe04b7-77f5-4019-9775-def59a618fe0)

PS: Whatever you decide, thanks a lot for your work, and this nice application! :pray:

**Comment by alainm23** [comment]
Thank you for using Planify, I understand your functionality request. We will do the following, the completed tasks will be ordered by date by default, but if you change the order from the preferences, the same selected order will be applied.

**Comment by itm4n** [comment]
I'm not sure I get it. I'm running version 4.8.2, and it doesn't change anything. Completed tasks are still displayed in a "random" order, no matter if I change the sort order or not. :thinking:
