### ISSUE TITLE
App crashes when selecting tasks

### ISSUE THREAD

**Issue by shofutex** [alainm23/planify#1317]
**Describe the bug**
When I select tasks from nextcloud, the app crashes.

**To Reproduce**
1. Go to one of my nextcloud projects
2. Click on multiple tasks

**Expected behavior**
The app should open the task

**Screenshots**
This is the only error I get when I launch Planify from the command line:
Segmentation fault (core dumped)

**Desktop (please complete the following information):**
This works on both environments I use planify:
 - Ubuntu 22.04 and Raspberry PI OS bookworm

This only occurs after I updated to polanify 4.7.2 in the snap store

**Comment by AdamLeonSmith** [comment]
I can reproduce this on Ubuntu 24.04 LTS and planify 4.7.2

**Comment by daggr8** [comment]
I'm having the same issue in Ubuntu 22.04 and Snap version of Planify 4.7.2.

**Comment by Androz2091** [comment]
Can you guys try to upgrade? Crashes were fixed for me after updating

**Comment by daggr8** [comment]
> Can you guys try to upgrade? Crashes were fixed for me after updating

4.7.2 is the latest Snap available. However the Flatpak 4.8.2 works better.

**Comment by shofutex** [comment]
> Can you guys try to upgrade? Crashes were fixed for me after updating 

I will have to try using the Flatpak. I was hoping new versions would get pushed to the snap store.

**Comment by Androz2091** [comment]
> 4.7.2 is the latest Snap available. However the Flatpak 4.8.2 works better.

I know, had to migrate to flatpak too (I am the one who opened #1322). To be honest this app gets frequently updated by a single man, we can build from source, I prefer him to take time to update the app than fixing workflows to push to all the stores every time something changes

**Comment by shofutex** [comment]
Flatpak 4.8.2 does not have this issue in Ubuntu or Raspberry Pi OS. Might make sense to remove the reference to snap from the main page.

**Comment by alainm23** [comment]
Hi, has the Issue been reproduced again? Snap is no longer supported at the moment.

**Comment by alainm23** [comment]
I will close this issue for the time of inactivity, if it happens again, feel free to create a new issue.

**Comment by fbarbe00** [comment]
Using flatpak on Ubuntu 25.04, I am unable to select a project synchronised with a Nextcloud server. Planify simply freezes when attempting to do so. I haven't had this issue before, and the nextcloud server seems to work fine (I am able to access it and modify it with the browser)

**Comment by fbarbe00** [comment]
When running it from the terminal, this message appears in an endless loop when clicking on the Project:
`** (io.github.alainm23.planify:2): CRITICAL **: 20:30:34.467: widgets_calendar_calendar_set_date: assertion 'self != NULL' failed`

Should I open a new issue for this?
