### ISSUE TITLE
Calendar events are not shown when building from flatpak

### ISSUE THREAD

**Issue by alainm23** [alainm23/planify#132]
When building from flatpak calendar events are not displayed. I worked on this and only managed to show the sources.

this is my manifest file:
https://github.com/alainm23/planner/blob/master/build-aux/flatpak/com.github.alainm23.planner.json

**Comment by ubuntudroid** [comment]
I'm also running the flatpack version and can't manage to see the events showing up in upcoming. This has been closed without a comment, so I guess it was supposed to be fixed? In that case I probably just don't see something very obvious. My calendars appear in the settings of the app, but no events are showing up. Running Pop_OS 20.04 with Gnome 3.36.2, if that helps pinpointing the problem.

**Comment by alainm23** [comment]
Hello, thank you very much for commenting, what version of Planner is running? The problem was fixed in v2.4 but it is not available yet. Check here #139.

**Comment by ubuntudroid** [comment]
Ah, you're right, I'm not on 2.4 - sorry, didn't see that other issue. That sounds great! Looking forward to 2.4! 🎉
