### ISSUE TITLE
Set a minimum window size

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#133]
**Describe the bug**
You can resize the window and obscure certain important parts of the app, like the add task button and more.

**To Reproduce**
Resize the window to a really small dimension
**Expected behavior**
Make it stop on the minimum size.

**Screenshots**
![image](https://user-images.githubusercontent.com/26935602/72657494-d7959b00-3959-11ea-87f9-a380e5bc58e0.png)

**Desktop (please complete the following information):**
 - OS or DE: eOS Juno
 - Version 2.0.5

**Comment by ghost** [comment]
Actually, why is the close button on the left for me. I have tweaked Elementary OS to have the close button on the right side instead of left.

**Comment by Philip-Scott** [comment]
Yeah, you can do some interesting stuff :D 

![image](https://user-images.githubusercontent.com/10786508/73391837-92446800-428d-11ea-8eda-06c38da07409.png)

**Comment by sviperm** [comment]
I think this is the best min horizontal  size
![image](https://user-images.githubusercontent.com/36929696/79562652-13084880-80b4-11ea-815b-c87d76eda590.png)

Also need to set min for vetical size
![image](https://user-images.githubusercontent.com/36929696/79563220-06d0bb00-80b5-11ea-89f3-ad28c7f39eac.png)
