### ISSUE TITLE
Planify crashes at launch

### ISSUE THREAD

**Issue by rolnico** [alainm23/planify#1330]
**Describe the bug**
I just installed Planify via snap (I can't use the other package manager on this computer) and, when I try to run it, it crashes and I get a message "Planify does not respond".

**To Reproduce**
1. Install from scratch via snap
2. Try to run it

**Expected behavior**
It should launch

**Screenshots**
When I run it manually via the terminal, I get the following messages:
```shell
$ snap run planify &
** (io.github.alainm23.planify:60789): CRITICAL **: 17:38:51.245: objects_item_get_completed: assertion 'self != NULL' failed

(io.github.alainm23.planify:60789): GLib-WARNING **: 17:38:51.475: getpwuid_r(): failed due to unknown user id (17******68)

** (io.github.alainm23.planify:60789): CRITICAL **: 17:38:51.476: Settings.vala:95: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.561" (uid=17******68 pid=60789 comm="/snap/planify/149/usr/bin/io.github.alainm23.plani" label="snap.planify.planify (enforce)") interface="org.freedesktop.Accounts" member="FindUserByName" error name="(unset)" requested_reply="0" destination="org.freedesktop.Accounts" (uid=0 pid=1491 comm="/usr/lib/accountsservice/accounts-daemon " label="unconfined")

(io.github.alainm23.planify:60789): GLib-GIO-CRITICAL **: 17:38:51.476: g_dbus_connection_call_internal: assertion 'object_path != NULL && g_variant_is_object_path (object_path)' failed
```

**Desktop (please complete the following information):**
 - OS or DE: Ubuntu 20.04
 - Version [e.g. 0.1.2] 149 on snap (I just installed it so probably the last?)

**Additional context**
This computer is behind a proxy so maybe something has to be configured?
Is it possible to run Planify only locally without it trying to sync to anything?

**Comment by alainm23** [comment]
Hi and thanks for using Planify, unfortunately I'm not sure what might be going on, I think it is blocked using dbus which is the channel Planify uses to connect to Quick Add.

**Comment by Jnetdev** [comment]
I'd like to mention this happen to me, Mint 20.3. This "bug" appears after the machine recovers from Hibernation mode and Planify was opened. Everything works well until reboot or shutdown. 

Planify Flatpak.

**Comment by ieris19** [comment]
I am sorry to bring yet another different opinion to the table, as it might be an unrelated issue, but every time I run Planify after a reminder passed with Planify closed (nothing gets sent), Planify will immediately send one reminder and then crash, no further details I have seen yet. After cycling through a few reminders, Planify launches as normal.

Using Nobara 40 (Fedora derivative, GNOME Edition) through the Flatpak version of the app

**Comment by alainm23** [comment]
Hi @ieris19 , this is because Planify is not yet running in background and when closing the process it does not detect new reminders.

**Comment by alainm23** [comment]
Hi @rolnico At the moment we are not supporting Snap, there are some dependencies that do not allow to compile the latest version of Planify. I will close this issue for now.
