### ISSUE TITLE
Stops syncing to Nextcloud on each restart - Fedora 40 KDE spin

### ISSUE THREAD

**Issue by bigcspecv** [alainm23/planify#1331]
**Describe the bug**
Every time I open the app I have to delete my Nextcloud integration and re-add it. The sync fails to function without doing this. When attempting to add new tasks to a project within the Nextcloud integration I see a spinning wheel on the "Add" button for about 1-2 seconds then it shows the word "Add" again. pressing the button multiple times does nothing. Nothing gets added to Nextcloud. Deleting or completing tasks in these projects will show as deleted/completed in the app but Nextcloud shows no change has occurred. If I go into integrations and delete my Nextcloud sync, ~~close out of the preferences window, reopen preferences,~~ (no longer necessary on 4.8) re-add the Nextcloud sync - everything works fine again until I close the app.

**To Reproduce**
1. Go to preferences -> Integrations
2. Click on the switch next to Nextcloud (turn it on)
3. Fill out the form to connect a Nextcloud instance
4. Click "Log In" button
5. On the left-hand panel see the synced projects under Nextcloud
6. Add or remove tasks successfully 
7. Close the app
8. Open the app
9. On the left-hand panel see the synced projects under Nextcloud
10. Attempt to add a task.
11. See that nothing occurs.
12. Go to preferences -> Integrations
13. Click on the switch next to Nextcloud (turn it off)
14. Click "Delete" in the "Sign Off" dialog
15. Click on the switch next to Nextcloud (turn it on)
16. Fill out the form to connect a Nextcloud instance
17. Click "Log In" button
18. On the left-hand panel see the synced projects under Nextcloud
19. Add or remove tasks successfully 

**Expected behavior**
Closing the app should not stop the Nextcloud integration from working

**Desktop:**
- Affected OS/DE: Fedora 40 KDE spin
- Attempted fresh installs of Fedora 40 KDE to no avail.
 - Planify Versions: 4.5.12 - 4.8

**Additional context**
- I ran a fresh install of vanilla Fedora 40 and it worked properly
- I suspected it had to do with secrets in some way as I have read that KWallet has been changed in some way with Plasma 6, and I don't think I had this issue in Fedora 39 (I will try a fresh install of Fedora 39 KDE later this week). I vaguely remember reading a post somewhere saying something about using flatseal to tell planify to use kwalletd5, but I can no longer find that post. I have checked all of the libsecret and gnome-keyring references that articles/posts have pointed to and I have them installed, so I'm at a loss.

**Comment by alainm23** [comment]
Hello and thank you for using Planify, you could run Planify in debug mode using the terminal to view the logs.
`flatpak run --devel io.github.alainm23.planify`

**Comment by alainm23** [comment]
Hi, Planify 4.10 was released, could you please check if this bug still exists?

**Comment by alainm23** [comment]
I will close this Issue for the time it has been inactive, if the error still persists, feel free to reopen, thank you.
