### ISSUE TITLE
Planify using a lot of performance

### ISSUE THREAD

**Issue by Androz2091** [alainm23/planify#1333]
**Describe the bug**

Please let me know how I can debug this, Planify is taking a lot of RAM and CPU on my computer (this is one of the very very fews apps that triggers the fans, even IntelliJ does not).

**To Reproduce**
Keep the app opened for a few hours

**Screenshots**
![image](https://github.com/alainm23/planify/assets/42497995/61157b58-448b-4188-bcba-b5a694cb8f9c)

**Desktop (please complete the following information):**

![image](https://github.com/alainm23/planify/assets/42497995/932ed6f8-932b-4f3e-a770-8c9a280f3f55)

Flatpak Alain io.github.alainm23.planify   4.8 stable      system

**Comment by Gert-dev** [comment]
Noticing the same here. With `top` it goes up to 80% often. Using sysprof to profile looks like a lot of signals are being invoked and closures being run as a result:

![afbeelding](https://github.com/alainm23/planify/assets/24809863/85f63e9f-af45-4e09-980c-6ba2bc48cf07)

(The stack goes on with lowering total numbers, possibly some kind of recursion happening here.)

#1265 and #1151 are probably related to this. In my case I'm not using any kind of syncs, but have a not so small database; ~225 tasks of which ~100 are open.

**Comment by Letterus** [comment]
Yes, some thousands tasks here. Planify goes high on load and then crashes while loading them from Nextcloud.

**Comment by alainm23** [comment]
Hi, update to the latest version of Planify and check if the issue continues?

**Comment by Letterus** [comment]
No improvement here. Screenshot is from first sync. Planify also spams my syslog with the content of CalDAV appointments which I find very annoying - I cannot find real program output anymore.

![Bildschirmfoto von 2024-11-01 11 37 49@2x](https://github.com/user-attachments/assets/b4372168-7813-4e70-b282-9a348bac6d40)

**Comment by judicandus** [comment]
Same problem here. Planify installed via flatpak syncing with Nextcloud servers consumes most of my CPU and over 30gb of ram after the computer is on for some time (even if I did not open planify at startup). Only solution was for me to uninstall it.
