### ISSUE TITLE
Show tomorrow tasks in Today list

### ISSUE THREAD

**Issue by fenixservicios** [alainm23/planify#1339]
**Is your feature request related to a problem? Please describe.**
Would be great if we can see in Today list the tasks scheduled for the next day, it will complete the trilogy: overdue, today and tomorrow.

**Describe the solution you'd like**
Show in today list the tasks scheduled for tomorrow.

**Describe alternatives you've considered**
Alternative could be create a new list called "Tomorrow", But I think it is better to use today list.

**Additional context**

**Comment by Riksu9000** [comment]
The today view is for tasks that should be completed today. You can see tomorrow's tasks in the scheduled view. Can you describe the problem you're facing?

**Comment by Riksu9000** [comment]
In addition, you can show tomorrow's tasks by selecting the tomorrow filter with the quick find function.

**Comment by fenixservicios** [comment]
Ok, what you tell me solves what I need. It was my fault, I didn't pay attention to the "scheduled" button. That button does the job... thanks!Case closed.

Rafael Sifontes 

 

    On Friday, June 14, 2024 at 09:46:19 AM GMT-4, Riksu9000 ***@***.***> wrote:  
 
 


In addition, you can show tomorrow's tasks by selecting the tomorrow filter with the quick find function.

**Comment by alainm23** [comment]
That's right, the Scheduled and Tomorrow view does the job,
