### ISSUE TITLE
Add synchronization with Microsoft To Do

### ISSUE THREAD

**Issue by iliasen** [alainm23/planify#1340]
In this task management application, I would like to have the ability to integrate and synchronize with Microsoft To Do. This will allow users to easily manage their tasks and current affairs both in their own application and on the Microsoft To Do platform (many standard applications such as Samsung reminders are already synchronized with them).

**Comment by lucagervasi** [comment]
+1

**Comment by alainm23** [comment]
Hi and thanks for using Planify, as far as I know, MS Todo, does not have a public REST API and only uses GraphQL, and unfortunately Vala does not have a library to support it, anyway I will keep investigating.

**Comment by iliasen** [comment]
It's a pity that we can't add it now. I wish you all success with the development of the project

**Comment by LSeelig** [comment]
> Hi and thanks for using Planify, as far as I know, MS Todo, does not have a public REST API and only uses GraphQL, and unfortunately Vala does not have a library to support it, anyway I will keep investigating.

Is a Vala library necessary?
https://learn.microsoft.com/en-us/graph/todo-concept-overview#common-to-do-api-operations
https://learn.microsoft.com/en-us/graph/api/resources/todo-overview?view=graph-rest-1.0&source=recommendations
