### ISSUE TITLE
Several Nextcloud accounts

### ISSUE THREAD

**Issue by coanda45** [alainm23/planify#1341]
**Context**
On my nextcloud own server, my girlfriend and I have ours own personal accounts.
We will use tasks.org with caldav to share (in a collaborative way, so we can modify the same list) todo lists without using Google keep.
If I am right, Tasks.org allow us to shared todo list between nextcloud user but not modify a same todo list (I can modify mine but she can only read mine). So the only way is to use another shared nextcloud account and modify the same list on our cell phones (I know the risk of bad sync if we modify the same line at the same time).

So given theses informations, I discover on internet that Planify exists and allow me to connect to my nextcloud account and display the todo list, very well. So thanks!

Unfortunately, if i am right, planify allow us to connect to only 1 nextcloud account (so in my case the shared nextcloud account). 

**The solution I'd like**
I would like to have the ability to sync another nextcloud account (my personal one), in order to have my private to do list.
 
On tasks.org, it is possible to sync several nextcloud account, but I would like to have the same on my linux laptop to access to my todo list thanks to Planify.

Thanks!

**Comment by alainm23** [comment]
Hi and thank you for using Planify, this feature is under development, please be patient.

**Comment by coanda45** [comment]
Thanks!

**Comment by coanda45** [comment]
Problem solved. Thanks
