### ISSUE TITLE
When adding a sub-task with no name, content is lost

### ISSUE THREAD

**Issue by minosimo** [alainm23/planify#1342]
**Describe the bug**
When adding a sub-task, if it does not have a name, clicking add will cancel rather than adding, which can lead to losing entered content.

**To Reproduce**
1. Add a subtask
2. Put some content in the body, leaving the name blank
3. Click add
4. Window closes and text entered into body is lost

**Expected behavior**
- If content is added to a task, force user to give it a name or...
- Create a name using the first X characters of the content
- Something else

**Desktop (please complete the following information):**
 - OS or DE: Fedora 40
 - Version 4.8.1

**Additional context**

**Comment by alainm23** [comment]
Hi and thank you for using Planify, I will keep it in mind, it is a good improvement for the user experience.

**Comment by alainm23** [comment]
![image](https://github.com/alainm23/planify/assets/33765137/7320ff9f-a9d7-484c-8b09-a229447ca6ac)
