### ISSUE TITLE
Differentiate To-do name and body text entry fields

### ISSUE THREAD

**Issue by minosimo** [alainm23/planify#1343]
This is related to #1342. I often find myself entering a description without entering a to-do name, as it currently looks like a single text entry field, and losing everything I typed as a result.

![Screenshot from 2024-06-18 16-02-26](https://github.com/alainm23/planify/assets/19229302/c6d8af56-8ab5-43e1-9217-dce4a763745d)

I would suggest adding a light separator and placeholder text for the content/body (not sure what to call this) as well:
![Suggestion](https://github.com/alainm23/planify/assets/19229302/e74c40b4-6e81-4f50-bdd7-8523670ffbd1)

**Comment by alainm23** [comment]
![image](https://github.com/alainm23/planify/assets/33765137/a607cbfc-4e0e-4de4-92d2-fc0d38d11e54)
