### ISSUE TITLE
Add repeats by day of week

### ISSUE THREAD

**Issue by rsholmes** [alainm23/planify#1347]
**Is your feature request related to a problem? Please describe.**
There are tasks I would like to have repeating on certain multiple days every week, e.g. weekdays (Monday–Friday) but not weekends (Sat–Sun). At present this requires creating a separate, duplicate weekly task for each day.

**Describe the solution you'd like**
In custom repeat, have check boxes for selecting which days of the week to repeat, allowing for instance repeat on Mondays, Wednesdays, and Fridays

**Describe alternatives you've considered**
Add "every weekday" to the repeat options — simpler but less flexible

**Additional context**

**Comment by Riksu9000** [comment]
Have you tried these options? I haven't used them, but it looks like it might fit your need.

![image](https://github.com/alainm23/planify/assets/37774658/56af8201-de37-4786-b7c6-589c7555fe4a)

**Comment by rsholmes** [comment]
Thanks, that is what I wanted but wasn't initially able to find in the user interface.

**Comment by rsholmes** [comment]
Feature exists
