### ISSUE TITLE
Some issue detail view labels don't seem to be translatable

### ISSUE THREAD

**Issue by Gert-dev** [alainm23/planify#1348]
**Describe the bug**
Some labels don't appear to be translatable, such as :

* The `Attachments` and `Attach File` labels in the issue detail view sidebar.
* `Search or Create` in the labels dropdown in the issue detail view.

**To Reproduce**
1. Start with Dutch locale.
2. Open task detail view.
3. Observe attachments panel not being translated.
4. Check .po file but all strings are translated.
5. Search through pot file, but there is no string for `Attachments` or `Attach File`

**Expected behavior**
The strings can be translated.

**Screenshots**
![afbeelding](https://github.com/alainm23/planify/assets/24809863/5a354b5a-0a36-4dbf-99b5-12e644e6f09e)

![afbeelding](https://github.com/alainm23/planify/assets/24809863/1650cfc7-c3e8-429f-9ae3-00b331ece97e)

**Desktop (please complete the following information):**
 - OS or DE: GNOME 46
 - Version 4.8.4

**Additional context**
https://github.com/alainm23/planify/blob/7ba2400c41f5bed5b375f8334d8ba20356ffcdfc/src/Widgets/Attachments.vala seems to imply that these strings are in fact translated, but they don't seem to appear in the translation strings.

**Comment by alainm23** [comment]
Thank you for reporting it, the translation sources need to be updated.
