### ISSUE TITLE
2.0.8 crashes on start

### ISSUE THREAD

**Issue by danirabbit** [alainm23/planify#135]
Installing from packaging in the appcenter testing repo I get this output when running Planner:

```
com.github.alainm23.planner 
URL: /home/daniel/.local/share
(com.github.alainm23.planner:4814): Gtk-CRITICAL **: 08:51:18.276: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed
**
ERROR:/build/com.github.alainm23.planner-2.0.8/src/Services/Database.vala:1453:services_database_get_all_projects_no_area: assertion failed: (res == Sqlite.OK)
Aborted
```

**Comment by alainm23** [comment]
Have you tried Planner on another occasion?
If that is the case, try deleting your database file.
`/home/<user>/.local/share/com.github.alainm23.planner/`

**Comment by danirabbit** [comment]
Hey it works! Might be good to try to guard against a corrupt/old database though :)

**Comment by alainm23** [comment]
I will consider it thank you very much.
