### ISSUE TITLE
Add Repeat option when creating new To-Do

### ISSUE THREAD

**Issue by kekkoudesu** [alainm23/planify#1357]
**Is your feature request related to a problem? Please describe.**
I use Planify solely for Daily tasks. Right now I need to create the To-Do, edit the To-Do, and set Repeat to Daily.

**Describe the solution you'd like**
I'd like to be able to set the To-Do to repeat at the same time I create it. Less clicking involved.

**Comment by alainm23** [comment]
The recurring task view is now displayed in the date picker.
![image](https://github.com/user-attachments/assets/4eded6a5-871f-4812-8f70-a3007a9d4676)
