### ISSUE TITLE
instabil behaviour under kde neon 

### ISSUE THREAD

**Issue by Aaaamu** [alainm23/planify#1358]
Hi, I just started using planify and love it - in theory :)
In theory because various interactions with tasks and categories (clicking editing draging, etc.) can cause planify to freeze/react slowly and eventually exit: console output see below.

### I am running:

Operating System: KDE neon 6.0
KDE Plasma Version: 6.1.2
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.0
Kernel Version: 6.5.0-41-generic (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-8650U CPU @ 1.90GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
Manufacturer: LENOVO

System Version: ThinkPad X280

I am Syncing Tasks via Nextcloud. I am starting with a big bunch of tasks created with task.org app on android.
I am running the flatpak - snap was even more unstable.

### latest Terminal Output is

** (io.github.alainm23.planify:2): CRITICAL **: 19:41:50.499: services_database_set_parameter_str: assertion 'val != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 19:41:50.500: util_get_color: assertion 'key != NULL' failed

(io.github.alainm23.planify:2): Gdk-CRITICAL **: 19:41:50.500: gdk_rgba_parse: assertion 'spec != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 19:41:50.500: util_get_color: assertion 'key != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 19:41:50.500: util_set_widget_color: assertion 'color != NULL' failed
sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/8973</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/8973</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/194</d:sync-token>
</d:multistatus>

** (io.github.alainm23.planify:2): CRITICAL **: 19:41:52.610: services_database_set_parameter_str: assertion 'val != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 19:41:52.610: util_get_color: assertion 'key != NULL' failed

(io.github.alainm23.planify:2): Gdk-CRITICAL **: 19:41:52.610: gdk_rgba_parse: assertion 'spec != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 19:41:52.610: util_get_color: assertion 'key != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 19:41:52.610: util_set_widget_color: assertion 'color != NULL' failed
sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/194</d:sync-token>
</d:multistatus>

** (io.github.alainm23.planify:2): CRITICAL **: 19:41:52.614: services_database_set_parameter_str: assertion 'val != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 19:41:52.615: util_get_color: assertion 'key != NULL' failed

(io.github.alainm23.planify:2): Gdk-CRITICAL **: 19:41:52.615: gdk_rgba_parse: assertion 'spec != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 19:41:52.615: util_get_color: assertion 'key != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 19:41:52.615: util_set_widget_color: assertion 'color != NULL' failed
sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/13</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/13</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/3801</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/3801</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/1</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/1</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/128</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/128</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/19</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/19</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/1</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/1</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/1</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/1</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/1</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/1</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/1</d:sync-token>
</d:multistatus>

sync_tasklist
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:sync-token>http://sabre.io/ns/sync/1</d:sync-token>
</d:multistatus>

(io.github.alainm23.planify:2): Gtk-WARNING **: 19:43:02.687: Broken accounting of active state for widget 0x57fd33a99120(GtkRevealer)

(io.github.alainm23.planify:2): Gtk-WARNING **: 19:43:02.687: Broken accounting of active state for widget 0x57fd33ab2360(GtkBox)

(io.github.alainm23.planify:2): Gtk-WARNING **: 19:43:02.687: Broken accounting of active state for widget 0x57fd33ab51a0(GtkBox)

(io.github.alainm23.planify:2): Gtk-WARNING **: 19:43:02.687: Broken accounting of active state for widget 0x57fd33ab5960(GtkRevealer)

(io.github.alainm23.planify:2): Gtk-WARNING **: 19:43:02.687: Broken accounting of active state for widget 0x57fd33ab2b00(WidgetsReorderChild)

(io.github.alainm23.planify:2): Gtk-WARNING **: 19:43:02.687: Broken accounting of active state for widget 0x57fd33ab6270(GtkRevealer)

(io.github.alainm23.planify:2): Gtk-WARNING **: 19:43:02.687: Broken accounting of active state for widget 0x57fd33a96b90(LayoutsLabelRow)
Gdk-Message: 19:43:02.702: Lost connection to Wayland compositor.

any ideas what causes this?

**Comment by alainm23** [comment]
Hi @Aaaamu, Did you reproduce the same bug in Planify 4.10?

**Comment by alainm23** [comment]
I will close this issue for the time of inactivity, if it happens again, feel free to create a new issue.
