### ISSUE TITLE
Add new task button disappears

### ISSUE THREAD

**Issue by gavr123456789** [alainm23/planify#136]
**Describe the bug**
Add-new-task button disappears.

**To Reproduce**
IDK, It seems like it disappears when I switch to a project that has a task with a description, but other projects also have tasks with a description, maybe this is somehow related to the fact that it is the last one... look gif

**Expected behavior**
The add button is always available

**GIF**
![Peek 2020-01-20 13-14](https://user-images.githubusercontent.com/30507409/72718356-d85f4480-3b86-11ea-9198-a0f1f8b722c1.gif)

**Desktop (please complete the following information):**
 - DE gnome (Arch btw)
 - Version 3.34
 - Installed via Flathub

**Comment by krebszattila** [comment]
I can reproduce this by clicking "Upcoming" (the button disappears) and then clicking any of my projects: the button does not appear. However, if I click on "Inbox" or "Today" the button appears again.

**Comment by alainm23** [comment]
Thanks for your comments, I already fixed this problem, wait for a next update.

**Comment by gavr123456789** [comment]
@alainm23 Nice!, can you please ping here to let me know that.

**Comment by alainm23** [comment]
Sure 😉️.
