### ISSUE TITLE
All tasks are gone!

### ISSUE THREAD

**Issue by Henko-DE** [alainm23/planify#1372]
Hi There, 
today I open Planify and 90% of all tasks are gone! Poof! Just gone. Just a few under "Scheduled" and "Today" left, the "Inbox" totally empty, although I left it there with about 15 or so tasks, last time I worked with the app.

As well the Nextcloud connection is gone and I cannot reconnect, keeps coming up with error message "connection failed" under Preferences > Integrations

As if it would be a total new installation of the app.Since this happened for no apparent reason, I don't see a way to reproduce the problem.

I downloaded a backup from yesterday, but not even 50% of the tasks are being restored. And Nextcloud is still not available.

What the hell happened here? A ton of work is just gone. I cannot believe this.

Is there any chance for help?

Sincerely,
Henko

**Comment by alainm23** [comment]
Hi, I'm sorry about this, but I'm not sure what may have happened, from what source did you download Planify? You could download DBeaver and check the database status. 

`/home/<user>/.var/app/io.github.alainm23.planify/data/io.github.alainm23.planify/database.db
`
![image](https://github.com/user-attachments/assets/5256adec-acb2-4c5c-91f5-5341d9dc6f5a)

**Comment by alainm23** [comment]
Hello, any update on this, it happened again.

**Comment by alainm23** [comment]
Apparently this was an isolated problem, I will close the problem for now, if the bug persists, feel free to create a new issue.
