### ISSUE TITLE
Move Recurrence To Task Properties

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#1373]
**Is your feature request related to a problem? Please describe.**
Accessing the recurrence section of a task requires several clicks, first by clicking on the task, next by clicking on the three dots then clicking repeat.

**Describe the solution you'd like**
I propose that the recurrence/repeating options of a task be located in the task properties, similarly to the task priority, due date and reminders. This would reduce the amounts of clicks needed and make the interface more intuitive. 

Additionally, the repeating interface could be simplified by removing the preexisting options for daily, weekly, monthly and yearly. Clicking the recurrence property could directly launch the recurrence dialog. The option to clear the recurrence could also be added directly to the recurrence dialog

**Describe alternatives you've considered**
None considered so far. 

**Additional context**
None

**Comment by alainm23** [comment]
The recurring task view is now displayed in the date picker.
![image](https://github.com/user-attachments/assets/4eded6a5-871f-4812-8f70-a3007a9d4676)
