### ISSUE TITLE
Backup function creates backup with old timestamp and does not include recent changes

### ISSUE THREAD

**Issue by stefs** [alainm23/planify#1375]
**Describe the bug**
So I just lost 3 hours of work with no way to recover it, because I used the backup function and wanted to try the restore function. The backup function created a backup with a timestamp 3 hours ago, no matter how often I click it. It's always the same timestamp 3 hours ago. I thought it's just a mistake in the name, but actually the changes of the last 3 hours were not included. Since I decided to test if the backup was successful, I restored it and lost many new tasks I just created (I was in the process of migrating to Planify).

**To Reproduce**
I used the create backup button in the settings menu. But when I press it again it works now as expected. I don't know what triggered the creation of outdated backups.

**Expected behavior**
When I click backup, then backup the current state and not a state 3 hours ago.

**Desktop (please complete the following information):**
 - OS or DE: Gnome
 - Version 46
 - Planify 4.9.0

**Additional context**
This is especially sad, because the backup page in the settings said I should not worry about data loss.

Maybe it has to do something with committing the SQL database, it's just a guess. I had it running for 3 hours so maybe the backup didn't include any changes from the current session.

Also I have no problem just using .db files for backup. No need to risk problems converting everything to JSON and back.

Planify also sometimes freezes and crashes while restoring backups, but that's another problem.

It turned out I did not completely loose my data, because the programs I was migrating away from (Logseq and Getting Things GNOME) turned out to have built-in automatic backup which I could restore. I could now manually repopulate the data in Planify.

**Comment by alainm23** [comment]
Hi, Planify 4.10 solved this issue
