### ISSUE TITLE
Newest update broke the sync option for me completely

### ISSUE THREAD

**Issue by McBaumwolle** [alainm23/planify#1380]
**Describe the bug**
I updated to 4.10.0 today, and it removed my Nextcloud account, so I just added it. But every time I close and reopen the app, it is gone and needs to be setup again. 

**To Reproduce**
1. Set up a Nextcloud connection
2. Close the app
3. Open the app.
4. See that Nextcloud is gone

**Expected behavior**
It should remember the added account. 

**Screenshots**
This is what it looks like after adding the account. 
![image_2024-07-30_11-12-59](https://github.com/user-attachments/assets/0c2022a6-a562-4949-b8bd-27206cf3aa0b)

And after a close/reopen it is back to "new". 
![image](https://github.com/user-attachments/assets/797d1946-6bc0-4a64-a277-2652973556c8)

**Desktop (please complete the following information):**
 - OS or DE: Ubuntu 24.04 LTS with GNOME 46 on a Surface Pro 8 with SurfaceKernel
 - Version Planify 4.10.0

<details><summary>neofetch Ubuntu</summary>

OS: Ubuntu 24.04 LTS x86_64
Host: Surface Pro 8 124I:00066T:000M
Kernel: 6.9.3-surface-2
Uptime: 16 mins
Packages: 2611 (dpkg), 102 (flatpak)
Shell: bash 5.2.21
Resolution: 2880x1920
DE: GNOME 46.0
WM: Mutter
WM Theme: Adwaita
Theme: Yaru-purple-dark [GTK2/3]
Icons: Yaru-purple [GTK2/3]
Terminal: gnome-terminal
CPU: 11th Gen Intel i5-1135G7 (8) @
GPU: Intel TigerLake-LP GT2 [Iris Xe]
Memory: 2372MiB / 7784MiB

</details>

**Additional context**
I had a similar issue with Nextcloud Desktop a while back where (only the) flathub-version behaved the same and could not remember the login. 

EDIT: I reverted to the previous  flatpak commit and the issue is still there. It is very weird, even after a new install (of Planify) it shows the account at first but after closing, it is gone. 

EDIT2: I can also reproduce this issue on Linux Mint 21.3.

EDIT3: Okay it is a bit random, when Planify is not opened for some minutes it shows the account but is unable to sync, in my case it also split the accounts haha. 

![image](https://github.com/user-attachments/assets/fbb4c3ef-1d23-473b-a7cf-5748d401729a)

**Comment by dnsflnv** [comment]
Same thing. At every start of app, you need to create a NextCloud account.

**Comment by McBaumwolle** [comment]
Okay it is a bit random, when Planify is not opened for some minutes it shows the account but is unable to sync, in my case it also split the accounts haha. 

![image](https://github.com/user-attachments/assets/fbb4c3ef-1d23-473b-a7cf-5748d401729a)

**Comment by alainm23** [comment]
I'm very sorry, your Nextcloud account does exist, it's just that Planify doesn't show it, I'm sending a setting to fix it.

**Comment by McBaumwolle** [comment]
omg thank you so much!
