### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by foegra** [alainm23/planify#1381]
Hej!
I love the app on Linux. In my opinion best implementation of apps from practical and estetical points of view. 

Would be great to have this in Windows environment as well!

**Comment by JJeeff248** [comment]
#542 This has been requested and denied before. Would be nice to have but not in scope for this project

**Comment by ieris19** [comment]
I am actually looking to compile this myself on Windows. Can't promise much since I don't have much time, but if any of the maintainers needs a hand, maybe I can be of help? Otherwise I'll report back if I ever get the time to get a fork running on Windows. 

Technically, and in theory, all dependencies can be compiled for Windows and Vala can compile Windows binaries if you use something like MSY2 to compile, so it IS possible, but it doesn't look straight-forward

**Comment by foegra** [comment]
> #542 This has been requested and denied before. Would be nice to have but not in scope for this project

sad to hear. One of those rare moments when there is a cool application for Linux, not for Windows.

**Comment by alainm23** [comment]
Not to raise the hype, but at some point I did an experiment trying to port Planify to Windows, I had to comment out an incredible amount of code and remove some of its features, but I didn't feel very comfortable using it, it was very slow and some animations looked very bad. I'm the only developer of Planify and supporting it on Windows would require a huge investment of time, and I'm not sure if I could do it.

![image](https://github.com/user-attachments/assets/d8c3914e-8b52-4c2f-9169-16cfbbf39414)

**Comment by Dmytro-Shulha** [comment]
I was recently trying to build Planify for Windows (on my Windows PC), and the thing that I got stuck with is the lack of `webkitgtk-6.0` package for MinGW environment.

And from those issues it seems like it's maintainers are not going to bring it to Windows any time soon:

https://github.com/msys2/MINGW-packages/issues/19965
https://github.com/msys2/MINGW-packages/discussions/9512#discussioncomment-2906753

And correct me if I am wrong, but even when building Planify for Windows on Linux PC, or from WSL environment, it is still necessary to have all dependencies as MinGW packages (or, like, built for Windows).

So, I totally understand the challenges of porting that application to Windows :(
Probably it's even not the only package that is causing problems.

Apart from that, I really like that application! 
And would like to express my gratitude and appreciation to developers for creating and maintaining it :)
