### ISSUE TITLE
Completed tasks do not show

### ISSUE THREAD

**Issue by MarsAstro** [alainm23/planify#1386]
At seemingly random times, the software decides to ignore the "Show Completed Tasks" setting when in List mode. Normally you're supposed to see completed tasks, but sometimes after a restart or reboot, they're all just gone. Toggling between Show and Hide does nothing. The tasks are still visible in the Board mode, but not List mode.

I haven't really found a consistent way to reproduce this, I can't find any pattern to when it chooses to heed or ignore the setting.

I'm encountering this issue on Linux Mint 22

**Comment by MarsAstro** [comment]
Will a fix for this be coming in the next update? Or was it closed for some other reason?

**Comment by alainm23** [comment]
Yes, wait for the 4.10.4  update which should arrive in a few hours.

**Comment by MarsAstro** [comment]
> Yes, wait for the 4.10.4 update which should arrive in a few hours.

Sweet, thanks for the good work! I'll throw a donation your way, this app has been a godsend
