### ISSUE TITLE
Wrong label number displayed in the left panel

### ISSUE THREAD

**Issue by GuillaumeCz** [alainm23/planify#1387]
**Describe the bug**
The number of labels showed in the left panel doesn't seem right.

**To Reproduce**
1. Create 3 tasks with each a different label

**Expected behavior**
When there's 3 created labels, the left panel should show "3" in the label section.

**Screenshots**
![Capture d’écran du 2024-08-01 07-59-48](https://github.com/user-attachments/assets/d094ca9b-e961-4c3b-b4aa-dad3dd509f75)

The value of the left panel label section ("Etiquettes" in French) shows that there is 6 labels, while there's obviously only 3 existing labels ("PR", "numeric-input" and "Stripe")

**Desktop (please complete the following information):**
 - OS or DE: Fedora 39 && Gnome 45.8.1

**Additional context**
It's my first use of the app, I don't exclude the fact that I misunderstood something.

**Comment by lixeix** [comment]
Hello, 

Seeing the issue I went and check and same for me I.
The panel label section ("Etiquettes" in French) shows that there is 66 labels, while I have only 26.

This leads me to check, and the label panel is showing how many tasks with at least on label you have, not how many labels you have. 

Now that I think of it I think it might be more usefull this way. 

In any case, I don't think it is a bug. ;)

**Comment by GuillaumeCz** [comment]
Thanks for your response ! 

Indeed I was misunderstanding this number and I agree that in this case it's not a bug,.

Since I have a response and I better understand this number, I'm closing this issue.
