### ISSUE TITLE
"Unnacceptable TLS certificate" error when adding Nextcloud account

### ISSUE THREAD

**Issue by alvaroemtnez** [alainm23/planify#1389]
**Describe the bug**
I've been using Planify with my self-hosted Nextcloud server for a couple months now, in Fedora. This morning the app got updated to the lastest version and I noticed it was stuck synchronizing. I deleted the account, attempted to re-add it and it gave an "**Unnacceptable TLS certificate**" error. My server's certificate looks fine (verified by ZeroSSL, exp. date 4th Oct, valid from the 6th July, RSA4096 and obtained using acme.sh). Works fine in every browser and app I've used (including Planify up to this morning).

BTW, I'm loving the new option to hide "On This Computer" reminders, as I wasn't using them. This app is miles ahead of any other reminders app available for Linux, congratulations.

The only thing I've been experiencing is that **the reminders order is not properly synced between the app and the nextcloud server, etc.** The order is properly kept between the Nextcloud Web UI, Android Tasks.org app, and also macOS and iOS native apps (I got rid of these two now, but it worked when I had them). But Planify is not consistent with this order. I opened an issue a while ago about this, and it got improved, as the first time I set up the account it displayed the correct order (_in most cases_). But as soon as you reorder something in Planify or NC/Tasks.org/etc, it doesn't get synced (planify does keep the order you set when you open the app again, but it looks like it's not pushed to the server). Still, it's not the end of the world and the app worked flawlessly.

**To Reproduce**
1. Go to Preferences/Integrations
2. Add Nextcloud Account
3. See error

**Expected behavior**
Nextcloud account should be added

**Screenshots**
![Captura de pantalla de 2024-08-01 13-43-49](https://github.com/user-attachments/assets/62b4fd17-8dbc-4830-aa75-fc65e834ebab)

**Desktop:**
 - OS or DE: Fedora Linux 40 (Workstation Edition) / Kernel 6.9.12-200.fc40.x86_64 + GNOME 46.3.1
 - Version: 4.10.3

EDIT!: As soon as I opened the issue, I saw there's a new version solving an issue for nextcloud servers using a custom port. That was quick! As soon as it's up on flathub, I'll test it, maybe it solves my thing.

**Comment by alainm23** [comment]
I'm sorry, how are you entering your server URL?

**Comment by alainm23** [comment]
And if, indeed, Planify does not update the order of the tasks, only locally, I will take it into account as an improvement.

**Comment by alvaroemtnez** [comment]
> I'm sorry, how are you entering your server URL?

https://[FQDN]:[PORT]
I also tried the CalDAV links that the NC UI gives:
https://[FQDN]:[PORT]/remote.php/dav
and
https://[FQDN]:[PORT]/remote.php/dav/principals/users/[NC USER]/


> And if, indeed, Planify does not update the order of the tasks, only locally, I will take it into account as an improvement.

Thank you so much! That would be a huge add to the app :)

**Comment by alainm23** [comment]
Oh, I see you are also using a custom port, version 4.10.4 has been shipped, it should fix your problem, please be patient, it should arrive in a couple of hours. Thank you for using Planify.

**Comment by alvaroemtnez** [comment]
Yes! I'm really sorry, it got released while I was writing the original comment and only noticed it after sending it :( I then edited the comment saying I had just seen that.

Thank you so much! I'll give it a try :)

**Comment by alvaroemtnez** [comment]
Everything perfect :)
