### ISSUE TITLE
Very high memory usage

### ISSUE THREAD

**Issue by janvlug** [alainm23/planify#1391]
**Describe the bug**
Planify uses too much memory.

**To Reproduce**
1. Start Planify
2. Start using your computer while Planify is also running
3. After a while Planify uses so much memory that the computer is mainly busy swapping

**Expected behavior**
Limited memory usage

**Desktop (please complete the following information):**
 - Fedora 40 workstation GNOME Wayland

I run Planify as a Flatpak. Planify version: 4.10.3
I use Planify with Nextcloud (CalDav - Nextcloud), with many task lists.
It seems like Planify is nearly always synchronizing.

**Comment by janvlug** [comment]
Screenshot of top after running for a few hours:
![image](https://github.com/user-attachments/assets/f386fd1b-dbf7-483c-ae00-f87ebb3f8e66)

**Comment by alainm23** [comment]
Hello and thank you for using Planify, this is a known issue and I am working to fix it.

**Comment by qgjdev** [comment]
Cheers @alainm23 , I was wondering the same, good to know you're working on a fix!

**Comment by Katze-942** [comment]
I confirm that this happens every time the tasks are synchronized. In my case, automatic synchronization is enabled and the amount of memory consumed increases every 15 minutes.

**Comment by alainm23** [comment]
@Katze-942 Apparently this feature not only affects Planify's performance, but also Todoist's servers, I have been notified that Planify is having a high load of requests and errors, and the only explanation I have is the automatic sync. I'm going to remove this feature for a while and look for a solution.

**Comment by Katze-942** [comment]
@alainm23 removing the automatic synchronization function will not solve the problem, since memory increases both during manual synchronization and when switching between tabs (sometimes). For example, if you go to the tab with all tasks, memory consumption increases by gigabytes and does not decrease after a while.

P.S: This problem is also relevant for NextCloud, not only Todoist

**Comment by janvlug** [comment]
I checked my Nextcloud server logs, but did not see any logging related to this issue.

What I do see now in Planify is that a number, but not all of the task list keep a spinner behind them. Like they are never updated.

Currently using version: 4.11.0

**Comment by madpipeline** [comment]
With the latest release, `4.11.6` this is still an ongoing issue.

**Comment by janvlug** [comment]
See also #1497.
