### ISSUE TITLE
Nextcloud Login Error

### ISSUE THREAD

**Issue by Scrambled777** [alainm23/planify#1393]
**Describe the bug**

1. Cannot login in the Nextcloud instance at server URL `https://efss.qloud.my/`.
2. I have TOTP enabled.
3. On Nextcoud Setup page, after enter login credentials I got following error:
```bash
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:o="http://owncloud.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\PasswordLoginForbidden</s:exception>
  <s:message/>
  <o:hint xmlns:o="o:">password login forbidden</o:hint>
</d:error>
```
4. TOTP window cannot be reached. 
5. I am entering my Email in `User Name` field.

**Expected behavior**
After entering login credential, 2FA window should open.

**Screenshots**
![Screenshot_20240803_205801](https://github.com/user-attachments/assets/6cb47236-bf43-4d66-8ed3-f0bb80272599)

**Desktop (please complete the following information):**
 - OS or DE: Fedora 40 [KDE Plasma 6.1.3] 
 - App Version: 4.10.5

**Comment by alainm23** [comment]
Hi, have you tried creating an app password?
![image](https://github.com/user-attachments/assets/48ebb376-c7ae-436f-8570-bb5d878f9fa1)

**Comment by Scrambled777** [comment]
> Hi, have you tried creating an app password? 

I have just tried and was able to login. I didn't even knew that could be done. 
Thanks a lot.

**Comment by alainm23** [comment]
Don't worry, that's why I'm also creating a documentation website, to take these little details into account.
