### ISSUE TITLE
Planify crashes when task with subtasks is closed in kanban view (and more)

### ISSUE THREAD

**Issue by lixeix** [alainm23/planify#1395]
**Describe the bug**
Planify crashes when task with subtasks is closed in kanban view and sometimes other views. 

**To Reproduce**

1. Create a task
2. Add at list 2 subtasks
3. Set view to kanban
4. Check as done the task
5. Planify freezes and then crashes.

Side notes : 

- sometimes it also happens on list view / today view, but can't fin a recurring pattern
- if you pre-check all subtask, it still crashes
- happens on small and big projects (in number of tasks open / closed)

**Expected behavior**
I expect the app not to crash. ;)

**Screenshots**

https://github.com/user-attachments/assets/1db91f58-72ad-413c-b818-d4a36e00e714

https://github.com/user-attachments/assets/15fe8770-9fd0-4fbb-8a0c-c4e12cdb8b04

**Crash report** 
`io.github.alainm23.planify killed by SUGSEV - org.freedesktop.GnomeAbrt`

```
--- Running report_uReport ---
Erreur : Unable to open './coredump': Aucun fichier ou dossier de ce nom

--- collect_vimrc_user ignoré ---
Aucune action correspondante trouvée pour cet évènement.

--- collect_GConf ignoré ---
Aucune action correspondante trouvée pour cet évènement.

--- collect_vimrc_system ignoré ---
Aucune action correspondante trouvée pour cet évènement.

--- collect_xsession_errors ignoré ---
Aucune action correspondante trouvée pour cet évènement.

--- Running analyze_CCpp ---
Création de la trace arrière
La trace arrière a été générée et enregistrée, 103478 octets
Can't open file 'component' for reading: Aucun fichier ou dossier de ce nom

--- Running analyze_BodhiUpdates ---
Looking for similar problems in bugzilla
```

**Desktop:**

- OS or DE: Fedora Linux 40
- GNOME : 46
- Windowing system : Wayland
- Panify Version 4.10.5
- Flatpack version installed

**Additional context**

I've been experiencing this bug for quite a while now, but wasn't sur of the pattern. I also experienced it on Fedora 37.
I do not sync Planify to any app.

**Comment by alainm23** [comment]
Fixed in v4.10.6, update should be ready in a few hours.
