### ISSUE TITLE
Meson dependency "libedataserverui-1.2" not found

### ISSUE THREAD

**Issue by erazemk** [alainm23/planify#14]
**Describe the bug**
When trying to build with meson, this error pops up:

`meson.build:27:0: ERROR:  Dependency "libedataserverui-1.2" not found, tried pkgconfig`

**To Reproduce**
1. Clone repo
2. Download all the dependencies and elementary-sdk (might not be necessary)
3. Start `meson build`

**Expected behavior**
Meson builds the project

**Desktop (please complete the following information):**
 - OS or DE: ElementaryOS Juno
 - Version: Latest? (Freshly cloned from Github)

**Additional context**
Meson build log: https://pastebin.com/4SuD799T

**Comment by alainm23** [comment]
I’m sorry, I forget to add this dependence on my README file, try to install `libedataserverui1.2-dev`

**Comment by erazemk** [comment]
I actually had `libedataserverui-1.2-dev` installed. Could the problem be that my version was `libedataserverui-1.2-2`?

**Comment by alainm23** [comment]
`libedataserverui-1.2-dev` is diferent to  `libedataserverui1.2-dev`

**Comment by erazemk** [comment]
Oh, you're right. It works perfectly now, thanks :)

One more dependency I had to install was `gtksourceview-3.0`.

**Comment by alainm23** [comment]
Hey thank you, I also forgot to put this dependency in my README file
