### ISSUE TITLE
Update Deletes ALl My Tasks

### ISSUE THREAD

**Issue by ccm27** [alainm23/planify#140]
**The New Mon Jan 20 2020 Update Removed My Tasks**

When I had all my new years resolutions and tasks on the old planner, updating it deleted all of them.

**To Reproduce**

1. You have all your tasks on the old planner
3. you update
4. you click localy instead of using todist
5. All my tasks are gone :(

**Expected behavior**

My tasks should move over to the new update

**Screenshots**

none

**Desktop**
 - OS or DE: Elementary os
 - Version 2.0.8

**Comment by alainm23** [comment]
I'm sorry. Planner 2 was built completely from 0 and support for Planner 1 will no longer be available.
