### ISSUE TITLE
Cannot login with Todoist

### ISSUE THREAD

**Issue by mazynoah** [alainm23/planify#1400]
**Describe the bug**
I cannot login with todoist.  When trying to add todoist as a source, I am met with a loading tab and nothing else

**To Reproduce**
1. Go to preferences
2. Click on integrations
3. Add a source
4. Select Todoist
5. Nothing happens

**Expected behavior**
A login prompt for todoist shows up

**Desktop (please complete the following information):**
 - OS or DE: [e.g. pantheon, unity, gnome]
 - Version [e.g. 0.1.2]

**Additional context**
When run using `fflatpak run io.github.alainm23.planify`, this error shows up on step 4:
```
flatpak-spawn: Invalid byte sequence in conversion input
Try "flatpak-spawn --help" for more information.

```

**Comment by alainm23** [comment]
It seems to be a bug in Flatpak, you could check one of these solutions:

https://github.com/flathub/org.cockpit_project.CockpitClient/issues/33#issuecomment-1976782272
https://github.com/flatpak/flatpak/issues/5564#issue-1955582768

**Comment by mazynoah** [comment]
Thank you, reinstalling the glib packages and running the app like so `PS1= flatpak run io.github.alainm23.planify` fixed it.
