### ISSUE TITLE
Snap version is gone?

### ISSUE THREAD

**Issue by gustavo-dotcom** [alainm23/planify#1401]
I reinstalled Ubuntu a week ago and now I noticed that Planify is gone from the Snap store. Is it not being supported anymore?

**Comment by rikonaka** [comment]
Same question here.

![image](https://github.com/user-attachments/assets/95d0b7c2-0851-476d-90e2-5ca6a8109af3)

**Comment by alainm23** [comment]
Hi, the new versions of Planify cannot yet be built using Snap, I have decided to hide it for the time being, migrate to the package in Flatpak to get the
