### ISSUE TITLE
Complete tasks to show

### ISSUE THREAD

**Issue by liamhan0905** [alainm23/planify#1402]
After a task is completed, it's crossed out and disappears. Is there a way to view the completed task? 

After a week of working, I want to see what tasks I've completed and there doesn't seem to be a way to recall the previous tasks.

**Comment by alainm23** [comment]
In the **View Option Menu** popover, select the Show **Completed Tasks option**.

![image](https://github.com/user-attachments/assets/c2c8b9c2-419a-4668-bb2c-8cae6806d06c)
