### ISSUE TITLE
Certificate TLS inacceptable

### ISSUE THREAD

**Issue by coanda45** [alainm23/planify#1405]
Hi, under a Synology NAS (DSM 7.2), Nextcloud is installed from Docker.

On my laptop (Debian 12, Planify 4.10.7), I try to connect to the tasks (as with Tasks, under my Android smartphone).

Previously I can connect to one of my 2 accounts existing under Nextcloud (one private, one shared with my girlfriend).
Thanks to the last update (Thanks for it!!), we are allowed to have several accounts.

Unfortunately, after update, I can't connect to these accounts anymore.

The settings are the following:
IP : https://my_local_ip_address:the_port/remote.php/dav/calendars/username
Login: the nextcloud login (username)
Pass : the password of this account.

Result : 
![image](https://github.com/user-attachments/assets/73359312-2722-4071-be0a-df0653a204be)

Same problem when using Tailscale which works with other apps (Cospend,....)

Thanks!

Fabien

**Comment by coanda45** [comment]
Same problem when using quickconnect (was working before I switch to Tailscale), despite this comment here:
https://github.com/alainm23/planify/issues/1306#issuecomment-2293523509

**Comment by coanda45** [comment]
Everything works fine with tailscale under my Android Phone.

**Comment by alainm23** [comment]
Version 4.10.8 should fix the bug, expect the update to arrive in a couple of hours.

**Comment by coanda45** [comment]
Thanks for your reactivity!

**Comment by coanda45** [comment]
I confirm, Problem solved. Thanks!
