### ISSUE TITLE
White font on white in Todoist login and password inputs when dark theme selected

### ISSUE THREAD

**Issue by oskarkunik** [alainm23/planify#141]
When dark theme is selected, text inputs Todoist authentication window stay white (background), but font gets white color from theme. This makes the font invisible (until you select it inside the input field).

1. Go to Preferences
2. Change Theme to 'Night'
3. In Preferences click on Todoist
4. Try typing in Email or Password fields

Text in input fields should stay black regardless of app theme selected.

 - OS or DE: elementary OS 5.1, Pantheon
 - 2.0.8

This is not a breaking bug, but the new app looks so beautiful I thought it's worth mentioning.

**Comment by alainm23** [comment]
I can't reproduce the error. Could you send me a screenshot please?

**Comment by oskarkunik** [comment]
Sure,

This is what I see when typing in Email:

![Screenshot from 2020-01-21 18-14-57](https://user-images.githubusercontent.com/8790204/72826957-26a14000-3c7a-11ea-837c-c362217fd37d.png)

When I select the contents of the field I see:

![Screenshot from 2020-01-21 18-15-10](https://user-images.githubusercontent.com/8790204/72826997-3e78c400-3c7a-11ea-80ff-a7b3020f06c4.png)

EDIT

And here's a gif that tries to capture the bug:

![Screenrecordfrom2020-01-21181837](https://user-images.githubusercontent.com/8790204/72827452-19d11c00-3c7b-11ea-87a5-56fd8d1fdeb7.gif)
