### ISSUE TITLE
4.10 still extremely unstable with linux kde wayland and caldav

### ISSUE THREAD

**Issue by Aaaamu** [alainm23/planify#1418]
Planify is still unusable on my setup. I have large caldav todo lists that seem to slow down planify a lot more than local tasklists do. any button action can cause p. to crash. last message is usually about lost connection to wayland. Ill paste an excerpt from  terminal output below. Another problkem is that the categories/labels from caldav are imported but the atribution to the respective tasks is lost, which means no tasks appear when choosing a label.  (it works for local lists though)

Also saving new tasks on caldav lists never works (turning weel on save button for eternity) (it works for local lists)

terminal excerpt (flatpak): 
`
** (io.github.alainm23.planify:2): CRITICAL **: 14:21:44.107: util_set_widget_color: assertion 'color != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 14:21:45.286: services_database_set_parameter_str: assertion 'val != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 14:21:45.287: util_get_color: assertion 'key != NULL' failed

(io.github.alainm23.planify:2): Gdk-CRITICAL **: 14:21:45.287: gdk_rgba_parse: assertion 'spec != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 14:21:45.287: util_get_color: assertion 'key != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 14:21:45.287: util_set_widget_color: assertion 'color != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:09:17.759: util_get_color: assertion 'key != NULL' failed

(io.github.alainm23.planify:2): Gdk-CRITICAL **: 16:09:17.759: gdk_rgba_parse: assertion 'spec != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:09:17.759: util_get_color: assertion 'key != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:09:17.759: util_set_widget_color: assertion 'color != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:09:17.759: util_get_color: assertion 'key != NULL' failed

(io.github.alainm23.planify:2): Gdk-CRITICAL **: 16:09:17.759: gdk_rgba_parse: assertion 'spec != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:09:17.759: util_get_color: assertion 'key != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:09:17.759: util_set_widget_color: assertion 'color != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:09:17.760: util_get_color: assertion 'key != NULL' failed

(io.github.alainm23.planify:2): Gdk-CRITICAL **: 16:09:17.760: gdk_rgba_parse: assertion 'spec != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:09:17.760: util_get_color: assertion 'key != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:09:17.760: util_set_widget_color: assertion 'color != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:09:17.760: util_get_color: assertion 'key != NULL' failed

(io.github.alainm23.planify:2): Gdk-CRITICAL **: 16:09:17.760: gdk_rgba_parse: assertion 'spec != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:09:17.761: util_get_color: assertion 'key != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:09:17.761: util_set_widget_color: assertion 'color != NULL' failed

(io.github.alainm23.planify:2): Gtk-WARNING **: 16:09:31.075: AdwBreakpointBin 0x5e194777dfc0 (widget) reported min height 285 and natural height 250 in measure() with for_size=-1; natural size must be >= min size

(io.github.alainm23.planify:2): Gtk-WARNING **: 16:09:31.075: AdwBreakpointBin 0x5e194777dfc0 (widget) reported min height 285 and natural height 250 in measure() with for_size=389; natural size must be >= min size

(io.github.alainm23.planify:2): Gtk-WARNING **: 16:09:40.397: AdwBreakpointBin 0x5e194777dfc0 (widget) reported min height 285 and natural height 250 in measure() with for_size=-1; natural size must be >= min size

(io.github.alainm23.planify:2): Gtk-WARNING **: 16:09:40.464: AdwBreakpointBin 0x5e194777dfc0 (widget) reported min height 285 and natural height 250 in measure() with for_size=389; natural size must be >= min size

(io.github.alainm23.planify:2): Gtk-WARNING **: 16:09:51.528: AdwBreakpointBin 0x5e194777dfc0 (widget) reported min height 285 and natural height 250 in measure() with for_size=-1; natural size must be >= min size

(io.github.alainm23.planify:2): Gtk-WARNING **: 16:09:51.574: AdwBreakpointBin 0x5e194777dfc0 (widget) reported min height 285 and natural height 250 in measure() with for_size=389; natural size must be >= min size

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:11:52.704: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 16:11:52.731: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:11:59.162: util_get_color: assertion 'key != NULL' failed

(io.github.alainm23.planify:2): Gdk-CRITICAL **: 16:11:59.162: gdk_rgba_parse: assertion 'spec != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:11:59.162: util_get_color: assertion 'key != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:11:59.162: util_set_widget_color: assertion 'color != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:11:59.162: util_get_color: assertion 'key != NULL' failed

(io.github.alainm23.planify:2): Gdk-CRITICAL **: 16:11:59.162: gdk_rgba_parse: assertion 'spec != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:11:59.162: util_get_color: assertion 'key != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:11:59.162: util_set_widget_color: assertion 'color != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:11:59.163: util_get_color: assertion 'key != NULL' failed

(io.github.alainm23.planify:2): Gdk-CRITICAL **: 16:11:59.163: gdk_rgba_parse: assertion 'spec != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:11:59.163: util_get_color: assertion 'key != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:11:59.163: util_set_widget_color: assertion 'color != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 16:11:59.163: util_get_color: assertion 'key != NULL' failed

(io.github.alainm23.planify:2): Gdk-CRITICAL **: 16:11:59.163: gdk_rgba_parse: assertion 'spec != NULL' failed

`

**Comment by alainm23** [comment]
Hi, have you tried Planify 4.11? it solved the problem of labels and several performance improvements.
