### ISSUE TITLE
Typo in project Homepage url in Elementary app store

### ISSUE THREAD

**Issue by oskarkunik** [alainm23/planify#142]
Planner's Homepage link in elementary OS app store leads to:

`https://https//planner-todo.web.app`

1. Go to AppCenter in Elementary OS
2. Open Planner's page
3. Scroll down to the footer
4. Hover/click on Homepage

The url should be

`https://planner-todo.web.app`

![image](https://user-images.githubusercontent.com/8790204/72784728-bec30900-3c29-11ea-85ba-3154085025d1.png)

**Desktop (please complete the following information):**
 - OS or DE: Elemenary OS with Pantheon
 - Version 2.0.8

**Comment by oskarkunik** [comment]
I just noticed this is a duplicate/related to #138

**Comment by alainm23** [comment]
Thanks for your observation but this is duplicated #138.
