### ISSUE TITLE
Setting colors for projects seems not to work

### ISSUE THREAD

**Issue by oskarkunik** [alainm23/planify#143]
Picking a color for project doesn't change anything.

1. Add a new Project
2. Click on the Project's menu icon
3. Click on Colors
4. Pick a color
5. The color gets saved (you can see it selected in the picker) but is not set for the Project

The color should be applied to the Project

 - OS or DE: Elementary OS, Pantheon
 - Version 2.0.8

**Comment by oskarkunik** [comment]
OK, now (after using the app for some time) I noticed that there's progress being displayed in the circle next to Project's name.

Closing.

**Comment by alainm23** [comment]
😁️

**Comment by 4jNsY6fCVqZv** [comment]
At least don't explain it yourself until I have created a project with tasks and worked through some of them. So it really seems as if the color selection does not work. Is there another way to make the workflow clearer for users?

**Comment by 4jNsY6fCVqZv** [comment]
At least it doesn't explain itself until I have created a project with tasks and worked through some of them. So it really looks like the color selection doesn't work. Is there any other visual way to make the workflow clearer for users?

**Comment by alainm23** [comment]
We could use the Project tutorial to teach about it.

**Comment by 4jNsY6fCVqZv** [comment]
Okay, it's definitely worth a try. I can't wait to see your design for this!

**Comment by 4jNsY6fCVqZv** [comment]
Okay, it's definitely worth a try. I am curious about your design for this!
