### ISSUE TITLE
No Caldav on Planify installed with Flathub

### ISSUE THREAD

**Issue by joe67** [alainm23/planify#1430]
**Describe the bug**
I installed plnify wirth Flat Hub on Debian 12.

There is no calldav service to connect, you can only select  Todoist or  nectcloud as source.
I saw at some sites that planify should support calldav.
Do i got an old Version of planify?

![Plnify](https://github.com/user-attachments/assets/257396e3-2f50-4aca-b48a-2a3a04058645)

**Screenshots**

**Desktop (please complete the following information):**
 - OS or DE: [ Debian 12, gnome]

**Comment by alainm23** [comment]
Hi and thank you for using Planify, CalDAV support is still under development.

**Comment by joe67** [comment]
> Hi and thank you for using Planify, CalDAV support is still under development.

Is there a possablity to tes planify with calldav?
