### ISSUE TITLE
Time format should automatically be set to the system standard

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#144]
**Describe the bug**
Currently, the Planner General Settings show "AM/PM" by default, although I selected "24h" in the Date & Time plugin. So I have to change it manually to make it match.

**Expected behavior**
Planner should use & suggest time settings that are already set by the system.

But I ask myself: What if for some reason I consciously want to choose a different time format in Planner than in the rest of the system?
However, it seems to me an unlikely use case. Besides, I can already make special settings in the "Language & Region" plugin for such cases.

**Desktop (please complete the following information):**
 - OS or DE: elementary OS 5.1 Hera/Pantheon
 - Version: v2.0.8

**Comment by alainm23** [comment]
Thanks for your comment. I implement this feature to make Planner can be built to other distributions. Planner uses `Granite` and this library depends on several variables that are only available in elementary OS.

**Comment by 4jNsY6fCVqZv** [comment]
So where does Planner currently get/handle the time format (from)? Granite.Services.Settings?

**Comment by 4jNsY6fCVqZv** [comment]
Okay, it's definitely worth a try. I can't wait to see your design for this!

**Comment by alainm23** [comment]
I see that Granite was [updated](https://github.com/elementary/granite/commit/35f8089e803354997064d470fc95150ab704a002). I had this problem with Planner 1. You are right, update this in a future update. Thank you 😃️.

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for taking another look at it!

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 What is the situation with the calendar or time picker right now? There it seems to go along with the system settings.
