### ISSUE TITLE
Consider using a more standard header bar layout

### ISSUE THREAD

**Issue by majjejjam** [alainm23/planify#1451]
**Is your feature request related to a problem? Please describe.**
GNOME apps with a sidebar and search function usually have the title of the app centered, the search button to the left and the main menu to the right:

![Skärmbild från 2024-09-27 13-33-43](https://github.com/user-attachments/assets/40cf96d8-bf1c-4085-b735-86b310c7937e)

![Skärmbild från 2024-09-27 13-33-54](https://github.com/user-attachments/assets/86d842e7-198d-464f-aeb0-e6a271a1b882)

Planify has no title and both buttons aligned to the right. This inconsistency is minor, but I thought changing it to follow other apps would improve usability a bit.

![Skärmbild från 2024-09-27 13-34-03](https://github.com/user-attachments/assets/1abc727d-4786-4049-93f7-0b0eb36be3ac)

**Describe the solution you'd like**
Add the title of the app to the center of the sidebar's header and move search to the left side.

**Comment by golamrabbiazad** [comment]
This will be a consistent header design similar to other app's headers. Great catch btw @majjejjam. Nicely describe the feature request with visuals, thanks for that.

I'm working on this now. PR is coming shortly.

**Comment by oktayacikalin** [comment]
This seems to be fixed now, right?
