### ISSUE TITLE
Make URLs in task description clickable

### ISSUE THREAD

**Issue by CR0CKER** [alainm23/planify#1454]
It currently doesn't seem possible to click URLs in the description/note of a task and open them in the default browser. 

It would be great if URLs would be clickable.

**Comment by alainm23** [comment]
In fact, if possible, but keep the Ctrl key pressed.

**Comment by basicdreams** [comment]
Links actually open if you click on them while holding down the Ctrl key. However, this only works for web links, and if the link contains a protocol other than HTTP/HTTPS, the link will be ignored. My workflow involves using links to Obsidian notes in task descriptions, but unfortunately, Planify ignores the links that start with `obsidian://`. Is there any way to fix this issue? I am happy to provide any additional information or debugging data that could help identify the problem.
