### ISSUE TITLE
Unable to run flatpak. Error message is "Failed to register: Timeout was reached"

### ISSUE THREAD

**Issue by sixcy** [alainm23/planify#1455]
Hello,

Trying to run flatpak:
```
flatpak run io.github.alainm23.planify
```

Results in :
```
Failed to register: Timeout was reached
```

My desktop is:
- OS: ubuntu
- Version 22.04.4 LTS

This happened after installing, using it for a while, then closing the application. After that, I cannot reopen it.

**Comment by sixcy** [comment]
I solved the problem by logging out then logging in again. Now I cannot reproduce it anymore. Is there any logging I could send if the issue happens again?

**Comment by dnsflnv** [comment]
Sometimes I got same messages with random apps on 24.04. On 24.10 nether saw those errors.

**Comment by alainm23** [comment]
Thank you for using Planify, has this bug replicated again? it is probably an isolated issue

**Comment by sixcy** [comment]
No, this has not happened again. Most probably an isolated issue yes

**Comment by montex** [comment]
Hi, I am also getting this message. At some point the app was stuck today, then I closed it and now I cannot open it again. I have tried to logout and even restart the machine, but it does not help. 

Debian 12 and latest version from Flatpak installed today.

```
          ID: io.github.alainm23.planify
         Ref: app/io.github.alainm23.planify/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.11.6
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 35,0 MB
     Runtime: org.gnome.Platform/x86_64/47
         Sdk: org.gnome.Sdk/x86_64/47

      Commit: 609cfc539fe4765000cb67c9d767d7cac76642a4b6218fe67ecda83a413bd6f8
      Parent: 19ef3fd7a1cb5d34bc24e03a7da513bbb092690fddde247db0ccb2f3dde5d89f
     Subject: Update io.github.alainm23.planify.json (4223ca7d)
        Date: 2024-11-05 05:30:23 +0000
```

**Comment by montex** [comment]
Hi,

Not sure if it is related, but today the app is opening, but it is still hanging, and I get the following message in the terminal:

```
** (io.github.alainm23.planify:2): CRITICAL **: 10:48:59.599: objects_item_get_item_type: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 10:48:59.600: objects_item_get_completed: assertion 'self != NULL' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 10:48:59.608: gtk_text_buffer_set_text: assertion 'text != NULL' failed
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers
```
