### ISSUE TITLE
[SOLVED] [Flatpak issue] App fails to launch on Ubuntu 24.10

### ISSUE THREAD

**Issue by foxtbirdy** [alainm23/planify#1463]
**Describe the bug**
Planify fails to launch

**To Reproduce**
1. Install Flatpak
2. Install Planify via Flatpak
3. Run Planify

**Expected behavior**
Successful launch of Planify application from either Dash Dock or Terminal

**Screenshots**
![image](https://github.com/user-attachments/assets/ca5cad7c-82e5-4e7b-a4d5-8f5a3d90fbb6)

**Desktop (please complete the following information):**
 - OS: Ubuntu (No session)
 - VERSION: 24.10 Oracular Oriole

**Additional context**
This application was installed directly from Flatpak. 

## Update
A short fix to this problem is to run the following commands by @comshc 
```
export GSK_RENDERER=ngl
flatpak run io.github.alainm23.planify
```
However this works only if you run it from a terminal. Once the terminal is terminated, the app kills itself. This is very inconvenient. 

## Update [SOLVED]
This issue is related to several other application that runs Flatpak with Wayland. To fix this issue,
1. Create a new file on `~/.config/environment.d/` called `gsk.conf`
2. Add line `GSK_RENDERER=gl`
3. Restart machine
_[Reference](https://discussion.fedoraproject.org/t/gdk-message-error-71-protocol-error-dispatching-to-wayland-display/127927/6)_
_Note that this is tested on **Ubuntu on Xorg** session_

The following fix allows Planify to launch from Dock and terminal.

**Comment by comshc** [comment]
I had this same issue on fedora, for several flatpak apps. The solution I found (I do not recall where) was to set `export GSK_RENDERER=ngl`. No idea what this does, but it worked for me.

**Comment by foxtbirdy** [comment]
Success. Application has started working normally after fresh install.
Unfortunately, it seems that this fix is possible if the application ran from terminal directly,
 `export GSK_RENDEDER=ngl` worked. However, until a maintainer acknowledges the solution, I'll be keeping the issue opened.

**Comment by comshc** [comment]
You can add `export GSK_RENDEDER=ngl` to your `.bash_profile` or `.zprofile` to have it apply automatically on login.

I think this is a problem with flatpak or GNOME, not with planify, though. I've had the same thing happen with GNOME Builder and a few others. I think it affects apps using the gome 47 sdk? I'm not sure.

EDIT: Here are a couple examples of the same bug:
https://github.com/nokyan/resources/issues/368
https://github.com/Jeffser/Alpaca/issues/328
