### ISSUE TITLE
Large mouse cursor in window

### ISSUE THREAD

**Issue by Skilly146** [alainm23/planify#1469]
**Describe the bug**
The mouse cursor gets really big when over the planify window in version 4.11.5 and the app is blurry in general. Version 4.11.4 works as expected

**To Reproduce**
1. Update to version 4.11.5
2. Launch planify

**Expected behavior**
The program is expected to have the same size cursor as every other window and the previous version

**Desktop (please complete the following information):**
 - OS or DE: KDE Wayland on Fedora
 - Version: KDE 6.2.0, fedora 40

**Comment by vhbui02** [comment]
Have you found the solution? I have the same problem

**Comment by Skilly146** [comment]
I actually switched to Fedora Sericea for unrelated reasons shortly after posting this and haven't had a problem since so I don't actually know what went wrong. I would guess that it is a problem with KDE since that is the main thing that changed (maybe something with X but I doubt it) and I have no issue now. You can downgrade to 4.11.4 like I did by finding a guide online, its just a couple commands.

**Comment by vhbui02** [comment]
> You can downgrade to 4.11.4 like I did by finding a guide online, its just a couple commands.

Hmm I have set up a systemd unit file that auto update Flatpak apps every Monday so downgrading isn't going to be viable. Maybe I will try to force it running X11 and apply some resizing cursor tricks I've found.

**Comment by Skilly146** [comment]
You could just add the downgrade command to the unit file until its fixed upstream but that might be too hacky for you

**Comment by vhbui02** [comment]
> You could just add the downgrade command to the unit file until its fixed upstream but that might be too hacky for you

No, I can do it. It's not the first time I've downgraded Flatpak apps. What's hacky is that I have to exclude Planify from my auto update script till a few months later or next version with major/minor change.

**Comment by vhbui02** [comment]
@Skilly146 I've downgraded to version 4.11.2 and it's back to normal. Thank you.

**Comment by Skilly146** [comment]
Does that mean you were still having issues on versions 4.11.4 and 4.11.3? That would be interesting since downgrading to 4.11.4 was enough to solve my issue so yours might be slightly different. I don't think the downgrading reset anything that inadvertantly fixed it since I also reverted to the commit between 4.11.4 and 4.11.5 right before and the issue was still there.

**Comment by vhbui02** [comment]
> Does that mean you were still having issues on versions 4.11.4 and 4.11.3? That would be interesting since downgrading to 4.11.4 was enough to solve my issue so yours might be slightly different. I don't think the downgrading reset anything that inadvertantly fixed it since I also reverted to the commit between 4.11.4 and 4.11.5 right before and the issue was still there.

Ah no, I haven't tried 4.11.4 or 4.11.3. I looked at the timestamp and choose this version since the interval from 4.11.2 to 4.11.3 is a whole month, but the interval between 4.11.3 - 4.11.4 and 4.11.4 - 4.11.5 is just a few days. So 4.11.2 must be decent enough that it can last a whole month. Beside the commit message of 4.11.2 and 4.115 is the same. Idk how to tell you but this version is like the end of a long chain of commits.

**Comment by Skilly146** [comment]
That makes sense, can't be too unstable if it lasted a month. I just stuck with what worked when I did it since I was only on it for a couple days

**Comment by vhbui02** [comment]
@Skilly146 Ah yes I've tackled the auto-updating issue. I've written a cronjob that will unmask Planify Flatpak on December 31 23:59:59 (just before New Year's Eve) to allow auto-updating after that. Hope the author push some new upstream commits soon.

```sh
# crontab -l
...
59 23 31 12 * /usr/bin/flatpak -vu --remove io.github.alainm23.planify
...
```

**Comment by alainm23** [comment]
Sorry, but this is not a Planify issue, and there are already some solutions published by the community. You could try one of those.

https://www.reddit.com/r/gnome/comments/14kxebz/why_does_my_cursor_turn_to_this_in_certain_apps/
