### ISSUE TITLE
Version 2.0.8 badge count not visible on autostart

### ISSUE THREAD

**Issue by WebShapedBiz** [alainm23/planify#147]
First of all, I would like to thank you for your time and effort in developing such a great app.

**Describe the bug**
In General settings, the Planner is set to "Run on startup" and "Run in background".
In Switchboard -> Applications -> Startup there is a Planner entry and it's switched on.
However, upon elementaryOS startup, there is no badge visible. The app needs to be started manually to activate badge count.

**To Reproduce**
See description

**Expected behavior**
Upon OS startup, the badge counter should be visible

**Desktop (please complete the following information):**
 - OS or DE: elementaryOS
 - Version: 5.1

**Comment by alainm23** [comment]
Do you have Planner visible in Plank when the system starts?

**Comment by WebShapedBiz** [comment]
It didn't come to my mind to check it since I'm having Planner pinned on Plank.
Now I see that it's not showing after removing it from the Plank and reboot.

**Comment by alainm23** [comment]
Ok I had to restart my computer about 3 times to verify the error hahaha. Well, basically it happens because Planner doesn't start.

**Comment by alainm23** [comment]
Thank you very much. It was corrected (It is probably necessary to reactivate the option 'Run on startup' in the Planner preferences.). However, it is necessary that Planner be visible in Plank to see the badge count.

**Comment by WebShapedBiz** [comment]
Thank you @alainm23 for your time and effort.
