### ISSUE TITLE
It should be possible to assign due dates also for projects and project periods

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#148]
**Is your feature request related to a problem? Please describe.**
I'm just thinking about professional contexts. When we work in so-called sprints, this has a time frame in which the project is to be worked on and finished. This is also often the case in software development. Currently, I can only define due dates for individual tasks within Planner.

**Describe the solution you'd like**
It should be possible to organize individual projects or project periods in Planner by means of higher-level due dates. Subordinate tasks should of course also be able to be adjusted even more precisely with separate due dates.

**Comment by alainm23** [comment]
Sure. I had already thought about it and I have a super cool design to implement it.
