### ISSUE TITLE
Search popover cannot be closed by pressing ESC, nor by clicking on an area outside the search popover

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#149]
**Describe the bug**
see issue title!

**To Reproduce**
1. Go to 'Inbox'
2. Click on 'Click Find'
3. Enter e.g. 'Getting Started'
4. Select "Getting Started"
5. Hit the "Clear button" -> btw. this one has no tooltip so far
6. Try to close the search popover with ESC. For me not working!

Even if I switch to the Today view afterwards, the popover remains open and does not close.
The step-by-step instructions refer to the error that even the ESC key can no longer close the popover.
Clicking into another window does not work in any case.

**Expected behavior**
In both cases I would expect the popover to close again.

**Desktop (please complete the following information):**
- OS or DE: elementary OS 5.1 Hera/Pantheon
- Version: v2.0.8

**Comment by alainm23** [comment]
Good observation.

**Comment by 4jNsY6fCVqZv** [comment]
While I think ESC should always close a popover, I am not sure if a popover should close immediately when I put the focus on another window (inside or outside Planner). What would make sense for you?
