### ISSUE TITLE
A search displays a single existing task seven times

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#151]
**Describe the bug**
it's already in the issue title.

**Expected behavior**
I would expect to get only one search result, if the searched word / word combination exists in only one place.

**Screenshots**
![Screenshot from 2020-01-22 21 02 21](https://user-images.githubusercontent.com/46536067/72930872-c92df180-3d54-11ea-9bd3-ac81ea8c295b.png)

**Desktop (please complete the following information):**
- OS or DE: elementary OS 5.1 Hera/Pantheon
- Version: v2.0.8

**Comment by alainm23** [comment]
Haha. How many times have you created a tutorial project? I already found the bug. Thank you.

**Comment by 4jNsY6fCVqZv** [comment]
Some ;-)
But seriously: What is the reason?

**Comment by alainm23** [comment]
There is an error in Planner. When I delete a project, I do not delete all the related sections and tasks.

**Comment by 4jNsY6fCVqZv** [comment]
Thank you for the explanation!

**Comment by 4jNsY6fCVqZv** [comment]
Just saw, that I had created a sample task to test the due dates and label and checklist in one task. This task and its list is still displayed in the upcoming view, but it is neither in the inbox nor part of an existing project. And I can even make changes to the task that are immediately applied and even survive a restart of Planner. Same thing?

**Comment by alainm23** [comment]
I think so, I will follow this more deeply.

**Comment by alainm23** [comment]
Fixed in version 2.1
