### ISSUE TITLE
Search results should be more precise

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#153]
**Is your feature request related to a problem? Please describe.**
Right now, when I search for the project "Getting Started", I get a lot of results, including duplicate results that have nothing to do with my search term directly. Unfortunately this makes my search efforts a bit cumbersome. Only when I have already typed in "getting s" Planner finds what I am looking for. Currently, my search term is displayed at the bottom of the result list. I have to scroll down first.

![Screenshot](https://user-images.githubusercontent.com/46536067/72932354-8588b700-3d57-11ea-85c0-5f23c5b42489.png)

**Describe the solution you'd like**
When I specifically search for "Getting Started" as a project, I want my search term - if matching - to appear at the 

Maybe it is a good orientation to see how the application menu in elementary OS builds up its search results?

**Comment by alainm23** [comment]
Definitely the Quick Search has to be improved. There will already be a super update for this. be passive please.

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for working on this! In the meantime, I'll be patient.

**Comment by alainm23** [comment]
I've been working on this. Now the results are more accurate and the match fields are highlighted.

![image](https://user-images.githubusercontent.com/33765137/76156525-9d2ebb80-60c9-11ea-8880-1ab2f40f3b17.png)

**Comment by 4jNsY6fCVqZv** [comment]
Thanks a lot! I am curious to see how this works in everyday practice.

What exactly have you done to improve the quality of the search results?
And (where) do you see room for further/future improvements?

**Comment by alainm23** [comment]
I made some improvements using SQL, now only results matching the search term are displayed.

**Comment by 4jNsY6fCVqZv** [comment]
What happens to searches that contain typos or use words that do not match exactly but are similar?
