### ISSUE TITLE
Header Bar

### ISSUE THREAD

**Issue by ww-9** [alainm23/planify#154]
**Is your feature request related to a problem? Please describe.**
Right now, on non Pantheon desktops current header bar implementation stands out from the overall UX, especially when header bar buttons are shifted to the right. It lacks Minimize, Maximize buttons also.

**Describe the solution you'd like**
To use GTK HeaderBar and follow system settings

**Comment by alainm23** [comment]
I've been working on this yesterday and it's a little difficult to get Planner to follow the default system settings. This is for a few technical details. My solution for this at the moment is to be able to select what kind of decoration layout you want from Planner's preferences.

What do you think?

**Comment by ww-9** [comment]
Thanks for working on it. I think this solution is ok, so everyone will have a choice.
