### ISSUE TITLE
Why does the "Add list" button have a text label while the "Add Task" button has a tooltip?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#155]

**Comment by alainm23** [comment]
What would be your idea to improve it?

**Comment by 4jNsY6fCVqZv** [comment]
What exactly have you changed here in the meantime to close the issue?

My first impulse for an improvement would be that the " Add List " button gets a tooltip as well. Plus keyboard shortcut if available.
