### ISSUE TITLE
If I select the time when adding a new reminder, I cannot add it by pressing ENTER

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#156]
I have to click the "Add" button manually. Deliberately designed this way?
Would expect ENTER to add the reminder.
By the way: When adding a new task it already works like this.
What do you think?

**Comment by 4jNsY6fCVqZv** [comment]
May I ask why you closed it already?

**Comment by alainm23** [comment]
Don't worry, I've already solved it.

**Comment by 4jNsY6fCVqZv** [comment]
Thank you so much!
