### ISSUE TITLE
Headerbar creates some UI problems

### ISSUE THREAD

**Issue by aggalex** [alainm23/planify#158]
**The headerbar created the following UI issues:**
1. The headerbar Gtk.Paned can be pulled too mush to the left. You correctly made the app restore such a change, but it's not addressing the issue by itself.
2. The space to the right of the x button is can be filled with the user's icon, name, and the search and gear icons, which right now are right below.
3. The headerbar cuts scrolling content much too abruptly

**How to fix:**
2 & 1. Add the user's icon, name, and the search and gear icons the left part of the headerbar
3. Make the section's title static (non-scrollable) and add a separator below it. You might also want to show/hide the separator depending on if the scrolling position is 0.

![Screenshot from 2020-01-23 19 26 10 png](https://user-images.githubusercontent.com/11951328/73011583-31480a80-3e1d-11ea-9d4a-a1cb8798f39f.png)

**Desktop (please complete the following information):**
 - OS or DE: elementary OS
 - Version: Hera 5.1

**Comment by alainm23** [comment]
I have ordered the left panel. However, the project view panel will remain the same. This with the intention of gaining space to show more sections or tasks.

![image](https://user-images.githubusercontent.com/33765137/73115576-f2d24e80-3ef5-11ea-90a8-0033e4021bce.png)
