### ISSUE TITLE
Can't login with Todoist username/password

### ISSUE THREAD

**Issue by Jan-Bart** [alainm23/planify#159]
**Describe the bug**
When entering username and password in Todoist Planner hangs.

**To Reproduce**
1. Open Planner
2. Click on the cog-wheel
3. Click on Todoist
4. Fill in username/password
5. Click on login
6. Nothing happens (error is visible in Linux terminal)

**Expected behavior**
I expect Planner to be linked with Todoist after clicking on "login".

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/430206/73063445-16b67580-3e9f-11ea-9200-8ee95ad1e80d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version
Name                                            Application ID                      Version         Branch         Installation
Planner                                         com.github.alainm23.planner         2.0.8           stable         system

**Additional context**
I am using the free version of Todoist.

This is what I see in the Terminal:

```
(com.github.alainm23.planner:2): Gtk-CRITICAL **: 11:38:39.546: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed

(com.github.alainm23.planner:2): Gdk-CRITICAL **: 11:38:39.747: gdk_rgba_parse: assertion 'spec != NULL' failed

(com.github.alainm23.planner:2): Gtk-CRITICAL **: 11:38:41.883: gtk_widget_get_visible: assertion 'GTK_IS_WIDGET (widget)' failed

** (com.github.alainm23.planner:2): CRITICAL **: 11:38:43.350: granite_date_time_get_relative_datetime: assertion 'date_time != NULL' failed
Cannot get default EGL display: EGL_BAD_PARAMETER
Cannot create EGL sharing context: invalid display (last error: EGL_SUCCESS)

(WebKitWebProcess:14): Gdk-ERROR **: 11:38:57.814: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was '179'.
  (Details: serial 197 error_code 179 request_code 155 (unknown) minor_code 21)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(com.github.alainm23.planner:2): Gtk-CRITICAL **: 11:39:25.413: gtk_main_quit: assertion 'main_loops != NULL' failed`
```

**Comment by alainm23** [comment]
Have you installed Planner from Flathub?

**Comment by Jan-Bart** [comment]
Yes, I did.

**Comment by alainm23** [comment]
I had the same problem in elementary OS Hera (Ubuntu 18.04) but I thought I had solved it.

**Comment by alainm23** [comment]
I will keep track of it, thanks for reporting it.

**Comment by yerbestpal** [comment]
I have a very similar situation except that, rather than a blank form after logging in, I am taken to the projects Github page. Is this worth making a separate issue for?

![Screenshot from 2020-06-26 13-47-41](https://user-images.githubusercontent.com/15250241/85858663-ebb8b080-b7b3-11ea-81a5-aed07677a8d7.png)

**Comment by whoisem** [comment]
> I have a very similar situation except that, rather than a blank form after logging in, I am taken to the projects Github page. Is this worth making a separate issue for?
> 
> ![Screenshot from 2020-06-26 13-47-41](https://user-images.githubusercontent.com/15250241/85858663-ebb8b080-b7b3-11ea-81a5-aed07677a8d7.png)

Same issue with me here. Infact I am commenting from the window that opened up inside Planner. 
I installed the rpm version on Fedora 32(2.3.5-1.fc32). Flathub version is 959.5 mb!!

**Comment by theotheroracle** [comment]
yeah, i had the same issue as the github one

**Comment by cameralibre** [comment]
I have the github redirect problem too - I'm also using a free Todoist account. 

Something that might be relevant (?) is that this is the **second** Planner installation that I'm trying to link to the same Todoist account.

Linking/login worked on my laptop, but it does not work on my desktop. Both are running elementaryOS and Planner 2.4.

**Comment by alainm23** [comment]
@cameralibre [Solved](https://github.com/alainm23/planner/issues/424), update to 2.4.4

**Comment by joe733** [comment]
Yep. Solved. 

<p align='center'>
<img src='https://user-images.githubusercontent.com/38415384/87372724-e629db80-c5a5-11ea-8dbf-39eca6d5734f.png' />
</p>

**Comment by BeatLink** [comment]
I guess this issue can be closed now?

**Comment by theotheroracle** [comment]
mhm

**Comment by emk** [comment]
This issue appears to discuss two different bugs:

1. The login hang discussed at https://github.com/alainm23/planner/issues/302 (which still affects Ubuntu 18.04 as of Planner 2.6).
2. A redirect to GitHub which is apparently fixed.
