### ISSUE TITLE
Drag and drop does not work properly

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#161]
- [x] It should be possible to move tasks to any position in a list.
I created a section with three tasks.
When I try to drag and drop task 2 or task 3 to position 1, it doesn't seem possible. 
Moving task 1 to position 2 or 3 is possible without problems.

- [x] It should be possible to move tasks to any section.
It seems that I can only move a task to a section if there is already another task in there. If there is none, I cannot move a newly created task or a task from another section into that section.
Using the context menu, however, moving them works without problems. The issue is probably due to drag and drop.

- [x] It should be possible to move sections to any desired position.
I created a project with three sections.
Section 1 can be moved to the second position, but not to the third position.
Section 2 can be moved to the first position, but not to the third position.
Section 3 can be moved to the first and second position, but not back to the third position after I have moved it once.

- [x] It should be possible to move projects in the sidebar to any position.
Currently, for example, no project can be moved to the first position in the list.

- [x] It should be possible to move areas in the sidebar. At the moment these cannot be moved at all.

- [x] It should be possible to move individual items of a checklist to any position within the checklist.
At the moment, a small cursor hand and a small plus symbol in a green circle appear, which only seems to copy text to another place.

- [x] Labels should also be freely arrangeable in their position.
Currently, I have to remove (sometimes all) labels from a task before I can add them again in the desired order.
**EDIT** I have already seen that there will soon be an improvement for moving labels under Preferences > Labels.
This request, however, refers to the ability to reorganize labels by dragging and dropping them within the view of expanded tasks.

I would expect that all combinations are possible, so that I can really freely arrange the order.

**Comment by alainm23** [comment]
Thanks for the comment. It will be fixed.

**Comment by alainm23** [comment]
4/5 of the described problems were solved.

**Comment by 4jNsY6fCVqZv** [comment]
Wonderful, thank you very much!
Could you imagine ticking off the already solved issues?

**Comment by 4jNsY6fCVqZv** [comment]
Exciting. When I see the last open point, I wonder if there should be a visual separation in the sidebar.

Username
->Seperator
Inbox
Today
Upcoming
->Seperator
Projects
->Seperator
Areas

Free movement would then not be possible at will, but only within a defined category. How do you feel about this idea?

**Comment by 4jNsY6fCVqZv** [comment]
Exciting. When I see the last open point, I wonder if there should be a visual separation in the sidebar.

Username
->Seperator
Inbox
Today
Upcoming
->Seperator
Projects
->Seperator
Areas

Drag and drop would then not be possible randomly, but only within a defined category. How do you feel about this idea? But that's probably an separate issue then, right?

**Comment by alainm23** [comment]
In version 2.1 the project panel was redesigned. A visual separation between action items, projects and areas was added.

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 With the visual separation, do you mean that there is now more space between the action items and the projects/headline? Somehow it also seems as if the space between individual projects and areas has increased and projects belonging to a certain area have moved closer to the area. Is this true?

**Comment by alainm23** [comment]
That's correct.

**Comment by 4jNsY6fCVqZv** [comment]
I like it very much, thanks!
Did you consciously decide against drawing separators?

**Comment by 4jNsY6fCVqZv** [comment]
> It should be possible to move areas in the sidebar. At the moment these cannot be moved at all.

Can that be ticked off too?

**Comment by alainm23** [comment]
Yes, update to 2.3.3

**Comment by 4jNsY6fCVqZv** [comment]
Update Planner via AppCenter always takes quite a while ;)
So there is no release yet. Yesterday I got the update to 2.3.2.
Thanks for your work on improving drag and drop in Planner! I am curious to see version 2.3.3!

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 

> It should be possible to move areas in the sidebar. At the moment these cannot be moved at all.

- [x] Areas are now called folders. Unfortunately I still can't move them in the sidebar by drag and drop. I am now using version 2.3.3 of the AppCenter for Planner. It works for projects.

 > Labels should also be freely arrangeable in their position.
Currently, I have to remove (sometimes all) labels from a task before I can add them again in the desired order.

- [ ] In an expanded task, the labels cannot yet be freely rearranged by drag and drop. Instead, Planner always offers me to move the whole task instead.
Observation: By the way, it looks as if the task disappears from the project view when dragging and dropping, the hand appears and the grey frame around the task seems not to be continuous anymore.

**Comment by 4jNsY6fCVqZv** [comment]
Planner 2.3.5 -> Moving folders works. What do you think about the free arrangement of labels in the **expanded task view**? @alainm23

**Comment by 4jNsY6fCVqZv** [comment]
Another observation concerning drag & drop in the **Upcoming view**: Either allow drag and drop in the Upcoming view or remove it completely. It's kind of in between right now. I can grab the task with my hand and move it across the screen, but I can't paste it into another day.

- [x] I think it would be nice if it would be possible to move the task at this point and then the due date of the moved task would be updated automatically.

**Comment by 4jNsY6fCVqZv** [comment]
- [x] In the **Today view** it is not possible to drag and drop a task. What already works by drag and drop, however, is to move any task from a project via the sidebar into the Today view, thereby assigning it a due date for the current day.

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 Can you please reopen the issue until it is completely resolved?

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 Can you please reopen the issue until it is completely resolved?

**Comment by alainm23** [comment]
> in an expanded task, the labels cannot yet be freely rearranged by drag and drop. Instead, Planner always offers me to move the whole task instead.

I am not sure if it is necessary.

> I think it would be nice if it would be possible to move the task at this point and then the due date of the moved task would be updated automatically.

I've also thought about it, I'll find an elegant way to do it.

> In the Today view it is not possible to drag and drop a task to the first position in the list. Within projects, however, this is possible at any time.

Sure, but I'll take some time to think about how to do it the best way.

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for reopening!

>>  In the Today view it is not possible to drag and drop a task to the first position in the list. Within projects, however, this is possible at any time.

> Sure, but I'll take some time to think about how to do it the best way.

Thank you! Would the implementation have to be different from that in the Inbox view or Project view?

 >>  I think it would be nice if it would be possible to move the task at this point and then the due date of the moved task would be updated automatically.

> I've also thought about it, I'll find an elegant way to do it.

Just got the feeling that there might be a design conflict with https://github.com/alainm23/planner/issues/352 How do you feel about that?

 >>  in an expanded task, the labels cannot yet be freely rearranged by drag and drop. Instead, Planner always offers me to move the whole task instead.

> I am not sure if it is necessary.

I hear you!
Would that be complicated to implement? What would be your argument for implementing it in the form I suggested?

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 I am using Planner 2.4.6 from the AppCenter and it doesn't seem to be possible yet to drag and drop tasks to the first place. Any idea why?
