### ISSUE TITLE
Sidebar, project settings: "Move to area" should be insensitive/greyed out if no areas have been created yet

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#162]
Then this view no longer appears.
![Screenshot](https://user-images.githubusercontent.com/46536067/73126435-58801280-3faa-11ea-9818-f63406305e0b.png)

**Comment by alainm23** [comment]
Thanks for the comment, we are working on this for v2.1.

**Comment by alainm23** [comment]
Fixed in v2.1
