### ISSUE TITLE
Why are there two different locations where different project settings are arranged?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#163]
Does it make sense to simplify it? E.g. to move the functions from the three dots hover menu from the sidebar to the "Options" area in the project view. The sidebar would then simply contain the project name, the location and the number of unsolved tasks. Without an extra settings menu. How do you feel about it?

**Comment by alainm23** [comment]
You're right, I had already thought about this. My solution is to create a dialog to be able to edit the name, color and other project data.

**Comment by 4jNsY6fCVqZv** [comment]
I'm curious! Do you have designs for it yet?

**Comment by alainm23** [comment]
This problem was already solved in v2.1, we added a dialog to edit the project preferences.

**Comment by 4jNsY6fCVqZv** [comment]
I see what has changed and I consider this a very good first step!
I would discuss to go one step further. Because by adding the dialog to a project setting, there are now even three ways.
1.  three dot hover menu (sidebar)
2. context menu (sidebar)
3. options menu (projects view)
My question is whether it is now possible to simply remove the three dot hover menu completely from the sidebar. Or alternatively the context menu, although I think this should always be possible. In any case, there would then only be one way per view to edit a project.Or alternatively the context menu, although I think this should always be possible. In any case, there would then only be one way per view to edit a project.
