### ISSUE TITLE
Application crashes on startup

### ISSUE THREAD

**Issue by sollymay** [alainm23/planify#164]
**Describe the bug**
The application starts up (I can briefly see the interface) and less than a second later, crashes. I have completely uninstalled and reinstalled the app without being able to fix the issue

**To Reproduce**
1. Install the app through AppCenter
2. Try to open app for the first time
3. App crashes
4. Uninstall the app
5. reinstalled the app
6. Try to open app for the first time
7. App crashes

**Expected behavior**
App should open normally

**Desktop (please complete the following information):**
 - OS or DE: Pantheon (Elementery OS Hera)
![Screenshot from 2020-01-25 15-20-40](https://user-images.githubusercontent.com/6496698/73126887-5015e080-3f86-11ea-81a8-ff1cb6421295.png)

**Comment by alainm23** [comment]
I'm so sorry, I'm not sure what happens, you can try this solution:
Delete the database file:
`/home/<user>/.local/share/com.github.alainm23.planner`

**Comment by alainm23** [comment]
Could you solve the problem?

**Comment by sollymay** [comment]
Issue solved by installing flatpak version, uninstalling app center version, uninstalling flatpak and reinstalling app center version. 

Really weird but hey, it worked and now it’s the official version.

**Comment by alainm23** [comment]
Great!!!
