### ISSUE TITLE
The Brazilian Portuguese is not completely done

### ISSUE THREAD

**Issue by gleissonjoaquim3** [alainm23/planify#165]
The translation into Brazilian Portuguese is not completely done (image below). I installed the program for the first time which is excellent, but it could have this improvement in the translation into my language.

Version : Planner 2.0.8

![Captura de tela de 2020-01-25 20-54-49](https://user-images.githubusercontent.com/55757359/73128870-15776c80-3fb5-11ea-9497-245c0ad685c2.png)

**Comment by alainm23** [comment]
I'm sorry, I don't speak Portuguese. However, if you could send a PR to fix it, I would be very grateful.
Check: https://github.com/alainm23/planner/tree/master/po#translating-planner
You should edit this file:
https://github.com/alainm23/planner/blob/master/po/pt.po
or
https://github.com/alainm23/planner/blob/master/po/pt_BR.po

**Comment by gleissonjoaquim3** [comment]
OK ! I'll do it and then send the PR

**Comment by alainm23** [comment]
I will close this problem because this channel is only for bug reports and feature requests.
