### ISSUE TITLE
Error syncing with todoist when syncing is disabled.

### ISSUE THREAD

**Issue by gavr123456789** [alainm23/planify#166]
**Describe the bug**
Error syncing with todoist when syncing is disabled.

**To Reproduce**
1. Somehow get a sync error with code 6.
2. Disable syncing so that you don't click OK every time.
3. The error still appears.

**GIF**
![Peek 2020-01-26 12-44](https://user-images.githubusercontent.com/30507409/73133462-eeaf4980-4039-11ea-80d3-d13814da224f.gif)

**Desktop (please complete the following information):**
 - GNOME 3.34 Arch
 - 2.0.8

**Additional context**
It would also be cool if you have assumptions about error №6 xd

**Comment by alainm23** [comment]
This problem was solved in v2.2
