### ISSUE TITLE
Is there a reason why it is not yet possible to create sub-levels of projects or areas?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#169]
I'm thinking of a way to map much more complex project structures. Or is the idea to solve that via the sections?

**Comment by 4jNsY6fCVqZv** [comment]
I'm thinking of a way to map much more complex project structures. Or is the idea to solve that via the sections?

**Comment by BeatLink** [comment]
I'm gonna close this in favour of the above linked issue. Feel free to give your input there!
