### ISSUE TITLE
It should be possible to create new projects directly within areas

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#170]
Right now I can create projects, but then I have to move them manually into an existing area. Don't know if areas would have to be selectable to achieve this (blue background, as in selected projects).

**Comment by alainm23** [comment]
Now yes.

![image](https://user-images.githubusercontent.com/33765137/74212344-c2164700-4c61-11ea-8dd0-d170e193ca8c.png)

![image](https://user-images.githubusercontent.com/33765137/74212354-cd697280-4c61-11ea-87c2-80bf158920a9.png)

**Comment by 4jNsY6fCVqZv** [comment]
Wonderful, thank you very much!
I am excited to test this improvement and then use it in everyday life.

**Comment by 4jNsY6fCVqZv** [comment]
If I create a project via "Add List" and there are no already created "areas", the selection menu is greyed out/insensitive, right? (Screenshot 2)

**Comment by alainm23** [comment]
Yeah, not really, I'll do it now :).
