### ISSUE TITLE
Position of the button for adding new labels does not seem intuitive to me

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#172]
![screenshot](https://user-images.githubusercontent.com/46536067/73250356-a49ba480-41ae-11ea-8488-1e253848392d.png)
The button for adding new labels should not be in the navigation bar, but where it is when adding a new reminder, for example.

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/73714935-57ed2780-46e0-11ea-8dc8-bf08d30be501.png)

**Comment by 4jNsY6fCVqZv** [comment]
Much better from my perspective! When I think about adding a reminder, what do you think about moving "Add Label" to the bottom?

Btw. I always ask myself that. Applies to the whole app, including tooltips: Should it be called "Add Label" or "Add label"? To make it coherent.

**Comment by alainm23** [comment]
- I'm putting it on top so that the user always has the focus when creating a new Label.
- I'm not sure which one is right haha.

**Comment by 4jNsY6fCVqZv** [comment]
> I'm putting it on top so that the user always has the focus when creating a new Label.

Let's go with it and see what the practical experience feels like!

About the question of spelling: Do you think it makes sense to find out?
