### ISSUE TITLE
When I want to create a new label with ENTER, nothing happens

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#174]
![screenshot](https://user-images.githubusercontent.com/46536067/73251464-ee858a00-41b0-11ea-9392-1808c979e6e9.png)
I would expect the new label to be added to my list then.

**Comment by alainm23** [comment]
It is not necessary to press the RETURN key because the label was already created.

**Comment by 4jNsY6fCVqZv** [comment]
Yeah, but then you keep seeing a blinking cursor, right? What, in your view, would be the logic of how users would recognize a) that the label was created as desired and b) how they should continue from there.

**Comment by 4jNsY6fCVqZv** [comment]
Yeah, but then you keep seeing a blinking cursor, right? What, from your point of view, would be the logic of how users would recognize a) that the label was created as desired and b) anticipate how they should continue/navigate from there.

**Comment by 4jNsY6fCVqZv** [comment]
May I ask why you closed the Issue?

**Comment by alainm23** [comment]
Now you have to press the RETURN key to create a new label.
