### ISSUE TITLE
When I rename a label in the settings, it should be removed from the task the old label was assigned to

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#175]
I'm not sure about that right now. How do you feel about it?

**Comment by alainm23** [comment]
I think the best behavior would be to update the name of the label in all the tasks where it was assigned.

**Comment by 4jNsY6fCVqZv** [comment]
I'm not sure about that.
For example, I have given the label "apple".
After some time of using it, I realize that this is no longer appropriate.
Instead of simply deleting it in the settings, I realize that I need a completely new label for something else at the same time. So I overwrite the old label "apple" with the new label "bicycle". But if I had assigned the old label twenty times, I would have to consider for all tasks individually whether the new label is at all usable for it, whether I don't need a label at all anymore or whether I would have to change the old label slightly.
Since there is currently no tag filter, I would have to search for these tasks individually.

**Comment by alainm23** [comment]
I understand your idea but you are talking about an extreme case where the idea of ​​a label is completely changed.  But what if the user only wants to edit the label due to a misspelling or wants to add more content.  Would it be correct to remove all labels from assigned tasks?

**Comment by yannicka** [comment]
I think it's better to update the name rather than remove the label.

**Comment by alainm23** [comment]
I think the same as you @yannicka.

**Comment by 4jNsY6fCVqZv** [comment]
@yannicka @alainm23 Do you see a reasonable way to solve both use cases together?

**Comment by yannicka** [comment]
If I want to rename the label (e.g. for correction/improvement of the label): I rename it and the associated tasks will use the renamed label.

If I want to delete the label (e.g. when the label is no longer necessary): I delete it and the label is removed from the associated tasks.

**Comment by alainm23** [comment]
I agree with you, I think we shouldn't think so much about this. If the user wants to change his tags completely he can delete them.

**Comment by 4jNsY6fCVqZv** [comment]
Thank you both for taking the time to discuss this point!
