### ISSUE TITLE
Why do the labels in the Task View not primarily use the color I assigned to them when I created the labels?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#176]
Example
#FFF9F4 becomes #FFE5CB
Unfortunately, this means that the label no longer has such a strong signal effect. It looks pale and rather pastel.

**Comment by alainm23** [comment]
I tried to put the same solid color but I did not like the result. That's why I decided to lower the intensity and I think it looks better this way.

**Comment by 4jNsY6fCVqZv** [comment]
What is the current hex value of the font color in Planner? Or especially in the labels, if it differs within the app.

How did you reduce the intensity?

**Comment by alainm23** [comment]
here: https://github.com/alainm23/planner/blob/master/src/Services/LabelsController.vala#L10

**Comment by 4jNsY6fCVqZv** [comment]
Where can I find the hex value of the (label) font color there?

**Comment by alainm23** [comment]
I'm going to close this problem since this is not a bug, it's just a design idea.

**Comment by 4jNsY6fCVqZv** [comment]
When you close the topic, will the discussion about a possibly even better design also be lost?

E.g. Did you check the given set of colors for WCAG contrast compliance with https://appcenter.elementary.io/com.github.danrabbit.harvey.desktop?

**Comment by alainm23** [comment]
Yes, I have an algorithm to find the best contrast.

**Comment by 4jNsY6fCVqZv** [comment]
May I ask what algorithm you use to check this?

**Comment by alainm23** [comment]
Here: https://github.com/alainm23/planner/blob/master/src/Utils.vala#L221
