### ISSUE TITLE
Separation between unsharp label when scrolling and "Edit labels" field should be clearer

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#177]
![screenshot](https://user-images.githubusercontent.com/46536067/73252569-da428c80-41b2-11ea-9b1a-54bbaa792d97.png)

**Comment by alainm23** [comment]
Now?

![image](https://user-images.githubusercontent.com/33765137/74974211-d04b2c80-53f2-11ea-9652-47831b63ac4d.png)

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for your wonderful design! I am curious how it will work in practice.
