### ISSUE TITLE
Window does not scroll to new subtask if subtask list is longer than window height

### ISSUE THREAD

**Issue by Andrewsudarikov** [alainm23/planify#179]
**Describe the bug**
Adding the new line in checklist by pressing ENTER doesn't automatically scroll to the highlighted line, so the user has to use mouse/touchpad to manually scroll down to see what's being typed in the new checklist line. 

**To Reproduce**
1. Create a task in any project.
2. Add as many items in checklist as is enough to fill the app's window. 
3. Add one more task by pressing ENTER.

**Screen Recording**
https://youtu.be/-zVkeKINK8E 

**Expected behavior**
The task list should be automatically scrolled to the new item line. 

**Desktop (please complete the following information):**
 - Elementary OS
 - Version 5.1

**Comment by 4jNsY6fCVqZv** [comment]
Reminds me of the desired behavior for https://github.com/alainm23/planner/issues/173

**Comment by BeatLink** [comment]
Issue is still present on planner 2.6.9

**Comment by alainm23** [comment]
Planner is no longer supported, I will close this issue for the time it has been inactive.
