### ISSUE TITLE
Add the ability to log out of your Todoist account.

### ISSUE THREAD

**Issue by gavr123456789** [alainm23/planify#181]
**Is your feature request related to a problem? Please describe.**
As I already noticed [here](https://github.com/alainm23/planner/issues/166)  I have a problem with Todoist sync. I would like to try logging out of my account and logging in again to see if this fixes the problem.

**Describe the solution you'd like**
Add the logout button here.
![image](https://user-images.githubusercontent.com/30507409/73266795-ac783a80-41e8-11ea-8129-bd8be801c43d.png)

**Additional context**
By the way, I do not know how to clear the memory of the Planner account. When I unistall and install Planner via Flatpak again it still remember my account. Where does Planner store the cache?

**Comment by alainm23** [comment]
Sure 😉️.

The Planner database is located at: `/home/<user>/.local/share/com.github.alainm23.planner/`

**Comment by gavr123456789** [comment]
@alainm23 amm, no, there no com.github.... folder 
```shell
~/.l/share ❯❯❯ ls
applications/         geary/                  gtk-doc/        minder/             Trash/
Celeste/              gegl-0.4/               gvfs-metadata/  nautilus/           vlc/
code-d/               gitg/                   icc/            recently-used.xbel  vulkan/
desktop-directories/  gnome-builder/          icons/          sounds/             webkitgtk/
evolution/            gnome-settings-daemon/  keyrings/       Steam/              wine_games/
fish/                 gnome-shell/            lutris/         TelegramDesktop/
flatpak/              grilo-plugins/          MetaPkg/        totem/
folks/                gsettings-data-convert  mime/           tracker/
```

**Comment by alainm23** [comment]
I think that Flatpak is different, try here: 
`/home/<user>/.var/app/com.github.alainm23.planner/data/com.github.alainm23.planner/`

**Comment by gavr123456789** [comment]
yes, u right, ty.

**Comment by gavr123456789** [comment]
![image](https://user-images.githubusercontent.com/30507409/73289040-0e4a9b80-420d-11ea-8391-84012bb2f894.png)
And now I understand why I can't sync with todoist, somehow flatpak can't find the network?
But before it worked!
