### ISSUE TITLE
Animation for deletion, instead of the normal trash button

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#182]
I love this fine animation when deleting a list item.
My idea: To use this animation - besides the context menu item - everywhere for deleting within the app. For tasks, sections, projects or areas.
Because currently I have to open a task before I can press the trashcan button. The right click menu seems to be almost faster. The animation not only looks nicer, but also simplifies the usability of the app. Of course, it is always important to offer an immediate undo. No matter what I want to delete.
How do you feel about this?

**Comment by alainm23** [comment]
I believe that deleting a project or section requires a confirmation message why the information being deleted is very important.

**Comment by 4jNsY6fCVqZv** [comment]
Makes sense. And how do you see this for individual tasks?
Couldn't the message also appear when I call up the animation?

**Comment by alainm23** [comment]
But deleting a project, section or task is already available from the context menu. Just right click on it.

**Comment by 4jNsY6fCVqZv** [comment]
Maybe I used some confusing language?

My idea was to remove this trash button.
![Screenshot](https://user-images.githubusercontent.com/46536067/73456750-592df580-436a-11ea-90f1-2f4bad53b760.png)

And instead, insert the animation for deletion (-> little rolling X icon) next to each task/project/area. Just as this already exists for the items in the checklist.
![Screenshot ](https://user-images.githubusercontent.com/46536067/73456900-a316db80-436a-11ea-8b04-99005f38268c.png)
My question was whether the possibility of an undo can be triggered by such a deletion animation.

The ability to delete a task via the context menu should of course also be available.

**Comment by 4jNsY6fCVqZv** [comment]
In addition, I also wonder why the three dots menu is still needed in this view. This is identical with the context menu, isn't it?

**Comment by alainm23** [comment]
I'm not sure about implementing a rolling button to remove a task. If you want to delete a task quickly you can do it from the context menu.

**Comment by 4jNsY6fCVqZv** [comment]
What makes you unsure about the idea of the rolling buttons for deleting tasks?

What else do you think about a keyboard shortcut to delete tasks?

**Comment by alainm23** [comment]
I would like the task view to be clean and minimalist, if you want to delete a task quickly use the context menu.
