### ISSUE TITLE
Why are there two ways to access the task settings?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#183]
The right-click context menu is available in most apps.
What I still don't understand, however, is why I should first open a task and then use a three-point menu to achieve the same effect as the context menu itself. This seems to me a bit awkwardly solved. What made you decide to design it that way?

Perhaps still in this context: due dates, reminders and labels are also only possible via the additional way of opening the note element. But what if I don't want to write any notes at all? Then these options are more difficult to access.

**Comment by alainm23** [comment]
The way to visualize a color was improved in Planner 2.3, what do you think?
![image](https://user-images.githubusercontent.com/33765137/79679685-a5503f80-81cd-11ea-8503-3f898be80ac3.png)

**Comment by 4jNsY6fCVqZv** [comment]
Were you gonna post that in another issue? ;-)

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/80043609-ce234e00-84c7-11ea-8c75-66c3fe6d6810.png)

**Comment by 4jNsY6fCVqZv** [comment]
What exactly did you change in the behaviour? Unfortunately, I cannot see that from your screenshot right now.

And what do you say to the second part of my thoughts?

> Perhaps still in this context: due dates, reminders and labels are also only possible via the additional way of opening the note element. But what if I don't want to write any notes at all? Then these options are more difficult to access.

**Comment by 4jNsY6fCVqZv** [comment]
What exactly did you change in Planners behaviour here? Unfortunately, I cannot see that from your screenshot right now.
