### ISSUE TITLE
The app is way too sexy looking.

### ISSUE THREAD

**Issue by Philip-Scott** [alainm23/planify#185]
**Describe the "bug"**

This app is way too good looking, you need to tone it down! Between the animations, the colors, and even the default getting started, just look at this: 
![image](https://user-images.githubusercontent.com/10786508/73419915-b2981500-42d5-11ea-8880-05df9ac97496.png)

10/10, only rice could make it better! 

But seriously man, I had to give you props for making the app. One of the hardest things about being an app developer is when you always hear about the bugs and the issues, so I wanted to let you know about your great work here :)

---------------

PS: I'm totally stealing these labels! :smile:  
![image](https://user-images.githubusercontent.com/10786508/73419787-46b5ac80-42d5-11ea-8d5b-bd9a60fff398.png)

**Comment by alainm23** [comment]
Thank you for your comments. You really made me smile. I'm a Latino like you, too. And it's very satisfying that you like my work.

**Comment by gfavaro** [comment]
I have to agree. This is really awesome!

**Comment by Philip-Scott** [comment]
Hermano Latino!!! I'm glad to know that it made you smile :) Keep up the great work man, and let me know if you ever need anything!

**Comment by alainm23** [comment]
Thank you very much. I'll keep that in mind. I'm going to close this issue because I don't think anyone can solve it 😅.
