### ISSUE TITLE
Crazy selection bar appears

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#187]
![Screenshot](https://user-images.githubusercontent.com/46536067/73447211-2974f280-4356-11ea-873a-f27e9feb90bb.png)

Neither opening and closing the task nor switching to another project or e.g. Today view in the meantime removes this selection. What works is to close Planner and start it again.

**EDIT**: It seems as if there is a connection with drag and drop. At least I can reproduce it by trying to move the only task in this project back and forth for a while.

**Comment by Andrewsudarikov** [comment]
I confirm this bug. Same thing happened to me.

**Comment by alainm23** [comment]
I can't reproduce the error in v2.1.

**Comment by Andrewsudarikov** [comment]
Yes, the bug is gone in 2.1.1

**Comment by 4jNsY6fCVqZv** [comment]
Just managed to reproduce the issue again with the same task in 2.1.1 I'm testing it again.
@alainm23 Did you make any changes that might have solved the problem?

**Comment by 4jNsY6fCVqZv** [comment]
see https://github.com/alainm23/planner/issues/187#issuecomment-580817194
Did you change anything after that? I was still able to reproduce the issue with version  2.1.1.

**Comment by 4jNsY6fCVqZv** [comment]
see https://github.com/alainm23/planner/issues/187#issuecomment-580817194
Did you change anything after that? I was still able to reproduce the issue with version  2.1.1. I think it only occurred in connection with drag and drop actions.

**Comment by alainm23** [comment]
Yes, I rewrote the code for v2.3, the update is in review.

**Comment by 4jNsY6fCVqZv** [comment]
Would you briefly explain what caused the problem and how you solved it?
