### ISSUE TITLE
Moving a task from one project to another project within the same area gives me a Todoist error

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#192]
![Screenshot](https://user-images.githubusercontent.com/46536067/73559351-c5812580-444c-11ea-9bfa-705a1eae927c.png)

Background information: I don't have a Todoist account and therefore this service is not activated. I use Planner v2.1.1 locally.

Another observation I made while testing this error. Something similar to https://github.com/alainm23/planner/issues/187 occurs. Just in the sidebar.
The only difference: The blue selection marker does not disappear even after a restart of Planner. It seems that this always happens when drag and drop is in action.
Here are two random versions:

![Screenshot](https://user-images.githubusercontent.com/46536067/73560294-95d31d00-444e-11ea-853b-5367a6d93465.png)

![Screenshot](https://user-images.githubusercontent.com/46536067/73560908-d2ebdf00-444f-11ea-9d04-136427d20ef1.png)

**EDIT**: After numerous app restarts and even a system reboot, the blue selection markers have all disappeared. Still a bug?

**Comment by zedtux** [comment]
I actually have the same error when moving a task from Inbox to a project. I'm not using todoist.

I believe the app doesn't check if a todoist account is connected, but tries anyway to update tasks which fails with a 403 error.

**Comment by igalic** [comment]
The same error occurs when renaming a project.

**Comment by 4jNsY6fCVqZv** [comment]
I can no longer reproduce the original issue with AppCenter version 2.2.14.
Regarding my observation of the blue selection markers: For this I would create a separate issue if the observation occurs again.

**Comment by 4jNsY6fCVqZv** [comment]
I can no longer reproduce the original issue with AppCenter version 2.2.14.
Also renaming projects no longer gives an error code.
Regarding my observation of the blue selection markers: For this I would create a separate issue if the observation occurs again.
