### ISSUE TITLE
After I have deleted the example project via the sidebar, the view changes to the Welcome Screen

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#195]
The funny thing is, I have several projects and areas left, which are still all shown in the sidebar. I would expect the next project or homepage to be displayed, but not the welcome screen again. I use the AppCenter version 2.1.1.

**EDIT**: A restart of the app shows my self chosen homepage again.
The issue can be reproduced at will. Simply generate a new example project in the settings, delete it via the sidebar and the view switches back to the welcome screen.
Even if I create two sample projects and delete one of them, the welcome screen appears immediately. I would expect it to only appear if there are no areas, projects and tasks left.

**Comment by alainm23** [comment]
I don't what happened, I can't reproduce  the bug .

**Comment by 4jNsY6fCVqZv** [comment]
...if you follow my description?

**Comment by 4jNsY6fCVqZv** [comment]
Can you try to follow my steps and make a small screencast about how it looks like for you?

**Comment by alainm23** [comment]
I thought about it and programmed it this way. If you delete a project that is selected, Planner automatically sends you to the Inbox.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33765137/73949194-16b76c00-48c8-11ea-89f9-f0b69918ddc6.gif)

**Comment by 4jNsY6fCVqZv** [comment]
Crazy, I'm no longer able to reproduce the error with the same Planner version.
I'll keep an eye on it ;)

**Comment by alainm23** [comment]
Ha ha, it happens.
