### ISSUE TITLE
When I try to change project colors from the sidebar, a Todoist error appears

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#198]
![Screenshot](https://user-images.githubusercontent.com/46536067/73590862-8e0f8900-44df-11ea-91c8-211086f81cc7.png)

Unfortunately reproducible at will. I use the AppCenter version 2.1.1, but only locally. Todoist is not activated in the settings.

**Comment by yannicka** [comment]
I've the same error since 2.1.

**Comment by 4jNsY6fCVqZv** [comment]
**EDIT** The error also occurs when simply renaming any project via the sidebar.

**Comment by williamd1k0** [comment]
This bug appears to have been fixed in version 2.2.
I had this bug in 2.1, but now I can't reproduce it anymore.

**Comment by alainm23** [comment]
Please confirm if you can reproduce the bug in v2.2

**Comment by 4jNsY6fCVqZv** [comment]
Can no longer reproduce it. AppCenter version 2.2.14.
