### ISSUE TITLE
[Feature request] Multiline tasks in projects and checklists

### ISSUE THREAD

**Issue by Andrewsudarikov** [alainm23/planify#200]
**Describe the solution you'd like**
If the text in task description is longer than can fit in one line, make the task multiline so that the end of the description doesn't get obscured by the window edge.

**Comment by alainm23** [comment]
You are right, this way there will be more space to add more indicators (comment, checklist, etc.)

**Comment by alainm23** [comment]
## What do you think?

![image](https://user-images.githubusercontent.com/33765137/73855272-d5f51f80-4801-11ea-90ef-bb0fc711538c.png)

**Comment by Andrewsudarikov** [comment]
Wow! I think it is absolutely fantastic!

**Comment by alainm23** [comment]
I had to redesign the whole task view. This way you can gain more space to display more information (deadlines, reminders, tags) And best of all, Planner will be able to work with a smaller screen.

**Comment by Andrewsudarikov** [comment]
This is a huge achievement! Thank you very much for the effort!

**Comment by 4jNsY6fCVqZv** [comment]
Looking at your screenshot, I wonder if it would make sense if the "Add task" button always keeps its position in the lower right corner and it doesn't look like it's going to overlay the text of the tasks while scrolling through them?
