### ISSUE TITLE
The options to show/hide completed tasks use the same icon

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#204]
Perhaps a solution that makes the difference clear not only on a linguistic level would be exciting.
See for example how elementary Files solves this for "Show Hidden FIles" and "Hide Local Thumbnails". Just an idea. There are certainly many nice solutions.
How do you feel about this?

**Comment by alainm23** [comment]
I'll keep that in mind, thank you very much.

**Comment by alainm23** [comment]
I'm now using a Gtk.Switch.

![image](https://user-images.githubusercontent.com/33765137/74157753-d2d5a700-4be6-11ea-93b2-9ad0ab6042e2.png)

**Comment by 4jNsY6fCVqZv** [comment]
You think that fits with HIG? I have not yet had much experience with that myself.
https://elementary.io/docs/human-interface-guidelines#switches

**Comment by alainm23** [comment]
I think it would work very well. Task uses it too.

![image](https://user-images.githubusercontent.com/33765137/74174185-8186e100-4c01-11ea-9baa-a7438f944f1c.png)

**Comment by 4jNsY6fCVqZv** [comment]
Do you know if this is the final Task Design for this feature? 

They solve this without the symbolic check icon. Just the switch. Would that be practicable for Planner as well?

**Comment by 4jNsY6fCVqZv** [comment]
I also wonder, shouldn't the "Delete" option always be at the bottom of the context menu? At least I would find it helpful if this is coherently solved in Planner.

**Comment by 4jNsY6fCVqZv** [comment]
I also wonder, shouldn't the "Delete" option always be at the bottom of the context menu?
At least I would find it helpful if this is coherently solved in Planner.
How do you feel about this?

**Comment by alainm23** [comment]
Sure. 

![image](https://user-images.githubusercontent.com/33765137/74375503-6dccad80-4dae-11ea-875c-8c1b8ba501fb.png)

**Comment by 4jNsY6fCVqZv** [comment]
Why did you consciously choose the symbolic icons? Tasks solves this purely on the text level.

**Comment by alainm23** [comment]
I'd like to leave it with an icon to keep the same menu design idea.
