### ISSUE TITLE
When I search for a task in Quick find, it should be possible that a click on the result not only puts the focus on the appropriate project, but also on the task itself

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#205]
Currently, for example, I have a project with about twenty tasks. If the task search then focuses on the project, it might still take a long time until I can focus on the appropriate task.
Do you have any idea how to solve this?

**Comment by alainm23** [comment]
How about a flashing indicator on the task when it is selected from Quick Find? I implemented this solution in Planner 1, it will not be difficult to implement it in Planner 2.

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for your feedback!
What did it look like in Planner 1? Would you mind to share a short screencast of it?
And what made you decide not to implement this for Planner 2 so far?

**Comment by alainm23** [comment]
Something like that.

![item-highli](https://user-images.githubusercontent.com/33765137/76156502-504ae500-60c9-11ea-8dab-3b199bac8559.gif)

**Comment by alainm23** [comment]
I've been working on this. Now the results are more accurate and the match fields are highlighted.

![image](https://user-images.githubusercontent.com/33765137/76156525-9d2ebb80-60c9-11ea-8880-1ab2f40f3b17.png)

**Comment by 4jNsY6fCVqZv** [comment]
I like your idea!
Does this also work for checklist items? Or sections?
Although I'm not sure if sections need a flash as well.
After all, there may be so many sections within a project that I would have to scroll or it may be difficult to spot the right section immediately. How do you feel about this?

**Comment by alainm23** [comment]
Still not working for the sub-tasks. And the sections were not included, although it's a good idea.

**Comment by 4jNsY6fCVqZv** [comment]
Do you want to look at both again?
