### ISSUE TITLE
Quick find should be more visually integrated into the app

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#206]
![Screenshot](https://user-images.githubusercontent.com/46536067/73973273-2c558180-491a-11ea-9900-d105cdccc603.png)

Right now, the search button and the pop-up search window look visually rather disconnected. Unfortunately I can't describe it any other way at the moment.

**Comment by alainm23** [comment]
I understand what you're thinking. I feel the same way. Quick Find definitely needs a redesign, making it more in line with Planner's design. It's in my plans and thanks for reminding me.

**Comment by alainm23** [comment]
What do you think?

![image](https://user-images.githubusercontent.com/33765137/74158192-a1a9a680-4be7-11ea-8990-d6b0f3197c72.png)

**Comment by 4jNsY6fCVqZv** [comment]
Exciting, many thanks for your design!
Your design refers to the search window and displaying the search results, right?
p.s. What does "Pages" mean here?

**Comment by alainm23** [comment]
Pages will show for example: "Inbox", "Today", "Upcoming", etc

**Comment by 4jNsY6fCVqZv** [comment]
How will you integrate the search design into the entire app window?
How will it be connected to the search button, for example?
Or does your design already show the complete app window?

I wonder if "Pages" is that accurate. It's about different "Views", isn't it?
But just calling it "Views" would also be weird in this case. Maybe just call it Inbox, Today, Upcoming instead of a generic category?

Will it be possible to filter by labels? Or will the search have filters at all?

**Comment by alainm23** [comment]
1. It will be launched as a Dialogue in the same style as the preferences.
2. The search button will trigger this dialogue.
3. You're right, the term "Views" would be more correct.
4. My idea is that, yes, being able to filter the tasks by labels.

**Comment by 4jNsY6fCVqZv** [comment]
> It will be launched as a Dialogue in the same style as the preferences.
The search button will trigger this dialogue.

1. I still don't quite understand how this solution creates a connection between the search and the overall app? At the moment it is already the case that an extra window opens when I click on the search button.
2. Which is something I've also been wondering about in this context: When I look at Plank, it looks like a second instance of Planner opens when I open the preferences menu. Why is that?

**Comment by alainm23** [comment]
Quick Find redesigned.

![image](https://user-images.githubusercontent.com/33765137/75820174-df729880-5d69-11ea-8f07-9c5842acbc6a.png)

**Comment by 4jNsY6fCVqZv** [comment]
Pages/Views and filtering by labels is not yet implemented in this design, right?

For me, this design solution also remains an unconnected, separate window. 
What are the advantages?
What does the view look like when the new search window opens centered?
Could you imagine to alternatively develop a design that embeds the search in the existing window UI?
How does elementary tasks/other project management apps solve the search functionality?
Is there any advice from the elementary UI/UX team?

**Comment by 4jNsY6fCVqZv** [comment]
Just ask myself about the projects and the assignment of colors to the projects: So far, the color assignment has in my perception still a rather small identification character with the corresponding projects, because the colored outer ring in the sidebar is quite small.

What do you think about the idea of not showing the progress of the project as a circle in the search, but simply showing a circle there that is completely filled with the color of the project? I have a feeling that the search won't be the place where I want to keep track of the progress of a project. 

I am thinking of the Upcoming View, where this is similarly solved.

What do others think?

**Comment by 4jNsY6fCVqZv** [comment]
About the location of the search window: What does it look like when the search window opens in a similar way to the preferences window, centered and in the middle?

**Comment by alainm23** [comment]
Centered looks a little weird. I don't like it.

![image](https://user-images.githubusercontent.com/33765137/76163506-a8f39f80-6114-11ea-8083-91f6839d0504.png)

**Comment by alainm23** [comment]
> Just ask myself about the projects and the assignment of colors to the projects: So far, the color assignment has in my perception still a rather small identification character with the corresponding projects, because the colored outer ring in the sidebar is quite small.
> 
> What do you think about the idea of not showing the progress of the project as a circle in the search, but simply showing a circle there that is completely filled with the color of the project? I have a feeling that the search won't be the place where I want to keep track of the progress of a project.
> 
> I am thinking of the Upcoming View, where this is similarly solved.
> 
> What do others think?

Perhaps you could open a new issue for this and then debate it.

**Comment by 4jNsY6fCVqZv** [comment]
> Centered looks a little weird. I don't like it.

I thought of centered because it would be more consistent with opening the preferences window.
Do you have any alternative design ideas that go completely away from what we have so far?
