### ISSUE TITLE
All Task view

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#21]
**Is your feature request related to a problem? Please describe.**
I want to quickly view all my tasks. I currently have plenty of projects and checking project by project is a bit too overwhelming.

**Describe the solution you'd like**
Add an "All Task" view on the sidebar, similar to inbox or Today

**Describe alternatives you've considered**
Checking projects one by one
**Additional context**

**Comment by alainm23** [comment]
Good point, I have it in mind for the next release.

**Comment by alainm23** [comment]
I am adding an option in the preferences to make this item visible.

**Comment by alainm23** [comment]
@Hedronmx This function is in the implemented in the new version but not entirely, I currently have a problem with my computer which does not allow me to update my 'schema' configuration, for the moment you can use this solution, I hope to fix my computer.

![all tasks](https://user-images.githubusercontent.com/33765137/51395067-ead51700-1b09-11e9-8a06-d56a47e4bae7.png)
![alltasks 2](https://user-images.githubusercontent.com/33765137/51395068-ead51700-1b09-11e9-908c-16c936d5abcc.png)

**Comment by Hedronmx** [comment]
This but for planner v2

**Comment by 73** [comment]
I want that too. Can this be reopened for v2?

**Comment by 73** [comment]
@alainm23 would you mind to reopen this?

**Comment by alainm23** [comment]
Sure friends, I'll work on that for the next version.

**Comment by 73** [comment]
I would love to have a view that just stacks all project views below each other. that would be awesome.

**Comment by 73** [comment]
Hi @alainm23,

why is this issue closed? Is this not happening anymore? 

Thanks,
--73

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/100279881-558ce000-2f35-11eb-9d90-0bd88c271b46.png)

**Comment by 73** [comment]
Nice! Thanks. I found it. I did not notice the change in the application because there is no signifier.

**Comment by alainm23** [comment]
Sorry, sometimes I forget to post what I do.

**Comment by 73** [comment]
No problem. I asked, you answered. Thank you for the view!

**Comment by Toxblh** [comment]
@alainm23 Can I pin the filter to the left panel? Or only reachable via search?

**Comment by alainm23** [comment]
@Toxblh I plan to show it on the panel as a customization option.

**Comment by Toxblh** [comment]
Cool, thank you. I will wait :)
