### ISSUE TITLE
fix Travis again

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#210]

**Comment by alainm23** [comment]
This is an AppCenter error, there's nothing I can do to fix it.

**Comment by 4jNsY6fCVqZv** [comment]
Are the AppCenter developers working on a solution or are they aware that this error exists?

**Comment by alainm23** [comment]
Here: https://github.com/elementary/houston/issues/773

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for the hint!
Then it will soon solve itself as if by magic ;)
