### ISSUE TITLE
Error in badge count

### ISSUE THREAD

**Issue by nandgator** [alainm23/planify#214]
**Describe the bug**
[Bug Type: Bitesize] The badge count is not displayed, when the option for Today+Inbox is selected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Settings'
2. Click on 'Badge count'
3. Check ✅ 'Today + Inbox' option
4. Badge count disappears

**Expected behaviour**
Correct badge count is displayed.

**Screenshot**
![Screenshot from 2020-02-11 08-01-43](https://user-images.githubusercontent.com/38415384/74207584-3b378d80-4ca6-11ea-84ee-fc8ba54f1711.png)

**Desktop:**
 - Elementary OS
 - Version 5.1

**Additional info**
From the screenshot *improper* strike-through rendering is also visible.

**Comment by alainm23** [comment]
I'm not sure what's wrong, I can't reproduce the bug.

**Comment by nandgator** [comment]
Was and update pushed recently? If not  there's a glitch, apparently badge is working now.
Can you create an `overdue` side-tab?
![Screenshot from 2020-02-12 08-18-38](https://user-images.githubusercontent.com/38415384/74299125-bb76f500-4d71-11ea-885c-5e1c029f322b.png)
The version: 
![Screenshot from 2020-02-12 08-19-57](https://user-images.githubusercontent.com/38415384/74299150-ce89c500-4d71-11ea-99f8-d497d27e436b.png)
The `Task-Completed` section is not being rendered properly. 
![Screenshot from 2020-02-12 08-37-39](https://user-images.githubusercontent.com/38415384/74299548-047b7900-4d73-11ea-8db7-ee6b05ebc94a.png)

**Comment by alainm23** [comment]
In v2.2 we are adding a color indicator when the task is overdue.

**Comment by nandgator** [comment]
This GIF shows it clearly (open it in a new tab):
![badge](https://i.stack.imgur.com/a6v6m.gif)

**Comment by alainm23** [comment]
I just released an update (v2.2.13) could you do the same test and see if it was corrected please?

**Comment by nandgator** [comment]
![Screenshot from 2020-03-03 18-55-48](https://user-images.githubusercontent.com/38415384/75780078-c88b7080-5d80-11ea-93c0-050fe8f884d7.png)
![Screenshot from 2020-03-03 18-52-57](https://user-images.githubusercontent.com/38415384/75780132-d7722300-5d80-11ea-8a74-d797dc760930.png)
Seems like its not yet on eOS repos. I'll do so when I get an update.

**Comment by nandgator** [comment]
Thanks guys!
Fixed in version [2.2.13](https://github.com/alainm23/planner/releases/tag/2.2.13).
