### ISSUE TITLE
The last expanded task should receive the focus

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#215]
Right now the focus seems to disappear completely.

**Scenario**
1. Create two test tasks A and B.
2. Expand both.
3. Use ESC to close B.
4. A gets no focus, so it cannot be closed with ESC either, so that at least one task always remains open.

I would expect that I could use ESC to close all previously opened tasks.
What do you say, does the request make sense?

**Comment by alainm23** [comment]
In order to solve this, I have an idea. Every time a task is opened (see detail) I will store the task reference in a list and so on every time a task is opened. Then to close the tasks I have to press the ESC key. Then the tasks will be closed according to the order in which they were opened. So if I open task 1 and then task 2 if I press the ESC key then task 2 will be closed first and then task 1. What do you think?

**Comment by 4jNsY6fCVqZv** [comment]
That's worth a try! 
Do you see any disadvantages of your solution?
Or do you have any ideas for alternative solutions?

I ask myself: What happens to the focus then? 
Normally, when I open a task I have the focus directly on the title, which I can change immediately.
To stick with our example and your solution: If I close B/task2 with ESC, can I change the title directly at A/task1 because the focus automatically jumps there again?

**Comment by alainm23** [comment]
I just implemented this feature, but using the ESC key to close all tasks is giving me conflicts with many of the elements in the interface that also use this key, what solution could we use?

**Comment by alainm23** [comment]
I'm giving the focus to the task at hand. For example if I open task 1 and then task 2, when I press the ESC key I close task 1 and task 2 gets the focus for editing.

**Comment by 4jNsY6fCVqZv** [comment]
Could you imagine to share a short video, how the possible behavior would look like with your example?

**Comment by 4jNsY6fCVqZv** [comment]
> I just implemented this feature, but using the ESC key to close all tasks is giving me conflicts with many of the elements in the interface that also use this key, what solution could we use?

With which interface elements does my idea actually conflict?

> I'm giving the focus to the task at hand. For example if I open task 1 and then task 2, when I press the ESC key I close task 1 and task 2 gets the focus for editing.

Actually, you haven't implemented that yet, have you?

**Comment by alainm23** [comment]
1. If I have an open task and the edition of a project or section there is a conflict because both things are closed with the ESC key.

2. It's implemented but with the commented code.

**Comment by 4jNsY6fCVqZv** [comment]
1. Could you imagine that only one task, section or project can be open for editing at a time?
**EDIT** I am wondering. And I may not have fully understood it yet. The focus in editing can only be in one place at a time, right? And where the current focus is, ESC should be possible to close it.
2. What do you mean "but with the commented code"? It is commented out in the code so far and therefore not yet active?

**Comment by BeatLink** [comment]
There are two ways to solve this:

1. Create a list that keeps track of the order in which tasks receive focus. Closing a task would remove it from the list, and thus transfer focus to the last focused task. Adding a task would add it to the focus list and would give it focus. So when tasks are closed, they would be closed in the order that they received focus.

2. Closing a task would simply transfer focus to the closest open task above it in the project list. So for example, if there are 3 tasks from A to C and all are open and Task C is the current focused task, pressing escape would close task C and shift the focus to task B. This would result in more consistent behaviour, and would be easier to implement from a codebase standpoint. Hence i prefer option 2.
