### ISSUE TITLE
Why is the delete button in the context menu red while it is black in the view of an expanded task?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#216]

**Comment by alainm23** [comment]
It's just a matter of alert.

**Comment by 4jNsY6fCVqZv** [comment]
I see, then why not in all views?

![Screenshot](https://user-images.githubusercontent.com/46536067/74420496-715e4400-4e43-11ea-84b3-efe2594c96d7.png)

**Comment by alainm23** [comment]
I have improved the design a little bit for this, now when you pass the mouse over the delete button, it turns red, indicating a warning.

![image](https://user-images.githubusercontent.com/33765137/75106444-b96f2a80-55ea-11ea-958c-8732694fd0ba.png)

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for your design!
Do your changes apply to all delete buttons within Planner?
