### ISSUE TITLE
make keyboard shortcuts easier to discover

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#217]
elementary OS has this wonderful milestone to make keyboard shortcuts easier to discover.

https://github.com/orgs/elementary/projects?utf8=%E2%9C%93&query=keyboard

Do you have the feeling that this would also be a useful and feasible feature for Planner?

**Comment by alainm23** [comment]
Of course.

**Comment by alainm23** [comment]
I'm adding these tooltips with their respective keyboard shortcuts.

![image](https://user-images.githubusercontent.com/33765137/74745901-92070f00-5232-11ea-97a0-0cb5952145f5.png)

**Comment by 4jNsY6fCVqZv** [comment]
Nice! This way it is also implemented in the native elementary apps, right?
There are no shortcuts for actions in the context menus yet?

**Comment by alainm23** [comment]
I think this problem has been solved, I'll be adding more keyboard shortcuts over time.

**Comment by 4jNsY6fCVqZv** [comment]
Thanks a lot!
