### ISSUE TITLE
Color palettes should be sorted by gradient

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#222]
From my point of view this makes it easier to find the desired color.
Concerns creating a new project and editing the labels.

**Comment by alainm23** [comment]
What should be the correct order according to you? I base it on the same order that Todoist uses.

**Comment by 4jNsY6fCVqZv** [comment]
Good question!
My idea goes in the direction of...
https://elementary.io/brand
or https://en.wikipedia.org/wiki/Color_wheel

**Comment by 4jNsY6fCVqZv** [comment]
Good question!
I am irritated especially by the colors 15, 16 and 17.
The colors 1-14 are more like a color wheel.
https://en.wikipedia.org/wiki/Color_wheel
Unfortunately, these do not have a smooth gradient. There are always very strong and very weak colors alternating.
But there is no room for the colors 18-20 on such a wheel.
At least at https://elementary.io/brand I find the transitions and the gradations within the individual colors quite well solved. But the last four color blocks are attached to the back as well.
See https://github.com/alainm23/planner/issues/109#issuecomment-571062100 for it's use in Planner. Looks a bit complicated, no idea if this is what we need.

**Comment by alainm23** [comment]
The way to visualize a color was improved in Planner 2.3, what do you think?

![image](https://user-images.githubusercontent.com/33765137/79679685-a5503f80-81cd-11ea-8503-3f898be80ac3.png)

**Comment by 4jNsY6fCVqZv** [comment]
Just wondering where in Planner do I see that. In the project creation? If so, I find a scroll list much more complicated and confusing. And unfortunately I don't know what the advantage is of being able to read the written out names. Isn't a tooltip enough?
Please explain to me, what is your idea behind this change? I am curious!

p.s. Did you see that elementary has added bubblegum and mint to its color palette?
And what do you think about including the complete color palette?
https://elementary.io/brand

**Comment by alainm23** [comment]
Using elementary OS colors.

## Before

![image](https://user-images.githubusercontent.com/33765137/80271192-995bf600-8683-11ea-8e77-8034b44559e6.png)

## After
![image](https://user-images.githubusercontent.com/33765137/80271218-cdcfb200-8683-11ea-9217-f06a97d555b7.png)

I can't see much difference.

**Comment by 4jNsY6fCVqZv** [comment]
Just landed in the master repository.
https://github.com/elementary/stylesheet/commits/master

**Comment by alainm23** [comment]
I will close this issue for being only a question and not a problem in itself.
