### ISSUE TITLE
Why is the view called "Inbox", what is its function within Planner?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#226]
Unfortunately, the meaning is still not quite clear to me why this view is needed in Planner at all. This is not an inbox in the classical sense, like in an email program, is it? Therefore the name seems a little confusing to me.
More like a list with individual tasks that cannot or not yet be assigned to projects.

**Comment by alainm23** [comment]
Check it:
https://get.todoist.help/hc/en-us/articles/360000538849-What-s-the-difference-between-the-Inbox-and-a-project-
