### ISSUE TITLE
Crush on DND

### ISSUE THREAD

**Issue by gavr123456789** [alainm23/planify#227]
**Describe the bug**
Crash when I drag a list item to the end, before creating a new todo.

**To Reproduce**
1. Start creating todo, but dont press add button
2. DND any todo one point higher then edit
3. Get Crush ^^

**Expected behavior**
No crush

**GIF**
![Peek 2020-02-15 00-05](https://user-images.githubusercontent.com/30507409/74567592-382eec80-4f87-11ea-9fbf-579b143326a2.gif)

**Desktop (please complete the following information):**
 - GNOME Arch btw
 - Planner from AUR

**Comment by 4jNsY6fCVqZv** [comment]
I can reproduce this at will. Version is Planner 2.1.1.
**EDIT** from AppCenter.
