### ISSUE TITLE
Labels preview on Task

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#23]
**Describe the solution you'd like**
Change the color of the tag icon so we can tell what label that task has.

**Describe alternatives you've considered**
Opening the task to find out what label it has

**Comment by ghost** [comment]
Hmm, I was a bit surprised to see that you labelled this issue as low priority. I hope you get to work on this soon. I will be nice to just look at all your tasks and know which label they have on them just like how Github shows you all the labels on your issues

**Comment by alainm23** [comment]
I will work on this feature tonight.

**Comment by alainm23** [comment]
What do you think?
![image](https://user-images.githubusercontent.com/33765137/51707577-9b05bc80-1fef-11e9-9b48-19989d5888c6.png)

**Comment by Hedronmx** [comment]
Looks good!

**Comment by alainm23** [comment]
I hope you like it.

![labels](https://user-images.githubusercontent.com/33765137/51761914-508e4980-209c-11e9-98c3-3fbd99fc28ae.png)
