### ISSUE TITLE
Window doesn't remember size correctly on HiDPI display

### ISSUE THREAD

**Issue by sgpthomas** [alainm23/planify#230]
**Describe the bug**
Every time I open Planner the window size grows. 

**To Reproduce**
1. Open Planner
2. Close Planner
3. Open Planner

**Expected behavior**
I expect either a default window size or Planner to remember it's window size. 

**Desktop (please complete the following information):**
 - OS or DE: Gnome 3.34.3 on Fedora 31
 - Planner v2.08

**Additional context**
I'm using a HiDPI display on a laptop.

**Comment by alainm23** [comment]
Thank you for reporting this bug. This was already corrected for v2.2 #150
