### ISSUE TITLE
Make the overview window for the keyboard shortcuts more appealing

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#231]
Proposal from elementary OS
![Screenshot](https://user-images.githubusercontent.com/46536067/74760663-a8cd5600-5272-11ea-98f7-b09973f935b2.png)

**Comment by 4jNsY6fCVqZv** [comment]
This is how Akira will solve this https://twitter.com/akiraux/status/1236199524890099712

**Comment by alainm23** [comment]
A design is in process.
![image](https://user-images.githubusercontent.com/33765137/85093706-9d535280-b1b2-11ea-8c07-a3b9a3aea094.png)

**Comment by 4jNsY6fCVqZv** [comment]
Which foreground and background colors are used in this design?

**Comment by alainm23** [comment]
The same colors in the project view and rgba(48,51,54,.85) for key;

**Comment by 4jNsY6fCVqZv** [comment]
So the background is rgb(48,51,54) and the value of the white text in the foreground? What exactly do you mean, .85?

**Comment by alainm23** [comment]
rgba(red, green, blue, alpha)

**Comment by 4jNsY6fCVqZv** [comment]
Can you please answer the first part of the question and then give me the hexadecimal values for both colors?

**Comment by 4jNsY6fCVqZv** [comment]
Did you deliberately choose such a strong contrast? And does it need a light and a dark variation?
