### ISSUE TITLE
Joplin

### ISSUE THREAD

**Issue by juansquintero** [alainm23/planify#232]
**The best app i've ever seen on the AppCenter**
Is there any to sync to Joplin or their solution on Onedrive or similar

**Comment by alainm23** [comment]
Thanks for using Planner.
At the moment we have no plans to add another synchronization method for Planner, but that could change in the future.
I'm going to close this issue because it's a question.

**Comment by 3v1n0** [comment]
> At the moment we have no plans to add another synchronization method for Planner

Did this changed? 😄

Or well, an android version of Planify would be also appreciated, given gtk supports it now.
