### ISSUE TITLE
Error when creating project on Todoist with special characters in its name.

### ISSUE THREAD

**Issue by wout** [alainm23/planify#234]
**Describe the bug**
Creating a project with special characters in its name on Todoist results in an error. 

**To Reproduce**
1. Click on Add List
2. Enter a name with an &
3. Select Todoist

**Expected behavior**
Should create the project as it does work for local projects.

**Screenshots**
![image](https://user-images.githubusercontent.com/107324/74862302-d1715080-5343-11ea-9851-3718ad03fbb0.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/107324/74862346-e4842080-5343-11ea-8ea8-d02150c7eff0.png)

**Comment by igalic** [comment]
>  Creating a project with special characters in its name on Todoist results in an error.

what exactly is the error?

**Comment by wout** [comment]
You can see the error in the screenshot.

**Comment by alainm23** [comment]
Similar to #186

**Comment by alainm23** [comment]
Solved
![image](https://user-images.githubusercontent.com/33765137/93161378-0ece6e80-f6d8-11ea-938b-d9b08359fe3d.png)
