### ISSUE TITLE
Move local project into cloud

### ISSUE THREAD

**Issue by igalic** [alainm23/planify#236]
**Is your feature request related to a problem? Please describe.**
I created a couple of areas and project inside those.
Then i decided you know what? I should dust off my todoist account, so i can obsess over this on my phone too!

Alas, local projects are local.
There's no move or copy of function, and the cloud / no-cloud icon is just that.
The edit button only allows to edit the name and colour — not whether the project is local or remote (as the create function allows)

**Describe the solution you'd like**
Extend the Edit function to analogue to the create function, allowing to move a project into the cloud, or, out of it.

**Describe alternatives you've considered**
A toggle in the Context Menu, analogue to the [Move to Area] function.

**Comment by nandgator** [comment]
> **Describe the solution you'd like**
> Extend the Edit function to analogue to the create function, allowing to move a project into the cloud, or, out of it.
> 
> **Describe alternatives you've considered**
> A toggle in the Context Menu, analogue to the [Move to Area] function.

It would be good to see some kind of `export` tasks function which exports it into `.csv` or something.

**Comment by alainm23** [comment]
@igalic Sure, this won't be so hard. Todoist provides an API to make this very easy.

**Comment by alainm23** [comment]
@joe733 In Planner 2.2 we can export our projects as Markdown and mail. Why do you want to export your project as .csv?

**Comment by nandgator** [comment]
> @joe733 In Planner 2.2 we can export our projects as Markdown and mail. Why do you want to export your project as .csv?

Okay, sorry I didn't notice... I'll test them then. Thanks.

**Comment by ni-ka** [comment]
Really missing this too, I think adding the same cloud / local switcher to the project edit page would be the cleanest UI wise.

**Comment by nandgator** [comment]
Here's my suggestion from #457

>The cloud icon which shows up next to a project (upon mouse hover) can be used. When the user hits it that particular project synchronization is toggled - switched on and off.

Which means it overrides the global sync. I don't know how to code it in Vala, but that's just a suggestion :)

**Comment by alainm23** [comment]
Available in v2.5
