### ISSUE TITLE
Ability to "postpopne" or "push" your schedule.

### ISSUE THREAD

**Issue by Schykle** [alainm23/planify#237]
Sometimes things just can't be done on schedule. Unplanned family events, illnesses, or just needing a break from things. Sometimes you just need to push everything forward a day or two.

An ability to "push" or "postpone" your schedule would be greatly appreciated. I apologize if this does exist and I've missed it. But a button to move forward your whole task list any particular amount of time or days could come in handy when dealing with illnesses or even burnout.

**Comment by alainm23** [comment]
Thank you for your comment, let me understand it better. Do you want there to be an option to reschedule all the tasks of a project? for example: If I have 2 tasks that are due tomorrow, with this option I can make these tasks reschedule for example in 2 days.

**Comment by Schykle** [comment]
Yeah, that's exactly what I was thinking. So if a task from a project is due tomorrow, it gets changed to the day after tomorrow, and the other tasks get pushed forward as well. So something on Friday becomes due on Saturday and something on Saturday gets pushed to Sunday. (Sorry if I'm explaining this poorly.)

**Comment by alainm23** [comment]
If I understand you, don't worry. This feature sounds like 'Sorted 3 App' to me but I like it. Thank you very much for your suggestion, I will keep it in mind for a future release.

**Comment by Schykle** [comment]
Much appreciated, thanks for your time and thanks for this awesome app!

**Comment by BeatLink** [comment]
This feature now exists in the latest versions of planner. Overdue tasks will show on the Today page in its own "Overdue" section. This section has a "Reschedule" button that when clicked, allows you to select which date in the future to reschedule all tasks to.

Closing the issue
