### ISSUE TITLE
Font size to small, and no way to increase it

### ISSUE THREAD

**Issue by igalic** [alainm23/planify#238]
**Describe the bug**
The font sizes for Tasks and sections are too small for my old, tired eyes.
I'm not sure what the font sizes are derived from, it certainly isn't from my desktop settings

I'm running Elementary OS, and have "Text Size" set to "Larger"
find, attached a screenshot of my Browser with Planner in the foreground, to see the contrast in sizing.

**To Reproduce**
1. Grow old, or otherwise gain poor eyesight.
2. Start planner
3. Create a task
4. Squint to see the task

**Expected behavior**
I would like planner to follow my desktop's suggested font sizes, or else offer me a chance to set them myself.

**Screenshots**
![Planner in the foreground (with tiny fonts) Firefox in the background, with this very page.](https://user-images.githubusercontent.com/497249/74987080-ae759800-543a-11ea-8969-2738e989de49.png)

**Desktop (please complete the following information):**
 - OS or DE: Elementary OS Hera; Pantheon
 - n.b.: my laptop has an HiDPI screen.

**Comment by alainm23** [comment]
Thanks for reporting this little bug. I stopped using the custom font sizes to use the default ones in elementary, I think this will solve the problem.

**Comment by alainm23** [comment]
I would like to know if this issue was resolved in v2.2.14.

**Comment by igalic** [comment]
i believe so.

**Comment by yeboahnanaosei** [comment]
Well, I'm using 2.2.14 and I must say that this problem still persists. I was about to file  a new issue when I searched and found this one. 

The font sizes are too small from the rest of the operating system.

![Screenshot from 2020-04-17 18-13-08](https://user-images.githubusercontent.com/22800157/79600751-2ed11600-80d7-11ea-9634-7e98f43e9958.png)


![Screenshot from 2020-04-17 18-11-03](https://user-images.githubusercontent.com/22800157/79600773-385a7e00-80d7-11ea-8abd-95bec62d85c1.png)
