### ISSUE TITLE
Crash with task drag and drop

### ISSUE THREAD

**Issue by PhilippeMorere** [alainm23/planify#239]
Dragging a task to the top (to make it the first task in a project) causes the app to crash.

**To Reproduce**
1. Create a few tasks in a project (eg. 3 or 4).
2. Drag and drop the last task on top of (a bit higher) the first task, don't release mouse button.
3. Crash!

Version 2.0.8

**Comment by alainm23** [comment]
Thank you very much for commenting. I made some drag and drop changes for v2.2 and I can't reproduce this bug.
