### ISSUE TITLE
Choose date for reminder

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#24]
**Is your feature request related to a problem? Please describe.**
I can't choose a date on the reminders, that means I can't get reminded to do my homework before the deadline.

**Describe the solution you'd like**
Choose a date and time for the reminder

**Describe alternatives you've considered**
Setting the deadline to a day or two before the actual deadline.

**Comment by alainm23** [comment]
I hope that with this new design I can improve a bit the UX.
![reminder 1](https://user-images.githubusercontent.com/33765137/51081132-961f3f80-16b6-11e9-8726-b7b084f4812c.png)
![reminder 2](https://user-images.githubusercontent.com/33765137/51081131-961f3f80-16b6-11e9-9cf3-5c51e2ea258a.png)

I'm thinking about adding a configuration in the preferences to assign how many minutes or hours before Planner has to notify you to finish a task.

**Thoughts?**

**Comment by Hedronmx** [comment]
That is good :heart:
