### ISSUE TITLE
Add Notes support to Sections

### ISSUE THREAD

**Issue by williamd1k0** [alainm23/planify#241]
**Is your feature request related to a problem? Please describe.**
I want to add notes not only in Projects and Tasks, but also in Sections.

**Describe the solution you'd like**
Add Notes support to Sections.

**Describe alternatives you've considered**
As a workaround, I'm adding a dummy task just to add notes, but it's not as good as it could be.

**Comment by alainm23** [comment]
This is a good idea. I think of this as a section menu item (Add note). But this feature will arrive for the next version, I'm about to release v2.2.

**Comment by BeatLink** [comment]
By next version do you mean Version 3?

**Comment by alainm23** [comment]
@BeatLink  I think we are still very far from v3 there are still many things to polish and features that I would like to add.

**Comment by BeatLink** [comment]
Ohh okay but this feature would be included in it right?

**Comment by alainm23** [comment]
This feature is currently available, check it out.

**Comment by BeatLink** [comment]
You mean in 2.3.5? I cant seem to find it :(

**Comment by BeatLink** [comment]
Ohhh I found it! Thanks!
