### ISSUE TITLE
Add FOSS multiuser and sharing feature

### ISSUE THREAD

**Issue by ovz93br43v7** [alainm23/planify#242]
**Is your feature request related to a problem? Please describe.**
At the moment I use Google Notes to store, share (this works on Google via gmail addresses) and edit notes. For example, we have several shopping lists which are shared and where everyone can add something to when they notice that something is used up at home.
I'm trying to replace every Google service with FOSS solutions but for Google Notes there is no good FOSS alternative on the market.

**Describe the solution you'd like**
Please add a feature for multi-user sharing and editing of notes. (replacement or additionally to todoist)

**Describe alternatives you've considered**
I tried all available FOSS notes apps as replacement of Google Notes, but nothing worked.

**Comment by alainm23** [comment]
Thank you very much for commenting. For v2.2 I'm adding the option to share your projects, sections and tasks by mail, markdown or text.
