### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by sbstn87** [alainm23/planify#244]
Hi guys,

are there any chances for a Windows version?

**Comment by gwutz** [comment]
I looked into crosscompile Planner for mingw64/windows but some dependency are hard to resolve. libgee, ecal, ical are all problematic.

**Comment by alainm23** [comment]
I'm sorry, this won't be possible. Planner uses some libraries and components that are only available on Linux and trying to solve the dependencies would be very complicated.
