### ISSUE TITLE
Show Completed does not work

### ISSUE THREAD

**Issue by DanyGee** [alainm23/planify#248]
**Describe the bug**
The **Show Completed** switch does not work.

**To Reproduce**
1. Mark some task as completed
2. Go to 3 dots menu
3. Switch "Show Completed"
4. Observe completed task not showing

**Expected behavior**
Completed task should show up.

**Screenshots**
![Screen record from 2020-02-25 18 07 30@2x](https://user-images.githubusercontent.com/26818551/75270300-9e730500-57fa-11ea-8fce-96f81975783d.gif)

**Desktop (please complete the following information):**
 - OS or DE: [eOS Hera]
 - Version [2.2]

**Comment by alainm23** [comment]
It seems that AppCenter is not distributing the latest version of Planner (2.2.6). I'm sending an update to fix this.

**Comment by alainm23** [comment]
Please upgrade to v2.2.8 and try again.

**Comment by DanyGee** [comment]
Fixed in 2.2.8 :tada: 
Thx! :clap:
