### ISSUE TITLE
Moving Task to other Projects crashes Planner sometimes.

### ISSUE THREAD

**Issue by alihammad-gist** [alainm23/planify#249]
**Describe the bug**
Moving Task to other Projects crashes the program.

**To Reproduce**
1. Create a Task in Inbox.
2. Add Today as a Due Date to the Task.
3. Move the Task to a Project

**Expected behavior**
Task is moved to the Project.

**Screenshots**
Program crashes sorry.

**Desktop (please complete the following information):**
 - Installed Planner (v. 2.2.2) from Flat hub, 
 - GNOME (v. 3.34.4) Desktop on Arch Linux.

**Additional context**
The Task is moved to the Project but Planner crashes **sometimes**.

**Comment by alainm23** [comment]
I'm trying to reproduce the bug but I can't.

**Comment by alainm23** [comment]
Did you reproduce the bug in v2.2.14?

**Comment by alihammad-gist** [comment]
Yes, the bug still exists in version 2.2.14. I used flatpak to install planner.

![planner](https://user-images.githubusercontent.com/3153718/76207587-e1cc6b00-621f-11ea-8a70-a01f5f1517aa.gif)

**Comment by alihammad-gist** [comment]
I keep getting this error in terminal repeatedly.
```
(com.github.alainm23.planner:2): Gtk-CRITICAL **: 16:12:31.783: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

```

And before exiting Planner produces the following error in the terminal.

```
(com.github.alainm23.planner:2): Gtk-CRITICAL **: 16:13:16.165: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:2): GLib-CRITICAL **: 16:13:16.179: Source ID 17052 was not found when attempting to remove it

(com.github.alainm23.planner:2): GLib-GObject-WARNING **: 16:13:16.185: invalid cast from 'WidgetsNewItem' to 'WidgetsItemRow'
```

**Comment by alainm23** [comment]
Great. Thanks for taking the time to send a gif.
