### ISSUE TITLE
Feature Request: todo.txt support

### ISSUE THREAD

**Issue by jtrees** [alainm23/planify#251]
[todo.txt](http://todotxt.org/) is a standardized file format for todo and project tracking. If planner adds support, it will improve inter-operability and reduce the "vendor-lock-in" effect.

For me personally, it is the killer feature I'm waiting for before switching to this app.

**Comment by keponk** [comment]
+1 on this feature. Currently using GoForIt for interoperability since I work with diff OSs and need apps that follow the same standard.

**Comment by hwille** [comment]
+1 - this would be a very nice addition

**Comment by alainm23** [comment]
I like the idea. Although I'm not sure how I can integrate this feature into Planner.

**Comment by gavr123456789** [comment]
@alainm23 what do you mean?  
GNOME todo has experimental support for that.  
You can check how it was implemented there.

**Comment by 12people** [comment]
@alainm23 It's really just about saving the todo list to a txt file with a certain structure -- that's all. And it allows for custom attributes, so you should be able to save everything from Planner into that text file.

The big advantage of using todo.txt is that it allows easy syncing across platforms. For example, I can use the same todo file on Android using any todo app that supports todo.txt, sync that file using my sync service of choice (e.g. Nextcloud), and then be able to access that same todo list in Planner.

**Comment by endorama** [comment]
Stepping in here, as I think this would be a very powerful addition. @alainm23 I would be willing to give it a try, but I think I need some guidance on how the plugin system works.

(I would also love to be able to pull tasks from other tools, like Jira 😅, so this may be a nice first step).

Before diving into this though, I'd like to understand the scope. Should this be a plugin implementing a "new" storage medium for tasks? How this is supposed to work related to the current storage Planner has?

**Comment by alainm23** [comment]
Thanks to the plugins available in Planner 2.6 this will be possible but for the moment I will concentrate on CalDav support, I hope to be able to work on this sometime in 2021

**Comment by BeatLink** [comment]
@alainm23 should i close this in favour of #623 and track progress there?

**Comment by alainm23** [comment]
There are no plans to develop this feature at the moment.
