### ISSUE TITLE
[Feature request] Treat subtasks as regular tasks feature-wise

### ISSUE THREAD

**Issue by niktss** [alainm23/planify#255]
**Is your feature request related to a problem? Please describe.**
Subtasks are just checkbox items on regular tasks - I can't use advanced features on them, such as due dates, reminders, notes, labels/priority, other subtasks. If they are treated as regular tasks, I can have granularity in my schedule, e.g. I can schedule a "major task", assign it priority, and then split it into subtasks that I then further schedule, prioritise, take notes on, etc.

**Describe the solution you'd like**
Just add all the options that regular tasks have to subtasks.

**Describe alternatives you've considered**
I get that it has to be easy and slick, but regular tasks already have these features hidden by default, requiring a click to reveal. You can hide these features like that again, just like in regular tasks, or change the default behaviour for both to "reveal on hover" - either solves the issue of slickness vs. functionality.

**Additional context**
I don't want to involve shame into this, but even GNOME which is terrified of being useful has subtasks of subtasks of subtasks of subtasks.

**Comment by BeatLink** [comment]
Closing this in favour of the above mentioned issue. Feel free to head over there and give your input
