### ISSUE TITLE
Reminder sticks even aftert task is marked as complete.

### ISSUE THREAD

**Issue by nandgator** [alainm23/planify#261]
**The bug**
Reminder rings even after task is marked as complete.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new task
2. Set a reminder (say... for the next two days)
3. Mark the task complete.
4. Notification still reminds. 

**Expected behaviour**
No notification after the task is marked complete, even if the reminder is set to a latter date.

**Screenshots**
![Screenshot from 2020-02-28 19-36-21](https://user-images.githubusercontent.com/38415384/75555553-7685da80-5a62-11ea-8aed-fa27d6a19b87.png)

**Info**
- OS: Elementary OS & Pantheon DE
- System Version: 5.1.2 Hera
- Planner Version: 2.2.8

**Suggestion**
I'm not a `vala` programmer but I guess that the reminder is tightly bound to the calendar.

Maybe by <s>deleting</s> moving the reminder entry from the calendar to a task-attribute-frame (a simple optimized location to store the properties of the task) can solve the issue.

**Comment by 4jNsY6fCVqZv** [comment]
I can reproduce it.
Even tried restarting Planner before the reminder notification appears. In case there's anything left in the cache that triggers the reminder. Nevertheless.

In connection with the sticky notification, this issue seems to be exciting as well.
https://github.com/elementary/notifications/issues/220

**Comment by alainm23** [comment]
That's a good point. Thank you very much for reporting it.

**Comment by alainm23** [comment]
To solve this, it is only necessary to validate that the task is not completed. If it is, we do not send the notification.

**Comment by nandgator** [comment]
May I add one more thing...
The `Show Completed` switch does not toggle back automatically. (I'm not sure if this can be reproduced...) Gets stuck... sometimes... (see the screenshot)
![Screenshot from 2020-02-28 20-33-43](https://user-images.githubusercontent.com/38415384/75560104-98835b00-5a6a-11ea-93e7-1da758e7eb70.jpg)

**Edit**: Yes reproducible, after we check ✅ and un-check a task.

**Comment by nandgator** [comment]
> That's a good point. Thank you very much for reporting it.

My pleasure.

> To solve this, it is only necessary to validate that the task is not completed. If it is, we do not send the notification.

Okay.
