### ISSUE TITLE
Crtl-tab add task does not work if you didn't setup local/todoist storage

### ISSUE THREAD

**Issue by megatux** [alainm23/planify#262]
**Describe the bug**
Installed new app version. Saw Ctrl-tab feature so closed main window and tried to add items but it failed without any UI feedback. I realized it was because didn't select storage. After that, it worked.
I guess, it should advise the user of this issue so he/she can continue with setup.

**Comment by alainm23** [comment]
Did you install Planner from AppCenter or Flathub?

**Comment by megatux** [comment]
@alainm23 oh, right, apt upgrade

**Comment by alainm23** [comment]
Sorry for not paying attention to your issue (I've been very busy these days). I can confirm the problem. It will be solved. Thank you very much :)

**Comment by alainm23** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/33765137/76164234-4520a500-611b-11ea-91e8-7eaa24821b1d.png)
