### ISSUE TITLE
Quick Add does not work if assigned to Super-key combination

### ISSUE THREAD

**Issue by cleac** [alainm23/planify#263]
**Description**
After the recent update, I've found out about quick add feature, which is awesome. But after I reassigned it from `Control+Tab` to `Super+P` or any other combination with Super key (it's the one mostly with Windows logo on it) with a combination that uses Control, it works back.

Other user-defined shortcuts work with the Super key, There is an issue only with Planner (tested with Ideogram - there was no issue).

This issue might be not much of a priority - just wanted to inform you about an issue.

**Steps to reproduce**

1. Install Planner 2.2.8
2. Try using Quick Add feature - it works
3. Go to Settings -> Keyboard -> Key combinations -> Other (the lowest entry in the list) (names might be not precise, I have different localization from English of system)
4. Change shortcut of `com.github.alainm23.planner-quick-add` to Super+P
5. Try using Quick Add - does not work
6. Change shortcut of `com.github.alainm23.planner-quick-add` to Ctrl+P
7. Try using Quick Add - now it works

**Expected behavior**

Well, it would be great if there was ability to specify combinations that use "Super" key as well. 

**Screenshots**

**Desktop:**
 - OS: elementaryOS 5.1.2 Hera
 - Planner 2.2.8

**Comment by alainm23** [comment]
This is a little weird. I'll try to find out what's going on. Thank you for your comment.

**Comment by KGMIT** [comment]
Are there any updates on this? 

I'm on elementary OS 5.1.3 Hera, and Planner 2.3.5, from AppCenter (not Flatpak).

Previous to this update, I was unable to enter any Super key as a the Quick Add combo from the App settings of Planner. Now I am able to, however there is a deterioration in the behavior of my now new combo of `Super+N` from the original `Ctrl+Tab`.

It is a minor one I would say, but here is what happens:

With original Ctrl+Tab combo (or other Ctrl+some other key combos), when you press the second time without having typed anything, the quick add nicely disappears.

With the changed Meta+N quick add shortcut, new quick adds are spawned on top of each other.

I would love to help debug this but I am still not very knowledgeable in Vala or GTK, but am happy to enter some chat-room or sth to help further debug this :)

**Comment by alainm23** [comment]
@KGMIT You talk about this:

![image](https://user-images.githubusercontent.com/33765137/80808553-6cc54400-8b85-11ea-9de7-f30aa2ce18e1.png)

**Comment by cleac** [comment]
Issue I've originally posted does not reproduce any more. Thanks for fixing an issue :grin:
