### ISSUE TITLE
The "Show Completed" switch does not jump back automatically

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#264]
The issue is already described here, but for me it fits better into a separate issue.
https://github.com/alainm23/planner/issues/261#issuecomment-592555936

After I have marked the task as not completed again, it looks like this to me:
![Screenshot](https://user-images.githubusercontent.com/46536067/75605914-4892ab80-5adf-11ea-8d55-39cd675812aa.png)

**Comment by nandgator** [comment]
I'd better add explanation & screenshot here, to make it clear...
> The `Show Completed` switch does not toggle back automatically. Gets stuck... sometimes..
Reproducible, if we check and un-check a task.

![Screenshot](https://user-images.githubusercontent.com/38415384/75560104-98835b00-5a6a-11ea-93e7-1da758e7eb70.jpg)

**Comment by alainm23** [comment]
@joe733 Yes please. I'm trying to replicate that behavior, but I can't.

**Comment by 4jNsY6fCVqZv** [comment]
By the way, in my case the switch looks insensitive for both themes. Planner version 2.2.8 from the AppCenter.

![Screenshot](https://user-images.githubusercontent.com/46536067/75778808-6155c800-5d50-11ea-8870-c8c8f57adf3b.png)
