### ISSUE TITLE
Should the Upcoming view use the entire window length?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#265]
Right now there is about a quarter of white space in the two weeks overview. If the entire window length could be used in full screen, the individual days would not look so clinched.
What do you others think?

![Screenshot](https://user-images.githubusercontent.com/46536067/75606185-26e6f380-5ae2-11ea-99cc-06a732e0e0ce.png)

**Comment by Hedronmx** [comment]
I usually just want to see the next 3 days... So I guess no

**Comment by alainm23** [comment]
I totally agree with you. We need a new design for this.

**Comment by 4jNsY6fCVqZv** [comment]
**EDIT** I have noticed that the white space is only there when there are no tasks scheduled. If at least several tasks are scheduled, the entire window length is used.
Perhaps it is possible to balance the view in such a way that in both cases no larger white spaces are created?

**Comment by alainm23** [comment]
I've improved the space between each day, I think it looks better now.

**Comment by 4jNsY6fCVqZv** [comment]
Do you have a screenshot or screencast that you would like to share?

**Comment by alainm23** [comment]
Yes.

![image](https://user-images.githubusercontent.com/33765137/79384810-2c32bd00-7f2d-11ea-80d4-567a2e9fa84c.png)

**Comment by 4jNsY6fCVqZv** [comment]
Thank you, what does the view look like when there are no tasks pending?

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/79391536-5ab59580-7f37-11ea-9d22-15f7f10c2a23.png)

**Comment by 4jNsY6fCVqZv** [comment]
Oh, to be more precise:
With no tasks and no active calendar.

**Comment by alainm23** [comment]
I think this has been solved.
