### ISSUE TITLE
CTRL + Tab override all application shortcut

### ISSUE THREAD

**Issue by Hydrog3n** [alainm23/planify#266]
**Describe the bug**
In Chrome, for example, I use a lot ctrl + tab for changing tabs but now is showing the new task panel and can't find where change this shortcut

**To Reproduce**
Launch planner in background task go on chrome open multiple tab and trie to navigate with the ctl+tab

**Desktop (please complete the following information):**
 - Elementary 5.1.2
 - Planner 2.2.8

**Comment by roypen** [comment]
You can change quick add shortcut in:

Planner -> Settings -> Quick Add -> Keyboard Shortcuts

**Comment by alainm23** [comment]
@roypen  has the answer :).

**Comment by Hydrog3n** [comment]
Hello, I search at this menu but there's no shortcut ctrl + shift + tab
![image](https://user-images.githubusercontent.com/1223893/75689655-d1594500-5ca1-11ea-85dc-1600466c7383.png)

**Comment by Hydrog3n** [comment]
Oh ! I didn't see before! Thank you sorry for the disturbance

**Comment by surendrajat** [comment]
@alainm23 I changed the shortcut but upon restart, it adds the same shortcut back to Ctrl+Tab.
