### ISSUE TITLE
Black borders around windows and dialog boxes

### ISSUE THREAD

**Issue by bfsgr** [alainm23/planify#268]
**Describe the bug**
When running the app under i3wm/Compton there's big black borders all around the window. The issue seems to be related with i3wm since disabling compton has no effect.

**To Reproduce**
1. Open the app while using i3wm

**Expected behavior**
Not to have these borders

**Screenshots**
![plannerBug](https://user-images.githubusercontent.com/38868063/75727411-ab449c80-5cc3-11ea-97cc-17886a866950.png)

**Desktop**
 - Fedora 31
 - i3wm 4.18

**Additional context**
I tried to fix this by adding 
````css
.window-frame {
     box-shadow: none;
     margin: 0
}
````
to `~/.config/gtk-3.0/gtk.css` but it didn't work.
If I open the app with GTK_DEBUG=interactive and choose another theme besides elementary the problem seems to go away, so maybe the problem is there.

**Comment by Hanouta** [comment]
I have the same issue when using awesomewm. But it happens only when the window is not set to maximized.
EDIT: Also happens when using Openbox, bspwm or Dwm.

**Comment by PaxSov** [comment]
I am having the same problem but it goes away when I switch it to fullscreen in bspwm, if I do this I cannot see everything because my polybars are blocking it.
[2020-04-07-200103_1920x1080_scrot](https://user-images.githubusercontent.com/63252513/78708772-8cf93e80-790a-11ea-8f3f-6fa38e7a9436.png)
edit: the problem also goes away when I use the fullscreen button in the app.
This issue still needs fixing.
I am using the aur package.

**Comment by wax911** [comment]
Can confirm that same issue also exists on Kbuntu 18.04

**Comment by ricardoseriani** [comment]
Same issue here, on  i3wm 4.17.1

**Comment by faelana** [comment]
Same here, KDE.

**Comment by gokberkakdeniz** [comment]
Same issue on XFCE 4.14.

**Comment by gokberkakdeniz** [comment]
I found its fix. https://github.com/alainm23/planner/issues/303

**Comment by bfsgr** [comment]
Confirmed that the fix found in #303 works in Fedora 31 with i3wm in Planner 2.3. 

It seems that the problem is in elementary theme, although I think this should be a concern of Planner, since it most definitely is going to keep users away, so if this css tweak can be added to the source code it should. I'm gonna wait feedback before closing this issue.

### Solution:

Add the following code to your ~/.config/gtk-3.0/gtk.css 
````css
window decoration {
    box-shadow: none;
    margin: 1px;
}
````

**Comment by rolodoom** [comment]
Can confirm that same issue also exists on Kubuntu 19.10 using official app from flathub. Only when window is not maximized.

![Screenshot_20200419_115457](https://user-images.githubusercontent.com/61945227/79694603-f9433e80-8236-11ea-9f07-2912f2cd04a2.jpeg)

**Comment by alainm23** [comment]
Yes, the error only happens in KDE, for some reason KDE cannot draw a CSS `box-shadow` correctly, I have a solution for this but I still want to investigate further.

**Comment by bfsgr** [comment]
Should this issue be closed?

**Comment by ankitson** [comment]
I'm using PopOS with regolith/i3wm and still see the same issue, even with the gtk.css patch mentioned in #303 . 

EDIT: It displays correctly if I force the theme to Adwaita before launch (and the gtk.css patch is not needed):

```flatpak --env="GTK_THEME=Adwaita" run com.github.alainm23.planner```

EDIT2: Running with Adwaita breaks other parts though: 
![adwaita](https://user-images.githubusercontent.com/855649/82751487-7436d200-9d6c-11ea-8d07-8afdcba21bd9.png)

^ Adwaita

![elementary](https://user-images.githubusercontent.com/855649/82751489-76009580-9d6c-11ea-8cd4-1b0db0f9050e.png)

^ elementary

**Comment by Domesdos** [comment]
Same issue on Qtile using the elementary-planner-git AUR package as of today.
The mentioned gtk.css fix works.

**Comment by gregflynn** [comment]
workaround doesn't work if you installed via flatpak. @alainm23 any chance you can push the update you tested out here? https://github.com/alainm23/planner/issues/303#issuecomment-614316932

**Comment by volker-schukai** [comment]
Same issue on debian buster with i3wm (flatpak)

**Comment by alainm23** [comment]
Unfortunately this is a bug in the elementary OS stylesheet that other applications like Akira also suffer from. It's unlikely we will fix it here. 

We can reopen if elementary refuses the issue.

elementary/stylesheet#843

**Comment by omega3** [comment]
I still have this issue with label view in Plasma 5
https://i.imgur.com/8Qouv8C.png

When there is no task in this view the window look normal. As soon as I add tasks it gets a black frame.

The work around doesn't work for me.
Installation from AUR on Manjaro.

**Comment by jerry-ne** [comment]
Please, reopen this issue. It is not about KDE or elementary OS, I am running LXQt on Lubuntu 20.04.1 LTS (no i3 wm) and same bug with black borders. Installed via flatpak. Workarounds does not work.

**Comment by almandin** [comment]
Same problem with Manjaro/i3, the workaround fixes the black borders for the main window but not for other secondary windows, especially when using the feature to open a secondary window to get a kind of memo.

**Comment by Flare183** [comment]
Having the same issue on Xubuntu using both Compiz Fusion and XFWM4.
![Screenshot_2021-01-05_11-46-48](https://user-images.githubusercontent.com/4323/103673569-bd2e4600-4f4b-11eb-90ee-1bbbd3b57553.png)

**Comment by xxyangyoulin** [comment]
I still have this issue on bspwm.

**Comment by BeatLink** [comment]
Okay, seeing as this issue has been reported numerous times (#303, #353, #440 and #495) we should definitely reopen this issue.

**Comment by Bykow** [comment]
Any update on this issue ?

**Comment by 3nt3** [comment]
Bump

**Comment by JezerM** [comment]
The provided workaround doesn't work with Flatpak if set inside `~/.config/gtk-3.0/gtk.css`, however it does work if it's inside your app config directory: `~/.var/app/com.github.alainm23.planner/config/gtk-3.0/gtk.css`
