### ISSUE TITLE
Flatpak version gets updates late? I am still on v2.2.2

### ISSUE THREAD

**Issue by unsungNovelty** [alainm23/planify#270]
First of all, Amazing app! Thanks a lot for your effort on this! This is making things easier for me.

**Describe the bug**

I use the flatpak version from flathub and it is still in **v2.2.2** While the latest version as per [Planner/Releases](https://github.com/alainm23/planner/releases) is **v2.2.11**.

Is this a known bottleneck? I am just curious about it as _I am excited for some of the latest changes in v2.2.8 still._ Or is there a bug or something in Flathub? If you're not aware of it, just wanted to let you know. :slightly_smiling_face:  

**To Reproduce**

_Flathub shows v2.2.2 too:_

:point_right: https://flathub.org/apps/details/com.github.alainm23.planner

**Steps to reproduce the behavior:**

- Go to settings and then `about`, you will find v2.2.2 instead of a newer version.

**Expected behavior**

- I should have the latest v2.2.11.

**Screenshots**

![image](https://user-images.githubusercontent.com/11845908/75757734-e47b1c00-5d58-11ea-8fab-c92e803396a8.png)
_Screenshot of the version from my computer._

**Desktop (please complete the following information):**
 - OS or DE: N/A
 - Version v2.2.2

**Additional context**

- N/A

**Comment by alainm23** [comment]
Thank you for your concern. We had some problems with AppCenter so we released several versions to solve it. Today I'm releasing v2.2.13 that fixes some bugs (AppCenter and FlatHub).

**Comment by unsungNovelty** [comment]
Can't wait! Appreciate it! :+1:
