### ISSUE TITLE
Change requested for AppCenter: More descriptive release description

### ISSUE THREAD

**Issue by cassidyjames** [alainm23/planify#271]
Thanks for submitting an update to AppCenter. However, while reviewing your app we noticed the release description for 2.2.13 is not very descriptive. We require precise release descriptions to encourage transparency of development and to keep the feature useful—otherwise every app might just include "bug fixes and performance improvements".

For this release, I would recommend something like:

>Improved stability and some bug fixes:
>
>- Fix tasks marked for next week showing up on the "Today" list
>- Fix tasks for today not showing up
>- Fix focus when changing views
>- Updated translations
>
>Special thanks to 'Wount' for becoming our new silver tier patron and supporting the development of Planner.

Please submit a new release, (i.e. 2.2.14) with the updated description—there is no need for a 2.2.13 description as it was never released to users.

**Comment by alainm23** [comment]
Sure. I did it in a hurry. Thanks for the recommendation.
