### ISSUE TITLE
Project notes not visible without active tasks

### ISSUE THREAD

**Issue by WebShapedBiz** [alainm23/planify#273]
**Describe the bug**
Project notes not visible when there is no active tasks

**To Reproduce**
1. Go to 'Ad List -> Project'
2. Click Project menu -> Edit
3. Add notes and close Edit menu
4. Empty project "landing page" is making notes unvisible

**Expected behavior**
Project notes should be visible at all times

**Screenshots**
![Peek 2020-03-04 13-52](https://user-images.githubusercontent.com/6765137/75881492-74839900-5e1f-11ea-8272-d68162ec7e7e.gif)

**Desktop (please complete the following information):**
 - OS or DE: [e.g. pantheon, unity, gnome]: elementaryOS
 - Version [e.g. 0.1.2]: 5.1 (Hera)

**Comment by 4jNsY6fCVqZv** [comment]
Sounds reasonable!
From a UI/UX perspective, are there any concerns about implementing the feedback?

**Comment by 4jNsY6fCVqZv** [comment]
Sounds reasonable!
From a UI/UX perspective, are there any concerns about implementing this feedback?

**Comment by 4jNsY6fCVqZv** [comment]
You think the project notes should always be visible or only if I have already created content in them?

By the way, I have the feeling that "project description" is more appropriate at this point - in terms of wording. What do you others think?

**Comment by WebShapedBiz** [comment]
@4jNsY6fCVqZv here's my two cents worth:

I believe that it's only natural when creating a new project one would like to enter both - name and description (yes, I think it's a far more appropriate name than Note). When I'm creating a new GitLab repo, and I believe you guys too, I'm usually entering both fields as a first step of the creation. Planner, however, does not allow the user to enter a project description in Add List menu nor in the Project edit menu. The later UX, regarding this field, is just awful, and what's worse, in the same application where overall UX is a dream by any standard. Just try to poke around trying to get to the "Add note" field. I even believe it has a bug because I managed to get "Add note" in Edit mode but the field was "pushed" under the Project name and the curser becomes hidden by it. I'll try to replicate this and report a bug with more meaningful details.

Regarding the question should the project notes be visible all the time, I believe yes, because tasks are coming and going dynamically and users might find themselves in the project with all tasks completed but the project is still active, just without live tasks at that point. Why then hide the project description? What is the gain here?

Thank you all for your time and effort in developing this marvelous app.

Cheers.

**Comment by alainm23** [comment]
@WebShapedBiz Thank you for your comments. This will be corrected.

**Comment by 4jNsY6fCVqZv** [comment]
Again concretely inquired:
The default placeholder is "Add note". Should this placeholder always be visible or only text that I have already added as description for my project?

I like the idea that it is possible to optionally enter a description during project creation, which is then also directly visible without tasks!

Btw. I'm not sure how this could be handled with sections. Does it need a similar function there?

**Comment by WebShapedBiz** [comment]
In the current design, which is awesome btw, I believe that it should be a placeholder because there is no other indication that there's something there to be filled. There is no visible input field, basically, it's an empty space below project title.

**Comment by alainm23** [comment]
What do you think about editing the project description from the project preferences only?

**Comment by WebShapedBiz** [comment]
It's also good. Besides, it's for sure more complicated to redesign Add List widget to add a Description field there, so adding it from the Project preferences widget where there is a lot of unused space is completely fine.

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 Why "only" in the project preferences? How would that look like?

**Comment by alainm23** [comment]
I'm adding a little visual indicator.

![image](https://user-images.githubusercontent.com/33765137/76107773-5cd71c80-5fa7-11ea-9a5f-cd08e6ad7eea.png)

@4jNsY6fCVqZv Relax, it was just an idea :).

**Comment by 4jNsY6fCVqZv** [comment]
I'm more curious than not relaxed ;)
The question was meant to be  unbiased as to the result. So why would you put it in the project preferences "only"?

**Comment by alainm23** [comment]
Well, it was just an idea. But I think this indicator improves the UX a lot.

@WebShapedBiz I think I have a design idea to be able to create a project with a name and description.

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for your good design ideas!
Should the indicator and the placeholder always be visible?
How do you feel about it?

**Comment by alainm23** [comment]
The indicator will only be visible when the editing of the note is in focus.

**Comment by 4jNsY6fCVqZv** [comment]
And how should the "add description" field be accessible?
