### ISSUE TITLE
It should only be possible to open one instance of "Preferences"

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#274]
Currently I can open as many instances as I want by clicking on the gear wheel, but since I cannot move the window, it is only possible to perform actions in the last opened instance. If it should not be possible to use several preferences windows at the same time, the possibility should not exist and the number of possible instances should be limited to 1.

I use Planner version 2.2.14 from the AppCenter.

**Comment by alainm23** [comment]
You are right, I will change the dialog preferences to a modal window (Always in focus).
