### ISSUE TITLE
The color I have assigned to a project could be reflected more clearly in the redesigned search function

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#275]
The issue is already described here, but for me it fits better into a separate issue.
https://github.com/alainm23/planner/issues/206#issuecomment-596186951

**Comment by alainm23** [comment]
I think this new progress indicator improves the visualization of the project color.

![image](https://user-images.githubusercontent.com/33765137/77124524-1b1b8c80-6a11-11ea-80ea-89c7c3ccf994.png)

**Comment by 4jNsY6fCVqZv** [comment]
One more question: I read on Twitter that you changed the icon for the areas.  How come? The old one was actually quite nice. Although I'm not sure if that was the best metaphor for it.

**Comment by alainm23** [comment]
If I liked the old area icon. I changed it because I needed a way to indicate that a work area was open or closed and I think the icon for an open or closed folder solves it.

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 Did you think about whether it makes sense to leave the project progress out of the search and instead just display a filled circle in the respective color of the projects, like Planner does in the Upcoming view? https://github.com/alainm23/planner/issues/206#issuecomment-596186951

**EDIT** I like the redesign of the progress indicator.
However, this issue cannot yet be solved for me with your proposed design. Because if a project has no completed tasks, the assigned project color is still not clearly visible here either. The projects then only have the narrow color ring, right?
Hence my idea that the colors fill the circles and the progress indicator is not part of the search.

How do others feel about this?

**Comment by alainm23** [comment]
I think that a color indicator is enough to differentiate a project in Quick Find, I will close this problem since this does not represent a problem for other users.
