### ISSUE TITLE
Past week report feature (aka see what I did in the last 7 days)

### ISSUE THREAD

**Issue by zedtux** [alainm23/planify#276]
**Is your feature request related to a problem? Please describe.**
I'm doing a weekly meeting where I have to briefly tell what I did last week and what I'll work on on the week. While the latter is already possible, the former is not possible.

**Describe the solution you'd like**
It would be awesome to get a place where I can see the closed tasks, in chronological order. Choosing the task filter's end date is a wish.

**Describe alternatives you've considered**
I don't see any yet.

**Additional context**
None. Please ask if any make sense.

**Comment by alainm23** [comment]
I have a super idea to add this feature. I'm thinking about designing an overview for each project where I show the project progress and the tasks completed in the last 7 days (the same way Todoist does but for each project). This way we can know how many tasks or which ones were completed in a specific day.

**Comment by zedtux** [comment]
Also a bird eye view which shows this but for all projects, one under the other.

**Comment by alainm23** [comment]
This feature is available in v2.5, click `Quick Find` -> `Completed`
![image](https://user-images.githubusercontent.com/33765137/97064611-cc1c7380-156c-11eb-9c65-881b69226c0b.png)

**Comment by zedtux** [comment]
Awesome @alainm23 thank you !
