### ISSUE TITLE
Copy or Import Projects - easy way to quickly build predefined projects

### ISSUE THREAD

**Issue by hcal** [alainm23/planify#279]
I have several big projects that I do over and over for various customers.  The only thing that really changes is the customer's name in the project title and the dates.  Since each project has dozens of tasks, it takes a long time to get each one set up.

It would be nice if there was an easy way to quickly build predefined projects.  I thought of two simple ways to do that, but I'm open to any options.  The first option is to have the option to copy/duplicate an existing project   With this option, it might be nice if there was a way recalculate the due dates.  The second option I thought of is a feature to import a project's tasks from a text file.  This option might not look as nice, but I think I might prefer it since I could keep set of "templates" for big projects do a quick find/replace on the text file before importing all the tasks.  

I have read other comments that imply copying tasks is supported, but I haven't figured out how that works.  Maybe I don't have the latest version.  I installed from flathub last week.

I saw a cli tool for managing todoist in bash.  That looks like it might provide a work-around for my usecase.  Not everyone is able to do that though, so I thought this might be a generally useful feature.  

I'm not a seasoned FOSS contributor so please feel free to delete this ticket if it is inappropriate or in error.

**Comment by alainm23** [comment]
Thank you very much for your comment. Any suggestion is valid if it makes your productivity better.
Basically what you are requesting is a way to import or use templates. Todoist already has a [repository](https://todoist.com/templates/) for this purpose (Unfortunately only for premium users).
 
To solve this problem quickly, Planner should have an option to duplicate the project. 
But I like the idea of having a user-defined template and that when you create a project you already create it with this template.

I like both options. I'll keep that in mind for a future release. Thank you very much for sharing your ideas.

**Comment by geertdobbels** [comment]
I am exactly in the same situation as @hcal .  All my projects are very similar and have a lot of tasks, to such an extent that I cannot use the software if there is no possibility to duplicate projects (this does not mean that I do not like the software, but having to create each project from scratch in my case is unproductive).
But I am a bit confused: on the version 2.4 release notes ([https://planner-todo.web.app/release/2020/06/22/what-s-new-in-v2-4/]) it is mentioned that an option to duplicate tasks has been added.
I have been downloading what is supposed to be v.2.4.6 from flathub, I have downloaded the 2.4.6 branch from Github and built it, but all of them show version number 2.3.5 in "settings-about", and I cannot find a duplicate task option anywhere... is this an error in the release notes, or am I missing something obvious here ?

**Comment by BeatLink** [comment]
This issue would be best served as two separate issues:

1. Ability to duplicate a project

2. Ability to import projects from files

**Comment by BeatLink** [comment]
The two new issues have been created. I am closing this issue in favour of the above two.
