### ISSUE TITLE
Travis gives me a failed build

### ISSUE THREAD

**Issue by alainm23** [alainm23/planify#28]
I have not the slightest idea why this happens, if someone can help me I will be very grateful.

https://travis-ci.com/alainm23/planner

**Comment by cjfloss** [comment]
on [this line](https://github.com/alainm23/planner/blob/0da0174919320c27e862a79e0dab9c4aebf32478/.travis.yml#L25), it should be `npm i -g @elementaryos/houston`

reference: https://github.com/elementary/houston/wiki/Continuous-Integration

**Comment by cjfloss** [comment]
Another thing, you should add the name-domain variable, so that PR don't report fail.

like this: https://github.com/tomatoers/tomato/pull/61/files

**Comment by alainm23** [comment]
Thank you very much, it works

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 Travis is still displaying errors.
Maybe you can see something in the AppCenter Build Configuration?

https://github.com/elementary/appcenter/runs/334056849

There it says: "script": [
    "houston ci --type system app --name-domain io.elementary.appcenter --name-human AppCenter"

While your configuration says:
 "script": [
    "houston ci"
https://github.com/alainm23/planner/runs/348617643
