### ISSUE TITLE
The button for creating a sample project should be located where it is possible to create new projects

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#280]
![Screenshot](https://user-images.githubusercontent.com/46536067/76617444-3290dc00-651e-11ea-91cd-9af6d9f28448.png)

Right now he is sitting somewhere in the general settings. I do not find that intuitive.

My expectation would be that the option would be more directly anchored in the "Add List" menu.
However, I wonder if it wouldn't make sense to remove this feature altogether.
For me, various scenarios are currently emerging:
- I have done the tutorial and now I know how to use Planner. So I do not need another example project.
- I accidentally deleted the tutorial. Then there is the Undo functionality.
- I missed to use the Undo functionality in time. Then there is the reset button in the preferences.
- And finally I can still try out and find out something by myself.

In connection with the possibility to duplicate projects or to create own templates https://github.com/alainm23/planner/issues/279 I guess you don't really need the example structure of the example project to create new projects in the future.

My vision right now: When starting the program for the first time, there might be a kind of guided introduction tour in form of popups or slides (in the sense of the elementary onboarding app), which explain the most important menus and functions. Users always have the possibility to skip. At the same time they can set a check mark whether the guided tutorial should be shown again or not when restarting Planner. The tutorial could also actively encourage users to perform the first steps themselves by taking action (just as it is possible in the onboarding app). For example "Create your first project now". "Create a task and assign it a due date for today" etc. and just show them where they can do it in the UI. The slides could have different topics, which are necessary to help you to get started immediately

How do you others feel about this?

**Comment by alainm23** [comment]
It is a good observation, the tutorial project needs love, you are free to contribute [here](https://github.com/alainm23/planner/blob/master/src/Utils.vala#L854l).

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/93161803-f3b02e80-f6d8-11ea-9765-7683804a4f82.png)
