### ISSUE TITLE
Renaming "Add List" to "Add Project"

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#281]
![Screenshot](https://user-images.githubusercontent.com/46536067/76618464-88ff1a00-6520-11ea-9858-6c34d70054f3.png)

I imagine that this makes the functionality behind the button even clearer. Especially since there is no tooltip for it yet.

**Comment by alainm23** [comment]
I understand but this button when activated does not only create a project, it can also create a folder (Work Area) so I put that name, to refer that the user can create some list of projects or work areas.

**Comment by 4jNsY6fCVqZv** [comment]
I hear you. "List" reminds me more of a simple shopping list, though. Or the checklist that I can create within a task. But for me, that would be a reduction in terms of complex projects or areas.
Perhaps we could search for a broader term?
