### ISSUE TITLE
Please update .appdata.xml.in & .desktop.in

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#283]
.appdata.xml.in -> Change the summary "Task and project manager with support for Todoist developer for Gnu/Linux" to "Task manager with Todoist support designed for GNU/Linux 🚀️".

.desktop.in -> Change the comment "Never worry about forgetting things again" to "Everyone needs a task manager and Planner adapts to anyone's needs" if this should be the new tagline of Planner.

Not sure if a period is needed as punctuation mark for the comment as well as for the summary and description. To make it consistent, at least dot behind the 🚀️ should be removed from the GitHub project description.

If "Everyone needs a task manager and Planner adapts to anyone's needs" is the new tagline, the project's README.md should also be adapted to reflect this.

**Comment by 4jNsY6fCVqZv** [comment]
Are you sure this issue is fixed?
When I look at the latest master, the files are still unchanged.

**Comment by 4jNsY6fCVqZv** [comment]
Are you sure this issue is fixed?
When I look at the latest master, the files are still unchanged.

**EDIT** I can also offer to make a pull request. I have never tried this before.

**Comment by alainm23** [comment]
Don't worry, I already made the change. The tagline of the application will continue as "Never worry about forgetting things again"

**Comment by 4jNsY6fCVqZv** [comment]
One last question about that: Why does the .appdata.xml says:

`<description>
    <p>Everyone needs a task manager and Planner adapts to anyone's needs</p>`?

Instead of "Never worry about forgetting things again".
