### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by martinpl** [alainm23/planify#284]
**Describe the bug**
App just crash on startup (on clear db too). What is weird because it work fine on PC with very similar configuration. Crash happens on laptop.

**Desktop (please complete the following information):**
 - OS / DE: Arch Linux / GNOME 3.36
 - Version: 2.2.14.r19.g79a30dab

**Additional context**
Log:

> **
> ERROR:com.github.alainm23.planner@exe/src/Services/Database.c:2448:services_database_add_text_column: assertion failed: (res == Sqlite.OK)
> Bail out! ERROR:com.github.alainm23.planner@exe/src/Services/Database.c:2448:services_database_add_text_column: assertion failed: (res == Sqlite.OK)
> Przerwane (zrzut pamięci)

**Comment by Jayrive** [comment]
I can state the same problem but it is the first time I installed it so I might don't know why it happened.

**Desktop**

- OS/DE: Artix Linux (Archlinux derivative) / XFCE 4.14
- Version: 2.2.14.r0.gbf2181dd-1

**Comment by alainm23** [comment]
Thank you very much for commenting. You installed Planner from AppCenter, Flathub?

**Comment by martinpl** [comment]
Tested AUR and chaotic-aur (compiled AUR)

**Comment by orlando-oli** [comment]
the same is happening to me
```
**
ERROR:com.github.alainm23.planner@exe/src/Services/Database.c:2448:services_database_add_text_column: assertion failed: (res == Sqlite.OK)
Bail out! ERROR:com.github.alainm23.planner@exe/src/Services/Database.c:2448:services_database_add_text_column: assertion failed: (res == Sqlite.OK)
[1]    3862699 abort (core dumped)  planner
```

Manjaro linux unstable

**Comment by Jayrive** [comment]
> Thank you very much for commenting. You installed Planner from AppCenter, Flathub?

I took it for the aur version too

**Comment by martinpl** [comment]
Hmmm after adding section: program crashed and i have this same error (on PC)

**Comment by alainm23** [comment]
It seems that the AUR version is building Planner from the repository. I fixed these bugs in my last commit.

**Comment by martinpl** [comment]
New pkgver trigger update i forget about it. Tested with recompiled and works thanks 🥳

**Comment by alainm23** [comment]
Hahaha that's good but I'm sorry to say that you are using a development version. It's all my fault for working on the master repository directly.

**Comment by sollymay** [comment]
Hey @alainm23, latest version was just updated for me (through AppCenter) and its now crashing with the same error. Here's my log:

```
(com.github.alainm23.planner:32325): Gtk-CRITICAL **: 23:49:52.350: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed

(com.github.alainm23.planner:32325): Gtk-CRITICAL **: 23:49:52.351: gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed

(com.github.alainm23.planner:32325): Gtk-CRITICAL **: 23:49:52.351: gtk_button_set_image: assertion 'GTK_IS_BUTTON (button)' failed

(com.github.alainm23.planner:32325): Gtk-CRITICAL **: 23:49:52.391: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:32325): Gtk-CRITICAL **: 23:49:52.397: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed

(com.github.alainm23.planner:32325): Gtk-CRITICAL **: 23:49:52.398: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:32325): Gtk-CRITICAL **: 23:49:52.398: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:32325): Gtk-CRITICAL **: 23:49:52.400: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:32325): Gtk-CRITICAL **: 23:49:52.400: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed
**
ERROR:/build/com.github.alainm23.planner-2.2.14/src/Services/Database.vala:1597:services_database_get_all_projects_no_area: assertion failed: (res == Sqlite.OK)
```
