### ISSUE TITLE
Suggestion: start minimized

### ISSUE THREAD

**Issue by WebShapedBiz** [alainm23/planify#29]
Since the icon has a nice notification badge it would be nice have an option to start the app minimized.

**Comment by alainm23** [comment]
I’m sorry, but I do not understand the suggestion, you could explain better by please.

**Comment by WebShapedBiz** [comment]
Sorry for not being clear. I've put Planner in my startup apps and every time the system goes up the Planner main window is shown. I was just thinking that it would be nice to have an option to start it minimized, like for example Skype.

**Comment by alainm23** [comment]
It's true, I have the same problem, I'm going to investigate how to do this, thanks for the comment.

**Comment by WebShapedBiz** [comment]
Thank you for your time and effort putting together this beautiful app, I really think it should be used as a showcase of what out-of-the-box thinking together with ElementaryOS can achieve.

**Comment by alainm23** [comment]
You can try it now.

**Comment by WebShapedBiz** [comment]
Awesome @alainm23, thank you for your effort. I'll try when my `apt update` pick it up.

Cheers.

**Comment by alainm23** [comment]
@WebShapedBiz Sorry for not being more explicit, I am now working on a new version of Planner (v2) This version is not available in AppCenter yet. However, you can test installing it from this repository 😁️.

![image](https://user-images.githubusercontent.com/33765137/69815921-5cb7cb80-11c5-11ea-9da8-798d3f6db860.png)

**Comment by WebShapedBiz** [comment]
Ah OK, thanks for this clarification.
