### ISSUE TITLE
Nextcloud support

### ISSUE THREAD

**Issue by ilfarpro** [alainm23/planify#294]
Please, add Nextcloud support for tasks sync

**Comment by alainm23** [comment]
Sure, but I'd have to make a big change in Planner's backend to make this work. However, I think it's possible.

**Comment by romixch** [comment]
I do like this feature very much. So the plan seamss to be using Caldav. Right?

**Comment by inputsh** [comment]
FYI there's work in progress to add Nextcloud as a provider in Online Accounts section, though I doubt it's going to get into elementary OS before 6.0, maybe even later:

https://github.com/elementary/switchboard-plug-onlineaccounts/pull/121

https://github.com/orgs/elementary/projects/63

**Comment by lightonflux** [comment]
Gnome and gnome-tasks already pick up Nextclouds CalDav details. I don't know how elementary handles online accounts. But i would hope that they reuse gnome components. 
https://github.com/GNOME/gnome-todo

**Comment by Theodin** [comment]
Nextcloud support would be great. In the meantime, Ill help by translating Planner :-)

**Comment by tdoerrich** [comment]
Is there any chance we'll see this before ElementaryOS adds them? Just wondering since it still works in Manjaro KDE and such and I love this app! :)~

**Comment by ghost** [comment]
Really looking forward for the nextcloud sync :D

**Comment by tifDev** [comment]
> Really looking forward for the nextcloud sync :D

Me too!

**Comment by BeatLink** [comment]
Could this issue be closed in favor of https://github.com/alainm23/planner/issues/75?

**Comment by alainm23** [comment]
I will close this issue in favor of #555
