### ISSUE TITLE
Labels section

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#295]
I think that it would be helpful if you could see all tasks assigned a certain label to be visible in one place.

I would suggest adding a new section under "Upcoming" called "Labels", in here you should see a list of all your tasks with labels assigned to them grouped into sections of that label.  For example, all tasks marked "Important" should be under a section named "Important".

I think this would be helpful as currently you need to go through each list manually to find tasks that have a certain label assigned to them.

**Comment by alainm23** [comment]
Of course I do. I'm adding this feature for v2.3. The idea is to use Quick Find to find the label and filter.

![image](https://user-images.githubusercontent.com/33765137/78298906-de639100-74f8-11ea-9210-209dc6525dda.png)


![image](https://user-images.githubusercontent.com/33765137/78298449-f25ac300-74f7-11ea-9c1e-5363f164389d.png)
