### ISSUE TITLE
Renaming Todoist tasks only affets Planner, not Todoist.

### ISSUE THREAD

**Issue by wout** [alainm23/planify#296]
**Describe the bug**
Renaming a task in Planner does not have any effect on Todoist. I renamed a bunch of them, but in Todoist they are all still the same. It's not a sync issue, because newly created tasks are added in Todoist as well.

**To Reproduce**
1. Rename task
2. Sync
3. Visit Todoist

**Expected behavior**
Task names should stay in sync between Todoist and Planner.

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/107324/78422937-d1f74980-765a-11ea-8113-53873c93013e.png)

**Comment by wout** [comment]
I need to mention is worked for a new list, created through planner. It seems only old lists from before I started using planner can not be renamend.

**Comment by alainm23** [comment]
Thank you very much for reporting the problem. I'm trying to reproduce the bug but I can't get it.
What do you mean by the old lists from before you used Planner?

**Comment by wout** [comment]
@alainm23 I mean the projects that were already in Todoist before I started using Planner.

**Comment by alainm23** [comment]
This is very strange, please try v2.3 of Planner and let me know if the problem was solved. 

If the problem persists, remove access to Todoist from Planner. `Preferences` > `Todoist` > `Logout`. and log back in.

**Comment by alainm23** [comment]
I will close this issue since this does not represent a problem for other users.
