### ISSUE TITLE
Enter in checklists does not always work as expected

### ISSUE THREAD

**Issue by wout** [alainm23/planify#297]
**Describe the bug**
The behavior of checklists isn't always consistent.

**To Reproduce**
1. Create a new task
2. Add a checklist
3. Type the name of the item
4. Press `enter` to create the item and have a new one available
5. Unfocus the second, empty item - it disappears
6. Click on the first item, press `enter`
7. Nothing happens

**Expected behavior**
I would expect a new item to appear on `enter`, but it does not. The "Add Checklist" button needs to be clicked once again, which in itself is a bit confusing. It seems like you are adding a second checklist, but in fact, it just adds a new item to the existing checklist.

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/107324/78454310-303e1f80-768f-11ea-9b1a-0f895c03d2eb.png)

![image](https://user-images.githubusercontent.com/107324/78454297-1ef51300-768f-11ea-91f6-b64acdbdf6a6.png)

**Comment by alainm23** [comment]
That's a very good idea, I'll keep that in mind, thank you very much.
