### ISSUE TITLE
Planner does not start

### ISSUE THREAD

**Issue by AstolfoKawaii** [alainm23/planify#298]
I have installed planner from flatpak on openSUSE Tumbleweed (KDE).

After running `flatpak run com.github.alainm23.planner` I get output like 
```
(com.github.alainm23.planner:2): Gtk-WARNING **: 21:06:54.370: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 21:06:54.371: Failed to load module "unity-gtk-module"
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused

(com.github.alainm23.planner:2): Gtk-WARNING **: 21:06:54.374: cannot open display: :99.0
```
and nothing more happens, planner does not start.
I have the latest version available on flatpak `Planner com.github.alainm23.planner 2.2.14 stable`

**Comment by alainm23** [comment]
Please, try to install `unity-gtk-module`
https://launchpad.net/ubuntu/+source/unity-gtk-module

**Comment by AstolfoKawaii** [comment]
The problem was with openSUSE + flatpak
https://github.com/flatpak/flatpak/issues/1821

> Running xhost + helps but only untill a reboot
