### ISSUE TITLE
Logging into TODOist causes hang

### ISSUE THREAD

**Issue by ditServices** [alainm23/planify#302]
When logging into Todoist the app hangs, unable to log in at all. 

This happens after entering login credentials. 

Currently running Zorin 15.2 / Gnome. 

Screenshot: 
![Screenshot from 2020-04-07 20-00-49](https://user-images.githubusercontent.com/41305949/78708848-aa2e0d00-790a-11ea-8a77-43f866d781d7.png)

**Comment by black1good** [comment]
I can conquer , same thing is happening to me , i use ubuntu 18 lts

**Comment by rGalrito** [comment]
Same here.

It hangs on Ubuntu 18.04.

Can not login via Google sso or email/password.

**Comment by alainm23** [comment]
Could you please send me the details of your current operating system.
Do you install Planner from App Center or Flathub?

**Comment by black1good** [comment]
> Could you please send me the details of your current operating system.
> Do you install Planner from App Center or Flathub?

Hey , for me it now works , before it was stuck on Todoist . Now I have managed to get my acc with planer connected.  Thanks a lot .

**Comment by alainm23** [comment]
> Hey , for me it now works , before it was stuck on Todoist . Now I have managed to get my acc with planer connected. Thanks a lot .

Did you install Planner from Flathub?
For v2.3.3 I update Gnome SDK to v3.36. Can it be the solution?

**Comment by ditServices** [comment]
What specifics do you need? Its Zorin 15.2 I installed from default software centre which I believe is the standard ubuntu one. I recently updated to the latest version of planner but the issue still persists.

**Comment by alainm23** [comment]
What video card do you use? 
Free or non-free driver?

**Comment by ditServices** [comment]
> What video card do you use?
> Free or non-free driver?

lspci reports Intel 5906 with i915 driver in use

**Comment by black1good** [comment]
> > Hey , for me it now works , before it was stuck on Todoist . Now I have managed to get my acc with planer connected. Thanks a lot .
> 
> Did you install Planner from Flathub?
> For v2.3.3 I update Gnome SDK to v3.36. Can it be the solution?

Yes I put Flathub in my Ubutu Store and installed it  . I use gnome shell 3.28.4 ....

**Comment by chamannarved** [comment]
I have same issue in Ubuntu 18.04 and i installed from flathub (Planner v2.3.6).


![Screenshot from 2020-10-02 22-12-25](https://user-images.githubusercontent.com/24298575/94948303-ba5f2780-04fc-11eb-8f1d-63171bfa06c3.png)

**Comment by krisgesling** [comment]
Hey there, seeing the same thing with Planner v2.5.5 on elementary OS 5.1.7

Piping the application output to dmesg as soon as you hit "Log in" it throws the following:
```
(WebKitWebProcess:32213): Gdk-ERROR **: 09:38:45.632: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 204 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

At a guess, it seems like it might be an Nvidia driver issue.

**Comment by alainm23** [comment]
Could you remove the proprietary drivers and use the free ones for Nvidia? it's probably a solution.

**Comment by Alejandro-Villa** [comment]
I'm also having the same issue:

OS: Ubuntu 18.04.5 LTS x86_64
Planner v2.5.7 from FlatHub
NVIDIA GeForce GTX 1050 Mobile using NVIDIA Drivers version 450.80.02

I don't know how to get you the logs @krisgesling posted but i saw this come up in `dmesg` output when seeing the error:

```
[23927.699499] traps: eadedCompositor[3236] trap int3 ip:7f73a7940ec5 sp:7f7331ff9f80 error:0 in libglib-2.0.so.0.6400.6[7f73a7905000+84000]
```

**Comment by emk** [comment]
I'm also seeing this issue on Ubuntu 18.04, with the latest `nvidia-driver-418-server` in Planner 2.6 from FlatHub. I also have the following log message:

```
[  114.262390] traps: eadedCompositor[4370] trap int3 ip:7f9d97e61ec5 sp:7f9d23f
fdf80 error:0 in libglib-2.0.so.0.6400.6[7f9d97e26000+84000]
```

Every time I try to log into Todoist, this error appears again. I'm going to try with the open source nVidia driver (although I need the proprietary driver for a number of programs I use regularly).

**Comment by emk** [comment]
I can verify that this also fails with the open source Nouveau drivers on my machine. The error this time is:

```
[   91.598875] traps: eadedCompositor[4442] trap int3 ip:7fb3c9815ec5 sp:7fb3537fcf80 error:0 in libglib-2.0.so.0.6400.6[7fb3c97da000+84000]
```

If I run it from the command-line using `flatpak run com.github.alainm23.planner`, I get the following errors using the open source Nouveau driver:

```
Cannot get default EGL display: EGL_BAD_PARAMETER
Cannot create EGL sharing context: invalid display (last error: EGL_SUCCESS)

(WebKitWebProcess:19): Gdk-ERROR **: 11:23:20.689: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was '179'.
  (Details: serial 202 error_code 179 request_code 154 (unknown) minor_code 21)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

So I think this is just broken under Ubuntu 18.04 with no workaround. :-( I'm reluctant to upgrade my older laptop to 20.04, because that always involves a risk that I'll break suspend or some other key feature.

Thank you for a very promising-looking program, and for any help you can provide!

**Comment by emk** [comment]
This error was also one of the two bugs originally reported in https://github.com/alainm23/planner/issues/159, but that issue was closed when the other bug was fixed.

**Comment by emk** [comment]
As far as I can tell, `WebKitWebProcess` is provided by `webkit2gtk`. The newest version seems to be `libwebkit2gtk-4.0-37/bionic-updates,bionic-security,now 2.30.3-0ubuntu0.18.04.1`, and there doesn't seem to be any third-party package repositories with a new version. (I don't even know if the Flatpack version of Planner uses the system `webkit2gtk` libraries.)

**Comment by BeatLink** [comment]
Is this issue still present on the latest version of planner?

**Comment by Akucuki** [comment]
@BeatLink Yes, updated to the latest version - still cannot login

**Comment by Akucuki** [comment]
Updated now - the problem solved!
Ubuntu 20.04.2 LTS
