### ISSUE TITLE
Black frame outside of the main ui

### ISSUE THREAD

**Issue by faelana** [alainm23/planify#303]
**Describe the bug**
The app has a black frame outside of the ui

**To Reproduce**
Open the app

**Screenshots**
![Screenshot_20200409_041157](https://user-images.githubusercontent.com/46012160/78854054-4bef5000-7a18-11ea-89e6-5b72a8fb0d45.png)

**Desktop (please complete the following information):**
 - OS or DE: OS: (k)ubuntu; DE: KDE
OS: Ubuntu 19.10
KDE: 5.16.5
Qt: 5.12.4

**Comment by gokberkakdeniz** [comment]
[![https://imgur.com/nqz69Ox.png](https://imgur.com/nqz69Ox.png)](https://imgur.com/nqz69Ox.png)

it spams the following log:
`(com.github.alainm23.planner:7584): Gtk-CRITICAL **: 14:13:46.580: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed`


**system information**
OS: Fedora 31
DE: XFCE 4.14
GTK2: 2.24.32
GTK3: 3.24.13
GTK4: 3.96.0

**dnf package info**
elementary-planner: 2.2.14-1.fc31
elementary-xfce-icon-theme: 0.14-1.fc31
elementary-icon-theme: 5.1.0-2.fc31
elementary-theme: 5.4.2-1.fc31

**Comment by faelana** [comment]
i confirm that "byte", the music player has the same problem

**Comment by gokberkakdeniz** [comment]
I found that the following css class in [elementary theme](https://github.com/elementary/stylesheet/blob/master/elementary/gtk-3.0/gtk-widgets.css#L4075)  causes the problem :
```
decoration {
    border-radius: 4px 4px 0 0;
    box-shadow:
        0 0 0 1px @decoration_border_color,
        0 14px 28px rgba(0, 0, 0, 0.35),
        0 10px 10px rgba(0, 0, 0, 0.22);
    margin: 12px;
}
```
![before](https://i.ibb.co/4WXYK4t/Screenshot-2020-04-15-13-33-59.png)

Then, I set box-shadow to none and margin to 1px (to able to resize). Now, it is working.

```
window decoration {
    box-shadow: none;
    margin: 1px;
}
```

![after](https://i.ibb.co/hmQpTtQ/Screenshot-2020-04-15-13-34-31.png)

You can save this css snippet to `~/.config/gtk-3.0/gtk.css` file to make it permanently.

**Comment by bfsgr** [comment]
Duplicate of #268

**Comment by alainm23** [comment]
@tncga Thanks a lot, that's a great solution, I'm trying it out now on elementary OS and Planner looks a little weird. I think we can add that style when Planner runs on another distribution.

Guys could confirm if this works for everyone?

**Comment by faelana** [comment]
It didnt work here but i think its because im using the flatpak version, what path should i use instead?

**Comment by alainm23** [comment]
I'm developing a patch right now. Can you please help me test it? I'll send you the instructions right now.

**Comment by faelana** [comment]
@alainm23 yeah, of course.

**Comment by alainm23** [comment]
Try it please:
```
git clone https://github.com/alainm23/planner.git
cd planner/build-aux/flatpak
flatpak-builder --install repo com.github.alainm23.planner.json --force-clean --user
flatpak run com.github.alainm23.planner
```

**Comment by faelana** [comment]
okay, going to try it now. Will give feedback

**Comment by faelana** [comment]
```
$ flatpak run com.github.alainm23.planner
error: app/com.github.alainm23.planner/x86_64/master not installed


```

I uninstalled the app before trying, should i install it again? does it works like a patch?

**Comment by alainm23** [comment]
No need to uninstall but if you did there is no problem.

**Comment by faelana** [comment]
i did uninstall it, am i missing some install command?

**Comment by alainm23** [comment]
> Try it please:
> 
> ```
> git clone https://github.com/alainm23/planner.git
> cd planner/build-aux/flatpak
> flatpak-builder --install repo com.github.alainm23.planner.json --force-clean --user
> flatpak run com.github.alainm23.planner
> ```

Yes, you have to follow the commands I sent you.

**Comment by faelana** [comment]
yes, i did it

**Comment by alainm23** [comment]
Great, now run Planner 
`flatpak run com.github.alainm23.planner`

**Comment by faelana** [comment]
```

> $ flatpak run com.github.alainm23.planner
> error: app/com.github.alainm23.planner/x86_64/master not installed

```

**Comment by alainm23** [comment]
@zayn666 
This is rare, when you run this command it gives you some error or message.
`flatpak-builder --install repo com.github.alainm23.planner.json --force-clean --user`

In my case Planner is installed correctly and gives me this message in the terminal.
![image](https://user-images.githubusercontent.com/33765137/79387418-52f2f280-7f31-11ea-934c-c4e8e9c1a631.png)

**Comment by faelana** [comment]
yes it gave me some errors regarding the install of gnome sdk, installed it and now its io.elementary.BaseApp/x86_64/juno-19.08

**Comment by faelana** [comment]
installed it all, building now

**Comment by faelana** [comment]
okay so, runned it and the bug still remains

**Comment by alainm23** [comment]
@zayn666 I just uploaded an update, please rebuild the application and run it again.

```
flatpak-builder --install repo com.github.alainm23.planner.json --force-clean --user
flatpak run com.github.alainm23.planner
```

**Comment by faelana** [comment]
okay, building

**Comment by faelana** [comment]
![Screenshot_20200416_000045](https://user-images.githubusercontent.com/46012160/79397177-688a0b80-7f75-11ea-9e5b-2f7fdfcd2494.png)

Working great! Confirming that it works

**Comment by faelana** [comment]
okay so, i assume the update is being pushed, how should i clean it? I dont really work with flatpak that much

**Comment by faelana** [comment]
i removed the package as normal.

**Comment by anhnn-vie** [comment]
> i confirm that "byte", the music player has the same problem

change exec on shortcut
flatpak --env="GTK_THEME=Adwaita:dark" run com.github.alainm23.byte
