### ISSUE TITLE
TODAY date is wrong

### ISSUE THREAD

**Issue by webxess** [alainm23/planify#304]
The TODAY view shows the date from yesterday and the tasks from yesterday. Todoist.com shows everything correct on the web. Maybe time zone error? - I am located in Vienna (GMT+2).

**Comment by martinlikescoffee** [comment]
I'm experiencing the same issue, not sure if it's timezone related, but if it can help I'm in the UK (GMT+1). Installed via Flathub on Ubuntu 19.10. 

If I take any given task marked for "Today" and set it for another day like "Tomorrow" and then switch back, they will properly appear in the Today pane.

**Comment by webxess** [comment]
found a WORKAROUND - disable the option "stay in background" - close the app and restart it. Now the date is correct. Looks like the date is set on startup and not checked any more later on.
