### ISSUE TITLE
Ctrl - Z to undo completed projects.

### ISSUE THREAD

**Issue by Themancodes** [alainm23/planify#306]
**Is your feature request related to a problem? Please describe.**
Sometimes I check something but forget about it, or just dont want it checked and it would be far easier to undo it with a ctrl - z command

**Describe the solution you'd like**
Ctrl - Z
**Describe alternatives you've considered**
Honestly none comes to mind.

**Additional context**
Thanks for having made this amazing project.

**Comment by alainm23** [comment]
Thank you very much for your comment. In Planner v2.3 I am adding a notification to undo a completed task. could be an alternative solution?

**Comment by Themancodes** [comment]
That absolutely works!
Thanks!

**Comment by Libric0** [comment]
Hey, first of all thank you for this amazing app. 

I just want to add here, it seems like this notification is no longer shown. Furthermore, as soon as the notification would disappear, undoing would be impossible. ctrl+z would therefore still be very useful. :)
