### ISSUE TITLE
Using etesync for syncing across devices

### ISSUE THREAD

**Issue by lallenfrancisl** [alainm23/planify#307]
**Is your feature request related to a problem? Please describe.**
Syncing tasks using etesync would be very useful as lot of opensource android apps support it and it would be nice to sync with them.

**Describe the solution you'd like**
Ability to sync using etesync

**Additional context**
https://www.etesync.com/

**Comment by alainm23** [comment]
Thank you very much for your comments, sorry Planner uses Todoist as a synchronization server and we plan to use Caldav (Nextcloud) in the future, thinking about another synchronization system is very difficult.

**Comment by alainm23** [comment]
How did you install Planner? Flathub? Repository?
Could you send me the error that the terminal gives you?

```
com.github.alainm23.planner
flatpak run com.github.alainm23.planner
```

**Comment by lallenfrancisl** [comment]
Oh CalDAV sounds great. Thank you Alain

**Comment by 4jNsY6fCVqZv** [comment]
I find the idea with EteSync support very exciting. I had not thought about it yet. The special thing about it is the end-to-end encryption.  And that is something the DAV protocol just can't do, right?
Import and export seems to be possible. There is also a possibility to import and export.
There seems to be a DAV bridge https://www.etesync.com/faq/ and it may well complement the purpose of this issue https://github.com/alainm23/planner/issues/105. Also, there is already a first example of how an implementation for a task app can be realized. https://blog.etesync.com/tasks-org-adds-etesync-support/
It would therefore be nice if the discussion about the potential of this integration could go a little further and if people could be found who would help to develop such an integration. Maybe the team of EteSync itself or in collaboration with the elementary tasks developers.
How do others feel about it?

**Comment by 4jNsY6fCVqZv** [comment]
I find the idea with EteSync support very exciting. I had not thought about it yet. The special thing about it is the end-to-end encryption.  And that is something the DAV protocol just can't do, right?
I would like to share the following article on this subject by one of the developers of the end-to-end encrypted mail provider Tutanota, who also offer an end-to-end encrypted calendar.
https://opensource.com/article/20/3/caldav-security
With EteSync import and export seem to be possible. There seems to be a DAV bridge https://www.etesync.com/faq/ and it may well complement the purpose of this issue https://github.com/alainm23/planner/issues/105. Also, there is already a first example of how an implementation for a task app can be realized. https://blog.etesync.com/tasks-org-adds-etesync-support/
It would therefore be nice if the discussion about the potential of this integration could go a little further and if people could be found who would help to develop such an integration. Maybe the team of EteSync @tasn itself or in collaboration with the elementary Tasks developers @marbetschar and the Planner community.
How do others feel about it?

**Comment by marbetschar** [comment]
@4jNsY6fCVqZv the elementary Tasks app is a frontend which uses `libecal` to communicate with the [Evolution Data Server (EDS)](https://developer.gnome.org/platform-overview/stable/tech-eds.html.en). The EDS is responsible for all the synchronization stuff.

That said, if you are interested to add EteSync support it needs to be supported by EDS first to find its way into elementary Tasks eventually.

**Comment by 4jNsY6fCVqZv** [comment]
> it needs to be supported by EDS first

@Alain Does this also apply to Planner?

> to find its way into elementary Tasks eventually

@marbetschar Tasks support is of course a different repo. So just a quick question: Do you feel that the idea of an EteSync integration in EDS is worth supporting for Tasks and could you imagine working with Alain on an integration?

By the way, I discovered something in the EteSync repository about using EteSync with Evolution / GNOME Calendar / GNOME Contacts. https://github.com/etesync/etesync-dav#evolution--gnome-calendar--gnome-contacts
Does that mean that it could be done right now? Even without an integration into the EDS backend?

**Comment by marbetschar** [comment]
@4jNsY6fCVqZv according to the description of your link, I guess EteSync runs its own WebDAV server on your local machine and calls this "WebDAV Bridge".

That said, if you configure EteSync this way, it appears to EDS (and any other consumer) as regular WebDAV endpoint and *should* work without any further customization needed.

**Comment by tasn** [comment]
Hey, creator of EteSync here.

It looks like EDS will probably get native EteSync support this summer during GSoC, more information: https://blog.etesync.com/summer-internship-opportunities-etesync-projects-in-both-gsoc-and-outreachy/

GSoC projects are announced on May 3rd, so only then we'll know if GNOME got enough interns to actually do it, but it looks very likely at this point. So hopefully this will be ready for usage soon. :)

**Comment by 4jNsY6fCVqZv** [comment]
Hey, thanks for your message. That sounds wonderful!
What is the difference between a native EteSync solution for EDS and the workaround you already described at https://github.com/etesync/etesync-dav#evolution--gnome-calendar--gnome-contacts?

**Comment by marbetschar** [comment]
@4jNsY6fCVqZv I guess the difference is you don't need to install and run the additional WebDAV Bridge on your local machine in case EDS supports EteSync natively.

From a daily usage perspective I don't expect there to be any major difference.

**Comment by tasn** [comment]
Exactly what @marbetschar said.

**Comment by 4jNsY6fCVqZv** [comment]
Looks like there will be an usable EDS implementation after the summer.
https://blog.etesync.com/gnome-and-kde-etesync-projects-accepted-to-gsoc/

**Comment by tifDev** [comment]
> The special thing about it is the end-to-end encryption. And that is something the DAV protocol just can't do, right?

Yes, EteSync would be great!

**Comment by tasn** [comment]
@alainm23, can this ticket be reopened? Or should someone open a new one? EteSync support is now in Evolution (in the GNOME repos), so no more wait needed! It's just a matter of whitelisting the EDS account if EDS is supported.
