### ISSUE TITLE
Don't show badge count

### ISSUE THREAD

**Issue by ruiite** [alainm23/planify#311]
Don't work Badge count on any type of items(inbox,today,inbox+today).
Planner was installed via flatpak on Pop_os! 19.10. Flatpak version 1.4.3.

**Comment by abuggin** [comment]
Just installed using flatpack on fedora and works for me.
![image](https://user-images.githubusercontent.com/830963/79672354-f873c380-81c8-11ea-83a5-d2e5d323850f.png)
Amazing work btw :clap: :clap:

**Comment by ruiite** [comment]
Hmm after reinstalling on the same it works well... strange bug
