### ISSUE TITLE
Show Localization status on AppCenter

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#312]
There is already an open issue in the AppCenter repository. https://github.com/elementary/appcenter/issues/440
And also an example how this can be realized for an default app like Calculator using gettext domain in AppData.
I'd like to see this supported by Planner. How do you feel about the idea @alainm23?

**Comment by BeatLink** [comment]
A pull request has been created to add information about the translation status to the readme of planner. https://github.com/alainm23/planner/pull/707

As for support in the AppCenter, that requires further work from Upstream

**Comment by BeatLink** [comment]
I will close this issue for now.

**Comment by 4jNsY6fCVqZv** [comment]
Can you please be transparent about why you want to close the issue when you previously classified it as an enhancement?

**Comment by BeatLink** [comment]
Sure thing. Ive been trying to clean up the issues list to make it easier on @alainm23 . The way i see it, theres nothing that could be done on this end to progress the issue. Thats why i closed it. But i could reopen it and flag it with some kind of blocked or waiting label

**Comment by alainm23** [comment]
There are no plans to develop this feature at the moment.
