### ISSUE TITLE
Being able to open more than one settings window

### ISSUE THREAD

**Issue by abuggin** [alainm23/planify#313]
**Describe the bug**
Being able to open more than one settings window

**To Reproduce**
1. Open Planner
2. Click on settings wheel
3. Click on settings wheel
4. Click on settings wheel
5. Click on settings wheel
6. Click on settings wheel
7. ...

**Expected behavior**
I mis-clicked twice but got really surprised by the behaviour.

**Screenshots**
![image](https://user-images.githubusercontent.com/830963/79672387-5c968780-81c9-11ea-8293-a2062c71804e.png)

**Desktop (please complete the following information):**
 - OS or DE: Fedora flatpack
 - Version 31

**Additional context**

**Comment by alainm23** [comment]
Thank you very much for reporting the problem, this behavior was eliminated in v2.3, wait for the update.
