### ISSUE TITLE
Sections into lists

### ISSUE THREAD

**Issue by zhandosweb** [alainm23/planify#314]
Hello!

Please, let me ask one question. Can I create sections into lists? (projects)

In Todoist for example available this function: https://get.todoist.help/hc/en-us/articles/360003788739-Sections

With sections into projects, we can easily organize many tasks into one project. Without sections, will be chaos and hard to organize many tasks. 

Sorry for bad English, I'm still learning. Thank you for your app, love it and believe, that you understand me!

**Comment by alainm23** [comment]
Of course, the sections are available from the first release of Planner 2.

![image](https://user-images.githubusercontent.com/33765137/79678372-72ec1580-81c0-11ea-9e3a-fb576044d006.png)
