### ISSUE TITLE
Application doesn't launch & causes high CPU usage (after update to 2.3)

### ISSUE THREAD

**Issue by Hanouta** [alainm23/planify#317]
**Describe the bug**
When using an application launcher to launch Planner, it just creates an empty window(the window or background behind it is still visible) and causes a very high CPU usage(100% across all cores on my system). For some reason this only happens when using an application launcher which uses the .desktop file, it doesn't happen when I launch the application through the terminal or dmenu.

**To Reproduce**
1. Launch an application launcher (I have reproduced this issue with Rofi, Xfce4-appfinder and the Gnome shell overview)
2. Try to launch Planner

**Expected behavior**
The application should launch without hogging my CPU.

**Desktop (please complete the following information):**
 - OS or DE: Arch Linux, probably every DE(I have reproduced it on Xfce, Gnome and Awesomewm, didn't try others)
 - Version 2.3.2 (technically I'm on the latest commit 4c341a4)

**Additional context**
This didn't happen before I updated to 2.3.2, I was on commit 53372d43 previously.
Log:
```
(com.github.alainm23.planner:36574): Gtk-CRITICAL **: 00:46:25.256: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed

(com.github.alainm23.planner:36574): Gtk-CRITICAL **: 00:46:25.316: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:36574): Gtk-CRITICAL **: 00:46:25.318: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

** (com.github.alainm23.planner:36574): CRITICAL **: 00:46:25.320: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:36574): CRITICAL **: 00:46:25.384: SimpleCommand.vala:103: Couldn't launch command echo $DESKTOP_SESSION in the directory .: Kindprozess »echo« konnte nicht ausgeführt werden (Datei oder Verzeichnis nicht gefunden)

(com.github.alainm23.planner:36574): GLib-CRITICAL **: 00:46:25.384: g_child_watch_add_full: assertion 'pid > 0' failed

(com.github.alainm23.planner:36574): Gdk-CRITICAL **: 00:46:25.393: gdk_rgba_parse: assertion 'spec != NULL' failed

** (com.github.alainm23.planner:36574): CRITICAL **: 00:46:25.394: widgets_project_row_apply_color: assertion 'color != NULL' failed

** (com.github.alainm23.planner:36574): CRITICAL **: 00:46:25.437: __lambda782_: assertion 'text != NULL' failed

** (com.github.alainm23.planner:36574): CRITICAL **: 00:46:25.437: __lambda782_: assertion 'text != NULL' failed

** (com.github.alainm23.planner:36574): CRITICAL **: 00:46:25.437: __lambda782_: assertion 'text != NULL' failed
```

I was able to avoid this issue by replacing this line:
https://github.com/alainm23/planner/blob/2703e74a1567f5c1d13250e4ce3132349755bbac/src/Application.vala#L135
with
`var command = new Granite.Services.SimpleCommand (".", "/usr/bin/echo $DESKTOP_SESSION");`
Not sure if this works on every distro though(idk but maybe there are distros without a /usr/bin directory or sth)

**Comment by alainm23** [comment]
Sorry, I am sending an update to fix it.

**Comment by igalic** [comment]
when will this be coming to the PPA?

**Comment by alainm23** [comment]
@igalic We have no plans to support PPA, Planner depends on the default elementary OS theme and technologies like Flatpak or Snap help us with that problem.

**Comment by osbre** [comment]
i have the same, Elementary OS.
