### ISSUE TITLE
Ability to set custom font since Flatpak isn't respecting system-wide font

### ISSUE THREAD

**Issue by unsungNovelty** [alainm23/planify#318]
**Is your feature request related to a problem? Please describe.**

Currently planner uses system wide font settings as per [#238](https://github.com/alainm23/planner/issues/238) . But in Flatpak, the system-wide font might not get used depending on the DE/WM we use. 

I use i3WM and my font is not respected by Flatpak applications. Not just Plannerby the way, but all Flatpak apps. It is hard to set fonts for Flatpak applications! (There is no straight forward way to do it!) So if your font is not respected, you have no other go but to stick a font you don't like.

**Describe the solution you'd like**

An easy option to choose a custom font from the fonts installed on your system.

**Describe alternatives you've considered**

I've tried setting fonts for all Flatpak and this obviously includes Planner, but I broke the theme making the app unable to use. I had to reinstall the app and since I couldn't find a way to take a backup, I lost all my data. Mentioned about it in #191 

**Additional context**

N/A

PS: Appreciate your effort on this app. It really is a productivity booster!

**Comment by BeatLink** [comment]
This issue would best be solved upstream by flatpak developers. Is it the font size or the font itself you wish to change?
