### ISSUE TITLE
v2.3 completely messed up gsettings and other issues

### ISSUE THREAD

**Issue by WebShapedBiz** [alainm23/planify#319]
Hi.

I've just updated the Planner to v2.3 and the following happened:

1. `gsettings` are now having two sets of keys under the `com.github.alainm23.planner` path
2. app can be run from terminal only but then badges don't work. Also, there is a very vocal terminal:
```
(com.github.alainm23.planner:32046): Gtk-CRITICAL **: 22:18:22.920: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed

(com.github.alainm23.planner:32046): Gtk-CRITICAL **: 22:18:23.004: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

** (com.github.alainm23.planner:32046): CRITICAL **: 22:18:23.055: SimpleCommand.vala:103: Couldn't launch command echo $DESKTOP_SESSION in the directory .: Failed to execute child process “echo” (Nema takve datoteke ili direktorija)

(com.github.alainm23.planner:32046): GLib-CRITICAL **: 22:18:23.055: g_child_watch_add_full: assertion 'pid > 0' failed

(com.github.alainm23.planner:32046): Gdk-CRITICAL **: 22:18:23.068: gdk_rgba_parse: assertion 'spec != NULL' failed

** (com.github.alainm23.planner:32046): CRITICAL **: 22:18:23.069: widgets_project_row_apply_color: assertion 'color != NULL' failed
```
The last line is repeated endlessly.

3. if run from the app menu the app is always running in the background without the way to make it visible, but badges are working. 
4. running from the app menu and running from the terminal produces two separate icons in plank.

I'm using Planner daily and I hope to see the next release soon :-(

Cheers.

**Comment by alainm23** [comment]
Sorry I made a mistake when I released Planner 2.3.2, I uploaded a new update yesterday afternoon fixing the bug, waiting to be reviewed.

![image](https://user-images.githubusercontent.com/33765137/80030662-22b9cf80-84ae-11ea-86c0-c127d2ceadcb.png)

**Comment by WebShapedBiz** [comment]
Thank you @alainm23

**Comment by fabianorss** [comment]
Thank you @alainm23
