### ISSUE TITLE
Planner does not start after upgrade

### ISSUE THREAD

**Issue by jfontich** [alainm23/planify#321]
**Describe the bug**
After last upgrade on elementaryOS (5.1.3), Planner does not start.

When I run com.github.alainm23.planner I get this output, and Planner starts

$ com.github.alainm23.planner

(com.github.alainm23.planner:6867): Gtk-CRITICAL **: 08:49:02.010: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed

(com.github.alainm23.planner:6867): Gtk-CRITICAL **: 08:49:02.661: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:6867): Gtk-CRITICAL **: 08:49:02.835: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:6867): Gtk-CRITICAL **: 08:49:02.835: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:6867): Gtk-CRITICAL **: 08:49:02.845: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:6867): Gtk-CRITICAL **: 08:49:02.845: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:6867): Gtk-CRITICAL **: 08:49:02.854: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:6867): Gtk-CRITICAL **: 08:49:02.854: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:6867): Gtk-CRITICAL **: 08:49:02.864: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:6867): Gtk-CRITICAL **: 08:49:02.864: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:6867): Gtk-CRITICAL **: 08:49:02.874: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:6867): Gtk-CRITICAL **: 08:49:02.874: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:6867): Gtk-CRITICAL **: 08:49:02.884: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:6867): Gtk-CRITICAL **: 08:49:02.884: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

** (com.github.alainm23.planner:6867): CRITICAL **: 08:49:02.892: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:6867): CRITICAL **: 08:49:03.275: SimpleCommand.vala:103: Couldn't launch command echo $DESKTOP_SESSION in the directory .: No s'ha pogut executar el procés fill «echo» (El fitxer o directori no existeix)

(com.github.alainm23.planner:6867): GLib-CRITICAL **: 08:49:03.275: g_child_watch_add_full: assertion 'pid > 0' failed

(com.github.alainm23.planner:6867): Gdk-CRITICAL **: 08:49:03.580: gdk_rgba_parse: assertion 'spec != NULL' failed

** (com.github.alainm23.planner:6867): CRITICAL **: 08:49:03.582: widgets_project_row_apply_color: assertion 'color != NULL' failed

(com.github.alainm23.planner:6867): Gdk-CRITICAL **: 08:49:03.592: gdk_rgba_parse: assertion 'spec != NULL' failed

** (com.github.alainm23.planner:6867): CRITICAL **: 08:49:03.593: widgets_project_row_apply_color: assertion 'color != NULL' failed

**Comment by danielpadula** [comment]
Hi everyone!

In order to add information, when planner starts, systemd-journal eat 100% of CPU usage.

Thanks!

**Comment by Thyriaen** [comment]
I just installed it for the first time - it does not open

however - i get the same errors when starting from terminal and it runs

**Comment by jfontich** [comment]
Also, all projects get duplicated
![Captura de pantalla de 2020-04-23 16-13-32](https://user-images.githubusercontent.com/64200431/80109501-da69e280-857d-11ea-8e95-50f4e6bd310f.png)

**Comment by alainm23** [comment]
The bug was fixed, wait for update 2.3.3 please.
