### ISSUE TITLE
Add option for Theme to Respect OS Wide Preferences

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#323]
The elementary standard applications and system components are currently made ready for this. It would be nice if Planner could support this as well.

As an example, the screenshot application: https://github.com/elementary/screenshot/pull/127

**Comment by alainm23** [comment]
Sure but this has to optional for the user.

**Comment by 4jNsY6fCVqZv** [comment]
What considerations does the elementary OS team have for integrating this feature into third-party applications?

**Comment by 12people** [comment]
@alainm23 Seems like the option for this will be at the OS level in the next version of elementaryOS.

**Comment by alainm23** [comment]
@12people  Yes, a service has been added in Granite that will do all the magic, so it will be a unique function for the elemental OS.

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 Are you happy about a pull request for it?

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 Are you open to a pull request here? Then I'll make one.

**Comment by isshin1** [comment]
any update on this one ? normally all gtk apps can register the theme switch done using gsetting. how far is the elementary OS in this regard ?
