### ISSUE TITLE
Planner do not open from the GUI

### ISSUE THREAD

**Issue by drom98** [alainm23/planify#324]
**Describe the bug**
After the latest update I'm unable to open Planner from the menu nor the dock. The indicator stays on but the actual windows never shows up, and if I close the app from the menu on the dock, the app continues running on background. 
If I open the app from the terminal it works fine.

**To Reproduce**
1. Open planner from the menu or from the dock.

**Expected behavior**
Window to show up.

**Desktop (please complete the following information):**
 - OS or DE: elementary OS (pantheon)
 - Version: 5.1.3

**Additional context**
I don't really know whats' causing this. The app used to work fine before the update.

**Comment by alainm23** [comment]
We have solved the bug #317, we have uploaded a update 3 days ago and we're still in revision process, be patient 🙏️.

**Comment by drom98** [comment]
Oh my bad. I'm sorry.
Glad to know that! 🙏️
