### ISSUE TITLE
Add an optional effort / time needed property to tasks

### ISSUE THREAD

**Issue by ECFE** [alainm23/planify#327]
# Feature Request Description
When managing a large set of tasks and deliverables on a tight schedule im challenged to match the available time in my calendar with the different tasks. I can write the assessed effort available in a note text. That solution is not useful for making Planner time aware and thus does not facilitate workflows in Planner centred around time management in general.

## Proposed solution
Add a task property next to "Due date" and "Reminder" where the assessed effort needed to complete a task can optionally be provided. Display this "effort needed" in a human readable format (weeks / days / hours / minutes)  bot for a maximized and a minimized task. Make the property accessible such that future Planner improvements can make use of it and thus make Planner "time aware". 

## Alternatives considered
I have considered:
- Use of alternative applications. Disregarded as Planner seems to have the better direction for accessibility, design and general improvements.
- Tracking of effort required in the note field for the task. This does not display consistently across multiple notes which makes overview tough. Furthermore it does not enable other time based aspects in Planner. 
- Use a calendar application for the Task effort aspects. This is a clunky workflow since effort is then only tracked for tasks that are "committed" to my schedule.

## Additional Context
I manage many different deliverables, i.e. 30-50 different work-streams with multiple individual sequenced tasks in each. My biggest challenge is to make sure progress all work-streams consistently on average and that I deliver key items on time for each work-stream. Currently this is addressed with heavy use of a calendar and Planner including weekly scheduled time for aligning Planner, my calendar and my free time. A perfect solution would probably require tasks with hierarchies / dependencies, a time based workflow, calendar integration and a Gantt type layout across multiple projects. A good first step, that would enable a lot of other possibilities in Planner, is to make Planner time aware, i.e. for Planner to capture how much time a given task is likely to take. This feature request aim to make this possible.

**Comment by BeatLink** [comment]
Perhaps this issue could be merged with #315 to provide planner with time tracking functionality?

**Comment by alainm23** [comment]
There are no plans to develop this feature at the moment.
