### ISSUE TITLE
Bugs in logs - Gtk-CRITICAL

### ISSUE THREAD

**Issue by salsero-coding** [alainm23/planify#329]
Hi,
First of all, I really like Planner and find it really useful.
I run Planner on Elementary OS 5.1.3 Hera with GTK 3.22.30 version.
Although Planner runs fine, I saw in logs (and in terminal if I run Planner directly) that there are quite a lot of entries suggesting problems with GTK. I paste them below:

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:28.943: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:28.991: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.001: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.004: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.006: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.008: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.008: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.014: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.016: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.016: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.018: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.020: gtk_revealer_get_reveal_child: assertion 'GTK_IS_REVEALER (revealer)' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.022: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.023: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.023: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.023: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.024: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.024: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.024: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.024: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.025: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.025: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.025: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.025: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.026: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.026: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.026: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.026: utils_get_relative_date_from_date: assertion 'date != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.027: utils_get_relative_date_from_date: assertion 'date != NULL' failed

(com.github.alainm23.planner:4655): Gdk-CRITICAL **: 15:22:29.102: gdk_rgba_parse: assertion 'spec != NULL' failed

** (com.github.alainm23.planner:4655): CRITICAL **: 15:22:29.102: widgets_project_row_apply_color: assertion 'color != NULL' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.230: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.249: gtk_list_box_row_grab_focus: assertion 'box != NULL' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.270: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.286: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.305: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.319: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.335: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.350: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.390: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.400: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.416: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.431: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.448: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.464: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.480: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.497: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.514: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.531: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.549: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.566: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.588: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.600: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.624: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.631: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.652: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.666: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.684: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.700: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.716: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.733: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.749: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.766: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.783: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.800: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.817: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.833: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.851: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:29.867: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed

(com.github.alainm23.planner:4655): Gtk-CRITICAL **: 15:22:30.923: _gtk_widget_get_preferred_size_for_size: assertion 'size >= -1' failed`

I don't know if these may be related to my personal configuration or are simply bugs in the application. Anyway, just wanted to report this so you can be aware of it.

And again, thanks for the great and really useful app.
P.

**Comment by alainm23** [comment]
The bug was fixed, please update to v2.3.3.

**Comment by tredondo** [comment]
I see lots of "Critical" warnings as well in 4.15.1. What I did was to create 4 dummy tasks, then drag #3 and #4 into #2.


<details><summary>Logs</summary>
$ flatpak run io.github.alainm23.planify
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:949: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:981: FINISHME: support more multi-planar formats with DRM modifiers

** (io.github.alainm23.planify:2): CRITICAL **: 18:42:28.897: objects_source_data_to_json: assertion 'self != NULL' failed

(io.github.alainm23.planify:2): Json-CRITICAL **: 18:42:38.388: json_object_get_string_member: assertion 'node != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 18:42:51.017: objects_project_get_inbox_section_hidded: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 18:42:51.021: objects_project_get_inbox_section_hidded: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 18:42:52.357: objects_project_get_inbox_section_hidded: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 18:42:52.361: objects_project_get_inbox_section_hidded: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 18:43:00.799: objects_project_get_inbox_section_hidded: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 18:43:00.800: objects_project_get_inbox_section_hidded: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 18:43:06.334: objects_project_get_inbox_section_hidded: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 18:43:06.336: objects_project_get_inbox_section_hidded: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 18:43:10.437: objects_project_get_inbox_section_hidded: assertion 'self != NULL' failed

** (io.github.alainm23.planify:2): CRITICAL **: 18:43:10.439: objects_project_get_inbox_section_hidded: assertion 'self != NULL' failed

(io.github.alainm23.planify:2): GLib-GObject-CRITICAL **: 18:43:17.243: ../gobject/gsignal.c:2699: instance '0x610612c594c0' has no handler with id '20170'

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.383: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.384: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.384: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.384: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.384: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.388: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.388: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.389: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.394: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.402: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.409: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.409: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.410: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.411: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.411: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.418: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.424: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.433: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.440: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.448: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.454: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.463: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.469: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.477: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.484: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.492: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.493: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.493: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.500: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.508: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.508: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.509: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.510: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.510: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.515: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.523: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.529: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.538: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.545: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.552: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.552: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.553: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.554: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.554: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.559: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.559: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.560: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.562: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.568: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.568: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.568: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.569: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.575: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.583: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.589: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.598: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.605: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.612: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.619: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.627: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.635: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.651: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.658: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.664: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.674: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.674: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.674: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.680: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.687: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.696: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.696: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.696: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.697: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.698: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.711: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.718: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-WARNING **: 18:43:18.718: (../gtk/gtkdroptargetasync.c:271):gtk_drop_target_async_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.719: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.724: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.724: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.815: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.838: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.845: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.852: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.859: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): Gtk-CRITICAL **: 18:43:18.890: gtk_drop_target_async_handle_event: assertion 'self->drop == drop' failed

(io.github.alainm23.planify:2): GLib-GObject-CRITICAL **: 18:43:19.340: ../gobject/gsignal.c:2699: instance '0x610612c594c0' has no handler with id '24291'

</details>
