### ISSUE TITLE
The project progress indicator should not be clickable (if it is intended that there is no functionality behind it)

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#330]
Right now it looks like a clickable button, but it does not allow any action.

![Screenshot](https://user-images.githubusercontent.com/46536067/80309909-6753ac80-87c7-11ea-89fc-96e5913cde35.png)

![Screenshot](https://user-images.githubusercontent.com/46536067/80309930-87836b80-87c7-11ea-9604-932450238999.png)

At this point a big thank you for Planner 2.3! I am really thankful that I can use this app and thank you very much for the time you take for improvements and implementing new features!

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for working on it!
I was just wondering if a simplification would be nice. Or whether you have further plans with it, which are not yet visible.

Impulse: The tooltip still shows the percentage.
The function behind the button is removed and the button becomes an icon instead, as in the sidebar.
This is because the new function behind the button adds a green progress indicator, which is just a newly introduced and additional form of progress indicator for the same project.It has no additional information for me in the current state of implementation.
Also, the green color has nothing to do with the color of the selected project, which is also irritating, because then there are different colors for one and the same progress. Not counting the monochrome button color here.
These are my feelings about it, when I look at the improvement for the first time.
I am curious about your perspective on it: Why you changed it the way you changed it.
And I am also curious about how other users feel about it.

**Comment by 4jNsY6fCVqZv** [comment]
![Screenshot](https://user-images.githubusercontent.com/46536067/80867858-06741a80-8c86-11ea-8eea-28d4eb19647e.png)

Do you have any other development plans with this view?

**Comment by alainm23** [comment]
Yes, I have.

**Comment by 4jNsY6fCVqZv** [comment]
Wouldn't it then make sense to label the tool button with a broader term?

But for me this would currently trigger a design conflict:

In the sidebar, the progress indicator should actually also get a tooltip.

But if you plan more functionality behind the tool button in the project view than just translating the project progress in percent, this tool button would basically need a different metaphor and a new tooltip that can also reflect the reality of the extended functionality.

Otherwise you either have two identical icon metaphors with different tooltips (in the sidebar and in the project view). Or the metaphor in the project view will no longer reflect the more complex functionality behind the tool button, as there is more planned for the future than just showing the progress of completed tasks.

How do you feel about this?
