### ISSUE TITLE
Planner doesn't sync with my todoist account.

### ISSUE THREAD

**Issue by PavelNikov** [alainm23/planify#334]
**Describe the bug**
* When I add something to planner it sometimes syncs to my todoist account sometimes it doesnt.
* When I add something to todoist it always shows up in planner.

**System**
* Ubuntu/Gnome 20.04
* Same thing happened on 19.10

**Thanks a lot for the app. When it works I absolutely love it**

**Comment by PavelNikov** [comment]
Last commit solved the issue. Thanks a lot Alain!

**Comment by alainm23** [comment]
You're welcome, I am aware that Planner's synchronization is not the best yet, I am working on it.

**Comment by kden416** [comment]
Same problem, i can add or modify jobs in project created by todoist, works well, but projects and jobs created by planner not sync to todoist
