### ISSUE TITLE
Question: Overdue tasks are not counted as Today tasks in the Dock, right?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#335]
I have four old tasks from the previous day that appear as overdue in the Today view.  Plus one task that was also originally scheduled for today and is also shown in the Today view. The sidebar counts the 4 tasks under Today with a red marked badge and a black marked badge for the original task for today.
However, the elementary OS Dock only shows a "1" in the badge. This motivated me to ask my question.
I use version 2.3.3 from the AppCenter.

**Comment by 4jNsY6fCVqZv** [comment]
Thanks a lot!

**Comment by alainm23** [comment]
You're welcome :).
