### ISSUE TITLE
Font size too small!

### ISSUE THREAD

**Issue by CreadorSW** [alainm23/planify#336]
**Describe the missing feature**
No option available to increase font size

**Describe the solution you'd like**
I'd like so much an option to increase the size of the font. My eyes are suffering and can't enjoy this application as I would like.

**Describe alternatives you've considered**
An option in contextual menu
An option in configuration settings 

**Additional context**
Here you can see how the font from the application is significantly smaller than the system one
![Captura de pantalla de 2020-04-28 11-53-44](https://user-images.githubusercontent.com/17933209/80513181-0e198380-8955-11ea-9ff1-6e796e2cfd41.png)

**Comment by alainm23** [comment]
I'm not sure why this happens, I'm using the default font size that elementary OS uses.

**Comment by CreadorSW** [comment]
Thank you very much for your response @alainm23, and thank you for creating Planner <3. I'm using big size, maybe that explains the difference, but the point is that the size in Planner remains uncomfortable to my eyes 😢️. Maybe Planner doesn’t fallow the system font size.

**Comment by omega3** [comment]
I also vote for option in settings to change font size. My sight is poor. Besides I use it on KDE Plasma. An option for font size would make planner independent from desktop environment settings.

**Comment by omega3** [comment]
Can someone tell me where is a configuration file? 
I can't find it in my /home directory. 
Would be great if I could change font size at least in configuration file. I desperately need to do it.

**Comment by ghost** [comment]
Any process on this? Even a config file should work.

**Comment by omega3** [comment]
@alainm23
Can you please comment on this issue? It seems as if you closed the issue without processing. I updated and I don't see any font size configuration option. For people with weak sight it is really critical issue.

**Comment by tylrbvn** [comment]
+1 on this, I have started using Planner today and immediately found myself looking for a way to make the font bigger but it seems it is currently impossible

**Comment by CreadorSW** [comment]
@alainm23 we love you for creating Planner but don't forget us. Would you drop here some help? I'm currently using todoist app instead of planner because of size font :(

**Comment by alainm23** [comment]
Hi guys, sorry for not giving much attention to this issue, I'm investigating how to change the font size without affecting the design considerably, please be patient.

**Comment by BeatLink** [comment]
Could this be closed in favor of https://github.com/alainm23/planner/issues/318?

**Comment by omega3** [comment]
Looks like these are different issues. The author of #318 doesn't mention font size.

> Describe the solution you'd like
> An easy option to choose a custom font from the fonts installed on your system.

As far as I understand it, it concerns font type (Arial, Noto Sans, etc.)

**Comment by BeatLink** [comment]
ahh

**Comment by alainm23** [comment]
I hope to solve this problem with this new feature.
![image](https://user-images.githubusercontent.com/33765137/97013715-fb9c9300-150e-11eb-97ff-232fb3e90528.png)

**Comment by alainm23** [comment]
Please upgrade to 2.5.6 and let me know if this new feature fixes the bug.

**Comment by omega3** [comment]
Works for me very well. Thank you very much.

Although Preferences window still has small font, different from other areas of Planner.
https://i.imgur.com/ksgvtwT.png

By the way, this double view / double layer of Preferences window and its transparency is by design or is it a bug?
