### ISSUE TITLE
Is there a way to run this on mac OS?

### ISSUE THREAD

**Issue by safareli** [alainm23/planify#338]

**Comment by romixch** [comment]
No. Or at least not yet. I tried to compile it once. But couldn't do it without errors.

**Comment by safareli** [comment]
Looking forward to it 🤩

**Comment by alainm23** [comment]
This could be possible removing `libevolution` as a dependency, but unfortunately I don't own a Mac for testing :(.

**Comment by BeatLink** [comment]
Any chance you could reopen this and flag it as help wanted? You could mention that we need alpha/beta testers with macs to test it

**Comment by alainm23** [comment]
Yes it could but there are technologies that could not be compiled in macOS for example calendar events.

**Comment by BeatLink** [comment]
Ahh okay

**Comment by Korne127** [comment]
Hey, searching for a macOS to do list app and this looks promising. I think it would still make sense to reopen it and marked as help wanted. I might be able to help at some point in the future. Even if not everything can be ported, it would still be nice to have a version (and in the long-term, maybe that code could be made platform-independent / with code for each platform).

**Comment by rollecode** [comment]
I use Linux and Mac. It would be great to be able to use this on a Mac as well.

**Comment by woj-tek** [comment]
> Any chance you could reopen this and flag it as help wanted?

bumping this old question - would it be possible? :)

**Comment by juanrloaiza** [comment]
Bumping it too! I love Planify on my Fedora system, but I also use macOS and it would be great if this were available there too.
