### ISSUE TITLE
Render markdown for github issue body

### ISSUE THREAD

**Issue by harisvsulaiman** [alainm23/planify#34]
![image](https://user-images.githubusercontent.com/29329325/51070662-043e1500-166b-11e9-8ce1-3cb683e849df.png)

**Comment by alainm23** [comment]
For this problem we have two possible solutions:
1️⃣ Create an algorithm to remove all Markdown format and convert it to text only
2️⃣ Support to Markdown
3️⃣ Remove support to Github Issues (😎)

**Comment by harisvsulaiman** [comment]
@alainm23 I like the support markdown option 😎
 Maybe we could render a webview with a markdown to html/css lib injected to the frame

**Comment by alainm23** [comment]
## Starting to work on this feature
![markdown](https://user-images.githubusercontent.com/33765137/51938852-1e525400-23dc-11e9-8205-596c81206fa0.png)
![markdown 2](https://user-images.githubusercontent.com/33765137/51938856-214d4480-23dc-11e9-82d7-5516d7c65f4a.png)

**Comment by alainm23** [comment]
I feel that the user experience is not the best, it's a good idea to show the markdown view in a Dialog?

**Comment by harisvsulaiman** [comment]
@alainm23 i feel that its best not to write any content in a dialog.
I Haven't looked at the code but i assume you are rendering markdown in a webview.

**Comment by alainm23** [comment]
Yes, I am using a WebView with a style basic in Github.
