### ISSUE TITLE
UI Bug - excessive empty space when selecting project color 

### ISSUE THREAD

**Issue by ECFE** [alainm23/planify#340]
**Bug description**
When setting the project color by clicking the color drop down box, 3/4 of the resulting drop down box is empty (top part), the first free color (red) is then shown 3/4'ths down the list.  

**To Reproduce**
1. Open Planner
2. Click on "Add List"
3. Select "Add Project"
4. Click on the red color icon
5. Observe excessive empty space at the top of the list 

**Expected behavior**
I would expect the drop down list to be tight, i.e. with no empty space. 

**Screenshots**
Not possible to screenshot as that deactivates the dropdown box which then closes.

**Desktop (please complete the following information):**
 - OS or DE: Elementary OS 5.1.4 Hera
 - Planner version 2.3.5

**Comment by 4jNsY6fCVqZv** [comment]
By the way, this is not observable for me when I want to change the color of an already existing project.

**Comment by alainm23** [comment]
Fixed in the master.
