### ISSUE TITLE
UI bug - Default size of "General" window is too small

### ISSUE THREAD

**Issue by ECFE** [alainm23/planify#341]
**Default size of General window hides setting**
When opening the "General" setting s window the default window size hides the Danger zone reset all setting without the corresponding window having a scrollbar. 

**To Reproduce**
1. Open Planner
2. Click on the gear icon in the lower left corner
3. Click General
4. Observe the "General" window hiding the last setting without the window showing a scrollbar. This setting is only accessible by window resizing.

**Expected behavior**
I would expect one of two things:
1. The window opens large enough to show all settings in full
2. The window opens as it does currently but displays a scrollbar on the right hand side

**Screenshots**
![image](https://user-images.githubusercontent.com/44121370/80861689-6a8be400-8c70-11ea-810a-5da28b1ead5a.png)

**Desktop (please complete the following information):**
 - Elementary OS
 - Version 5.1.4 Hera

**Comment by 4jNsY6fCVqZv** [comment]
> The window opens large enough to show all settings in full

I wonder how this could be solved in combination with the other settings in preferences.
For example in "Labels", where the number of entries depends on the user. The same applies to "Homepage", where the number of projects will vary. And "Support & Credits" may also continue to grow. So there is not always a fixed number of entries with which the window size can correlate.

Maybe a larger default window size could be useful here to display at least the entries in "General", "Keyboard Shortcuts" and "Todoist" without scrolling. @alainm23?

> The window opens as it does currently but displays a scrollbar on the right hand side

I don't know whether there should be no scrollbar visible here for design reasons. @alainm23?
In the Upcoming view there is such a visible scrollbar.

**Comment by 4jNsY6fCVqZv** [comment]
May I ask exactly what you changed to solve the issue?
