### ISSUE TITLE
Change name of the "Add List" button to reflect the underlying options

### ISSUE THREAD

**Issue by ECFE** [alainm23/planify#342]
**"Add List" does not really correspond to the underlying options it facilitates**
The "Add List" button is now named "Add List", but is used to add: Projects or Folders. Folders do not really have a list structure outside organizing projects, and projects have more functionality than just lists. 

**To Reproduce**
1. Open Planner
2. Look at lower left corner to find "Add List"
3. Click "Add List" and observe options available: Project or Folder 

**Expected behavior**
I would expect "Add List" to just add a list. Given it now adds both projects and folders I think renaming it to "Add Project" better reflects the actual functionality. Currently we have three words: List, Project and Folder to describe two different entities: Projects and Folders. I understand that naming it "Add Project" does not expose the possibility to add "Folders" however, everyone will need to add a project and in doing so will be exposed to the fact that you can also add folders. 

**Screenshots**
![image](https://user-images.githubusercontent.com/44121370/80861981-023e0200-8c72-11ea-8e4d-cafe3ae80e8a.png)
![image](https://user-images.githubusercontent.com/44121370/80861992-12ee7800-8c72-11ea-8fe5-0f78fb768ef7.png)

**Desktop (please complete the following information):**
 - Elementary OS
 - 5.1.4 Hera

**Comment by 4jNsY6fCVqZv** [comment]
Related to https://github.com/alainm23/planner/issues/281
