### ISSUE TITLE
Does it need two different icons to display folders?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#343]
![Screenshot](https://user-images.githubusercontent.com/46536067/80868123-1260dc00-8c88-11ea-968d-7f74b21e24da.png)
![Screenshot](https://user-images.githubusercontent.com/46536067/80868136-1d1b7100-8c88-11ea-8566-2e432dd57e90.png)

**Comment by alainm23** [comment]
It is not necessary but visually it looks more coherent. Using the original folder icon would not be consistent just to the project icon.
