### ISSUE TITLE
Window size grows larger every time the app is launched

### ISSUE THREAD

**Issue by neikeq** [alainm23/planify#344]
**Describe the bug**
Every time the app is launched the window size is a bit larger than it was the last time the app was running.

**To Reproduce**
1. Close the app
2. Launch the app again
3. Window size is larger

**Expected behavior**
The window size should be the same as it was when the app was closed.

**Screenshots**
![Peek 2020-05-02 20-55](https://user-images.githubusercontent.com/7718100/80873242-646d2600-8cb7-11ea-95d0-3eaa9b79440c.gif)

**Desktop (please complete the following information):**
 - OS or DE: Ubuntu 20.04 64-bit, Gnome 3.36.1
 - Planner Version: 2.3.5 (flatpak)

**Comment by alainm23** [comment]
Is there someone else who has been able to reproduce this bug?

**Comment by stormchaser3000** [comment]
yes, this happens on every non-elementary OS distro, even when using the flatpak.

**Comment by BeatLink** [comment]
I could not replicate this on the latest planner version 2.6.9, Flathub running on Linux Mint Cinnamon 20.1. Please update planner and confirm if this issue still exists

**Comment by neikeq** [comment]
I can still reproduce it with Planner 2.6.9. I noticed it doesn't happen when configured to use the system window decoration, so I will be using that.

**Comment by dmlls** [comment]
I'm using Arch and Planner is having the same behaviour as commented by @neikeq.

But I'm actually thinking... shouldn't it be the default to use the system window decoration? It makes more sense to me since Planner then integrates better with the rest of the windows and the system appearance overall...

**Comment by rbribeiro** [comment]
Hey guys, just to say that I've experienced the same bug in eOS 6.1 and Planner 2.7. If you close the app and reopen it, the window size increases by a factor. It is a pretty annoying bug, I must say.
