### ISSUE TITLE
Add support for Responsive UI using Libhandy

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#345]
To make Planner's UI responsive to screen size.
Maybe it will also help to solve open issues like this one https://github.com/alainm23/planner/issues/178#issuecomment-579171694?
And it allows Planner to run on a Librem5 or PinePhone or other mobile Linux operating systems in the future.

**Comment by theotheroracle** [comment]
i've had issues like #178 for a while now, i'm using the flatpak version, and i think it would be really beneficial
