### ISSUE TITLE
Duplicate task

### ISSUE THREAD

**Issue by Theodin** [alainm23/planify#346]
While setting up my Todoist / Planner app, I had some entries I wanted to copy from one list to another which I couldnt find a way to do. Is this something that could be added?

**Comment by alainm23** [comment]
Probably what you need is the 'Duplicate Task' option, right?

**Comment by Theodin** [comment]
Exactly. Does it already exist and I didnt find it?

**Comment by alainm23** [comment]
Available in the next release.

**Comment by alainm23** [comment]
Available in the master.
