### ISSUE TITLE
Slim Mode: Collapse the sidebar

### ISSUE THREAD

**Issue by wada3n** [alainm23/planify#349]
First of all, I would like to thank you for this amazing work
Planner I think is one of the most important and promising programs in the Linux world during the past years.

**Describe the solution you'd like**
I'd like to add the feature to collapse the sidebar to focus on the task and get more room on your screen.

**Describe alternatives you've considered**
This feature is found in a similar app in Mac OS called things
This is a Gif illustrates the idea.
![Peek 2020-05-04 01-12](https://user-images.githubusercontent.com/13304792/80929631-83e27c80-8da5-11ea-8520-b792cfcfea4a.gif)

**Comment by raproenca** [comment]
Yes, yes please!

I agree with the propposal. I even dare to expand (no pun intended) the feature request to include a "partial collapse" of the sidebar, where only the icons would be visible. The attached gif better explains what I mean.

![ms-todo-collapsible-sidebar](https://user-images.githubusercontent.com/23019356/81992016-f7438400-9618-11ea-9356-42478b7aa2e0.gif)

P.S.: The app in the gif is Microsoft Todo, the web version running within the app Ao (Linux).

I absolutely love Microsoft Todo and Things! There nothing wrong on borrowing some ideas from them ;-)

**Comment by alainm23** [comment]
It's an amazing feature, I hope I can implement it in the future.

**Comment by alainm23** [comment]
https://user-images.githubusercontent.com/33765137/138869105-5b629680-1b76-4d97-961f-e991ba5beaf2.mp4
