### ISSUE TITLE
UI improvements: Round icon for checklist

### ISSUE THREAD

**Issue by wada3n** [alainm23/planify#350]
Hi,
I think it is better to put a different icon for checklist, Maybe round like this:
![Selection_001](https://user-images.githubusercontent.com/13304792/80929791-ac1eab00-8da6-11ea-8eab-6360f82a7115.png)
Thank you again for this wonderful app.

By the way, why don't add an e.g .ini file to save the window dimensions, every time the program opens the window resizes?

**Comment by alainm23** [comment]
Thank you very much for your comments.

> I think it is better to put a different icon for checklist, Maybe round like this:

Cassidy James Blaede has an explanation #68

> By the way, why don't add an e.g .ini file to save the window dimensions, every time the program opens the window resizes?

Esto es un poco extraño, Planner siempre guarda el tamaño y la posición antes de cerrar.
