### ISSUE TITLE
Label view

### ISSUE THREAD

**Issue by omega3** [alainm23/planify#351]
I miss label / tag view where I can see all tasks and notes that has specific label. And within this view ability to move them up and down in order to prioritize. It would greatly enhance the management of tasks.  

Use-case: I have tasks from different projects and I need to prioritize them and see as a list but not necessarily put them into today or whatever day.

Sometimes Today view is not enough. Maybe people have different strategies of thinking about their tasks. Sometimes for me giving for example label: soon doesn't mean today or tomorrow or any other specific day but when I have free time to do this particular task. So calendar is the only way of thinking about tasking / prioritizing.

**Comment by alainm23** [comment]
Thank you very much for your comment.
This feature is already available.

Open **Quick Find** > **Enter the name of your label**.

![image](https://user-images.githubusercontent.com/33765137/80977704-b367a800-8dea-11ea-9c89-da9640d4cf78.png)

**Comment by omega3** [comment]
Yes. No offense, but this is terrible way of implementing it. At least a panel where all labels are displayed and it is possible to click on them would be a lot more convenient.

**Comment by omega3** [comment]
Maybe you can rethink it again.

It would be great to be able to see click on label panel to filter all tasks from a specific label and see them in separate view as to-do, in progress, done.

Why? For example you have different projects but in many of them you have task that you label: shopping. When you go shopping you want to have a quick view what to buy and even prioritize them because you may need to buy them in different shops so not all may be possible today.
