### ISSUE TITLE
Upcoming view: show only dates which have at least one task

### ISSUE THREAD

**Issue by 0xgirish** [alainm23/planify#352]
I am not a heavy user of todoist / planner so my upcoming view look like this.

![feature_request](https://user-images.githubusercontent.com/45126881/81044105-4b3fc180-8ed1-11ea-84a2-3c495daf6add.jpg)

As you can see above 4 dates are redundant and doesn't give much information.
It would be good if only dates which have at least one task are shown to upcoming view.

**Describe the solution you'd like**
Show only dates which have at least one task in the upcoming view.
**edit:** When one has continuous free days, these days can be squashed into one listbox which contains information about free days.

**Thanks for such an amazing application**

**Comment by 4jNsY6fCVqZv** [comment]
Exciting idea! And yes, it makes a lot of sense for my current personal usage, too. Why should I see upcoming days that have no tasks and appointments? 

I am just thinking about the display of stops on a bus or tram. I always see the next stations and not all stations at once. The same applies to the connections that are displayed while waiting at stops. It is always the next x connections.
This is of course a question of how much should be displayed at once. Or, for example, in the case of Planner, which can be made accessible by scrolling or a "load/display more" button. However, there is always content and no non-content that is displayed.
I don't know if this is comparable to the idea of a project management tool. This is just my first impulse.

@zkmrgirish Could you imagine to create a design for it?

However, I can imagine that the current design of the Upcoming View can help me to see where I might have a lot of free time in the next weeks and months and therefore maybe specifically put new tasks on these free spaces.

**Comment by 0xgirish** [comment]
@4jNsY6fCVqZv
`However, I can imagine that the current design of the Upcoming View can help me to see where I might have a lot of free time in the next weeks and months and therefore maybe specifically put new tasks on these free spaces.`

Current design surely help to see where one might have free time. But When we have continuous free days, current design takes a lot of space in the upcoming view.
One of the alternative is to squash these free days into one listbox. Something like this might help.

06 - 09 May, No Tasks
---------------------------------------------------

10 Sunday, May
---------------------------------------------------
- [ ] Task1
- [ ] Task 2

**Comment by alainm23** [comment]
Thanks for commenting and using Planner. It's an interesting observation but your Upcoming view could be better seen with some calendar events. Another thing to keep in mind is that DnD is coming to the Upcoming view and being able to drag a task to any date is an amazing feature.


![Upcoming DnD](https://user-images.githubusercontent.com/33765137/82720417-f80f9200-9c78-11ea-9897-50f64e525d44.gif)

**Comment by 0xgirish** [comment]
That's amazing, I also sometimes extend deadlines of my tasks by 2-3 days. This feature can be really useful.

Thanks for your hard-work 🙂

**Comment by 4jNsY6fCVqZv** [comment]
Hi Alain, thanks for working on this!
If you write that the Upcoming View works better with a few calendar entries, I wonder if it is basically necessary to have such entries to make the view work for me. If it only shows what is there, the problem from my perspective no longer exists. How do you feel about this idea?

**Comment by 4jNsY6fCVqZv** [comment]
Thanks, looks good with drag and drop! And solves https://github.com/alainm23/planner/issues/161#issuecomment-622963543 as well.

I am a little irritated that this issue has already been closed. The issue title says "show only dates which have at least one task". Have you also improved something in this matter?
I still don't understand how drag and drop is related to improving the view itself. You write that it is helpful if I have some calendar entries. But what if I don't use virtual calendars at all and therefore can't include them in the view?
