### ISSUE TITLE
Black border around window in tiling window managers

### ISSUE THREAD

**Issue by daaniiieel** [alainm23/planify#353]
**Describe the bug**
A black box appears around the window on i3-wm and i3-gaps

**To Reproduce**
Install the application and open it in a tiling window manager

**Expected behavior**
Looks normally

**Screenshot**
![Screenshot_2020-05-05_15-53-45](https://user-images.githubusercontent.com/41679054/81074484-59014100-8ee9-11ea-930d-6fb43fe3c5e6.png)

**Desktop (please complete the following information):**
 - OS or DE: Arch Linux + i3-gaps
 - Version git (2.3.4.r0)

**Additional context**
Does happen if I use a compositor. Doesn't happen on GNOME, XFCE or KDE

**Comment by alainm23** [comment]
Thanks for commenting, we have already tracked the bug. I'll close because it's duplicate #268
