### ISSUE TITLE
Show the count of Checklist on the task

### ISSUE THREAD

**Issue by linbyndvk** [alainm23/planify#354]
**Is your feature request related to a problem? Please describe.**
The issue that I have is on the task view in a project. We can see the Icon for the checklist. However I do not know how many Items I have on the checklist and how many are completed and ticketed off. 

**Describe the solution you'd like**
What I would like to see is that when a task is created and a checklist is added. In the task view, next to the checklist icon I should be able to see the count of checklist with a number of remaining points in the check list. If this could be considered in the progress of the project that would be great. I come from the perspective of Emacs orgmode user. In it you have an option to have the indicator to show how many points in a checklist are completed and remaining. 

For an example if a task contains a checklist of 5 items that count could show [0/5] completed and as the user progresses on the task and checks of the items in the checklist the count should reflect the change. 

`* TODO Organize party [2/4]
  - [-] call people [1/3]
    - [ ] Peter
    - [X] Sarah
    - [ ] Sam
  - [X] order food
  - [ ] think about what music to play
  - [X] talk to the neighbors`

**Describe alternatives you've considered**
Emacs - orgmode has this concept of showing a summary of checklist and the number of items completed in a checklist.

**Comment by raproenca** [comment]
I think the "productivity/progress disk" icon would be great here - the same we already have for projects, but whithin the tasks that has subitens/checklists.
