### ISSUE TITLE
Unable to add Emoji's to labels

### ISSUE THREAD

**Issue by linbyndvk** [alainm23/planify#355]
**Describe the bug**
Unable to add emoji to a label that is already created.If you edit a label you will not be able to add emoji's through ideogram or even copy and paste it. However during the creation of the label emoji can be added.

**To Reproduce**
1. Go to the settings panel
2. Add a new label with out an emoji.
3. close the label section.
4. Go back to label Section and edit the label
5. Try to add an emoji. ( This does not happen)

**Expected behavior**
When you add a new label without an emoji and later when you get to edit the label you should be able to insert an emoji. At the moment you are able to add the emoji only during the creation of the label.

**Screenshots**
![newlabel](https://user-images.githubusercontent.com/58896420/81127782-fea1c800-8f5c-11ea-91f1-fb672260f476.png)

**Desktop (please complete the following information):**
 - Elementary os 5.1.4 Hera

**Comment by 4jNsY6fCVqZv** [comment]
For me it works with Planner 2.3.5 from the AppCenter without any problems when I select "Insert Emoji" from the context menu.

What does not work, however: I have also installed Ideogram from Cassidy. When I try to insert the emoji while editing using the Ideogram app's shortcut Super+E, nothing happens. If I try Super+E while creating the label, it works fine.

Additional observation: I don't have to leave the label view for this, as described above in step 3. All I have to do is confirm the creation of the new label with Enter. After that it will not work with Super+E when editing.

It looks to me as if the input field loses its focus the moment I use the key combination.
