### ISSUE TITLE
Switching language stops editing

### ISSUE THREAD

**Issue by OssNass** [alainm23/planify#356]
**Describe the bug:**
When I try to switch the language when writing either a main task, description or a sub task the editing mode stops

**To Reproduce:**
Steps to reproduce the behaviour::
1. When editing a task or description or subtask
2. Change the keyboard layout

**Expected behaviour:**
The editing continues until I am done

**Desktop:**
 - Elementary OS Hera 5.1.4
 - Planner 2.3.5

**Comment by alainm23** [comment]
Sorry, I was unable to reproduce the bug. But reading its description is probably not a Planner bug, Maybe it's [Gala's](https://github.com/elementary/gala) unexpected behavior.

**Comment by azchatlanin** [comment]
Ubuntu 18.04 or 20.04
**Describe the bug**:
When I try to switch the language when writing either a main task, description or a sub task the editing mode stops

![Peek 2020-07-09 12-00](https://user-images.githubusercontent.com/21025345/87020205-34249500-c1dc-11ea-862e-fc40435d96af.gif)
