### ISSUE TITLE
Can't drag and drop in Today view

### ISSUE THREAD

**Issue by omega3** [alainm23/planify#357]
Can't drag and drop in Today view.

I don't know if it is a bug or a feature but it makes prioritizing for Today impossible. 

Affects:
elementary-planner-git 2.3.4.r0.gdba6c85d-1
https://aur.archlinux.org/packages/elementary-planner-git

**Comment by 4jNsY6fCVqZv** [comment]
Related to https://github.com/alainm23/planner/issues/161

**Comment by 4jNsY6fCVqZv** [comment]
Related to https://github.com/alainm23/planner/issues/161#issuecomment-622964333?
Or does your issue bring in another quality?

**Comment by omega3** [comment]
I am not sure what the user 4jNsY6fCVqZv thought by this: 

> In the Today view it is not possible to drag and drop a task. What already works by drag and drop, however, is to move any task from a project **via the sidebar into the Today view**, thereby assigning it a due date for the current day.
or 

> In the Today view it is not possible to drag and drop a task **to the first position in the list**

My intention is to be able to prioritize task that are in Today by moving them up and down (via drag and drop). Considering there might be plenty small tasks to do today, like 20 or so, it would be helpful to somehow put them in order.  Just putting one task at the top of the list is not enough.
