### ISSUE TITLE
Idle cpu usage around 6%

### ISSUE THREAD

**Issue by ni-ka** [alainm23/planify#361]
Hi,

Am running planner on manjaro linux kernel 5.6.11-1-MANJARO, gnome 3.36.2 on X11, with dark blue theme. Planner constantly uses around 6% of CPU.

Cheers,

Nils

**Comment by Julioevm** [comment]
I've also noticed planner being heavy on the cpu while idling.

**Comment by ni-ka** [comment]
I've tried to profile the application with sysprof but probably did not use it properly. However if I comment out database service it seems to go down quite a bit (6% to 1.9%).

**Comment by alainm23** [comment]
I made some modifications to the database and it seems that the performance improved a lot (0 - 2% CPU) Please check it.

**Comment by ni-ka** [comment]
@alainm23 Unfortunately its still giving me the same idle cpu load. it may be due to some things happening when there are elements loaded / displayed

**Comment by rixx** [comment]
Can confirm, only for me it's even worse: Running Planner on Arch Linux with the current AUR build, it idles at 15-25% CPU usage, which is quite surprising. This is on current Arch, with i3 as window manager (both with and without compositor).

**Comment by Schykle** [comment]
I'm seeing less than 1% CPU usage on my desktop with Planner. I have both local and synced projects. Currently, Planner uses 0.2%-0.3% on average on my desktop and about 1%-1.2% on my laptop. This is on elementary OS 5.1.7 running kernel 5.4 at the moment. Both @rixx and @ni-ka are using Arch/Arch-based. Perhaps there's something in particular to worry about there? It might also be worth noting that CPU percentages are of a whole, and thus dependent on the hardware as well. More data could be useful.

**Comment by BeatLink** [comment]
Closing in favour of #569 as they seem to be related. Feel free to head over to that issue and give feedback
