### ISSUE TITLE
Light theme checklist marks are too light.

### ISSUE THREAD

**Issue by Julioevm** [alainm23/planify#364]
**Describe the bug**
Light theme checklist marks are too light. Making it hard to see. I suspect these are the dark theme check marks that are incorrectly being used in the light theme as well.

![image](https://user-images.githubusercontent.com/38758281/81670005-4df96400-9447-11ea-8438-4cb95cbff11b.png)

Dark theme for comparison:

![image](https://user-images.githubusercontent.com/38758281/81670079-610c3400-9447-11ea-99b1-becc1e992688.png)

**Expected behavior**
The check marks should be dark, to contrast properly with the background.

**Desktop (please complete the following information):**
 - OS or DE: Elementary Os
 - Version 3.2.5

**Additional context**

**Comment by 4jNsY6fCVqZv** [comment]
https://github.com/alainm23/planner/issues/347

**Comment by Julioevm** [comment]
I searched but didn't find a similar issue, oh well. I'll close this issue.
