### ISSUE TITLE
Window Re-size Does Not Re-size the App

### ISSUE THREAD

**Issue by gojo-limitless** [alainm23/planify#366]
**Describe the bug**
Normally, one would expect the window to be re-sized and the app to re-size accordingly when a user does that.

But, it looks like Planner (v2.3.5) needs a specific minimum screen space without any re-sizing capability in this case.

**To Reproduce**
Just try to resize the planner app on GNOME .

**Expected behavior**
The app should just re-size without cutting the contents.

**Screenshots**
https://i.imgur.com/1rwBr3L.png

**Desktop (please complete the following information):**
 - OS or DE: Pop!_OS 20.04 (GNOME 3.36)

**Additional context**

**Comment by BeatLink** [comment]
The latest version of planner has a minimum window size, as well as scrolling functionality to allow content to be navigated, even with a small window or device screen size. Is this bug resolved?

**Comment by BeatLink** [comment]
I will close this issue for now. If the issue still exists on the latest planner version, feel free to reply to this issue and I will reopen
