### ISSUE TITLE
Support using tags and labels in quick-add (ex today, @label1, #my-project, and p1 for priority)

### ISSUE THREAD

**Issue by ni-ka** [alainm23/planify#367]
**Is your feature request related to a problem? Please describe.**
When I use the todoist web app, I can directly add a task to tomorrow by using "Call Amanda tomorrow #my-project". I can also assign to a project without using the mouse to choose a project

**Describe the solution you'd like**
It would be great if tags could be assigned rather than interpreted as part of the task title, to mirror the todoist web app behavior. Ideally it could offer autocomplete, but at first it is not necessary. It should support scheduling (today, tomorrow), tags @, labels # and priorities.

**Describe alternatives you've considered**

**Additional context**

**Comment by benmordecai** [comment]
Its been a long time since this has been looked at. Are there plans to put todoist style incline scheduling, #projects, @tags, and !!1 priorities?

**Comment by alainm23** [comment]
I have a small preview of this feature
https://github.com/user-attachments/assets/603675ef-a77e-4167-acae-5e5a1927a952

**Comment by alainm23** [comment]
I have a small preview of this feature

https://github.com/user-attachments/assets/7ea3bcdc-9dc7-44df-b5e0-0f4796507cf9

**Comment by benmordecai** [comment]
Looks perfect!
