### ISSUE TITLE
Align project hierarchy with todoist

### ISSUE THREAD

**Issue by ruffson** [alainm23/planify#371]
**Is your feature request related to a problem? Please describe.**
There seems to be a major misalignment with project organization in planner and todoist:

In planner, the areas are not synced up to todoist and the todoist way, which is structure projects in a hierarchy under parent projects is not synced back to planner (at least the structure is not).

So the two clash and result in a inconsistent state on both sides.

**Describe the solution you'd like**
I really like the area metaphor but to make it work better with todoist I would like to at least have the optin to additionally have project hierachies like in todoist.

**Describe alternatives you've considered**
Alternative would be to sync areas up to todoist, but since that is not supported by the service that will not work. Another way is labels, but these usually serve a different purpose (context, location, etc.).

**Additional context**
-

Substitute **areas** with **folders**. I'll leave it as area to differentiate from todoist project folders (which are just projects with sub-projects)

**Comment by thomasaull** [comment]
Planner is such an awesome tool, the fact that it doesn't sync the projects structure well with Todoist is basically the only thing holding me back from using it.

**Comment by ruffson** [comment]
> Planner is such an awesome tool, the fact that it doesn't sync the projects structure well with Todoist is basically the only thing holding me back from using it.

Same. I even made a Todoist premium subscription just because of Planner before I found out that they really don't work together well.

**Comment by thomasaull** [comment]
@alainm23 Do you have plans to implement this feature? Also you should consider activating monetization in the elementary App Center, I'm pretty sure a lot of people would be very happy to pay for planner :)

**Comment by DanielRios549** [comment]
I would like this feature as well

**Comment by BeatLink** [comment]
Closing in favour of the above mentioned discussion. Please feel free to head to that issue and give your input.

**Comment by alainm23** [comment]
@thomasaull Yes, I'm working on this feature right now and in sync with Todoist.
![image](https://user-images.githubusercontent.com/33765137/102811777-ebc8f000-4393-11eb-97d2-0f7281fe7ff2.png)

I would like to activate the monetization in AppCenter but unfortunately it is not yet available in my Country (Perú) 😭️😭️😭️

**Comment by BeatLink** [comment]
Awesome!
