### ISSUE TITLE
Adding Attachments To Task note.

### ISSUE THREAD

**Issue by wada3n** [alainm23/planify#375]
Hi,

**Describe the solution you'd like**
I think adding attachments in a task note will make things a lot easier.
Sometimes tasks relate to files, and it will be very useful to attach a file or image, and when you click on it, it opens with the default application in the OS.

**Describe alternatives you've considered**
Attachments can be added via an icon, or by drag and drop within the task.

**Additional context**
For Todoist, tasks can be synced with attachments only as links. These links are related to the file on the computer, and the file is not uploaded, of course.
Or it can be set a condition that the Attachments cannot be simply synchronized.

**Comment by usersaurus** [comment]
+1 to this feature. Adding the ability to paste images or any kind of file to a task description will add so much value to the tool.

**Comment by BeatLink** [comment]
Closing in favor of #88
