### ISSUE TITLE
Show deadlines in sidebar

### ISSUE THREAD

**Issue by schiegl** [alainm23/planify#376]
**Is your feature request related to a problem? Please describe.**
If you have lots of projects with different deadlines it can get a little overwhelming knowing which one is the most important right now. Most projects have deadlines which Planner also doesn't have concept of yet. But one can use the "Scheduled Date" I suppose.

**Describe the solution you'd like**
Show days left until next deadline in project next to each project in the sidebar. If the deadline is more than 2 weeks a date can be shown. This would replace the indicator of how many tasks are left in each project.

**Describe alternatives you've considered**
I tried using the schedule feature to assign deadlines. Then I can look them up in upcoming. But this approach scatters all project deadlines on a long page.

**Comment by alainm23** [comment]
Sure
![image](https://user-images.githubusercontent.com/33765137/83532601-16189600-a4b4-11ea-8315-a5a2d29825ef.png)
