### ISSUE TITLE
[Solicitud] Mostrar tareas completadas

### ISSUE THREAD

**Issue by cemetary** [alainm23/planify#38]
Hola.

He observado que transcurrido un día, las tareas completadas ya no se muestran en el _dashboard_, a pesar de que se encuentre activa la opción de «Mostrar tareas completadas». ¿Esta funcionalidad es a propósito o es un _bug_? Sea como fuere, me gustaría tener la opción de poder visualizar las tareas completadas sin importar en qué fecha fueron realizadas.

Gracias y felicitaciones por tu software.

**Comment by alainm23** [comment]
Gracias por el comentario, estuve recreando el bug y me doy cuenta que el botón "Mostrar tareas completadas" no funciona cuando no hay ninguna tarea abierta, arreglare esto en la próxima versión.
