### ISSUE TITLE
history view for completed tasks

### ISSUE THREAD

**Issue by adds68** [alainm23/planify#381]
**Is your feature request related to a problem? Please describe.**

The moto is "never forget anything again", which believe me resonates with me well, however one problem i have is remember everything i have *done*.

**Describe the solution you'd like**

I'd really like it if the calendar view could go backwards and show my "completed" tasks for that day

**Describe alternatives you've considered**

I can't think of any other way to do this

**Additional context**

**Comment by alainm23** [comment]
Thanks for commenting, probably the best solution for this is the 'Completed' view
![image](https://user-images.githubusercontent.com/33765137/82720733-f1cee500-9c7b-11ea-809a-fc16e88c9b9d.png)
Could it be a solution?
