### ISSUE TITLE
Quick find dialog is not easily dismissible 

### ISSUE THREAD

**Issue by raproenca** [alainm23/planify#382]
**Describe the bug**
When I open the Quick Find dialog, my first instinct to close it is by clicking away from it (A.K.A. clicking anywere else on the main window). But it does not go away that way. Then I think that I should trigger the same keyboard shortcut I used to open it to dismiss it (like a toggle of sorts), but CTRL+F does not close this dialog; Then I think that maybe by clicking the magnifying glass icon, the same one that opens the dialog, will dismiss the Quick Search dialog, but no - it doesn't.
I have to hit ESC to close it, and - as far as I know - only then the dialog will be dismissed (or if I acutally click one of the search results, if I searched for something). I think for people that are not very "keyboard focused", hitting esc to close a dialog is not very intuitive, specially in this age of mobile interfaces.

**To Reproduce**
1. Press CTRL+F to open the Quick Find dialog;
2. Do not type in any query;
3. Try to dismiss it (without using ESC key)

**Expected behavior**
When you click away from the Quick Find dialog (anywhere in the main window), it should close the dialog; When you hit the same keyboard shortcut you used to reveal the dialog, the dialog should be destroyed; When you click the same icon used to reveal the dialog, the dialog should be destroyed (but I guess this one would become obsolete by the first method of clicking away from the dialog, so it is not really relevant).

**Desktop (please complete the following information):**
 - OS or DE: POP OS using Gnome 3.36
 - Version 2.3.5

**Comment by alainm23** [comment]
Fixed, now we use [focus_out_event](https://valadoc.org/gtk+-3.0/Gtk.Widget.focus_out_event.html)

**Comment by alainm23** [comment]
I will close the issue because it has already been fixed in the master.

**Comment by forteller** [comment]
I see here that you should now be able to close the search dialog by pressing Ctrl+F (again) and by clicking outside of it. None of this works for me.

In addition: If you have not written anything in the search box I have to press Esc twice to close it. Not sure if that should be a separate issue.

Nobara 39, Gnome, Planify 4.4

**Comment by alainm23** [comment]
@forteller  Hello and thank you for using Planify, with the migration to Gtk4, Quick Find can no longer be closed by losing focus. However the error of pressing Esc twice to close is correct and is being fixed.
