### ISSUE TITLE
See Events in the calendar

### ISSUE THREAD

**Issue by andirsun** [alainm23/planify#383]
**Is your feature request related to a problem? Please describe.**
Is not releated with problem

**Describe the solution you'd like**
I want to know if its possible to show the upcomming events in the elementary os calendar 

**Describe alternatives you've considered**
Maybe in the notificartions area or somethig to remind without enter in the app
** Example of why is important
![Screenshot from 2020-05-21 17-36-48](https://user-images.githubusercontent.com/22928302/82613044-00d56a80-9b8a-11ea-9f4d-5864202a1353.png)

**Comment by alainm23** [comment]
Calendar event is available and works fine on elementary OS. 
![image](https://user-images.githubusercontent.com/33765137/82614242-fd8fae00-9b8c-11ea-8f62-792f24bb76b6.png)

**Comment by alainm23** [comment]
Sorry that is not possible, calendars work with Evolution Data Server (EDS) and it is a technology that Planner doesn't support yet.

**Comment by andirsun** [comment]
> Evolution Data Server

How many time and money could cost that feature ?

**Comment by alainm23** [comment]
I'm not sure, EDS is a package provides a unified backend for programs that work with
contacts, tasks, and calendar information. We plan to support EDS and Caldav in the future but as a major update that will rebuild all Planner (Maybe Planner 3).

**Comment by alainm23** [comment]
Closing as "Out of Scope" because this feature uses Evolution Data Server and Planner doesn't support it yet.

**Comment by andirsun** [comment]
Thanks for taking time to answer me. Good Luck with your awesome project !
