### ISSUE TITLE
minimize to system tray

### ISSUE THREAD

**Issue by omega3** [alainm23/planify#384]
Please, add option to minimize to system tray. I don't know how it works in elementary desktop environment because I use it in Plasma. This function would be extremely for other DE users who use traditional panels with system tray, not any docks. 

This is not the same issue as 
https://github.com/alainm23/planner/issues/359
I think minimize to system tray is even easier to do and more versatile option but I don't put it here as competition but as separate issue.

**Comment by williamd1k0** [comment]
I think this feature would complement the "Run in background" setting.
For now, you need to run the application again to reopen the main window (which is not very intuitive).

**Comment by isshin1** [comment]
yes please, this app is awesome for bigger and planned projects, but covering small daily tasks is hassle without a tray option. It will really help if we can view all the current day task in the tray menu

tray menu as shown in #359 is a good reference itself

**Comment by goirik-chakrabarty** [comment]
Is this coming anytime soon? I completely agree, having a system tray icon for quick access will be awesome!!!

**Comment by edumapurunga** [comment]
I definitely agree with a system tray minimization for other operational systems other than elementary OS. It would be a nice feature.

**Comment by alainm23** [comment]
Planner is no longer supported, I will close this issue for the time it has been inactive.

**Comment by kosssi** [comment]
it's a feature that could help with adoption of the software, which looks great - I'm just discovering it 🙏

**Comment by GermanZun** [comment]
just discovering too, this feature could be useful
