### ISSUE TITLE
Granular control of recurring tasks

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#389]
I simply love the fact that planner has recurring todos. It would be far more improved if two more features are added though:

The ability to set the number of intervals to repeat the task, eg every 2 days, every 3 weeks, every 2 months, ect

The ability to specify the days of the week the task repeats on, eg repeat every week on monday, wednesday and friday. 

These two things would make the recurrence system *perfect*

**Comment by alainm23** [comment]
I'm working on a natural date parser to solve this problem.

**Comment by BeatLink** [comment]
Awesome!

**Comment by alainm23** [comment]
Delayed but soon available
![image](https://user-images.githubusercontent.com/33765137/218072898-68c42c4e-4835-40cb-93c3-c61fda72178e.png)
