### ISSUE TITLE
Moving the task for collapsed tasks from below the task to the right

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#390]
Currently the icons for a related task are kept below it as shown here

![image](https://user-images.githubusercontent.com/47278150/82843620-47390b00-9ea3-11ea-8da3-7234376acb22.png)

What im requesting is moving these icons to the right as shown here

![image](https://user-images.githubusercontent.com/47278150/82843805-faa1ff80-9ea3-11ea-8c09-891e40fe0827.png)

This would improve vertical space utilization while improving the appearance of the application

**Comment by alainm23** [comment]
Thank you very much for commenting, the first Planner 2 version came with this feature but we decided to leave it because when introducing multi-line tasks the design broke and looked ugly.
