### ISSUE TITLE
Allow expanding and collapsing of section by clicking on the title

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#391]
Currently, the application requires the user to click on a section's drop down arrow on the far right of the screen to toggle expanding or collapsing a section. 

What im recommending is allowing the user to click anywhere on a section's title and horizontal space to collapse or retract the section. This will improve usability by allowing the user to click (or tap as the case may be) on a larger surface area

**Comment by alainm23** [comment]
Sure, let's do this, 1 click to open and close the section, double click to edit.

**Comment by alainm23** [comment]
![SecyiomDnD](https://user-images.githubusercontent.com/33765137/83263474-44306a00-a184-11ea-9cee-1bc9fdae1d59.gif)

**Comment by BeatLink** [comment]
Awesome!

**Comment by isshin1** [comment]
Can this also be extended to tasks, a double click on empty area next to title should hide them ?

Or Hide Details button can be shifted to down left before Schedule 

Reason : Its really cumbersome when you have multiple tasks open under a section and have to go to far right everytime just to click Hide Details button
