### ISSUE TITLE
Cursor Jumps around when editing description

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#392]
**Describe the bug**
The cursor jumps to the end of the textbox when editing a project description.

**To Reproduce**
1. Click on a project description to begin editing
2. Write some text
3. Move the cursor to the middle of the text or anywhere that isnt the end
4. Type some more text and wait a few seconds
5. The cursor will jump to the end of the textbox

**Expected behavior**
The cursor should remain in the original position even after a few seconds

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint Cinnamon 19.3
 - Version: 2.3.5

**Additional context**
I believe that this is due to the autosaving mechanism in the application. When text is typed into the description textbox, the autosave mechanism kicks in after a few second. After saving, the textbox is reinitialized and the cursor then jumps to the end of the new text. A solution would be to record the position of the cursor prior to autosave and after the textbox is reinitialized, immediately set the cursor to the previously saved position

**Comment by alainm23** [comment]
Thanks for reporting it.

**Comment by BeatLink** [comment]
Another update, this bug also affects the description fields of individual tasks
