### ISSUE TITLE
Add support for opening local paths and files

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#393]
Hey it would be cool if local files, folders and paths could be converted to links that could then be opened with a default application. I do believe gnome has default handler opening tools such as exo-open that could make this really easy

**Comment by alainm23** [comment]
Sorry but I can't understand your request, could you be a little more explicit, maybe add an example, etc.

**Comment by BeatLink** [comment]
Currently, URLs work in the application, for example: http://example.com/ will work. However, local files wont work. for example ~/Documents/Projects or ~/eBooks/calibre-gui.desktop. So its not possible to open either folders or files via links from task descriptions

**Comment by wada3n** [comment]
#375

**Comment by wada3n** [comment]
Duplicate of #375

**Comment by wada3n** [comment]
Duplicate of #375

**Comment by 73** [comment]
> Duplicate of #375

Not exactly. It is about making URIs with the scheme `file` like in `file:///home/user/Documents/more.md` actually clickable.

**Comment by bepolymathe** [comment]
Any news on this subject ? Markdown would be a + (like in todoist)...

**Comment by alainm23** [comment]
Hi guys, I am adding this new feature in the next Planify update, it is now possible to add attachments.

![image](https://github.com/alainm23/planify/assets/33765137/d2a3318f-d7a0-46d4-bcd8-9831e1e4fd8d)
