### ISSUE TITLE
Cant reorder tasks in Today section

### ISSUE THREAD

**Issue by gavr123456789** [alainm23/planify#394]
**GIF**
![Peek 2020-05-28 11-14](https://user-images.githubusercontent.com/30507409/83116416-6ff41700-a0d4-11ea-82e9-d68b1c644681.gif)

**Desktop (please complete the following information):**
 - OS or DE: [e.g. pantheon, unity, gnome] gnome
 - Version [e.g. 0.1.2] 3.36

**Comment by alainm23** [comment]
Sure 😉️
![Today DND](https://user-images.githubusercontent.com/33765137/83144533-19c5aa80-a0b9-11ea-9d4a-370ef4a5d33b.gif)

**Comment by 4jNsY6fCVqZv** [comment]
https://github.com/alainm23/planner/issues/161

**Comment by 4jNsY6fCVqZv** [comment]
Request for Drag & Drop in the **Today View**
https://github.com/alainm23/planner/issues/161#issuecomment-622964333

Request for Drag & Drop in the **Upcoming view**
https://github.com/alainm23/planner/issues/161#issuecomment-622963543

**Comment by rzelnik** [comment]
I just wanted to create a new issue for that. I use Planner 2.3.5 with Ubuntu 20.04. I can reorder tasks in Inbox and in projects, but in Today and Upcoming it just doesn't work. It allows to move the task by drag&drop, but then it returns back to it's previous position - like in [gavr123456789's video](https://github.com/alainm23/planner/issues/394#issue-626311204).

**Comment by 4jNsY6fCVqZv** [comment]
@rzelnik both wishes for improvement are already noted. this issue can probably be labeled as a duplicate. @alainm23?

**Comment by rzelnik** [comment]
@4jNsY6fCVqZv thank you for your info. I respect it and I am sorry for confusion.

**Comment by 4jNsY6fCVqZv** [comment]
@rzelnik all good, thanks for thinking it over!

**Comment by 4jNsY6fCVqZv** [comment]
@rzelnik Thanks for sharing your thoughts!

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 It looks like it is still not possible to move a task to the first position by dragging and dropping. I use Planner 2.4.6 from the AppCenter. This is different from what is possible in the Inbox, for example.

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 Even with Planner 2.5.7 from the AppCenter it is not yet possible to move tasks to the first position by drag and drop. Is this a conscious decision or could you imagine to add this?
