### ISSUE TITLE
No tasks are showing in the application

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#396]
**Describe the bug**
Areas, Projects, Project Descriptions and Sections are visible, but no tasks. 

**To Reproduce**
Not really sure what I did to cause this. Last I remember was adding a task

**Expected behavior**
I should see my tasks

**Screenshots**
For context, all sections are expanded here. There should be several tasks in each section 
![image](https://user-images.githubusercontent.com/47278150/83362706-f1f47200-a358-11ea-8688-8e651a9da237.png)

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint Cinnamon 19.3
 - Version: 2.3.5

**Additional context**
I've checked the database file and the tasks *are* there so i'm not quite worried as yet. I've also made a backup of the database file just in case this bug will end up wiping it out. I think the first step is to diagnose what's going on in the application. Unfortunately, planner doesn't have a debug mode.

I will search for log files in the program folder. Failing that, ill try to debug it with GTK inspector

**Comment by BeatLink** [comment]
Running from the command line gives the following errors

```
(com.github.alainm23.planner:2): Gtk-CRITICAL **: 16:05:27.827: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed

** (com.github.alainm23.planner:2): WARNING **: 16:05:27.898: CustomShortcutSettings.vala:28: Schema "org.gnome.settings-daemon.plugins.media-keys" is not installed on your system.

** (com.github.alainm23.planner:2): CRITICAL **: 16:05:27.898: services_custom_shortcut_settings_list_custom_shortcuts: assertion 'available' failed

** (com.github.alainm23.planner:2): CRITICAL **: 16:05:27.898: services_custom_shortcut_settings_create_shortcut: assertion 'available' failed

(com.github.alainm23.planner:2): Gtk-CRITICAL **: 16:05:28.250: gtk_list_box_row_grab_focus: assertion 'box != NULL' failed

(com.github.alainm23.planner:2): Gdk-CRITICAL **: 16:05:32.913: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.alainm23.planner:2): Gdk-CRITICAL **: 16:05:32.932: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.alainm23.planner:2): Gdk-CRITICAL **: 16:05:32.961: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.alainm23.planner:2): Gdk-CRITICAL **: 16:05:32.985: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.alainm23.planner:2): Gdk-CRITICAL **: 16:05:33.013: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.alainm23.planner:2): Gdk-CRITICAL **: 16:05:33.029: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.alainm23.planner:2): Gdk-CRITICAL **: 16:05:33.051: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.alainm23.planner:2): Gdk-CRITICAL **: 16:05:35.805: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.alainm23.planner:2): Gdk-CRITICAL **: 16:05:35.890: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.alainm23.planner:2): Gdk-CRITICAL **: 16:05:35.932: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.alainm23.planner:2): Gdk-CRITICAL **: 16:05:35.971: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.alainm23.planner:2): Gdk-CRITICAL **: 16:05:36.007: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.alainm23.planner:2): Gdk-CRITICAL **: 16:05:36.035: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.alainm23.planner:2): Gdk-CRITICAL **: 16:05:36.066: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.alainm23.planner:2): Gtk-WARNING **: 16:05:37.480: Child name 'project' not found in GtkStack

(com.github.alainm23.planner:2): Gtk-WARNING **: 16:05:37.481: Child name 'project' not found in GtkStack

(com.github.alainm23.planner:2): Gtk-WARNING **: 16:05:37.481: Child name 'project' not found in GtkStack

(com.github.alainm23.planner:2): Gtk-WARNING **: 16:05:37.482: Child name 'project' not found in GtkStack

(com.github.alainm23.planner:2): Gtk-WARNING **: 16:05:37.483: Child name 'project' not found in GtkStack
```

I think this bit: `Child name 'project' not found in GtkStack`

is rather interesting. I think it suggests that there is a UI widget that the code cant find

**Comment by BeatLink** [comment]
Attempting a total uninstall and reinstall including user config folders (ive backed up my db files).

**Comment by BeatLink** [comment]
Still no go. That rules out program errors. I fear database corruption.

Okay next step, Ill try to go through the database using sqlitebrowser and try to find and remove the last task I added. If something breaks, ill restore from the copy i made

**Comment by BeatLink** [comment]
Didnt work. Before I tried deleting another task, i tried restoring a database backup from 3 days ago. It worked! We can now confirm that im experiencing some kind of database corruption. 

So something happened between earlier today and a a few minutes ago. All i can remember was adding tasks. Ill continue to delete tasks from the latest version of the database to see whats up.

**Comment by BeatLink** [comment]
Still no luck. Haven't been able to nail down this database bug. My guess is its a non reproducible database corruption bug of some sort. Ill just restore the working database from 3 days ago and manually reenter any new tasks from the latest database.

Good news! My dejadup backups backed up the database yesterday. So even less to restore :D

**Comment by BeatLink** [comment]
Ill keep the buggy databases around if you want me to take a closer look on the issue.

**Comment by BeatLink** [comment]
All back up to speed! Waiting to hear from you

**Comment by alainm23** [comment]
Thank you very much for commenting, I have been able to reproduce the bug 2 times and just like you I'm not sure how it happened.

**Comment by BeatLink** [comment]
Happened again yesterday, had to roll back to a backup from tuesday to get it working again. 

As a stopgap, i made a backup script that creates a timestamped tarball of the database folder on every database change. Since the database files are KBs in size this shouldn't be a problem. Here's the script if you guys want it


https://gist.github.com/BeatLink/7e404de40561be76f204aaf64d9f9b1d

Just set your username/path properly in the first 3 variables and add the script to startup apps. You'll also need to get inotifywait from your distro. For me on deb based systems i can install it by typing `sudo apt install inotify-tools`

**Comment by BeatLink** [comment]
@alainm23 I think i nailed down the bug! Or at the very least, its now reproducible. I reproduced it by deleting an item under a section and immediately after deleting the same section. Then the tasks all vanished

This is leading me to believe that this is some kind of race condition. Not sure how id prevent it from happening, nor how to fix it after its happened

But the way the bug is tied to the database (reverting to a previous version of the database undos the bug) this makes me think that some form of invalid data is being saved to the database and preventing the tasks from loading in the UI. Perhaps a foreign key being set to a reference that no longer exists.

To fix the bug, i think a good place to start would be to enable validation for every single field in every table in the database. Then implement cascading operations for creations, updates and deletions. Once the database is nice and strict and validated, im sure the bug will turn up in a visible exception or crash

**Comment by alainm23** [comment]
@BeatLink Thank you very much.

**Comment by BeatLink** [comment]
np :)

**Comment by BeatLink** [comment]
Can this issue be closed?

**Comment by alainm23** [comment]
The bug has already been fixed, available in the last update in AppCenter or Flathub.
