### ISSUE TITLE
Checklist items not reset in repeated tasks

### ISSUE THREAD

**Issue by rzelnik** [alainm23/planify#397]
**Describe the bug**
When I finish a repeating task, it creates a new one for next day/week/month/year. The repeating task can contain checklist of subtasks. These subtasks are checked although the main task instance is new and unsolved.

**To Reproduce**
1. Create a new task
2. Create a checklist of that task
3. Check "Repeat > Every day"
4. Check the subtasks in checklist as finished
5. Check the main task as finished
6. New task appears in Upcoming
7. The new task is unchecked (new, unsolved), which is good.
8. The subtasks in the new task are checked. 

**Expected behavior**
If the checklist of subtasks is a child of the main task, then they should be considered to be new/unsolved with each new instance of the main task. Like repeated task - start again from scratch.  

**Desktop (please complete the following information):**
 - OS or DE: Ubuntu 20.04
 - Version 2.3.5

**Comment by alainm23** [comment]
Duplicate #388
