### ISSUE TITLE
Add Unscheduled and expired/overdue Views

### ISSUE THREAD

**Issue by JordyScript** [alainm23/planify#398]
Firstly, great app and thank you for developing it.

### Proposal
Presently it is possible to view an aggregate view of:

- the tasks that are due Today
- the tasks that are have been scheduled and are therefore Upcoming

It is however not possible to see an aggregate view of:

- the tasks that are overdue
- the tasks that have not been scheduled

I believe that adding such views would be useful to the users of Planner. 

### Arguments
As much as we would like to finish tasks in a timely manner, if this is not possible, it would be a huge benefit to be able to quickly see an aggregate view of all the tasks that are overdue in every folder/project and from there reschedule them, or simply complete them before moving on to Today's tasks.

Similarly, it would be good to be able to see at a glance all of the unscheduled tasks, so that you can either work through them one by one when you have some time to spare (after finishing Today's tasks), or plan them for some future date while having all unscheduled tasks in view to determine which ones deserve most priority.

### User Interface
For the sake of consistency I had in mind that the UI of the overdue view would mirror that of the upcoming view (alist of days starting with yesterday's date/the date of the youngest overdue task and going backwards in time), and the UI of the unscheduled view would mirror that of the today view (an alphabetically sorted list with tasks that are labelled with the project that they belong to).

### Feedback
What do you all think?

**Comment by BeatLink** [comment]
The latest build of planner does include a dedicated section for overdue tasks. So all that would really be needed is the Unscheduled view

**Comment by JordyScript** [comment]
Hadn't seen that yet. I hope the overdue tasks section will skip dates for which there are no overdue tasks. Wouldn't be optimal if you had a task that's 30 days overdue, but you don't even see it because it's so far down the list.

**Comment by alainm23** [comment]
Hi guys, a new filter has been added called Anytime which filters out all unscheduled tasks. And as @BeatLink  pointed out the overdue tasks can be viewed in the Today view.

![image](https://github.com/alainm23/planify/assets/33765137/73160360-a019-4764-9344-a335cceb6227)
