### ISSUE TITLE
Window border doesn't work

### ISSUE THREAD

**Issue by guilmour-asc** [alainm23/planify#40]
**Description**
Dark theme style has `rounded` borders on bottom, while light/normal style hasn't.
(_In my opinion, rounded borders go well with your app, hehe_)

**To Reproduce**
On the app:
1. Go to the `Menu` button
2. Swap to the dark theme, via the Night Mode switch

**Screenshots (My custom theme is the exact copy of elementary GTK, theme, just changed colors)**
![captura de tela de 2019-01-15 16 22 20](https://user-images.githubusercontent.com/26415345/51200934-f0501880-18e1-11e9-8fd4-a16687fe7eeb.png)
Above, the app on normal theme (no rounds on bottom).

![captura de tela de 2019-01-15 16 22 32](https://user-images.githubusercontent.com/26415345/51200939-f5ad6300-18e1-11e9-9acf-913d995bb303.png)
This next picture is the app in dark mode (bottom-rounded).

**Desktop**
 - elementary OS Juno

**Comment by alainm23** [comment]
You have eagle eyes, I also saw the same behavior, by default the edges are rounded, but it only works in night mode and I have no idea why it happens, I will investigate how to fix it. 
By the way I like how Planner looks with its default theme, this gives me many ideas, thanks for feedback.

**Comment by alainm23** [comment]
I tried to fix this problem, but I still can not find a solution.

**Comment by guilmour-asc** [comment]
Ummm...
... maybe there's something on the GTK theme, now that I think 'bout it.
And if it's true, we shall **correct the main elementary theme**, as well... or somebody else, I dunno really.

**Comment by alainm23** [comment]
The window with borders look good, but I decided to stop using them.

**Comment by alainm23** [comment]
I found a way to make it work.
