### ISSUE TITLE
Add support for time

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#400]
**Is your feature request related to a problem? Please describe.**
A new way to sort tasks is needed. While sorting based on priority is a good starting point, not all tasks can be done at any given time. It may be the case where some tasks can only be done at a specific time. For example, eating breakfast would only be doable in the morning, 

**Describe the solution you'd like**
A solution to this would be to add support for setting times, as well as dates, and then sorting tasks in the today section based on that time. With this design, planner can better follow the mechanics of a calendar with a clearly established order that tasks should be done in. This would make the app easier to use

**Describe alternatives you've considered**
A stopgap measure could be to add a toggle to sort the tasks in the today section in alphabetical order. Then the user could manually enter the time of the task as the first part of its title for manual sorting.

**Comment by nandgator** [comment]
Just to make it clear...

> For example I have a weekly evening meeting on Wednesday at 19:00 Hrs.

Take a look at the slight difference in the planner and Todoist UI.

| ![image](https://user-images.githubusercontent.com/38415384/89140718-15f25080-d560-11ea-9a19-d73b08ece8db.png) | ![image](https://user-images.githubusercontent.com/38415384/89140885-8c8f4e00-d560-11ea-84f8-8b2fdf2ac87a.png) |
| --- | --- |

Currently I can set the task as recurring but not for a particular time on Planner but while syncing sometimes the time factor (as you see on Todoist) gets lost. I guess that is what this issue addresses.

---

> Apart from that the regular reminder stays, irrespective of the above mentioned time.

**Comment by BeatLink** [comment]
Another way we can easily implement this is simply make reminders recurring too according to the same rules of the recurring main task. So for example if i have a daily task with reminders, reset the dates of all the reminders one day in the future the same as the main daily task (the time can stay the same).

**Comment by nandgator** [comment]
> Another way we can easily implement this is simply make reminders recurring too according to the same rules of the recurring main task.

Yep, that is plausible but that does not hamper the ability to keep a reminder at custom time, right?

**Comment by BeatLink** [comment]
It shouldnt. Like the time could stay the same. Its just the reminder repeats when the task does. So if a reminder is a day before the main task at 5pm it will stay a day before 5pm even after the task reccurs.

**Comment by BeatLink** [comment]
Would it be possible to implement this in the next release? Or is it further along on the roadmap?

**Comment by alainm23** [comment]
Available in version 2.5, an update soon.

![image](https://user-images.githubusercontent.com/33765137/93128323-e96c4100-f694-11ea-8fc4-95aea4224005.png)
