### ISSUE TITLE
Tasks do not sync to todoist.

### ISSUE THREAD

**Issue by ruanformigoni** [alainm23/planify#405]
**Describe the bug**
The local tasks do not sync to todoist, but tasks from todoist sync to local.

**To Reproduce**
1. Create a task
2. Click on sync
3. Nothing happens

**Expected behavior**
Tasks show up on todoist

**Desktop (please complete the following information):**
OS: Ubuntu 20.04 LTS x86_64 
Host: 81V7 Lenovo IdeaPad S145-15API 
Kernel: 5.4.0-37-generic 
Uptime: 1 hour, 31 mins 
Packages: 2656 (dpkg), 7 (flatpak), 20 (snap) 
Shell: bash 5.0.16 
Resolution: 1920x1080 
DE: GNOME 
WM: Mutter 
WM Theme: Yaru-dark 
Theme: Yaru-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: x-terminal-emul 
CPU: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx (8) @ 2.300GHz 
GPU: AMD ATI 03:00.0 Picasso 
Memory: 3420MiB / 5882MiB

**Comment by alainm23** [comment]
Thanks for commenting, local projects are not syncing with Todoist for now, I will close this issue as it is related or duplicated with #236
