### ISSUE TITLE
[Feature Request] Title Bar support

### ISSUE THREAD

**Issue by raulcraveiro** [alainm23/planify#406]
It's not exactly a problem, but I use GNOME and every app that I uses has support to the system titlebar, giving a more cohesive look. I would love to see support for this in Planner app.

![image](https://user-images.githubusercontent.com/5623492/85043428-b7fddb00-b162-11ea-9160-b8b4f2af3fc3.png)

**Comment by alainm23** [comment]
Thank you very much for commenting, I'm not sure what you mean by title bar? is it about the buttons position?

**Comment by raulcraveiro** [comment]
Not the position itself, but the style of the title bar. 

I would love to see the title bar using the system theme. (In the case of the screenshot, It's Adwaita-dark)

**Comment by raproenca** [comment]
+1 for this.
On Elementary Planner looks great, but on other GNOME-based distros it does not feel like a native app and what would go a long way on fixing this is providing a [Gtk.HeaderBar](https://valadoc.org/gtk+-3.0/Gtk.HeaderBar.html) widget in the top of the window if Planner detects it is being ran on GNOME (or have a toggle in the preferences to toggle between the "full headerbar" or "minimal mode", which would be the current default style).

That can be achieved by using CSS. See the screenshot of an app I am developing to teach myself to code Python and GTK:
![Screenshot from 2020-06-22 15-25-03](https://user-images.githubusercontent.com/23019356/85322794-4218ad00-b49d-11ea-84de-2f6f7a587104.png)
![Screenshot from 2020-06-22 15-25-15](https://user-images.githubusercontent.com/23019356/85322804-45ac3400-b49d-11ea-8aad-88c9376aad7b.png)

The screenshot was taken on Gnome using Adwaita. The CSS code to blend the HeaderBar into the MainWindow is:
```
headerbar.titlebar {
  border: none;
  box-shadow: none;
  background-image: linear-gradient(to bottom,
    shade(@theme_bg_color, 1.05),
    shade(@theme_bg_color, 1.00));
}
```
Of course you can (and should) tweak it even further so it feels native on both Elementary (Pantheon?) and GNOME as well.

Just a suggestion. I hope it helps.

**Comment by raproenca** [comment]
Just to complement my previous comment:
I do not know if Planner currently uses a Gtk:HeaderBar to contain the window control buttons (minimize, close, etc), but I think it could implement one if it is not the widget being used now.
And if you do implement a Gtk.HeaderBar, you could use CSS to make it hide its borders so it would blend better with a more minimalistic look, like the current appearence of Planner does. Or if you want better uniformity with GNOME environment, the HeaderBar bottom border and colors would be set to the default GNOME theme.
There are some applications that looks and feels great both in Elementary and on Gnome and they still use a Gtk.HeaderBar. One example of this, at the top of my mind, is [Apostrophe](https://gitlab.gnome.org/somas/apostrophe). 
I know that several default Elementary OS apps use Gtk.HeaderBar, but to be honest I haven't tried to see how those apps look on a GNOME enviroment.

**Comment by theotheroracle** [comment]
honestly this is my biggest complaint with the app, if it uses proper header styling, the app would be so much cleaner

**Comment by digitalethics** [comment]
I can only emphasize how important it is to make Planner more **agnostic** in terms of what desktop environment is being used. I am currently using KDE Plasma, however, I have customized it in a way to resemble GNOME, and Planner really looks out of place.

**Comment by digitalethics** [comment]
Related to #401 
@alainm23 Would you mind commenting again on this issue and how to move forward?

**Comment by Leon0402** [comment]
In general provide an option to use "system window frame", I would like to see this happening as the window frame (title bar) looks out of place on KDE. Instead the feature to customize the buttons on the title bar, planner currently has, (windows style, mac style ...) could be removed, this should just work out of the box with system frames.

**Comment by Toxblh** [comment]
![image](https://user-images.githubusercontent.com/2198153/101383777-73e9c880-38b1-11eb-8727-3c1103ea6b28.png)
@alainm23 they and I about to be able to change the appearance of window with theme from system.

I'll try to do the PR for implement the switch without broke the theme of content the app
That I just to disable https://github.com/alainm23/planner/blob/master/src/Application.vala#L231 the line, but if don't use elementary theme a lot of small details stay look is different, because got it from my current theme

**Comment by dsprenkels** [comment]
I took a shot a fixing this issue. Any feedback is appreciated at #619. :)

**Comment by dsprenkels** [comment]
@Toxblh Sorry, I did not notice that we _just_ collided on this issue. :/

**Comment by Toxblh** [comment]
@dsprenkels so cool 👍
