### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by lexesv** [alainm23/planify#407]
**Describe the bug**
Build error:  _The name `Application' does not exist in the context of Granite.Services_

**To Reproduce**
meson build --prefix=/usr
cd build
ninja

**Screenshots**
![2020-06-19_16-44](https://user-images.githubusercontent.com/15149258/85138840-2a96b580-b24c-11ea-9fd4-e5416196d9fd.png)

**Desktop (please complete the following information):**
 - OS or DE: Debian 10 amd64 (XFCE)

**Comment by alainm23** [comment]
Thanks for commenting, please install the latest version of [Granite](https://github.com/elementary/granite).
