### ISSUE TITLE
Add support to Todoist

### ISSUE THREAD

**Issue by alainm23** [alainm23/planify#41]
In the same way as we do with support for Github Issues, we can bring each new task created in the Todoist Inbox

**Comment by Hedronmx** [comment]
I guess you could use Todoist as a syncing platform... ?

**Comment by alainm23** [comment]
I'm starting to do tests with this feature. You can now get an Access Token.

![todoist](https://user-images.githubusercontent.com/33765137/52394856-d8e7f380-2a79-11e9-95be-91f61892d321.png)

I will try to use Todoist as a synchronization platform.

**Comment by Hedronmx** [comment]
Any news on this :D, i cant wait!

**Comment by alainm23** [comment]
I will work on this feature in a larger version of Planner, I'm still doing tests. anything will keep you informed

**Comment by ansoni-san** [comment]
Is this still intended to be worked on?

**Comment by alainm23** [comment]
@ansoni-san Of course, for the moment I'm working hard and I'm giving myself little time for Planner, but I already have a good progress:
https://github.com/alainm23/planner/tree/planner_v2

**Comment by coworkingon-es** [comment]
Any news on EDT?
Thanks!

**Comment by alainm23** [comment]
@coworkingon-es  Thanks for your comments, I am including this feature but the form of the visualization will be in lists.

Project > Headings > Tasks

**Comment by alainm23** [comment]
- [x] Sync tasks
- [x] Sync projects
- [ ] Sync labels
- [x] Create projects
- [x] Update projects
- [x] Delete projects
- [x] Add Tasks
- [x] Update tasks
- [x] Delete tasks
- [ ] Move tasks
- [ ] Order tasks
- [x] CRUD Sections

**Comment by alainm23** [comment]
Has anyone already started trying this new feature?
In my case it works well, but I would like to know if in all cases it is the same.

**Comment by Hedronmx** [comment]
I did try it out! It works, tho its missing the today and week view. Also recurrent tasks are not shown.

Is there a way to reset the app, so i can re login and start from scratch?

**Comment by alainm23** [comment]
Yes, delete the db file:
`/home/user/.local/share/com.github.alainm23.planner`

**Comment by Hedronmx** [comment]
Well its working really good, just some missing features that's all

**Comment by balance-wtf** [comment]
Hey, I might be dumb, but how do I access this?

**Comment by Hedronmx** [comment]
Compile this repo and give Version 2 a try
