### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#412]
**Describe the bug**
The icon for Getting Started project not show up

**To Reproduce**
Just open the app with default Getting Started project

**Expected behavior**
Icon show up normally

**Screenshots**
![2020-06-22-193444_1920x1080_scrot](https://user-images.githubusercontent.com/37035950/85289318-72724280-b4c1-11ea-8c24-47cc522c849b.png)

**Desktop (please complete the following information):**
 - OS or DE: Arch linux with i3wm

**Additional context**
I already install 'elementary-icon-theme 5.3.1-1' and 'gtk-theme-elementary 5.4.2-1'

**Comment by alainm23** [comment]
Check here: #196

**Comment by ghost** [comment]
Install 'noto-fonts-emoji' package fix this for me. I suggest mention this package on readme for feature users.
