### ISSUE TITLE
[Feature Request] Allow clicking to see details of completed task

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#415]
**Is your feature request related to a problem? Please describe.**
Currently, you can't see completed task by clicking on it but you can do it on uncompleted task.

**Describe the solution you'd like**
Clicking on completed task should also expand that task.

**Comment by yannicka** [comment]
`ItemRow` and `ItemCompletedRow` should by only one class but with a parameter to have a different, read-only rendering for completed tasks.

**Comment by alainm23** [comment]
Update to v2.5.4 please.
![image](https://user-images.githubusercontent.com/33765137/95775027-2d983480-0c87-11eb-8c61-b350175a1b08.png)
