### ISSUE TITLE
[Feature Request] Add support for sub-task

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#416]
**Is your feature request related to a problem? Please describe.**
Currently, Planner have no support for sub-task. The only thing that come close is section but that far from enough. Usually, 1 task will have small sub-task, and sometime, those sub-task can have smaller sub-task too. I think that the way to organize task, by breaking them down to smaller, easier to do sub-task and it would be nice to add that to Planner.

**Comment by alainm23** [comment]
Subtasks are available in Planner but only at 1 level.
![image](https://user-images.githubusercontent.com/33765137/85350119-deef4080-b4c5-11ea-99fe-a60d224a35e4.png)

**Comment by ghost** [comment]
Thanks for your reply.

1. ~~How can I create sub-task? I tried drag and drop but it have no effect.~~ I see it now, it's called checklist. But it somewhat limited since it just a checklist, not a normal task.
2. Can you make it to support more level?

**Comment by yannicka** [comment]
Seems to be a duplicate of #255.

**Comment by BeatLink** [comment]
Closing in favour of the above linked discussion. Feel free to head there and give your input
