### ISSUE TITLE
Ctrl + Tab still works despite custom Quick Add shortcut

### ISSUE THREAD

**Issue by cameralibre** [alainm23/planify#420]
**System:** elementary OS 5.1.5 Hera
**Version:** Planner 2.4.2

### Context
I made a custom Quick Add keyboard shortcut (`Shift + Ctrl + Left Tab`) because every time I was switching between tabs in a browser using `Ctrl + Tab` the Quick Add dialog would pop up. 

### Expected Result
My new keyboard shortcut should be the **only** shortcut that triggers Quick Add. If there's a custom shortcut set, `Ctrl + Tab` should no longer trigger Quick Add.

### Actual Result
Both the custom shortcut _and_ the default shortcut work, so I still can't navigate between browser tabs unless I close Planner.

**Possibly related:** the `Ctrl + N` shortcut does not work for me. All other shortcuts work as expected.

**Comment by alainm23** [comment]
The keyboard shortcut to use Quick Add can be changed from the Preferences in Planner. Go to Preferences > Quick Add
![image](https://user-images.githubusercontent.com/33765137/85906118-fb93bd00-b7d2-11ea-956a-47e211c92d1e.png)

**Comment by cameralibre** [comment]
@alainm23 yes, that preferences section is exactly how I changed the shortcut. 
That is the issue I'm describing. Despite changing that preference, the old default shortcut still works.

**Comment by alainm23** [comment]
@cameralibre You can remove the old keyboard shortcut in System Settings> Keyboard> Shortcuts > Custom
![image](https://user-images.githubusercontent.com/33765137/85908934-fd627e00-b7dc-11ea-811f-a9bb04fa0d71.png)
