### ISSUE TITLE
Todoist unable to link

### ISSUE THREAD

**Issue by Vyshnav2255** [alainm23/planify#424]
**Describe the bug**
Todoist is unable to link. The window opens, after typing username and password it goes to a permission page. After agreeing the permission it goes to this GitHub page.

Elementary os 5.1.5

**Comment by TheKlavData** [comment]
Same problem here on elementary os 5.1.5
It used to work a week ago

**Comment by alainm23** [comment]
Walt the update please

**Comment by thelazygit** [comment]
I have the same issue. Trying to link ToDoist account it goes to the Github page. Apologies, I am on elementary OS 5.1.6 Hera
