### ISSUE TITLE
Can't launch Planner after trying to change .db file

### ISSUE THREAD

**Issue by tsitokhtsev** [alainm23/planify#431]
**Describe the bug**
I can't launch Planner. After clicking on app nothing happens.

**To Reproduce**
I tried to change default database file and chose file on remote desktop. Planner crashed and I tried again changing .db file twice, after that Planner didn't even launch. I tried to reinstall app but it didn't help.

**Expected behavior**
I want to recover Planner.

**Screenshot**
When I launch Planner from terminal it gives this output
![Снимок экрана от 2020-06-29 17-20-36](https://user-images.githubusercontent.com/38284633/86010755-e4500c00-ba2c-11ea-8038-b899e5d189b7.png)

**Desktop:**
 - OS or DE: Pop!_OS 20.04
 - Version 2.4.5 (Flatpak version)

**Comment by sergiosrav** [comment]
I have the same problem, but when I created a new user I could open it normally.

Version of Flatpak 1.6.5

![image](https://user-images.githubusercontent.com/5314752/90690825-4299ae00-e26a-11ea-9f78-58b486e42941.png)

**Comment by BeatLink** [comment]
This should be closable since later versions of planner replaces the changing of the db file location with an export import system instead
