### ISSUE TITLE
Drag and Drop makes stuff invisible

### ISSUE THREAD

**Issue by jounathaen** [alainm23/planify#432]
**Describe the bug**
Dragging and dropping Stuff makes it disappear. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Select a project in a sidebar folder and drag it into another folder
2. Sometimes (almost every time) the folder the project gets dragged over disappear and the project which was dragged disappears as well

Similar Problem with tasks inside a project
1. Dragging Tasks over sections makes the section and the task disappear

**Expected behavior**
Well...

**Desktop (please complete the following information):**
 - OS or DE: GNOME Shell 3.36.3 on Fedora 31
 - Planner 2.4.5 - Flatpak

**Additional context**

- After a restart, all items are back
- Local account. No Todoist
- Does not happen when using rightclick actions to move objects

**Comment by alainm23** [comment]
Thanks for reporting this bug, I'm trying to reproduce the error but I can't, is there anything else I should be aware of?

**Comment by jounathaen** [comment]
I guess not. It was a fresh install with only a few dummy notes

**Comment by jounathaen** [comment]
One more little detail: The mouse icon does not change back from the drag-icon (hand) to normal (cursor)

**Comment by jounathaen** [comment]
Additional Detail: I'm running Gnome on Wayland.

I tried to capture it in screenshots (Mouse not included due to wayland)

First:
![Screenshot from 2020-06-30 16-34-57](https://user-images.githubusercontent.com/16337548/86140032-b6cc9680-baf0-11ea-872c-7a3f8cd40578.png)
Dragging "Other" upwarts:
![Screenshot from 2020-06-30 16-36-02](https://user-images.githubusercontent.com/16337548/86140045-ba601d80-baf0-11ea-8587-358fab42bf1d.png)
Dropping it - Poooof it is also gone :grin: 
![Screenshot from 2020-06-30 16-36-07](https://user-images.githubusercontent.com/16337548/86140054-bc29e100-baf0-11ea-8a30-f3bcea359fa3.png)

**Comment by alainm23** [comment]
This is a very rare bug, I can't really reproduce it and I see that when you drag your project 'others' the whole folder disappears. Maybe it has something to do with the window manager you use. I'm not sure how to fix it.

**Comment by jounathaen** [comment]
I could also reproduce the bug with the dnf fedora version (2.3.5)

**Comment by XT-Martinez** [comment]
I also encounter this behavior when rearranging my project sections.

**Desktop (please complete the following information):**
OS or DE: GNOME Shell 3.36.4 (Wayland) on Fedora 32 (Silverblue)
Planner 2.4.6 - Flatpak

**Comment by veigaribo** [comment]
Has just happened to me as well.
After trying to reorder my tasks, I did apparently grab the whole section by mistake, as it all disappeared.
Then I tried to position it in the same place it was before, and it didn't show up.

After killing the process (with `flatpak kill`) and restarting it, I could see the section again.

My environment is very similar to the others:
- OS or DE: GNOME Shell 3.36.3 (Wayland) on Fedora 32 (Silverblue)
- Planner 2.4.6 - Flatpak

I was not able to reproduce it afterwards, though, and moving projects between folders did not make it happen here in the 20 < x < 50 times I tried.

**Comment by marcopat** [comment]
Same thing happened here. Some hopefully useful details:
- The inbox appears to be empty after making an upgrade to Planner 2.4.6 (through the Ubuntu "Software Updater").
- My system is Ubuntu 18.04.
- Projects & folders are still visible, but nothing appears in the Inbox.
- items are there somewhere, I can confirm that an item becomes visible when making a search of it.
- NOTE: I can keep working with this trick: 
  - I open the search window
  - search any item that I know it is in the Inbox
  - when the item appears in the search window, then I double-click on it
  - then the *whole* Inbox reappears with all the items. It is not a fix - if I click on Today and then again on Inbox then no item appears - but until I do this I can work in the Inbox normally.

**Comment by hcal** [comment]
just want to mention that it happened to me.  I had a mild panic when one of my important folders along with all it's projects disappeared.  

Was dragging a project from one folder to another.  The target folder was at the very bottom of the windows and I think I might have missed the target slightly and unintentionally drug the project off the Planner window.  

The entire folder and all the project in it disappeared, not just the project I was moving.   The missing projects could be pulled up by searching for them, but they weren't listed anywhere in the list on the left.  

Closing and relaunching the app didn't make the folder and projects come back, but later I rebooted and once I relaunched the app the folder was back.

EDIT:  I've switched away from Wayland to X11 and have not seen the problem since and it was a fairly regular occurrence.

**Comment by slrendell** [comment]
Happened to me a few times. Seems to happen when dragging anything. Using latest gnome on Debian 10.

**Comment by isshin1** [comment]
Happened to me too, on Arch with sway 

I had two sections in a project with some tasks in both. Dragging any task from lower section makes the whole lower section go invisible and can't placing the task in upper section after dragging does nothing. And now I only have upper section visible and dragged task also disappears with lower section.

If I restart planner or refresh the same project by selecting another project and back to it, it is same as it was before the earlier attempt.

While Shifting a task from upper section to lower happens without a hitch.

**Comment by Jarodiv** [comment]
Guess it's related to mine too (on Gentoo Linux with X11) -> #691
