### ISSUE TITLE
Checklist box color is the same for Priority 3

### ISSUE THREAD

**Issue by wada3n** [alainm23/planify#433]
Hello again
I would like to thank you, by the way, You are every time amazed me with the additions that you offer in each version of this masterpiece.

One simple technical thing I want to mention is the color of the subtasks box (Checklist) is the same color as the tasks of the priority3 .
I think if the priority 3 color had changed from blue to another color (brown or turquoise) would be better.
What do you think ?

**Comment by alainm23** [comment]
A new color is not necessary.
![image](https://user-images.githubusercontent.com/33765137/86483905-a4ce3c00-bd1a-11ea-9d7b-844f4adb2882.png)
