### ISSUE TITLE
All tasks have suddently disappeared

### ISSUE THREAD

**Issue by MrJohz** [alainm23/planify#434]
**Describe the bug**
Yesterday I had multiple tasks split into different sections, all in the Inbox view (I only use the Inbox view).  Today, when I opened the app, it had updated to the latest version (i.e. with the Ctrl-Tab shortcut), and all of my todos are now missing.

**To Reproduce**
1. Open Planner
2. There are no tasks

**Expected behavior**
There should be tasks.

**Desktop (please complete the following information):**
 - OS or DE: Pop!_OS, Gnome (20.04)
 - Planner Version: 2.4.5 (installed via Flatpak)

**Additional context**
I have not linked Planner with Todoist or anything similar.  This seems similar to #418, but (a) I can't make this happen reliably, and (b) that seems to involve the sync process..  This should not have involved syncing anything at all, because I have no other accounts set up.

**Comment by cromangnon** [comment]
I can second this - no online linking, all tasks in "Inbox" gone. Very bad.

**Comment by Dwyte** [comment]
Experienced the same, all my task on a project also went gone. It left 1 task tho.

**Comment by alainm23** [comment]
I have tracked the bug. I'm working on a solution, please be patient.

**Comment by BeatLink** [comment]
Yay!
