### ISSUE TITLE
Connecting todo list to google

### ISSUE THREAD

**Issue by mhabibi** [alainm23/planify#435]
**Describe the bug**
After Logging in with my google, the popup window redirects to the github repository of Planner

**To Reproduce**
1. Go to the application
2. Click on Todoist
3. Login in with your google credentials
4. See it's redirected to github repository and nothing happens

**Expected behavior**
It should connect to google and supposedly sync with google calendar

**Screenshots**
![Screenshot from 2020-07-01 09-34-58](https://user-images.githubusercontent.com/4964205/86217273-8a139000-bb7f-11ea-8b54-843697d9d2fa.png)

**Desktop (please complete the following information):**
 - Elementary OS 
 - Version 5.1.5 Hera
- Built on Ubuntu 18.04.4 LTS

**Comment by alainm23** [comment]
Update Planner to v2.4.5 please
