### ISSUE TITLE
Feature Request: Add Markdown support for notes section

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#438]
Hey! Great to see the new release. I think by now planner is the best todo app i've seen on linux! It would be great if you could add markdown rendering support for the notes sections of project, section and task description. Just simple stuff like headers, bullet points, ordered lists and the like. Its not an urgent priority but it would be a nice feature to have once everything is nice and stable. And if you think its too much work or not the goal of the app then thats okay too :)

**Comment by alainm23** [comment]
It is good to know that you would like this feature. However, we have already supported Markdown in Planner 1 and I don't like the result. The UX is horrible and the details on a technical level too.

**Comment by BeatLink** [comment]
Ahh okay then!
