### ISSUE TITLE
Feature Request: Rewrite in Python

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#439]
Would you be rewilling to rewrite the app in python? It would benefit from increased support and better code readability and I could also help out with maintaining the app. If the rewrite seems too daunting, I can assist with it

**Comment by alainm23** [comment]
Thanks for commenting, I had Python in mind to develop my applications but I was not convinced as it is an interpreted language and with a slow execution in desktop applications (For this reason Ubuntu stopped using it).

https://www.reddit.com/r/elementaryos/comments/7o5grw/why_use_vala/
https://blog.elementary.io/why-we-write-elementary-apps-in-vala/

**Comment by BeatLink** [comment]
Ahh okay
