### ISSUE TITLE
option to remove window decoration 

### ISSUE THREAD

**Issue by BiegeRelic** [alainm23/planify#441]
**Describe the solution you'd like**

the option of no window decorations in the drop down menu (none)

**Comment by jounathaen** [comment]
Could it be, that you want what is already described in https://github.com/alainm23/planner/issues/406 ? (or https://github.com/alainm23/planner/issues/401)

**Comment by alainm23** [comment]
Planify was ported to gtk4 and libadwaita, this should no longer be a problem. try it here:
https://t.co/QlimF62c5a
