### ISSUE TITLE
Implement Logging Framework

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#442]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alainm23** [comment]
I'm sorry but I don't understand your request.

**Comment by BeatLink** [comment]
Basically using vala's logging tools to print more messages to console after every action, depending on levels. Would help debug issues faster. Sorry for not taking the time to explain it

**Comment by alainm23** [comment]
Planner is no longer supported, I will close this issue for the time it has been inactive.
