### ISSUE TITLE
Add sorting functionality for today view

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#444]
Ideas for sorting

* By Priority
* By Project
* By Labels
* Manually

**Comment by BeatLink** [comment]
I'm wondering if its in any way possible to get this into the next release of planner. It would mean a lot

**Comment by alainm23** [comment]
I'm working on this feature.

**Comment by BeatLink** [comment]
Thank You!

**Comment by BeatLink** [comment]
Any updates on this or like a timeframe, say this month or next month? (Sorry if im being annoying, this feature would make my day)

**Comment by alainm23** [comment]
The feature is available only for projects, I have to implement it for today's view yet.

![image](https://user-images.githubusercontent.com/33765137/89698817-da051580-d8e8-11ea-9a79-50aae802f959.png)

**Comment by BeatLink** [comment]
Ohh awesome! So excited to see work being done on this

**Comment by BeatLink** [comment]
Whooo Hooo!

**Comment by BeatLink** [comment]
Im gonna build the latest version and dogfood this right now! If there are any bugs ill file a new issue
