### ISSUE TITLE
I would like to help out with maintaining planner

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#446]
I may not know vala much but i'm familiar with github workflows. I can help with

* Triaging issues
* Updating documentation and website
* Reviewing pull requests
* Helping to reproduce bugs
* Helping to identify problems and suggest issues
* Help with UI testing

I think planner is the best todo app on linux right now and im very invested in its continued support and maintenance. Im still in uni so i cant donate right now so i think this is another way i could help! :)

**Comment by alainm23** [comment]
Thank you very much for your interest in Planner.
- Planner is open source so you are free to request features and solutions to the different problems we have. 
- Planner also has a [website](https://github.com/alainm23/planner-web) that has a few things to add and improve.
