### ISSUE TITLE
Improve Tutorial Project.

### ISSUE THREAD

**Issue by alainm23** [alainm23/planify#447]
**Is your feature request related to a problem? Please describe.**
The tutorial project that Planner creates when you first start is not very clear.

**Describe the solution you'd like**
Make the tutorial project easier to understand and update it with all the features that Planner offers in each update.

If someone is interested in writing the new tutorial project, you can request a PR by editing these [lines of code](https://github.com/alainm23/planner/blob/master/src/Utils.vala#L851).

**Comment by ghost** [comment]
Hello 
I ve installed planner on ubuntu 18.04. looks like the tutorial dosent work for me.
when i created a new task nothing changed. is this normal or do i have a problem in the installation ? 

thank you for this app its very helpful !

**Comment by alainm23** [comment]
@Mezonx The Tutorial Project is a project like any other, it doesn't do anything special, it just tells you some things you can do with Planner.

**Comment by 4jNsY6fCVqZv** [comment]
I wonder if this could be an inspiration to improve the tutorial? https://github.com/pulsardev/vue-tour#vue-tour

**Comment by Tlamatinime** [comment]
Is help still wanted on this? I see commented-out code in master that would do something like this, but there is probably a reason that it is commented.
