### ISSUE TITLE
Cant login with my todoist account "Please, enter your credentials"

### ISSUE THREAD

**Issue by andirsun** [alainm23/planify#448]
**Describe the bug**
I cant start my todoist account
**To Reproduce**
1. Go to google login
2. Click on login
3. Scroll down to 'account

**Expected behavior**

**Screenshots**
![Screenshot from 2020-07-08 10-14-45](https://user-images.githubusercontent.com/22928302/86936822-20a5fb00-c104-11ea-8127-2a678a632bed.png)

**Desktop (please complete the following information):**
 - OS or DE: pantheon
 - Version [e.g. 0.1.2]

**Additional context**
the program says please enter your credentials

**Comment by andirsun** [comment]
The error only affect the appcenter version, i reinstall the flatpack version and it works

**Comment by alainm23** [comment]
Duplicate #424 
An update is sent to the AppCenter to fix the problem, but approval is taking time.
