### ISSUE TITLE
"Show completed tasks" always reports the deadline as today

### ISSUE THREAD

**Issue by inputsh** [alainm23/planify#449]
**Describe the bug**

"Show completed tasks" always shows the deadline as today, even if it was some time in the past.

**To Reproduce**
1. Add a new task.
2. Add a deadline some time in the past (like yesterday).
3. Mark it as completed.
4. Toggle show completed tasks.

**Expected behaviuor**

The deadline should remain in the past.

**Actual behaviour**

The deadline somehow gets switched to today.

**Desktop (please complete the following information):**
 - OS or DE: elementary OS Hera
 - Version: 2.4.2

**Additional context**

My idea was to create a folder and fill it out with projects titled as a week number. So this week's numbers would go in a project titled 2020-28. I wanted to use "show completed tasks" as a way of doing #276 before it gets implemented. This bug prevents me from doing so, since I can't organize my tasks by days in a week.

**Comment by alainm23** [comment]
Thanks for commenting, This behavior is not a bug but rather is done in this way. When you complete a task, the due date is replaced by the date it was completed. But if you hover over the task you will be able to see the task details including her due date.
![image](https://user-images.githubusercontent.com/33765137/87039174-691cf180-c1b4-11ea-81de-478d2cda9d9e.png)

**Comment by BeatLink** [comment]
Since this is an intended design, i guess we can go ahead and flag the issue as a question and close it? Unless you're considering changing the behavior in which case we can keep it open

**Comment by inputsh** [comment]
Sorry, waited for the next day to see what will happen. Indeed, the task is now shown as completed yesterday.

I'd say it's kind of confusing to have the completion date at the same spot as the deadline without some sort of a label indicating which is which.

That being said, I can't think of a good alternative UX-wise, and the difference in colour between an unfinished task and a finished one allows me to use the feature as I've imagined it.
