### ISSUE TITLE
Please add Appdata to be translated

### ISSUE THREAD

**Issue by NathanBnm** [alainm23/planify#45]
Translating `appdata.xml` file will help people to know about your app in the AppCenter. For example mostly French users won't download the app if it's description is in English, 'cause they will think that the app isn't translated and won't take time to read if its not translated.

What do you think?

**Comment by alainm23** [comment]
Thanks for comment, appdata if you are available for translation, you may only need to update the translations in your language.
Check: https://github.com/alainm23/planner/blob/7cdb9b1d43d095d5540d22374a5e57b4e5e6c792/po/fr.po#L886
