### ISSUE TITLE
Unable to create new Task from Inbox

### ISSUE THREAD

**Issue by MobileAZN** [alainm23/planify#451]
**Describe the bug**
When I am in the Inbox folder, I am unable to click the blue + to add a new task.  This is ONLY when I am in the Inbox.  All other folders work as expected.

**To Reproduce**
1. Go to 'Inbox'
2. Click on the blue '+' in the lower right corner
3. Watch the '+' acknowledge the click with a spin animation
4. Nothing happens other than the spin animation

**Expected behavior**
I expect a blue bar to appear towards the top of my list to accept input for a new Task.

**Screenshots**
![planner](https://user-images.githubusercontent.com/16355316/87050277-46daa200-c1bb-11ea-952b-dd52940dcde2.png)

**Desktop (please complete the following information):**
 - Fedora 32 / Gnome 3.36.3
 - Version 2.4.5

**Comment by BeatLink** [comment]
Not able to reproduce it myself. Were you doing anything in particular before this happened?

**Comment by BeatLink** [comment]
Also could you try running it from the command line, that way we can see if there are any error messages being thrown

**Comment by alainm23** [comment]
I confirm that I cannot reproduce the bug too. How do you install Planner?

**Comment by silvigon** [comment]
I had it happen at some point, don't know how (on Xubuntu 20.04 with Xfce 4.14, version 2.4.5 installed from Flathub)

The Ol' Reliable (closing and reopening the app) seems to fix it for me though, at least for now :"D

**Comment by MobileAZN** [comment]
I was not doing anything different before hand.  This is installed via flatpak.

I just updated to 2.4.6 today and this is not an issue within the new version.  I guess we can close this, as it's fixed in the latest version.

**Comment by MobileAZN** [comment]
Also, I gotta say, you all are fast with replying to issues!
