### ISSUE TITLE
Feature Request: Support a subset of markdown  in  titles

### ISSUE THREAD

**Issue by Shinigami072** [alainm23/planify#452]
**Is your feature request related to a problem? Please describe.**

When synchronizing with Todoist, the tasks that are in (a subset of) markdown (fe. created from a page via browser plugin)are rendered as plain text.

This is a problem for me as i frequently either add an email from a browser (as a formatted)
or use bold for emphasis in my task titles.
 
**Describe the solution you'd like**

Support for using markdown in titles that would include:
- **bold** `**bold**`
- `*italics*` `*italics*`
- [links](https://github.com/alainm23/planner/issues/) `[links](https://github.com/alainm23/planner/issues/)`

This would ensure feature parity between the two applications

**Describe alternatives you've considered**

Looking at ugly text and trying to ignore it,
Not using this application at all.

**Additional context**

**Comment by alainm23** [comment]
Sure.
![image](https://user-images.githubusercontent.com/33765137/87164070-e5cfce80-c28d-11ea-8851-d5644041ba87.png)
![image](https://user-images.githubusercontent.com/33765137/87164101-f41dea80-c28d-11ea-9e74-dfd4353d9179.png)

**Comment by alainm23** [comment]
I managed to format the text in bold and italics only missing the links. @romixch  could you give us a hand using Regex please? I try it but this is not my specialty yet.
