### ISSUE TITLE
Broken until user can safely backup/restore data

### ISSUE THREAD

**Issue by cromangnon** [alainm23/planify#454]
All the bugs which have led to data loss have perhaps been fixed, but the data is lost.
This is an unacceptable risk for anyone seriously interested in actually using this software.
A means to backup and restore user data must be implemented, so users can start again after the next error and it's subsequent fix - or am I supposed to write down my stuff with pen and paper or make screenshots of my data?

**Expected behavior**
If the software fails I have my data - ideally in plain text - so I can continue from where I was, after a fix.

**Desktop (please complete the following information):**
Ubuntu 20.04, GNOME

**Additional context**
Error #434 and others

**Comment by alainm23** [comment]
Thank you very much, I will work on this.

**Comment by cromangnon** [comment]
Alainm23, thank you for your work - I know how difficult this can be. You have made a nice piece of software, I'm sure you'll fix the rough edges. Thanks again.

**Comment by BeatLink** [comment]
@cromangnon It might not help to recover past data but i built a script to backup the database to a timestamped tarball after every change. You can read more on it here https://github.com/alainm23/planner/issues/396#issuecomment-653741133

I hope you find it useful
