### ISSUE TITLE
Filter tasks by priority

### ISSUE THREAD

**Issue by rzelnik** [alainm23/planify#455]
I would like to have a filter that would show me tasks from all projects filtered by priority, so that I would be able to show high-priority tasks and add deadlines to them. It could be a drop-down list under "Upcoming", that would have options like Show All (tasks from all projects), Show Only Priority 1, Priority 2, Priority 3, Priority 4.

**Comment by alainm23** [comment]
You can filter your task by priorities from Quick Find, try with p1, p2, p3.

**Comment by rzelnik** [comment]
Yes, it works, thanks. I didn't notice it yet. I am closing this issue.
