### ISSUE TITLE
Feature Request: add option to provide amount of days/weeks/months for the repeat function

### ISSUE THREAD

**Issue by mlubej** [alainm23/planify#458]
**Is your feature request related to a problem? Please describe.**

I have a planner project for meetings and I can't set them on repeat if they are i.e. every two weeks.

**Describe the solution you'd like**

I think it would be great if one could provide the amount of the selected period of time (day/week/month) for repeating

Great app btw! I love it

**Comment by alainm23** [comment]
Duplicate #389 Thank you very much for your feedback, I am investigating how to make this work but it's in the development plans,
