### ISSUE TITLE
Bug report: Weird behavior on Ubuntu with flatpak

### ISSUE THREAD

**Issue by mlubej** [alainm23/planify#459]
**Describe the bug**

I noticed this planner app and wanted to install it, but I had some trouble achieving this on Ubuntu 18.04 and 20.04. I installed flatpak normally following the [instructions here](https://flatpak.org/setup/Ubuntu/), but installing the planner app was weird.

**To Reproduce**

I tried the following ways:

1. via software center
after the app was available in the SC, the installation never finished and my whole OS became really unresponsive, I wasn't able to install it this way

2. via terminal

via terminal I tried both:
- downloading from flathub: `flatpak install flathub com.github.alainm23.planner`
- downloading the file and installing: `flatpak install com.github.alainm23.planner.flatpakref`

Both ways notified that I need to install some additional packages which were relatively small (few 100 MB or less). The issues with this were:
- incredibly slow download speeds (10-100 kB/s)
- OS became unresponsive (all apps started to lag, some didn't load anymore)

The above could take for hours and would still not finish.

3. installing packages separately

At a separate issue I noticed a list of commands

```bash
sudo apt install flatpak-builder
flatpak install flathub org.gnome.Sdk/x86_64/3.34
flatpak install flathub org.gnome.Platform/x86_64/3.34
flatpak install flathub io.elementary.BaseApp/x86_64/juno-19.08

flatpak-builder --install repo com.github.alainm23.planner.json --force-clean --user
```
where the result was the same for the first few lines of code, but the last one didn't even work, perhaps something changed in between.

4. Solution: installing with sudo

In the end, I was able to install everything if I just used the `sudo` permissions: `sudo flatpak install flathub com.github.alainm23.planner`. The download and installation were as fast as I expected them to be and the OS was responsive as always. Then the app was available system-wide and now everything works normally, except for the quick-add button.

**Additional context**
I just wanted to put this out there in case it can be fixed or for potential others which might hit the same issue.

Cheers!

**Comment by alainm23** [comment]
Thank you very much for using Planner. I will close this issue by `Out of Scope`.

I'm not sure why this happens, do you have the same behavior with other applications using Flatpak? you should probably open this issue at https://github.com/flathub/flathub/issues, they have more specialized people who will help you solve this bad behavior.
