### ISSUE TITLE
We can't translate the whole projet throught Weblate 

### ISSUE THREAD

**Issue by Mattherix** [alainm23/planify#461]
**Describe the bug**
When you use Planner in an other language (here french) it's not entirely translate even when it's 100% translate. Weblate doesn't detect all the extra and quick-add GNU gettext message catalogue files (.po).

**To Reproduce**
1. Install a french version of planner
2. Click F1
3. It's half translate

**Expected behavior**
Every gettext files need to be translatable thought Weblate.

**Screenshots**
![planner-help-page](https://user-images.githubusercontent.com/26037328/87663650-757ced80-c764-11ea-9ebd-57f3830fca9c.png)
![planner-no-create-new-items](https://user-images.githubusercontent.com/26037328/87663653-7746b100-c764-11ea-89ee-78cdec69d7f4.png)
![planner-no-open-quick-find](https://user-images.githubusercontent.com/26037328/87663657-79107480-c764-11ea-9a4b-c5b02c1c4cf0.png)
![Screenshot_2020-07-16 Planner Translations — French](https://user-images.githubusercontent.com/26037328/87663659-7a41a180-c764-11ea-882c-ba635b61b19c.png)

**Desktop**
 - OS or DE: Arch linux, Gnome
 - Version 2.4.6.g30060c22-1 (via [AUR elementary-planner-git](https://aur.archlinux.org/packages/elementary-planner-git))

**Additional context**
I have made a PR for the french translation #462

**Comment by alainm23** [comment]
I am aware the problem and it will be a bit difficult to solve it. Weblate requests a billing plan to add new translation files. We receive monthly donations but it's still not enough to be able to use Weblate with a billing plan.
