### ISSUE TITLE
Change first day of the week 

### ISSUE THREAD

**Issue by eliocamp** [alainm23/planify#469]
In the calendar thingy, Monday is the first day of the week. This is one convention, but not universal. It would be great being able to change it to be the same as the local calendar.

**Comment by alainm23** [comment]
Of course, it' something I had in mind.

**Comment by alainm23** [comment]
In development, It'll be available for Planner 2.6

![image](https://user-images.githubusercontent.com/33765137/97063428-46e19080-1565-11eb-90e0-dea80e60fe79.png)
