### ISSUE TITLE
Planner doesn't start in German language

### ISSUE THREAD

**Issue by kr428** [alainm23/planify#47]
Just received the latest version via elementary update; am unable to start anymore. Running from the terminal ends up in a segmentation fault, no real valuable additional information. How to help?

**Comment by alainm23** [comment]
Sorry, try manually deleting the database file:
`/home/<user>/.cache/com.github.alainm23.planner/database.db`

**Comment by kr428** [comment]
Still, unfortunately. :( Seems rather random here:

[22259.325026] com.github.alai[11669]: segfault at 7fff9a8d9fc8 ip 00007fafdbba7309 sp 00007fff9a8d9f90 error 6 in libharfbuzz.so.0.10702.0[7fafdbb7e000+9c000]
[22265.304296] com.github.alai[11686]: segfault at 7ffc8b7c5fa0 ip 00007f9fe4f03098 sp 00007ffc8b7c5fa8 error 6 in libpango-1.0.so.0.4000.14[7f9fe4eea000+4a000]
[22272.796582] com.github.alai[11705]: segfault at 7fffff401ff8 ip 00007f62fc5d8cf9 sp 00007fffff402000 error 6 in libpango-1.0.so.0.4000.14[7f62fc5ac000+4a000]
[22280.030939] com.github.alai[11729]: segfault at 7fffaeeeeff8 ip 00007f64f9c182b6 sp 00007fffaeeef000 error 6 in libpthread-2.27.so[7f64f9c0c000+1a000]

**Comment by alainm23** [comment]
I really have no idea why this happens.

**Comment by alainm23** [comment]
@kr428 Some update with this problem, was solved in the last update?

**Comment by kr428** [comment]
Not completely. But I've been some debugging recently and wonder whether this is my own fault in some way: Starting planner with the default locale and English language 

LANG=C com.github.alainm23.planner

apparently works. Seems whatever causes this segfault might be caused by the (German) translation. I didn't manage so far to start it with another locale though. Gonna look at the translation again to see whether there might be some issue with the strings in there - though I have no idea what it could be. :(

**Comment by alainm23** [comment]
This is very strange, I changed my language to German and try to launch the application, but for some reason can not be started, I was playing with the translation but there is no way to start.

`27688 segmentation fault  ./com.github.alainm23.planner`

**Comment by kr428** [comment]
Yes. That's the same thing I see here. I'm not sure something is wrong with the translation file, looking at the translation file using 

msgunfmt /usr/share/locale/de/LC_MESSAGES/com.github.alainm23.planner.mo  

things *seem* to look ok. Maybe there are some special chars in there that cause things to misbehave? I'll see whether I find some way to start planner in debugging, maybe there's a chance to see what happens.

**Comment by kr428** [comment]
For what I found right now, this seems caused by

0x00007ffff0ae7098 in pango_itemize_with_base_dir () from /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0

happening in Application.vala:181 somewhere in the "app.run()" call but I didn't really manage to get into that, so far. :|

**Comment by ghost** [comment]
**Example time in de_DE format:** "11:23 NACHMITTAGS"
**Length of this string:** 17 _> 8_

Without 65th line from Widgets/TimePicker runs successfully with the German language.
[(see my issue)](56)
