### ISSUE TITLE
Projects/Folders not visible consistently when moving tasks between projects

### ISSUE THREAD

**Issue by rushabhgala** [alainm23/planify#470]
**Describe the bug**
If I have a task in inbox, the other projects / projects in a folder are not visible when I want to move the task to a different project.

But when I have a task in a particular project and I want to move it elsewhere, I can see other projects (except inbox).

I am not sure if it is intentional but it seems like a bug to me

**To Reproduce**
1. Add a task in inbox and add few projects or folders if you don't have any
2. click on the task-> Three dots -> Move to project (only inbox is visible, the added projects are not visible)

1a. Add a task in a different project
2a.click on the task-> Three dots -> Move to project (all other projects except inbox are visible)

**Expected behavior**
Irrespective of where the task was added, when it is being moved, all projects should show up as an option

**Screenshots**
![image](https://user-images.githubusercontent.com/46610083/87969632-85f8d500-ca90-11ea-85fa-7a5a50596c15.png)
![image](https://user-images.githubusercontent.com/46610083/87969570-6792d980-ca90-11ea-87a8-f400b4bcf0a8.png)

**Desktop (please complete the following information):**
 - OS : Ubuntu 18.04.02 LTS with GNOME

**Additional context**
Apologies if I haven't explained it well.

**Comment by rushabhgala** [comment]
update : I can't drag and drop a task from inbox to a different project. But I can drag and drop a task from project R/L/C to project R/L/C in the above image

**Comment by alainm23** [comment]
Thank you very much for using Planner. This behavior is not a bug. You can work with Planner using Todoist and locally, when you sync your Todoist account the Inbox view is synced too. You can move tasks or sections between local or synchronized projects, but not from a synchronized project (Inbox) to a local project (Your created projects). Es un comportamiento horrible (lo se) pero estoy trabajando para poder solucionarlo.

**Comment by rushabhgala** [comment]
Okay. So the projects in the folders cannot be synced? For example, I want the R, L and C to be synced with my todoist. Is there a way I can do that? That would also solve the problem of moving stuff around in projects.

**Comment by BeatLink** [comment]
The latest version of planner allows you to convert local projects into todoist projects. That should solve your issue with moving tasks from the inbox to the projects
