### ISSUE TITLE
App doesn't refresh on next day if kept running

### ISSUE THREAD

**Issue by mlubej** [alainm23/planify#474]
**Describe the bug**
When I put my laptop to sleep mode and wake it up the next day, the running planner app still shows the situation for the previous day. If I restart the app then it behaves as expected.

**To Reproduce**
1. Start app
2. Put laptop to sleep
3. Wait to next day
4. Wake laptop and check app

**Expected behavior**
The app should automatically check if the date has changed

**Desktop (please complete the following information):**
 - Ubuntu 20.04, Cinnamon flavour
 - Version of app: 2.4.6

**Comment by yashasvi-ranawat** [comment]
Having the same issue still. Wonder why the issue is closed.

Planner version 2.4.6 (from flathub)
Ubuntu 20.04 LTS

Edit: I realise it could be resolved in the git, but not in a published version

**Comment by r3dArch** [comment]
I just recently installed Planify for the first time through Flatpak and am experiencing the same issue. I am running Arch Linux (6.8.1-zen1-1-zen) with SwayWM (1.9) and version 4.5.4 of Planify. I use hibernate to disk for my laptop so the battery isn't used, but I am not sure if that makes a difference over sleeping to RAM. When waking my laptop for the first time each day, I must restart Planify for it to update. How have so few people experienced this problem? Does it only happen with certain configurations? Or maybe sleeping/hibernating overnight is not that common?
