### ISSUE TITLE
Switch locale

### ISSUE THREAD

**Issue by azchatlanin** [alainm23/planify#476]
**Describe the bug**
When you switch the locale, the task you started disappears

**To Reproduce**
1. Click 'a' to create an task
2. Switch locale (ctrl+alt)
3. The task disappeared
4. Also the task disappears if I change the focus.

**Expected behavior**
Continue writing the task.

**Screenshots**
![Peek 2020-07-24 13-35-2](https://user-images.githubusercontent.com/21025345/88383728-b5bb1c00-cdb3-11ea-984e-ee8806fa574f.gif)

**Desktop (please complete the following information):**
 - Ubuntu 20.04

**Comment by alainm23** [comment]
Fixed in v2.5
