### ISSUE TITLE
Markdown links in title

### ISSUE THREAD

**Issue by mlist** [alainm23/planify#478]
problem: The gmail addon / extension for todoist conveniently allows saving e-mails as tasks. todoist saves them as markdown links of the form [text](url) which are not recognized by planner as urls and are thus not clickable.

solution: parse markdown url links to hyperlinks in planner

**Comment by alainm23** [comment]
![image](https://github.com/alainm23/planify/assets/33765137/ea932b7d-4a47-46bf-80b6-7f8ebb37fa3e)
