### ISSUE TITLE
Add a distinction between a folded section, a section without tasks and a section with only completed tasks

### ISSUE THREAD

**Issue by yannicka** [alainm23/planify#483]
Currently, there is no distinction between a folded section, a section without tasks and a section with only completed tasks:
![image](https://user-images.githubusercontent.com/22885898/89108869-7ee0a800-d43c-11ea-95a8-b0342d4b4073.png)

It would be nice to display that a section is empty or has only completed tasks (and, if completed tasks are displayed, this message is not displayed).

Here is the idea (illustration only):
![image](https://user-images.githubusercontent.com/22885898/89109014-c6b3ff00-d43d-11ea-823f-d1324ee1d6c6.png)

Also, an arrow could be displayed to indicate the folded/unfolded state of a section:
![image](https://user-images.githubusercontent.com/22885898/89124427-2dd1c200-d4d7-11ea-976a-7b1dd5b022d4.png)

**Comment by alainm23** [comment]
I like the idea, I'll consider it.

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/90085223-136cc500-dcdd-11ea-9478-efe0c4c1f480.png)
