### ISSUE TITLE
[Feature request] Add image support

### ISSUE THREAD

**Issue by mozzwald** [alainm23/planify#488]
Would it be possible to add the ability to insert images into text fields (descriptions) or as an attachment?

**Comment by vastray** [comment]
I agree. Useful function

**Comment by theunclemez** [comment]
I'm everyday halfway between graphic design and other IT task and while building my projects tasks and notes I noticed I couldn't drag and drop a pic (it's an essential part of my work)
So this made me go try to find another way and the simplest one was to copy-paste link to pics ... bit of too much efforts !

My entry as a solution would be to expand the possibilities and allow dragn'drop of pics in common format and maybe of other common file type.
Not going to ask you make it possible to create mood board using Planner but if it possible then please it would help a lot.

If not possible to dragn'drop files in there then link preview can make it too.
copy paste link and the app would sync and display the object linked to the url.

**Comment by alainm23** [comment]
Hi guys, I am adding this new feature in the next Planify update, it is now possible to add attachments.

![image](https://github.com/alainm23/planify/assets/33765137/d2a3318f-d7a0-46d4-bcd8-9831e1e4fd8d)
