### ISSUE TITLE
Appdata file is corrupted

### ISSUE THREAD

**Issue by NathanBnm** [alainm23/planify#49]
I don't know if it's only with French, but the app view in the AppCenter looks like this for me. Some stings are missing and screenshots too:

![image](https://user-images.githubusercontent.com/45366162/51699098-30af4500-200c-11e9-8ae6-e3811d1fb683.png)
![image](https://user-images.githubusercontent.com/45366162/51699126-3dcc3400-200c-11e9-95f3-795204d44f02.png)

**Comment by alainm23** [comment]
In Spanish, everything is fine, I'll check what happens.

![captura realizada el 2019-01-24 15 13 32](https://user-images.githubusercontent.com/33765137/51705890-da7dda00-1fea-11e9-94fc-5face155c349.png)
![captura realizada el 2019-01-24 15 14 00](https://user-images.githubusercontent.com/33765137/51705897-dce03400-1fea-11e9-90f2-ba86dbe18632.png)

**Comment by NathanBnm** [comment]
Maybe there's a problem with quotes in the fr.po file, I'm going to check

**Comment by vsg68** [comment]
In russian
(com.github.alainm23.planner:15733): Gtk-WARNING **: 18:40:24.156: Attempting to add a widget with type GtkImage to a container of type GtkButton, but the widget is already inside a container of type GtkButton, please remove the widget from its existing container first.

(com.github.alainm23.planner:15733): Gtk-WARNING **: 18:40:24.192: Theme parsing error: <data>:20:22: Not using units is deprecated. Assuming 'px'.

(com.github.alainm23.planner:15733): Gtk-WARNING **: 18:40:24.203: Theme parsing error: <data>:20:22: Not using units is deprecated. Assuming 'px'.

(com.github.alainm23.planner:15733): Gtk-WARNING **: 18:40:24.207: Theme parsing error: <data>:20:22: Not using units is deprecated. Assuming 'px'.

(com.github.alainm23.planner:15733): Gtk-WARNING **: 18:40:24.216: Theme parsing error: <data>:20:22: Not using units is deprecated. Assuming 'px'.
Segmentation fault

**Comment by NathanBnm** [comment]
@alainm23 I have checked `fr.po` and `appdata.xml` and nothing seems to be broken. Screenshots are now available but strings 1 to 5 aren't displaying.

**Comment by alainm23** [comment]
I hope that in this new update it will be fixed

**Comment by NathanBnm** [comment]
I hope so 👍

**Comment by alainm23** [comment]
@NathanBnm Please, let me know if in this update to solve the problem.

**Comment by NathanBnm** [comment]
@alainm23 I will

**Comment by NathanBnm** [comment]
@alainm23 it's fixed

**Comment by alainm23** [comment]
@NathanBnm Great!!!
