### ISSUE TITLE
[Feature request] Add show completed to Today panel too

### ISSUE THREAD

**Issue by vio1etus** [alainm23/planify#490]
You know it's a wonderful thing to see what you have done today in the evening of today.
Wish to see this function!

**Comment by alainm23** [comment]
Sure

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/90082529-9be76780-dcd5-11ea-89fe-278a88111ae3.png)

**Comment by Paulpatou** [comment]
Is this feature planned to come in a future version?
