### ISSUE TITLE
Sequeler reports Integer values too big for many tables

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#492]
**Describe the bug**
I've been trying out Sequeler as an alternative to SQLite Browser for my system setup and I thought I'd try it out on Planner's DB. When I did, i noticed an interesting error message. The Areas, Items, ItemsLabels, Labels, Projects and Sections all report that an integer value in their respective ID columns are too big

**To Reproduce**
1. Download Sequeler (You can get it here: https://flathub.org/apps/details/com.github.alecaddd.sequeler)
2. Open the planner database with it
3. Select the content tab in the headerbar
4. Select one of the following tables: Areas, Items, ItemsLabels, Labels, Projects and Sections
5. You will see an error raise. For example, clicking on the Area Table shows (Error 10 on Column id: Integer value is too big)

**Expected behavior**
Each integer ID should be within normal integer ranges.

**Screenshots**
Area
![image](https://user-images.githubusercontent.com/47278150/89739244-c79fee80-da44-11ea-92ef-1c030924f0b0.png)

Items
![image](https://user-images.githubusercontent.com/47278150/89739250-d5ee0a80-da44-11ea-808e-804fb1c3802c.png)

Items_Labels
![image](https://user-images.githubusercontent.com/47278150/89739259-e605ea00-da44-11ea-8f25-5f19153a2b61.png)

Labels
![image](https://user-images.githubusercontent.com/47278150/89739271-00d85e80-da45-11ea-8868-afba707b4e28.png)

Projects
![image](https://user-images.githubusercontent.com/47278150/89739280-13eb2e80-da45-11ea-8c64-355801a6d8af.png)

Sections
![image](https://user-images.githubusercontent.com/47278150/89739285-1ea5c380-da45-11ea-93a6-fe37ddae8f45.png)

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint Cinnamon 20
 - Version GIT Build Commit ID be455fb48210e411e404d91c6b06f806c569e8b0 Built with Gnome Builder Flatpak

**Additional context**
Planner generates IDs randomly, correct? A possible way to solve this is to test whether a generated ID falls within SQLite acceptable integer ranges before using that ID.

**Comment by alainm23** [comment]
Thanks for commenting, I will close this issue as Out of Scope because it's not a Planner error, Planner generates a random number to identify each project, section or task. This bug was already reported in [Sequeler](https://github.com/Alecaddd/sequeler/issues/83)
