### ISSUE TITLE
Add support for sorting by label

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#493]
**Is your feature request related to a problem? Please describe.**
I'm trying out the new sorting system and its really great. The only thing that's missing is the ability to sort tasks by their Labels. 

**Describe the solution you'd like**
I'd like to be able to sort tasks by their labels/tags

**Describe alternatives you've considered**
The search by label feature already exists but shows all tasks in the application with that label, without the context of areas or projects, Having the ability to sort specific projects by their labels would help reduce mental clutter

**Comment by alainm23** [comment]
I just implemented this feature, it works similar to Github Issues.

![image](https://user-images.githubusercontent.com/33765137/100530458-5dac8000-31c0-11eb-9ab7-b26c85b66f3b.png)

**Comment by BeatLink** [comment]
Awesome!
