### ISSUE TITLE
Label View Showing black borders around tasks

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#495]
**Describe the bug**
When using the search mode and selecting a label, black borders will appear around the main task list

**To Reproduce**
1. Click the magnifying glass to bring up the search tool
2. Select a label
3. The black border will be shown around the task list

**Expected behavior**
The black borders should not appear around the task list and the list should be displayed normally

**Screenshots**
![image](https://user-images.githubusercontent.com/47278150/89857443-b8fb2980-db61-11ea-9cd2-ae028dcea809.png)

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint Cinnamon 20
 - Version GIT Commit https://github.com/alainm23/planner/commit/be455fb48210e411e404d91c6b06f806c569e8b0 built with GNOME Builder Flatpak

**Additional context**
Not sure if its related to the Elementary theme, or whether its a flatpak application. Maybe it just doesnt play nice with Cinnamon.

**Comment by alainm23** [comment]
Thanks for reporting this bug, it is already fixed in the master.
