### ISSUE TITLE
Today view is empty

### ISSUE THREAD

**Issue by bknksrs** [alainm23/planify#501]
**Describe the bug**
Todays view is empty but on todoist i have tasks for today. Everything is synchronized with todoist.

**To Reproduce**
1. Go to 'Today view'

**Expected behavior**
Get list of Today tasks

**Screenshots**

![2020-08-28_12-21](https://user-images.githubusercontent.com/70373801/91550595-0f6db380-e929-11ea-8a41-f94d2acbee0d.png)

**Desktop (please complete the following information):**
 - Pop_OS
 - Version 20.04

**Additional context**
After some time Today View is back to normal, but from time to time the list is empty

**Comment by alainm23** [comment]
This problem is fixed in the master, please wait for the next release.
