### ISSUE TITLE
Dark Mode and Title Bar in Ubuntu 20.04 / awesome-wm

### ISSUE THREAD

**Issue by ng4mf** [alainm23/planify#502]
New user here, this looks cool! Couple issues with the UI in my installation, though.

**Describe the bug**
Dark modes in Ubuntu 20.04 / awesome-wm not switching text colors properly (including in popup menus).
Title bar is duplicated as window manager has its own as well.

**To Reproduce**
Install from source in Ubuntu 20.04 while running awesome-wm, start the application and switch to any of the dark themes.

**Expected behavior**
Text should should invert colors, ranging from white to light shades of grey to preserve readability (both in normal interface and the popup menus).
There shouldn't be two title bars - and the app title bar colors didn't switch for some reason.

**Screenshots**
The gif looks kind of odd - unsure why ffmpeg is having issues converting to gif, I'll see if I can get a better shot.
![planner-bug](https://user-images.githubusercontent.com/6548274/91644213-0bfd2980-ea08-11ea-812d-ddd9ea48ac20.gif)

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04
- Window manager: awesome v4.3

**Comment by ng4mf** [comment]
I tried again after installing from Flathub, and this time everything looks great. Unsure why installing from source wouldn't produce the same though. Maybe there was some kind of clash?

**Comment by Razer0123** [comment]
I am having the same issue after building from AUR (Archlinux)

Hope this gets fixed soon because i really like the app

**Comment by Razer0123** [comment]
Found the culprit, you need gtk-theme-elementary

**Comment by archisman-panigrahi** [comment]
@Razer0123 How did you install `gtk-theme-elementary` in Ubuntu? It does not seem to be available in the repositories.
This way, Flatpak can be avoided, and it will save a lot of space

**Comment by Razer0123** [comment]
I installed it using Archlinux so it's different, but have a look here

https://github.com/elementary/stylesheet

**Comment by chibbardpm** [comment]
> Found the culprit, you need gtk-theme-elementary

This was it exactly for me (Manjaro: Cinnamon with AUR enabled). Thanks mate!

**Comment by BeatLink** [comment]
Maybe we can add this to documentation for future reference and then close the issue?

**Comment by ng4mf** [comment]
I'll try this on Lubuntu and post back here so that the documentation can include all the flavors mentioned in this thread.

**Comment by alainm23** [comment]
Outside of elementary OS it's necessary to install Planner using Flatpak so that the themes and icons can be used correctly.
