### ISSUE TITLE
💡 : Synchronize with Tasks

### ISSUE THREAD

**Issue by nandgator** [alainm23/planify#503]
**Is your feature request related to a problem? Please describe.**
Recently I missed an important event due to no reminders on Todoist 😢

**Describe the solution you'd like**
Would love to sync tasks & projects with Google Tasks / Microsoft To-Do

**Describe alternatives you've considered**
Zapier works with the integration, but it's messy, actual sync isn't performed.

**Comment by nandgator** [comment]
**Update**
I stumbled upon this beautiful application: [Tasks](https://github.com/tasks/tasks) I think Planner has got a neat partner. I would love to see a collaboration with Tasks.

> Currently tasks does not support sub-lists but hopefully they'll consider with [this](https://github.com/tasks/tasks/issues/1123).

**Comment by BeatLink** [comment]
This should be doable if we can get planner to be compatible with other CalDAV applications such as NextCloud, and Etesync. Then we can use these CalDAV platforms as an intermediary between planner and Tasks.org

Should we close this issue in lieu of https://github.com/alainm23/planner/issues/75?

**Comment by nandgator** [comment]
@BeatLink as it feels right to the colabs. If CalDAV is being worked upon in the planner as requested in #294, it's okay. But we can close multiple issues together... once CalDAV is implemented. Label this issue. It will be a preferable :)

**Comment by BeatLink** [comment]
yeah, makes sense

**Comment by alainm23** [comment]
CalDAV support is coming anyway, I'm doing some internal testing and my code will be based on [io.elementary.task](https://github.com/elementary/tasks), there are still a lot of technical details to fix but I'm very happy to work on this feature.

**Comment by BeatLink** [comment]
awesome!

**Comment by alainm23** [comment]
I will close this issue in favor of #555
