### ISSUE TITLE
Design a new icon for a new section.

### ISSUE THREAD

**Issue by romdef** [alainm23/planify#504]
I would like to add multiple sections in a project, but the '+' button at the right of the project title (described in the tutorial) is missing.

This problem exists for local projects and ToDoist synchronized projects.

OS : elementary 5.1.7 Hera / Version [2.4.6]

**Comment by alainm23** [comment]
You can create a section using the button as shown in the screenshot.
![image](https://user-images.githubusercontent.com/33765137/92181670-6b47a900-ee0f-11ea-826c-76a37f86affc.png)

**Comment by romdef** [comment]
Hi Alan,
It could be better to change in the french tutorial (maybe in original tutorial too ?) the sentence for creating sections :
"- En haut à droite d'un projet, cliquez sur l'icône +."
Because it's not a plus sign, it's an right arrow ...

I thought it will change the name project. I didn't try to fill and add. Sorry ! :-/

**Comment by alainm23** [comment]
Sure :)

**Comment by 4jNsY6fCVqZv** [comment]
In this context, I wonder to what extent an arrow pointing to the right tells users that the action is here to add something.

I just looked again, elementary Greeter shows me a similar arrow. But the action in this case is to log into the desktop. I find this way more coherent. Would it be possible to actually change the right arrow to a plus? As far as I am aware, Planner uses the plus symbol to express this action in other parts of the UI. From my perspective with this change it would be less confusing and much more coherent.

**Comment by alainm23** [comment]
It is true, the icon to create a new section is a bit confusing, I would like to design or if anyone has any idea for the design of this icon I would be very grateful.

**Comment by Brin-o** [comment]
Hi!

Before I get to the icon, I think the header in the popup that you get when clicking on the icon should say "Section name" not just "name" so a user that clicks on the button without hovering over it can discover what it does more easily.

I started working on some icons for this. This is a symbolic icon so it should be 16x16, right?

I found the 16x16 constraint to be very hard to work with, especially if we wanna keep the circle. I think there should be a circle as well as that can suggest that this is a creation task just like the plus in a circle on the bottom right.

Here are some of the buttons I came up with so far:
![image](https://user-images.githubusercontent.com/49071768/93721891-34092400-fb93-11ea-98d4-9e0018d7869f.png)

I have a few more ideas for what kind of designs I could do and I'll try to tackle them during the week.

A few screenshots of mockups with the new icons:
![image](https://user-images.githubusercontent.com/49071768/93722254-cc080d00-fb95-11ea-9b62-b247043e405c.png)

![image](https://user-images.githubusercontent.com/49071768/93722260-d4604800-fb95-11ea-99da-d089d3bf0c30.png)

![image](https://user-images.githubusercontent.com/49071768/93722267-db875600-fb95-11ea-8d60-63e53d90a8fb.png)

I would highly suggest checking out the Figma file, there are more icons and mockups here so it's easier to get an idea of the whole thing.

https://www.figma.com/file/NlknnlTAWnfLsdQbVKhtvd/FOSS-Projects?node-id=0%3A1

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/93905208-4f258200-fcc0-11ea-8bd2-a5341246b6a7.png)

@Brin-o  Thank you very much for helping with the development of Planner. I like the design of image 1, Is it possible that you can send me the icon in svg format?

**Comment by Brin-o** [comment]
Hey!

Sorry, it's been a busy week.

I'm glad you like the icon! Here are the SVGs for it, I would however like to ask if you know where the original icons are coming from? I kind of eyeballed the drop shadow and I'd like to make sure it is consistent with the rest of the icons.

I have also played around with a version that has a more prominent "+" symbol, which might work better.


![Screenshot from 2020-09-25 21-37-32](https://user-images.githubusercontent.com/49071768/94308948-9a1cef00-ff77-11ea-9ce7-9d6c71588a0e.png)


Here are the SVGs, let me know if you need anything else :)
[Planner Icons.zip](https://github.com/alainm23/planner/files/5284995/Planner.Icons.zip)

**Comment by alainm23** [comment]
Thank you very much, I'm using the official [elementary OS icons](https://github.com/elementary/icons)

**Comment by 4jNsY6fCVqZv** [comment]
What does the rectangular box with the little plus in the upper right corner mean to you? An icon should be self-explanatory, right?

**Comment by Brin-o** [comment]
> What does the rectangular box with the little plus in the upper right corner mean to you? An icon should be self-explanatory, right?

To me it means "new square" and i'm interpreting square here as a section. What's your take on it?

**Comment by 4jNsY6fCVqZv** [comment]
If you associate a square, the four sides should be the same length, otherwise it is a rectangle ;)

When I look at the suggested iconography, I imagine that a box or container opens. However, when I add a section in Planner, no box opens, as it does when I edit a task, for example. What Planner does is create a heading for the section and a continuous horizontal line below it. This does not look like a box to me.

**Comment by 4jNsY6fCVqZv** [comment]
In other parts of the app a simple plus is used. I wonder when it makes sense to introduce another symbol. But I have no experience with that either. I just want to bring in my feelings and my critical questions at this point. Thank you for thinking and working on it!

**Comment by Brin-o** [comment]
That's a fair point!

I tried associating it with a line first since that's what planner does however, I felt like I couldn't make the icon stand in coherently with the rest of the UI. 

Inside of the circle it always ended up looking like a + and - due to the limited amount of horizontal space.

![image](https://user-images.githubusercontent.com/49071768/94902463-7c301c80-0498-11eb-8f73-892221022eaa.png)

I'll take a look at it one more time when I have the time to work on it, maybe I can come up with a solution now that I had some time for it to rest.

**Comment by dmlls** [comment]
I've been playing around with different ideas with @Brin-o's designs as starting point, having in mind what was mentioned previously here. After quite some time, this is the best I've been able to come up with:

![Line_Plus](https://user-images.githubusercontent.com/22967053/97857403-fb19ae80-1cfd-11eb-8d6e-291bec424759.jpg)

![Line_Plus_2](https://user-images.githubusercontent.com/22967053/97857419-ffde6280-1cfd-11eb-9e78-4c855addabfb.jpg)

Personally, I think a filled icon (e.g. https://github.com/alainm23/planner/issues/504#issuecomment-695836533) pops out too much, especially with the kebab menu icon next to it.

(PS: @alainm23 hope you don't mind I used your screenshot as base picture)

**Comment by Brin-o** [comment]
@dmlls 
I think "Line_plus_2" looks great in terms of representing what it does. And maybe you are right about the filled icon, my train of thought was to try keeping it consistent with the + icon on the bottom right. It  may be just the screenshot but your icon does appear to be a bit blurry? 

Did you make it on a 16x16 grid?

**Comment by dmlls** [comment]
@Brin-o 
The pictures I uploaded were just mockups, I didn't take care of resampling or anything when scaling down the icon.

Here's how the "Line_plus_2" icon would look on a 16x16 grid:

![Planner_16px](https://user-images.githubusercontent.com/22967053/98286888-ef034a80-1fa4-11eb-8f8f-b30fb2a8a76e.png)

**Comment by dmlls** [comment]
@Brin-o 
The pictures I uploaded were just mockups, I didn't take care of resampling or anything when scaling down the icon.

Here's how the "Line_plus_2" icon would look rescaling it to 16x16:

![Planner_16px](https://user-images.githubusercontent.com/22967053/98286888-ef034a80-1fa4-11eb-8f8f-b30fb2a8a76e.png)

However, since what we need is the .svg file, as long as this file is 16x16, rescaling/resampling is not something we should care about right?

**Comment by alainm23** [comment]
My design
![image](https://user-images.githubusercontent.com/33765137/100382135-9e51a100-2fe8-11eb-9e9f-a839c06ff363.png)

**Comment by BeatLink** [comment]
I love it!
