### ISSUE TITLE
Integrate with Workspaces to launch a selected project from there

### ISSUE THREAD

**Issue by dar5hak** [alainm23/planify#505]
**Is your feature request related to a problem? Please describe.**
[Workspaces](https://appcenter.elementary.io/com.github.devalien.workspaces/) is a new app that provides a way to launch multiple apps and run commands for a project. I use it to launch Planner so that I can see the tasks for the given project. The problem is, it can only launch apps directly, same as how you would do from the launcher or the dock.

**Describe the solution you'd like**
I propose that there be a way to launch Planner from Workspaces with a specific project opened. This would need at least two things:
- Ability to specify a project while launching Planner (likely using a CLI argument ~or Contractor~)
- ~UI to choose a project while configuring Workspaces (something similar to the Homepage preferences view)~

**Describe alternatives you've considered**
I launch Planner directly from Workspaces, then manually select the project.

**Additional context**
I have started a related discussion on the Workspaces repo as well. See devalien/workspaces#28. I am also willing to help with the coordination and development effort.

**Comment by alainm23** [comment]
I was working on some CLI commands for Planner and I am interested in your idea but with some improvements, instead of opening Planner with the project you choose we could open a new window with only the selected project if you only want to focus on that project and forget the rest.

**Comment by dar5hak** [comment]
Whoa, that's a much better idea! The user has simply no use of the other projects since they explicitly asked for a specific one. 🤯

**Comment by dar5hak** [comment]
Going by the discussion with @DevAlien, it looks like CLI arguments would be a much simpler approach, since it would work without Workspaces having to change anything. (It already supports running a command.)

It would even rule out my bullet point above about needing a separate "project chooser" UI.

**Comment by alainm23** [comment]
It is a work in progress and there is still a lot to fix but this works.

![Planner WultiWindows](https://user-images.githubusercontent.com/33765137/92635124-f35c0180-f29a-11ea-8d25-bd0b605eb91e.gif)

**Comment by dar5hak** [comment]
¡Eso es fenomenal! Do you think there's any enhancement that could be done on Workspaces side? If not, I'll go ahead and close the issue over there.

Also, let me know if I can help with any bugs.

**Comment by DevAlien** [comment]
@alainm23 so it will be a param when executing planner? I was thinking to add an easy way to pass a parma to an app, instead of writing a custom command.

Btw amazing work. I took some inspiration from your work.

**Comment by alainm23** [comment]
@DevAlien Yes, it is necessary to send a parameter like this: `com.github.alainm23.planner --load-project=2222757256` <- PROJECT_ID, If you can improve this process it would be amazing.

**Comment by DevAlien** [comment]
I could add app specific data somehow. Is it easy to find the project I'd on planner?

**Comment by alainm23** [comment]
There are 3 possible ways to do it, here are my ideas:

- You could connect to the Planner database directly but it would not be a good practice,
- You could use Planner's DBus server to get the list of all projects but Planner would necessarily have to be open to be able to provide this information.
- Planner could provide this command from the project preferences so that each user can use it in their application as in any other or even create a custom launcher.

**Comment by alainm23** [comment]
Add this command in the project preferences to be able to launch the project directly:
![image](https://user-images.githubusercontent.com/33765137/93025045-7beee080-f5c0-11ea-9f5b-a87d5ccd2884.png)

**Comment by dar5hak** [comment]
Perfect! This works everywhere: in Workspaces, at system start-up, as a shell alias…
