### ISSUE TITLE
Let me choose the date when i add a new task

### ISSUE THREAD

**Issue by Razer0123** [alainm23/planify#506]
**Is your feature request related to a problem? Please describe.**
When i add a task,  i need to add it then edit to change the date

**Describe the solution you'd like**
Give me the chance to set the date when i add the item

**Comment by daveiro** [comment]
I would add that one should also be able to add a time to the scheduled date of the task like it's possible in todoist web version, it has some smart auto-complete that would be wonderful to have in planner (see screenshot included); and I just noticed that planner does not show the scheduled time of tasks as entered in todoist... should I file a separate issue for this? Thanks!
![image](https://user-images.githubusercontent.com/4978070/92420781-27d19f80-f16d-11ea-934a-bae0c5ccadcb.png)

**Comment by alainm23** [comment]
I'm adding this feature for v2.5, @daveiro It's an amazing feature but unfortunately I still don't know how to do this, but it is something I will investigate.

![image](https://user-images.githubusercontent.com/33765137/92612846-e5e54e00-f27f-11ea-9145-e099592698e0.png)

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/93024940-a55b3c80-f5bf-11ea-9b0c-bfd20923dace.png)

**Comment by daveiro** [comment]
Hi alain, thanks for your reply. I didn't download/install yet the code with your recent commit, but is it now possible to specify date while writing/adding a task?
