### ISSUE TITLE
CTRL + TAB binding conflict with browsers

### ISSUE THREAD

**Issue by mredigonda** [alainm23/planify#507]
I noticed CTRL + TAB keybinding opens a new dialog to create a new task on planner. This keybinding though is widely used for browsers to switch between tabs (along with CTRL + SHIFT + TAB to go in the other direction).

Furthermore, can it be the case that it "broke" my browser configuration? since even after I uninstalled Planner I'm not being able to switch between tabs as I used to.

**Comment by coffeebrick** [comment]
I had this too. You can change the key binding in the settings in the app. I changed it to CTRL + Insert.

**Comment by alainm23** [comment]
For v2.5 I'm changing the default shortcut to Super + n (Windows + N), but if you want you can change it from the preferences or deactivate it.

![image](https://user-images.githubusercontent.com/33765137/92614061-3d37ee00-f281-11ea-904b-faeee431a371.png)

**Comment by mredigonda** [comment]
Awesome, feel free to close this already. Sadly my browser CTRL+TAB or CTRL+SHIFT+TAB stopped working but I believe that's on them (I also can't edit their keybindings).
