### ISSUE TITLE
allow to specify a due time for a task besides the date; show these times in task list

### ISSUE THREAD

**Issue by daveiro** [alainm23/planify#509]
Hi there,

I am loving this native linux app, however there's a main issue that still makes me use todoist web which is the fact that one can't specify a due time for a task besides the date. Also planner should show these times in task list. See todoist screenshot for a project with 2 tasks:

![image](https://user-images.githubusercontent.com/4978070/93025721-58478c80-f5f8-11ea-9580-ab8ffe489efa.png)

planner shows only that the tasks are due today, but not the time:

![image](https://user-images.githubusercontent.com/4978070/93025744-947aed00-f5f8-11ea-8657-d610cb223aee.png)

todoist allows one to specify a time to a task as per screenshot below or directly in task name as shown in issue #506 

![image](https://user-images.githubusercontent.com/4978070/93025802-05baa000-f5f9-11ea-881f-95f6ede336d1.png)

thanks for your dedication!!

Kind regards, David

**Comment by alainm23** [comment]
It's something that I'm working for v2.5. Very soon the new update.

**Comment by alainm23** [comment]
### What you think?

![image](https://user-images.githubusercontent.com/33765137/93128323-e96c4100-f694-11ea-8fc4-95aea4224005.png)

**Comment by daveiro** [comment]
seems fine 😀 looking forward to try the latest version, thanks!!
