### ISSUE TITLE
"&" character gets removed from task titles

### ISSUE THREAD

**Issue by xmo-odoo** [alainm23/planify#510]
**Describe the bug**
When the "&" character is input in a task title, it gets replaced by a " " (space?)

**To Reproduce**
1. Add task
2. Have "&" character in title e.g. "check that a & b"
3. Confirm
4. "&" has been removed by an extra space
**Expected behavior**
"&" to remain where I put it

**Desktop (please complete the following information):**
- mint 19
- cinnamon 3.8.9
- planner 2.4.6 (flatpak)

**Comment by alainm23** [comment]
Duplicate #186
