### ISSUE TITLE
Links no longer render properly in latest build

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#515]
**Describe the bug**
Latest build breaks website links parsing

**To Reproduce**
1. Build Flatpak from this commit https://github.com/alainm23/planner/commit/b55b26338f21f22d0625333f07eb0fbc66ab1f28
2. Add a link to project notes or task notes
3. Links will appear as the screenshot below shows, while the tasks are unfocused

**Expected behavior**
Links should be parsed and rendered appropriately (blue, underlined and clickable)

**Screenshots**
![image](https://user-images.githubusercontent.com/47278150/93378033-7b08b980-f821-11ea-8acd-07ead671bef6.png)

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint Cinnamon 20
 - Version:  Commit b55b26338f21f22d0625333f07eb0fbc66ab1f28

**Additional context**

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/93623992-34dc6300-f9a5-11ea-8407-34e3da968949.png)
