### ISSUE TITLE
Improve date entry

### ISSUE THREAD

**Issue by bepolymathe** [alainm23/planify#522]
Hi, 

Thank you for this tool that I am discovering and which is very useful. I have a suggestion for adding dates with the quick order. In addition to "today" or "tomorrow" you could use Emacs or todo.txt for a quick and extended input. 

Ex: 
1d --» tomorrow
1w --» +7 days
1m --» the same day next month 

What do you say?

**Comment by alainm23** [comment]
Great idea, but we should also think about internalization, do you have any idea how Emacs or todo.txt handles this for other languages.

**Comment by bepolymathe** [comment]
It's all in English but you just have to remember 3 letters (d for day, w for week, m for month). But there is also the possibility to use the + sign. 

+7 --» next week
+14 --» in two week
+365 --» next year

It’s more fast to type "+1" than "tomorrow" (or "demain" in french or "mañana" in spanish)

In addition, software usually uses the @ sign to introduce tags/labels.

**Comment by alainm23** [comment]
Thanks to the new date recognition system, the implementation of this feature will be very easy.
![Peek 2020-09-22 10-19](https://user-images.githubusercontent.com/33765137/93902810-9f4f1500-fcbd-11ea-8a48-750154ee2bfe.gif)

**Comment by bepolymathe** [comment]
Great 👍 Thanks.

**Comment by bepolymathe** [comment]
Hi @alainm23 

Happy New Year! A few suggestions to make this feature even more effective. 

1. Add more options for the coming week (or 2 weeks). On a daily basis I need to choose more options than tomorrow (1d) or next week (1w). I suggest the following additions: 

1d --» +1 day (tomorrow)
2d --» +2 days
3d --» +3 days
4d --» +4 days
5d --» +5 days
6d --» +6 days
1w --» +7 days

And maybe same for old task

-1d --» -1 day (yesterday)
etc

In general we could have a very advanced practice of this with equivalences of the type 1w1d = 8d and I could make proposals for that but you would have to imagine the possibility of making it optional for users in the options. Either that activates these shortcuts. Either they are not activated by default...

2. When typing "1d" in the note title, it would be nice if this disappears once the date has been selected. What do you say?

3. Could we imagine the same system of additions for labels? Or we could create at least a keyboard shortcut to add labels quickly because we have to validate the task and go back in to add a label.
