### ISSUE TITLE
Sync projects created in offline mode to todoist

### ISSUE THREAD

**Issue by Suzie97** [alainm23/planify#525]
I created all my projects in offline mode. Now I want to sync them with todoist so that I can view them using the todoist official app on other platforms like android and Mac. I am frustrated because all the tasks are very crucial in my life. There are some really important ideas and tasks that are very important to me. 

I would like to be able to sync my projects created in offline mode to todoist. 

I looked for a way to sync my offline projects with todoist but I couldn't find a way to do so. 

I really wish this feature gets introduced because it is going to make the already fantastic app even

**Comment by alainm23** [comment]
Fixed in v2.5
