### ISSUE TITLE
Black rectangle padding on main window

### ISSUE THREAD

**Issue by alex-bender** [alainm23/planify#527]
I've just installed app and see that main window is outlined with black rectangle.
This black area is transparent for clicks, i.e. it's possible to click at the link if web page is behind planner window being covered under that black rectangle.
**Screenshots**
![image](https://user-images.githubusercontent.com/3628862/94136288-66ee3900-fe6d-11ea-894e-cea8c59859e3.png)

**Desktop:**
- OS: Ubuntu 18.04
- DE: KDE 5.44.0 / Plasma 5.12.9
- WM: KWin

**Additional context**
Installed via flatpack

**Comment by yannicka** [comment]
Check #268, your issue is a duplicate

**Comment by alainm23** [comment]
Unfortunately this is a bug in the elementary OS stylesheet that other applications like Akira also suffer from. It's unlikely we will fix it here. 

We can reopen if elementary refuses the issue.

elementary/stylesheet#843
