### ISSUE TITLE
Feature Request: Add ability to export database from command line. 

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#529]
With planner now migrated to the new json export and import system, it would be really cool if planner had an option to export the database from the commandline. With that feature we could add it to boot time scripts or cron to automate task backups. All that would be needed is to ask the user for the path of the export file on the commandline. So for example.

`planner --export-database ~/Documents/TasksBackup-2020-09-24.planner`

**Comment by alainm23** [comment]
This functionality is now available in Planify 4.3.
