### ISSUE TITLE
"Fund" button on "what's new" window takes a long time to open the website.

### ISSUE THREAD

**Issue by pedrofleck** [alainm23/planify#530]
**Describe the bug**
I just updated Planner (flatpak) and it opened a "What's new" window, in the bottom of the window, there were a "fund" button, I clicked it and nothing happened. Then I clicked a few more times. A tab opened on Firefox like 3 minutes later and then other tabs opened after more minutes waiting. It doesn't seem to be a fixed time, but a long time anyway (the last one opened more than 5 minutes after I clicked on it). Both Planner and Firefox are on a NVMe SSD, Firefox was already opened and other external links on Planner work as expected.

**To Reproduce**
1. Open Planner after an update that triggers the "What's new" window.
2. Click on the "fund" button.

**Expected behavior**
A new tab be opened immediately on my browser.

**Desktop (please complete the following information):**
 - OS or DE: Fedora 32, Gnome 3.36.
 - Version: 2.4.6

**Comment by alainm23** [comment]
I wish I could fix it but it seems to be a bug from Gtk or your system.
