### ISSUE TITLE
One of my project's tasks are duplicated (or triplicated).

### ISSUE THREAD

**Issue by pedrofleck** [alainm23/planify#531]
**Describe the bug**
There are a "story" for this in the additional context, but I'm describing the bug I have after hitting "Redefine all" and syncing with Todoist: I have a few projects, one of them have the tasks triplicated (more in "screenshots" below). In "today" and "next" views, the tasks from this project are only duplicated, while the other tasks are fine.

**Expected behavior**
Tasks showing like in Todoist.

**Screenshots**
I can show it privately, if needed, there are personal stuff on the tasks (it is the "Personal" project).
But it is basically:
* Task 1
* Task 2
* Task 3
 [sep 27]
* ...
* Task 1
* Task 2
* Task 3
[sep 27]
* ...
* [one more time]

**Desktop (please complete the following information):**
 - OS or DE: Fedora 32 with Gnome 3.36.
 - Version: 2.4.6

**Additional context**
Before that, I've been some time away from Todoist/Planner until I came back to it this week, then when I opened it, all my projects were duplicated (including the "Getting started" - I don't know the exact word used in English - with the rocket emoji). So I noticed there was an update, and after that, my Todoist account wasn't synced anymore, but all my projects were there and were not duplicated. Then I logged in again with Todoist and all my projects got duplicated again. So, I went to Preferences > General > Redefine all (in "Danger Zone"). Btw, I had this problem on my laptop too.

**Comment by alainm23** [comment]
Thank you very much for using Planner. For v2.4 we did a restructuring of the Planner database to be able to use Quick Add on all platforms.

To fix this error you can restart the Planner databases and synchronize your Todoist account.
Go to `Preferences` > `General` > `Reset All`, Close Planner and re-sync your Todoist account.

**Comment by pedrofleck** [comment]
I did try to reset all, but it didn't work. But now it just fixed by itself, everything seems to be working fine. Thanks!
