### ISSUE TITLE
Fearure request: Hide all details (collapse all)

### ISSUE THREAD

**Issue by alexios-tsiaparas** [alainm23/planify#532]
When I am reviewing the tasks for the day, I normally open each one in order to see any notes. When finished ordering them, I would like to collapse all of them, so that more can fit in my screen. This seems to be impossible currently.

We could add a keyboard shortcut (I personally prefer them) to accomplish that, and maybe even an icon next to the view (Inbox, today, upcoming, project), like the hide details button on each task.

**Comment by alainm23** [comment]
I'm using a keyboard shortcut for testing: `Shift + h` but this is yet to be defined.
