### ISSUE TITLE
Window theme problem

### ISSUE THREAD

**Issue by alexios-tsiaparas** [alainm23/planify#533]
**Describe the bug**
I build the application and install it according to the instructions in the README.md and install it in /usr. The theme has serious deficiencies, as shown in the included screenshot.

**To Reproduce**
1. Fork and clone the repository
2. Start terminal and navigate to the repository source
3. Execute meson build --prefix=/usr
4. Execute cd build
5. Execute ninja
6. Execute sudo ninja install
7. Execute com.github.alainm23.planner

**Expected behavior**
I expected to see something similar to the screenshot when I install the application from flathub, as depicted below.

**Screenshots**
![image](https://user-images.githubusercontent.com/54047840/94361874-17ec1200-00c0-11eb-8bf9-3af328763458.png)
*Output after build*

![image](https://user-images.githubusercontent.com/54047840/94361903-48cc4700-00c0-11eb-8056-d649ad75c4a5.png)
*Output when installing via flathub*

**Desktop (please complete the following information):**
 - OS or DE: Fedora 32 Workstation with GNOME
 - Version Planner 2.4.6 installed / latest master build

**Additional context**
It seems that the CSS code seems lacking some rules, as I was able to correct some of the problems in my tests, although I have no way of testing my changes to other distributions, and do not know which distributions the project tests against.

**Comment by alexios-tsiaparas** [comment]
I tried to find the differences between the system here and my installation, but I managed to not read that in Fedora 2 packages are essential for the correct UI experience:

* elementary-theme
* elementary-icon-theme

I installed them and everything is in order.

**Comment by markallasread** [comment]
This is still an issue.
Anyone mind providing the dummie's guide to customization, color-wise? Happy to just make modifications manually if there's a theme file or similar.
