### ISSUE TITLE
Issue: Task with # in name can't be added

### ISSUE THREAD

**Issue by esszed** [alainm23/planify#538]
**Describe the bug**
When creating new task with # somewhere in its name the task will just disappear and is not added anywhere

**To Reproduce**
1. Create new task anywhere in the app
2. Put **#** symbol anywhere in the task
3. Task disappears and is not added

**Expected behavior**
Adding taks with # in the name

**Video:**
https://i.imgur.com/FIDELSs.mp4

**Desktop (please complete the following information):**
 - OS or DE: Manjaro with Plasma
 - Version: 19.0.2

**Comment by alainm23** [comment]
This error has already been solved in the master. Wait for the new update.
