### ISSUE TITLE
Strange UI on i3wm

### ISSUE THREAD

**Issue by devarshirawal0111** [alainm23/planify#541]
**Description**:

![2020-09-30-145519_1920x1080_scrot](https://user-images.githubusercontent.com/23256745/94667897-00fe2780-032d-11eb-8d34-a6b497e3d475.png)

As seen in the above image, planner UI is not same as when used in any other DE. It shows a black padded area around it's windows.

I am using Arch Linux with i3-gaps. This happens in both AUR packages 
1. [elementary-planner](https://aur.archlinux.org/packages/elementary-planner/)
2. [elementary-planner-git](https://aur.archlinux.org/packages/elementary-planner-git/)

This issue also persists in Flatpak as well as Fedora rpm package. I have installed elementary-gtk-theme and elementary-icon-theme too.

**Comment by yannicka** [comment]
Check #268, your issue is a duplicate
