### ISSUE TITLE
Flathub install not showing emoji

### ISSUE THREAD

**Issue by 73** [alainm23/planify#548]
**Describe the bug**
Flathub installed application is not showing emoji

**To Reproduce**
1. Install from [flathub](https://flathub.org/apps/details/com.github.alainm23.planner)
2. Click on 'Getting Started'
3. See error

**Expected behavior**
I would expect to see emojis.

**Screenshots**
![image](https://user-images.githubusercontent.com/529346/95093729-5ec5b180-0729-11eb-9a0a-65ca2f6dc88f.png)

**Desktop (please complete the following information):**
 - Ubuntu 20.04 
 - Version 2.5

**Additional context**
I have not used planner before, so  I don't know whether a prior version was okay.

**Comment by alainm23** [comment]
Maybe this is the solution you are looking for. #196

**Comment by 73** [comment]
> Maybe this is the solution you are looking for. #196

Na. I have noto-color-emoji installed. However, investigating further I see it is not planners fault, but hits all my flatpak apps.
