### ISSUE TITLE
Issues with duplicate tasks

### ISSUE THREAD

**Issue by brcmesquita** [alainm23/planify#55]
When you duplicate a task, the planner does not create a second task, it repeats the same task. When you change one of the duplicate tasks, they all change together. When you delete a duplicate task, all are deleted.

**Comment by alainm23** [comment]
Thanks for reporting the error, fix this in the next release

**Comment by brcmesquita** [comment]
Thx, guy!

**Comment by eliocamp** [comment]
This is happening to me when I have multiple tasks in the same project even when just adding them normally (no duplication).

**Comment by alainm23** [comment]
@eliocamp This bug happens because you will surely create a task with the same name.

**Comment by eliocamp** [comment]
They had different names but they changed to the same task somehow. But now I opened the app and they are correctly there, like it never happened 🤔️

**Comment by rafaelcn** [comment]
This bug also affects the `today`'s page. It's kind of strange because if you create two tasks and minimize one the other one gets the same content of the one who has been minimized already.

**Comment by simon-co** [comment]
If you click create task it copies the previously made task, and overwrites new task.  Minimising tasks overwrites all tasks with the first one created.  If you delete all the tasks which are now all copies of one another it only shows as one task removed but removes all from the interface until you try adding a new task or leaving the page.

**Comment by alainm23** [comment]
Thank you very much for reporting the problem, and I have been busy working at Byte and at the university, I will do my best to correct these errors as soon as possible.
