### ISSUE TITLE
Sync between different instances

### ISSUE THREAD

**Issue by theunclemez** [alainm23/planify#550]
Well I'm happy with the app but, because i run it on Manjaro which is not that bleeding edge distro, I miss the recent improvement and the recent version, I was then told to install the flatpak version but I'm afraid I'll have to redo everything from the beginning.

My approach of solution would be that, Planner to be made capable to sync local datas from one instance to another like flatpak get stuffs from preinstalled binary on the distro.
Like does the browsers when we add a new one it takes contents from any other browser installed before, this would help us not redo everything from the very beginning.

A good alternative would be the app installed as flatpak or native to offer a dialog box allowing us to point to the files location so tasks and project can be synched  in a more manual way but still allow to loose nothing or redo nothing from the very beginning.

**Comment by RussianNeuroMancer** [comment]
Support of something like NextCloud (or WebDAV protocol) also would be much appreciated.

**Comment by williamd1k0** [comment]
For a workaround, you can just create a hard/sym-link to the `planner.db` file.

**Comment by theunclemez** [comment]
> For a workaround, you can just create a hard/sym-link to the `planner.db` file.

Good idea but not everyone is geek or knows how to do such tricks.
It should be made easier for everyone pick the thing straight without too much struggle

**Comment by BeatLink** [comment]
Couldnt both planner instances log into the same todoist account and use that as an intermediary sync server? Alternatively, the upcoming CalDAV support will allow caldav task apps such as nextcloud to be used as sync servers as well.

**Comment by RyanGreenup** [comment]
For reference the location of the `planner.db` file is [mentioned here](https://github.com/alainm23/planner/issues/191#issuecomment-616628820). Although for me (on Arch with v 2.6.9) it seems to be called `database.db` so:

```bash
# Make a Directory Location
mkdir ~/Sync/Documents/alainm23-Planner/

# Move the Data base
mv ~/.local/share/com.github.alainm23.planner/database.db ~/Sync/Documents/alainm23-Planner/

# Symlink the Database
ln -s ~/Sync/Documents/alainm23-Planner/database.db ~/.local/share/com.github.alainm23.planner/database.db
```

**Comment by HansCronau** [comment]
@RussianNeuroMancer:
> Support of something like NextCloud (or WebDAV protocol) also would be much appreciated.

You might be interested in issue #555 CalDAV Support, which I hear is coming soon.
