### ISSUE TITLE
On a tiled window manager (i3), all windows are wrapped with black margins

### ISSUE THREAD

**Issue by andreesteve** [alainm23/planify#553]
**Describe the bug**
On a tiled window manager (i3), the main window and any popup windows also include a black background / margin around it.

**To Reproduce**
1. Go to the settings page

**Expected behavior**
The about page/settings page should not be wrapped with a black background (margin).

**Screenshots**
![image](https://user-images.githubusercontent.com/942449/95153552-86764300-0744-11eb-9bf9-6985ed188e46.png)

**Desktop (please complete the following information):**
 - OS or DE: i3 (Xorg)
 - Version 2.5

**Additional context**
This happens independently whether I switch the window from tiled to floating on the window manager.
I tried searching for a similar issue on i3 forums but I did not find anything that rings a bell.

**Comment by alainm23** [comment]
Duplicate #268
