### ISSUE TITLE
Rescheduled tasks and time setting

### ISSUE THREAD

**Issue by rzelnik** [alainm23/planify#554]
**Describe the bug**
I have some missed tasks that have schedule date set, but not schedule time. When I reschedule it for example from yesterday to today, they show schedule time "now", although they should not show any time, just the date "today".

**To Reproduce**
1. Create a task, set it's schedule to today, leave Time setting untouched (turned off)
2. Wait one day
3. Click to Today in the left sidebar
4. Click to reschedule
5. See the task showing current time as schedule time 

**Expected behavior**
When I not set a schedule time, it should not show any time.

**Desktop (please complete the following information):**
 - OS or DE: Ubuntu 20.04.1 LTS
 - Planner Version: 2.5

**Comment by alainm23** [comment]
I can confirm the bug, It'll be fixed.
