### ISSUE TITLE
Duplicated task doesn't have check list from original

### ISSUE THREAD

**Issue by raggesilver** [alainm23/planify#558]
**Describe the bug**
Duplicating a task doesn't duplicate it's checklist.

**To Reproduce**
1. Create a task with some checklist items
2. Duplicate the task you just created
3. Checklist doesn't exist in the duplicated task

**Expected behavior**
The checklist from the original task should be copied over to the duplicated one.

**Desktop (please complete the following information):**
 - OS or DE: Fedora 33 / Gnome 3.38
 - Version: Flatpak 2.5.3

```
          ID: com.github.alainm23.planner
         Ref: app/com.github.alainm23.planner/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.5.3
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 107.0 MB
     Runtime: org.gnome.Platform/x86_64/3.36
         Sdk: org.gnome.Sdk/x86_64/3.36
```

**Comment by alainm23** [comment]
Sorry for the delay, it has been fixed, please wait for the next update.
