### ISSUE TITLE
Showing completed tasks is virtually useless

### ISSUE THREAD

**Issue by raggesilver** [alainm23/planify#559]
**Describe the bug**
Sorry about the issue title, but it's kinda true. If you select "Show completed tasks" they will appear on the board once again but seeing it is all you can do. I think it would be expected for one to be able to expand the completed task and see it's contents. This gets particularly annoying with tasks that have checklists because if you want to see the task's contents you have to mark it as not completed and that will reset **all** of it's checklist's checkboxes back to not completed.

**To Reproduce**
1. Create a task with description/checklist
2. Mark it as complete
3. Click "Show completed tasks"
4. Try to expand the completed task to see it's contents

**Expected behavior**
> I think it would be expected for one to be able to expand the completed task and see it's contents

**Desktop (please complete the following information):**
 - OS or DE: Fedora 33 / Gnome 3.38
 - Version: Flatpak 2.5.3

```
          ID: com.github.alainm23.planner
         Ref: app/com.github.alainm23.planner/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.5.3
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 107.0 MB
     Runtime: org.gnome.Platform/x86_64/3.36
         Sdk: org.gnome.Sdk/x86_64/3.36
```

**Comment by BeatLink** [comment]
Seems like a duplicate of https://github.com/alainm23/planner/issues/415

**Comment by raggesilver** [comment]
Indeed, closing

**Comment by alainm23** [comment]
Update to v2.5.4 please.

![image](https://user-images.githubusercontent.com/33765137/95775027-2d983480-0c87-11eb-8c61-b350175a1b08.png)

**Comment by raggesilver** [comment]
Thanks for the update!
