### ISSUE TITLE
Order of created tasks

### ISSUE THREAD

**Issue by rzelnik** [alainm23/planify#560]
When I create a new task outside a section, it stored at the bottom of the list. When I create a new task inside a section, it is stored at the top of the section list. Isn't it inconsistent? IMHO it would be better to have a possibility to set a preferred order - top-down or bottom-up orders (in the settings). If I prefer top-down order, I would prefer it in both cases - inside a section and outside the section.

**Comment by rzelnik** [comment]
It seems like this issue was already fixed. I am closing this ticket.

**Comment by alainm23** [comment]
I'll add an option that the user can select if the task is created at the beginning or at the end of the list and other preferences that I already have in mind.
