### ISSUE TITLE
libedataserver-1.2.so.24 No such file or directory

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#561]
Planner is not starting.

After command ``planner`` or clicking an icon nothing happens. It just throws the error:

```
planner: error while loading shared libraries: libedataserver-1.2.so.24: cannot open shared object file: No such file or directory
**Expected behavior**
```
I am on Arch Linux, and recently updated my gnome version from 3.36 to 3.38. The package evolution-data-server was updated as well. As far as I understand libedataserver-1.2.so.24 is a part of evolution-data-server.

**Comment by alainm23** [comment]
Thank you very much for using Planner, did you install Planner from Flathub? If not, I recommend you do it to avoid this type of bug.

**Comment by devarshirawal0111** [comment]
I am also facing this issue. I use i3wm, installing from flathub will cause me issues with the black box surrounding the app. 

I downgraded the evolution-data-server package by 1 version. It's a workaround than a solution.

**Comment by RuthlessRuler** [comment]
evolution-data-center v3.38.1-1 from arch works with v2.5.7 of the app. So i guess this issue should be closed now.

**Comment by BeatLink** [comment]
Closing the issue for now. 

@MaciekZar Try installing the latest version of planner. If the issue still exists, feel free to open a bug report
