### ISSUE TITLE
Huge frame around the window app 

### ISSUE THREAD

**Issue by Magnus512** [alainm23/planify#566]
**Describe the bug**
The app starts with a big frame around, in awesome wm and I believe another wm also

**To Reproduce**
1. Open Planner in awesome wm
2. Application starts with huge frames

**Expected behavior**
Normal frames or no frame in the window app

**Screenshots**
![2020-10-12_16-00](https://user-images.githubusercontent.com/7065012/95794185-8e823580-0ca4-11eb-85a2-4c6515275db7.png)

**Desktop (please complete the following information):**
 - OS or DE: ArchLinux Awesome WM

**Comment by williamd1k0** [comment]
This seems to be a problem with the window composer.

**Comment by asakura42** [comment]
Same in i3-gaps. And for me this works: https://github.com/alainm23/planner/issues/303#issuecomment-613968198

**Comment by alainm23** [comment]
Duplicate #303
