### ISSUE TITLE
App shuts down when moving a task to the bottom

### ISSUE THREAD

**Issue by ksuzu46** [alainm23/planify#568]
**Description**
The app behaves fine unless the moving destination is at the bottom, but it shuts down when you try to move the task to the bottom of the list.

**To Reproduce**
1. Go to a project
2. Create two or more tasks
3. Drag and move down one of the tasks to the bottom
4. App shuts down

**Screenshots**
![bug](https://user-images.githubusercontent.com/33506119/96215472-1a69bb00-0f4c-11eb-82c2-a84dda2fffdc.gif)

**Desktop**
 - OS: elementary OS Hera
 - Version: 5.1.7

**Comment by alainm23** [comment]
Duplicate #563. Update yo v2.5.4
