### ISSUE TITLE
Feature Request: Ability to show labels in the sidebar

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#571]
**Is your feature request related to a problem? Please describe.**
I'd love to use labels more but needing to click on the quick find menu slows things down.

**Describe the solution you'd like**
I'd like each label to have a toggle that determines whether it's showed in the side bar below the Inbox, Today and Upcoming events

**Describe alternatives you've considered**

**Additional context**

**Comment by alainm23** [comment]
Of course, it's one of the new features in Planner 2.6

**Comment by BeatLink** [comment]
Awesome!
