### ISSUE TITLE
Plugin Support

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#572]
Implementing a plugin system would help make planner easier to maintain as well as more customizable to individual users taste. It will help reduce bloat and feature creep by allowing the application to have a small, solid core, while still allowing users to install as many plugins as they want or need to suit their purposes.

**Comment by alainm23** [comment]
I like the idea.

**Comment by BeatLink** [comment]
Awesome! As a step further, once this is implemented, you could reimplement existing core features as separate plug-ins as well. Completely up to you though, and its something to think about *after* the plug-in support is implemented so you can sleep on it.

**Comment by alainm23** [comment]
I just uploaded a [basic plugin system implementation](https://github.com/alainm23/planner/commit/1c84365aa8ee4c94bcbdf5d1f0e9a469762933bd) but now I don't know how to make it work, I think I'll need some help.

**Comment by BeatLink** [comment]
Hmm. Okay, ill take a look at the codebase when I can and see what I can do.

**Comment by BeatLink** [comment]
But basically, a typical plugin architecture works by passing parts of the application you want plugins to access as parameters to the plugin initializer. To start out, you could pass broad generic objects, (such as the window object, database manager object and so on) but down the line you will want to create more specific objects and functions to limit plugin access, improve security and prevent breaking and crashing when plugins conflict with each other or try to access the same object at the same time

**Comment by alainm23** [comment]
I'm very happy to announce that the plugin system works 🎉️🎉️🎉️

![Plugin DEMO](https://user-images.githubusercontent.com/33765137/97333200-4557e700-1849-11eb-80f7-4dd5bd794d13.gif)

This plugin gives solution to #571 and it is only the first step for a new Planner.

**Comment by BeatLink** [comment]
Awesome!

**Comment by skaldebane** [comment]
Great job! This'll make it easier to make custom plugins for custom needs. Waiting for documentation once it's done 👌

**Comment by airtonix** [comment]
@alainm23 I might be a bit dense, but does this only load plugins from the apps directory ? or does it also load them from something like `~/.config/planner/plugins` ?
