### ISSUE TITLE
Completing a recurring task hides it from the current view

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#577]
**Describe the bug**
When you click on the checkbox to complete a recurring task, it is hidden from the current view and can only be seen again by switching to another view or restarting the app

**To Reproduce**
1. Create a recurring task
2. Click on its checkbox to complete it
3. Notice that it disappears instead of just updating the due date

**Expected behavior**
The task should remain visible and its due date updated instead.

**Screenshots**

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint Cinnamon
 - Version 2.5.6

**Additional context**

**Comment by Leon0402** [comment]
Can confirm this. Although I thought it was by design and just wanted to make a feature request :-)
