### ISSUE TITLE
Customizable repeat delay for recurring tasks

### ISSUE THREAD

**Issue by skaldebane** [alainm23/planify#580]
Hi! Could you implement something similar to the repeating tasks in Todoist? Sometimes 7 days feels very little and 15 feel so much and it would be great if we can choose a custom delay (e.g. every 2 days)

In Todoist there's a text field for that (just like how you parse time in the latest version) where you can write something like "every 2 days" and it automatically repeats that task every 2 days.

**Comment by BeatLink** [comment]
Sounds like a duplicate of https://github.com/alainm23/planner/issues/389. It seems to be a well desired feature! You can just close this, head on over and give the open one a thumbs up.

**Comment by skaldebane** [comment]
Thanks for informing! I'll close this right away.
