### ISSUE TITLE
Sync with Caldav tasks

### ISSUE THREAD

**Issue by bitsandnumbers** [alainm23/planify#59]
Hi,

Is it possible to add CalDav sync for tasks ? ElementaryOS has a good implementation of CalDav with its Calendar app, but it lacks Tasks support. Adding this feature to Planner would allow to make it the standard companion to the Calendar app. It also mean that you can check how eOS devs have implemented it in the first place by checking the source code...

Thanks

**Comment by corbin-auriti** [comment]
I would love to see this and possibly help contribute this.

**Comment by marbetschar** [comment]
Any plans on integrating this? Would love to be able to sync Planner with Nextcloud.

**Comment by corbin-auriti** [comment]
Why was this closed?

**Comment by alainm23** [comment]
Thank you very much for your comments. Now I am working on a new version of Planner with support for Todoist and local tasks, sorry, I think Planner will not be able to use Caldav tasks.

But this functionality is being worked on https://github.com/elementary/tasks
