### ISSUE TITLE
Task dissapearing and reapearing after completed.

### ISSUE THREAD

**Issue by lulivi** [alainm23/planify#591]
**Describe the bug**

When having the "Show completed" checked, if you mark a task as completed, it desapears for 2 or 3 seconds and then appears again at the end of non-completed tasks.

**To Reproduce**

1. Go to some project with 3 oppened tasks
2. Mark the middle task as completed
3. See it desappear for some secconds despite the option "Show completed" is checked
4. Then see it appear again after some seconds at the end of the open tasks list

**Expected behavior**

Don't desappear and then appear again and maybe remain in the same spot.

**Screenshots**

![planner-hide](https://user-images.githubusercontent.com/10894592/97701885-62412400-1aae-11eb-975d-df1a1449359d.gif)

**Desktop (please complete the following information):**

 - Archlinux (XFCE)
 - 2.5.7 ([AUR](https://aur.archlinux.org/packages/elementary-planner-git))

**Additional context**

Pretty cool aplication though, Great work!

**Comment by lulivi** [comment]
Maybe an option could be to optionally disable animations?

**Comment by alainm23** [comment]
This is not a bug, this feature was implemented on purpose to keep completed and uncompleted tasks in order.

@lulivi We could add this option in the preferences to remove the undo option, but the order of the tasks will always remain, completed at the beginning and uncomplete at the end.

**Comment by lulivi** [comment]
Then, I may create a feature request instead of a bug report. Thank you for the response @alainm23 ! Should I close the issue?

**Comment by BeatLink** [comment]
So you would like a feature request to disable animations?

**Comment by raggesilver** [comment]
I mean, I wouldn't call what Planner currently has an animation. It does have slide-out and slide-in animations but the main issue here is that there's huge delay between the time a completed task disappears and comes back as a completed task.

Personally, I'd just like to see a regular task becoming green (as it does after the animations) without sliding in or out.

**Comment by alainm23** [comment]
This feature is already available in Planify, best regards.
