### ISSUE TITLE
Improve "Convert to Todoist" behavior

### ISSUE THREAD

**Issue by Miqueas** [alainm23/planify#592]
I recently created a free Todoist account to synchronize my local Planner projects with that account. However, I didn't know that free accounts were limited to 5 projects. While I was converting my local projects to Todoist projects, after 3 successful conversions, the next 2 simply disappeared and nothing else happened. It was at that moment that I went to my Todoist account to see what was going on and believe that it was some problem with Planner and my internet connection. At that moment I could see that it was not and that it was just the limit of my free account.

That said... The problem here is that, I lost 2 local projects with a lot of information and at the moment I don't know how to recover (and I think it's not possible). Therefore, I want to suggest to change or improve Planner's behavior in that aspect and instead of simply losing the projects, notify the user about it with something like a `Gtk.Dialog` (just to mention an example).

**Comment by esszed** [comment]
That's strange. According to todoist [webpage](https://todoist.com/pricing) free accounts are limited to 80 projects. Myself I have no issue having multiple todoist projects or converting new local ones.

**Comment by Miqueas** [comment]
> That's strange. According to todoist [webpage](https://todoist.com/pricing) free accounts are limited to 80 projects. Myself I have no issue having multiple todoist projects or converting new local ones.

Well... Not that it's happening exactly, but I simply can't have more than 5 projects on my Todoist account :/

**Comment by BeatLink** [comment]
So sorry to hear you've lost data. Maybe the data is still in the database but not shown in the GUI. You could try navigating to the database file, creating a copy and opening that copy with an SQL browser like Sequeler or DB browser for SQLite. A bit hard to do but its better than loosing your project files for good.

**Comment by Miqueas** [comment]
> So sorry to hear you've lost data. Maybe the data is still in the database but not shown in the GUI. You could try navigating to the database file, creating a copy and opening that copy with an SQL browser like Sequeler or DB browser for SQLite. A bit hard to do but its better than loosing your project files for good.

Oh, thats a good idea, I'll try it now!

Note: sorry for the delay, I thought this issue was closed.

**Comment by Miqueas** [comment]
Also, idk what happens with the todoist pricing page. I open the link that @esszed mentioned in a private window, and looks like this:

![image](https://user-images.githubusercontent.com/31262466/104620576-23f2e400-565d-11eb-92e1-b2023870f47d.png)
> Free accounts can have 80 projects

But opening the same link in a normal window:

![image](https://user-images.githubusercontent.com/31262466/104621190-d5921500-565d-11eb-81bf-0f7dfd3b17e8.png)
> Only 5 projects for free accounts

Maybe the problem is the region or something :thinking:
