### ISSUE TITLE
[Feature request] Crosssing out completed (sub)tasks

### ISSUE THREAD

**Issue by esszed** [alainm23/planify#594]
I think it would help visual clarity to have completed tasks, besides the "completed" tick, also crossed out. This applies especially to the subtasks as there is no option for them to disappear after completion. It seems to be the norm across todo applications and I think for good reason. Slightly graying out the completed (sub)task could also be a nice addition. 

![Screenshot_20201030_235031](https://user-images.githubusercontent.com/56234798/97763739-d27e9280-1b0c-11eb-9411-121830c553df.png)

**Comment by alainm23** [comment]
We could add this as a personal option to enable in the preferences.

**Comment by esszed** [comment]
I wouldn't mind it being on by default, but having it optional is of course the best way. I thought of it when I looked at my subtasks, which some were completed and some were not and could not clearly distinguish between them at first glance. When the tasks are crossed out, our mind automatically skips them, which would enhance the first glance clarity and make it easier to focus on the task to be yet finished.
