### ISSUE TITLE
problem with planner tutorial

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#595]
It seems that the Planner tutorial dosent work for me. 

in the getting started section it asks me to add a new task.
when i add a new task nothing changes in the tutorial.

I do not know if i misunderstood the tutorial or if dosent work for me ?

thanks for your help. 
![Bildschirmfoto von 2020-11-01 15-13-58](https://user-images.githubusercontent.com/49533360/97805195-eb925b00-1c54-11eb-94d1-258985f4ed9d.png)

**Comment by alainm23** [comment]
The tutorial project is like any other project, it doesn't do anything special, it just tells you the things you can do with Planner.
