### ISSUE TITLE
Add ability to sort tasks by due time

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#598]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alainm23** [comment]
This feature is already available in the current version, you can verify it.

![image](https://user-images.githubusercontent.com/33765137/100530659-a107ee00-31c2-11eb-94e4-0fef975caa25.png)

**Comment by BeatLink** [comment]
It does work! Thanks! I guess what I really needed was #597

I just gotta say, I really really appreciate how much you listen to feedback from the community. Not many developers do that. I cant wait until I can start contributing regularly to planner. It's the best to-do app on linux!
