### ISSUE TITLE
Stop storing data in cache folder

### ISSUE THREAD

**Issue by naaando** [alainm23/planify#60]
Nice app man, I noticed that you're storing user data in cache directory, this doesn't seem right because an app like Optimizer can wipe the cache and erase it (which happened to me), I suggest that it should be saved directly on home or inside a directory for the application starting with an . to hide it as described [here](http://www.pathname.com/fhs/pub/fhs-2.3.html#HOMEUSERHOMEDIRECTORIES).

**Comment by naaando** [comment]
This is a bit obvious but worth noting that you may need to move the content from cache to home.

**Comment by ghost** [comment]
Or like other apps move to `~/.config/`

**Comment by naaando** [comment]
You're right, seems that using `~/` to store data was the before freedesktop standard.

But I don't think `~/.config` is the best place either because it is meant for configuration files so it isn't that safe also (backup tools might ignore these, users can delete it, etc.), the most appropriate place seems to be `$XDG_DATA_HOME` that is `~/.local/share/`

**Comment by alainm23** [comment]
Thank you very much I will take it into account in a next release

**Comment by dkotik** [comment]
I found the database under ~/.var/app/com.github.alainm23.planner/data/com.github.alainm23.planner
has it been moved to ~/.local/share? I wish the app itself would give some kind of indication where data is stored, so it could be synced and backed up easily without having to google

**Comment by romixch** [comment]
Coming in the next release.

**Comment by alainm23** [comment]
We have not made any changes to the database location yet but it will change for v2.4 thanks to @romixch. The idea is that the installation of Planner from App Center or Flathub have the same database location.

Database current location:
**AppCenter**
`~/.local/share/com.github.alainm23.planner`

**Flatpak**
`~/.var/app/com.github.alainm23.planner/data/com.github.alainm23.planner`

![image](https://user-images.githubusercontent.com/33765137/81197214-a3380000-8f85-11ea-9ee4-bc3b87fd4c1a.png)
