### ISSUE TITLE
Progress indicator for each task of a project

### ISSUE THREAD

**Issue by ttsesm** [alainm23/planify#600]
**Is your feature request related to a problem? Please describe.**
Not really, this is more like a suggestion enhancement proposal

**Describe the solution you'd like**
As you have a progress indicator for each project, it would be nice to have one as well for each task of the project, especially if there are subtasks on a task.

**Comment by alainm23** [comment]
Planner already has this feature implemented.
![image](https://user-images.githubusercontent.com/33765137/99260126-fa4a4780-27e8-11eb-8997-46df685e6fb8.png)
