### ISSUE TITLE
Add possibility for notes in subtasks

### ISSUE THREAD

**Issue by ttsesm** [alainm23/planify#601]
**Describe the solution you'd like**
Add the possibility to create individual seperate notes for subtasks of a task.

**Comment by BeatLink** [comment]
The easiest way to implement this would be to treat subtasks as full featured tasks with notes, labels, priorities and all the other bells and whistles. 

That is already being proposed in https://github.com/alainm23/planner/issues/540, so you can close this as a duplicate and express your request for this feature there

**Comment by ttsesm** [comment]
Transfer discussion to https://github.com/alainm23/planner/issues/540
