### ISSUE TITLE
Add hotkey for "Hide Detail"

### ISSUE THREAD

**Issue by jorg-j** [alainm23/planify#602]
**Is your feature request related to a problem? Please describe.**
When clicking through Items the detail box remains open on previously selected items. This would be useful in some situations but the option to hotkey hide detail for all items would be a good clean addition

**Describe the solution you'd like**
GIVEN I press a keyboard shortcut/hotkey
THEN All non hidden item detail boxes will be hidden

**Describe alternatives you've considered**
None

**Comment by alainm23** [comment]
This feature is already available in the current version, try `Ctrl + H`
