### ISSUE TITLE
Stuck on creating a new synced task

### ISSUE THREAD

**Issue by inputsh** [alainm23/planify#603]
**Describe the bug**

Every now and then, Planner just spins after clicking on "Add Task".

**To Reproduce**

I can't reliably reproduce it.

**Expected behavior**

A task will be added.

**Screenshots**

![Screenshot from 2020-11-05 10-15-33](https://user-images.githubusercontent.com/4890548/98221408-df0d4b80-1f4f-11eb-80d6-737e389a8c28.png)

Took this screenshot about 3 min after creating a new task.

**Desktop (please complete the following information):**
 - OS or DE: Pantheon
 - Version: Whatever's latest on elementary OS stable. 

The only way around this issue is to force-kill the app, start it again, and re-create a task.

I realize I didn't really manage to provide a lot of info, so if there's something I can provide you with to help get to the source of the issue, I'll gladly do so.

**Comment by alainm23** [comment]
I am adding the possibility to add a task asynchronously and to be able to cancel the process at any time.
