### ISSUE TITLE
quick search and preferences transparent minimal view

### ISSUE THREAD

**Issue by omega3** [alainm23/planify#604]
**Describe the bug**
When quick search window is in minimal window it is transparent:
https://i.imgur.com/AYsFyUS.png
It also looks like a double layer window.

The same with preferences window:
https://i.imgur.com/GUeD38S.png

When quick search window is maximized it looks ok (no transparency):
https://i.imgur.com/ozY250d.png

**Expected behavior**
Minimal window should not be transparent as well. Should look and behave the same as maximized window.

**Additional context**
Also notice that as oppose to preferences window, quick search minimized window doesn't have cloze button.
But I added Plasma 5 titile - window bar. So, I am not sure if this is Planner or not issue. 

**Desktop (please complete the following information):**
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.2
KDE Frameworks Version: 5.75.0
Qt Version: 5.15.1
Kernel Version: 5.4.74-1-MANJARO
OS Type: 64-bit
Graphics Processor: GeForce 210/PCIe/SSE2

Installation 2.5.7 from 
https://aur.archlinux.org/packages/elementary-planner-git/

**Comment by alainm23** [comment]
Unfortunately Planner has some incompatibility issues with KDE, I will close this issue because it is related to #268
