### ISSUE TITLE
add label option to "create new task" in Inbox

### ISSUE THREAD

**Issue by omega3** [alainm23/planify#606]
**Is your feature request related to a problem? Please describe.**
When a plus in Inbox is clicked, "create new task" is made but there is no label option in it:
https://i.imgur.com/KXFdFnF.png
Only when I hit Add task and click on already existing task there is Label icon in it.

So, it is possible to define Priority, schedule it, assign yo project but no possible to add label.

**Describe the solution you'd like**
Label icon should be available when creating a new task.

**Comment by kevinnegy** [comment]
This would be a nice feature for every place where new tasks are created, including projects.
