### ISSUE TITLE
Some events shown with wrong time

### ISSUE THREAD

**Issue by hummerd** [alainm23/planify#607]
**Describe the bug**
Some events displays with wrong time.

**To Reproduce**
Events exported from Exchange. Events in Planner show wrong time 6:00-6:30 (actual is 3:00-3:30)

**Screenshots**
Planner show wrong time
![image](https://user-images.githubusercontent.com/1921665/98462984-2b16f500-21c9-11eb-8ea1-4a4317f2fc70.png)
Evolution shows correct time
![image](https://user-images.githubusercontent.com/1921665/98462966-0f135380-21c9-11eb-88b4-4a3c8b108ad5.png)
Gnome calendar is somewhere in the middle (it shows wrong and write time at the same time)
![image](https://user-images.githubusercontent.com/1921665/98463055-a8db0080-21c9-11eb-92b7-77f2ab01aa48.png)

3 hour difference is probabbly came from my time zone (+3).

**Desktop (please complete the following information):**
 - Ubuntu 20.10  
 - Planner 2.5.7

**Comment by BeatLink** [comment]
This seems like a timezone configuration issue. Would it be possible to review your system configurations so that everything is using the same timezones?

**Comment by alainm23** [comment]
I will close this issue for the time it has been inactive, thank you.
