### ISSUE TITLE
Import/Export Backup

### ISSUE THREAD

**Issue by Chamillo32** [alainm23/planify#609]
I am using Linux Mint 19.3 and I had been using an older version of planner. That version had the option to save the database file at a location of my preference. I bought a new laptop and I want to transfer all the information from the old laptop to the new one, but version 2.5.7 does not have an option to import/export the database. Without that option, planner becomes a brick for me. Can you please consider restoring the option to back up and restore my database? Thank you for your consideration.

**Comment by BeatLink** [comment]
If you are still using the flatpak version, planner stores the database in 

`~/.var/app/com.github.alainm23.planner/data/com.github.alainm23.planner/database.db`

You can install a fresh version of planner on your system, copy the database with your tasks to that location and fire it up. It should work, if I'm mistaken. 

On the off chance it doesn't, ensure you keep a copy of the database with your tasks before you try this, that way you can copy the task information by hand, from the old planner ui to the new one.

If all else fails and as a very last resort, you can open up the database with a database browser app like DB Browser for SQLite and pick through the different data manually.

**Comment by BeatLink** [comment]
Do you still need help with this?

**Comment by skaldebane** [comment]
Hi there. You only mentioned the Flatpak version location, but what about the regular Debian version on elementary OS? I'd like to sync it with Mega so that I never lose my notes again (I've had a disk failure recently, tasks stayed in Todoist but all notes and details are gone as bad sectors touched the database).

**Comment by skaldebane** [comment]
Alright I found it. It's located in `~/.local/share/com.github.alainm23.planner/database.db`.

**Comment by johnblommers** [comment]
Great information! Thanks for sharing as it's very useful.

**Comment by alainm23** [comment]
This functionality is now available in Planify 4.3.
