### ISSUE TITLE
Optimization needed

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#61]
**Laptop info:**
- i3-5005U
- 4GB RAM

With a large number of tasks, the application starts to slow down terribly.
Editing data in the Planner becomes extremely difficult.
Only one CPU core is used.

In idle with all loaded projects consumes ~13% of CPU.

Analysis of slow loading of projects showed that it takes a lot of time to create new TaskRow (over 1000 lines of code, a large part of which is a constructor).

In this regard, I have to edit the data directly in the database.

![25% CPU](https://i.imgur.com/VRUHZ0M.png)

**Comment by alainm23** [comment]
Thanks for the comment, you are right, do not optimize Planner when the user creates many tasks, I will improve it for a next release.

**Comment by Julioevm** [comment]
With just 4 tasks this is idling at 5% cpu, more than chrome on idle. There's some serious optimization needed on this program.

**Comment by alainm23** [comment]
@ie900 You can try Planner 2 to do the same test please. I think that with this new version performance was greatly improved.

**Comment by ghost** [comment]
I don't have the _same_ test anymore, but I'll do a _similar_ one and report the results.

**Comment by ghost** [comment]
| Tasks |   CPU   |
| ----- | ------- |
|  000  | ~00%    |
|  100  | ~03-05% |
|  200  | ~09-10% |
|  300  | ~11-12% |
|  400  | ~13-14% |
|  500  | ~15-16% |

But it no longer suffers from usability issues. Good job.

And also I found bugs:

- When you create a task, it can include all existing tasks (including itself) in its checklist.
- When you add a task to a section, this task can also be included in the project body.
