### ISSUE TITLE
Recurring Tasks set to null if completed in planner

### ISSUE THREAD

**Issue by awag90** [alainm23/planify#610]
Hello Everyone,
i have Planner 2.5.7 on Manjaro synced with Todoist on my Phone. I have many recurring Tasks in Todoist. If i check completed Tasks in Todoist everything works fine, but if I check it in Planner, the Date of the next Occurrence is displayed as __(null)__.
Even after new Sync, the Date doesn't update to the real Date, and the Task is not shown in the Today-Tab on the due-date. 
Am I doing something wrong, or is this a bug?

Thanks for your help, and this otherwise great App.

**Comment by basslerfish** [comment]
I have the same issue on Ubuntu 20.04 / Planner 2.5.7 when synced with Todoist. App looks great otherwise!

**Comment by alainm23** [comment]
@Carabas90 What language do you use Todoist?

**Comment by awag90** [comment]
@alainm23 
Both Planner and Todoist are set to german

**Comment by alainm23** [comment]
There's the bug, Planner only supports English and Spanish for recurring tasks, I hope to enlarge the list for v2.6, please be patient.

**Comment by basslerfish** [comment]
Not sure if still relevant, but I use todoist and Planner in English and recurring tasks fail for me.

**Comment by skaldebane** [comment]
Just as a question, are custom recurring periods set in Todoist supported by Planner?

**Comment by alainm23** [comment]
@Skaldebane Not at the moment but I hope to support you in the future.

**Comment by EugeneUvin** [comment]
I get this error on recurring tasks for todoist, is it the same? "Sorry, Planner doesn't support 'ru' language yet, please try to set a recurring task in English."
![изображение](https://user-images.githubusercontent.com/9447963/131847868-e15c8d98-5213-4d60-b617-c751ca7e7679.png)

**Comment by alainm23** [comment]
Fixed in the new version of Task Planner
