### ISSUE TITLE
Keyboard Shortcut for adding section not working

### ISSUE THREAD

**Issue by Suzie97** [alainm23/planify#611]
The shift + ctrl + s keyboard shortcut for adding a section to a project is not working.

Nothing happens when I type the shortcut. I have to manually click on the add section icon to add a section.

**Comment by alainm23** [comment]
Try with `s`

![image](https://user-images.githubusercontent.com/33765137/99551783-4254a000-298a-11eb-92b3-1983a5b27001.png)
