### ISSUE TITLE
Switch laguage with keyboard

### ISSUE THREAD

**Issue by rubstudio-admin** [alainm23/planify#612]
**Describe the bug**
Closing the quick add task window when switching the keyboard layout.

**To Reproduce**
1. Start Planner
2. Keys down ctrl + Tab (call quick add task window)
3. Switch the keyboard layout ('en' => 'ru' or 'ru' => 'en')
4. Quick add task window is close

**Expected behavior**
Quick add task window not closed when switch the keyboard layout

**Desktop (please complete the following information):**
 - OS or DE: [Elementary OS 5.1.7 Hera, pantheon]
 - Version Planner 2.5.7

**Comment by alainm23** [comment]
I'm not sure how to solve this problem, this happens because when Quick Add loses focus it automatically closes, this is useful to avoid having the window always open and being able to close very quickly.

**Comment by strikerusrus** [comment]
Add in settings switch "Automatically close Quick Add with loses focus", please. It is very inconvenient to use this window now. Close it window with press ESC

**Comment by alainm23** [comment]
It's a good idea
