### ISSUE TITLE
Unlink from todoist

### ISSUE THREAD

**Issue by srulikuk** [alainm23/planify#613]
I cannot find an option to unlink a project from todoist, does such an option exist? if not is there a command I can use? 
(Flatpak planner v2.5.7 on ubuntu 18.04)

**Comment by alainm23** [comment]
There is currently no way to unlink a project from todoist, I think we could add this in the project preferences.

**Comment by srulikuk** [comment]
Thanks for your quick response, is there a way to copy a project so i can delete the one that's linked?

**Comment by alainm23** [comment]
Sadly no, it takes a lot of changes to the database for this to work.

**Comment by srulikuk** [comment]
I understand, looking forward to the unlink enhancement to be implemented.
thanks

**Comment by srulikuk** [comment]
Any ETA on when this feature might be added?

**Comment by srulikuk** [comment]
> Sadly no, it takes a lot of changes to the database for this to work.

Not sure why it should be a lot of chnages, I just manually changed the "is_todoist" columns in the DB from 1 to 0 in the tables, "Items, Projects & Sections" logged out from todoist and all the tasks are now local.
