### ISSUE TITLE
[UI] Unable to view the text on Left Side bar in Night Mode

### ISSUE THREAD

**Issue by rtcms** [alainm23/planify#614]
**Describe the bug**
Unable to view the text on Left Side bar in Night Mode

**To Reproduce**
1. Install Planner
2. From the settings menu change the Appearance to Night Mode
3.  The colour of the font remains unchanged

**Expected behavior**
The colour of the font should change for the text to be visible

**Screenshots**
![Text Not Visible](https://user-images.githubusercontent.com/35173068/100470376-26759a80-30fe-11eb-87a5-293e1341ace9.png)

**Desktop (please complete the following information):**
 - OS or DE: Fedora 33 , GNOME(Wayland)
 - Version : Linux  5.9.10-200.fc33.x86_64, GNOME 3.38.1

**Additional context**
NA

**Comment by alainm23** [comment]
You should install Planner from AppCenter or Flathub, try one more time.

**Comment by rtcms** [comment]
Ah! My bad I have missed installing elementary-theme and elementary-icon-theme on Fedora
After installing them, it works fine for me :)
