### ISSUE TITLE
Theming issues; text is illegible.

### ISSUE THREAD

**Issue by IcedQuinn** [alainm23/planify#615]
**Describe the bug**

**To Reproduce**
Install Planner.
Use Arc Dark as the GTK theme.
Set the theme of Planner to anything. For most confusing effect set Planner to Arc Dark as well.

**Expected behavior**
Text should use appropriate colors either from the system theme or from the theme picked in Planner. For example, white on blue-ish text.

**Screenshots**
![image](https://user-images.githubusercontent.com/70673392/100529451-85461d00-31ad-11eb-8b92-864f88424369.png)

**Desktop (please complete the following information):**
 - Void Linux
 - 2.5.7

**Additional context**
This is bizzare since both the system are set to Arc Dark, and Arc Dark is selected from Planner's theme palette. In theory the correct colors should have come from one or the other but they do not.

**Comment by alainm23** [comment]
You should install Planner from AppCenter or Flathub, try one more time.

**Comment by P4Cu** [comment]
Another option: https://github.com/alainm23/planner/issues/751#issuecomment-872374885
