### ISSUE TITLE
Add a pomodoro timer with planner 

### ISSUE THREAD

**Issue by MohiuddinSumon** [alainm23/planify#616]
**When you are doing some work it is also important to keep track of time!**
Pomodoro is a well known technique to improve productivity. If we had some kind of pomodoro option that would be wonderful.

**Integrate a pomodoro based time tracking solution**

**Pomodoro for GNOME**
https://gnomepomodoro.org/ I am using this in ubuntu 20.04.

**Comment by skaldebane** [comment]
Great idea! +1

**Comment by BeatLink** [comment]
Seems others are interested. There's already an open issue for this feature at #315. Head over there and show some support with a thumbs up.

**Comment by alainm23** [comment]
Duplicate #315
