### ISSUE TITLE
Feature request quick filter "anytime"

### ISSUE THREAD

**Issue by Toxblh** [alainm23/planify#617]
![image](https://user-images.githubusercontent.com/2198153/100887008-647f0f80-34ac-11eb-9a55-0adf8c844f21.png)

Hey! 
Would to request a similar to preset filter in Things "Anytime" or a filter in Todoist web - "view all"
for overview all tasks across all projects in fast actions.

**Comment by alainm23** [comment]
Duplicate #21

**Comment by Toxblh** [comment]
@alainm23 got it thanks.
Can I some pin it to the left panel?  Or only via search?
