### ISSUE TITLE
Option to fail a particular task

### ISSUE THREAD

**Issue by Bollos00** [alainm23/planify#618]
Hello and congratulations for this great free software project,

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When I am about to complete a certain task, I just have the option to mark it as completed, but sometimes -- even though it is not ideal -- I was not able to really complete that task and there was no come back on that situation. That means that I had failed on that task.

For instance, today I was supposed to have an exam but I did not do it (for personal problems), since I will not be able to do it again, I have failed on that task, so I would like to mark that task as failed and not successful complete.

Now the application allows me to remove the task, but it is not the same as mark some task as failed.

**Describe alternatives you've considered**
I do not know how the code works, a trivial non-technical answer to this question would propose to create a second option for complete the task and mark it as failed.

**Additional context**
Nothing to add.

**Comment by BeatLink** [comment]
Well from what I know, planner deals with tasks as a binary absolute: tasks are either completed or they aren't. Would it be possible for you to instead utilize the labels feature to flag tasks? Perhaps you could leave it unchecked but add an "Incomplete" label to show the status. I myself use the labels systems to track the status of different tasks, such as those that are waiting on an external event, those that reccur, those that are in the distant future and so on. You can do a lot with labels including searching and filtering by labels, setting custom colours, and in a future update you will be able to sort by labels as well.

**Comment by Bollos00** [comment]
Hi @BeatLink and thank you for your quickly response,

The idea of using the flags to manage the tasks is great, adding a "Failed" label on a task is a great solution since the tasks have just two states (zero or one / complete or incomplete). That way it is easy to organize myself.

**Comment by BeatLink** [comment]
Awesome!

So you can go ahead and close that issue if that's all.

**Comment by Bollos00** [comment]
Understood! Thanks.
