### ISSUE TITLE
Unable to build latest planner with GNOME Builder

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#621]
**Describe the bug**
Attempting to build planner version https://github.com/alainm23/planner/commit/6d85f2f42d136a1d2c61659ca8361d9e267c86b2 with GNOME Builder shows the error 

`meson.build:24:0: ERROR: Dependency "libpeas-1.0" not found, tried pkgconfig and cmake`

**To Reproduce**
1. Launch GNOME Builder
2. Clone planner https://github.com/alainm23/planner/commit/6d85f2f42d136a1d2c61659ca8361d9e267c86b2
3. Attempt to build

**Expected behavior**
GNOME Builder should compile planner without error. 

**Screenshots**
![image](https://user-images.githubusercontent.com/47278150/102006315-3be9e780-3cee-11eb-8257-487327cd4277.png)

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint Cinnamon 20
 - Version https://github.com/alainm23/planner/commit/6d85f2f42d136a1d2c61659ca8361d9e267c86b2

**Additional context**
Build logs here: [meson-log.txt](https://github.com/alainm23/planner/files/5684315/meson-log.txt)

**Comment by alainm23** [comment]
Install `libpeas-dev`

**Comment by BeatLink** [comment]
Unfortunately, installing it did not fix this issue. I have it installed on my host system.

**Comment by BeatLink** [comment]
Remember, this would be building the flatpak version using GNOME Builder. So what may be on the host system may not necessarily be in the flatpak environment

**Comment by BeatLink** [comment]
I found a way to add the dependency to the flatpak environment. I'm testing it out now, and if it works, I'll do a pull request
