### ISSUE TITLE
Task creation date and history of changes

### ISSUE THREAD

**Issue by tsitokhtsev** [alainm23/planify#622]
**Describe the solution you'd like**
In Todoist in task menu there is a tab with information about when was the task created and about changes. I would like this to be implemented in Planner somehow.

**Additional context**
That tab in Todoist
![Screenshot 2020-12-13 130959](https://user-images.githubusercontent.com/38284633/102007786-61eea680-3d45-11eb-8216-2d49679ad788.png)

**Comment by alainm23** [comment]
![image](https://github.com/alainm23/planify/assets/33765137/c5419cbc-a845-4481-a927-568f901a8ec6)
