### ISSUE TITLE
Feature Request: Migrate Data Storage Backends to Plugin Architecture.

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#623]
It would make planner easier to maintain and extend if the existing data storage backends, (todoist, local database and the upcoming CalDAV were migrated to a plugin architecture.

This would allow yourself and other developers to easily create storage backends for various services, platforms and even file formats. 

For example, we could create plugin backends for:
* Markdown (Saving and loading tasks from markdown files instead of just export)
* EteSync (a dedicated plugin that doesnt depend on CalDAV which means greater utilization of features)
* todo.txt (Which is compatible with a *lot* of applications)

And these are just some examples. The possibilities are limitless!

It would also make it easier to maintain existing backends by decoupling the dependence of Planner itself on a few specific backends.

The implementation shouldnt be too hard. All that would be needed is the creation of a standard API that would handle saving each data object in planner using a specific data format, for example a json data string

For example. 
```
save_project() / get_project()

save_labels() / get_labels()

save_task() / get_task()

save_areas() / get_areas()
```

So essentially, each table in the current database format would have a corresponding save/get function in the API, that takes or returns a corresponding json data string. Each plugin would then implement these functions using its own internal logic. So for example, the local database plugin would take the parameters of these functions and save them in a database with SQL queries or if retrieving data, grab the data from the database with queries, parse it and set the return value to the result

**Comment by stefanoginella** [comment]
> Markdown (Saving and loading tasks from markdown files instead of just export)

This would be an amazing feature!

**Comment by bepolymathe** [comment]
Support of todo.txt would be great !

**Comment by alainm23** [comment]
I like the idea, but this feature would lead to a complete rebuild of Planner, probably v3. We will support CalDAV in the next Planner update and a few other things and will probably start with v3.

**Comment by BeatLink** [comment]
Okay! Sounds good!

**Comment by MichaelTunnell** [comment]
this would be amazing! I really just want import / export via Markdown so I can do things more efficiently like import a batch of tasks rather than having to create them over and over. (repeat tasks wouldnt be the answer as they are consistent tasks but not the same tasks every time)
