### ISSUE TITLE
Suggestion: Task window close when lose focus

### ISSUE THREAD

**Issue by brcmesquita** [alainm23/planify#63]
I'm using Planner daily, and man, what an excellent tool. Beautiful, simple, but I'm having difficulty with the user experience. I think the task window might close automatically if I clicked on another task to edit it, or click anywhere outside the task window that is currently open. And when this occurs, the task edit is saved. Understood?

Suggestions:
- Close window task when click outside;
- Save edit on close, when click outside;

**Comment by alainm23** [comment]
Thanks for the comment, this function is already available in the latest available version in AppCenter.
#### Go to > Menu > Preferences > General > Quick Save 
Select the number of clicks, to do it.

![image](https://user-images.githubusercontent.com/33765137/54217801-4e504500-44ba-11e9-874d-4b3ba3774dfc.png)

Now enter the list of tasks and the amount of click that I select in any part of the interface within the project, this will make all open tasks close and automatically save

**Comment by alainm23** [comment]
I think I will improve the labels to better understand this feature.

**Comment by brcmesquita** [comment]
Yeah, man, I tried it, but doesn't works. I'll try again.
