### ISSUE TITLE
Lots of memory in use (possible memory leak)

### ISSUE THREAD

**Issue by williamd1k0** [alainm23/planify#635]
**Describe the bug**
I upgraded to v2.6 (flatpak) and noticed that the app *always* allocates memory when you switch projects. So, if you keep switching projects, memory usage increases because (apparently) it is never released or reused.

**To Reproduce**
1. Create at least two projects
2. Add at least one task to each project
3. Keep switching between these two projects
4. Check memory usage

**Expected behavior**
The application should free up memory when you switch to another project or reuse memory if there is a cache.

**Desktop**
 - OS or DE: Manjaro Xfce 20.2
 - Version: 2.6 (flatpak)

**Additional context**
I don't know if this behaviour was introduced in v2.6 because I was using only one project in the past few months. I only noticed this now because the v2.6 update messed up my projects a bit, I had to recreate "Areas" using the new sub-projects feature.

**Comment by williamd1k0** [comment]
Ah, It's also happening when you click in the project that is already selected.

**Comment by alainm23** [comment]
In v2.6 we are allocating and freeing memory when loading a project or selecting it, this is completely different in previous versions of Planner where memory was never freed and a consumption of 100% of CPU was observed.

**Comment by williamd1k0** [comment]
Umm, but I noticed this behaviour in v2.6.

**Comment by williamd1k0** [comment]
I did a simple test, clicking on the same project every +-3 seconds.
[![asciicast](https://asciinema.org/a/hJpNZ92bL1hESfJJ6uxXy8xOB.svg)](https://asciinema.org/a/hJpNZ92bL1hESfJJ6uxXy8xOB)
