### ISSUE TITLE
How can I use sub-projects?

### ISSUE THREAD

**Issue by rzelnik** [alainm23/planify#636]
I use Planner in local mode, without Todoist sync. I noticed that project folders disappeared after upgrade to version 2.6, so now all projects are like eggs in one basket. I can't figure out how to create sub-projects so that I could reorganize my projects again.

**Comment by rzelnik** [comment]
I just found an answer to my question in this blogpost: https://useplanner.com/release/2020/12/24/merry-christmas-everyone-planner-2-6-is-here/

**Comment by alainm23** [comment]
@rzelnik I think I have to improve the UX for this process but the solution indicated in the blog works.
