### ISSUE TITLE
Allow GitHub Discussions in Planner project

### ISSUE THREAD

**Issue by rzelnik** [alainm23/planify#637]
It would be useful to activate a [GitHub Discussions](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions) to allow Planner users to talk to each other, to ask questions and to separate conversation from issues.

**Comment by alainm23** [comment]
Sure https://github.com/alainm23/planner/discussions.
