### ISSUE TITLE
My folders have disappeared

### ISSUE THREAD

**Issue by floriancuerq** [alainm23/planify#646]
**Describe the bug**
I just updated to planned 2.6.2 and when I open it there is no more folder to sort my projects; I had 2 folders one for home and a another for school. 

**To Reproduce**
1.Open planner
2.Look on the sidebar there is no more folder and no way to create them

**Expected behavior**
The ability to recreate folder

**Desktop (please complete the following information):**
 - OS or DE: ubuntu with xfce
 - Version of planner: 2.6.2

**Additional context**
Thanks you for this cool software.

**Comment by BeatLink** [comment]
Folders have been replaced with subprojects which has several advantages. You can basically add projects underneath other projects to group and collapse them. You can nest them infinitely so your subprojects can have subprojects and those projects can have subprojects too. It should make breaking down tasks easier to do.

You can move projects to subprojects by right clicking on the project, hovering over the move menu, then selecting the project you want the right clicked project to go under.

So in your case you could create a school and home project and move all your other projects under those two.

**Comment by floriancuerq** [comment]
Ok, that's makes sense. 
Thanks a lot for your reply

**Comment by BeatLink** [comment]
No prob

**Comment by alextakitani** [comment]
I've had the same "problem".

I think it should be better if when updating it converts the folders into projects and put the project's under.

Normal users would think they had their data deleted and it would generate a lot of confusion.
