### ISSUE TITLE
Convert to todoist not working.

### ISSUE THREAD

**Issue by hojjatabdollahi** [alainm23/planify#648]
**Describe the bug**
I'm not sure what this feature is supposed to do. But convert to Todoist is not working. I don't particularly need it, or use it, but just reporting.

**To Reproduce**
1. Create a new project
2. Go to the "Edit project dialog"
3. click "convert to Todoist"
4. It says "Failed to convert project. Try again."
5. It doesn't matter if you have tasks in the project or not.

**Expected behavior**
I expected the project to convert to a Todoist project.

**Desktop (please complete the following information):**
 - OS or DE: Pop!_Os 20.10 Gnome
 - Version 2.6.2

**Comment by BeatLink** [comment]
It is quite likely that the conversion failed because you have not logged into a todoist account.  If that is not the case, feel free to reply to this issue. In the meantime, I will close this issue.
