### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by rahidulislam** [alainm23/planify#651]
**Describe the bug**
when i am trying installing this app from elementary os appcenter, it shows

**Error while installing package: trying to overwrite '/usr/lib/x86_64-linux-gnu/libcodecore.so.0.0', which is also in package libcodecore0 3.4.1~r3155+pkg133~ubuntu5.1.5.1**

**To Reproduce**
1. Go to appcenter
2. Click on Planner
3. click Free button

**Error while installing package: trying to overwrite '/usr/lib/x86_64-linux-gnu/libcodecore.so.0.0', which is also in package libcodecore0 3.4.1~r3155+pkg133~ubuntu5.1.5.1**

**Screenshots**
![Screenshot from 2020-12-29 06 15 19](https://user-images.githubusercontent.com/33887458/103252462-386d8600-49a7-11eb-86c9-ef41e66f61f7.png)

**Desktop (please complete the following information):**
 - OS or DE:[pantheon]
 - Version [5.1.7]

**Comment by Suzie97** [comment]
> **Describe the bug**
> when i am trying installing this app from elementary os appcenter, it shows
> 
> **Error while installing package: trying to overwrite '/usr/lib/x86_64-linux-gnu/libcodecore.so.0.0', which is also in package libcodecore0 3.4.1~r3155+pkg133~ubuntu5.1.5.1**
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Go to appcenter
> 
>     2. Click on Planner
> 
>     3. click Free button
> 
>     4. See error
> 
> 
> **Error while installing package: trying to overwrite '/usr/lib/x86_64-linux-gnu/libcodecore.so.0.0', which is also in package libcodecore0 3.4.1~r3155+pkg133~ubuntu5.1.5.1**
> 
> **Screenshots**
> ![Screenshot from 2020-12-29 06 15 19](https://user-images.githubusercontent.com/33887458/103252462-386d8600-49a7-11eb-86c9-ef41e66f61f7.png)
> 
> **Desktop (please complete the following information):**
> 
>     * OS or DE:[pantheon]
> 
>     * Version [5.1.7]

I also had the same error while updating to 2.6

**Comment by Suzie97** [comment]
I also had this problem while updating to 2.6
![Screenshot from 2020-12-29 17-14-29](https://user-images.githubusercontent.com/68198116/103281779-c7a38980-49f9-11eb-901f-b9bd9f68253a.png)

**Comment by rbribeiro** [comment]
I had the same issue. I had to force overwrite
`sudo dpkg -i --force-overwrite /var/cache/apt/archives/com.github.alainm23.planner_2.6.2_amd64.deb
`

**Comment by alainm23** [comment]
@rbribeiro  It's a momentary solution, I'm sending an urgent update to AppCenter, please be patient 🙏️.

**Comment by rbribeiro** [comment]
@alainm23 don't worry, man! We all admire your work and understand the problems one has to face when it comes to software development! I'm sure you will find a solution! I was just offering a momentary solution in case the other users didn't know how to fix it.
