### ISSUE TITLE
Moving task from inbox to project using drag and drop does not work properly

### ISSUE THREAD

**Issue by Suzie97** [alainm23/planify#655]
**Describe the bug**
When I use the mouse to drag a task from my inbox to a project in the sidebar, it displays a message stating that the task has been moved, but the task gets copied over to the project and also stays in the inbox. When the task is deleted from inside the project or from the inbox, it gets deleted in both the inbox and the project.

**To Reproduce**
1. Drag a task from the inbox to a project.
2. Look for the task inside the project.
3. Look for the task in the inbox.
4. Delete the task from either the inbox or from the project.
5. The task is deleted from the inbox as well as the project.

https://user-images.githubusercontent.com/68198116/103398355-5f23ec00-4b62-11eb-8b87-7da8bfdfe5b7.mp4

**Comment by alainm23** [comment]
Thanks for using Planner. I try to reproduce the bug but I can't.
- What version of Planner are you using?
- Do you have Todoist syncing enabled?

**Comment by Suzie97** [comment]
I tried the same thing once again and this time it works.

Maybe it was a problem with my computer. I am closing this issue.

**Comment by twrightsman** [comment]
I am still encountering this behavior on Planner 2.6.9.
