### ISSUE TITLE
Flathub doesn't sync with new releases

### ISSUE THREAD

**Issue by rzelnik** [alainm23/planify#659]
**Describe the bug**
I see version 2.6.8 in the source code repository, but in Flathub there is still 2.6.2.

https://flathub.org/apps/details/com.github.alainm23.planner

**Comment by alainm23** [comment]
Apparently there are some problems in AppCenter, I'll release 2.6.8 for Flathub, it should be available in some hours.

**Comment by alainm23** [comment]
Apparently there are some problems in App Center, I will release 2.6.8 for Flathub, it should be available in some hours.
