### ISSUE TITLE
The repeat option does not appear when creating a new task

### ISSUE THREAD

**Issue by BasilioDavid** [alainm23/planify#669]
**Describe the bug**
When you create a new task you can't select the repeat option and you must save that task and then add it

**To Reproduce**
1. Create new task
2. Try to add repeat

**Expected behavior**
It should show the repeat option

**Screenshots**
the screenshots are in spanish, I didn't find the option to change languaje

![Captura de pantalla de 2021-01-08 11-10-40](https://user-images.githubusercontent.com/75041569/104003099-43dc6080-51a2-11eb-884c-7ba485cfff6e.png)

![Captura de pantalla de 2021-01-08 11-11-02](https://user-images.githubusercontent.com/75041569/104003171-5d7da800-51a2-11eb-830d-b2d28433cf4a.png)

**Desktop (please complete the following information):**
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Comment by alainm23** [comment]
This feature is now available on Planify.
