### ISSUE TITLE
[RFE] Import from Markdown as companion to Share Markdown

### ISSUE THREAD

**Issue by akvadrako** [alainm23/planify#670]
I would like to import many TODOs that are currently stored in markdown like this:

```markdown
# Pack

## Always

- [ ] Wallet
  - [ ] money, credit card, bank pass, ID card
- [ ] Keys
- [ ] Phone

## Day Trip

- [ ] Tissues
- [ ] USB-C → USB-A adapter
- [ ] Battery
- [ ] Immodium
- [ ] swiss army knife (w/corkscrew)
- [ ] pen
```

The current "Share → Markdown" feature produces just the kind of markdown I would like. It would be nice if I could then paste that markdown into a project and have it create sections and todo entries.

Another option would be to have a "Import → Markdown" menu next to the Share menu.

**Comment by BeatLink** [comment]
The best way this could be implemented would be to migrate planner's storage architecture to a plugin based system. That is being discussed here #623 . Feel free to head there and give your input

**Comment by alainm23** [comment]
Hi, this looks super interesting, but I see it's been a long time without activity, I'll close the issue and if you think it's important, please reopen the issue, thanks.

**Comment by Nico7as** [comment]
> Hi, this looks super interesting, but I see it's been a long time without activity, I'll close the issue and if you think it's important, please reopen the issue, thanks.

Hi, 

I think that would be very useful.

I often prepare and store tasklists in Markdown compatible softwares such Notes taking apps, MindMapping apps, and it would be really convenient to be able to import them easily.
