### ISSUE TITLE
Board View doesn't show up immediatly

### ISSUE THREAD

**Issue by Leon0402** [alainm23/planify#675]
**Describe the bug**
When Board View is enabled for some folder and you open this up this folder, planner first builds up the classic view and then the board view. 

**To Reproduce**
1. Add folder with sections and enable board view 
1. Go in another folder 
1. Go Bock to the created folder 
1. Observe how you see for a second or less the classic view
1. Observe then how it builds up the board view

**Expected behavior**
When board view is enabled it should show up directly to avoid these sort of graphical glitches. Also this would speed up switching folder a little bit I guess.

**Comment by alainm23** [comment]
The board view is still under development, feel free to open the issue when the functionality is available. thank you,
