### ISSUE TITLE
Project and task overview showing ALL projects and tasks

### ISSUE THREAD

**Issue by MatthiasSiewert** [alainm23/planify#677]
**Is your feature request related to a problem? Please describe.**
I have a hard time to get an overview of all my tasks. Sometimes, they also belong to different projects, but are related.

**Describe the solution you'd like**
I would like to have one overview panel with all projects and all tasks visible. Similar to today, but all tasks. 

**Describe alternatives you've considered**
-

**Additional context**

**Comment by Toxblh** [comment]
If I correct understand is related to 
https://github.com/alainm23/planner/issues/21#issuecomment-737335372
https://github.com/alainm23/planner/issues/21#issuecomment-455579792
