### ISSUE TITLE
Task checklists look like radio buttons

### ISSUE THREAD

**Issue by cassidyjames** [alainm23/planify#68]
**Describe the bug**
The task checklists are rounded, and thus look like check-one-of-many radio buttons instead of check-many-from-many checkboxes.

**To Reproduce**
1. Go to Today
2. Click on "Add a new task"
3. Add a checklist at the bottom
4. See the radio buttons

**Expected behavior**
Checklists are a check-many-of-many situation, so they should have square checkboxes instead of round radio buttons in the elementary stylesheet.

**Screenshots**

![image](https://user-images.githubusercontent.com/611168/55445718-e8675280-5579-11e9-9ea1-b1661e9492f7.png)

**Desktop (please complete the following information):**
 - OS or DE: elementary OS Juno, Pantheon
 - Version 1.2.4

**Comment by alainm23** [comment]
Thanks for the comment, I will take it into account in the next release :)

**Comment by alainm23** [comment]
Thank you very much for reporting the problem, and I have been busy working at Byte and at the university, I will do my best to correct these errors as soon as possible.
