### ISSUE TITLE
Cannot open display

### ISSUE THREAD

**Issue by Roy-Ermers** [alainm23/planify#685]
**Describe the bug**
The application won't open in gnome, other flatpak application that uses gtk still work.

**To Reproduce**
1. Open planner
2. Nothing happens

**Expected behavior**
The planner application opens

**Screenshots**

**Desktop (please complete the following information):**
 - OS or DE: Fedora 33, gnome 3.38.2, X11
 - Version: 2.6.9

**Additional context**
when I open this application using `flatpak run com.github.alainm23.planner` I get this warning:
```
Unable to init server: Could not connect: Connection refused

(com.github.alainm23.planner:2): Gtk-WARNING **: 17:04:01.900: cannot open display: 
```

**Comment by alainm23** [comment]
Is it the first time installing Planner or did the problem appear in the new update?

**Comment by Roy-Ermers** [comment]
I think it appeared with the new update, because a week ago I was able to open planner without any problems

**Comment by alainm23** [comment]
Did you do something with your system? I cannot reproduce the bug, I have searched the internet for the problem, maybe this video is the solution.

https://www.youtube.com/watch?v=j-WVc9HGCfI&ab_channel=ZINATAKLIT

**Comment by Roy-Ermers** [comment]
I didn't do anything special that could change something like this. I think
it has something to do with a dependency of planner.

**Comment by BeatLink** [comment]
Attempt to uninstall and reinstall planner.

**Comment by Roy-Ermers** [comment]
Nope still the same error.

**Comment by Roy-Ermers** [comment]
The issue is resolved now, still no idea why.
