### ISSUE TITLE
Sub-items in project tasks are deleted when converting project to todoist

### ISSUE THREAD

**Issue by naidoo88** [alainm23/planify#687]
**Describe the bug**
After creating a project in planner, and noticing it was not syncing to my todoist account, I converted it to a todoist project using the options in the settings.  Upon doing this, all the sub-tasks of tasks within the project were deleted, instead of being added to the tasks as subtasks.  

**To Reproduce**
1. Create a project
2. Add tasks
3. Add subtasks to that task
4. Go into the project settings and convert to todoist project

**Expected behavior**
As sub-tasks also exist on todoist, I expect subtasks to be properly exported to subtasks when converting a project to a todoist project.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS or DE: Xubuntu (Ubuntu 20.04.1;  kernel 5.8.0-40-generic)
 - Version 2.6.9 - installed from Flatpak

**Additional context**
N/A

-------------------------------------------------------------------------
Other than this bug, the app is great.  Miles better than the post-it note system I was using and was spiralling out of control!  Keep up the great work :)

**Comment by alainm23** [comment]
This functionality has not yet been developed in Planify, you can reopen it or create one when the functionality is available.
