### ISSUE TITLE
Completed task in project are deleted when converting to Todoist

### ISSUE THREAD

**Issue by murilodaluz** [alainm23/planify#688]
**Describe the bug**
After convert my local Planner project  to my Todoist free account, it was successfully converted but deleted all my completed tasks.
If you add any task directly to Todoist and mark it completed, it will appear in the Planner

**To Reproduce**
1. Create a local Planner project
2. Add task
3. Mark as completed
4. Go into the project settings and convert to Todoist project

**Expected behavior**
Convert all task and sync with Todoist

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS or DE: Pop! OS - Gnome
 - Version 2.6.8

**Additional context**
N/A

**Comment by murilodaluz** [comment]
Sorry, I think this is the default behavior of Todoist because my account is free version. 
Maybe add an alert or keep completed tasks local.

**Comment by alainm23** [comment]
This functionality has not yet been developed in Planify, you can reopen it or create one when the functionality is available.
