### ISSUE TITLE
Ubuntu - Icons missing and broken contrast when building manually

### ISSUE THREAD

**Issue by ojoched** [alainm23/planify#689]
**Describe the bug**
When built manually the application has missing icons and some broken features

**To Reproduce**
1. Download clean Ubuntu ISO 20.04 from the Canonical website.
2. Install deps manually:
`sudo apt install libgtk-3-dev libgee-0.8-dev libjson-glib-dev libsqlite3-dev libsoup2.4-dev libgranite-dev libwebkit2gtk-4.0-dev libecal2.0-dev libedataserver1.2-dev libpeas-dev libical-dev meson valac gettext -y`
3. Open the planner archive, and run:
meson build --prefix=/usr
cd build
ninja
sudo ninja install

4. Launch Planner successfully

**Expected behavior**
Buttons and GUI as shown in screenshots and as experienced when installed using Flatpak. 

**Screenshots**
![welcome_screen](https://user-images.githubusercontent.com/32438470/105646284-bc803400-5ea7-11eb-9ef9-37df97a90034.png)
![main screen](https://user-images.githubusercontent.com/32438470/105646286-bf7b2480-5ea7-11eb-8de0-de5ddaa14f00.png)
![dark mode](https://user-images.githubusercontent.com/32438470/105646287-c144e800-5ea7-11eb-8fcb-15535caac952.png)

**Desktop (please complete the following information):**
 - OS or DE: Ubuntu Gnome 
 - Version 20.04

**Additional context**
Pretty much can't use the app at that state. 
If there is a specific solution (install some sort of theme), probably should be added to the README.

**Comment by alainm23** [comment]
Thanks for using Planner, you I recommend installing Planner from Flathub but if you want to build it from the repository you have to install [elementary stylesheet](https://github.com/elementary/stylesheet/releases/tag/5.4.2) and [elementary icons](https://github.com/elementary/icons)

**Comment by ojoched** [comment]
Thanks. Indeed installing them solves the issue. On the elementary stylesheet one of the themes names' on /usr/share/themes needs to change from io.elementary.* to elementary, and that's the one that planner would load.
Can you please add it to the README?

**Comment by dirlidishka** [comment]
@ohadx3 What do you mean by 
> On the elementary stylesheet one of the themes names' on /usr/share/themes needs to change from io.elementary.* to elementary,

I have installed both repos but still have the issue with the colours of the menu items.

**Comment by paulcarroty** [comment]
The same issue. Fixed by copying `com.github.alainm23.planner.desktop` to `~/.local/share/applications` and editing `Exec` to `Exec=env GTK_THEME=Adwaita:dark com.github.alainm23.planner`.

P.S. You can use another themes.

**Comment by alainm23** [comment]
@ohadx3 The elementary team is working on a new stylesheet for elementary OS 6, this new stylesheet is not  supported yet by Planner, you need to download a stylesheet that is supported, [try it](https://github.com/elementary/stylesheet/releases/tag/5.4.2).
