### ISSUE TITLE
Change the icon of a to do task to a dash instead of a cross

### ISSUE THREAD

**Issue by rafaelcn** [alainm23/planify#69]
I'm always confused by the cross icon whenever I open a todo task to see details. The cross icon gives an idea of removing, closing for good and not seeing that task anymore. What should be done is to show an icon of minimize, the minimize icon gives an idea of fading details away.

The following image describes the cross icon that should be replaced.

![image](https://user-images.githubusercontent.com/3271143/55553246-12259400-56b6-11e9-92d5-d178aa62245c.png)

**Comment by alainm23** [comment]
Thank you very much for reporting the problem, and I have been busy working at Byte and at the university, I will do my best to correct these errors as soon as possible.
