### ISSUE TITLE
Code format feature

### ISSUE THREAD

**Issue by ontimond** [alainm23/planify#690]
**Is your feature request related to a problem? Please describe.**
When I add a code text in the task comment like `code` (\`code\`) don't takes the format as todoist. [Todoist Text formatting](https://todoist.com/es/help/articles/text-formatting)

**Describe the solution you'd like**
Adds the code format when use the characters \` for `code` or \`\`\` for ```Code block``` around the text code.

**Comment by alainm23** [comment]
Markdown support is coming in the next version.
