### ISSUE TITLE
Preferences window can't scroll to bottom, seems to have multiple scrollbars

### ISSUE THREAD

**Issue by twrightsman** [alainm23/planify#693]
**Describe the bug**
I cannot scroll completely to the bottom in the preferences window and some of the children windows (e.g. Calendar Events with a lot of system calendars). This seems to be because there are two scollbars stacked on top of each other. By playing with both of them I can see the whole view but this doesn't seem to be intended behavior.

**To Reproduce**
1. Go to Preferences
2. Try to scroll to the bottom, "Support & Credits" is cut off

**Expected behavior**
I expect to be able to scroll completely to the top or bottom of these views without cut off labels.

**Screenshots**
![Screenshot 1](https://user-images.githubusercontent.com/6300973/106683102-de597500-6591-11eb-8efa-61804ddc9229.png)

**Desktop (please complete the following information):**
 - OS or DE: Flatpak
 - Version 2.6.9

**Comment by ghost** [comment]
I have the same issue. I am on Linux Mint 19.3 and I downloaded Planner from FlatHub. 
![image](https://user-images.githubusercontent.com/34846387/107615584-72060200-6c72-11eb-8b41-0e3d302cf8af.png)
