### ISSUE TITLE
Dark thick border around Quick find, Preferences and the applications window when default decoration is used

### ISSUE THREAD

**Issue by gerroon** [alainm23/planify#696]
**Describe the bug**
There isa  dark thick border around the quiock find window. I am not sure if this is intentional so reporting it here.

**To Reproduce**
1. enable white theme (it is there with every theme, but easier to see with the white one)
2. Try with the system window decoration and without it.

**Expected behavior**
I would expect that the pop up windows behave like other windows without non system/non native thick borders.

**Screenshots**
![rGpdKf0](https://user-images.githubusercontent.com/8519469/107170382-ca44b780-6985-11eb-90d2-52e23eabf002.png)

**Desktop (please complete the following information):**
 - OS:  Debian Testing , installed with Flatpak
 - Version: 2.6.9

**Additional context**
This exists with all pop ups. Also there is a thick border around the actual app window if I disable the "system window decoration"  Please see the image

![2021-02-07_20-51](https://user-images.githubusercontent.com/8519469/107170596-6969af00-6986-11eb-820d-652860361e8a.png)

**Comment by BeatLink** [comment]
Which desktop environment and window compositor are you using? GNOME, KDE ect

**Comment by gerroon** [comment]
Hi

I am using Fluxbox on Debian Testing.

**Comment by BeatLink** [comment]
could you try running planner on another desktop environment to see if the issue still exists?

**Comment by theperelomov** [comment]
Hi, i have the same problem
I am use Qubes OS 4.0.4rc2, and launch it on fedora 32 VM 
Planner v2.6.6 - from fedora repo
DE - xfce 4.12 - but i am not sure, how windows are drawn on my system from virtual machines 
here are screenshots, with/without system decoration
![1Screenshot_2021-02-21_04-50-36](https://user-images.githubusercontent.com/37098738/108614409-fee35500-7402-11eb-94fe-27c2f9811702.png)
![2Screenshot_2021-02-21_05-02-33](https://user-images.githubusercontent.com/37098738/108614410-ff7beb80-7402-11eb-92d2-d6e7a5d1db3c.png)

P.S. I just found this application on the Internet - good job!

**Comment by BeatLink** [comment]
Ok, so it is confirmed that this issue currently exists in the latest version of planner. 

@theperelomov by the way, I just help with triaging and such, you should show your support to @alainm23 . He's the creator of Planner

**Comment by chewybaws** [comment]
Hi,

I'm having the same problem on Arch Linux (5.10.16-arch1-1) with Awesome Window Manger (4.3-2). Compositor is picom 8.2-1.

Planner version is from AUR;
elementary-planner-git 2.6.9.r24.g59ef061c-1

Here is a screenshot
![border](https://user-images.githubusercontent.com/78068224/108617236-779adf00-740c-11eb-81ee-1aae6f73337a.png)

It happens with the main window too unless I enable Use system window decoration like the original post said.

**Comment by BeatLink** [comment]
Closing in favor of #268
