### ISSUE TITLE
Use Elementary Icons

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#7]
While the icons you use inside the app are good, I think you should use the elementary icons.
For example the calendar icon.

**Comment by alainm23** [comment]
Thanks for your comment, I'm using all possible elementary icons except for the icons for Inbox, Today and Tomorrow, you can see it in the last update I posted a few minutes ago.

**Comment by Hedronmx** [comment]
Is it because there are no icons for that? Just wondering. Your app looks and works really awesome
