### ISSUE TITLE
Issue editing note

### ISSUE THREAD

**Issue by muriloventuroso** [alainm23/planify#70]
Duplicating data while editing task

1. Create a task with note.
2. Create a second task (there is no option to add note)
3. Click to edit the second task and add note.
4. Both tasks are updated with the same data.

**Comment by muriloventuroso** [comment]
At first I thought I was updating all the tasks, but this is just visual. After closing the application and opening again I saw that the edited task was duplicated.

**Comment by Julioevm** [comment]
I have the same issue.

**Comment by inkoqnito** [comment]
Hello,
I also have this issue very annoying and confusing. Is there a solution on this bug on its way?
