### ISSUE TITLE
No notifications of any sort

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#700]
**Describe the bug**
The App wont push notifications to the system, I don't get any reminders about upcoming tasks even though the app is running in the background from startup. Also there is no sync with the calendar even though its enabled.

* I have notifications enabled for Planner in the system settings

**To Reproduce**
1. Create a task and schedule it to the next minute or two
2. Keep the app running in the background

**Expected behavior**
The task should appear in the calendar as well as I should get notified about the task.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Elementary OS
 - 5.1.7 Hera

**Additional context**
N/A

**Comment by alainm23** [comment]
Thanks for using Planner
- Scheduling a task does not send a notification, it's only a indicator, instead you can add a Reminder.

![image](https://user-images.githubusercontent.com/33765137/108512459-42b54d80-728f-11eb-86c8-a22ca83024db.png)


- If you schedule a task it will not appear in the calendar, Planner will only show calendar events, it does not create them.

**Comment by ghost** [comment]
Hmmm... I was under the impression that tasks should push notifications when they're due, seems kinda odd you can schedule a task and then have to add a reminder about it... a bit counter intuitive. shouldn't it remind you about it self on its own if its scheduled?

Any way I added a reminder and it did work this time with the push notification, but it seems like there is no recurring reminders either. How do I get recurring reminders for my recurring tasks?
