### ISSUE TITLE
Add label filtering to today view

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#703]
**Is your feature request related to a problem? Please describe.**
The today view can be disorganized without a way to filter tasks by label

**Describe the solution you'd like**
Adding the label filter to the today view would allow users to find tasks that have a specific label that is due today

**Describe alternatives you've considered**
None considered

**Additional context**
No other information

**Comment by alainm23** [comment]
It's an interesting idea.

**Comment by alainm23** [comment]
This feature is available in Planify 4.7
