### ISSUE TITLE
Enable Projects section of Github to track issues

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#704]
It would be easier to organize issues if the projects section was activated on the github repo

**Comment by BeatLink** [comment]
@alainm23 Would you be willing to do this? It shouldnt take more than 5 seconds in github settings and it could really help with sorting out all the issues and creating a roadmap

**Comment by alainm23** [comment]
I'm sorry, sure.

**Comment by BeatLink** [comment]
Thanks!
