### ISSUE TITLE
Ability to Duplicate Projects

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#705]
**Is your feature request related to a problem? Please describe.**
This issue is inspired by issue #279 where the user wished to create template projects that could be duplicated for reuse. 

**Describe the solution you'd like**
A button could be added to the project settings that would create a duplicate project, ideally with all data retained, such as project properties (description, colour, due dates, ect), section properties (names, notes) and task properties (tasks, reminders, due dates, notes. ect)

**Describe alternatives you've considered**
No alternatives discussed yet

**Additional context**
No other context as yet

**Comment by hcal** [comment]
I'd be happy with almost any version of a duplication feature, but I think you might want to avoid coping the dates.    I'm guessing based on a sample of users including just myself so take this with a grain of salt, but it seems unlikely that most duplicated projects would have the same dates.  

For me, just leaving them out would be fine.  I could add them back as needed.  It would be ideal if dates could be quickly recalculated during the duplication action.   Given that the tasks are the same, it is probably likely that the overall timelines would stay the same so you could ask for a new date of the earliest task and offset every other date by the same number of dates.

**Comment by BeatLink** [comment]
Ahh, okay, that makes sense

**Comment by alainm23** [comment]
This feature is available in Planify 4.7.2
