### ISSUE TITLE
Ability to import projects from files

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#706]
**Is your feature request related to a problem? Please describe.**
This issue is inspired by https://github.com/alainm23/planner/issues/279

**Describe the solution you'd like**
There could be an option in planner to add a project either from a todo.txt file or from a properly formatted markdown file (formatted in the same manner that project exports are done). This would not only solve the issue of the above user but would allow other users to migrate their existing todo systems to planner.

The project import system could be modularized so that projects can be imported from a variety of sources and file formats. It could even be integrated into issue #623 

**Describe alternatives you've considered**

**Additional context**

**Comment by johnblommers** [comment]
It's nice that Planner has an export database option but it does not have an import database option. This matters because the Todoist sync via Apple Authentication does not seem to work. And there is no documentation about how to put Planner's database on an external folder that can be synced via Dropbox or Owncloud et. al..

**Comment by MichaelTunnell** [comment]
This would be wonderful to have! I'd also like the ability to import Sections into exist projects via Markdown like you do the sharing piece out.

Planner is great so far but the lack of Import is a little limiting in regards to efficiency and migrating. I have consistent tasks that I do every week such as things related to my podcasts. (I could do recurring but I'd rather just do a basic markdown import)

**Comment by alainm23** [comment]
The functionality to import and export a backup is now available in Planify 4.3.
