### ISSUE TITLE
Duplicated subtasks in a new task

### ISSUE THREAD

**Issue by przepior** [alainm23/planify#71]
When I add a task with subtasks and try to add another task, the second task conteains subtasks from previous task.

**Comment by ghost** [comment]
I have the same issue.
And when in the task is in a project and there is a task before then all tasks changed.
I could find out that it happens, when you create subtasks and press enter and you will save with an empty subtask.

**Comment by alainm23** [comment]
Thank you very much for reporting the problem, and I have been busy working at Byte and at the university, I will do my best to correct these errors as soon as possible.
