### ISSUE TITLE
Allow Syncing To A Custom Location

### ISSUE THREAD

**Issue by ProfessorCode212** [alainm23/planify#710]
**Is your feature request related to a problem? Please describe.**
I don't have a _Todoist_ account nor do I use _NextCloud_. I still want to be able to backup my tasks and projects in Planner.

**Describe the solution you'd like**
An option to sync to a custom location in the filesystem. This would allow anyone to sync it to their cloud storage service of choice through a virtual drive in the filesystem.

**Additional context**
It would be great if this feature could be coupled with an option to encrypt the database as mentioned in #105.

**Comment by BeatLink** [comment]
Planner supports creating json file backups of all the tasks and projects. You can find the settings under the General tab of the preferences window. 

Alternatively, you can hunt down the planner database file itself and backup that. That's what I do. I run https://github.com/gitwatch/gitwatch to backup the planner data folder when it changes. 

If #623 is implemented, then planner will be able to support numerous file formats and storage backends. You can head on over and express your wish for this feature there! I'm going to go ahead and close this issue, but if you feel your case merits a separate issue, I'll go ahead and reopen it
