### ISSUE TITLE
Allow Quick Find Button to be Rearrangable

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#717]
**Is your feature request related to a problem? Please describe.**
In the side pane, the Quick Find button is stuck to the top

**Describe the solution you'd like**
Allow the Quick Find button to be manually sorted like the Inbox, Today and Upcoming button can be

**Describe alternatives you've considered**

**Additional context**

**Comment by alainm23** [comment]
Esta funcionalidad aun no ha sido desarrollada en Planify, puede volverla a abri o crear una cuendo la funcionalidad este disponible.
