### ISSUE TITLE
Todoist sync issues

### ISSUE THREAD

**Issue by isshin1** [alainm23/planify#721]
**Describe the bug**
planner is not updating the project list after I synced it with todoist. As you can see the list of projects in move to project menu, some of these projects were in todoist at the time of syncing but now deleted, yet planner is showing them as real. Some of the current projects are missing from the list, and If I drag this demo task to `TO-DO` or any other unlisted project, I am getting the warning `Unable to move task`

Edit : Planner is showing deleted projects from todoist in list of available projects where you can move a task from another project from todoist

**Expected behavior**
Planner should list all the available projects and allow transfer of tasks between them

**Screenshots**
![2021-03-11_11-29-17](https://user-images.githubusercontent.com/36916613/110743027-63087480-825d-11eb-9685-6655941ed486.png)

**Desktop (please complete the following information):**
Arch Gnome / sway

**Comment by alainm23** [comment]
Thanks for using Planner, This is not a bug, it's a behavior that I hope to improve in future versions of Planner. Probably you have created Todoist projects and Local projects, moving tasks between Todoist and Local projects is not possible yet.

**Comment by isshin1** [comment]
> moving tasks between Todoist and Local projects is not possible yet

yeah, I realized that a bit later,my bad.  I didn't close the issue because project `Intern work` don't exist and shouldn't show up at all.

 After I synced todoist with planner for the first time, I deleted both `intern work` projects from todoist. Now even after the sync I can see them after I right click on a task to send it to other project.
