### ISSUE TITLE
Add labels with multi selection on tasks

### ISSUE THREAD

**Issue by tifDev** [alainm23/planify#722]
Hi,

When selecting multiple tasks (_ctrl + click_ on multiple tasks) you can perform some actions like:
- Schedule
- Mark as Done
- Remove

**Could you pls add support to add a label?**

This would be very useful as of now I need to be adding 1 by 1.

Thank you very much and congrats for this awesome project.

**Comment by alainm23** [comment]
Sure

**Comment by alainm23** [comment]
This feature is available in Planify
