### ISSUE TITLE
flatpak: The GNOME 3.36 runtime is no longer supported as of February 13, 2021

### ISSUE THREAD

**Issue by 73** [alainm23/planify#726]
**Describe the bug**
The platform used by the flatpak package is end-of-life.

**To Reproduce**
This error occurred on `fllatpak update`:
```
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please as
k your application developer to migrate to a supported platform.                                                                      
Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Pl
ease ask your application developer to migrate to a supported platform.
```
Looking for the apps needing it, yields:
```
flatpak list --app --columns=application,runtime | grep 3.36
com.github.alainm23.planner     org.gnome.Platform/x86_64/3.36
```

**Expected behavior**
No errors.

**Desktop (please complete the following information):**
 - OS or DE: Ubuntu 20.10 on GNOME
 - Version 2.6.9 from flathub

**Comment by HideyoshiNakazone** [comment]
Same thing in Arch.

**Comment by HideyoshiNakazone** [comment]
Does the developer @alainm23 have any comment in this topic?

**Comment by alainm23** [comment]
I am aware of the problem, in the repository I am working with [GNOME 3.38](https://github.com/alainm23/planner/blob/master/build-aux/flatpak/com.github.alainm23.planner.json#L5), I hope to release an update soon.

**Comment by HideyoshiNakazone** [comment]
> I am aware of the problem, in the repository I am working with [GNOME 3.38](https://github.com/alainm23/planner/blob/master/build-aux/flatpak/com.github.alainm23.planner.json#L5), I hope to release an update soon.

Thank very much @alainm23 for your hard work

**Comment by hanaral** [comment]
Are there plans to create an AppCenter flatpak manifest during the beta now that the SDK is on the AppCenter repo?
