### ISSUE TITLE
"quick add" as a command line option

### ISSUE THREAD

**Issue by westofer** [alainm23/planify#728]
**Is your feature request related to a problem? Please describe.**
Key Combination for "Quick Add" doesn't work in window managers such bspwm (with sxhkd)

**Describe the solution you'd like**
a command line option such as `planner --quickadd` or `--quickadd="{title:'x', date:''}"` to allow for scripting

**Comment by ProfessorCode212** [comment]
@westofer You can already do this. If you installed _Planner_ as a Flatpak, the command is this: `flatpak run --command=com.github.alainm23.planner.quick-add com.github.alainm23.planner`. You can also see #627.

**Comment by westofer** [comment]
thanks @ProfessorCode212 , it is a duplicate. 

and I don't use flatpak sadly 😞
