### ISSUE TITLE
Sync Server

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#73]
Hi,

I really love your app.
What do you think about a small sync server for a private cloud for all the people who are concerned about their privacy?
I thought about a little docker with python who save all data in a small SQLite database and has a small REST API.
I think that could be really easy to setup.

**Comment by alainm23** [comment]
Thank you very much for your comment, I am currently working on a new version of Planner with support for Todoist, support for private server would be a very good feature, but at the moment it is not in future plans.

You can try the new version in:
https://github.com/alainm23/planner/tree/planner_v2
