### ISSUE TITLE
Checklist, labels and reminders to be cloned

### ISSUE THREAD

**Issue by genyuz** [alainm23/planify#733]
**Is your feature request related to a problem? Please describe.**
When duplicating a task, its priority, its text and its description is cloned, but not its labels, reminders and most important its subtasks (checklist). So its not possible, so use an existing task as complete template.

**Describe the solution you'd like**
When duplicating a task, all its properties including labels, reminders and checklist shall be cloned.

**Describe alternatives you've considered**
An alternative could be to introduce a general template-concept. But having a complete cloning-feature would be the better solution.

**Comment by genyuz** [comment]
Does "CLOSED" mean that it was implemented or that the request is ignored?

**Comment by alainm23** [comment]
Sorry for the delay, it has been fixed, please wait for the next update.
