### ISSUE TITLE
Snap Support

### ISSUE THREAD

**Issue by hodev-dev** [alainm23/planify#735]
**Is your feature request related to a problem? Please describe.**
Snap or Deb Support 

**Describe the solution you'd like**
please add snap package as supported list , its really great app
since Flatpak is not that well integrated in Ubuntu and install freeze in Ubuntu 20.04

I actually compiled it from source and installed elementary-os style sheet and icons but UI still seems broken

**Comment by alainm23** [comment]
Thanks for using Planner, we intend to support Snap, if there is any collaborator that is interested in apollarding? [I have a small advance](https://github.com/alainm23/planner/blob/master/build-aux/snap/snapcraft.yaml) but I think it is not fully functional.

**Comment by naDevi** [comment]
+1 :(

**Comment by Claudio-code** [comment]
@alainm23 Hi, I'm really enjoying using your app, can I help create this snap support?

**Comment by alainm23** [comment]
@Claudio-code Sure.

**Comment by Claudio-code** [comment]
@alainm23 Do you have any background material on where do I start?
after it's done, just open a pull request?

**Comment by Claudio-code** [comment]
Do you have any background material on where do I start?
after it's done, just open a pull request?
