### ISSUE TITLE
Task title sometimes gets deleted

### ISSUE THREAD

**Issue by really-just-a-tech** [alainm23/planify#737]
**Describe the bug**
I don't know exactly when it happens, but sometimes the title of a task is suddenly gone. This is really annoying because I often don't remember what it was.

**To Reproduce**
I haven't been able to reproduce it yet; it just sometimes happens. I will update this issue when I can find out how to reproduce it.

**Expected behavior**
All task information should stay unaltered when the user does not change it.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/59294175/116376056-2ba35680-a810-11eb-9827-b5ff92b5f5d8.png)
This is not an actual example of the bug, just recreated to clarify my description. As you can see, the title of the second task is empty.

**Desktop:**
 - OS and DE: Fedora 33 with GNOME 3.38.5
 - Version 2.6.9 (Flatpak)

**Comment by dmlls** [comment]
Do you have Todoist sync activated?

**Comment by shackenberg** [comment]
I have the same problem with tasks "losing" their title.
It seems to happen when tasks have their due-date changed. 

Ubuntu 20.04. 
Gnome 3.36.8
I had the same issue using Wayland and the old default (x11?) backend.

**Comment by really-just-a-tech** [comment]
> Do you have Todoist sync activated?

No, I don't.

> It seems to happen when tasks have their due-date changed.

I still haven't managed to reproduce the bug :/

**Comment by shackenberg** [comment]
I forgot. I also don‘t have any syncing activated. For me it happens nearly
every day.

**Comment by shackenberg** [comment]
I forgot. I also don‘t have any syncing activated. For me it happens nearly every day.

**Comment by cohalex** [comment]
Planner 2.6.9
Ubuntu 20.04.2
Gnome 3.36.8
No Todoist sync

Happened to me twice today, task title and notes were gone. I can also confirm it is somehow related to changing the due date.

Luckily I had a backup so I searched the json but this is a fatal bug for me if I want to rely on Planner to manage my tasks (and I really do want to rely on it, it is a great application).

**Comment by shackenberg** [comment]
To also leave a positive note. I want to thank you for providing this app to the community. I looked at nearly all to-do apps I could find for Ubuntu and Task Planner was by far the most useful and appealing one to me.

**Comment by cohalex** [comment]
I've found consistent reproduction steps:

1. Have some overdue tasks from yesterday.
2. In the Today screen click an overdue task.
3. Click "Yesterday" (to reschedule) and select "Today".
4. Click <kbd>Ctrl</kbd>+<kbd>H</kbd> to close task details.
5. After a brief moment the task title disappears (task notes are gone as well).

Hope this helps to find the bug.

**Comment by kak-tus** [comment]
Same here.

**Comment by alainm23** [comment]
Ha tenido el mismo bug en Planify? cerrare este problema por el tiempo que lleva inactivo, sientase libre de volverlo a abrir y reportarlo.
