### ISSUE TITLE
Checklists not correctly imported from backup

### ISSUE THREAD

**Issue by really-just-a-tech** [alainm23/planify#738]
**Describe the bug**
When importing a backup, all checklist items will be converted to normal tasks.

**To Reproduce**
1. Create a task with checklist items
2. Go to Preferences > General > Export database and save your backup somewhere
3. Delete all Planner data
4. Import the previously saved backup
5. See that the checklist items are now separate tasks

**Expected behavior**
Checklist items should be imported as checklist items.

**Screenshots**
Before backup:
![afbeelding](https://user-images.githubusercontent.com/59294175/116405763-48e81d00-a830-11eb-8db9-1ec6adb8f93b.png)
After backup and import:
![afbeelding](https://user-images.githubusercontent.com/59294175/116405796-57cecf80-a830-11eb-8097-3b98ab7dc28e.png)

**Desktop:**
 - OS and DE: Fedora 33 with GNOME 3.38.5
 - Version 2.6.9 (Flatpak)

**Additional context**
When making a second backup after the import, you can see that the "parent_id" is 0 instead of the id of the task it belongs to. It is correct in the first backup, so the problem lies with the import.

**Comment by alainm23** [comment]
This functionality has not yet been developed in Planify, you can reopen it or create one when the functionality is available.
