### ISSUE TITLE
[Todoist] Labels now included in Free Plan 

### ISSUE THREAD

**Issue by dmlls** [alainm23/planify#739]
Todoist [rececently announced](https://todoist.com/help/articles/whats-new#making-new-plans-apr-13) that labels (and filters) are no longer a Premium feature.

I guess by now all references to the setting `"todoist-sync-labels"` can be deleted (or set to `true` by default) for the labels to work for everyone.

https://github.com/alainm23/planner/blob/6602d279469075880ec5525dbbd8557dae776558/src/Services/Todoist.vala#L259-L261

**Comment by skaldebane** [comment]
Todoist also has task descriptions in beta right now! I write task descriptions all the time, but I've recently had a disk failure that made me lose them because they're not synced with Todoist.
Also, Todoist limits maximum number of projects to 5, which may be discouraging to new users of Planner.

**Comment by alainm23** [comment]
@Skaldebane This is good and bad news. Planner will be able to sync descriptions, but limiting the user to only 5 projects in the free version is very bad, I hope Todoist will reconsider this. The good thing is that Planner is working on CalDAV support, but there are definitely a lot of things they don't support (Tags, Sections, etc).

**Comment by alainm23** [comment]
@dmlls Thanks for the observation, I just tested it and it works correctly.
