### ISSUE TITLE
Updating issues creates many notifications

### ISSUE THREAD

**Issue by eliocamp** [alainm23/planify#74]
I recently added my github profile and selected some repos to watch for issues. As soon as I clicked "udpate issues" Planner created a barrage of notifications (one per new issue) that I had to remove manually: 

![image](https://user-images.githubusercontent.com/8617595/60731995-4875e800-9f1f-11e9-9cfe-7ab23343998d.png)

I would expect either to not create notifications when updating issues (since it's manually done, there's no need to get the user's attention) or create just one notification with something like "23 new issues imported".

**Comment by alainm23** [comment]
You're right, I'll see how I solve it

**Comment by alainm23** [comment]
I'm very sorry, Planner 2 no longer supports Github Issues, but if it does in the future I will take this problem into account.
