### ISSUE TITLE
Allow resizing of sections

### ISSUE THREAD

**Issue by StoicDeveloper** [alainm23/planify#742]
In the board view, there is a lot of wasted space, such that a maximum of three additional sections can be added before (in my resolution) the next section does not appear on screen.

The sections should resize automatically to take up only the space that is needed to display all necessary information, and resize according to user input, showing or hiding information as space allows.

**Comment by alainm23** [comment]
The board view is still under development, feel free to open the issue when the functionality is available. thank you,
