### ISSUE TITLE
Allow renaming the (no section) section

### ISSUE THREAD

**Issue by StoicDeveloper** [alainm23/planify#743]
All tasks without a specified section are associated by default with the (no section) section. In board view, this has the static label (no section) though there is no label in the default view. It would be useful to allow the user to select a different name for this default section.

Solution:
Add a button that allows this section to be renamed

**Comment by Arcitec** [comment]
The best solution is if the default section can be renamed per-project, just like any other section.

Renaming tools should be shown in 2 cases:

- In board view: Always show "rename" feature, permanently.
- In normal view: Only show the default section if the user has created at least one more section. So, projects in normal view start out without any visible section. Then, if the user creates extra sections, the default section shows up too and lets the user rename it too. If the user deletes all other sections again, it should hide the default section in normal view again.

**Comment by alainm23** [comment]
The board view is still under development, feel free to open the issue when the functionality is available. thank you,
