### ISSUE TITLE
Add swimlane support

### ISSUE THREAD

**Issue by StoicDeveloper** [alainm23/planify#744]
Kanban boards typically have "swimlanes" which allow tasks to be sorted vertically on the board. This allows the user to differentiate tasks at a glance based on an arbitrary tag possessed by the task. Currently sorting is only possible by date, priority and name, but not by type of task, or other arbitrary tags. Adding "swimlanes" would greatly help with the users ability to organize their tasks according to their own needs.

Solution:
Add a category between project and section, ex. projects have categories, which have sections, which have tasks. Or projects have a table with axes categories and sections, and tasks are all assigned to one section and one or more categories.

**Comment by alainm23** [comment]
The board view is still under development, feel free to open the issue when the functionality is available. thank you,
