### ISSUE TITLE
Allow changing section of repeating task, it then moves back to default upon repeat

### ISSUE THREAD

**Issue by StoicDeveloper** [alainm23/planify#745]
Currently a repeating task cannot be moved into another section from the board view. For example, a "to do"  section may contain a repeating task, which cannot then be moved to a "completed" section upon completion. The repeated character of a task should not affect whether it can be moved. Rather, it should affect only its own subsequent moves.

Solution:
For each repeated task, upon its repetition, move the task to the default section, otherwise place no restrictions on its ability to move sections.

**Comment by alainm23** [comment]
The board view is still under development, feel free to open the issue when the functionality is available. thank you,
