### ISSUE TITLE
Sections with repeated task do not have "add task" button

### ISSUE THREAD

**Issue by StoicDeveloper** [alainm23/planify#746]
If a section has a repeated task in it, then that section's "add task" button is not visible.

**To Reproduce**
1. add a repeated task to a section

**Expected behavior**
The presence of a repeated task should have no effect on the ability to add tasks

**Screenshots**

**Desktop (please complete the following information):**
 - OS or DE: ubuntu 18.04.5
 - Version 2.6.9

**Comment by alainm23** [comment]
Planner is no longer supported, I will close this issue due to downtime.
