### ISSUE TITLE
Quick Find not opening

### ISSUE THREAD

**Issue by cohalex** [alainm23/planify#747]
[Planner 2.6.9 on Ubuntu 20.04.02]

Quick Find stopped working. Clicking the top left shortcut or Ctrl+F does nothing. There's a very brief flicker, as if the main window lost focus, but no dialog or window appears (and the focus isn't actually lost).
It used to work last time I tried a few days ago and I didn't change anything since then.
Is there a log file that may have some error details?

**Comment by alainm23** [comment]
This bug was fixed in Planify 4.1
