### ISSUE TITLE
Integration with Pantheon Online Accounts

### ISSUE THREAD

**Issue by marbetschar** [alainm23/planify#75]
Usage of Pantheon Backend for Online Accounts would be highly appreciated. This opens the door for easy future integration of different Cloud providers such as Google, Nextcloud, Exchange etc.:

https://github.com/elementary/switchboard-plug-onlineaccounts

**Comment by coworkingon-es** [comment]
Yes please!!

**Comment by alainm23** [comment]
Thank you very much for your comments. Now I am working on a new version of Planner with support for Todoist and local tasks, sorry, I think Planner will not be able to use Pantheon Backend for Online Accounts.

But this functionality is being worked on https://github.com/elementary/tasks To which I am attentive and supporting with some ideas of design and development.

**Comment by alainm23** [comment]
I'll reopen this problem. I think synchronization with different providers in the cloud now if possible. This is because Planner is growing as software and is becoming very flexible.

**Comment by alainm23** [comment]
I will close this issue in favor of #555
