### ISSUE TITLE
adding alt sync services

### ISSUE THREAD

**Issue by mlaarebi** [alainm23/planify#750]
**Is your feature request related to a problem? Please describe.**
the current sync service has its limits. Lots of times I had to merge projects and sub-projects just to stay under the limits of what is acceptable by the used service.

**Describe the solution you'd like**
giving the user the choice to sync his data with other services like Dropbox or Nextcloud.

**Comment by BeatLink** [comment]
Would be resolved by https://github.com/alainm23/planner/issues/623
