### ISSUE TITLE
Goofy fedora colors (duplicate, but someone got 30 seconds?)

### ISSUE THREAD

**Issue by markallasread** [alainm23/planify#751]
Fedora & planner don't work well together even with the related elementary packages installed.
Does anyone happen to have the stylesheet.css reference that would correlate with the titles for tasks when an existing task is selected? 

Attached a screenshot of what I'm referring to. Adding a new task has the appropriate text color, but selecting an existing task changes the text to white (which is also the color of the BG). I've wandered through every .item reference in the css with no luck.

![Screenshot from 2021-05-25 17-51-20](https://user-images.githubusercontent.com/1235464/119573323-14f60e00-bd82-11eb-8516-02444199e49b.png)

![Screenshot from 2021-05-25 17-51-26](https://user-images.githubusercontent.com/1235464/119573337-18899500-bd82-11eb-825a-3b262c4525a9.png)

Thanks in advance!

**Comment by markallasread** [comment]
Further testing leads me to believe data/stylesheets.css is not being used when running com.github.alainm23.planner — which explains why I'm not making much headway :)

**Comment by alainm23** [comment]
@markallasread Are you sure you installed the correct [stylesheet](https://github.com/elementary/stylesheet/releases/tag/5.4.2)?  In any case, I recommend installing Planner from Flathub to avoid this type of problem.

**Comment by markallasread** [comment]
Yeah, that sorts it — appreciated.

**Comment by P4Cu** [comment]
There's also a way to make the RPM version working.

In the /usr/share/applications/com.github.alainm23.planner.desktop
You need to change:
`Exec=com.github.alainm23.planner`
to
`Exec=env GTK_THEME=io.elementary.stylesheet.blueberry com.github.alainm23.planner`

This requires the elementary stylesheet to be installed:
`dnf install elementary-theme`

All available themes can be listed by:
`ls /usr/share/themes/ -l`

I believe that we could work on a SPECFILE that could have these things included (required package and desktop fix).

PS the Fedora counterpart bug is: https://bugzilla.redhat.com/show_bug.cgi?id=1974869 Specfile can be also found there.
