### ISSUE TITLE
Typo: "Morning" is spelled wrong in Date/Time settings

### ISSUE THREAD

**Issue by mbc3** [alainm23/planify#755]
In the "Date&Time" settings, "Morning" is spelled wrong.

This is on 2.7

**Comment by kd2flz** [comment]
Here's a screenshot 
![image](https://user-images.githubusercontent.com/47010084/120643079-b563c680-c443-11eb-8367-4f91a961c36d.png)

**Comment by mjoork** [comment]
Not only that, the variable is also misspelled :smile:
https://github.com/alainm23/planner/blob/dab2d9bca94d410819adfb2b38bc33b8503c16d3/src/Dialogs/Preferences/Preferences.vala#L557
https://github.com/alainm23/planner/blob/dab2d9bca94d410819adfb2b38bc33b8503c16d3/src/Dialogs/Preferences/Preferences.vala#L567

**Comment by mjoork** [comment]
This [pull request](https://github.com/alainm23/planner/pull/778) closes this
