### ISSUE TITLE
Use system window decoration setting no longer works in Pop!_OS 20.10 after Planner 2.7 update

### ISSUE THREAD

**Issue by rikugo1** [alainm23/planify#757]
**Describe the bug**
Use system window decoration setting no longer works in Pop!_OS after Planner 2.7 update

**To Reproduce**
Enable system window decoration in and restart.

**Expected behavior**
System title bars will apply as they did just prior to the 2.7 update.

**Desktop (please complete the following information):**
Pop!_OS 20.10, Gnome 3.38.0

**Comment by mbc3** [comment]
this is also broken for me on Arch and Plasma 5.21.5

**Comment by Lorenzo888** [comment]
Same on Linux Mint 20.1

**Comment by Devansh80** [comment]
same for me on Ubuntu 20.04 LTS

**Comment by ProfessorCode212** [comment]
It's the same on Linux Mint 19.3 as well.

**Comment by vroger11** [comment]
Same on Kubuntu 20.04 LTS

**Comment by robotic-rabbit** [comment]
Same on Manjaro KDE

**Comment by borges-filipe** [comment]
Same on Arch and Gnome 40.2.0 on Wayland
