### ISSUE TITLE
Unable to Change Font Size

### ISSUE THREAD

**Issue by ProfessorCode212** [alainm23/planify#761]
**Describe the bug**
After updating to _Planner 2.7_, trying to change the font size only affects the subsections of _Preferences_. The rest of _Planner_,  including the main _Preferences_ window is unaffected. Restarting the app didn't make a difference.

**To Reproduce**
1. Go to _Appearance_ under _Preferences_.
2. Change the font size.
3. Notice the difference in font size.

**Expected behavior**
The font size is changed throughout _Planner_.

**Screenshots**
![image](https://user-images.githubusercontent.com/78950242/120723340-2ca26480-c4ef-11eb-983f-ec35302a00dd.png)
![image](https://user-images.githubusercontent.com/78950242/120723357-36c46300-c4ef-11eb-9512-863f2d2fd050.png)

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint (Cinnamon)
 - Version: 19.3
 - Installation Method: Flatpak

**Comment by steel-steven-87** [comment]
I really like the app, but this is something that's a major annoyance in version 2.7. Not every element in the UI follows the slider setting. The text is too tiny on high resolution displays.

**Comment by evankersey** [comment]
This problem is reproducible on fedora 35 - flatpak.

**Comment by alainm23** [comment]
Fixed in the new version of Task Planner
