### ISSUE TITLE
Unable to Add Sections in Projects

### ISSUE THREAD

**Issue by ProfessorCode212** [alainm23/planify#762]
**Describe the bug**
When using _Board View_ in a Project, clicking on _Add Section_ in the project settings or pressing `S` on the keyboard doesn't do anything. There is also no option to add a section in _Inbox_ when using _Board View_.

**To Reproduce**
1. Create a new project.
2. Toggle _View as Board_ in project settings. 
3. Add a new section through the project settings or by pressing the shortcut key.
4. A section **will not** be added.

**Expected behavior**
Trying to create a section actually makes one in the project.

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint (Cinnamon)
 - Version: 19.3
 - Installation Method: Flatpak

**Comment by airtonix** [comment]
I've found that if you switch off `Board View` you can then add sections, which then show up as expected when you switch back to `Board View`

**Comment by alainm23** [comment]
The board view is still under development, feel free to open the issue when the functionality is available. thank you,
