### ISSUE TITLE
'Inbox' got cleared!

### ISSUE THREAD

**Issue by ProfessorCode212** [alainm23/planify#764]
**Describe the bug**
After getting the update for _Planner 2.7_, all the tasks in my _Inbox_ disappeared. I had to go to _Upcoming_ in order to retrieve them again. All my previous _Completed tasks_ were completely lost. I don't have any _Projects_ so I don't know if it applies to that.

**Expected behavior**
Updating _Planner_ makes no changes to any of my tasks or the places in which they are kept in.

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint (Cinnamon)
 - Version: 19.3

**Additional context**
I've installed _Planner_ as a Flatpak.

**Comment by antimech** [comment]
#479

**Comment by ProfessorCode212** [comment]
This is an update. Even after I specifically added a task to _Inbox_, it still failed to show up there. It's currently only visible in _Upcoming_.
