### ISSUE TITLE
Default Project For New Tasks

### ISSUE THREAD

**Issue by ProfessorCode212** [alainm23/planify#765]
**Describe the bug**
When creating a new task, either directly or through _Quick Add_, _Planner_ doesn't select _Inbox_ as it's default project since it's update. This has resulted in some unexpected behavior where some tasks don't show up.

**Expected behavior**
When creating a new task, it adds it to _Inbox_ by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/78950242/120754877-dce18e80-c52a-11eb-90ab-b8e890549462.png)

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint (Cinnamon)
 - Version: 19.3

**Additional context**
I've installed _Planner_ as a Flatpak.

**Comment by alainm23** [comment]
This bug was fixed in Planify 4.1.
