### ISSUE TITLE
[HELP NEEDED] Replacing the `database.db` with a symbolic link crashes the application

### ISSUE THREAD

**Issue by bxff** [alainm23/planify#767]
**Describe the bug**
When replacing the `database.db` with a symbolic link back to `database.db` crashes the application. I am doing this so that I can locally backup the files in a folder which I can later use as a easy backup or to use as live backup from multiple devices.

I am still new to Linux and am not sure if this is the way to achieve my backup goal. I will later try using `rsync` and similar sollution to achieve the same thing and report.

**To Reproduce**
2. Move the file to `somemedia` I have attached to my system: `mv "/home/dex/.var/app/com.github.alainm23.planner/data/com.github.alainm23.planner/database.db" "/media/somedrive/database.db"`
1. Make a link: `ln -s "/media/somedrive/database.db" "/home/dex/.var/app/com.github.alainm23.planner/data/com.github.alainm23.planner/database.db"`

**Expected behavior**
Should simple work, with everything getting backedup.

**Desktop:**
 - OS or DE: Zorin 16
 - Version 2.7

**Additional context**
Did I do anything wrong?

**Comment by bxff** [comment]
Also I got the `database.db` file location from this issue, depending on how you installed Planner the location may be different: https://github.com/alainm23/planner/issues/609

**Comment by fmneto** [comment]
I don't think glib has the capability of following symlinks.

I suggest adding a cronjob to copy it regularly (ideally, you should check if the file is being used). rsync is a good option for that.

**Comment by BeatLink** [comment]
Though @alainm23 really doesn't recommend it, and would rather you use the export system, there is a way to manually set the path of the planner database via dconf. I cant remember the exact instructions on how to do this, however.

**Comment by alainm23** [comment]
This problem is still pending to be solved and the best solution is to have an import and export service, I will close this issue because Planify 4.1 no longer has this feature.
