### ISSUE TITLE
Allow Imports of planner files, or option to convert from todoist tasks / projects back to planner

### ISSUE THREAD

**Issue by andythedude** [alainm23/planify#768]
**Is your feature request related to a problem? Please describe.**
First of all i love this application, but currently the data transfer from planner to todoist is one way, which for me, since i have decided not to subscribe to todoist, makes things difficult. 

it currently doesn't have the ability for todoist and planner tasks to interact directly.

example: 
i have 30 something tasks in my inbox that are synced with todoist, I want to add them to planner projects, but i cannot add todoist synced tasks to a planner project.  If i log out of todoist my tasks dissapear from planner. there is no way to convert these back to planner tasks other than manually re-key all of them.

Solution 1:
add an option to convert all tasks that are currently todoist tasks back to planner tasks on the logout option for todoist options, so you can uncouple yourself from todoist if you'd like to.
Solution 2: 
add an option to reimport the planner file that you currently can only export.

I have tried to export, log out of todoist and then reimport my tasks, but there seems to be no option for that anywhere, or any documentation on how to do so.

Thank you

**Comment by krillin666** [comment]
+1

**Comment by alainm23** [comment]
This feature is available in Planify 4.7.2
