### ISSUE TITLE
Old Data Project are Gone

### ISSUE THREAD

**Issue by syahrulfadli** [alainm23/planify#769]
**Describe the bug**
I'm just open the apps then the apps show me "What's new" dialog box then i close it.

The recent data project that I created still there but another data, like my project that I created a week ago and older is gone, the title project and description still there and the theme reset to light (my previous setting is dark).

**Aditional information**
I'm run sudo apt update/upgrade yesterday.

**Screenshots**
![Screenshot from 2021-06-11 10-23-20](https://user-images.githubusercontent.com/64543548/121626170-212adc80-ca9f-11eb-9f06-bb121cbd8510.png)

**Desktop (please complete the following information):**
 - OS or DE: Ubuntu 20.04 - Gnome 3
 - Planner 2.7

**Comment by antimech** [comment]
Same on Linux Mint 20, everything is gone after the last update. Can't use the app except starting from scratch. I had thousands of tasks there. :disappointed:

**Comment by nsmlzl** [comment]
A quick (and dirty) workaround for me was to roll back the flatpak package to the previous version (v2.6.9): 

`$ sudo flatpak update --commit=61a2b8c67b62e14a89722c21d313592ddc1af13c97f65719297b1b63c023bd2f com.github.alainm23.planner`

More information regarding [flatpak package roll back](https://unix.stackexchange.com/a/552700/280557).
