### ISSUE TITLE
Duplicated tag when im creating a task

### ISSUE THREAD

**Issue by marcelsby** [alainm23/planify#772]
**Describe the bug**
When i am creating a task and put a tag in this creation moment when i click in "Add task"  the tag appears duplicated in my task list.

**To Reproduce**
1. Go to "Today"
2. Click on "Add Task" blue button
3. Put the task details (title, note) and tag it.
4. Click on "Add Task"
5. See the tag duplicated in your task card

**Expected behavior**
Was expected that just one tag appears.

**Screenshots**
![planner-bug-report-1](https://user-images.githubusercontent.com/57691142/123555062-beea0100-d759-11eb-89e5-aaf9fbba4f85.png)
![planner-bug-report-2](https://user-images.githubusercontent.com/57691142/123555063-c01b2e00-d759-11eb-9baf-471773e87b91.png)

**Desktop (please complete the following information):**
 - OS or DE: Fedora 34 with Gnome 40
 - Version: 2.7 Flatpak

**Comment by ChibiYuzu** [comment]
I have the same problem here. Except that I'm on Ubuntu 20.04, with Gnome 3.36.8

The solution I found was to save the new task first, before I enter the tags. Then, they don't duplicate. But, it is a bit tedious.
