### ISSUE TITLE
Recurring tasks can not be set to done as they recure immediately

### ISSUE THREAD

**Issue by genyuz** [alainm23/planify#773]
**Describe the bug**
When I want to set a task to done (tick the box) that is set up to be recurring, than the task is scheduled for today immediately and so it does not disappear from the TODAY-view

**To Reproduce**
1. Set up a new task
2. Schedule it for today
3. Set it to be recurring
4. Try to mark it done

**Expected behavior**
I would expect the task to be rescheduled to the next relevant date (eg. tomorrow when the task recurred every 1 day).

**Screenshots**
![Flameshot - Screenshot from 2021-06-29 11-37-21](https://user-images.githubusercontent.com/26007827/123775915-15c51700-d8cf-11eb-9a51-50796e223570.png)

![Screenshot from 2021-06-29 11-37-39](https://user-images.githubusercontent.com/26007827/123775964-21184280-d8cf-11eb-9c90-a82d6536ff64.png)

**Desktop (please complete the following information):**
 - Ubuntu 20 using Cinnamon-Desktop

**Additional context**
-

**Comment by Ph0enix001** [comment]
> **Describe the bug**
> When I want to set a task to done (tick the box) that is set up to be recurring, than the task is scheduled for today immediately and so it does not disappear from the TODAY-view
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Set up a new task
> 2. Schedule it for today
> 3. Set it to be recurring
> 4. Try to mark it done
> 
> **Expected behavior**
> I would expect the task to be rescheduled to the next relevant date (eg. tomorrow when the task recurred every 1 day).
> 
> **Screenshots**
> ![Flameshot - Screenshot from 2021-06-29 11-37-21](https://user-images.githubusercontent.com/26007827/123775915-15c51700-d8cf-11eb-9a51-50796e223570.png)
> 
> ![Screenshot from 2021-06-29 11-37-39](https://user-images.githubusercontent.com/26007827/123775964-21184280-d8cf-11eb-9c90-a82d6536ff64.png)
> 
> **Desktop (please complete the following information):**
> 
> * Ubuntu 20 using Cinnamon-Desktop
> 
> ## **Additional context**

I have the same problem for daily reoccurring tasks.

**Comment by Ph0enix001** [comment]
I have the same problem with daily reoccurring tasks.

**Comment by QuentinLab** [comment]
I have observed the same problem with every type of reccuring task

Desktop : Ubuntu 18.04 Gnome 3

**Comment by alainm23** [comment]
This bug was fixed in Planify 4.1.
