### ISSUE TITLE
System Window Decoration Do Not Work

### ISSUE THREAD

**Issue by heptahex** [alainm23/planify#776]
**Describe the bug**
Although I've changed planner's appearance in preferences and set the button layout to 'Use system window decoration', planner does not follow system theme's window decoration. I also restarted the planner and even rebooted my system. But it didn't work.

**Expected behavior**
The expected behavior is planner must follow my current using GTK theme's window decoration like any other apps.

**Screenshots**
![Planner-Error](https://user-images.githubusercontent.com/82636866/124541208-f5550980-de46-11eb-93e5-d6a539d969e0.png)

**Desktop (please complete the following information):**
 - OS or DE: [Pop OS 20.04 LTS, Gnome 3.36.8]
 - Version [2.7, flatpak]

**Additional context**
Planner is a perfect tool for my daily productivity. The one which only annoying me is planner's window decoration. Although it's a not big problem, I hope to see planner integrated with my system theme. And thank you for bringing planner.

**Comment by williamd1k0** [comment]
I have the same issue on Manjaro Linux Xfce (v2.7 flatpak).
It used to work on previous versions, but I don't remember which versions though.

**Comment by sriram-kailasam** [comment]
Having the same issue on Planner 2.7 with Ubuntu 20.04.

**Comment by sriram-kailasam** [comment]
Looks like this is the same as #757

**Comment by Suzie97** [comment]
elementary Tasks had a similar issue and was recently fixed by using a Hdy.HeaderGroup. Planner can most probably do something similar

https://github.com/elementary/tasks/pull/277

**Comment by JaneSmith** [comment]
Same issue here on Fedora Silverblue 34.

**Comment by borges-filipe** [comment]
Same issue on Arch with Gnome using the Flatpak
