### ISSUE TITLE
Subtasks not hidden by "Hide Tasks Details" feature

### ISSUE THREAD

**Issue by SaiKiru** [alainm23/planify#779]
**Describe the bug**
If I try to hide all tasks details, only the main tasks are hidden. The subtasks remain "opened" or their details are not hidden.

**To Reproduce**
1. Go to any project
2. Add some tasks
3. Add some subtasks
4. Hide tasks details with CTRL + H or the option in the utilities in the upper right

**Expected behavior**
ALL tasks will have their details hidden.

**Screenshots**
Before hiding details:
![image](https://user-images.githubusercontent.com/59113205/125168462-4adb3e80-e1d8-11eb-9c92-cb506c6d6f03.png)

After hiding details:
![image](https://user-images.githubusercontent.com/59113205/125168471-4f075c00-e1d8-11eb-9863-70196cadb3bc.png)
After hiding details

**Desktop (please complete the following information):**
 - OS or DE: Pop!_OS 21.04 - GNOME 3.38.5
 - Version 2.7

**Additional context**
I tried using both the flatpak version and compiling the source.

**Comment by alainm23** [comment]
It is a strange behavior, but valid, the solution could perhaps be to add a new button that closes the subtasks
