### ISSUE TITLE
ToDo list support for tasks

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#780]
**Is your feature request related to a problem? Please describe.**
I have a Baikal caldav server setup and I can use OpenTasks on Android, Evolution and now Planner on linux. I can add "todo list items" on my OpenTasks without a problem, but my suggestion is going to make todo lists or sub todo lists on planner look nicer.

**Describe the solution you'd like**
Support sub task lists or todo lists inside planner tasks, like the attached image.

Below, this is how I manage small "todo lists" on planner:
![2021-07-17_17-37](https://user-images.githubusercontent.com/81695893/126048821-725435af-299d-48d0-af62-aa1f2c7dc424.png)

And this is how I manage on my phone, using OpenTasks. Note that I use the same caldav address book to manage the tasks.
![WhatsApp Image 2021-07-17 at 17 40 32](https://user-images.githubusercontent.com/81695893/126050086-af0ac9af-80e0-4310-bcb7-f8dcf6804779.jpeg)

**Comment by SaiKiru** [comment]
Don't we already have subtasks?

**Comment by ghost** [comment]
> Don't we already have subtasks?

Where? I couldn't do that.

**Comment by Ph0enix001** [comment]
> > Don't we already have subtasks?
> 
> Where? I couldn't do that.
![Sample Task](https://user-images.githubusercontent.com/87118723/126582562-57617b8e-b9f3-4adf-9c3f-4827d3451125.png)


The icon in the red rectangle is used to create sub-tasks.

**Comment by alainm23** [comment]
CalDAV support is under development for Planify, I will close this issue until the implementation is done. thank you.
