### ISSUE TITLE
Tag and Sub-task Issue

### ISSUE THREAD

**Issue by Ph0enix001** [alainm23/planify#781]
> When I export my database and import it on another system the sub-tasks are displayed as tasks and the tags are not linked to the tasks.

**Comment by SaiKiru** [comment]
Please follow the issue template and be more specific

**Comment by Ph0enix001** [comment]
> Please follow the issue template and be more specific

**Describe the bug**
The tag's and sub-tasks are not imported properly. Tags are not linked to the tasks and sub-tasks are displayed as plain tasks.

**To Reproduce**
Steps to reproduce the behaviour:

1. Export any existing project with sub-tasks and/or tags.
2. Import the back up in the freshly downloaded planner application.
3. Inspect the tags and sub-tasks.

**Expected Behaviour**
All the tags and sub-tasks will be intact as in the previous/original project.

**Screenshots**
This is the original task:
![Task Orignal](https://user-images.githubusercontent.com/87118723/126583288-86f5e2cc-5425-467a-bef6-fa8fb5d15839.png)

This is the imported task:
![Task Imported](https://user-images.githubusercontent.com/87118723/126583309-d2a3a8b1-5353-4277-a2e9-8d59e76a7525.png)

**Desktop**
- Endeavour OS

**Additional context**
I tried using the flatpak version AUR version both have this problem.

**Comment by raulV92** [comment]
I've run into this as well, I wonder if this is more of a feature request to have planner export the subtask details alongside the sub tasks, or something similar...

**Comment by alainm23** [comment]
I will close the problem because Planify 4.1 does not have an import/export service yet, it will be addressed when the functionality is implemented
