### ISSUE TITLE
[HELP NEEDED] How can I configure the location of the database.db file?

### ISSUE THREAD

**Issue by codeRetard** [alainm23/planify#784]
I am trying to find a way to move the default location of the database.db file to a location of my choosing, mainly for it to be shared between different devices using my cloud but there's no place on the General settings of the application to do so, nor can I find any config file to make the change.

I am using the flatpak version and I can confirm that the current location of my database.db is at "_/home/[user]/.var/app/com.github.alainm23.planner/data/com.github.alainm23.planner/database.sb_" The question now is how can I move it to another location?

I am running OpenSUSE Tumbleweed Rolling Release and have Planner version 2.7 installed from the Flathub.

Cheers.

**Comment by alainm23** [comment]
I will close the issue because Planify 4.1 does not have an import/export facility yet, it will be addressed when the functionality is implemented.
