### ISSUE TITLE
Can't resize below title width

### ISSUE THREAD

**Issue by Freeplayg** [alainm23/planify#786]
**Describe the bug**
If you have a long title name, you can't resize the window below it

**To Reproduce**
1. Open Planner
2. Add a note with a really long title
3. Try to resize the window

**Expected behavior**
When you resize the window, the title should wrap.

**Screenshots**

https://user-images.githubusercontent.com/40742947/128795812-b9c6ffb3-76d0-4f2d-8299-3806165f0762.mp4

**Desktop (please complete the following information):**
 - OS or DE: Pop! OS
 - Version: 21.04

**Additional context**

**Comment by puyoxyz** [comment]
This also happens with a lot of labels (so both labels and titles need to wrap)
