### ISSUE TITLE
Viewing a project in Board View always shows an empty section taking up valuable space

### ISSUE THREAD

**Issue by linuxhype** [alainm23/planify#787]
**Describe the bug**
When you create a project and toggle on the "View as Board" option, an empty section is always shown as the first section of the board, despite the user not having created a section. This section takes away valuable space, pushing your real sections over to the side.

**To Reproduce**
1. Create a new Project
2. From the top-right context menu, toggle ON the "View as Board" option
3. Observe that an empty section is present on your board, despite not having created a section

**Expected behavior**
The board should only show the sections that the user has created.

**Screenshots**
![image](https://user-images.githubusercontent.com/88370509/129360897-7e35e27b-6b8f-4ee0-a855-8f16f33e7baf.png)

**Desktop (please complete the following information):**
 - OS or DE: Pop OS! GNOME/Cosmic
 - Version 21.04

**Comment by alainm23** [comment]
The board view is still under development, feel free to open the issue when the functionality is available. thank you,
