### ISSUE TITLE
Checking recurring tasks doesn't work - issue with the "repeat" setting

### ISSUE THREAD

**Issue by ChibiYuzu** [alainm23/planify#788]
**Describe the bug**
When I want to check a recurring tasks to have it re-scheduled as indiciated in the "repeat" setting, the check doesn't work. I get a message that the task has been marked completed, but the task itself is still there, as if not completed

**To Reproduce**
1.Create a new task
2. Set it to repeat every week
3. Check the task to indicate it has been completed

**Expected behavior**
Once checked, the task should disappear from the "today" view and should be re-introduced in the project with the next deadline. 

**Desktop (please complete the following information):**
 - OS or DE: Ubuntu 20.04, Gnome 3.36.8
 - Version of Planer: 2.7

**Additional context**
The same thing happens when I set subtasks to repeat  on a weekly basis. Actually, if I suppress the subtask, checking the main task works. There seems to be an issue with the repeat setting.

**Comment by ChibiYuzu** [comment]
I just found out that if I check the task after the deadline, it doesn't go away. The only thing I can do, is to change the deadline date to the next one manually. Then, it will simply report the task to the new date. So, this means that one can't check a task set for repeat later than when it is due. Otherwise, nothing happens and the task remains in the "late" section, no matter what. 

This is kind of annoying, because it means that I have to really remember to check stuff on deadline in Planner. If I forget, I have to manually change the deadline to the next one.

**Comment by Knyffen** [comment]
I have the same problem and have one thing to note:
When I check the task it the popup says "Completed. Next occurrence: Sep 1 [Undo]", with september 1st being the date of the original task, not a week later as it should have been. Also, the task doesn't shop up as a completed task, although I don't know if repeated tasks are supposed to.
So while I don't know what _actually_ happens, it is possible that the repeat function "works", but that it sets the date of the new task to the same as the original task  (assuming that it isn't supposed to show up as completed).

(I am running the Flatpak version on Manjaro.)

**Comment by cansozbir** [comment]
Same issue for me.

**Comment by t26y** [comment]
I also have this issue (Flatpak version on Fedora). Whats even more surprising is that even if I complete the task in the Todist Interface, which correctly sets the next due date in the future, Planner still displays the task with the old due datem, even after manually initiating a synchronization. Only removing the Todoist connection and adding it again resolves this, but this can obviously not be a solution.

**Comment by mrBluestSky** [comment]
I have the same issue. Flatpak version on Fedora's xfce spin.
