### ISSUE TITLE
CalDav tasks do not show up in "today" and "upcoming" lists

### ISSUE THREAD

**Issue by renestalder** [alainm23/planify#789]
**Describe the bug**
Tasks created in a CalDAV connected list do not show up in the generic "today" and "upcoming" lists.

**To Reproduce**
1. Activate the CalDAV extension and create a task list in a compatible application, e.g. Thunderbird
2. Restart Planner
3. Go to the now visible CalDAV list
4. Create two tasks, one with today's date and one scheduled for tomorrow.

**Expected behaviour**
One task should show up under "today" and one under "upcoming"

**Screenshots**
–

**Desktop (please complete the following information):**
 - OS or DE: Pop_OS 21.04, Cosmic (Gnome)
 - Version: Planner 2.7

**Additional context**
–

**Comment by therealrobster** [comment]
Hi there, do you mind if I cask how you do step 1?  "Activate the CalDAV extension".  I can't find this anywhere. 
I should note I have my own server at something like `https://ip.address.etc/caldav/url/etc`

Thank you

**Comment by alainm23** [comment]
CalDAV will be available in Planner 3 beta2

**Comment by therealrobster** [comment]
Thank you so much for the reply.  Is there a rough ETA on that?  No pressure at all, just 'planning' my software :-)   I really like Planner.  Out of all I've tried there is no doubt this is one of the best out there.

**Comment by therealrobster** [comment]
Sorry to comment on a closed thread, but just checking.  Is this closed due to it being complete or just cleaning up as it's probably elsewhere?  Thank you

**Comment by alainm23** [comment]
This feature is available in the next release.

**Comment by wvdtoorn** [comment]
Hi, I am using the Planner 3 Beta 2 release and I am still experiencing the issue that tasks created in a CalDAV connected list do not show up in the generic "today" and "upcoming" lists. Do you have some thoughts on how to address this? 

Edit: I realized my issue might not be exactly the same as the one in this thread. The tasks *are* detected (indicator digit in Today/Scheduled tab), but just not showing. See #944
