### ISSUE TITLE
Labels show up twice in the task

### ISSUE THREAD

**Issue by AnishDe12020** [alainm23/planify#791]
**Describe the bug**
If a label is added to a task, it shows up twice on the task component.

**To Reproduce**
1. Add a task with label
2. See the task

**Expected behavior**
The label should show up just once

**Screenshots**
![image](https://user-images.githubusercontent.com/63192115/129894755-d893a746-7ba9-4933-9e90-a0b08ab524a1.png)
![image](https://user-images.githubusercontent.com/63192115/129894782-861e592a-35e0-466c-8553-8ed68d08c4b6.png)

**Desktop (please complete the following information):**
 - OS or DE: Pop OS 21.04 with GNOME 3.38
 - Version: 2.7

**Additional context**
None.

**Comment by puyoxyz** [comment]
Can reproduce on 2.7, GNOME 41, [flatpak info](https://gist.github.com/puyoxyz/38d263eb0bd47d24ae2a7133421fdb50). They don't appear twice in the Todoist app on my phone, and if I `flatpak kill com.github.alainm23.planner` and reopen Planner, the duplicates disappear.
