### ISSUE TITLE
How would I go on and increase the total ui size

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#792]
It is not a problem, but when increasing the font size it doesnt get reflected in the whole app and I was wondering how could I do the same

**Comment by faiz-crypto** [comment]
+1 when I go to Preferences->Appearance->Font Size and try to move the slider it only changes the font inside the open Preferences window and not the font in the rest of the app.

**Comment by sohzm** [comment]
You can use ```GDK_DPI_SCALE=1.2 planner``` for launching the application,
that will increase the font size 1.2x you can also change it to your liking, ig the range is 0.5 to 2.0

Works as a temporary fix, will definitely like in the preferences

**Comment by ghost** [comment]
How would I do that

**Comment by sohzm** [comment]
You can add a shortcut that'll execute ```GDK_DPI_SCALE=1.2 planner```.

If you're using a desktop enviroment it should be somewhere in Settings > Keyboard or Shortcuts.
If you're using a window manager you can probably edit its keybinding config, it'll depend on your wm/de

edit: typo

**Comment by CottageCabbage** [comment]
Sorry, I'm having some difficulty understanding what to do. If I'm executing Planner through:
`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=com.github.alainm23.planner com.github.alainm23.planner`

Where should I place `GDK_DPI_SCALE`?

**Comment by sohzm** [comment]
Sorry but I don't really have idea about flatpaks.
But I think [this](https://unix.stackexchange.com/questions/559129/how-do-i-permanently-set-an-environment-variable-for-a-specific-flatpak-applicat) is what you need.

So you'll have to run `flatpak override --env=GDK_DPI_SCALE=1.2 com.github.alainm23.planner #run as sudo` and run application as normal if I'm correct. Just check that page to confirm.

**Comment by CottageCabbage** [comment]
It worked, thank you very much
