### ISSUE TITLE
Suggestions and confirmation for pkgbuild on mpr

### ISSUE THREAD

**Issue by justvipul** [alainm23/planify#798]
I have tried creating a pkgbuild for planner so that it becomes available in mpr which is like an aur but for debian and ubuntu.
https://mpr.hunterwittenborn.com/cgit/aur.git/tree/PKGBUILD?h=planner
Please confirm if it is made as it is intended to be made.

I have created seperate packages for elementary icons and stylesheet as well. So should I ask about it's improvement in here or their respective gh pages?

**Comment by alainm23** [comment]
Planner a dejado de tener soporte, cerrare este issue por el tiempo de inactividad.
