### ISSUE TITLE
Some of the appointments from my calendar (CALDAV) appear on the wrong day in Planner

### ISSUE THREAD

**Issue by ChibiYuzu** [alainm23/planify#802]
**Describe the bug**
In the today view of Planner, appointments from past days appear. Even when I restart Planner, it doesn't change. 

**To Reproduce**
1. Open Planner on "Today" view
2. Look at the appointments from CALDAV calendar. They are from past days. 

**Expected behavior**
When I check the "today" view, I expect to see the appointments I have scheduled for that day to appear, not those from previous days. In the "upcoming" view, the appointments are displayed on the right days and times. 

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - GNOME 3.36.8
 - Planner 2.7

**Further information**
I'm using the calendar tool from the Evolution mail client 3.36.5-0ubuntu1. And I'm synching it with my CALDAV client on my Nextcloud, using Nextcloud desktop client 3.3.1.

**Comment by therealrobster** [comment]
Can I ask, how did you setup CalDav on planner?  I can't find an option anywhere?  I have a CalDav server I want to connect to, but just can't find the option.
