### ISSUE TITLE
Markdown support in task note

### ISSUE THREAD

**Issue by Suzie97** [alainm23/planify#806]
@alainm23 I was thinking of having task note written in markdown

_Originally posted by @Abdallah-Moh in https://github.com/alainm23/planner/issues/760#issuecomment-856855722_

**Comment by sofiedotcafe** [comment]
Probably also like.... saving them in markdown? So it would be easy to e.g. store in a git repo

Bit like obsidian

**Comment by sofiedotcafe** [comment]
Like.... for small todos, this is ok

But for bigger ones?

At least for me, primary markdown support would be essential
