### ISSUE TITLE
task label list font color not displayed correctly

### ISSUE THREAD

**Issue by everyx** [alainm23/planify#811]
**Describe the bug**
Task labels list's font color in left panel is same with it's background, so font disappeared.

**To Reproduce**
1. Open planner from gnome shell

**Expected behavior**
We can see the label text. 

**Screenshots**

![图片](https://user-images.githubusercontent.com/1665522/133867439-8ae57b34-6db7-4592-ac25-6474865d04ab.png)

**Desktop (please complete the following information):**
 - OS or DE: Gnome on Archlinux
 - Version 40.4

**Additional context**
The problem exists under both themes of Adwaita and elementary theme.

**Comment by Caraffa-git** [comment]
I have same issue, on other themes same situation - fonts colors are not changing as they should
Manjaro KDE kernel 5.12.19-1
Planner 2.7

**Comment by cosmopool** [comment]
The cause on Arch Linux is these two packages: 
elementary-icon-theme 6.0.0-1
gtk-theme-elementary 6.1.0-1

You need to downgrade to version 5 as discussed on issue #783, here is the link to the packages: https://github.com/raulV92/planner-old-theme
