### ISSUE TITLE
Repeating todos are broken

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#812]
**Describe the bug**
Repeating todo dates stay the same and do not move into the future

**To Reproduce**
1. Create a repeating todo with a date and enabled recurrence
2. Click the checkbox to mark the task as completed
3. Note that the task does not update the date

**Expected behavior**
Once checked as completed, the task should be rescheduled into the future according to the repeat settings

**Screenshots**

**Desktop (please complete the following information):**
 - OS or DE: Linux mint Cinnamon 20.2
 - Version: 2.7

**Additional context**

**Comment by cansozbir** [comment]
Same for me.

**Comment by alainm23** [comment]
Fixed in the new version of Task Planner
