### ISSUE TITLE
can't make sections in in "view as board"

### ISSUE THREAD

**Issue by MilozW** [alainm23/planify#813]
**Describe the bug**
I can only make sections in a project when in "View as board" is turned **off**

**To Reproduce**
1. Create project (in my case my firs ever)
2. turn "View as board" on
3. click "Add section"
4. nothing will happen

**Expected behavior**
when "View as board" is on, I can add sections to a project

 - Fedora 34 w/ Gnome 40

**Comment by primal-buddhist** [comment]
I can confirm this behaviour. If you select View as  Board _before_ making sections, you also get a "No Section" column which you can't remove.

**Comment by Arcitec** [comment]
+1 I noticed the same thing. Have to temporarily exit board view to make more sections.

**Comment by DebanjanBarman** [comment]
I'm facing the same issue.

**Comment by alainm23** [comment]
The board view is still under development, feel free to open the issue when the functionality is available. thank you,
