### ISSUE TITLE
Delete in bulk all 'Completed Tasks'

### ISSUE THREAD

**Issue by Pkpop** [alainm23/planify#814]
**Is your feature request related to a problem? Please describe.**
Yes. I have many 'completed tasks' per day and it takes time to delete each one, one by one. I don't want to hide the completed tasks since I like seeing them on the list too. 

**Describe the solution you'd like**
I'm trying to figure out if there is a bulk delete button for all completed tasks. If there is non, I would like to request this feature. 

**Describe alternatives you've considered**
Just deleting each tasks one by one does work, it's just time consuming when you have multiple tasks. 

**Additional context**

**Comment by NickMTL** [comment]
I totally agree with this suggested feature : would be so useful !

**Comment by IcedQuinn** [comment]
The lack of bulk editing is also why I tend to bounce quickly when I check up on this. I have 900 open tasks in a kanboard :woozy_face: getting rid of them is a chore.

**Comment by Luflosi** [comment]
It looks like this has been implemented in https://github.com/alainm23/planify/commit/d11abfa94c840ee3debc621411e24367537d6b4d although I find it strange, that the issue was closed as completed on the 11th of May 2024, while the commit was created on the 5th of August 2024.
