### ISSUE TITLE
Font color mismatch

### ISSUE THREAD

**Issue by bitwave** [alainm23/planify#815]
**Describe the bug**
Font color is matching background.

**To Reproduce**
1. Create new task
2. edit task

**Expected behavior**
Text should be visible in description. Labels are affected, too.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1345784/134670939-646c1b36-46c7-414a-ade4-c209cc79982f.png)
![grafik](https://user-images.githubusercontent.com/1345784/134670964-06f6fc05-a491-4973-965c-90670fb9591a.png)
![grafik](https://user-images.githubusercontent.com/1345784/134671009-f0943900-7039-417a-8e39-42bfdc21a8ca.png)

**Desktop (please complete the following information):**
 - OS or DE: Arch Linux, awesome wm
- Planner 2.7

**Comment by RigleGit** [comment]
I'm having the same problem using dark mode, completely unusable 
![image](https://user-images.githubusercontent.com/8595185/136352565-c04d68cc-9d81-4588-a592-bc3c240564ed.png)

**Comment by barreiroleo** [comment]
Same here

**Comment by cs-t1** [comment]
Same thing here 
![image](https://user-images.githubusercontent.com/52403031/138914228-210702d0-3c3e-43ed-a815-dbb03d4aabc1.png)

Pop!_OS 21.04 with Regolith and Planner 2.7

**Comment by CyanCoding** [comment]
Curiously, I've noticed this issue in some distros but not in others. In Ubuntu 21.10 this error isn't present but in Arch it made the whole interface completely unusable.

**Comment by cosmopool** [comment]
The cause on Arch Linux is these two packages: 
elementary-icon-theme 6.0.0-1
gtk-theme-elementary 6.1.0-1

You need to downgrade to version 5 as discussed on issue #783, here is the link to the packages: https://github.com/raulV92/planner-old-theme

**Comment by RigleGit** [comment]
Thanks, it's working perfectly!

**Comment by alainm23** [comment]
Fixed in the new version of Task Planner
