### ISSUE TITLE
Subtasks drag and drop is currently broken

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#818]
**Describe the bug**
When dragging and dropping subtasks, subtasks are moved to the top level and do not retain their place

**To Reproduce**
1. Create a task
2. Create 2 subtasks of the task created in Step 1
3. Drag and drop one of the subtasks to reorder it in the list
4. Notice that the subtask will be moved to a top level task and will not stay a subtask

**Expected behavior**
Subtasks should obey drag and drop behavior and not become top level tasks unless dragged to the top level

**Screenshots**

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint Cinnamon 20.2
 - Version 2.7

**Additional context**

**Comment by alainm23** [comment]
This functionality has not yet been developed in Planify, you can reopen it or create one when the functionality is available.
