### ISSUE TITLE
Planner doesn't maintain sorted order of tasks

### ISSUE THREAD

**Issue by liferooter** [alainm23/planify#819]
**Describe the bug**
When I set sorting and then add task or move task or do something that can modify task order Planner doesn't maintain task order.

**To Reproduce**
1. Add some tasks with different date different from today to the project
2. Enable sorting by due date
3. Add yet another task due today
4. Task will be in the end of list

**Expected behavior**
Tasks should be resorted so new task due today should be at the top of the list.

**Screenshots**
![image](https://user-images.githubusercontent.com/54807745/135869944-e7f168ed-eb57-4d4c-b600-185976e4840a.png)

**Desktop (please complete the following information):**
 - DE: GNOME
 - Version: 2.7

**Comment by KOT040188** [comment]
Sorting by date does not work for me at all. Sometimes when you click this item, the application crashes.
KDE
2.7
