### ISSUE TITLE
Please Add a PPA For Linux Mint

### ISSUE THREAD

**Issue by blueray453** [alainm23/planify#820]
**Is your feature request related to a problem? Please describe.**
The Flatpak takes too long to download.
If I install by source then updating will be difficult (because I will not know when a new update arrives).

**Describe the solution you'd like**
we would like to have a PPA for this app, so that we can install and update planner easily.

**Comment by Arcitec** [comment]
Rejected.

Flatpaks are the best cross-platform distribution solution. Maintaining distro-specific PPAs is too much work regarding compatibility and distro-specific bugs, outdated dependencies, etc.

The only time a flatpak takes time to download is if you're grabbing an entire flatpak runtime environment for the first time. All updates after that are tiny (smaller than PPA updates). And flatpak shares the runtimes between all apps, so you only have to do the large download once per computer.

**Comment by toasterrepairman** [comment]
+1 for this, I have Flatpak disabled on all of my devices (with no intention of changing that), so it would be nice to not build from source every time I want to install the app.
