### ISSUE TITLE
Font Size Slider Affected by Scrolling Causes Unwanted Behavior

### ISSUE THREAD

**Issue by deron-dev** [alainm23/planify#821]
**Description**
When in the appearance menu, if scrolling upward to attempt to see more options, the font size changes and makes the menu hard to use.

**To Reproduce**
1. Go to triple-dot menu in bottom-left corner
2. Click on 'Preferences'
3. Scroll down to bottom of menu
4. Place cursor slightly below 'Font Size' slider
5. Scroll upwards

**Expected Behavior**
The menu scrolls up.

**Actual Behavior**
The menu scrolls up, and the font size increases to max.

**Screenshots**
![image](https://user-images.githubusercontent.com/24536673/140018826-19d2b176-ccb3-497e-8b6b-819ba946343e.png)

![image](https://user-images.githubusercontent.com/24536673/140018860-827fc386-57cb-42f6-8d1e-7822c80bbc07.png)

![Peek 2021-11-03 01-38](https://user-images.githubusercontent.com/24536673/140019393-593e9828-8cec-439f-899e-04ebc6959f15.gif)

**Desktop**
- Operating System: Ubuntu 21.10
- KDE Plasma Version: 5.22.5
- KDE Frameworks Version: 5.86.0
- Qt Version: 5.15.2
- Kernel Version: 5.13.0-20-generic (64-bit)
- Graphics Platform: X11
- Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2

**Comment by alainm23** [comment]
Fixed in the new version of Task Planner
