### ISSUE TITLE
Awful Fonts in Flatpak-Version

### ISSUE THREAD

**Issue by NePank** [alainm23/planify#824]
**Describe the bug**
I use gentoo+kde on my machine. I have installed planner from Flathub via KDE-Discover. However I was not able to use Planner because of the awful fonts  (see screenshot below) from which I get eye bleeding.

In settings toggling the "use system decorations" options does not change anything.  

![Screenshot_20211116_134710](https://user-images.githubusercontent.com/8472408/141988054-91eaa52c-b397-46d1-a656-1f1701827f7d.png)

**To Reproduce**
1. Install Planner with Discover
2. Open it

**Expected behavior**
Not getting eye bleeding

**Screenshots**
![Screenshot_20211116_135542](https://user-images.githubusercontent.com/8472408/141989094-db5a4b82-7a5a-4b46-96cb-d8cd0a13df82.png)

**Desktop (please complete the following information):**
 - OS or DE: Gentoo with Plasma 5.23.3
 - Version: 5.23.3

**Comment by jetflux** [comment]
I have the same issue with Archlinux/KDE. horrible fonts from flatpak install. unusable.

**Comment by osbre** [comment]
I don't have this problem with Linux Mint Una. Maybe installing some fonts outside of Flatpak fixes this?

**Comment by alainm23** [comment]
Fixed in the new version of Task Planner
