### ISSUE TITLE
When attempting to use the app provided "Direct Access" command, errors are received.

### ISSUE THREAD

**Issue by MostHated** [alainm23/planify#826]
**Describe the bug**
When attempting to use the app provided "Direct Access" command, errors are received.

**To Reproduce**
Right-click on a category in the main left side menu and select "Open New Window"
Then in the new window, open the settings menu and select "Edit Project"
At the bottom of that window is a text area labeled "Direct Access" (seen in the image below)

It provides the following command. 
` flatpak run com.github.alainm23.planner --load-project=xxxxxxxxxxxxxxx // - Redacted, in case that number is important for some reason`
But when the command is used, the following errors are had.

```sh
zsh flatpak run com.github.alainm23.planner --load-project=xxxxxxxxxxxxxxx // - Redacted, in case that number is important for some reason
Gtk-Message: 13:38:16.773: Failed to load module "xapp-gtk3-module"
Gtk-Message: 13:38:16.773: Failed to load module "appmenu-gtk-module"
```

![](https://i.imgur.com/r42UJCv.png)
 
**Desktop (please complete the following information):**
Application Version: 2.7

System Information:

<details>
<summary>Details</summary>

OS: Pop!_OS 21.04 x86_64
Host: X570 AORUS ELITE -CF
Kernel: 5.13.0-7620-generic
Uptime: 7 days, 5 hours, 10 mins
Packages: 3465 (dpkg), 9 (brew), 62 (flatpak), 11 (snap)
Shell: zsh 5.8
Resolution: 1920x1080, 2560x1080, 1920x1080
DE: GNOME 3.38.4
WM: Mutter
WM Theme: Pop
Theme: Materia-dark-compact [GTK2/3]
Icons: Flatery-Orange-Dark [GTK2/3]
Terminal: alacritty
CPU: AMD Ryzen 9 3950X (32) @ 3.500GHz
GPU: NVIDIA GeForce RTX 2070
Memory: 41485MiB / 64250MiB

</details>

**Comment by alainm23** [comment]
Planner is no longer supported, can you reopen the issue when the functionality is developed, thank you.
