### ISSUE TITLE
Quick Add, disappearing issue.

### ISSUE THREAD

**Issue by PotatoNut** [alainm23/planify#828]
**Describe the bug**

**To Reproduce**
1. Use the short cut
1.1 The Quick add something will disappear right away, no matter how many times I press the short cut. Fixed after opening the main app. 
2. After it appears, moving of the cursor will cause it to close itself.
3. After I delete the title text and switch to another language (Super +space), it will close itself. 

**Expected behavior**
The Quick app is nice to not be affected by mouse scroll, and other minor key presses. Will be great if there is an option to disable this behavior and let the user close the Quick Add window as normal window.

**Desktop (please complete the following information):**
 - OS or DE: Gnome, Ubuntu 20.04.02 
 - Version : 3.38

**Comment by alainm23** [comment]
Hello, Quick Add is available in Planify 4.1, a keyboard shortcut preset is required (Until Global Keyboard portal is available) by the end user. Greetings.

https://flathub.org/es/apps/io.github.alainm23.planify

**Comment by PotatoNut** [comment]
Thank you so much for this update. It's one of the best To-do apps I have found on Linux. I can't wait to see it becoming mainstream. The only thing I could add to the "Quick Add" is the date picker option or option to open the full app and edit it there.  
Thanks once again.

**Comment by alainm23** [comment]
Thank you for using Planify. Task options for Quick Add will be available in Planify 4.2.
