### ISSUE TITLE
Option to open task details in a Modal or Fullscreen

### ISSUE THREAD

**Issue by VaZark** [alainm23/planify#835]
Occasionally I maintain comments about the task and related details such as links or notes from colleagues within the Task Details section. This becomes a bit frustrating to read when I have the view set to Board view.

I'd like to have an option to have a full-screen view for just one task or large modal for the same so that I can maintain detailed notes with planner.

The alternative would be, I have to maintain a separate set of text files or a separate section for each task. While it is feasible, it easy to lose track of the notes when working with multiple tasks at the same time.

**Comment by alainm23** [comment]
It is available in Planify 4.4
