### ISSUE TITLE
[Feature Request] Collapsible columns in Board model

### ISSUE THREAD

**Issue by VaZark** [alainm23/planify#836]
When I have multiple sections and I am actively using only one or twos sections, its frustrating to slide every time to get to the sections I am using. 

One solution would be to reorganise and bring up the sections I am using currently using however it doesn't seem like the section are rearrangeable on the board view. I usually go to the normal view to rearrange the sections and switch back to board view.  Moreover, the order of sections sometimes have some informal prioritization associated with them.

It would be a cleaner solution if we can just collapse the columns in board mode

**Comment by alainm23** [comment]
The tableron view is not yet available in Planify, please reopen an issue when the functionality is available, thank you.
