### ISSUE TITLE
add webdav protocol support

### ISSUE THREAD

**Issue by PowaBanga** [alainm23/planify#837]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
i really do no know, how to do that

**Describe alternatives you've considered**
webdav is a protocol t synchronize your task with a web server... something like radical, or nextcloud...
so you can synchronize your task with others machines, computers, android, same your freezer if you want ! :yum: 

**Additional context**
An me i will use your application after, that's an important thing too :smile:

**Comment by HansCronau** [comment]
Possible duplicate of #555.
