### ISSUE TITLE
Easy way to backup and restore Database.

### ISSUE THREAD

**Issue by PotatoNut** [alainm23/planify#839]
**Describe the solution you'd like**
I found it difficult to see how could I back up and restore the Database of tasks. I can see export option, but import is missing. While looking for the answer I found where the database is stored: ~/.var/app/com.github.alainm23.planner/data/com.github.alainm23.planner/database.db

If the process of backup and restore could be made easier will be great. Also some kind of automated backup creation scheduling will be peace of mind.

**Comment by tr1p0p** [comment]
I second this. Did you really do a update by thinking "let's DESTROY user database, not testing the import/export on flatpak build, and don't give a shit on issues github" ?

Like, really, it was your plan ?

Wow. Linux world, right ?

**Comment by alainm23** [comment]
Planner is no longer supported, but a backup system is being developed for Planify. Thank you.
