### ISSUE TITLE
move “X” button to right side

### ISSUE THREAD

**Issue by LYK-love** [alainm23/planify#840]
No offence, but i think the location of the close button is weird, which should be at the right side just as other applications like browser.

**Comment by Neyl-123** [comment]
Totally agree, what is this design? At least give a option to move it to the right

**Comment by PotatoNut** [comment]
@LYK-love  Go to preferences -> Appearance -> Change the style of from Elementary to Close only Button right.

**Comment by Neyl-123** [comment]
Sorry for the harsh tone, I don't know why I was so upset yesterday.You are providing this open source application for free, I should be more grateful.
But at least for me the Button layout only shows 'elementary' without being able to click on it and select something else. I'm on Pop!_OS 21.10.

**Comment by PotatoNut** [comment]
@Neyl-123 I'm on Planner version 2.7 and there is an option for me. Be sure that you run the latest version.

**Comment by Neyl-123** [comment]
I have version 2.7 installed.
When I go to Appearance it looks like this:
![grafik](https://user-images.githubusercontent.com/97339070/150517514-5f36622c-3521-42c2-95be-3fd098534325.png)

**Comment by Neyl-123** [comment]
@PotatoNut Thx, I figured it out - sorry for the trouble
