### ISSUE TITLE
Update to Planner 3.02 (flathub) signs out of todoist.

### ISSUE THREAD

**Issue by kollienne** [alainm23/planify#846]
After [yesterday's flathub update](https://github.com/flathub/com.github.alainm23.planner/commit/820a6f6eed331b9330a95cf420ac203089b50f79), when opening planner all tasks are gone and the option to sign in again to todoist is presented.

I'm not 100% certain, but I'm pretty sure I had some non-todoist projects that are gone now.

**Comment by Leon0402** [comment]
Same here, all my data seems lost :/

**Comment by alainm23** [comment]
Planner 3 is not compatible with Planner 2, but you do use Planner with Todoist. just log back in and all your tasks will be back.
