### ISSUE TITLE
3.0.2 (flathub) uses a broken theme

### ISSUE THREAD

**Issue by kollienne** [alainm23/planify#847]
**Describe the bug**
After the [latest flathub update](https://github.com/flathub/com.github.alainm23.planner/commit/820a6f6eed331b9330a95cf420ac203089b50f79) to 3.0.2, planner has a broken gtk theme.

**Screenshots**
![Screenshot from 2022-02-11 10-30-35](https://user-images.githubusercontent.com/20397647/153500812-e6bd2d91-75d7-4b1c-8fd0-f07b77b58bb5.png)

**Desktop (please complete the following information):**
 - Fedora 35, Gnome 41.3

**Comment by alainm23** [comment]
Update to 3.0.3 pls

**Comment by therealrobster** [comment]
How do we install and run the latest 3.x branch?  I'm trying to test CALDAV but can't find a place to do this.  I noted the zip file in the above link you provide and downloaded that, but not sure on build process.

**Comment by kollienne** [comment]
Updating to 3.05 fixes this.

**Comment by therealrobster** [comment]
Thank you for this info, but HOW do we update?  Flatpak install only installs an older version.  Thanks again
