### ISSUE TITLE
I've read in the bug reports that there is a caldav extension.  Where can I find this?

### ISSUE THREAD

**Issue by therealrobster** [alainm23/planify#848]
Hi there,

I've read in the bug reports that there is a caldav extension.  Where can I find this?

I have my own server with a url I need to point to but can't find anything in the interface.  I might be going mad, or maybe it's hidden away?

I'm on Debian 11 with the latest flatpak planner. 

Thank you

**Comment by alainm23** [comment]
CalDAV will be available in Planner 3 beta2

**Comment by therealrobster** [comment]
Thank you so much Alain
