### ISSUE TITLE
[Critical] All notes/tasks/data lost after update - DB has been overwritten no-way to recover

### ISSUE THREAD

**Issue by arfanliaqat** [alainm23/planify#849]
**Describe the bug**
I'm a Debian 10 (Buster) user. My version of Planner got updated today and all of notes taken in last year or so are gone. After going through other similar issues i figured out the db location (which is not documented in the readme itself) after i opened it using DB Browser for SQLite there was nothing in it.
**To Reproduce**
1. Have current - 1 version (1 version lower then current version, which version exactly I dont know because planner wont let me see its version as described below)
2. Update planner to current version
3. Planner will ask will you use it locally or using todoist? Choose locally
3. Say good bye to all your data

**Expected behavior**
Still have my data? Or atleast a warning that if you update you will have to let go of your data?

**Screenshots**
![image](https://user-images.githubusercontent.com/11976300/153542001-36b927ba-e8db-4d72-a5dd-419ba35d5cbb.png)

**Desktop (please complete the following information):**
 - Debian 10 (Buster) Gnome
 - Version 10
There is no way for me check which version of planner i'm running in this updated version. In settings there is no information regarding which version i've???
![image](https://user-images.githubusercontent.com/11976300/153544016-4f6c3c87-0b22-4e10-ad5a-b4962d2743d8.png)

**Additional context**
After going through other issues here on Github, I noticed many other users are reporting similar issues though with other circumstances
- #764
- #769
- #691
- #629
- #592
- #432

It is disastrous that this project keep causing people to lose data due to bugs/bad design. I agree that this is free-project and no-body is paying for its maintenance and we'd respect the developer who put their time/effort into this, but is that a good excuse to justify complete data losses to uninformed random users? Right now this project is a net disservice to its users.  I'm going to uninstall planner for good today.

If this project is gonna stay afloat I propose that it should
- [ ]  clearly indicate to its users that its not reliable yet. It can be done either declaring it Alpha/Beta. Also put a warning that project is yet unstable/unreliable and is prone to losing data.
- [ ]  keep a rotating backup for its database like WhatsApp?
- [ ] Allow user to backup their data manually?

At-last to developer I regret any hurt this issue may cause, but I've purposefully made it stark to prevent other users from having a similar incident.

**Comment by Leon0402** [comment]
There is also an already closed issure for this release: https://github.com/alainm23/planner/issues/846

I agree though. We all appreciate you working on this project and we're absolutely not in the position to demand anything! But I kindly ask to think about the update policy. 
Introducing a new version with known data loss and automatically rolling it out via flatpak without any warning really is bad. 

I agree with the solutions proposed above in general: 
- Please put some warnings in the release notes about data loss (and what can be done about it) 
- Please use alpha / beta / unstable release or insider build, you could release this as a separate flatpak package to get early feedback before releasing this to everyone 
- Please provide some (automatic?) backup functionality that doesn't rely on todoist, but it just local

In particular I want to propose some specific solution for such an upgrade, where you definitely know that everything breaks: 
- Please make it a separate package on flathub ... for instance planner3.0, so there is no automatic update 
- Please don't completly delete / overwire the old database (as far as I can tell). Just create a new sql lite database, so the old one is still there. Or copy the old database beforehand. Then one could at least manually migrate data or write some own script for this 

Nevertheless, thank you very much for your effort! Planner 3 looks very nice

**Comment by arfanliaqat** [comment]
That is exactly what happened to me that update was automatic I didn't even initiate it. Since it was available so my OS updated to it. This not strange as i want/expect my system to move to newer releases when possible. Even if it was not automatic I may have done it myself within few days. Nonetheless i'm trying to come to terms with loss. 

One thing i gained from this is that I've moved to [Obsidian](https://obsidian.md), I invite all of you to give it a try as well.

**Comment by alainm23** [comment]
Thank you for reporting it, I am sorry if you had this problem, I am sending the 3.0.5 update that allows you to export a backup before starting Planner 3. 

Again, I am very sorry 🙏️.

**Comment by arfanliaqat** [comment]
Thank you @alainm23 much appreciated, hopefully it will beneficial to many.

**Comment by Jarodiv** [comment]
Is there any way to re-import the exported tasks after the update? Right now the only option I see is to manually recreate all of them, which sounds a little bad inconvenient if you have a large number of tasks.

**Comment by MichelaML** [comment]
> That is exactly what happened to me that update was automatic I didn't even initiate it. Since it was available so my OS updated to it. This not strange as i want/expect my system to move to newer releases when possible. Even if it was not automatic I may have done it myself within few days. Nonetheless i'm trying to come to terms with loss.
> 
> One thing i gained from this is that I've moved to [Obsidian](https://obsidian.md), I invite all of you to give it a try as well.

Thank Arfanliaqat! 
 I suffered from the same fate and am not pleased. This is outrageous. I will also de-install the tool and consider Obsidian. 
Cheers.
