### ISSUE TITLE
Please don't push unfinished products to main branch

### ISSUE THREAD

**Issue by really-just-a-tech** [alainm23/planify#852]
First of all, I wanted to say thank you for developing this great app for free! I and many others really appreciate the work you've put in this project and I'm glad to pay a weekly donation for that on [Liberapay](https://liberapay.com/Alain) :)

But today I was a bit frustrated with the sloppy release of Planner 3.0.

First of all, all my data was gone without any warning. I know there's a warning now in 3.0.5, but the damage was already done. My last backup was from more than a week ago, so I lost quite a bit of (important) data. Second, I noticed a lot of features from Planner 2 are missing, like subprojects, subtasks, sorting, etc.. I assume the idea is to reimplement these in the future, but for now the features are a bit limited in my opinion.

My point is, Planner 3.0 is clearly not a finished product and so it's unacceptable that this got pushed on the main branch on Flathub, which caused automatic updates for many users. Please, in the future, when you think the new version isn't 100% complete and thoroughly tested, release it to an alpha or beta channel, so only users who choose to be testers get these experimental versions.

For now I have decided to downgrade to Planner 2.7 until most of it's features are introduced in Planner 3.

**Comment by hyuri** [comment]
+1 Lost all my projects, tasks... everything too.

**Comment by DekosAnjo** [comment]
I lost all my data. now i have to re enter every thing i need to do manually... but I don't remember all the tasks =( I hope don't have angry customers because of this. and a bunch of feature simple disappeared, things that i really use like sub tasks and add multiples tasks.

**Comment by singartence** [comment]
Much like OP, I'd like to thank Alain for working on the project. I appreciate your hard work and have been using Planner for a while now.

That said, like the resto of the folks here, I lost all my data. However, since I regularly backup, it's not that big a deal. The only problem is: the new version has no import option. If only that could be fixed, those of us who used the export feature to create *planner backups could get back. As of now, I have no way to restore my backup.

**Comment by andythedude** [comment]
I feel like a development branch where he was rebuilding this from the ground up was accidentally merged into production.
TONS of stuff is missing.

**Comment by singartence** [comment]
Indeed. I'm trying to rollback to version 2.7, but I'm not versed enough on this stuff unfortunately.

**Comment by andythedude** [comment]
> Indeed. I'm trying to rollback to version 2.7, but I'm not versed enough on this stuff unfortunately.

Unless you're running on eOS and already have all the needed dependencies, probably not worth the effort.
getting eOS apps to install on other distros like LTS ubuntu is a bit of a nightmare as all of the stuff in apt is not up to date with it. And you need to set up granite manually, which is a nightmare in itself.

If you have all the build dependencies, 
you're going to need to clone, change the commit to before 3.0 was released, and then compile from source.

**Comment by really-just-a-tech** [comment]
> Indeed. I'm trying to rollback to version 2.7, but I'm not versed enough on this stuff unfortunately.

https://docs.flatpak.org/en/latest/tips-and-tricks.html#downgrading

**Comment by singartence** [comment]
Thanks for the help, guys. I did follow those instructions, Just a Tech, but now planner just doesn't start.

**Comment by alainm23** [comment]
Try with: `flatpak run com.github.alainm23.planner -r`

**Comment by singartence** [comment]
Ah, that did the trick. Thank you, Alain! For helping and for your hard work. The new version looks really good, btw! I'll make the switch as soon as I can import my projects and tasks.

**Comment by arfanliaqat** [comment]
My sympathies with you @really-just-a-tech, i had similar issue yesterday #849. May I invite you to try [Obsidian](https://obsidian.md)?

**Comment by makew0rld** [comment]
I ran this to go back to 2.7:

```
flatpak update --commit=3e5e1ec487007f434f37ffa3c4b3036e6777475976492b48868397117ac0ef7a com.github.alainm23.planner
```

And then
```
flatpak mask com.github.alainm23.planner
```
to prevent going back to the latest version when I update my other Flatpaks.

**Comment by rotalumi** [comment]
Like others above, I lost all of my data with this upgrade. Also like others above, I appreciate the effort of developers to create what might one day be a first-class app.

Only days ago, I posted on another site a review of to-do apps for Linux and ranked Planner second among "great apps focused on task management":

https://forum.endeavouros.com/t/favourite-lesser-known-programs/7459/564

Unfortunately, with such a catastrophic upgrade, which resulted in the loss of my data, I can no longer recommend Planner to others. However, I will continue to use Planner _with test data_ and I will follow Planner's development with interest. Planner still has the potential to be a first-class app.
