### ISSUE TITLE
Lots of interface functions are missing, can't get back to main screen once i selected planner or todoist projects

### ISSUE THREAD

**Issue by andythedude** [alainm23/planify#854]
**Describe the bug**
When i load up planner it flashes the main screen really quickly again, but it loads right into my local projects and i can't find any way to get back or sync with a todoist project.

a lot of old functions like export, log out of todoist, etc are all gone. 
all the settings are gone except for "appearance",

i can't get back to the main menu

to replicate. start up on a brand new instance and select "start locally" or "todoist" and sync.

where i end up
![image](https://user-images.githubusercontent.com/45073230/153652272-b770bc99-6d33-4af9-8a32-52763376d935.png)

no settings or any indication of how to get back 
![image](https://user-images.githubusercontent.com/45073230/153652361-a71a4159-e565-494e-bf16-d37dcfbcd866.png)

**Comment by andythedude** [comment]
the only way to get back was to remove it and delete data using
`flatpak remove planner --delete-data`

should i be cautious about hooking this clearly unfinished software up to todoist? is there any chance it will delete all of my todoist data?

**Comment by andythedude** [comment]
Did this with a test account, i cannot even sign out. i think there's something seriously wrong, did a development branch get pushed to production?

**Comment by alainm23** [comment]
Try with `flatpak com.github.alainm23.planner -r`

**Comment by andythedude** [comment]
> Try with `flatpak com.github.alainm23.planner -r`

flatpak `run` com.github.alainm23.planner -r

that worked
