### ISSUE TITLE
Planner 3 didn't backup my Database as json.

### ISSUE THREAD

**Issue by PotatoNut** [alainm23/planify#856]
**Describe the bug**
The newer version Planner 3 was installed, upon using it the app suggested to export my old Database as Json, after I typed name for the backup I expected it to work, but no output and file appear. I think the database is forever lost. That suck.  Do you have suggestion for file undelete on Linux? With testdisk I can't see option to undelete on the ext4 partitions.

**Comment by tr1p0p** [comment]
Yeah same.

Such a same doing a update like this, really.

**Comment by antimech** [comment]
This app never suggested me to convert the database from `*.db` to `*.json`.
Still can't open my tasks since v2.7 update.
Does it have something to do with my non default saving folder?

**Comment by thomsch98** [comment]
Same here. That's a bummer. I had quite a few (~30) task still inside with notes and remarks.

**Comment by malbion** [comment]
Similar issue, v3 on ubuntu wiped all my saved tasks and projects.

**Comment by machadowisck** [comment]
I also lost years of tasks and projects here... plus, the new UI is really, REALLY awful

**Comment by BenHerbst** [comment]
Version 3 seems to be realy, realy unfinished. Please turn the flatpak back to the 2.7 version until 3 is stable.

**Comment by Ahmed-E-86** [comment]
I have the same issue, and I thought that it will be fixed, but here we are.

At least give us an option to stay with the older version.

**Comment by Ahmed-E-86** [comment]
> Version 3 seems to be realy, realy unfinished. Please turn the flatpak back to the 2.7 version until 3 is stable.

To rollback to version 2.7, copy and paste these commands in the terminal:

```
sudo flatpak update --commit=3e5e1ec487007f434f37ffa3c4b3036e6777475976492b48868397117ac0ef7a com.github.alainm23.planner
sudo flatpak mask com.github.alainm23.planner
```

**Comment by BenHerbst** [comment]
> > Version 3 seems to be realy, realy unfinished. Please turn the flatpak back to the 2.7 version until 3 is stable.
> 
> To rollback to version 2.7, copy and paste these commands in the terminal:
> 
> ```
> sudo flatpak update --commit=3e5e1ec487007f434f37ffa3c4b3036e6777475976492b48868397117ac0ef7a com.github.alainm23.planner
> sudo flatpak mask com.github.alainm23.planner
> ```
Will I lose my 3.x data? And also 3.0.6 got  released. When the flatpak updates it now supports sub tasks and  more,  so it got a lot more stable some hours ago...

**Comment by danabyrd** [comment]
Same issue. All data from v2.7 is gone. 3.06 doesn't allow any project or tasks to be added. v3.06 is woefully incomplete and totally unusable. (installed via snap, ubuntu 21.10, aarch64)

**Comment by BenHerbst** [comment]
Non go: Planner deleted some changes I did today. Now I don't know what I wanted to do.

**Comment by vexedmoth** [comment]
> > > Version 3 seems to be realy, realy unfinished. Please turn the flatpak back to the 2.7 version until 3 is stable.
> > 
> > 
> > To rollback to version 2.7, copy and paste these commands in the terminal:
> > ```
> > sudo flatpak update --commit=3e5e1ec487007f434f37ffa3c4b3036e6777475976492b48868397117ac0ef7a com.github.alainm23.planner
> > sudo flatpak mask com.github.alainm23.planner
> > ```
> 
> Will I lose my 3.x data? And also 3.0.6 got released. When the flatpak updates it now supports sub tasks and more, so it got a lot more stable some hours ago...

You saved my life

**Comment by antimech** [comment]
What I discovered is I have to rollback as @Ahmed-E-86 said. Find the backup button in the old UI, save it as a `*.planner` a.k.a. `json` file. Update Planner and then find the import button in the new UI. It works but it messed up my subtasks, inbox became empty, and labels are gone, so I'm stuck forever on v2.7 with thousands of carefully build tasks. It's time to find another software and start from 0.

**Comment by alainm23** [comment]
Planner has been discontinued and was replaced by Planify, I'll close this issue for the same reason.
