### ISSUE TITLE
Not able to add task to sections in a project

### ISSUE THREAD

**Issue by GandhiParth** [alainm23/planify#858]
After the update, lost all the data and was recreating it but for the sections created in projects I am unable to add tasks. It says to click on the + icon to add task to that section but while doing that it adds tasks in the main project and not in the section.

**Desktop (please complete the following information):**
 - OS or DE: POP OS
 - Version 21.10
**Additional context**
![Screenshot from 2022-02-14 10-12-33](https://user-images.githubusercontent.com/87466488/153801270-2f0265a0-4f8f-4b0d-a328-f7c124d6467b.png)

**Comment by CottageCabbage** [comment]
Kinda late response, but you have to hold and drag the task to inside the grey block. It'll get a blue outline, and you can release it then.
