### ISSUE TITLE
Feature request: Integration with Nextcloud/Tasks

### ISSUE THREAD

**Issue by nztvar** [alainm23/planify#859]
**Is your feature request related to a problem? Please describe.**
Planner does not pick up calendar tasks from synchronised calendars in Fedora (may be a GNOME configuration failure on my part,) nor include calDAV configuration for remote calendars.

**Describe the solution you'd like**
A simple configurator to add remote calDAV calendar tasks, such as Nextcloud.

**Describe alternatives you've considered**

**Additional context**
[Nextcloud/Tasks](https://github.com/nextcloud/tasks#apps-which-sync-with-nextcloud-tasks-using-caldav) on Github, and on [apps.Nextcloud.com](https://apps.nextcloud.com/apps/tasks)

**Comment by HansCronau** [comment]
Possible duplicate of #555.

**Comment by nztvar** [comment]
Yes, dup.
