### ISSUE TITLE
Cant run latest master

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#86]
After compiling from master I cant run the app

ERROR:/home/carlos/planner/src/Services/Database.vala:719:services_database_get_all_projects_no_area: assertion failed: (res == Sqlite.OK)
Aborted

**Comment by alainm23** [comment]
Try to delete the database file /home/alain/.local/share/com.github.alainm23.planner

**Comment by Hedronmx** [comment]
Got it working! Thank you

**Comment by alainm23** [comment]
Dear Sir. Now Planner is a software in beta and by the moment it is changed everytime.
