### ISSUE TITLE
Subtasks don't work in 3 v. 

### ISSUE THREAD

**Issue by gravit22** [alainm23/planify#862]
I don't think that needs additional explanation, when I upgraded to v 3 all the subtasks are not synchronizing with my PC version of Planer 3.

**Comment by therealrobster** [comment]
Where do you get V3 to test?  I'm on flathub, it says 3.x is out, but only 2.x is available there.  It's a mystery to me.  If you can help it'd be appreciated.  Thank you

**Comment by gravit22** [comment]
To be hones, I do not remember exactly, but I believe I downloaded the pack here: [https://flathub.org/apps/details/com.github.alainm23.planner](url)
And then I installed it with app manager.
After that I received V2, but recently, I was asked to update to V3 in app itself, and then I clicked to update, and that is it.

**Comment by therealrobster** [comment]
Thanks for your reply.  I just gave it another go.  Installed and it loaded 2.x.  Can't find any update options.
Ran this `$ flatpak update com.github.alainm23.planner`

and got:

`Looking for updates…
Nothing to do.`

Oh well, I guess I just... don't know!  :-)  One day hopefully it releases as default.  Thanks again

**Comment by gravit22** [comment]
I have no idea, I didn't do anything special. I don't know how to reproduce that request for update.
Thank you for your attention anyway.

**Comment by gravit22** [comment]
Or I actually updated it via software center, after installing gnome support for flatpacks. 
`sudo apt install gnome-software-plugin-flatpak`

**Comment by therealrobster** [comment]
Interesting, thanks again.  I then got this:

`
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gnome-software-plugin-flatpak is already the newest version (3.38.1-1).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
`
However, my planner is on : 

`Planner                                   com.github.alainm23.planner                           2.7             stable       system`


EDIT:  I see you said your software centre.  Let me see what I can dig up with that...  brb

**Comment by gravit22** [comment]
Yeah, I belive I used this instruction [this](https://itsfoss.com/flatpak-guide/) when I was installing flatpacks, and option to install with software center, and then software center may rise that request to update the app.

**Comment by gravit22** [comment]
Why is it closed?

**Comment by alainm23** [comment]
Available in v3.0.6

**Comment by therealrobster** [comment]
> Available in v3.0.6

Sorry to interrupt, but where can I get the latest versions?  The flathub  comments mention 3.x but the flathub only has 2.x.  I can't get access to 3.x.  Thank you

**Comment by gravit22** [comment]
> > Available in v3.0.6
> 
> Sorry to interrupt, but where can I get the latest versions? The flathub comments mention 3.x but the flathub only has 2.x. I can't get access to 3.x. Thank you

`flatpak update`
