### ISSUE TITLE
How to sync in the new version?

### ISSUE THREAD

**Issue by BenHerbst** [alainm23/planify#867]
I have the 3.x version and I can't see how to sync with Todoist or email? I need that for backup. Is there an other way to backup only planner and not the whole system via deja dup etc.? Can I just copy the /home/.../.var/app/com.github.alainm23.planner/ folder?

**Comment by therealrobster** [comment]
There will soon be caldav sync which will be amazing.  Means you'll be able to sync to heaps of other apps as well on your phone / tablet / etc.  https://github.com/alainm23/planner/issues/872  has the question answered recently.
