### ISSUE TITLE
Closing task preview overwrites all tasks

### ISSUE THREAD

**Issue by saugatkhadka** [alainm23/planify#87]
**Describe the bug**

Closing the task preview/edit on a new project tasks updates all the other tasks in that project. Editing the project after closing the task preview/edit also results in overwrite of all the task in that project. And deleting one task after this bug, deletes all the tasks in that project

**To Reproduce**
### Overwrite on close
1. Click on the New Project button and add a new project.
2. On the task window for that project, create a few new tasks.
3. Click on one of the task (any tasks) and close it (without editing anything).
4. Error: All tasks are overwritten to the one you just closed.

### Overwrite on edit
1. Click on any of the task in the project and edit it.
2. Error: All tasks are overwritten to the one you just edited.

### All tasks deleted on delete
1. Click on any tasks of the project and delete it.
2. All tasks in that project is also deleted.

**Expected behavior**
On closing only the updated or changed task should be updated or changed
On deleting a single task on a project, only the selected task must be deleted 

**Screenshots**
*Creating a new project and some tasks*
![image](https://user-images.githubusercontent.com/19860535/67921468-ea58c900-fbcf-11e9-828c-d66dc21962be.png)

*Opening a task for edit*
![image](https://user-images.githubusercontent.com/19860535/67921486-052b3d80-fbd0-11e9-8b00-6466a1b9247f.png)

*Closing the task* Generates the mentioned error
![image](https://user-images.githubusercontent.com/19860535/67921507-1aa06780-fbd0-11e9-9cb8-06b53d890c51.png)

*On editing the fourth task*
![image](https://user-images.githubusercontent.com/19860535/67921540-30ae2800-fbd0-11e9-9619-1e2a574c1fc8.png)

*On deleting any of the tasks*
![image](https://user-images.githubusercontent.com/19860535/67921561-43c0f800-fbd0-11e9-9acc-1fa3322646da.png)

**Desktop (please complete the following information):**
 - OS or DE: pantheon
 - Version OS 5.0 Juno

**Additional context**
Hope this helps :)

**Comment by alainm23** [comment]
Thank you very much for your comments. I am currently working on a new version of Planner and the version you are using is already archived 😅️.

If you want to try this new version you can compile the project
https://github.com/alainm23/planner

![image](https://user-images.githubusercontent.com/33765137/67922374-98388900-fb78-11e9-829d-328b18227ea4.png)
