### ISSUE TITLE
Where did the reminders go in the new version interface?

### ISSUE THREAD

**Issue by jstormshak** [alainm23/planify#871]
**Describe the bug**
After the upgrade to the new version, I can no longer locate in the interface the ability to set reminders for any of my project tasks.  I truly rely on that feature for the tool.  Please advise if that is indeed no longer available or if there's a way to find them.

**Expected behavior**
Expected that on all new tasks, to be able to click on a add reminders but no longer can I locate this on the new interface?  What happened?  

**Screenshots**

**Desktop (please complete the following information):**
OS: Rocky Linux 8.5
Flatpack Planner ver. 3

**Additional context**
If these are no longer available, is there a way to obtain or move back to the older version?  As a user, I truly need that functionality in this tool which has meet my needs for a long time of use.  Thanks!

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/155245727-d4cba17a-2097-4b99-9b81-881a5a004510.png)
Available in v3.0.6

**Comment by jstormshak** [comment]
Thank you for the quick response.  I'm new to GIThub and looked and see a 3.0.5 release.  Do you have a timeline or best ETA when that 3.0.6 would be ready for general public/download?

**Comment by alainm23** [comment]
Today

**Comment by jstormshak** [comment]
I apologize for this silly question but how do I go about getting the 3.0.6 from the following file as the only option in it says "stable" and when I tried to modify it for 3.0.6 it fails.  In other words, will there be a time where the 3.0.6 is made to the flathub and its general audience?   This is what file I was hoping to update to get this new release install and back to use.  Please advise as your time permits and thank you so far on the help!  It appreciated.

com.github.alainm23.planner.flatpakref
[Flatpak Ref]
Name=com.github.alainm23.planner
Branch=3.0.6
Title=com.github.alainm23.planner from flathub
IsRuntime=false
Url=https://dl.flathub.org/repo/
