### ISSUE TITLE
 The type name `Granite.HyperTextView' could not be found

### ISSUE THREAD

**Issue by rayklaus** [alainm23/planify#873]
1.the version planner-3.0.6  (note:he version plannner 2.7 is ok)
2.meson build 
3.cd build && ninja
valac -C --debug --debug --pkg libhandy-1 --pkg webkit2gtk-4.0 --pkg json-glib-1.0 --pkg sqlite3 --pkg gtk+-3.0 --pkg granite --pkg gee-0.8 --pkg gobject-2.0 --pkg glib-2.0 --color=always --directory com.github.alainm23.planner@exe --basedir ../ --gresources=../data/com.github.alainm23.planner.gresource.xml ../src/Util.vala ../src/Application.vala ../src/MainWindow.vala ../src/Layouts/Sidebar.vala ../src/Layouts/FilterPaneRow.vala ../src/Layouts/HeaderItem.vala ../src/Layouts/LabelRow.vala ../src/Layouts/ItemRow.vala ../src/Layouts/ProjectRow.vala ../src/Layouts/ViewHeader.vala ../src/Layouts/SectionRow.vala ../src/Layouts/LabelChild.vala ../src/Layouts/SectionChild.vala ../src/Widgets/Entry.vala ../src/Widgets/DynamicIcon.vala ../src/Widgets/TodoistSync.vala ../src/Widgets/ProjectProgress.vala ../src/Widgets/EditableLabel.vala ../src/Widgets/TopHeaderProject.vala ../src/Widgets/ColorPopover.vala ../src/Widgets/MagicButton.vala ../src/Widgets/HyperTextView.vala ../src/Widgets/LoadingButton.vala ../src/Widgets/ProjectButton.vala ../src/Widgets/PinButton.vala ../src/Widgets/IconColorProject.vala ../src/Widgets/ItemSummary.vala ../src/Widgets/ScheduleButton.vala ../src/Widgets/PriorityButton.vala ../src/Widgets/LabelButton.vala ../src/Widgets/ItemLabels.vala ../src/Widgets/ItemLabelChild.vala ../src/Widgets/Placeholder.vala ../src/Widgets/SubItems.vala ../src/Widgets/ReminderButton.vala ../src/Widgets/Calendar/Calendar.vala ../src/Widgets/Calendar/CalendarDay.vala ../src/Widgets/Calendar/CalendarHeader.vala ../src/Widgets/Calendar/CalendarView.vala ../src/Widgets/Calendar/CalendarWeek.vala ../src/Views/Welcome.vala ../src/Views/Project.vala ../src/Views/List.vala ../src/Views/Today.vala ../src/Views/Date.vala ../src/Views/Pinboard.vala ../src/Views/Scheduled/Scheduled.vala ../src/Views/Scheduled/ScheduledHeader.vala ../src/Views/Scheduled/ScheduledDay.vala ../src/Views/Label.vala ../src/Views/Board.vala ../src/Dialogs/TodoistOAuth.vala ../src/Dialogs/Project.vala ../src/Dialogs/Label.vala ../src/Dialogs/MessageDialog.vala ../src/Dialogs/QuickFind/QuickFind.vala ../src/Dialogs/QuickFind/QuickFindItem.vala ../src/Dialogs/QuickFind/Synapse.vala ../src/Dialogs/ReminderPicker/ReminderPicker.vala ../src/Dialogs/ReminderPicker/ReminderRow.vala ../src/Dialogs/Settings/Settings.vala ../src/Dialogs/Settings/SettingsHeader.vala ../src/Dialogs/Settings/SettingsContent.vala ../src/Dialogs/Settings/SettingsItem.vala ../src/Dialogs/ProjectPicker/ProjectPicker.vala ../src/Dialogs/ProjectPicker/ProjectRow.vala ../src/Dialogs/ProjectPicker/SectionRow.vala ../src/Dialogs/DateTimePicker/DateTimePicker.vala ../src/Dialogs/DateTimePicker/TimePicker.vala ../src/Dialogs/LabelPicker/LabelPicker.vala ../src/Dialogs/LabelPicker/LabelRow.vala ../src/Dialogs/ContextMenu/Menu.vala ../src/Dialogs/ContextMenu/MenuItem.vala ../src/Dialogs/ContextMenu/MenuItemSelector.vala ../src/Dialogs/ContextMenu/MenuSeparator.vala ../src/Dialogs/ContextMenu/MenuCalendarPicker.vala ../src/Dialogs/ContextMenu/MenuSwitch.vala ../src/Dialogs/Shortcuts/Shortcuts.vala ../src/Dialogs/Shortcuts/ShortcutLabel.vala ../src/Services/EventBus.vala ../src/Services/Database.vala ../src/Services/Todoist.vala ../src/Services/ActionManager.vala ../src/Services/Badge.vala ../src/Services/Notification.vala ../src/Objects/v2.vala ../src/Objects/BaseObject.vala ../src/Objects/Project.vala ../src/Objects/Label.vala ../src/Objects/Section.vala ../src/Objects/Item.vala ../src/Objects/Color.vala ../src/Objects/DueDate.vala ../src/Objects/ItemLabel.vala ../src/Objects/Today.vala ../src/Objects/Pinboard.vala ../src/Objects/Scheduled.vala ../src/Objects/Reminder.vala config.vala
../src/Widgets/HyperTextView.vala:1.38-1.58: error: The type name `Granite.HyperTextView' could not be found
public class Widgets.HyperTextView : Granite.HyperTextView {
                                     ^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.

**Comment by alainm23** [comment]
Install Granite > 6.0
https://github.com/elementary/granite

**Comment by Lyton505** [comment]
I installed granite 7 and still getting that error. Do I have to downgrade to an earlier version?

**Comment by Lyton505** [comment]
Resolved. I downgraded to an earlier version of granite. I wish it supported granite 7
