### ISSUE TITLE
Misplaced Menus

### ISSUE THREAD

**Issue by RushingAlien** [alainm23/planify#875]
**Describe the bug**
Menus don't appear where they are supposed to appear in Wayland.

**To Reproduce**
1. Open Planner as a Native Wayland client
2. Click on three dot icon
3. See that menus appear out of place

**Expected behavior**
For menus to appear where they are supposed to

**Screenshots**
![Cuplikan,layar dari 2022-02-27 18-12-48](https://user-images.githubusercontent.com/80886145/155880172-7aa4b89c-a148-44a9-85b9-29199d6939dd.png)
![Cuplikan,layar dari 2022-02-27 18-12-38](https://user-images.githubusercontent.com/80886145/155880179-5e437b61-0c3b-4cc7-997e-483b4bb974a2.png)
![Cuplikan,layar dari 2022-02-27 18-12-34](https://user-images.githubusercontent.com/80886145/155880184-43f12c7b-412e-4e5b-9018-609eab299cc7.png)
![Cuplikan,layar dari 2022-02-27 18-12-20](https://user-images.githubusercontent.com/80886145/155880186-9089b166-f775-433d-aee9-30f7f6e4bc7e.png)

**Desktop (please complete the following information):**
 - OS or DE: Arch, GNOME
 - Version : rolling, 41
 - Display Server : Wayland

**Comment by alainm23** [comment]
Fixed in the new version of Task Planner
