### ISSUE TITLE
Cannot load the old data after update to ver. 3

### ISSUE THREAD

**Issue by naivomah3** [alainm23/planify#879]
**Describe the bug**
I tried to update and I am now unable to find all of my old records. A few numbers appear in place of the old records after updating the app. I did the update through Ubuntu Software app. 

**Screenshots**
![Planner_001](https://user-images.githubusercontent.com/7285775/156119022-76b70cfe-42ab-439b-8785-613a9af5f81d.png)

**Desktop:**
 - OS or DE: Ubuntu Gnome 20.04.03 
 - Version: 
   + Planner old version: I don't know but I'm sure it has the old UI (perhaps ver. 2)
   + Planner new version: 3.0.6

**Comment by tschuette22** [comment]
I have the same issue, rolling back to version 2 resolves the problem. Unfortunately, the flatpak version available through snap on Ubuntu 20.04 has a bug that keeps it from masking the new update. This means that the update simply gets installed over and over again. Would love to see a compatibility layer that makes it possible to keep the data from version 2.x.

**Comment by Lorde-Soup** [comment]
you can use these commands to roll back to version 2
```
 sudo flatpak update --commit=3e5e1ec487007f434f37ffa3c4b3036e6777475976492b48868397117ac0ef7a com.github.alainm23.planne
sudo flatpak mask com.github.alainm23.planner`
```

**Comment by alainm23** [comment]
Planner has been discontinued and was replaced by Planify, I'll close this issue for the same reason.
