### ISSUE TITLE
Add Support for Attachments

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#88]
I would love the ability to upload files! Todoist has the option, but im not sure if its supported on the api.

**Comment by alainm23** [comment]
Yes, the upload of files is compatible with the [Todoist API](https://developer.todoist.com/sync/v8/?shell#upload-a-file) but the feature for the moment is not a priority but it is in my plans.

**Comment by Hedronmx** [comment]
Awesome! Glad to hear.

**Comment by 4jNsY6fCVqZv** [comment]
Nextcloud Deck has this feature: "Attach files and embed them in your markdown description"
I think it would be exciting to be able to add files to projects, sections or individual tasks. And not only with Todoist, but also for people who want to use Planner only locally.
How do others feel about it?

@alainm23 Should I create an extra issue for this "local attachment" idea?

**Comment by BeatLink** [comment]
- [ ] Add support for local attachments
- [ ] Add support for uploading attachments using Todoist API

**Comment by alainm23** [comment]
This functionality is not planned, and we are not quite sure how to do it either, I will reopen the issue when we see a correct way to do it.
