### ISSUE TITLE
Show Completed does not work after restarting planner

### ISSUE THREAD

**Issue by shakakibara12** [alainm23/planify#882]
**Describe the bug**
show completed resets back to off after closing & reopening planner.

**To Reproduce**
 1. Open planner & go to inbox or any project 
 2. toggle "Show completed"
 3. close & reopen planner
 4. "Show Completed" resets back to off.

**Expected behavior**
"Show Completed" should stay the way it is, it should not reset.

https://i.imgur.com/dzyzr3Q.mp4

**Desktop (please complete the following information):**
 - OS : **Arch linux** 
 - Wm: **sway 1.7 | wlroots 0.15.1**
Using planner from flatpak 
planner version - 3.0.6

**Comment by alainm23** [comment]
In Planner 3 the option to show completed tasks is disabled by default to avoid loading a huge list of completed tasks and improve performance, while Planner is open, the option to show completed tasks will be saved, but when restarting Planner, this setting will be lost .

**Comment by shakakibara12** [comment]
hello thanks for replying! . Can you tell me which line of code do i need to change in order to keep show completed checked? i don't mind loading a big list and also maybe it can help others who want this. Thanks!

**Comment by alainm23** [comment]
If you need this feature, I'll keep it in mind for the next release.

**Comment by shakakibara12** [comment]
> If you need this feature, I'll keep it in mind for the next release.

Thank you so much!
