### ISSUE TITLE
Has Planner 3 been officially released?

### ISSUE THREAD

**Issue by HansCronau** [alainm23/planify#887]
If "a user" goes to [Planner's homepage](https://planner-todo.web.app/), because they want to know about the latest version of Planner, they will find links to:
- [Planner's blog](https://planner-todo.web.app/blog/) 
- [Alain's Patreon](https://www.patreon.com/alainm23)
- [AppCenter](https://appcenter.elementary.io/com.github.alainm23.planner/)
- [Flathub](https://flathub.org/apps/details/com.github.alainm23.planner)

Out of these only the latter mentions the release of Planner 3. This could mean that the other sources are out of date. However, according to Github the [Planner 3 Milestone](https://github.com/alainm23/planner/milestone/3) has not yet been reached.

The user in question (me) was rather confused by all this. Issue #872 might be the result of a similar confusion.
Will there be an update on the official channels on the status of Planner 3?

**Comment by rohmishra** [comment]
The Planner 3 build on Flathub is completely broken and wipes your data without warning as of now so I would say no, Planner 3 seems to be in early development now. P.S. Im not sure either; I found my way here after loosing data and missing tasks.

**Comment by ChibiYuzu** [comment]
> The Planner 3 build on Flathub is completely broken and wipes your data without warning as of now so I would say no, Planner 3 seems to be in early development now. P.S. Im not sure either; I found my way here after loosing data and missing tasks.

I have the same problem. Except, it just appeared for me today. Strangely enough, I didn't get any update for Planner until very recently and I just noticed all this when I opened it today, to upgrade my projects. Not only does it wipe out all your data, but you can't import backups made with the previous version. And a lot of functions have disappeared (no repeat task, no more categories, no more copy in markdown or txt, no more sections, no more subtasks). Basically, I can't do much with it anymore. And I'm a bit at a loss. Fortunately, I've been using this with a markdown note-taking app, which I could synchornize with my other devices, so I haven't lost everything, but still. I'm kind of annoyed and would very much like reverse to the previous version until this one is ready. I'm not sure how, though, as my stores on Ubuntu 22.04 only offers this new Beta 2 of version 3.

**Comment by colios13** [comment]
Find it a bit strange to recommend and to put only a non stable release to download for people. 
All of my subtask as disappear from my projects today but strangely I can still see them in the scheduled part of the app.

**Comment by HansCronau** [comment]
Note that, while this GitHub issue has been closed, the reported inconsistency remains unsolved.
While other sources are at version 2, the [Flathub](https://flathub.org/apps/details/com.github.alainm23.planner) page still reads:

> Planner 3 is here...
