### ISSUE TITLE
When creating a task, have an option to add more.

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#89]
When I create a new task it would be useful to have an option to continue adding tasks, instead of pressing the add task button multiple times

**Comment by alainm23** [comment]
Thanks for the suggestion, We can add as an activatable option in the preferences.

**Comment by Hedronmx** [comment]
Sweet thank you!!

**Comment by alainm23** [comment]
Although thinking it well we could implement this feature in another way, for example by pressing the enter key to create task + (some key to be defined)

What key could it be, maybe Ctrl or Shift?

**Comment by Hedronmx** [comment]
I would prefer shift, since shift+enter is used for entering a new line

**Comment by alainm23** [comment]
Try it pls

**Comment by Hedronmx** [comment]
I cant when i try to build i get
`meson.build:26:0: ERROR:  Dependency "libecal-1.2" not found, tried pkgconfig and cmake`

Trying to install gets me
```
Note, selecting 'libecal-1.2-19' for regex 'libecal-1.2'
libecal-1.2-19 is already the newest version (3.28.5-0ubuntu0.18.04.2).
```

**Comment by alainm23** [comment]
You should install:

* libecal1.2-dev
* libedataserver1.2-dev
* libical-dev

**Comment by Hedronmx** [comment]
How do you add more? I tried enter, shift enter...

**Comment by alainm23** [comment]
with left shift?

**Comment by Hedronmx** [comment]
I tried both shifts actually

**Comment by alainm23** [comment]
What I do is: After writing the title of my task I have pressed the Shift key and then press the return key.

![planner shift](https://user-images.githubusercontent.com/33765137/68564977-238b0780-0420-11ea-84a5-0251b741f48e.gif)

**Comment by Hedronmx** [comment]
I am doing just that.... shift + enter

is there a way to check the version of the app?

Nevermind.... I found out why! It just works inside the inbox view.

**Comment by alainm23** [comment]
I just found the bug, I'll fix it for tomorrow.

**Comment by Hedronmx** [comment]
Awesome thanks!

**Comment by alainm23** [comment]
Try it one more time pls.

**Comment by Hedronmx** [comment]
Working perfectly!
