### ISSUE TITLE
Planner crashes after trying to add a task offline

### ISSUE THREAD

**Issue by heret0x0** [alainm23/planify#891]
**Describe the bug**
app crashes after trying to add a task  whilst offline

**To Reproduce**
Steps to reproduce the behaviour:

1. turn off internet connection
2. try to add a new task

**Notes:**
  * Todoist sync is enabled
  * the error is happening no mater if i turned the connection off before/after opening the app
  
**Expected behaviour**
adds the task offline locally and sync it whenever the system goes online 

**Desktop:**
 - Gnome 41.5 on Fedora 35
 - latest version of Planner flatpak

**Additional context**
com.github.alainm23.planner killed by a seg fault

**Comment by geoph9** [comment]
I noticed the same behavior. The only way to avoid it is by starting the app from the terminal (by running `flatpak run com.github.alainm23.planner`). For some reason, adding a task works that way.

**Comment by heret0x0** [comment]
well this didn't work for me smh

**Comment by geoph9** [comment]
What error are you getting on the terminal when the app crashes?

**Comment by heret0x0** [comment]
it didn't show anything 
just crashes 
![Screenshot from 2022-03-31 20-37-56](https://user-images.githubusercontent.com/99084207/161126404-059ef145-2bba-49a3-b9d4-43fb4ff7a335.png)

**Comment by geoph9** [comment]
Hmm, the above solution does not work when you want to create a new project for me either. This is the system error I get:

```
com.github.alainm23.planner killed by SIGSEGV
com.github.alainm23.planner
/app/bin/com.github.alainm23.planner
35509
...
fedora
1
...
...
myusername (1000)
CCpp/abrt-journal-core
/
5.16.14-200.fc35.x86_64
bwrap --args 45 com.github.alainm23.planner
0::/user.slice/user-1000.slice/user@1000.service/app.slice/app-flatpak-com.github.alainm23.planner-35499.scope
N 5
Fedora release 35 (Thirty Five)
...
...
x86_64
2.14.6
/var/spool/abrt/ccpp-2022-03-31-12:42:26.222436-35509
```

To be honest, I am not sure if the above are helpful and I don't know what each of these things mean, but this may be helpful to the dev (?).
