### ISSUE TITLE
Data loss on upgrading to 3.0.7

### ISSUE THREAD

**Issue by eightfiftytwo** [alainm23/planify#893]
**Describe the bug**
Upon upgrading to 3.0.7, everything in my inbox is gone, except for items assigned a tag or to a project. 

**To Reproduce**
1. Upgrade to 3.0.7
2. Check the inbox

**Expected behavior**
Data not disappearing after upgrades.

**Desktop (please complete the following information):**
 - Fedora 35, Gnome 41.5
 - 3.0.7 from Flathub

**Additional context**
First, I'd like to thank you for the time and effort you spent on developing this project. I've really enjoyed using it. However, this is the second time in two months an upgrade has completely wiped my data, the other time being upgrading to 3.0. Looking through the issues, it seems like this has happened quite a few times, [even on 2.7](https://github.com/alainm23/planner/issues/764). Although I have backups, most users don't backup regularly and will find these bugs dealbreakers. Planner exists to remember things for people, randomly forget everything on upgrades would defeat its purpose. Perhaps releases should be more thoroughly tested before being pushed? Thank you.

**Comment by Vortex-TH** [comment]
I am also affected by this. Am I seeing this correctly that the old data is still in database.db, but isn't used anymore? Where is the new data stored?

**Comment by alainm23** [comment]
Your tasks weren't lost, Planner just doesn't show them, update to 3.0.8 to fix the problem, thank you very much for your patience and reporting the bug.

**Comment by eightfiftytwo** [comment]
Sorry for responding so late. 3.0.8 is working fine. Thank you for your work!
