### ISSUE TITLE
Sections disappear when (tasks are) moved

### ISSUE THREAD

**Issue by Inshal240** [alainm23/planify#894]
**Describe the bug**
I created a project with multiple sections. I created tasks, then moved them to their section. When reordering the section, reordering tasks within it or moving tasks around, the sections would disappear as if it was being moved and not reappear. Restarting the application shows all the sections and tasks again correctly (before my attempt at moving them) but the problem persists. 

**To Reproduce**
Steps to reproduce the behavior (might take a few attempts):
1. Create a project
2. Create sections and multiple tasks within the objects
3. Set show completed tasks (doesn't seem to make a difference)
4. Click and drag a section or task within a section
6. Observe the section disappear

**Expected behavior**
The sections or tasks to not disappear and the reordering operation to go through.

**Screenshots**
https://user-images.githubusercontent.com/5384262/164950744-9181a007-5369-4f30-85e3-cf34ef183a1b.mp4

**Desktop:**
 - OS or DE: Ubuntu + GNOME
 - Version 22.04

**Comment by Mahrjose** [comment]
I'm having the same problem. While moving taks just disapear and I need to restart the program to make the application normal again. using ubuntu 22.04.
