### ISSUE TITLE
I see the new 3.0.8 is out (excellent!)  but I can't find CALDAV support anywhere.  Is it in this release?  

### ISSUE THREAD

**Issue by therealrobster** [alainm23/planify#896]
This is not a bug as such, I just can't find CALDAV settings anywhere yet.

I see the new 3.0.8 is out but I can't find CALDAV support anywhere.  Is it in this release?  

Flatpak planner V 3.0.8 on Debian Linux 11

**Comment by alainm23** [comment]
It is necessary to delete all the data of the application and start Planner with the CalDAV option.
![image](https://user-images.githubusercontent.com/33765137/165221857-24e58ef3-acd5-41a7-a517-65f201c0bd32.png)
![image](https://user-images.githubusercontent.com/33765137/165221940-d95d1e39-9359-472e-aa3b-fe310a91d4dd.png)
Set up your account from settings.
![image](https://user-images.githubusercontent.com/33765137/165222024-a200a87e-a0a5-4b41-8e01-607293036fa2.png)
I have the idea of ​​adding the functionality of being able to use the 3 backends (Local, Todoist, CalDAV) at the same time and move between them as if they were workspaces, for the moment this is the only way.

**Comment by therealrobster** [comment]
Thank you!  Just letting you know though that when i open the settings and click +.  I then get to add my server details, username and password etc.  But, if I click over to my password manager on my second window, to copy say the url or password etc, the settings screen for planner closes.  So I have to manually enter all my details.  The password is quite long and random and tricky, so I can copy / paste that, but the rest (url, username) I have to type.  It's not end of the world, but, when it loses focus, the caldav settings screen closes itself.  I hope that helps.

**Comment by alainm23** [comment]
Apparently it is a user experience issue, I will take it into account, thanks for commenting.

**Comment by therealrobster** [comment]
Thanks for all the effort, it's incredibly appreciated.
