### ISSUE TITLE
Editing one tasks in a project edits all of them

### ISSUE THREAD

**Issue by brejoc** [alainm23/planify#90]
**Describe the bug**

If you edit one tasks in a project, then all tasks are edited. This applies to labels, title, status or notes.

**To Reproduce**
1. Create a project
2. Add some tasks to the project
3. Edit one tasks and see all of them get changed.

**Expected behavior**
Changes should only apply to one task.

**Desktop (please complete the following information):**
 - OS or DE: elementary OS 5.0 Junao
 - Version: 1.2.4

**Comment by alainm23** [comment]
Thank you very much for your comments. I am currently working on a new version of Planner and the version you are using is already archived 😅️.

If you want to try this new version you can compile the project
https://github.com/alainm23/planner

![Screenshot from 2019-11-06 08 36 47](https://user-images.githubusercontent.com/26935602/68317807-9c7d0e80-0070-11ea-9abd-6ff276befff9.png)

**Comment by brejoc** [comment]
@alainm23 Are you sure you linked the right repo? When compiling this I get seemingly the same version with the same bug.

**Comment by alainm23** [comment]
This is rare, I am currently only working on a branch: https://github.com/alainm23/planner/tree/master

**Comment by brejoc** [comment]
I was tricked by an old process still running in the background. Executing the binary would then just bring the old app back. :laughing: 
So it's working now. Pretty nice! I really love that it's a Todoist client now!
