### ISSUE TITLE
Flathub version is on V3 (not stable, or complete)

### ISSUE THREAD

**Issue by andythedude** [alainm23/planify#902]
The stable version of planner is not available to non-elementaryOS users.

It's currently shipping out version 3+, which does NOT support Todoist anymore. (hopefully it will eventually)
This makes it difficult to use for non-elementary users to actually use this program if they used to use todoist integration in planner

did you just drop support for todoist alltogether or what's going on?

**Comment by matfantinel** [comment]
Not sure how things were when you opened this issue, but I installed it from Flathub today and the Todoist integration is working well.

**Comment by andythedude** [comment]
todoist integration seems to work fine but, there used to be an option to have todoist projects and planner projects co-exist next to eachother. if you dont choose todist at the outset, it will not ever show up again period unless you clear some arbitrary variable using flatpak cli.

there's definitely some work to be done still. the new interface is beautiful, but it irks me when a piece of software is released before it's finished and actually _removes_ existing features that were not neccessary to remove.
