### ISSUE TITLE
Syncing interval with CalDAV / manual syncing not possible

### ISSUE THREAD

**Issue by cryptono** [alainm23/planify#903]
Adding or changing tasks with a connected CalDAV account from Planner is being synced to the server immediately. Yet there is no option to force syncing with the server immediately to get remote changes. I am also wondering what the default/current syncing time is that is configured?

An option to perform manual syncing would be MUCH appreciated :+1:

**Comment by alainm23** [comment]
CalDAV support is under development for Planify, I will close this issue until the implementation is done. thank you.
