### ISSUE TITLE
KDE/Debian 11 "Could not save configuration"

### ISSUE THREAD

**Issue by JeffersonReal** [alainm23/planify#904]
**Describe the bug**
When trying to add a CalDAV account, I get the error "Could not save configuration".

**To Reproduce**
1. Go to settings by clicking cog icon in top of left sidebar.
2. Click on 'Synchronization > CalDAV' then '+' for a new account.
3. Complete the 4 fields (URL, user/pass and display name) and submit by clicking the search icon (presumably the logic here was find the server before saving credentials).
4. An error appears "Could not save configuration".

**Expected behavior**
Configuration is saved and I can now sync my CalDAV tasks.

**Screenshots**
Couldn't screenshot because when the UI loses focus, it auto-closes (and clears the form) and screenshotting in KDE was causing loss of focus.

**Desktop (please complete the following information):**
KDE Plasma on Debian 11 stable

**Additional context**
I know the credentials are not the issue, as I tested with wrong creds and got "could not fetch tasklists", so "Could not save configuration" indicates an error later in the logic.

A settings file was generated at `/home/jeff/.var/app/com.github.alainm23.planner/config/glib-2.0/settings/keyfile` which contains:

```
[com/github/alainm23/planner]
version='3.0.8'
window-size=(1187, 1006)
window-position=(56, 147)
backend-type='caldav'
run-in-background=true
projects-sort-by='Alphabetically'
```

As you can see, the last two lines indicate the saving of general settings is ok and the file exists, so it's not a permissions issue.

Also, a keyring file is generated here: `/home/jeff/.var/app/com.github.alainm23.planner/data/keyrings/default.keyring` but no account is listed in the Planner UI.

**Comment by C-512L** [comment]
Testing for #907 I tested KDE Desktop on Fedora 36 and found this behavior. Might be related.

**Comment by beangeli** [comment]
Same two errors ("could not save configuration", and the settings clearing and closing when clicking anywhere outside Planner) experienced on Xubuntu 20.04 and a fresh install of Xubuntu 22.04.

**Comment by sebastianschauenburg** [comment]
Both issues also appear here (Ubuntu 22.04.1 with Awesome WM, using Planner 3.0.8 from Flathub).
Additional information: In my case the 'settings' window disappears as soon as my mouse leave the settings window.

**Comment by sedding** [comment]
Same issue here - kubuntu 22.04 with flatpak planner.

**Comment by Cris70** [comment]
Same here, openSuse Tumbleweed with KDE, Planner 3.0.10 from Flathub.
BTW, I do not experience the problem with the disappearing settings window, only the "Could not save configuration" red box trying to save settings.

**Comment by lorenzoiuri** [comment]
Same for me. Fedora 38 KDE, flatpak.

**Comment by jonhteper** [comment]
I have the "Could not save configuration"  errror, on Manjaro with KDE Plasma, using Planner 3.0.10 from Flathub.

I found [this comment](https://github.com/alainm23/planify/issues/897#issuecomment-1246689540) , which makes sense to me, because all of us commenting in this issue use KDE.

**Comment by alainm23** [comment]
CalDAV support is under development for Planify, I will close this issue until the implementation is done. thank you.
