### ISSUE TITLE
Can't Type Chinese or Japanese

### ISSUE THREAD

**Issue by leongjs98** [alainm23/planify#906]
Typing or copy-pasting Chinese or Japanese characters (into title, description, projects, labels) just give square boxes. I am on Linux Mint, not sure if other OS have the same problem. I haven't tried other eastern languages like Korean.

It'd be great to have some of our tasks in these languages

**Comment by alainm23** [comment]
It appears to be a bug related to Gtk and is outside the scope of Planify, thank you.
