### ISSUE TITLE
CalDAV sync not working as expected

### ISSUE THREAD

**Issue by C-512L** [alainm23/planify#907]
Version: 3.0.8
Source: Flatpak (Flathub)

Steps to reproduce:
1. Launch app
2. Add new CalDAV account (in case is provider specific, its https://fruux.com/)

Expected behavior:

Account gets added and available tasks list are show on side menu

Found behavior: 

Account gets added but no tasks are listed on the side menu

![image](https://user-images.githubusercontent.com/29307937/168774173-fbd1b0df-ef82-44a3-bfcc-f1c9be0d9865.png)

Notes: Apparently although tasks are not listed, you can create new tasks lists but they will no be shown.

![image](https://user-images.githubusercontent.com/29307937/168774630-622f4d59-6417-4a26-a630-c37b42269846.png)

Following are the only relevant logs from running `G_MESSAGES_DEBUG=all flatpak run com.github.alainm23.planner` (They do not reappear when reopening the app with the account already added):

```
** (com.github.alainm23.planner:2): DEBUG: 10:56:18.616: CalDAV.vala:112: Adding task list 'b3297392896'

** (com.github.alainm23.planner:2): CRITICAL **: 10:56:18.618: CalDAV.vala:53: Unable to connect to “b3297392896”: Backend factory for source “c8c380b20c25f4b8a9a12d25a6dc169fcb475684” and extension “Task List” cannot be found.
** (com.github.alainm23.planner:2): DEBUG: 10:56:18.618: Sidebar.vala:296: Adding row 'b3297392896'

** (com.github.alainm23.planner:2): CRITICAL **: 10:56:18.619: TasklistRow.vala:162: Error creating view with query for source b3297392896[(contains? 'any' '')]: No client available for task list 'b3297392896'
```

**Comment by alainm23** [comment]
I just created a Fruux account and synced it with Planner, I can't report the same bug, try running Planner again.

**Comment by C-512L** [comment]
I tried to remove all flatpak's data (`~/.var/app/com.github.alainm23.planner`) multiple times without result. Also tried to remove all GNOME Online Accounts. I will try on a VM to see if is distro-specific (which is uncommon for flatpak I suppose).

I don't know if I am doing something wrong here, but here is how I'm adding it:

![image](https://user-images.githubusercontent.com/29307937/168808068-6c274c12-fc28-46fd-8fd9-d53f1042dec2.png)

**Comment by alainm23** [comment]
Try:
Server URL: https://fruux.com/

**Comment by C-512L** [comment]
> Try: Server URL: https://fruux.com/

I tried with the same results.

Something good is that I was able to reproduce the issue on a fresh and updated install of Pop!_OS 22.04.

Side note: I forgot to mention in the initial issue the OS/DE which I made it (Fedora Workstation 36, GNOME)

**Comment by ghost** [comment]
> > Try: Server URL: https://fruux.com/
> 
> I tried with the same results.
> 
> Something good is that I was able to reproduce the issue on a fresh and updated install of Pop!_OS 22.04.
> 
> Side note: I forgot to mention in the initial issue the OS/DE which I made it (Fedora Workstation 36, GNOME)

Hey,

Just wanted to ask if you found a solution to your problem? I have exactly the same and not only with fruux, but also with my infomaniak account (which I tried half a year ago).

I use Zorin OS 16.2.

**Comment by comminutus** [comment]
I have the same issue, on Ubuntu 22.04

**Comment by rpallai** [comment]
FYI seems like there is a solution: https://github.com/alainm23/planner/issues/897#issuecomment-1246689540

**Comment by alainm23** [comment]
CalDAV support is under development for Planify, I will close this issue until the implementation is done. thank you.
