### ISSUE TITLE
Today and Upcoming are not working V2

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#91]
**Describe the bug**
Today and Upcoming view are not showing anything

**To Reproduce**
open the app

**Expected behavior**
Show the taks that match the date of Today.
Show the tasks that are upcoming in the week

**Screenshots**
![Screenshot from 2019-11-06 08 36 51](https://user-images.githubusercontent.com/26935602/68317802-9b4be180-0070-11ea-9a1a-0cd58597ab7c.png)
![Screenshot from 2019-11-06 08 36 47](https://user-images.githubusercontent.com/26935602/68317807-9c7d0e80-0070-11ea-9abd-6ff276befff9.png)

**Desktop (please complete the following information):**
 - Elementary Juno 5
 - Version 2

**Additional context**

**Comment by alainm23** [comment]
Hehehe, I still want to finish the Project Page and then I will work on this.

By the way, What do you think about the new project progress widget? Do you speak Spanish too?

**Comment by Hedronmx** [comment]
Looks pretty good!! I am loving planner v2!

Btw, will it take too long for this to be implemented? Thats the only thing keeping me from using planner full time.

**Comment by alainm23** [comment]
I can't give you a date, but I will try to work on this.

**Comment by Hedronmx** [comment]
You are awesome!! Thank you for your time! And don't rush it.

**Comment by alainm23** [comment]
- [x] Today
- [ ] Upcoming

**Comment by Hedronmx** [comment]
Testing today view at the moment. Looks good!! Thank you so much

**Comment by alainm23** [comment]
Yes, but I feel that Today is very empty and lifeless, any idea to improve it? I plan to add calendar events.

**Comment by Hedronmx** [comment]
Maybe you can create sections with the name of the projects. Like this mockup
Also this would fix #94 

![planner](https://user-images.githubusercontent.com/26935602/68429300-a848fd80-0162-11ea-8bf9-c72c8a448a86.png)

**Comment by alainm23** [comment]
It's a very good idea, this will take me more time but I like it.

**Comment by Hedronmx** [comment]
No worries, take your time. 
Looking at the mockup, on the right side there could be a sidebar with the calendar events.

**Comment by Hedronmx** [comment]
Btw you can just use the sections you have designed in the project view. Just change the label to the project name. That would look good too

**Comment by alainm23** [comment]
### Today Works!!!

![image](https://user-images.githubusercontent.com/33765137/68449811-a9a41580-01b6-11ea-8cbf-8fe8fa4cff17.png)

I want you to give me your opinion. What do I have to do if we are in Today's view and I change or delete the date for a task?

What I do is wait a few seconds and delete the task automatically.

**Comment by Hedronmx** [comment]
That works! Also, for the upcoming view, the sections should be like in todoist which show the next 5 days. So the sections would be, Tomorrow, then for example, saturday, sunday, etc...

That way when you change the task day it can move to the appropriate section or disappears if its outside the 5 day window.

~~Another thing, the today view should also have the overdue tasks in their own section, which are the task that have a a date but they are not completed yet.~~

edit-
I just cloned the repo and the today view already shows the overdue tasks! that's good!

**Comment by alainm23** [comment]
Great, today I will start working on Upcoming view.

**Comment by alainm23** [comment]
This is my idea for the Upcoming view, we can get the dates dynamically when the user collides with the end of the Scrolled. Ideas?

![planner-upcoming](https://user-images.githubusercontent.com/33765137/68521858-45935700-0273-11ea-9c05-7e1e534686f6.gif)

**Comment by alainm23** [comment]
I decided to use a button to get more tasks.

![today-upcoming](https://user-images.githubusercontent.com/33765137/68523752-7c756700-028b-11ea-85ad-bd5ad568e60e.png)

**Comment by Hedronmx** [comment]
Se ve increíble! Gracias!!!
