### ISSUE TITLE
Not able to open the settings menu on flatpak version

### ISSUE THREAD

**Issue by AnishDe12020** [alainm23/planify#910]
**Describe the bug**
Can't open the settings window

**To Reproduce**
Make sure to use Flatpak version (haven't tried others). Login with Todoist and try to open the settings menu.

**Expected behavior**
The settings menu should open

**Desktop (please complete the following information):**
 - OS or DE: Pop! OS 21.10
 - Version: 3.0.8

**Comment by guglovich** [comment]
I have no Todoist settings at all. It's strange that there are so many versions of the functionality.
