### ISSUE TITLE
Russian translate

### ISSUE THREAD

**Issue by guglovich** [alainm23/planify#912]
Hello. As I see on the translations page, Russian is almost ready, but I don't even see the settings to switch the language in the application. I assume the switch should have happened automatically depending on the system language? If so, it didn't work for me. 
https://hosted.weblate.org/projects/planner/translations/ru/

elementary-planner-3.0.7

**Comment by alainm23** [comment]
Translations for Planify are done from the repository

https://github.com/alainm23/planify/tree/master/po
