### ISSUE TITLE
It looks awful on Pop!_OS 22.04 LTS

### ISSUE THREAD

**Issue by BenHerbst** [alainm23/planify#913]
![grafik](https://user-images.githubusercontent.com/83538916/174117379-494d03b2-3f7d-44fd-afa2-eaee6d71336f.png)

**Comment by AlbusPercivalDumbledore** [comment]
> ![grafik](https://user-images.githubusercontent.com/83538916/174117379-494d03b2-3f7d-44fd-afa2-eaee6d71336f.png)

Think installing Elementary Icons & Stylesheet would solve this issue. Links here: https://github.com/alainm23/planner#building

**Comment by BenHerbst** [comment]
> > ![grafik](https://user-images.githubusercontent.com/83538916/174117379-494d03b2-3f7d-44fd-afa2-eaee6d71336f.png)
> 
> Think installing Elementary Icons & Stylesheet would solve this issue. Links here: https://github.com/alainm23/planner#building

Should not work as Flatpak is a container. It would be easy if Planner would be also avaible as Appimage etc. I dont want to build Planner myself. Then why even publish it on Flathub when the theme only works on Elementary. Then only publish on the Elementary Flatpak and say it is only for Elementary users. A lot of Planner users do not use Elementary. The simplest solution would be to just downgrade.
Update:
There is no elementary Stylesheet in apt, and I installed Elementary icons but as I said above, cause container it does not work. Then I would have to build it my self, or use an Appimage version but there is only the Flathub...

**Comment by AlbusPercivalDumbledore** [comment]
> Should not work as Flatpak is a container

You could try installing Elementary theme from flathub:

`flatpak install org.gtk.Gtk3theme.elementary`

Also, Planner 2.6.9 is available as .deb here, if you wanna consider it: http://packages.elementary.io/appcenter/pool/main/c/com.github.alainm23.planner/

Requires libgranite 5.5.0, and a few other dependencies though, so you'd have to add a couple of repos:
```
deb http://cz.archive.ubuntu.com/ubuntu impish main universe
deb http://security.ubuntu.com/ubuntu bionic-security main
```
