### ISSUE TITLE
CalDAV support in local network

### ISSUE THREAD

**Issue by habibi-hapti** [alainm23/planify#914]
**Is your feature request related to a problem? Please describe.**
I have a Radicale CalDAV server running in my local network and I would like to use it to synchronize my tasks. However, Planner will neither accept a URL like something.local nor the IP address of my home server like 192.168.xxx.yyy. 

**Describe the solution you'd like**
Planner should accept common URL formats for local networks.

**Comment by alainm23** [comment]
CalDAV support is under development for Planify, I will close this issue until the implementation is done. thank you.
