### ISSUE TITLE
Keyboard Shorcuts in CalDAV Task LIsts

### ISSUE THREAD

**Issue by X-pech** [alainm23/planify#915]
**Describe the bug**
Today I decided to give Planner a try as a client for CalDAV Tasks from Nextcloud. Tasks lists are here, all the tasks are here and successfully sync with the server. 
I loved the way Todoist is keyboard-centered with many shortcuts and language-parsing so I looked for keyboard shorcuts first and then tried using them but some of them including "add task" `a` shortcut are not working there. 

**To Reproduce**
1. Set up CalDAV sync (Nexcloud, Google Tasks, etc.)
2. Go to one of the CalDAV lists
3. Press `a` shorcut
4. Nothing happens

**Expected behavior**
Add task dialogue like in any local task list.

**Actual behavior**
Pain

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS x86_64 
 - DE: GNOME 42.1 
 - WM: Mutter 
 - Planner: 3.0.8 Flatpak

**Comment by alainm23** [comment]
CalDAV support is under development for Planify, I will close this issue until the implementation is done. thank you.
