### ISSUE TITLE
Top corners are still rounded when the application is maximized

### ISSUE THREAD

**Issue by snakedye** [alainm23/planify#916]
**Describe the bug**
When the window is maximized, the top right and left corners are still somewhat rounded.

**To Reproduce**
1. Maximize the window.

**Expected behavior**
The radius of all corners is 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/49378990/175310780-0d6fd8a7-10dc-4c17-8208-586f61b94a03.png)
![image](https://user-images.githubusercontent.com/49378990/175310835-16e69c18-8351-4f68-b00b-570a6f938eae.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/49378990/175310935-b60628ce-6072-44ab-8592-2abd44afac84.png)

**Additional context**

**Comment by alainm23** [comment]
Fixed in Planify 4.1
