### ISSUE TITLE
window decoration inconsistencies

### ISSUE THREAD

**Issue by semimqmo** [alainm23/planify#917]
**Describe the bug**
The minimize and maximize buttons don't conform to the selected gtk-theme, instead they are custom designs.
Especially the minimize button is unintuitive and out of place, because it ooks like a download button.

**To Reproduce**
Enable the minimize and/or maximize buttons.

**Expected behavior**
The buttons should look like they do on other apps and conform to the theme.

**Screenshots**
[standard theme](https://imgur.com/DTwbazQ)
[adw-gtk3-theme](https://imgur.com/0K3wbL2)

[expected button look](https://imgur.com/Av2Kgbo)

**Desktop (please complete the following information):**
 - OS or DE: Fedora 36, GNOME 42.2
 - Version: 3.0.8 (Flatpak)

**Comment by alainm23** [comment]
Fixed in Planify 4.1.
