### ISSUE TITLE
I can´t change language

### ISSUE THREAD

**Issue by marcoszy** [alainm23/planify#918]
**Describe the bug**

I really don´t know if this is a bug. But I can´t find a way to change the language in Planner for Brazilian Portuguese. The app on Linux works well, but only in english, and I can´t find an option to change it.

**Desktop (please complete the following information):**
 - OS or DE: Linux - KDE Plasma
 - Version 3.0.8

Thanks in advance for your help guys!

**Comment by alainm23** [comment]
Task Planner uses the default language of your system, probably this is not available, if this is the case you can help with the translation of Task Planner.

https://github.com/alainm23/planner/tree/master/po
