### ISSUE TITLE
No indication of recurrent taks or way to create them

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#92]
**Is your feature request related to a problem? Please describe.**
There is no way to create a recurrent task and if using Todoist, previously created recurrent task have no indication that they loop.

**Describe the solution you'd like**
Add a small loop icon next to the date or the task name.
Ability to set re-currency.

**Describe alternatives you've considered**
Create the task over and over again.

**Additional context**

**Comment by alainm23** [comment]
Duplicate #54
