### ISSUE TITLE
Can't find the option to repeat a task

### ISSUE THREAD

**Issue by robinsrk** [alainm23/planify#920]
**Describe the bug**
Can't find the option to repeat a task weekly or daily or any other option.

**To Reproduce**
1. Create task
2. Click on schedule
3. No option for repeating the task

**Expected behavior**
There should be an option for repeating the task

**Screenshots**
Couldn't add screenshot as when trying to capture the screen, the schedule tooltip disappears

**Desktop (please complete the following information):**
 - OS or DE: Arcolinux plasma
 - Version: 3.0.7

**Comment by jahinzee** [comment]
Same issue here; using the Flatpak on Fedora 36.
![image](https://user-images.githubusercontent.com/56011682/179716159-2bb9c8a7-fbdb-4c4b-9723-ea4c52b3922e.png)

**Comment by IceM4n43** [comment]
Did you find a solution?

**Comment by alainm23** [comment]
Fixed in the new version of Task Planner
