### ISSUE TITLE
Hide accounts without lists

### ISSUE THREAD

**Issue by azmeuk** [alainm23/planify#923]
I use planner in a regular session, with a dozen accounts plugged with gnome-online-accounts. However only a few of those accounts have task lists. It would be nice to be able to hide the other accounts so interface would be clearer.

![Capture d’écran du 2022-07-21 12-20-39-obfuscated](https://user-images.githubusercontent.com/60163/180192511-198845d4-8740-4671-9986-fe9e90ac4a5e.png)

**Comment by alainm23** [comment]
CalDAV support is not yet available in Planify 4.1, I will close this issue for that, it will be taken into account when implementing CalDAV.
