### ISSUE TITLE
Selecting Todoist Integration Impossible: settings screen only flashes on startup

### ISSUE THREAD

**Issue by stockphrase** [alainm23/planify#924]
I'm on the flatpak version of the latest Planner. When I first set up Planner I did not select an integration with Todoist. However, now I would like to. The problem is that when I start up Planner, the option to connect to Todoist flashes on the screen for a split second, then disappears. It is not possible to access this setting otherwise, it seems.

**Comment by ItsJ0el** [comment]
I have the same issue with the AUR Package version 3.0.7-1 of Planner

**Comment by ItsJ0el** [comment]
#925 is about the same issue

**Comment by alainm23** [comment]
Fixed in the new version of Task Planner
