### ISSUE TITLE
Planner(flatpak) doesn't sync existing Todoist projects and tasks contained within them

### ISSUE THREAD

**Issue by the1derer** [alainm23/planify#927]
**Describe the bug**
Planner doesn't sync existing Todoist projects and tasks contained within them. I can only see tasks inside 'Inbox'. I have installed Planner via flathub.

**To Reproduce**
1. Create a new Todoist account from browser.( I have created account via Google Sign-in, if that matters)
2. Install Planner via flathub flatpak
3. Sing-in to your Todoist account on first launch of Planner.
4. See error that no Projects that is in Todoist account has synced.

**Expected behavior**
All Projects should sync.

**Screenshots**
Todoist in browser(3 Projects can be seen):
![Screenshot from 2022-08-06 21-41-26](https://user-images.githubusercontent.com/31668258/183257071-1815f274-b7e7-40ab-ac54-869802baab79.png)

Planner after  Todoist Sync:
![image](https://user-images.githubusercontent.com/31668258/183257110-91e19ebd-608d-47a6-8f10-527fbfe25857.png)

**Desktop (please complete the following information):**
 - OS or DE: Pop!_OS (based on Ubuntu)
 - Version: 22.04

**Additional context**

**Comment by ghost** [comment]
Also, any new tasks created in planner is reflected in Todoist but any tasks created in Todoists (via my phone or on the website) is not shown in planner. 

I am also on flatpak on Pop_Os 22.04.

**Comment by dmatavel** [comment]
For me, the problem starts last week I think. What's odd because there wasn't any Planner flatpak updates since. Maybe the issue could be due to some Todoist  recent update. I sync my Todoist account without Google sign in, btw.

**Comment by Jakp3** [comment]
Same problem here, hope it will be fixed soon

**Comment by hrqmonteiro** [comment]
Same thing here.

Literally doesn't work. And that's annoying as hell. 
Planner just show blank stuff.

**Comment by jo-jstrm** [comment]
Same problem for me. PopOS  22.04, Planner installed via Flatpak, using Todoist account.

**Comment by fluxxen** [comment]
Same here.

Using flatpak on elementary OS 6.1 based on Ubuntu 20.04.5 LTS; Apple sign in

**Comment by hrqmonteiro** [comment]
Hello?

Will anyone look into this? Or the app will remain useless????

**Comment by mangz74** [comment]
Experiencing same issue using the AUR package in ArchLinux.  Hope this gets some visibility.

**Comment by hrqmonteiro** [comment]
> Experiencing same issue using the AUR package in ArchLinux. Hope this gets some visibility.

It will not. The developer doesn't give a damn about the users.

**Comment by mangz74** [comment]
Still nothing? Anything we can do to help fix this?
