### ISSUE TITLE
Support webkit2gtk-4.1 / evolution-data-server 3.45+ / libsoup-3

### ISSUE THREAD

**Issue by bobby285271** [alainm23/planify#928]
Starting with GNOME 43, some core components of the desktop have been ported to libsoup-3, which apparently brings a lot of new features, including HTTP/2 support. However, for libsoup-2.4 and libsoup-3, processes can only link against one version of the library **(even transitively)**, or there will be symbol clashes.

The effects of this are especially bad for planner. It links against evolution-data-server libraries (which have been ported to libsoup-3 as of e-d-s 3.45.1) and webkit2gtk-4.0, which is the WebKitGTK library for use with libsoup-2.4. As a result, planner no longer builds with e-d-s 3.45+ because vala is trying to link against both libsoup-2.4 and libsoup-3. Here is the full log: https://gist.github.com/bobby285271/365f09a7c06195c2f432e7b7f7adca27

It will be really nice to have support for webkit2gtk-4.1 and e-d-s 3.45+ so we can still build this properly with them.

**Comment by tim77** [comment]
Planner failed to build on Fedora 37+. Package will be retired soon due of that.

Full [build.log](https://github.com/alainm23/planner/files/9585605/build.log).

**Comment by bobby285271** [comment]
We are also marking this as broken in NixOS. Sadly many Pantheon packages are affected in the libsoup 3 migration and I really don't know much about how to help port them and all I can do is try to update `meson.build` and replace all `Soup.URI` with `GLib.Uri`. For this package, I would really appreciate some suggestions on how to handle those `libgdata` stuff (so we can unbreak [elementary-tasks](https://github.com/elementary/tasks/issues/340) as well).

**Comment by ElnuDev** [comment]
Any news on this? elementary-planner is still marked as broken in NixOS's nixpkgs...

**Comment by yochananmarqos** [comment]
@alainm23 Closing issues like this makes no sense as you neither merged the planner-gnome branch into master nor created a new release.

**Comment by bobby285271** [comment]
Sorry, this got lost in my notifications, other than https://github.com/alainm23/planner/pull/985 the `master` branch builds fine, but yeah having a tag will be nice:

- https://github.com/NixOS/nixpkgs/pull/230983

The `planner-gnome` branch is using `webkit2gtk-5.0` which is gone after WebkitGTK 2.40, it has to be ported to `webkitgtk-6.0` first (which is already done in `master` branch) if that is the base branch of future releases.

**Comment by alainm23** [comment]
I haven't created a new version yet because I would like to send something stable.

**Comment by ElnuDev** [comment]
Shouldn't this issue be reopened until then?
