### ISSUE TITLE
Move a task from a list to another

### ISSUE THREAD

**Issue by dabrain34** [alainm23/planify#935]
**Is your feature request related to a problem? Please describe.**
I created a task in my local list and I'd like to move it to an online list (ie caldav account)

**Describe the solution you'd like**
Be able to drag and drop or offer a drop down list with the other tasks group (account or folder)

**Describe alternatives you've considered**
Rewrite the tasks and delete 

**Additional context**

**Comment by alainm23** [comment]
CalDAV support is under development for Planify, I will close this issue until the implementation is done. thank you.

**Comment by afuetterer** [comment]
Is this possible in Planify 4.5? I am struggling with moving a task from list A to B, using nextcloud lists. Should I open a new issue?
