### ISSUE TITLE
Autosave tasks during new task creation

### ISSUE THREAD

**Issue by tim-den-dulk** [alainm23/planify#937]
**Is your feature request related to a problem? Please describe.**
I often create several tasks at once. I start writing down one task, and when i'm finished, i click on the "add task" button to start on my next task. This does not save the previous tasks, but instead cancels anything i wrote down. 
Similarly, if halfway through writing a new task I want to select another task, or add a new label, i lose the work on the new task i was doing.

**Describe the solution you'd like**
When writing a new task, If i click away(e.g. to create anohter new task, or to select a different task) i would like the task i was writing to be saved.

**Describe alternatives you've considered**
Autosave could be an extra option that can be turned off or on.
Alternatively, one might have a warning pop up if work would be deleted.

**Additional context**

**Comment by alainm23** [comment]
We could work in the same way as Things 3 does, create the task by clicking the "+" button instead of pressing the Save button and confirming the task creation.

**Comment by alainm23** [comment]
I feel this is no longer a problem, the way to add task change to a modal, reopen the problem if you feel it can still be improved.
