### ISSUE TITLE
Show project name like a label.

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#94]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the project name as a label, that way no matter in which view you are, you know to which project the task belongs to.

**Describe the solution you'd like**
To automatically create a label or show the name of the project the task belongs.

**Describe alternatives you've considered**
Manually create a label with the name of the project.

**Additional context**

**Comment by Hedronmx** [comment]
Could you add a small square or maybe change the color of the font  to the color projects color?

**Comment by alainm23** [comment]
In the last compilation I added the name of the project to the tasks in Upcoming. Do you mean this?

![image](https://user-images.githubusercontent.com/33765137/68565351-37833900-0421-11ea-8417-8e290619fe8e.png)

**Comment by Hedronmx** [comment]
Yes! could you add a small colored square or similar to how you display tags. That way each project name pops more.

**Comment by alainm23** [comment]
Sure but tomorrow, now I have to sleep 😅️

**Comment by Hedronmx** [comment]
No problem man! You are doing amazing work, Ill sure donate some more cash later this week!
