### ISSUE TITLE
Todoist sync crashes and no tasks

### ISSUE THREAD

**Issue by tejasraman** [alainm23/planify#940]
**Describe the bug**
If I log in with Todoist, the app crashes and shows no tasks (occasionally one task).

**To Reproduce**
1. Open Planner
2. Use a Todoist sync account

**Expected behavior**
It syncs and shows all my tasks

**Desktop (please complete the following information):**
 - OS or DE: Fedora 36 + KDE - Kernel 5.19.12, KDE 5.25 (Maybe 5.26  but I don't think so)

@alainm23 do you know why this started happening? It nerved happened on gnome before (that was >4 months ago)

**Comment by AnirudraChoudhury** [comment]
I am facing the same issue in Gnome 3.38..6
I am using Debian 11 With Gnome desktop environment kernal version 5.10.0-19-amd64

**Comment by tejasraman** [comment]
So not a KDE issue. Hmmmm.

**Comment by tejasraman** [comment]
It seems like the dev isn't active anymore though

**Comment by tejasraman** [comment]
tysm @alainm23 

I'll test this once I have access to my desktop again... I'm away from home for 2 weeks on vacation.
