### ISSUE TITLE
Task settings appear at fixed, offset position

### ISSUE THREAD

**Issue by semdner** [alainm23/planify#942]
**Describe the bug**
If you right-click on a task, the task settings will open at a fixed, offset position. Regardless of the window size, the position of the settings remains the same.

**To Reproduce**
1. Go to a Project
2. Right-click on task
4. See problem

**Expected behavior**
The task settings should be close to the task and not appear at the same position when resizing the window.

**Video**
https://user-images.githubusercontent.com/56640416/197151051-6897da9c-ae45-4b71-8582-8fcebe8bfbde.mp4

**Desktop:**
 - Fedora 36 (Gnome 42.4)
 - Planner Version 3.0.8

**Comment by alainm23** [comment]
Fixed in the new version of Task Planner
