### ISSUE TITLE
Local task list's color when services' backend prevent from changing task list's color

### ISSUE THREAD

**Issue by vepain** [alainm23/planify#943]
## Issue

Services like google don't want to change the colour of task lists:
> Updating the list color is not supported for 'google' backends.

## Proposition

Catching the error and allowing the user to change the colour (locally)
However, the colour will not be sync.

---
Thank you for your really cool application!

**Comment by alainm23** [comment]
CalDAV support is under development for Planify, I will close this issue until the implementation is done. thank you.
