### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by unityblessedme** [alainm23/planify#945]
**Describe the bug**
I've just tried to build project myself/install from AUR on arch, this bug appeared both cases.

**To Reproduce**
Just try to build / install and build from AUR

**Screenshots**
![image](https://user-images.githubusercontent.com/56166443/200398589-cb827b07-d37a-419c-8629-40af49958d7d.png)

**Desktop Arch linux:**

**Comment by deeedob** [comment]
same! any progress on this?

**Comment by unityblessedme** [comment]
> same! any progress on this?

After a few tries to build up from sources, i've installed this package via flatpack

**Comment by alainm23** [comment]
We are working on the migration to GTK4 and using the default Gnome theme, with this this problem will be solved.

**Comment by alainm23** [comment]
Fixed in the new version of Task Planner
