### ISSUE TITLE
Allow resizing of the sidebar

### ISSUE THREAD

**Issue by creative-brain** [alainm23/planify#946]
I suggest to allow user to resize the side-panel. Some user defined project names could get quite long and currently it is a bit indistinct. This should be an easy fix.

**Comment by alainm23** [comment]
It's an important feature, but I still don't know how to do it, unless it works next to the hide sidebar function.

**Comment by alainm23** [comment]
This functionality is now available in the new Planify update. Preferences -> Appearances -> Sidebar Width
