### ISSUE TITLE
Typo "addd subtask"

### ISSUE THREAD

**Issue by BarbzYHOOL** [alainm23/planify#947]
Typo on button "addd subtask" there are 3 "d"

**Comment by jacopotediosi** [comment]
Already fixed by 980618c42eb169b68cee8e0644bbab010b9e6fd3

**Comment by BarbzYHOOL** [comment]
you're right but the latest release on flathub is 3.0.8 and on github is 3.0.7...

https://flathub.org/apps/details/com.github.alainm23.planner
