### ISSUE TITLE
Ctrl+Enter should validate the current task (actually forced to use the mouse)

### ISSUE THREAD

**Issue by BarbzYHOOL** [alainm23/planify#948]
**Is your feature request related to a problem? Please describe.**
When creating a task, there is no way to validate the task without using the mouse when cursor is inside the description field. Very annoying. 

**Describe the solution you'd like**
Ctrl+Enter should logically validate the task. Also Ctrl+Tab should skip to the next element but it is not working when inside the description field

**Describe alternatives you've considered**

**Additional context**

**Comment by alainm23** [comment]
It will be available in Planify 4.5 this weekend.
