### ISSUE TITLE
Dates marked inside the app don't update on todoist V2

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#95]
**Describe the bug**
When creating a task and setting a date, the date is not synced to todoist.

**To Reproduce**
create a task and set a date, then open todoist client and check that the date is missing

**Expected behavior**
To sync all dates

**Screenshots**
![Screenshot from 2019-11-08 00 08 33](https://user-images.githubusercontent.com/26935602/68460140-ee7e7b00-01bb-11ea-92bd-e309d6946aa9.png)

**Desktop (please complete the following information):**
 - OS or DE: Juno v5
 - Version 2

**Additional context**

**Comment by alainm23** [comment]
This error has already been fixed.
