### ISSUE TITLE
Gnome Planify Icon

### ISSUE THREAD

**Issue by alainm23** [alainm23/planify#953]
Planner 3.1 is being ported to Gtk4 and using libadwaita instead of the elementary project themes and icons.

We currently have great progress but we need to change the icon as well.

If you have any ideas for improvement or let me know, I will be very happy to see it.

**Comment by igor-dyatlov** [comment]
And what would you like to see on the icon? I wouldn't use a tablet like GTG and Endeavour (ex GNOME To-Do)
I would use something similar to the mac Things app, but I would change the colors. To increase awareness

![fghfghfgh d](https://user-images.githubusercontent.com/15961107/205444463-e058937f-cec4-416c-a632-1013840cb52c.png)

How about a new name? To avoid confusion by the project https://gitlab.gnome.org/World/planner
A new library. New name, new icon?

> Each app icon should have a simple, recognizable metaphor. Ideally this should have a clear and obvious relationship with the [app name](https://developer.gnome.org/hig/guidelines/app-naming.html).

https://developer.gnome.org/hig/guidelines.html

**Comment by alainm23** [comment]
Thanks, I like the icon but as you say, it looks a lot like the Things icon and I would prefer to avoid that similarity. 
Regarding the name, it is correct, we will probably have problems when entering the Gnome Circle, I will create a new issue for this change.

**Comment by igor-dyatlov** [comment]
That's what I wrote about. Suddenly, after entering the Gnome Circle, you will need to change the name. And the new name is a new metaphor and icon. And maybe you need to solve the problem with the name first, and then the icon?

![plan](https://user-images.githubusercontent.com/15961107/205501375-d91ab815-597a-4b7d-9e62-bfd2da0818c4.png)

I tried to change the color to red like a Todoist. And added a texture for a piece of paper. Already looks more recognizable. Not enough ideas for the main element in the center of the icon, maybe you have?

**Comment by bertob** [comment]
I took a quick stab at just adapting the current metaphor to the GNOME style, but it's a bit boring:

![image](https://user-images.githubusercontent.com/1908896/205922168-7b8e112b-44bb-41a4-a2ee-efcb45f68ee3.png)

The inbox metaphor is probably nicer, but it needs some kind of check to be recognizable as a todo app.

**Comment by igor-dyatlov** [comment]
The name of the Target 🎯 may work ![Предварительный просмотр](https://user-images.githubusercontent.com/15961107/209392460-28f4dd90-2bc6-4f7b-be66-c408e36a694a.png)

**Comment by RusticBard** [comment]
A journal icon I made, let me know what you think

![image](https://user-images.githubusercontent.com/120028833/217000957-ec0ebaa2-3c3b-4087-8307-31e369c2fd8a.png)

**Comment by alainm23** [comment]
I like the idea, although I had thought to do something simpler, improving the original icon but adding a little more detail (improve the borders, gradient colors, improve the design of the cross, etc), this is my idea.

Note that Planner was renamed to **Task Planner** for future versions.

![image](https://user-images.githubusercontent.com/33765137/217026490-2f86ca16-d8d7-49ea-ad31-407c98ca7d54.png)

**Comment by RusticBard** [comment]
I see, thanks for letting know :)

**Comment by bertob** [comment]
@alainm23 something in this direction?

![image](https://user-images.githubusercontent.com/1908896/219975196-1709b308-6e06-4a5e-9e45-efaf07940d33.png)

**Comment by alainm23** [comment]
We are on the right track, I really like the design, I don't know much about icon design, but maybe we could add some gradient or shadows like the camera or music icon. For the rest it's a great job, thank you very much.

**Comment by bertob** [comment]
An attempt to make it look more fun with different colors:

![image](https://user-images.githubusercontent.com/1908896/220502306-4497c382-1d07-4810-aaea-c91539595176.png)

**Comment by alainm23** [comment]
Sorry for late reply, I just released Planify in beta version by Flathub.
https://github.com/alainm23/planify#flathub-beta

@bertob It looks good, but maybe the palette could be improved a bit and not be too flat, I'm open to various ideas and changes, since Planify is a new app that uses gtk and libadwaita.

**Comment by bertob** [comment]
I tried adding some depth to the last proposal, but IMO this would work fine without any chin. We could try other things, but I think this would work well for now.

![image](https://github.com/alainm23/planify/assets/1908896/0a36802a-3a8c-4eda-a22c-45cd8178cdbf)

**Comment by alainm23** [comment]
@bertob It looks much better, could you create a PR by updating the current icon please, thanks.
