### ISSUE TITLE
Rename Project

### ISSUE THREAD

**Issue by alainm23** [alainm23/planify#954]
As you know we are updating the project to Gnome instead of elementary, using Gtk4 and libadwaita, our intention is to give better support to this technology and obtain better benefits for users. One of those improvements is to apply to Gnome Circle, and we probably need to change the name to avoid confusion with the other Gnome [Planner ](https://wiki.gnome.org/action/show/Apps/Planner?action=show&redirect=Planner) project. These are some of my ideas:

- [ ] Check
- [ ] Task Planner
- [ ] Done
- [ ] Planny

If you have any ideas let me know.

**Comment by igor-dyatlov** [comment]
One of the names is already taken [Done](https://flathub.org/apps/details/dev.edfloreshz.Done)

More ideas:
- [ ] Effort
- [ ] Exercise
- [ ] Involved
- [ ] Process
- [ ] Purpose
- [ ] Target 🎯

**Comment by literalEval** [comment]
I have a question though. Why was Gtk chosen instead of Qt ? 😅

**Comment by hcal** [comment]
Task Kraken - Get to Kraken
Gnome Productive
Gnome Hustle
Gnome Do It

Done / Gnome Done gets my vote.

**Comment by rurigk** [comment]
> I have a question though. Why was Gtk chosen instead of Qt ? sweat_smile

Try to search documentation about Vala and QT

**Comment by ghost** [comment]
@hcal + @alainm23  Without permission from GNOME board, you cannot use GNOME brand anymore :(

More information:
- https://gitlab.gnome.org/GNOME/Initiatives/-/issues/35
- https://discourse.gnome.org/t/official-proposal-how-we-define-gnome-software/3371

**Comment by alainm23** [comment]
What do you think of **PlanIt**?

**Comment by michael-rapp** [comment]
Happy to hear about the plan to migrate to GTK/libadwaita. Here are a few suggestions for a new name:
* Tasks
* Goals
* Ambitions
* Milestones

With regard to the previously mentioned names, I would personally prefer "Check". "Task planner" also seems appealing, as it is close to the original name.

**Comment by Julian4711** [comment]
Can't wait for the libadwaita beta :)
Namewise, what do you think about:
* Backlog
* Agenda
* Things to be Done (TBD)

**Comment by alainm23** [comment]
@michael-rapp  @Julian4711 Thank you very much for your contribution, the port to gtk4 and libadwaita is almost finished, there are not many changes in the interface, although I am trying to align myself with the design styles of Gnome HIG.

**Comment by alainm23** [comment]
In the end I decided that the new name for Planner will be Task Planner, the idea is not to move away so much from the original name, so we keep the domain and the brand.
