### ISSUE TITLE
Planner crashes when I create a new project

### ISSUE THREAD

**Issue by njds823jndsj8** [alainm23/planify#955]
I have been unable to build elementary-planner 3.0.7-1 on Manjaro (getting errors about libedata shared objects), so installed it using flatpak. Whenever I try to create a new project, planner crashes. I click on 'Add project' and it crashes, every time. I'm able to add both labels and  items, just not projects.

**Comment by stollr** [comment]
In my case it works without issues. But i am using local planning, not CalDAV or Todoist - maybe that makes a difference...
