### ISSUE TITLE
planner 3.0.7 compil fail

### ISSUE THREAD

**Issue by PowaBanga** [alainm23/planify#956]
**Describe the bug**
compilation fail on Archlinux.

**To Reproduce**
Open a terminal, download PKBUILD from AUR, enter in the folder and do a makepkg to start compilation
the most of errors are like 
```
Compilation failed: 114 error(s), 2 warning(s)
```
the most of errors are like 
```
libsoup-3.0.vapi:7.3-7.62: error: `Soup.Form' already contains a definition for `decode'
    7 | 		public static GLib.HashTable<weak string,weak string> decode (string encoded_form);
```

my long too long to be posted here. So it is [here](https://pastebin.com/raw/4ZY77AXv)
any ideas how to fix this ?

**Comment by pav00** [comment]
Yes, the last successful compile under Archlinux was in May 2022. I used planner under Archlinux successfully, it stopped working around September, after Archlinux upgrades, probably no longer compatible with the current libraries. Would it be possible to upgrade planner to the latest libraries so it is possible to use it under Archlinux again? Thanks.

**Comment by Jarodiv** [comment]
Same issue with Gentoo Linux (not surprisingly as this seems to be a general issue with compiling it on up to date systems).

**Comment by alainm23** [comment]
Planner is being ported to Gtk4 and libadwaita, a beta version is close to being released.

**Comment by pav00** [comment]
Thanks guys, planner is the best application in its class; if you want to achieve the same functionality without planner you would have to go a grade higher like redmine. When you port to a different platform could you (at least initially) keep the structure of tables in SQLite the same so that the data can be used without migration if possible.

**Comment by alainm23** [comment]
Fixed in the new version of Task Planner
