### ISSUE TITLE
Ergonomy is really lacking

### ISSUE THREAD

**Issue by BarbzYHOOL** [alainm23/planify#960]
There are several bugs or non optimal things

Do you plan on improving those? i'm really on the verge of switching to something else, it's just too time consuming to use it, having to remember each "bug"

example: you're creating a new task, you alt+tab to copy a link, you come back, the task you took 3 minutes to write has totally disappeared. I have to remember to click "create task" before alt+tab

**Comment by alainm23** [comment]
Fixed in the new version of Task Planner
