### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by rayklaus** [alainm23/planify#969]
**Describe the bug**

when I build in arm64, It's going someing wrong ,the log is here.
$ meson build
The Meson build system
Version: 0.53.2
Source dir: /data/code/tools_bak/planner-3.0.6
Build dir: /data/code/tools_bak/planner-3.0.6/build
Build type: native build
Project name: com.github.alainm23.planner
Project version: 3.0.6
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-10kylin2) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Vala compiler for the host machine: valac (valac 0.48.3)
Host machine cpu family: aarch64
Host machine cpu: aarch64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Configuring config.vala using configuration
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency glib-2.0 found: YES 2.64.2
Run-time dependency gobject-2.0 found: YES 2.64.2
Run-time dependency gee-0.8 found: YES 0.20.3
Run-time dependency granite found: YES 5.3.0
Run-time dependency gtk+-3.0 found: YES 3.24.23
Run-time dependency sqlite3 found: YES 3.31.1
Run-time dependency json-glib-1.0 found: YES 1.4.4
Run-time dependency webkit2gtk-4.0 found: YES 2.28.1
Run-time dependency libhandy-1 found: YES 1.5.0
Library m found: YES
Program build-aux/meson/post_install.py found: YES (/usr/bin/python3 /data/code/tools_bak/planner-3.0.6/build-aux/meson/post_install.py)
Build targets in project: 11

Found ninja-1.10.0 at /usr/bin/ninja
admin@:/data/code/tools_bak/planner-3.0.6$ cd build
admin@:/data/code/tools_bak/planner-3.0.6/build$ ninja
[6/106] Compiling Vala source ../src/Util.vala ../src/Application.vala ../src/Ma...ard.vala ../src/Objects/Scheduled.vala ../src/Objects/Reminder.vala config.vala.
FAILED: com.github.alainm23.planner@exe/src/Util.c com.github.alainm23.planner@exe/src/Application.c com.github.alainm23.planner@exe/src/MainWindow.c com.github.alainm23.planner@exe/src/Layouts/Sidebar.c com.github.alainm23.planner@exe/src/Layouts/FilterPaneRow.c com.github.alainm23.planner@exe/src/Layouts/HeaderItem.c com.github.alainm23.planner@exe/src/Layouts/LabelRow.c com.github.alainm23.planner@exe/src/Layouts/ItemRow.c com.github.alainm23.planner@exe/src/Layouts/ProjectRow.c com.github.alainm23.planner@exe/src/Layouts/ViewHeader.c com.github.alainm23.planner@exe/src/Layouts/SectionRow.c com.github.alainm23.planner@exe/src/Layouts/LabelChild.c com.github.alainm23.planner@exe/src/Layouts/SectionChild.c com.github.alainm23.planner@exe/src/Widgets/Entry.c com.github.alainm23.planner@exe/src/Widgets/DynamicIcon.c com.github.alainm23.planner@exe/src/Widgets/TodoistSync.c com.github.alainm23.planner@exe/src/Widgets/ProjectProgress.c com.github.alainm23.planner@exe/src/Widgets/EditableLabel.c com.github.alainm23.planner@exe/src/Widgets/TopHeaderProject.c com.github.alainm23.planner@exe/src/Widgets/ColorPopover.c com.github.alainm23.planner@exe/src/Widgets/MagicButton.c com.github.alainm23.planner@exe/src/Widgets/HyperTextView.c com.github.alainm23.planner@exe/src/Widgets/LoadingButton.c com.github.alainm23.planner@exe/src/Widgets/ProjectButton.c com.github.alainm23.planner@exe/src/Widgets/PinButton.c com.github.alainm23.planner@exe/src/Widgets/IconColorProject.c com.github.alainm23.planner@exe/src/Widgets/ItemSummary.c com.github.alainm23.planner@exe/src/Widgets/ScheduleButton.c com.github.alainm23.planner@exe/src/Widgets/PriorityButton.c com.github.alainm23.planner@exe/src/Widgets/LabelButton.c com.github.alainm23.planner@exe/src/Widgets/ItemLabels.c com.github.alainm23.planner@exe/src/Widgets/ItemLabelChild.c com.github.alainm23.planner@exe/src/Widgets/Placeholder.c com.github.alainm23.planner@exe/src/Widgets/SubItems.c com.github.alainm23.planner@exe/src/Widgets/ReminderButton.c com.github.alainm23.planner@exe/src/Widgets/Calendar/Calendar.c com.github.alainm23.planner@exe/src/Widgets/Calendar/CalendarDay.c com.github.alainm23.planner@exe/src/Widgets/Calendar/CalendarHeader.c com.github.alainm23.planner@exe/src/Widgets/Calendar/CalendarView.c com.github.alainm23.planner@exe/src/Widgets/Calendar/CalendarWeek.c com.github.alainm23.planner@exe/src/Views/Welcome.c com.github.alainm23.planner@exe/src/Views/Project.c com.github.alainm23.planner@exe/src/Views/List.c com.github.alainm23.planner@exe/src/Views/Today.c com.github.alainm23.planner@exe/src/Views/Date.c com.github.alainm23.planner@exe/src/Views/Pinboard.c com.github.alainm23.planner@exe/src/Views/Scheduled/Scheduled.c com.github.alainm23.planner@exe/src/Views/Scheduled/ScheduledHeader.c com.github.alainm23.planner@exe/src/Views/Scheduled/ScheduledDay.c com.github.alainm23.planner@exe/src/Views/Label.c com.github.alainm23.planner@exe/src/Views/Board.c com.github.alainm23.planner@exe/src/Dialogs/TodoistOAuth.c com.github.alainm23.planner@exe/src/Dialogs/Project.c com.github.alainm23.planner@exe/src/Dialogs/Label.c com.github.alainm23.planner@exe/src/Dialogs/MessageDialog.c com.github.alainm23.planner@exe/src/Dialogs/QuickFind/QuickFind.c com.github.alainm23.planner@exe/src/Dialogs/QuickFind/QuickFindItem.c com.github.alainm23.planner@exe/src/Dialogs/QuickFind/Synapse.c com.github.alainm23.planner@exe/src/Dialogs/ReminderPicker/ReminderPicker.c com.github.alainm23.planner@exe/src/Dialogs/ReminderPicker/ReminderRow.c com.github.alainm23.planner@exe/src/Dialogs/Settings/Settings.c com.github.alainm23.planner@exe/src/Dialogs/Settings/SettingsHeader.c com.github.alainm23.planner@exe/src/Dialogs/Settings/SettingsContent.c com.github.alainm23.planner@exe/src/Dialogs/Settings/SettingsItem.c com.github.alainm23.planner@exe/src/Dialogs/ProjectPicker/ProjectPicker.c com.github.alainm23.planner@exe/src/Dialogs/ProjectPicker/ProjectRow.c com.github.alainm23.planner@exe/src/Dialogs/ProjectPicker/SectionRow.c com.github.alainm23.planner@exe/src/Dialogs/DateTimePicker/DateTimePicker.c com.github.alainm23.planner@exe/src/Dialogs/DateTimePicker/TimePicker.c com.github.alainm23.planner@exe/src/Dialogs/LabelPicker/LabelPicker.c com.github.alainm23.planner@exe/src/Dialogs/LabelPicker/LabelRow.c com.github.alainm23.planner@exe/src/Dialogs/ContextMenu/Menu.c com.github.alainm23.planner@exe/src/Dialogs/ContextMenu/MenuItem.c com.github.alainm23.planner@exe/src/Dialogs/ContextMenu/MenuItemSelector.c com.github.alainm23.planner@exe/src/Dialogs/ContextMenu/MenuSeparator.c com.github.alainm23.planner@exe/src/Dialogs/ContextMenu/MenuCalendarPicker.c com.github.alainm23.planner@exe/src/Dialogs/ContextMenu/MenuSwitch.c com.github.alainm23.planner@exe/src/Dialogs/Shortcuts/Shortcuts.c com.github.alainm23.planner@exe/src/Dialogs/Shortcuts/ShortcutLabel.c com.github.alainm23.planner@exe/src/Services/EventBus.c com.github.alainm23.planner@exe/src/Services/Database.c com.github.alainm23.planner@exe/src/Services/Todoist.c com.github.alainm23.planner@exe/src/Services/ActionManager.c com.github.alainm23.planner@exe/src/Services/Badge.c com.github.alainm23.planner@exe/src/Services/Notification.c com.github.alainm23.planner@exe/src/Objects/v2.c com.github.alainm23.planner@exe/src/Objects/BaseObject.c com.github.alainm23.planner@exe/src/Objects/Project.c com.github.alainm23.planner@exe/src/Objects/Label.c com.github.alainm23.planner@exe/src/Objects/Section.c com.github.alainm23.planner@exe/src/Objects/Item.c com.github.alainm23.planner@exe/src/Objects/Color.c com.github.alainm23.planner@exe/src/Objects/DueDate.c com.github.alainm23.planner@exe/src/Objects/ItemLabel.c com.github.alainm23.planner@exe/src/Objects/Today.c com.github.alainm23.planner@exe/src/Objects/Pinboard.c com.github.alainm23.planner@exe/src/Objects/Scheduled.c com.github.alainm23.planner@exe/src/Objects/Reminder.c com.github.alainm23.planner@exe/build/config.c 
valac -C --debug --debug --pkg libhandy-1 --pkg webkit2gtk-4.0 --pkg json-glib-1.0 --pkg sqlite3 --pkg gtk+-3.0 --pkg granite --pkg gee-0.8 --pkg gobject-2.0 --pkg glib-2.0 --color=always --directory com.github.alainm23.planner@exe --basedir ../ --gresources=../data/com.github.alainm23.planner.gresource.xml ../src/Util.vala ../src/Application.vala ../src/MainWindow.vala ../src/Layouts/Sidebar.vala ../src/Layouts/FilterPaneRow.vala ../src/Layouts/HeaderItem.vala ../src/Layouts/LabelRow.vala ../src/Layouts/ItemRow.vala ../src/Layouts/ProjectRow.vala ../src/Layouts/ViewHeader.vala ../src/Layouts/SectionRow.vala ../src/Layouts/LabelChild.vala ../src/Layouts/SectionChild.vala ../src/Widgets/Entry.vala ../src/Widgets/DynamicIcon.vala ../src/Widgets/TodoistSync.vala ../src/Widgets/ProjectProgress.vala ../src/Widgets/EditableLabel.vala ../src/Widgets/TopHeaderProject.vala ../src/Widgets/ColorPopover.vala ../src/Widgets/MagicButton.vala ../src/Widgets/HyperTextView.vala ../src/Widgets/LoadingButton.vala ../src/Widgets/ProjectButton.vala ../src/Widgets/PinButton.vala ../src/Widgets/IconColorProject.vala ../src/Widgets/ItemSummary.vala ../src/Widgets/ScheduleButton.vala ../src/Widgets/PriorityButton.vala ../src/Widgets/LabelButton.vala ../src/Widgets/ItemLabels.vala ../src/Widgets/ItemLabelChild.vala ../src/Widgets/Placeholder.vala ../src/Widgets/SubItems.vala ../src/Widgets/ReminderButton.vala ../src/Widgets/Calendar/Calendar.vala ../src/Widgets/Calendar/CalendarDay.vala ../src/Widgets/Calendar/CalendarHeader.vala ../src/Widgets/Calendar/CalendarView.vala ../src/Widgets/Calendar/CalendarWeek.vala ../src/Views/Welcome.vala ../src/Views/Project.vala ../src/Views/List.vala ../src/Views/Today.vala ../src/Views/Date.vala ../src/Views/Pinboard.vala ../src/Views/Scheduled/Scheduled.vala ../src/Views/Scheduled/ScheduledHeader.vala ../src/Views/Scheduled/ScheduledDay.vala ../src/Views/Label.vala ../src/Views/Board.vala ../src/Dialogs/TodoistOAuth.vala ../src/Dialogs/Project.vala ../src/Dialogs/Label.vala ../src/Dialogs/MessageDialog.vala ../src/Dialogs/QuickFind/QuickFind.vala ../src/Dialogs/QuickFind/QuickFindItem.vala ../src/Dialogs/QuickFind/Synapse.vala ../src/Dialogs/ReminderPicker/ReminderPicker.vala ../src/Dialogs/ReminderPicker/ReminderRow.vala ../src/Dialogs/Settings/Settings.vala ../src/Dialogs/Settings/SettingsHeader.vala ../src/Dialogs/Settings/SettingsContent.vala ../src/Dialogs/Settings/SettingsItem.vala ../src/Dialogs/ProjectPicker/ProjectPicker.vala ../src/Dialogs/ProjectPicker/ProjectRow.vala ../src/Dialogs/ProjectPicker/SectionRow.vala ../src/Dialogs/DateTimePicker/DateTimePicker.vala ../src/Dialogs/DateTimePicker/TimePicker.vala ../src/Dialogs/LabelPicker/LabelPicker.vala ../src/Dialogs/LabelPicker/LabelRow.vala ../src/Dialogs/ContextMenu/Menu.vala ../src/Dialogs/ContextMenu/MenuItem.vala ../src/Dialogs/ContextMenu/MenuItemSelector.vala ../src/Dialogs/ContextMenu/MenuSeparator.vala ../src/Dialogs/ContextMenu/MenuCalendarPicker.vala ../src/Dialogs/ContextMenu/MenuSwitch.vala ../src/Dialogs/Shortcuts/Shortcuts.vala ../src/Dialogs/Shortcuts/ShortcutLabel.vala ../src/Services/EventBus.vala ../src/Services/Database.vala ../src/Services/Todoist.vala ../src/Services/ActionManager.vala ../src/Services/Badge.vala ../src/Services/Notification.vala ../src/Objects/v2.vala ../src/Objects/BaseObject.vala ../src/Objects/Project.vala ../src/Objects/Label.vala ../src/Objects/Section.vala ../src/Objects/Item.vala ../src/Objects/Color.vala ../src/Objects/DueDate.vala ../src/Objects/ItemLabel.vala ../src/Objects/Today.vala ../src/Objects/Pinboard.vala ../src/Objects/Scheduled.vala ../src/Objects/Reminder.vala config.vala
../src/Layouts/ItemRow.vala:380.9-380.9: error: syntax error, expected identifier
        };
        ^
../src/Layouts/ItemRow.vala:387.47-387.47: error: syntax error, `new' modifier not allowed on creation method
        actionbar_revealer = new Gtk.Revealer () {
                                              ^
../src/Layouts/ItemRow.vala:393.41-393.41: error: syntax error, `new' modifier not allowed on creation method
        subitems = new Widgets.SubItems (item);
                                        ^
../src/Layouts/ItemRow.vala:395.34-395.34: error: syntax error, `new' modifier not allowed on creation method
        main_grid = new Gtk.Grid () {
                                 ^
../src/Layouts/ItemRow.vala:405.42-405.42: error: syntax error, `new' modifier not allowed on creation method
        main_revealer = new Gtk.Revealer () {
                                         ^
../src/Widgets/SubItems.vala:46.9-46.9: error: syntax error, expected identifier
        };
        ^
../src/Widgets/SubItems.vala:49.43-49.43: error: syntax error, `new' modifier not allowed on creation method
        checked_listbox = new Gtk.ListBox () {
                                          ^
../src/Widgets/SubItems.vala:59.49-59.49: error: syntax error, `new' modifier not allowed on creation method
        var checked_listbox_grid = new Gtk.Grid () {
                                                ^
../src/Widgets/SubItems.vala:64.45-64.45: error: syntax error, `new' modifier not allowed on creation method
        checked_revealer = new Gtk.Revealer () {
                                            ^
../src/Widgets/SubItems.vala:71.38-71.38: error: syntax error, `new' modifier not allowed on creation method
        var main_grid = new Gtk.Grid () {
                                     ^
../src/Widgets/SubItems.vala:79.42-79.42: error: syntax error, `new' modifier not allowed on creation method
        main_revealer = new Gtk.Revealer () {
                                         ^
../src/Widgets/SubItems.vala:156.78-156.78: error: syntax error, `new' modifier not allowed on creation method
                        items_checked [item.id_string] = new Layouts.ItemRow (item);
                                                                             ^
../src/Widgets/SubItems.vala:167.70-167.70: error: syntax error, `new' modifier not allowed on creation method
                        items [item.id_string] = new Layouts.ItemRow (item);
                                                                     ^
Compilation failed: 13 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
admin@:/data/code/tools_bak/planner-3.0.6/build$

**Comment by alainm23** [comment]
I'll close this issue because Planify is only officially distributed by Flathub, however, could you please build the project again and report back if it's crashing, thanks.
