### ISSUE TITLE
Planner's self-conception & Add a plugin system to handle integrations

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#97]
**Is your feature request related to a problem? Please describe.**

On his project page Planner writes about himself "Todoist Client designed for elementary OS". My request would be that Planner does not define itself through a commercial and proprietary external service, but promotes itself as a Free Software solution for project/task management, offering interfaces for external services where these are useful and possible.
**So this is an issue about ethics and self-conception.**

Especially because Planner also works locally and with GitHub already offers an integration to other services. **Perhaps this issue is also about wording.**

**Describe the solution you'd like**

Planner already has a GitHub integration https://github.com/alainm23/planner/issues/25, an integration for GitLab is on the wishlist already https://github.com/alainm23/planner/issues/78 and a support for Todoist https://github.com/alainm23/planner/issues/41 is work in progress.

My idea would be that Planner becomes first and foremost a local app, and handles the aforementioned integrations in the form of plugins, which users can consciously add/enable if they want to use external services. By default, there should be no connection to external providers through the app. In this sense, **my concern is also about data protection, privacy and security.**

Maybe it just needs something like a plugin system to handle integrations?

A plugin system would focus on the possible variety of interfaces that Planner currently already supports or can support in the future.
Community users and developers should be able to easily add/remove their own integrations or create new ones.

I understand this issue as an open invitation to discuss my thoughts and ideas with people who want to use Planner 2 as intensively as I do.

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 How do you feel about this idea? By the way, thank you for working on Planner!

**Comment by alainm23** [comment]
I like the idea but I want to make Planner a powerful software but limited to integration functionalities. This with the idea of making a good task manager and only that. I changed the project description on Github.

**Comment by alainm23** [comment]
I will close this issue because this channel is only for bug reports and feature requests.
