### ISSUE TITLE
Allow CalDav Lists and Todoist sync to coexist

### ISSUE THREAD

**Issue by rohmishra** [alainm23/planify#971]
**Is your feature request related to a problem? Please describe.**
Whens setting up Planner for fist time, you can either select CalDAV or Todoist for online sync. Currently only one can be used at a time.

I am trying out todoist and am liking it for planning out projects, larger tasks, etc. But I still use Google Tasks through Lists for smaller errands, one-off task, simple repeating tasks, etc. 

While calender can still be synced with google accounts, using Planner doesn't allow Task Lists to be added or synced. 

**Describe the solution you'd like**

Allow Task lists from CalDAV and Local list to be connected and synced alongside Todoist.

**Describe alternatives you've considered**
None - I resort to using Google Tasks on my phone.

**Additional context**

**Comment by zickzackzuck** [comment]
this affects me too: Want to move away from Todoist and switch to Nextcloudbased Task Managment...

**Comment by alainm23** [comment]
This was fixed in Planify, it allows to use local accounts like Todoist, CalDAV support is under development for Planify, I will close this issue until the implementation is done. thank you.
