### ISSUE TITLE
Planner planning features and gnome integration

### ISSUE THREAD

**Issue by JLT032** [alainm23/planify#972]
**Is your feature request related to a problem? Please describe.**
Planner offers a reasonably good interface to quickly jot down things, it does not integrate well with gnome in my experience. At this point planner obsoletes itself because the fine details are not available and not showing up in gnome calendar for example.

**Describe the solution you'd like**
Have planner on-board the planning features in-sync with gnome evolution calendar/tasks so events show up in the calendar.

**Describe alternatives you've considered**
moving away from planner as I'm looking for an easy tool to work with, not a tool in the way of working with other applications (such as gnome calendar, gnome evolution etc)

**Additional context**
I'd also appreciate non-flatpak releases of planner.

Planner looks promising, please take the above as constructive input.

**Comment by Hedronmx** [comment]
New gtk4 version is coming and it will integrate better to gnome

**Comment by alainm23** [comment]
Planner is being migrated to Gtk4 and libadwaita, a beta version is about to be released.
