### ISSUE TITLE
Removing CalDAV Accounts Found From Evolution DELETES Them From Evolution

### ISSUE THREAD

**Issue by deron-dev** [alainm23/planify#974]
**Describe the bug**
When I remove accounts that were found from my Evolution config, they are deleted. Evolution no longer contains them.

**To Reproduce**
1. Install planner flatpak
2. Run
3. Go to Settings > Synchronization > CalDAV
4. Remove auto-detected accounts

**Expected behavior**
Those accounts are no longer included in planner, and I can still access them from Evolution.

**Desktop (please complete the following information):**
Desktop:
```
OS: Manjaro Linux x86_64 
Kernel: 6.1.12-1-MANJARO 
DE: Xfce 4.18 
WM: Xfwm4 
```
Planner:
```
          ID: com.github.alainm23.planner
         Ref: app/com.github.alainm23.planner/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.0.10
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 133.6 MB
     Runtime: org.gnome.Platform/x86_64/42
         Sdk: org.gnome.Sdk/x86_64/42

      Commit: 743b1feef78c1fc2fc82beafbb4341482b159d0c7449cfbab2cf46bc3c779f5c
      Parent: e2dd3427178a4373c18a2a59610996481f57841fecb18555f9239da5bd6e9d35
```

**Comment by alainm23** [comment]
El soporte para CalDAV esta en desarrollo para Planify, cerrare este problema hasta que la implementacion este hecha. gracias.
