### ISSUE TITLE
Some Feature request for planner

### ISSUE THREAD

**Issue by gnurichard** [alainm23/planify#975]
Hello! I have time using Planner. Unlike many Planner users I use it in Cinnamon and Gnome not in pantheon. I know that this usually goes against elementaryOS design decisions but, I miss a tray icon that notifies me if I have pending tasks and indicates that the software is running in the background. I think it would be a useful feature for all of us who use Planner in non-Pantheon environments. I also think it would be very useful to be able to synchronize tasks with other task management services such as mycrosoft To Do, or even taskwarrior. Also, the option to integrate the tasks to the calendar (gnome-calendar or better google-calendar)

**Comment by alainm23** [comment]
Hello, let me tell you that Planner is now Planify and is written in gtk4 and libadwaita and gives exclusive support to the GNOME desktop. On the other hand, many of the things that they comment are in development. I will close this issue to keep things in order and I would ask you to create an issue for each problem or feature request next time, thanks.
