### ISSUE TITLE
random blue bar

### ISSUE THREAD

**Issue by danbryan** [alainm23/planify#976]
Curious, Any idea where is this blue bar coming from?  none of my other apps have it.   Is this coming from `planner`, or my window manager?  I'm new to qtile, but have not been able to track down where this is coming from.

 I'm using flatpak stable
```
~ flatpak list |grep planner
Planner	com.github.alainm23.planner	3.0.10	stable	system
➜   ~
```
![image](https://user-images.githubusercontent.com/807940/226195018-6bb77e5e-8100-4dd9-82f1-32ef2285cbd3.png)

**Comment by alainm23** [comment]
Planner is now Planify and is written using gtk4 and libadwaita. Could you check if the problem still persists please, thank you.

https://flathub.org/es/apps/io.github.alainm23.planify
