### ISSUE TITLE
Update org.gnome.Platform runtime - end-of-life

### ISSUE THREAD

**Issue by aarondill** [alainm23/planify#977]
The GNOME 42 runtime is no longer supported as of March 21, 2023
```
Info: org.gnome.Platform//42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.github.alainm23.planner
```

**Comment by blaze-fire** [comment]
Kindly migrate, to prevent any security issues

**Comment by DreamHollow** [comment]
I have this issue as well.

Flatpak is still flagging Planner as running on the older GNOME environment.

**Comment by alainm23** [comment]
Planner is now Panify, Planner will no longer be supported, you could now use Planify and you won't have any problem with your information, because they are different applications.
