### ISSUE TITLE
TAB for jumping from Task Title to Task Description

### ISSUE THREAD

**Issue by chamaoskurumi** [alainm23/planify#978]
**Is your feature request related to a problem? Please describe.**
Currently I'm forced to use the mouse when adding Description information in a task.

**Describe the solution you'd like**
I would like to use `TAB` to jump from the Title to the Description. Here you can see the actual behavior - when `TAB` is pressed a big tab space is added.

https://user-images.githubusercontent.com/7808560/228251039-9659585f-3fca-4912-a5b5-e4d47bc0908b.mp4

**Describe alternatives you've considered**
Maybe some other keyboard shortcut would do as well...But `TAB` wuould be very natural I guess...

**Comment by alainm23** [comment]
This is already fixed in Planify 4.4, please update.
