### ISSUE TITLE
Suggestion for improvement

### ISSUE THREAD

**Issue by gargullia** [alainm23/planify#979]
There happens to be a big problem with to-do list apps on Linux.
I propose to make an interface like in the GTG and iPlan mockups

In the layout there are tasks in the list and tasks in the boards. If you take the best of all the apps, yours will be the most ultimative, beautiful and productive

It would also be nice to make everything on native widgets libadwaita. You are still using granite

![GTG_ui](https://user-images.githubusercontent.com/19420334/229196084-d87847f8-895b-466c-8fef-7176455cee95.svg)
![window](https://user-images.githubusercontent.com/19420334/229196753-7ce68f20-8ea0-4356-87b8-a4320ec59997.png)

Links:
https://github.com/getting-things-gnome/gtg/issues/737
https://github.com/iman-salmani/iplan

**Comment by alainm23** [comment]
Planner is now Planify and was rewritten in gtk4 and libadwaita.
