### ISSUE TITLE
Add a plus next to the option button on the sections to quickly add a task

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#98]
**Describe the solution you'd like**
Add a plus icon next to the 3 vertical dots icon in a section, so you can quickly add a task

**Describe alternatives you've considered**
Clicking the 3 vertical dots icon and the pressing the add task button

**Comment by alainm23** [comment]
This feature is already in the current version, you can open the menu and create a quick task. You can double click on the section and open the menu too.

**Comment by Hedronmx** [comment]
I know... what I am saying is to add a plus icon outside of the menu, right next to the menu icon. That way you can add task faster!

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/79255805-84de5900-7e4c-11ea-95e7-7263f6441b41.png)
