### ISSUE TITLE
"Add tasklist" for CalDAV server (radicale) has no effect in UI, though "New list" is added to server

### ISSUE THREAD

**Issue by ianrgraham** [alainm23/planify#983]
**Describe the bug**
When using a CalDAV server (radicale), clicking the "Add tasklist" button doesn't produce any change in the Planner UI. But exploring the server, it does indeed start a new tasklist called "New list". 

**To Reproduce**
1. Setup radicale server (https://radicale.org/v3.html#getting-started) and expose to internet
2. Add server to Planner (same machine, but using hostname)
3. Try to add a new tasklist to the server from the sidebar

**Expected behavior**
Tasklist should be added as is seen with "local" tasklists.

**Desktop (please complete the following information):**
 - OS or DE: Pop_OS 22.04
 - Version: 3.0.10 from Flathub

**Additional context**
I'd be happy to help with a fix here! Though some guidance would be appreciated!

**Comment by senesc** [comment]
It's the same for me with my radicale server (I even set up SSL and trusted my own CA) on Flathub version 3.0.10 and Arch Linux.
I'll attach the output of `G_MESSAGES_DEBUG=all com.github.alainm23.planner`
[planner.log](https://github.com/alainm23/planner/files/11463037/planner.log)

**Comment by alainm23** [comment]
CalDAV support is under development for Planify, I will close this issue until the implementation is done. thank you.
