### ISSUE TITLE
Quck add command returns error "Settings schema 'com.github.alainm23.planner3' is not installed"

### ISSUE THREAD

**Issue by ajvillarroel-leroy** [alainm23/planify#989]
**Describe the bug**
After installing from flatpak, the app runs fine, but the quick-add command fails.

**To Reproduce**
1. Install: flatpak install flathub com.github.alainm23.planner
Finish ok
2. Then run quick-add: flatpak run --command=com.github.alainm23.planner.quick-add com.github.alainm23.planner
Error:
process:2): GLib-GIO-ERROR **: 20:03:58.916: Settings schema 'com.github.alainm23.planner3' is not installed

**Expected behavior**
Open quick-add

**Screenshots**

**Desktop (please complete the following information):**
 - OS or DE: [e.g. pantheon, unity, gnome]: 
 Ubuntu 22.10, with standard gnome shell

**Additional context**

**Comment by alainm23** [comment]
Hello, Quick Add is available in Planify 4.1, a keyboard shortcut preset is required (Until Global Keyboard portal is available) by the end user. Greetings.

https://flathub.org/es/apps/io.github.alainm23.planify
