### ISSUE TITLE
There are still syncing issues with Todoist

### ISSUE THREAD

**Issue by Hedronmx** [alainm23/planify#99]
**Describe the bug**
Some tasks are not updated when completed, some other tasks are not being synced when created. Syncing is hit or miss

**To Reproduce**
Use multiple clients to check the syncing

**Expected behavior**
To all clients having the same tasks.

**Screenshots**
![Screenshot from 2019-11-14 22 07 43](https://user-images.githubusercontent.com/26935602/68920802-4c1a4680-072b-11ea-8cc8-aadcb54f1710.png)
![Screenshot from 2019-11-14 22 08 15](https://user-images.githubusercontent.com/26935602/68920803-4c1a4680-072b-11ea-8392-44778d02cb23.png)

**Desktop (please complete the following information):**
 - Juno EOS
 - Version Latest master

**Comment by Hedronmx** [comment]
You could add a sync now button on the settings window. Maybe this could help?

How are you syncing right now? Since it seems some tasks are synced and some are not

**Comment by Hedronmx** [comment]
Any updates on this? Thanks!

**Comment by alainm23** [comment]
Yes, te responderé en español ya que así podre ser mas claro con mis ideas. 
- La sincronización en Planner por el momento solo es al inicio de ingresar tus credenciales de Todoist y cada vez que actualizas algo (Proyecto, tareas).
Esto es bueno siempre y cuando solo uses tu cuenta de Todoist desde Planner pero si usas Todoist desde otra plataforma (Android, Web) la sincronización no se vera reflejada en Planner.

- Para solucionar esto voy a crear un servicio de actualización en Planner que verifique cada n segundos o minutos alguna actualización desde el servidor en Todoist.

**Comment by Hedronmx** [comment]
Creo que una solución más sencilla sería agregar un botón de sincronizar, porque incluso al usar las aplicaciones oficiales de todoist se llegan ha desincrozinar, pero con el botón se sincroniza todo de nuevo.

Las pruebas que hice fueron con dos ordenadores usando elementary, cada una con planner instalado.

**Comment by alainm23** [comment]
Vale, si también tenia en cuenta lo de agregar un botón de sincronización al costado de buscar y las preferencias y una animación girando cada vez que la sincronización este en proceso. Por cierto las búsquedas rápidas ya están disponibles en la ultima versión del repositorio, las puede probar ya. Aun hay algunas cosas que mejorar pero para un primer lanzamiento creo que esta bien.

**Comment by Hedronmx** [comment]
Excelente! Esta muy chula la aplicación! Este es el único problema antes de usar planner al 100%.

Probaré la nueva versión. Muchas gracias!

**Comment by alainm23** [comment]
Por cierto si quiere abrir las búsquedas rápida le puede dar click al botón o usando el teclado Ctrl + F

**Comment by Hedronmx** [comment]
Vale! Espero con ansias la próxima actualización!

**Comment by alainm23** [comment]
Acabo de actualizar esta caracteristica, Dele click al boton de sincronizar y sus proyectos y secciones se actualizaran, por el momento las tareas solo se sincronizan al crear una tarea, cambiar el nombre y moverlos de seccion a seccion (Esta ultima es la mas complicada asi que intentare terminarlo este fin de semana).

Por cierto por el momento la sincronizacion solo es manual (dandole click al boton). SI encuentras algun error, avisame pls.

**Comment by Hedronmx** [comment]
Parece que no se sincronizan las tareas...
Agrego un vídeo como ejemplo
https://gfycat.com/uncommonpolisheddouglasfirbarkbeetle

```
{"full_sync":false,"temp_id_mapping":{},"labels":[],"project_notes":[],"filters":[],"sync_token":"sdQxS1wM9cocR66_dZMDV51dp4fqoCTc5Qhuoj9GySnZwouf0PM6LpwbOkF0bpXr9oaQiqjgbd6NljCJ2TeYvidvUjJ0Nim0XF9GAT2THvkEnQ","day_orders":{},"projects":[],"collaborators":[],"day_orders_timestamp":"1575585641.9","live_notifications_last_read_id":2266089948,"items":[],"notes":[],"reminders":[],"due_exceptions":[],"live_notifications":[],"sections":[],"collaborator_states":[]}

```

**Comment by alainm23** [comment]
@Hedronmx  en el codigo que me envio se ve que no hay ninguna tarea creada que Planner pueda procesar. A probado con volver a correr Planner borrando la base de datos e iniciando nuevamente con Todoist?

**Comment by Hedronmx** [comment]
Ya la borré, parece ser que había un error. Ahora funciona perfecto!

**Comment by alainm23** [comment]
Hola, voy a cerrar este problema ya que es muy general, recordarle que el soporte para Todoist Offline ya trabaja y la sincronizacion tambien.

**Comment by Hedronmx** [comment]
Si perfecto, la aplicación va muy bien! Me corre excelente!

**Comment by Hedronmx** [comment]
Aún hay problemas de sincronización
![image](https://user-images.githubusercontent.com/26935602/72774313-ffd20380-3bbe-11ea-959b-79e816d93d2b.png)

**Comment by alainm23** [comment]
Si definitivamente y gracias por tu observacion pero solo una imagen no es suficiente. me gustaria que puedas ser un poco mas detallado e intentar reproducir el problema, de esa forma se podria solucionar mas rápido.

**Comment by Hedronmx** [comment]
Cómo puedo darte logs o de qué manera puedo hacer mejor el reporte?

Sigue sucediendo de la misma manera, le doy completar a las tareas y no se actualiza en todoist, o cambio las fechas y no se actualiza.

Le doy en el botón de actualizar e igual no se actualizan.

A veces, dandole Kill a planner, se actualiza pero sólo al iniciar de nuevo el programa

**Comment by alainm23** [comment]
- Y al editar el contenido de una tarea (el nombre) a tenido problemas?
- Tiene una buena conexión de internet?
- Podría confirmar que esto solo pasa al completar y actualizar las fechas de una tareas?

**Comment by Hedronmx** [comment]
1. Probando esto me di cuenta, que al presionar el boton de sincrozinar, sólo descarga la información, no la envía. Tendré que esperar 15 minutos para que se actualice en todoist.
Al editar el nombre por si solo, no se actualiza de manera "Inmediata"

2. Si, no tengo problemas con mi internet. Siempre pruebo la aplicación con mi laptop o mi ordenador.

3. Es con lo que más lo he notado. Debo hacer más pruebas. Aunque falló al desarchivar un proyecto desde todoist, no aparecía el proyecto en planner hasta que hice kill y volví a lanzar el programa.

**Comment by alainm23** [comment]
- Exactamente, el boton de sincronizar no sube la información, solo comprueba si hay cambios en el servidor.
- No tiene que esperar 15 min para que los cambios se actualicen en el servidor. al agregar, editar o eliminar una tarea, proyecto o sección esta se actualiza automáticamente en Todoist.
- Planner no soporta el archivamiento de un Proyecto o Sección aun.

**Comment by alainm23** [comment]
Me estaba olvidando de algo. Cuantas veces ejecuta alguna operación con Todoist por minuto? con una operación me refiero a crear, editar o eliminar ya sea una proyecto, sección o tarea. Todoist limita el uso de su API a 60 de estas operaciones por minuto. Tal vez esta sea la causa de por que no se actualiza.

**Comment by Hedronmx** [comment]
No pues solo completo las tareas cada 10 20 hasta 1 hora entre cada tarea.

De qué otra manera puedo ayudarte?

**Comment by Hedronmx** [comment]
No sé si yo soy el único con el problema pero me falla muchísimo la sincronización
