### ISSUE TITLE
planner can't sync with disroot

### ISSUE THREAD

**Issue by mohammadRezaeian** [alainm23/planify#991]
hi
when i trying connect planner to disroot in fedora  with flatpak i have this error but in debian it's ok and work fine

** (com.github.alainm23.planner:2): CRITICAL **: 20:45:27.966: CalDAV.vala:53: Unable to connect to “myuser”: Backend factory for source “5221833a394bf78d8b12d6badba2bdf9435c4b30” and extension “Task List” cannot be found.

** (com.github.alainm23.planner:2): CRITICAL **: 20:45:27.966: TasklistRow.vala:162: Error creating view with query for source myuser[(contains? 'any' '')]: No client available for task list 'myuser'

**Comment by alainm23** [comment]
CalDAV support is under development for Planify, I will close this issue until the implementation is done. thank you.
