### ISSUE TITLE
option CalDAV and crash select start week

### ISSUE THREAD

**Issue by mohammadRezaeian** [alainm23/planify#993]
Hi 
Now it's very beautiful thanks 
But why dropping support CalDAV?
And when I trying set start of week it's crashed
And please add  Saturday in menu select
Thanks.

**Comment by alainm23** [comment]
Support for CalDAV is under development, we are working on a new own service independent of EDS. The beginning of the week thing is an error that is being fixed.

**Comment by shvchk** [comment]
@alainm23 please drop a comment here when CalDAV support in Planify lands :pray:

**Comment by alainm23** [comment]
Este error a sido solucionado en Planify 4.1, aunque aun no es posible cambiar el dia de la semana por defecto.

**Comment by shvchk** [comment]
@alainm23 I've upgraded to 4.1.1 via Flatpak, but there's no CalDAV option in Preferences → Accounts, only Todoist.

OS: Kubuntu 23.04
DE: KDE Plasma

**Comment by alainm23** [comment]
It's true, the new CalDAV client for Planify is still under development, soon new news.

**Comment by bepolymathe** [comment]
Any news for caldav support ?
