### ISSUE TITLE
A way to make tasks stay upon completion 

### ISSUE THREAD

**Issue by GhostInThePC** [alainm23/planify#994]
**Is your feature request related to a problem? Please describe.**
Whenever I check something off, it disappears after a certain amount of time.

**Describe the solution you'd like**
A extra option in the tasks settings, probably under "Settings > General Settings >  Task Settings > Complete Task". The menu there would now contain this: Instantly, Wait 2500 Milliseconds, and Never. You select never, and any task you check off stays there forever, still checked off, still visible.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by alainm23** [comment]
It's an interesting prospect, but currently Planify keeps created and completed tasks in different sections, if you want your completed task to always be visible you can hit the 'View completed tasks' option.
