### ISSUE TITLE
Incorrect string in Scheduled screen 

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#995]
Hi, there is a small string error in the Scheduled screen. I think these strings come from another module. Which module do they come from?

![Ekran Görüntüsü - 2023-06-02 09-22-36](https://github.com/alainm23/planify/assets/6218679/65295264-b783-4b8e-b561-6e840ba1fbf1)

**Comment by alainm23** [comment]
This is a bit strange, it will be reviewed.

**Comment by alainm23** [comment]
I will close this issue because it is related to a problem with Gtk. Thank you.
