### ISSUE TITLE
Flatpak: Translated strings seem untranslated 

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#999]
I've just compiled the Planify to test my translation. Translated strings seem untranslated in Flatpak.

I used  the devel json (https://github.com/alainm23/planify/blob/master/build-aux/io.github.alainm23.planify.Devel.json)
 
 - OS or DE: Ubuntu 23.04 GNOME
 - Planner Version: From source code

**Comment by alainm23** [comment]
The build in development uses the latest sources in the repository, please try again, I just merged the translations you made.


![Captura desde 2023-06-02 04-12-00](https://github.com/alainm23/planify/assets/33765137/886ac61d-1b18-44ee-a472-3cb1c92625bc)

**Comment by ghost** [comment]
Hi, It worked when I remove this line: https://github.com/alainm23/planify/blob/master/build-aux/io.github.alainm23.planify.Devel.json#L136

**Comment by alainm23** [comment]
Of course, when commenting a line compile in production mode. Anyway, I'll check why that happens, thanks. I will close this issue because the main issue was closed.
